### ISSUE TITLE
Consider delivering a snap of eclipse che

### ISSUE THREAD

**Issue by popey** [eclipse-che/che#10051]
[snaps](https://snapcraft.io/) are "_containerised software packages that are simple to create and install._"

It would be awesome if che was available in the snap store. Snaps are easy to install and remove, both from the command line and within GNOME Software on the desktop. They contain the necessary dependencies to run, meaning they don't have to worry about host system library installation conflicts. They automatically update, so developers don't have a long tail of old releases to support. Developers and adventurous users can opt into a firehose of updates directly from your master branch if they choose.

Once built, one snap (per arch) can be installed on various Linux distributions including Ubuntu 14.04, 16.04,  18.04, Linux Mint, Fedora, OpenSUSE, Solus, Arch and others with no modification. There are numerous other features to snaps which make them compelling both for developers and users. 

There's a significant developer audience snaps cater to. There are already snaps for popular developer tools like [go](https://snapcraft.io/go), [kotlin](https://snapcraft.io/kotlin), [PyCharm](https://snapcraft.io/pycharm-professional), [Atom](https://snapcraft.io/atom), [VSCode](https://snapcraft.io/vscode) and of course, [eclipse](https://snapcraft.io/eclipse). There are thousands of users of those snaps.

We also love to promote snaps to users both as featured "Editor's Picks" in GNOME Software, on the [snapcraft.io](https://snapcraft.io/) home page, and via our social media channels.  

Disclaimer: I work on the snap advocacy team (as if you couldn't tell ;) ) and would love to help a Che developer get started.

**Comment by eivantsov** [comment]
@popey that's quite interesting. I have actually had a conversation about it with folks from Canonical at EclipseCon Europe last year.

Is there a how to guide for snap dummies like myself to take a look at?

**Comment by popey** [comment]
Hi @eivantsov thanks for the prompt response! :) 

We have some [docs](https://docs.snapcraft.io/) for [getting started](https://docs.snapcraft.io/build-snaps/) and specific docs per [language](https://docs.snapcraft.io/build-snaps/languages).

In a nutshell, snapcraft is typically the tool we use to assemble the snap. The resulting snap is built to run against a very minimal 16.04-based base image called 'core'. So it's currently recommended to build the snap on a 16.04 based system, either bare metal, or preferably a container (e.g. lxd) or virtual machine. Personally I use lxd, but a VM is just as good, to keep it clean. It's not a good idea to build on a developer laptop bare-metal because the snap may pull in other random libraries or PPAs which may be enabled.

I made a [video](https://www.youtube.com/watch?v=goHBeJSYSno) detailing how to setup builds. It's only ~30 mins or so. :) 

So I'd start with a 16.04 VM or lxd container and build in that. I had a go at prototyping a che build as a snap. I got as far as getting che building but then it fails at the end, I suspect when it tries to fire up a docker container to test the . I filed an issue #9178 back then, but we never quite figured out what's wrong with the way I'm building it. Maybe you'll have more luck with a snapcraft setup :)

Here is the snapcraft.yaml which could be used as a base. This has two parts, one (node) to grab a supported release of node, then the next part (che) builds che itself. It's incomplete but should make a good start point.

To use this in a 16.04 vm I would:-
1. Install snapcraft
```
snap install snapcraft --classic
```
2. Create 'che-snap' directory, and place the yaml below in it.
```
mkdir -p ~/che-snap/snap
vi ~/che-snap/snap/snapcraft.yaml
```
3. Try and build it
```
cd ~/che-snap/snap
snapcraft
```

This will likely fail in a similar way to how it did in issue #9178 . 

```
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-antrun-plugin:1.8:run (build-dashboard) on project che-dashboard-war: An Ant BuildException has occured: Replace: source file /root/build_che/parts/che/build/dashboard/target/dist/index.html doesn't exist
```

Happy to help here, or over on the [snapcraft forum](https://forum.snapcraft.io/), your irc/slack or wherever is best for you.

```
name: che
version: '6.6.2' 
summary: Eclipse CHE
description: |
  Next-generation Eclipse IDE. Open source workspace server and cloud IDE. 

grade: stable
confinement: strict

parts:
  che:
    after: [node]
    plugin: maven
    source: https://github.com/eclipse/che.git
    source-tag: '6.6.2'
    override-build: |
      mvn -e -DskipTests=true -Dfindbugs.skip=true -Dgwt.compiler.localWorkers=2 -T 1C -Dmdep.analyze.skip=true -Dlicense.skip=true -Pnative clean install
    build-packages:
      - golang
  node:
    plugin: nil
    override-build: |
      apt install -y apt-transport-https
      echo "deb https://deb.nodesource.com/node_9.x xenial main" | \
            sudo tee /etc/apt/sources.list.d/node.list
      curl --silent https://deb.nodesource.com/gpgkey/nodesource.gpg.key | apt-key add -
      apt-get update
      apt install -y nodejs
    prime: [-./*]
    build-packages:
      - curl

```
