### ISSUE TITLE
ws.next walking skeleton

### ISSUE THREAD

**Issue by l0rd** [eclipse-che/che#10123]
## Walking Skeleton Details

**Goal**: Integrate ws.next and theia plugin + introduce the plugin registry

**User Story 1**: As a Che developer I want to start a ws.next based workspace that is configured to load theia as the editor and an “hello world” frontend theia plugin (using an existing che stack from the dashboard and with the editor and plugins definition available in a remote plugin registry) so that I will be able to easily extend this model developing new theia plugins.

**User Story 2**: Same as Story 1 but instead of the “hello world” frontend theia plugin the workspace should be configured to load a backend Che plugin that includes a theia plugin part (frontend) so that I will be able to easily extend this model developing new che plugins.

**Success Criteria** The plugin registry is deployed on OSIO and rh-che is configured to use it. 2 new stacks (for Story1 and Story2) are available on rh-che and I can start a workspace based on both on OSIO.

**What’s in the walking skeleton** Support of 2 simple stories (not a feature complete IDE), 2 che stacks, works on Kubernetes, works on OSIO

**What’s not in the walking skeleton** A feature complete IDE, Self Hosting, Che Terminal, Java LS, Documentation, Performance tuning, UI components, ws.next Factories

**Target** 11 September

#### Packaging and Runtime

The registry is an http server (apache, nginx or whatever fits better) packaged as a docker image (will be `eclipse/che-plugin-registry` now it's `garagatyi/che-marketplace:os`). The docker image contains also the plugins metadata (for both Che plugins and Che editors). This list will be served statically by the apache server.

The Dockerfile (that defines the registry Docker image) and the plugins metadata will be in a repository `eclipse/che-plugin-registry`. A CI will build automatically the Docker image after each PR is merged (it can be the Docker hub autobuild for example).

For development purposes the registry can be started locally and in general anyone can start it's own registry in his infrastructure. For OpenShift.io we will run a Che plugin registry on DSAAS that will serve che.openshift.io.

#### Plugins (and Editor) Metadata

The plugins and editors metadata will be in some subfolders of the `plugins` folder of the git repository:

```
github.com/eclipse/che-plugin-registry/
    |
     --- plugins
            |
             --- che-jdt-ls       <- folder name matches the plugin id
                    |
                     --- 0.0.1    <- folder name matches plugin version
                          |
                           --- meta.yaml
```

The meta.yml file has the following format for a plugin

```yaml
id: che-jdt-ls
version: 0.0.1
type: Che Plugin   # can be `Che Plugin` or `Che Editor` 
name: che-java
title: Che Java Plugin
description: ...
icon: https://....
url: https://.... # this points to the URL of the tar.gz of the plugin (usually this is the plugin release URL on github)
```

**Note that both plugins and editors are under the `plugins` folder**

#### Contributing (adding a new plugin to the registry)

A plugin author can contribute to the plugin registry with a PR. He will need to add a new folder matching the plugin id and version. The folder should contain a meta.yaml file:

```
github.com/eclipse/che-plugin-registry/
    |
     --- plugins
            |
             --- che-jdt-ls
            | 
             --- che-hello-world
                        |
                         --- 0.0.1
                               |
                                --- meta.yaml
```

### The Che Plugin Packaging

Every Che plugin/editor should be packaged as a **tarball** + one or more **Docker images**. 

A **tarball** contains the following files:

- `che-plugin.yaml` (mandatory): the plugin details like the plugin containers, endpoints and theia plugins
- `dependencies.yaml` (only if the plugin has dependencies): the details of the plugin required dependencies (typically a list of theia plugins) 
- `example.theia` (only example.theia is a plugin's dependency): a theia plugin

```
che-hello-world.tar.gz
             |
              --- che.plugin.yaml
             |
              --- dependencies.yaml
             |
              --- hello-world.theia
```

The **docker image** contains the backend services (e.g. a language server) or command line tooling (e.g. kubectl or oc)

An example of che-plugin.yaml:

```yaml
endpoints:
 -  name: "hello-ls"
    public: true
    targetPort: 8080
containers:
 - name: che-hello
   image: eclipse/che-hello:nightly   #  <-- the plugin docker image
   env:
     - name: ENV1
       value: VAL1
   editor-commands:  #   <-- commands that should be visible in the editor (e.g. theia)
     - name: build
       working-dir: "$(project)"
       command: ["mvn", "clean", "install"] 
   volumes:
     - mountPath: "/projects"
       name: projects
   ports:
     - exposedPort: 8080
editors:  #   <-- list of editors plugins that should be loaded with this plugin  
   - id: org.eclipse.che.editor.theia
     plugins: [theia-hello-world:1.0.0]   # the format is id:version
   - id: org.eclipse.che.editor.jupyter
     plugins: [jupyter-hello-client, jupyter-hello2-client]
```

An example of `dependency.yaml`:

```yaml
plugins:
    - id: theia-hello-world
      version: 1.0.0 
      location: /theia-hello-world-v1.0.0.theia # use `location` if the plugin is included inside the tarball
      url: https://…                            # use `url` if the plugin is published as as a github project release
```

Notes:
- A Che plugin can contain only one Theia frontend plugin: in this case it won't have containers and endpoints
- For a Che editor it is basically the same except that it doesn't have dependencies (at least for now)

#### Configuration

The Che plugins and the Che editor of a workspace are defined as workspace attributes:

```json
"attributes": {
    "plugins": ["che-jdt-ls:1.0.0", "theia-hello-world:1.0.0"],
    "editor": "theia-ide:1.0.0"
}
```

The format of the plugins name is `<id>:<version>` where `id` and `version` are defined in the plugin `meta.yaml` 

#### Start

1. Download of the plugins and editor meta.yaml from the plugin registry
    The URL of the plugin registry should be a wsmaster property
2. Download and extract the plugins tarballs
3. Copy the editor plugins in a PV folder that will be shared with the editor container
4. Start the editor container (e.g. theia)
5. Start the plugins containers (e.g. jdt-ls)

## Subtasks

**OSIO team**

- [x] Workspace.next - CheService model adjustment #9964
- [x] Load Theia in Workspace.Next workspaces #9870
- [x] Service discovery of APIs running in tooling containers of Workspace.Next #9913
- [x] Update Che workspace config model: add CheEditor #10203    
- [x] Implement Plugin broker
- [x] Download Che Plugins and Editor meta.yaml and invoke Che Plugin Broker #10561
- [x] Update Che workspace config model: replace Feature/CheService with ChePlugin #10202 
- [x] Make che-plugin-broker push result to JSON_RPC of Che master #10878
- [x] Add an ability to use different PVC strategies in Walking skeleton instead of hardcoding behavior of common strategy #10879
- [ ] BONUS Support of RWX Mode and running containers in multiple pods

**IDE2 team**

- [x] Implement the theia-hello-world plugin. Package it as a .theia file. Publish it in a [github release](https://github.com/theia-demo-plugins/theia-frontend-plugin/releases)
- [x] Embed the [theia-hello-world plugin](https://github.com/theia-demo-plugins/theia-frontend-plugin/releases) inside a tar.gz + `che-plugin.yaml` + `dependency.yaml` and publish it in a repository
- [x] Package theia as a che-plugin #10648
- [x] Implement/Package che-hello-world plugin #10649
- [x] Create a Che Stack to support User Story 1
- [x] Create a Che Stack to support User Story 2

**PLATFORM team**

- [x] Move the Plugin Registry to its own repository #10615
- [x] Support multi-user Che #11071 
- [x] Setup a CI for the Plugin Registry #10651
- [x] Factory and stack features are not supported in Workspace.Next #10368
- [x] Deploy the Plugin Registry on OSIO #10652
- [x] Edit Workspace Attributes from the dashboard #10650
- [x] Move Plugin broker to start of Kubernetes runtime https://github.com/eclipse/che/issues/11042
- [x] Implement permissions support on Json/RPC calls #10861

**Comment by eivantsov** [comment]
@l0rd what is Che backend plugin? Is this a scenario where a backend plugin is a sidecar? If not, don't we want to target such a scenario?

**Comment by l0rd** [comment]
@eivantsov yes the scenario is about that. A che plugin that runs in a sidecar container and communicates with a theia plugin to provide the UI functionality (like a language server and its theia client).

What I wanted to stress is that the user need to specify one plugin only (`che-hello-world:1.0.0`) and this will be composed by a backend component (the che plugin) and a frontend (theia plugin).

**Comment by eivantsov** [comment]
@l0rd thanks. got it. SO, a feature, speaking in old fashioned ws.next terms :)

For such a scenario, there's one important dependency - Theia LSP client being able to connect to LS over host:port.

**Comment by l0rd** [comment]
Theia clients should contact a Che service using the Plugin [endpoint name](https://gist.github.com/l0rd/390bb13b2b8cc7697981dfc9da52f2ed#file-che-plugin-yml-L10). No port (port 80).

For this first scenario it's ok to hardcode the endpoint name in the theia client. We should make it a parameter to pass to the theia client in future iterations.

**Comment by eivantsov** [comment]
@l0rd not Che API (its clear that we have a plugin that provides such endpoints), but LS running in tcp mode. That would be the most interesting scenario - Che plugin bringing over Theia plugin + a sidecar.

**Comment by skabashnyuk** [comment]
A couple of remarks and changes.


## Marketplace content ##
```
theia-plugins/
	|---- theia-hello-world-v1.0.0
                  |---- meta.yaml
                  |---- theia-hello-world-v1.0.0.tar.gz
                           |---- package.json
                           |---- ......  
che-plugins/
	|---- theia-ide-v1.0.0/
	      |---- meta.yaml
	      |---- che-editor.yml

	|---- che-hello-world-v0.0.1/
	      |---- meta.yaml
	      |---- che-plugin.yml

````

Where 
<details/>
  <summary>che-plugin.yml</summary>

```yaml
version: 0.0.1
type: Che Plugin
name: che-hello-world
id: che-java
title: Che Hello plugin
description: ...
icon: https://....
endpoints:
 -  name: "hello-ls"
    public: true
    targetPort: 8080
containers:
 - name: che-hello
   image: eclipse/che-hello:nightly
   env:
     - name: ENV1
       value: VAL1
   editor-commands:
     - name: build
       working-dir: "$(project)"
       command: ["mvn", "clean", "install"] 
   volumes:
     - mountPath: "/projects"
       name: projects
   ports:
     - exposedPort: 8080
editors:
   - name: org.eclipse.che.editor.theia
     plugins: [theia-hello-world:1.0.0]
   - name: org.eclipse.che.editor.jupyter
     plugins: [jupyter-hello-client, jupyter-hello2-client]
```` 


</details>



<details/>
  <summary>che-editor.yml</summary>

```yaml
version: 1.0.0
type: Che Editor
name: org.eclipse.che.editor.theia
id: theia-ide
plugins: theia-plugins
title: Theia for Che
Description: ...
Icon: https://....
endpoints:
 -  name: "ide"
    public: true
    targetPort: 8080
containers:
 - name: theia-ide
   image: eclipse/che-editor-theia:nightly
   env:
       - name: theia-plugins
         value: file://plugins/
       - name: ENV1
         value: VAL1
   editor-commands:
      - name: reload-plugins
        working-dir: "$(plugins)"
        command: ["node", "reload"] 
   volumes:
       - mountPath: "/plugins"
         name: plugins
       - mountPath: "/project"
         name: project
    ports:
       - exposedPort: 8080
 ```      
</details>


## Notes ##
 - In a marketplace, our first level citizens are che-plugin and theia-plugin. That's why I would like to remove ```Che editor``` from the root into to che-plugins section  
 - In che-plugin.yaml/editors/name  - is reference to che-plugins/theia-ide-v1.0.0/che-editor.yml/name
 - in che-editor.yml/plugins - is reference about kind of plugins in   che-plugin.yaml/editors/[]/plugins 
 - I see two issues with  ```.spec.initContainers``` idea. It's very connected to K8s/Openshift and will be
   complicated for Docker. 2. It will have troubles in a multicluster environment when a master is working in one cluster and workspace working in another.


## Usecase 1 ##

1. theia plugin is referenced with extra ```theia-plugin/``` since we don't want to duplication it in che-plugin section.

```
# workspace config
plugins:
- theia-plugin/theia-hello-world:1.0.0  
editor: theia-ide:1.0.0 
```
2. The user starts the workspace and wsmaster downloads the editor metadata from a marketplace to be able to start theia container.
```
curl $(marketplace_url)/che-plugins/theia-ide-v1.0.0/che-editor.yml
```
3. Thiea container will query ws-master and figure out a list of Theia plugins to start. After that query marketplace to download Thiea plugins
```
curl $(marketplace_url)/theia-plugins/theia-hello-world-v1.0.0/theia-hello-world-v1.0.0.tar.gz
```



## Usecase 2 ##

1.

```
# workspace config
plugins:
- che-hello-world:1.0.0
editor: theia-ide:1.0.0 
```
2. The user starts the workspace and wsmaster downloads the editor and plugin metadata from a marketplace to be able to start theia container and hello container.
```
curl $(marketplace_url)/che-plugins/theia-ide-v1.0.0/che-editor.yml
curl $(marketplace_url)/che-plugins/che-hello-world-v0.0.1/che-plugin.yml
```
3. Theia container will query ws-master and figure out list of theia plugins to start. After that query marketplace to download Thiea plugins
```
curl $(marketplace_url)/theia-plugins/theia-hello-world-v1.0.0/theia-hello-world-v1.0.0.tar.gz
```
