### ISSUE TITLE
[Question]Is replicas at che's deployment can be bigger than 1?

### ISSUE THREAD

**Issue by LarryZhangy** [eclipse-che/che#10141]
### Description
Is replicas can be bigger than 1?

```
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: che
  name: che
spec:
  replicas: 1
```

### Reproduction Steps

**OS and version:**    
che version :  6.6.0  or  6.7.0
infrastructure: kubernetes
multiuser deploy
