### ISSUE TITLE
Add an ability to configure health checks for container in Workpsace.Next ChePlugin

### ISSUE THREAD

**Issue by garagatyi** [eclipse-che/che#10273]
### Description
Right now we use hardcoded health checks, but with the Workspace.Next we need to make them configurable

### Reproduction Steps

**OS and version:**    

**Diagnostics:**

**Comment by sleshchenko** [comment]
@garagatyi 
The title says about containers health checks while the description contains an information that `right now we use hardcoded health checks` and actually we don't have any health checks for containers but we have for Che Servers(ws-agent, terminal, exec).
So, could you please clarify whether we should:
1. Introduce health checks for plugins containers;
2. Introduce health checks for plugins endpoints since they will be transformed to Che Server and it would be useful to has actual status there, especially for Workspace Loader, when it waits for Editor Endpoint before opening it in an iframe.
3. For both of Plugins Containers and Endpoints.

**Comment by garagatyi** [comment]
I think we need to add container health checks. We couldn't do that in Che 6 because each container could have several apps because of installers. In Che 7 we should put 1 app per container, so container liveness checks would be enough. Apart from that, we would be able to reuse existing functionality of k8s/OS/Docker. 
In any case, since WS.NEXT flow is not implemented for docker we should add liveness checks for containers only. 
I'm talking about Plugin sidecar containers only. In case a user needs health checks in workspace recipe he can use native health check for the recipe type. 

Health checks (liveness probes in k8s terms) can check app running in a container, not container itself, so they can check app state. If app state is OK then I consider as fare to set statuses of all the servers of that container as RUNNING. Maybe later we can remove those statuses at all.

**Comment by BarryDrez** [comment]
@garagatyi For custom stacks, could this be something the user can configure in their recipe - e.g.,
```
"recipe": {
  "type": "kubernetes",
  "content": "kind: List\nitems:\n - \n  kind: Service\n  apiVersion: v1\n  metadata:\n   name: isservice\n  spec:\n   selector:\n    name: IS103\n   ports:\n    - \n     name: isadmin\n     protocol: TCP\n     port: 5555\n     targetPort: 5555\n - \n  kind: Pod\n  apiVersion: v1\n  metadata:\n   name: is103\n  spec:\n   containers:\n    - \n     image: 'daerepository03.eur.ad.sag:4443/design-server/is:10.3.0.0xa'\n     name: integrationserver\n     ports:\n      - \n       containerPort: 5555\n       protocol: TCP\n     resources:\n      limits:\n       memory: 2048Mi\n     livenessProbe:\n       failureThreshold: 11\n       initialDelaySeconds: 5\n       periodSeconds: 5\n       successThreshold: 1\n       tcpSocket:\n         port: 5555\n       timeoutSeconds: 45\n     readinessProbe:\n       failureThreshold: 10\n       initialDelaySeconds: 20\n       periodSeconds: 5\n       successThreshold: 1\n       tcpSocket:\n         port: 5555\n       timeoutSeconds: 120\n",
  "contentType": "text/x-yaml"
}
```
Formatted content:
```
kind: List
items:
 - 
  kind: Service
  apiVersion: v1
  metadata:
   name: isservice
  spec:
   selector:
    name: IS103
   ports:
    - 
     name: isadmin
     protocol: TCP
     port: 5555
     targetPort: 5555
 - 
  kind: Pod
  apiVersion: v1
  metadata:
   name: is103
  spec:
   containers:
    - 
     image: 'daerepository03.eur.ad.sag:4443/design-server/is:10.3.0.0xa'
     name: integrationserver
     ports:
      - 
       containerPort: 5555
       protocol: TCP
     resources:
      limits:
       memory: 2048Mi
     livenessProbe:
       failureThreshold: 11
       initialDelaySeconds: 5
       periodSeconds: 5
       successThreshold: 1
       tcpSocket:
         port: 5555
       timeoutSeconds: 45
     readinessProbe:
       failureThreshold: 10
       initialDelaySeconds: 10
       periodSeconds: 3
       successThreshold: 1
       tcpSocket:
         port: 5555
       timeoutSeconds: 2
```
I have tried this, but it does not work.
