### ISSUE TITLE
Response mode for custom oidc (open id connect)

### ISSUE THREAD

**Issue by osmankibar** [eclipse-che/che#11075]
I am trying to deploy che with multi user and custom oidc. I use 6.10.0 version and I followed this steps https://github.com/eclipse/che/tree/6.10.0/deploy/kubernetes/helm/che . 

My yaml files is 

```yaml
cheWorkspaceHttpProxy: ""
cheWorkspaceHttpsProxy: ""
cheWorkspaceNoProxy: ""
cheImage: eclipse/che-server:nightly
cheImagePullPolicy: Always
cheKeycloakClientId: "che-public"
customOidcUsernameClaim: "preferred_username"
customOidcProvider: "http://192.168.99.1/core"

global:
  cheNamespace: "che"
  multiuser: true
  cheDedicatedKeycloak: false
  ingressDomain: 192.168.99.100.nip.io
  ingressAnnotationsPrefix: "nginx."
  serverStrategy: multi-host
  tls:
    enabled: false
    useCertManager: false
    useStaging: false
    secretName: che-tls
  gitHubClientID: ""
  gitHubClientSecret: ""
  pvcClaim: "1Gi"
  cheWorkspacesNamespace: ""
  workspaceIdleTimeout: "-1"
```

I have problem while che is trying take token from oidc server. Che redirect to this url 

http://192.168.99.1/core/connect/authorize?client_id=che-public&redirect_uri=http%3A%2F%2Fche-che.192.168.99.100.nip.io%2Fdashboard%2F&state=cf6ba053-8772-491e-95c5-ebab6f5df5e6&response_mode=fragment&response_type=code&scope=openid&nonce=a512567c-3b49-492a-967f-06108e7ca7e5

I can see response type is "code". I think It means it uses "Authorization Code" grant flow. But response mode is "fragment". I think fragment response mode for "implicit" grant flow. When I check OIDCKeycloak.js , I see config that is injected in the beginning of code. 

``` javascript

(function( window, undefined ) {

    var Keycloak = function (config) {
        if (!(this instanceof Keycloak)) {
            return new Keycloak(config);
        }
		
```

How I can change this config or how to change response mode to form_post. 

Reproduction Steps

I assume you have "open id server", "minikube" and "helm".

Download these files "https://github.com/eclipse/che/tree/6.10.0/deploy/kubernetes/helm/che"

Run this command.

 helm install -n custom-che --namespace che -f ./values/multi-user.yaml ./
open "http://che-che.192.168.99.100.nip.io/dashboard/"
