### ISSUE TITLE
Automate helm chart deployment to k8s

### ISSUE THREAD

**Issue by kostiamol** [eclipse-che/che#11208]
Now in order to add custom che projects right away after installation I execute:
`kubectl cp custom-samples.json che-8467596d54-7c2hg:/data/templates`
And in order to add a new stack I send HTTP request. But the problem in multi-user mode is that every day I should add an adequate token and session id.

Is there any way to eliminate manual command execution? Should I create post-install hook for that?

**Comment by kostiamol** [comment]
@eivantsov But I still need to execute 2 commands manually. 
I tried to change this init container:
```
 - name: fmp-volume-permission
        image: docker.io/busybox
        command: ["chmod", "777", "/data"]
        volumeMounts: [{
              "mountPath": "/data",
              "name": "che-data-volume"
        }]
```
to 
```
 - name: fmp-volume-permission
        image: registry1-docker-io.repo.lab.pl.alcatel-lucent.com/busybox
        command: ["sh", "-c", "chmod 777 /data; cp custom-samples.json /data/templates"]
        volumeMounts: [{
              "mountPath": "/data",
              "name": "che-data-volume"
        }]
```
and event this one:
```
     name: che
        volumeMounts:
        - mountPath: /data
          name: che-data-volume
      volumes:
      - name: che-data-volume
        persistentVolumeClaim:
          claimName: che-data-volume
```
to
```
     name: che
       command: ["sh", "-c", "cp custom-samples.json /data/templates"]
        volumeMounts:
        - mountPath: /data
          name: che-data-volume
      volumes:
      - name: che-data-volume
        persistentVolumeClaim:
          claimName: che-data-volume
```

But it dosn't work.
