### ISSUE TITLE
Workspace RAM limit doesn't work with sidecar-based workspaces

### ISSUE THREAD

**Issue by garagatyi** [eclipse-che/che#11424]
### Description
We have a limit of RAM for a workspace/user in Che. Unfortunately, with sidecar-based workspaces, it doesn't work because sidecar-based memory consumption can be evaluated on a start of a workspace only and we do not have code that would check memory needed for the workspace at this stage.  

### Reproduction Steps

**OS and version:**    

**Diagnostics:**

**Comment by tsmaeder** [comment]
I don't understand how this is a problem. Could you explain for the unwashed masses?

**Comment by garagatyi** [comment]
When we run Che with a limit for a workspace RAM consumption set to 3GB anybody can create and run a workspace with a sidecar with 30GB of RAM.
We don't check how much memory sidecars consume, so this feature of Che doesn't work in that case. 
On OSIO we also have limits on the OS side, so it wouldn't be possible to misuse service, but in case Che starts workspaces on a cluster that doesn't control RAM consumption by workspace (so only Che is responsible for RAM limits) users can use as many RAM as they want.

If the explanation is not clear enough or you still think that we don't need to fix that, please, elaborate.

**Comment by garagatyi** [comment]
On OSIO this leads to a situation when workspace shows only 1024MB of RAM on UD, but doesn't start because sidecars brought by plugins adds a lot of RAM on top of that.

**Comment by skabashnyuk** [comment]
Duplicate or relevant to https://github.com/eclipse/che/issues/11801

**Comment by sleshchenko** [comment]
It would be ideal if Che Server exposes detailed information about `effective` environment for Che 7 workspace. For example for the following workspace
```yaml
---
specVersion: 0.0.1
name: my-plugin-env
projects:
  - name: microproj
    source:
      type: git
      location: 'https://github.com/rajivnathan/microproj.git'
  - name: nodeTemplate
    source:
      type: git
      location: 'https://github.com/microclimate-dev2ops/nodeExpressTemplate'
components:
  - alias: theia-ide
    type: cheEditor
    id: eclipse/che-theia/next
  - type: dockerimage
    image: centos:centos7
    command: ["fail"]
    args: ["-f", "/dev/null"]
    memoryLimit: 50Mi
```
Che Server should return something like
```
containers:
  - image: centos:centos7
    attributes:
      memoryLimit: 50Mi
  - image: eclipse/che-theia:latest
    attributes:
      memoryLimit: 512M
      plugin: eclipse/che-theia
  - image: eclipse/che-machine-exec:0.0.1
    attributes:
      memoryLimit: 512M
      plugin: eclipse/che-machine-exec
```
And then UI would be able quite easily provide good UX where user understand what his workspace consists of, and can easily tune memory limits for plugins. But this solution requires introducing new API on Che Server and big UI changes.

@ashumilova and I propose the following solution that would make Resource API and UD consistent again. UX won't be great and can be improved later and it sounds realistic that we're able to implement it for GA.

From Che Server perspective:
Che Server needs to evaluate memory for workspace before an attempt to start: 
- to deny start a workspace if there is not enough memory;
- to provide values for displaying for UD;
So, Che Server downloads all `meta.yaml` and calculate workspace memory limit using it and user-defined containers. When workspace is requested by id, `estimatedMemory` attribute is returned in workspace attributes.
After update of workspace, `estimatedMemory` should be recalculated since editor can be changed, plugins can be removed/added.
Caching of `estimatedMemory` is an open issue since plugin configuration can be changed, and it would lead to some inconsistency. Will decide during implementing.

From UD perspective:
- Dashboard displays correct value fo memory of workspace.
- Dashboard does not display a memory that is needed for a particular plugin.
UD now is able to handle it but quite a lot of additional requests are needed to do it and it's better to move iterative way and postpone it.
- Dashboard provides an ability to override memory of plugin, and it affects the value of workspace memory.

cc @slemeur @skabashnyuk @l0rd
