### ISSUE TITLE
Create Che Plugin with GWT IDE and Workspace Agent

### ISSUE THREAD

**Issue by sleshchenko** [eclipse-che/che#11453]
### Description
It would be nice to have an ability to enable GWT IDE using Che Plugins functionality. To make it possible it is needed to create Che Plugin with GWT IDE and Workspace Agent as different servers.

I assume it requires new maven project that will package `IDE` and `wsagent` wars into separate tomcat that will be started in docker image.

**Comment by skabashnyuk** [comment]
In my experiments I have two issues for now.
```
version: 1.0.0
type: Che Editor
name: gwt-ide
id: org.eclipse.che.editor.gwt
title: Eclipse GWT IDE  for Eclipse Che
Description: Eclipse GWT IDE
Icon: https://pbs.twimg.com/profile_images/929088242456190976/xjkS2L-0_400x400.jpg
endpoints:
 -  name: "che-gwt-ide-master"
    public: true
    targetPort: 8085
    attributes:
      protocol: http
      type: ide
 -  name: "wsagent-http"
    public: true
    targetPort: 8087
    attributes:
      protocol: http
      path : api
 -  name: "wsagent-ws"
    public: true
    targetPort: 8087
    attributes:
      protocol: ws
      path : wsagent
containers:
 - name: che-editor-gwt-ide
   image: ksmster/che-editor-gwt-ide
   env:
       - name: SERVER_PORT
         value: 8080
   volumes:
       - mountPath: "/plugins"
         name: plugins
       - mountPath: "/projects"
         name: projects
   ports:
       - exposedPort: 8085
       - exposedPort: 8087
   memory-limit: "512M"
```
1. In che-plugin.yaml I need to be able to define endpoint that will be transformed to the server with name "wsagent/http" "wsagent/ws". I can't do that since the name is required to be valid K8s name
2. To be able to load IDE  I need to have an url to load in such format http://route-to-gwt-ide/{namespace}/{workspacename}

@garagatyi @sleshchenko can you suggest something for 1) ? I will try myself to take a look on 2).
