### ISSUE TITLE
Revise model of meta.yaml and che-plugin.yaml

### ISSUE THREAD

**Issue by sleshchenko** [eclipse-che/che#11479]
### Description
Now we have the following model for `meta.yaml` (plugin registry):
```yaml
type: ...
id: ...
version: ...
name: ...
title: ...
description: ...
icon: ...
url: ...
```
and for `che-plugin.yaml` (packaged into archive):
```yaml
type: ...
id: ...
version: ...
name: ...
title: ...
description: ...
icon: ...
endpoints:
 -  
    ...
containers:
 - 
    ...
```

So, they have duplicated fields. It is reasonable to revise models of these files and choose one place for fields which are duplicated, and document which fields are optional and which mandatory.

Ideally, it would be nice to have validation of `meta.yaml` during build of Che Plugin Registry project. Since `che-plugin.yaml` comes from archive - Plugin Broker/Che Server/both may perform validation of this file. There is a separate issue for that https://github.com/eclipse/che/issues/11509
