### ISSUE TITLE
Setup Devfile implementation plan fro Phase 1

### ISSUE THREAD

**Issue by skabashnyuk** [eclipse-che/che#11719]
### Description
The goal of this task is to dive into the task https://github.com/eclipse/che/issues/11549 and provide some implementation plan for the first iteration.

**Comment by mshaposhnik** [comment]
Phase 1 issue https://github.com/eclipse/che/issues/11832

**Comment by mshaposhnik** [comment]
Phase 2 issue https://github.com/eclipse/che/issues/11833

**Comment by garagatyi** [comment]
@skabashnyuk I have some question. Would you be willing to elaborate? 
- some REST methods produce JSON and some YAML. Is it a typo or design?
- theia-ide is editor, not plugin. Are you suppose that we won't differentiate them in the dev file model?
- in the tool object, there is a definition field that encapsulates che plugin. Are there any other fields or this is some wrapper needed for some particular reason?
- command matches against a tool, but the tool can have multiple containers. How devfile would correlate them? 
- can `toolsCommands` field be simplified? It seems a bit too complex and it would be cool to have devfile clear for the better UX

**Comment by mshaposhnik** [comment]
I expect tools to be be like:
```
tools:
- name: "editor"
  definition:
    chePlugin:
      name: "org.eclipse.che.editor.theia:1.0.0"
- name: "che-machine-exec-plugin"
  definition:
    chePlugin:
      name: "che-machine-exec-plugin:0.0.1"
- name: "che-jdtls-plugin"
  definition:
    chePlugin:
      name: "che-jdtls-plugin:0.0.1"

```

**Comment by skabashnyuk** [comment]
>some REST methods produce JSON and some YAML. Is it a typo or design?

By design.
DevFile->Workspace produces json
Workspace -> Devfile produces yaml

>theia-ide is editor, not plugin. Are you suppose that we won't differentiate them in the dev file model?

I guesses you right. Copy/past from. https://github.com/l0rd/devfile/blob/master/petclinic.yaml @l0rd can you confirm?

>command matches against a tool, but the tool can have multiple containers. How devfile would correlate them? 

This use case postponed to next iteration for simplification. Now we considering that tool = 1 container.

>can toolsCommands field be simplified? It seems a bit too complex and it would be cool to have devfile clear for the better UX

Proposals?

**Comment by garagatyi** [comment]
> can toolsCommands field be simplified? It seems a bit too complex and it would be cool to have devfile clear for the better UX


> Proposals?

just `commands

**Comment by garagatyi** [comment]
@skabashnyuk tnx for the explanation

**Comment by l0rd** [comment]
Answering @garagatyi comments

> theia-ide is editor, not plugin. Are you suppose that we won't differentiate them in the dev file model?

I think that at the time of the devfile definition we had not made a distinction between plugins and editors or that the distinction was blurry. I am ok to have:
```yaml
- name: "editor"
  definition:
    cheEditor:
      name: "org.eclipse.che.editor.theia:1.0.0"
```

Anyway `devfile` wasn't designed to describe a Che workspaces but to define a development environment that could be used by any dev tool (not only graphical IDE). That's why it's all about generic `tools`.

> in the tool object, there is a definition field that encapsulates che plugin. Are there any other fields or this is some wrapper needed for some particular reason?

The full model is https://github.com/l0rd/devfile#third-generation-devfile. And this is just a draft so any idea for improvement is very welcome.

> can toolsCommands field be simplified? It seems a bit too complex and it would be cool to have devfile clear for the better UX

Yes the simpler the better but renaming `commands.toolsCommands` with `commands.commands` doesn't look like an option. Maybe `commands.tools`:

```yaml
commands:
  - name: build
    tools:
      - name: mvn-stack
       (...)
```

**Comment by garagatyi** [comment]
> Yes the simpler the better but renaming commands.toolsCommands with commands.commands doesn't look like an option.

Sergii and I were suggesting `actions.items`:
```
actions:
  - name: re-run
    items:
      - tool: maven-sidecar
        action:
          type: exec
          command: mvn spring-boot:run
          workdir: /projects/spring-petclinic
```
