### ISSUE TITLE
An ability to specify Kubernetes/OpenShift List as tool in Devfile

### ISSUE THREAD

**Issue by sleshchenko** [eclipse-che/che#11906]
### Description
To start quicker it was decided to start with Devfile that will contain editor and plugins only.
But it is needed to add an ability to specify workspace environment in Devfile.
This issue is about changing Devfile model to be able to handle Kubernetes/OpenShift tool.
<details>
<summary>
# An example of Devfile with Kubernetes/OpenShift tool specified
</summary>

```yaml
---
specVersion: 0.0.1
name: petclinic-dev-environment
projects:
  - name: petclinic
    source:
      type: git
      location: 'git@github.com:spring-projects/spring-petclinic.git'
tools:
  - name: petclinic-app
    type: kubernetes
    local: petclinic-app.yml
  - name: theia-ide
    type: cheEditor
    id: eclipse/theia:0.0.3
  - name: jdt.ls
    type: chePlugin
    id: eclipse/theia-jdtls:0.0.3
commands:
  - name: run
    actions:
      - type: exec
        tool: petclinic-app
        command: `./catalina.sh start`
        workdir: /home/user/app/tomcat
```
</details>

Note that this issue is only about Devfile model changes to be able to handle kubernetes/openshift tool.
`DevfileService#createWorkspaceFromYaml` and `DevfileService#createFromWorkspace` methods won't support `kubernetes`/`openshift` tool since it contains relative link to tool configuration file (at least  for time being).
`kubernetes`/`openshift` tool will be supported by Factory workflow when workspace is created from repository inside of repository, the following issue https://github.com/eclipse/che/issues/12266.
