### ISSUE TITLE
Create VSCode extension broker for Theia

### ISSUE THREAD

**Issue by garagatyi** [eclipse-che/che#12026]
### Description
We need Che 7 plugin broker that would start compatible VSCode extension as Theia plugin in a sidecar container. This would allow us to leverage existing VSCode extensions in Che Theia.
The flow:
1. meta.yaml of a plugin specifies VSCode extension URL
1. Identifier of the Che plugin for that would be `VSCode extension`
1. meta.yaml of a plugin specifies docker image of a sidecar needed to run extension as Theia remote plugin
1. VSCode extension broker uses this info to add sidecar into workspace configuration, download the extension and copy it to sidecar container (and Theia container too at the moment).

Example of meta.yaml:
```yaml
id: che-service-plugin
version: 0.0.1
type: VS Code extension
name: k8s extension
title: k8s extension
description: k8s extension
icon: https://www.eclipse.org/che/images/ico/16x16.png
attributes:
 - container-image: dockerhub.io/garagatyi/kubectlnode:latest
 - extension: vscode:extension/ms-kubernetes-tools.vscode-kubernetes-tools
```
**PRs:**
Broker code https://github.com/eclipse/che-plugin-broker/pull/19
Broker integration in Che https://github.com/eclipse/che/pull/12149
Adding it to the plugin registry https://github.com/eclipse/che-plugin-registry/pull/66

**Known issues:**
VS Code extension call commands execution in main Theia container even when the extension and its dependencies are in a sidecar container https://github.com/eclipse/che/issues/12292
Remote extension runner doesn't copy env vars of a sidecar container to extension Node.js process https://github.com/eclipse/che/issues/12298
It is not possible to run several workspaces with remote plugins https://github.com/eclipse/che/issues/12336

### Reproduction Steps

**OS and version:**    

**Diagnostics:**
