### ISSUE TITLE
Factory flow should support k8s/OS tool in Devfile

### ISSUE THREAD

**Issue by sleshchenko** [eclipse-che/che#12266]
### Description
The goal is to improve factory flow to support k8s/OS tool with a relative path to a configuration file specified in Devfile.
<details>
<summary>
# An example of Devfile with Kubernetes/OpenShift tool specified
</summary>

```yaml
---
specVersion: 0.0.1
name: petclinic-dev-environment
projects:
  - name: petclinic
    source:
      type: git
      location: 'git@github.com:spring-projects/spring-petclinic.git'
tools:
  - name: petclinic-app
    type: kubernetes
    local: petclinic-app.yml
  - name: theia-ide
    type: cheEditor
    id: eclipse/theia:0.0.3
  - name: jdt.ls
    type: chePlugin
    id: eclipse/theia-jdtls:0.0.3
commands:
  - name: run
    actions:
      - type: exec
        tool: petclinic-app
        command: `./catalina.sh start`
        workdir: /home/user/app/tomcat
```
</details>

An idea is not to embed k8s/OS yaml into Devfile model but just reference file with k8s/OS content that is located in the same repository where Devfile lives.
Then `resolve factory` flow should parse Devfile and fetch k8s/OS tool configuration content by specified relative path in repository. Then the environment should be provisioned into `Factory#getWorkspaceConfig` with fetched k8s/OS configuration as content of recipe with type `kubernetes/openshift`.
<details>
<summary>
# An example OpenShift Tool Configuration
</summary>

```yaml
apiVersion: v1
kind: List
items:
- apiVersion: v1
  kind: Pod
  metadata:
    name: petclinic
    labels:
      app: petclinic
  spec:
    containers:
    - name: server
      image: mariolet/petclinic
      ports:
      - containerPort: 8080
        protocol: TCP
      resources:
        limits:
        memory: 512Mi
    - name: mysql
      image: centos/mysql-57-centos7
      env:
      - name: MYSQL_USER
        value: petclinic
      - name: MYSQL_PASSWORD
        value: petclinic
      - name: MYSQL_ROOT_PASSWORD
        value: petclinic
      - name: MYSQL_DATABASE
        value: petclinic
      ports:
      - containerPort: 3306
        protocol: TCP
      resources:
        limits:
        memory: 512Mi
- kind: Service
  apiVersion: v1
  metadata:
    name: petclinic
    labels:
      app: petclinic
  spec:
    ports:
      - name: web
        port: 8080
        targetPort: 8080
    selector:
      app: petclinic
- kind: Service
  apiVersion: v1
  metadata:
    name: mysql
    labels:
      app: petclinic
  spec:
    ports:
      - name: mysql
        port: 3306
        targetPort: 3360
    selector:
      app: petclinic
```
</details>
