### ISSUE TITLE
Add support of dockerimage tool in Devfile

### ISSUE THREAD

**Issue by sleshchenko** [eclipse-che/che#12389]
### Description
Add support of dockerimage tool in Devfile.
dockerimage tool format should allow to specify dockerimage like (eclipse/che-server:nightly) and Che specific fields for defining volumes, servers, env vars, etc. See the following example of possible format
```yaml
---
version: 0.0.1
name: petclinic-dev-environment
projects:
  - name: petclinic
    source:
      type: git
      location: 'git@github.com:spring-projects/spring-petclinic.git'
tools:
  - name: maven
    type: dockerimage
    image: maven:3.5.4-jdk-8
    volumes:
      - name: maven-repo
        containerPath: /root/.m2
    env:
      - name: ENV_VAR
        value: value
    endpoints:
      - name: maven-server
        port: 3101
        attributes: 
          protocol: http
          secure: true
          public: true
          discoverable: false
    memoryLimit: 1500M
    mountSources: true
  - name: theia-ide
    type: cheEditor
    id: eclipse/theia:0.0.3
  - name: maven-sidecar
    type: chePlugin
    id: eclipse/maven-sidecar:0.0.3
commands:
  - name: build
    actions:
      - type: exec
        tool: maven
        command: mvn package
        workdir: /projects/spring-petclinic
```

The format should be sync with `che-plugin.yaml` format. See [Plugin Java Model](https://github.com/eclipse/che/blob/master/wsmaster/che-core-api-workspace/src/main/java/org/eclipse/che/api/workspace/server/wsplugins/model/PluginBase.java), [che-plugin.yaml example](https://github.com/ws-skeleton/che-machine-exec/blob/master/assembly/etc/che-plugin.yaml)
