### ISSUE TITLE
Allow to access additional folders/volumes from theia-ide on dev workspace

### ISSUE THREAD

**Issue by eneufeld** [eclipse-che/che#12397]
### Description
I have a java project which relies on proprietary jars which I would like to provide to theia using a volume. 
I have created a custom stack where I mount the volume and when checking with the built in terminal in theia I can see that the volume is available.
But I cannot access this mounted volume from the theia-ide as the only shared folder is the projects folder.

My thought was to provide a custom theia plugin which would mount my custom folder.

I'm opening this issue as a follow up of my discussion on mattermost:
> agaragatyi

> I don't think a custom plugin would help here. But custom IDE would help ) And it is not hard to alternate config of the IDE to add a volume as you might think, but there would be a support burden. 
We need to consider more general and user-friendly approach than creating a custom IDE config or even custom plugin

### Reproduction Steps

**OS and version:**    
Ubuntu 18.04
**Diagnostics:**

**Comment by garagatyi** [comment]
Here is the easiest way I know to workaround lack of this feature in Che.
Now (while Che with https://github.com/eclipse/che/pull/12391 is not merged):
1. Fork https://github.com/eclipse/che-editor-theia
2. Update https://github.com/eclipse/che-editor-theia/master/etc/che-plugin.yaml with content similar to https://raw.githubusercontent.com/garagatyi/che-editor-theia/master/etc/che-plugin.yaml in your fork
e.g. 
```yaml
version: 1.0.0
type: Che Editor
name: theia-ide
id: org.eclipse.che.editor.theia
title: Eclipse Theia for Eclipse Che
Description: Eclipse Theia
Icon: https://pbs.twimg.com/profile_images/929088242456190976/xjkS2L-0_400x400.jpg
endpoints:
 -  name: "theia"
    public: true
    targetPort: 3100
    attributes:
      protocol: http
      type: ide
      secure: true
      cookiesAuthEnabled: true
 -  name: "theia-dev"
    public: true
    targetPort: 3130
    attributes:
      protocol: http
      type: ide-dev
containers:
 - name: theia-ide
   image: eclipse/che-theia:0.3.18-nightly
   env:
       - name: THEIA_PLUGINS
         value: local-dir:///plugins
       - name: HOSTED_PLUGIN_HOSTNAME
         value: 0.0.0.0
       - name: HOSTED_PLUGIN_PORT
         value: 3130
   volumes:
       - mountPath: "/plugins"
         name: plugins
       - mountPath: "/custom"
         name: custom
       - mountPath: "/projects"
         name: projects
   ports:
       - exposedPort: 3100
       - exposedPort: 3130
   memory-limit: "1536M"
```
where I added volume `custom` for the example purposes. But if this fits your case you can use the same content. 
3. Call ./build script in your fork. Tar.gz archive in the root of the repo will be created.
4. Do a Github release and attach! the archive from the previous step to it.
![image](https://user-images.githubusercontent.com/1851863/51105325-54df7a80-17f1-11e9-91c7-4aa249302fe3.png)
5. Fork https://github.com/eclipse/che-plugin-registry
6. Add file like this in your fork (preserve path to match requirements `/plugins/<plugin ID>/<plugin version>/meta.yaml`) 
https://github.com/garagatyi/che-plugin-registry/customTheia/plugins/org.eclipse.che.editor.custom-theia/1.0.0/meta.yaml
With content (ID and version fields should match path to the file):
```yaml
id: org.eclipse.che.editor.custom-theia
version: 1.0.0
type: Che Editor
name: theia-ide
title: Eclipse Theia for Eclipse Che
description: Custom config of Eclipse Theia with custom volume
icon: https://raw.githubusercontent.com/theia-ide/theia/master/logo/theia-logo-no-text-black.svg?sanitize=true
url: https://raw.githubusercontent.com/garagatyi/che-editor-theia/master/etc/che-plugin.yaml
```
where url points to a github released archive (not release itself, but archive in it!) file added on step 4 on github.
![image](https://user-images.githubusercontent.com/1851863/51105393-8bb59080-17f1-11e9-976d-08f3e72f6c8a.png)
7. Copy the RAW link to the file from the previous step by
 - removing `/meta.yaml`
 - replacing `/` between ID and version with a colon `:`
Here how it looks in my case: `https://raw.githubusercontent.com/garagatyi/che-plugin-registry/customTheia/plugins/org.eclipse.che.editor.custom-theia:1.0.0` 
8. Open a Che 7 workspace configuration in UD
![image](https://user-images.githubusercontent.com/1851863/51104028-8ce4be80-17ed-11e9-96d5-5dfbdddb56e4.png)
9. Set modified link from step 6 as value of field `editor`.
![image](https://user-images.githubusercontent.com/1851863/51104619-4ee89a00-17ef-11e9-8741-2d1fdb6b117c.png)
10. Add volume to a machine at the same view of UD:
![image](https://user-images.githubusercontent.com/1851863/51104739-97a05300-17ef-11e9-8127-c9f5c0bd208d.png)
Note that volume name in machine is called `custom` - the same name as we added on step 2. Name itself doesn't matter, but it should match between machine volume and editor definition.
11. Press SAVE! and start the workspace

After the merge of PR https://github.com/eclipse/che/pull/12391 (resuses steps from the previous instruction):
1. From the previouse instruction 1
2. From the previouse instruction 2
3. From the previouse instruction 5
4. Add file like this in your fork (preserve path to match requirements `/plugins/<plugin ID>/<plugin version>/meta.yaml`) 
https://github.com/garagatyi/che-plugin-registry/customTheia/plugins/org.eclipse.che.editor.custom-theia/1.0.0/meta.yaml
With content (ID and version fields should match path to the file):
```yaml
id: org.eclipse.che.editor.custom-theia
version: 1.0.0
type: Che Editor
name: theia-ide
title: Eclipse Theia for Eclipse Che
description: Custom config of Eclipse Theia with custom volume
icon: https://raw.githubusercontent.com/theia-ide/theia/master/logo/theia-logo-no-text-black.svg?sanitize=true
url: https://raw.githubusercontent.com/garagatyi/che-editor-theia/master/etc/che-plugin.yaml
```
where url points to a RAW file added on step 2 on github.
5. From the previouse instruction 7
6. From the previouse instruction 8
7. From the previouse instruction 9
8. From the previouse instruction 10
9. From the previouse instruction 11

Hopefully, I didn't mess with the instruction. I tried the instruction 2 on Friday and it worked on Che instance with merged PR.
