### ISSUE TITLE
[Improve che-plugin.yaml] Use of the property mountProjectSources (or even the simpler mountSources) for a tool/plugin

### ISSUE THREAD

**Issue by skabashnyuk** [eclipse-che/che#12413]
### Description
This issue is created as result of the following discussion https://github.com/redhat-developer/devfile/pull/2#discussion_r242876449

Now if plugin developer wants to get projects sources mounted to his plugin then he has to define volume with name `projects` and path `/projects`. 
```yaml
version: 1.0.0
type: Che Editor
name: theia-ide
id: org.eclipse.che.editor.theia
endpoints:
       ...
containers:
 - name: theia-ide
   image: eclipse/che-theia:0.3.18-nightly
   env:
       ...
   volumes:
       - mountPath: "/projects"
         name: projects
       - mountPath: "/plugins"
         name: plugins
   ports:
       ...
```
The idea of this issue is simplify defining of mounting projects sources to the following format:
```yaml
version: 1.0.0
type: Che Editor
name: theia-ide
id: org.eclipse.che.editor.theia
endpoints:
       ...
containers:
 - name: theia-ide
   image: eclipse/che-theia:0.3.18-nightly
   env:
       ...
   volumes:
       - mountPath: "/plugins"
         name: plugins
   mountSources: true // false
   ports:
       ...
```
should define project volumes
The idea of this issue is avoid defining projects volume by user/plugin developer.

The scope of this issue includes:
- [ ] Made Che Server respecting this flag and provision `projects` volume automatically with `/projects` path specified. Note that the solution should be back forward compatible and plugins that are configured in old way (with `projects` volume specified) should work. It may be implemented by taking `mountSources` into account only when `projects` volume is missing;
- [ ] Update field name in dockerimage tool when final name decision about `mountSources`/`mountProjectSources` will be made. See https://github.com/redhat-developer/devfile/blob/master/Devfile.yaml;
