### ISSUE TITLE
Dashboard should validate PVCs in Kubernetes/OpenShfit recipes

### ISSUE THREAD

**Issue by sleshchenko** [eclipse-che/che#12440]
### Description
Dashboard should validate PVCs in Kubernetes/OpenShfit recipes.

What should be checked:
```
  apiVersion: v1
  kind: PersistentVolumeClaim
  metadata:
    name: userdata   // Name MUST BE not null and unique to other PVCs names
  spec:
    accessModes:      // Need to check rules according to Kubernetes API
     - ReadWriteOnce
    resources:        // Need to check rules according to Kubernetes API
      requests: 
        storage: 1Gi
```
Also it is needed to validate PVCs references in Pods volumes
```yaml
  apiVersion: v1
  kind: Pod
  metadata:
    name: ws
  spec:
    containers:
     -
      image: 'eclipse/che-dev:nightly'
      name: dev-with-vm
      volumeMounts:
       -
         mountPath: /data
         name: data-volume     // volume with specified name MUST BE present in Pod#Spec#Volumes
         subPath: user/data     // subPath must be relative, it means that it should not start with `/`
    initContainers:
     -
       name: init
       image: alpine:3.5
       command: ["sh", "-c", "echo Hello > /init-data/hello.txt"]
       volumeMounts:
       -
         mountPath: /init-data  -- the same validation as for Pod#Spec#Containers
         name: data-volume
         subPath: user/data
    volumes:
     -
      name: data-volume
      persistentVolumeClaim: // check volume only if `persistentVolumeClaim` object is not null
        claimName: userdata  // PVC with the specified name MUST BE present in recipe
```
