### ISSUE TITLE
Describe process for making and testing Che 7 plugin from vscode plugin

### ISSUE THREAD

**Issue by tsmaeder** [eclipse-che/che#12447]
Write a small how-to on how to create and test a che 7 plugin from an existing vscode plugin. Add it to the Che wiki pages.

**Comment by tolusha** [comment]
### How to create and test a Che 7 plugin from an existing VS Code extension

Complete the following steps to run a Che 7 plugin based on [VS Code extension](https://marketplace.visualstudio.com/vscode)

1. Prepare docker image to launch extension based on `wsskeleton/theia-endpoint-runtime`. The image should additionally contains
all necessary tools, for instance java, Go etc.

2. Build and pull image at docker hub.

3.  Prepare `meta.yaml` for desired plugin. Have a look at an example for node debug plugin:

```yaml
id: ms-vscode.node-debug2
version: 1.31.1
type: VS Code extension
name: Node Debug
title: Node.js debugging support
description: Node Debug is the debugger for Node.js versions >= 8.0 https://marketplace.visualstudio.com/items?itemName=ms-vscode.node-debug2
icon: https://www.eclipse.org/che/images/logo-eclipseche.svg
attributes:
  extension: "vscode:extension/ms-vscode.node-debug2"
  container-image: "eclipse/ms-vscode.node-debug2" 
```

4. Push `meta.yaml` at https://github.com. The list of [available plugins](https://github.com/garagatyi/che-plugin-registry/tree/sonarlint/plugins)

5. Create workspace and add plugin url to the workspace config:

```json
"attributes": {
    "editor": "org.eclipse.che.editor.theia:1.0.0",
    "plugins": "che-machine-exec-plugin:0.0.1,https://github.com/eclipse/che-plugin-registry/tree/master/plugins/org.eclipse.che.samples.container-fortune:0.0.1"
  }
```
