### ISSUE TITLE
Can't open terminal in Che deployed with Che minishift addon

### ISSUE THREAD

**Issue by jarifibrahim** [eclipse-che/che#12451]
### Description
 

I'm running che on minishift via the minishift addon. I'm using the che-server:nightly docker image.
I have created a workspace using the following devfile
```yaml
---
specVersion: 0.0.1
name: petclinic-dev-environment
projects:
  - name: petclinic
    source:
      type: git
      location: 'git@github.com:spring-projects/spring-petclinic.git'
tools:
  - name: theia-ide
    type: cheEditor
    id: org.eclipse.che.editor.theia:1.0.0
  - name: terminal
    type: chePlugin
    id: che-machine-exec-plugin:0.0.1
commands:
  - name: hello
    actions:
      - type: exec
        tool: theia-ide
        command: echo Hello
        workdir: /projects/spring-petclinic
```

The workspace was created but I couldn't start a terminal. The che pod on minishift had the following error
```
[GIN] 2019/01/16 - 14:08:19 | 200 |    3.161257ms |    192.168.42.1 | GET      /connect
Unable to create machine exec. Cause:  pods is forbidden: User "system:serviceaccount:mini-che:default" cannot list pods in the namespace "mini-che": no RBAC policy matched
```
### Reproduction Steps
1. Start che in minishift using the addon.
2. Replace image with `che-server:nightly`
3. Create a workspace via post request to `api/devfile` with payload
```yaml
---
specVersion: 0.0.1
name: petclinic-dev-environment
projects:
  - name: petclinic
    source:
      type: git
      location: 'git@github.com:spring-projects/spring-petclinic.git'
tools:
  - name: theia-ide
    type: cheEditor
    id: org.eclipse.che.editor.theia:1.0.0
  - name: terminal
    type: chePlugin
    id: che-machine-exec-plugin:0.0.1
commands:
  - name: hello
    actions:
      - type: exec
        tool: theia-ide
        command: echo Hello
        workdir: /projects/spring-petclinic
```

4. Start the newly created workspace and try to open a new terminal.
