### ISSUE TITLE
[Devfile] Support commands for Os/K8s tool

### ISSUE THREAD

**Issue by skabashnyuk** [eclipse-che/che#12479]
### Description
Now we support commands only for the ChePlugin or CheEditor tool.
We want to introduce an ability to define commands for OS/K8s tools
Like
```yaml
specVersion: 0.0.1
name: che-in-che
projects:
  - name: che
    source:
      type: git
      location: 'https://github.com/eclipse/che.git'
tools:
  - name: theia-editor
    type: cheEditor
    id: org.eclipse.che.editor.theia:1.0.0
  - name: exec-plugin
    type: chePlugin
    id: che-machine-exec-plugin:0.0.1
  - name: che-dev
    type: openshift
    local: .che-dev.yaml
commands:
  - name: build
    actions:
      - type: exec
        tool: che-dev
        command: mvn clean install
        workdir: /projects/che
```

**Comment by skabashnyuk** [comment]
One of the issues that exist is: what to do if OS/K8S recipe contains more then one container.
Should we specify some additional information in command definition?
@l0rd  can you comment?

**Comment by l0rd** [comment]
**Option 1** Use an `action#tool-selector` that, associated with the `action#tool-name`, would select the right container.

**Option 2** Use one of the filter that will be put in place by #12386 

**Option 3** Prompt the user when one or more container match the filters/selectors

These options are not mutually exclusive. Ideally we should put in place all of them.

**Comment by sleshchenko** [comment]
> Option 1 Use an action#tool-selector that, associated with the action#tool-name, would select the right container.

@l0rd Could you clarify what you mean `action#tool-selector`? It should be a new field in action to specify `selector` for picking up the right container? How this selector is supposed to work since Kubernetes Pod has labels but not a container.

> Option 2 Use one of the filter that will be put in place by #12386

Could you clarify what does it mean for Devfile format? It is introducing new field in action to specify whether this action is supposed to be run in `recipe`/`tool` sourced container?

**Comment by sleshchenko** [comment]
@l0rd Thanks for clarifications.
```yaml
    actions:
      - type: exec
        tool: 
           name: che
           selector:
               name: postgres
        command: psql
```
I expect from `selector` to be matched with objects labels. But container does not have own labels. If we would match `name` selector field with container name than it would not be so clear format since `Pods` in tool also have names.
Also there is only restriction from Kubernetes to be containers names unique whithing one Pod. And tool may contain multiple containers with the same names. Like `Pod{name: db, containers{name: main}}`, `Pod{name: web-app, containers{name: main}}`.

I have in mind the following way how to provide not bad UX for user with minimal afford. 
As an example user uses the following Devfile:
```yaml
specVersion: 0.0.1
name: che-in-che
projects:
   ...
tools:
  - name: theia-editor
    type: cheEditor
    id: org.eclipse.che.editor.theia:1.0.0
  - name: che-dev
    type: openshift
    local: che-dev.yaml
commands:
  - name: build
    actions:
      - type: exec
        tool: che-dev
        command: mvn clean install
        workdir: /projects/che
  - name: hello-theia
    actions:
      - type: exec
        tool: theia-editor
        command: echo Hello from Theia IDE
```
1. The user run `hello-theia` command and it is automatically executed in first theia-plugin container (it contains the only one container). Such functionality is already implemented.

As for `build` command there can be two cases:
The tool contains the only one container:
2. The user run `build` command. Machine name is preconfigured and command is executed there without user confirmation. 
Implementation notes: Che Server should be updated to set machine name if OpenShift, Kubernetes tool contains one container.

The tool contains the several containers:
2. The user run `build` command. Machine name is not preconfigured. Theia asks user to choose machine from recipe.

Implementation notes: https://github.com/eclipse/che/pull/12386 should be merged. And Theia Tasks plugin should be reworked to propose user to choose machines from recipe sourced containers, choose plugin containers is possible as additional option. It may looks like the following:
![screenshot_20190130_125624_____](https://user-images.githubusercontent.com/5887312/51977760-ebb66300-2490-11e9-8856-8b24fb61877b.png)
After clicking on `Show other contains` containers list should be updated
![screenshot_20190130_125624__](https://user-images.githubusercontent.com/5887312/51977398-05a37600-2490-11e9-8ce3-2794c9ebee93.png)
Maybe tool containers should be marked like the following
![screenshot_20190130_125624__123](https://user-images.githubusercontent.com/5887312/51977628-967a5180-2490-11e9-9522-9994f7628b6f.png)
The label may be different like `editor`, `plugin`, etc.

Later Devfile format may be improved to provide a user an ability to pre-configure container from Kubernetes/OpenShift tool with multiple containers. But I think we should consider implementing the described workflow as initial and simpler one.
@skabashnyuk @l0rd WDYT?
