### ISSUE TITLE
Add machine token to request to exec sidecar

### ISSUE THREAD

**Issue by garagatyi** [eclipse-che/che#12573]
### Description
When Exec/terminal extension connects to exec sidecar it should pass machine token to authenticate the request. It can be done using a query parameter.

**Comment by AndrienkoAleksandr** [comment]
@vparfonov could you get this issue to fix this issue for task extension/plugin?

**Comment by AndrienkoAleksandr** [comment]
@garagatyi Is this issue still actual? For tasks plugin it was not completed.

**Comment by garagatyi** [comment]
@AndrienkoAleksandr terminal is fixed but tasks feature is still not sending needed token.
To check replace your exec plugin in Che workspace with `https://raw.githubusercontent.com/eclipse/che-plugin-registry/05277173234b708e3361c8279f1257f4c557f8be/v2/plugins/eclipse/che-machine-exec-plugin/0.0.1`. 
In case link expires:
Content of meta.yaml to test
```yaml
publisher: eclipse
name: che-machine-exec-plugin
version: 0.0.1
type: Che Plugin
displayName: Che machine-exec Service
title: Che machine-exec Service Plugin
description: Che Plug-in with che-machine-exec service to provide creation terminal
  or tasks for Eclipse CHE workspace machines.
icon: https://www.eclipse.org/che/images/logo-eclipseche.svg
url: https://raw.githubusercontent.com/eclipse/che-machine-exec/1f5598a5c535a341f9d74170f2a0b52c50dac87c/assembly/etc/che-plugin.yaml
repository: https://github.com/eclipse/che-machine-exec/
firstPublicationDate: "2019-02-05"
category: Other
```
Which points to another yaml:
```yaml
endpoints:
 -  name: "che-machine-exec"
    public: true
    targetPort: 4444
    attributes:
      protocol: ws
      secure: true
      type: terminal
      discoverable: false
containers:
 - name: che-machine-exec
   image: eclipse/che-machine-exec
   ports:
     - exposedPort: 4444
editors:
   - id: org.eclipse.che.editor.theia
```
