### ISSUE TITLE
Implement an ability to specify container for commands for K8s/OS tool with multiple containers

### ISSUE THREAD

**Issue by sleshchenko** [eclipse-che/che#12606]
### Description
Now commands for K8s/OS tool in devfile work fine only if the tool has one container.
It is needed to improve UX of K8s/OS tool commands if the tool has multiple containers.
There are two different improvements directions:

1. IDE should propose to user choose container from tool containers list (now it shows all containers, editors, plugins, Che Utils(like jwtproxy)).

2. Add an ability in Devfile to specify the concrete container from tool.
It may be done by extending Devfile Command model and introducing new fields like
```yaml
  - name: build
    actions:
      - type: exec
        tool: 
          name: che-dev
          containerName: mysql  // new
          podName: db           // new 
          selector:             // new
            app.kubernetes.io/component: database
        command: mvn clean install
        workdir: /projects/che
```
It is just a proposal that should be discussed in details and there was not made final decision how Command model should be changed to handle this case.
