### ISSUE TITLE
Provision labels for kubernetes containers created by Che

### ISSUE THREAD

**Issue by sleshchenko** [eclipse-che/che#12671]
### Description
There is an example when the client (`kubectl` in this particular case) needs to identify which containers belong to which plugin. So, it is needed to have some place that we would be able to use for storing container meta information. Kubernetes Container does not have its own metadata and labels. We can use pod's labels to store containers metainformation like related plugin id.
In such case, we should define container label format like `container.<name>.<label_key>` that will be stored in pod's labels.
Like an example
```yaml
kind: Pod
metadata:
  name: myPod
  labels:
    container.vscode_generated18f6csn.plugin: org.eclipse.che.vscode-sonarlint
    container.theia.plugin: org.eclipse.che.editor.theia
spec:
  containers:
  - name: theia
    ...
  - name: vscode_generated18f6csn
    ...    
```
Would mean that  `theia` container is provisioned by `org.eclipse.che.editor.theia` and `vscode_generated18f6csn` by `org.eclipse.che.vscode-sonarlint` in accordance. And client is able to quite easily evaluate plugin id using Kubernetes API response only, no need to request Che API.

Note that labels has quite strict format and annotations may be used instead if that format does suite Che needs.
