### ISSUE TITLE
Support devfile with more than one Kubernetes tool

### ISSUE THREAD

**Issue by l0rd** [eclipse-che/che#12719]
### Description

Devfile example:

```yaml
specVersion: 0.0.1
name: fix-the-kube
projects:
  - name: nodejs-mongo-app
    source:
      type: git
      location: 'https://github.com/ijason/NodeJS-Sample-App.git'
tools:
  - name: theia-editor
    type: cheEditor
    id: org.eclipse.che.editor.theia:1.0.0
  - name: exec-plugin
    type: chePlugin
    id: che-machine-exec-plugin:0.0.1
  - name: mongodb
    type: kubernetes
    local: mongo-controller.yaml
  - name: nodejs
    type: kubernetes
    local: node-controller.yaml
```

Controllers yamls can be found at [kubernetes example](https://github.com/kubernetes/examples/tree/master/staging/nodesjs-mongodb)
