### ISSUE TITLE
[Devfile] OpenShift/K8s tool -  reference to content

### ISSUE THREAD

**Issue by skabashnyuk** [eclipse-che/che#12733]
### Description
At this moment we only one way to reference an external OpenShift/K8s recipe is a file that is located near devfile on GitHub.
And we can use it only with factories.

```
tools:
  - name: os-recipe
    type: openshift
    local: petclinic.yaml
```

The idea of this issue is to add the ability to specify a direct link to content.
For example 

```
tools:
  - name: os-recipe
    type: openshift
    url: https://raw.githubusercontent.com/eclipse/che/master/.che-dev.yaml
```
