### ISSUE TITLE
Theia should be the default editor

### ISSUE THREAD

**Issue by l0rd** [eclipse-che/che#12835]
### Description

When a user defines a Che 7 workspace (using a devfile, a workspace json or a stack) he needs to specify the editor. Otherwise, if no tools are defined, he gets the following error:

```json
{
  "message": "Devfile schema validation failed. Error: /devfile object has missing required properties ([\"tools\"])"
}
```

and, if at least a tool is defined, the workspace is created but the execution fails (wsagent server doesn't exist):

![image](https://user-images.githubusercontent.com/606959/53870303-46942a80-3ffa-11e9-86bd-21513915027e.png)
 
Most of the users will only want to use the default editor (che-theia) and we should make it possible to use a devfile without a theia-editor and without tools. 

In addition, if the editor is Theia, the `exec-plugin` should be loaded by default:

For instance a user should be able to use the following devfile

```yaml
specVersion: 0.0.1
name: petclinic-dev-environment
projects:
  - name: petclinic
    source:
      type: git
      location: 'git@github.com:spring-projects/spring-petclinic.git'
```

and it should be equivalent to 

```yaml
---
specVersion: 0.0.1
name: petclinic-dev-environment
projects:
  - name: petclinic
    source:
      type: git
      location: 'git@github.com:spring-projects/spring-petclinic.git'
tools:
  - name: theia-editor
    type: cheEditor
    id: org.eclipse.che.editor.theia:1.0.0
  - name: exec-plugin
    type: chePlugin
    id: che-machine-exec-plugin:0.0.1
```
