### ISSUE TITLE
Devfile: tools should be renamed components 

### ISSUE THREAD

**Issue by l0rd** [eclipse-che/che#12836]
### Description

Component is a better name. It's more generic and tools is ok for IDE tools (language suppport, debugging etc...) but less for IDE runtimes (application servers, databases etc....) or editors (e.g. theia).

And we need to do the renaming also to align with [odo](https://github.com/redhat-developer/odo) terminology 

So a devfile would look like:

```yaml
---
specVersion: 0.0.1
name: petclinic-dev-environment
projects:
     (...)
components:
     (...)
commands:
   - name: (...)
     actions:
       - type: exec
         component: mysql
         (...)
```
