### ISSUE TITLE
workdir on a devfile is ignored

### ISSUE THREAD

**Issue by gorkem** [eclipse-che/che#12853]
Created a workspace with the following and the run and build commands specified fails because they are run on the /projects folder 

```yaml
---
specVersion: 0.0.1
name: nodejs-rest-http
projects:
  - name: node-rest
    source:
      type: git
      location: "https://github.com/nodeshift-starters/nodejs-rest-http.git"
tools:
  - name: theia-editor
    type: cheEditor
    id: org.eclipse.che.editor.theia:master
  - name: exec-plugin
    type: chePlugin
    id: che-machine-exec-plugin:0.0.1
  - name: typescript
    type: chePlugin
    id: ms-vscode.typescript:1.30.2
  - name: node-runtime
    type: dockerimage
    image: eclipse/centos_nodejs
    env:
      - name: PORT
        value: "8080"
    endpoints:
      - name: express-server
        port: 8080
        attributes:
          protocol: http
          secure: "true"
          public: "true"
          discoverable: "false"
    memoryLimit: 256M
    mountSources: true
commands:
  - name: build
    actions:
      - type: exec
        tool: node-runtime
        command: npm install
        workdir: /projects/node-rest
  - name: run
    actions:
      - type: exec
        tool: node-runtime
        command: npm start
        workdir: /projects/node-rest
```
