### ISSUE TITLE
Che 7 ssh git is not working

### ISSUE THREAD

**Issue by gorkem** [eclipse-che/che#12850]
`git clone git@github.com:gorkem/penfold.git` fails with the following message
```
Request clone failed with message: Cloning into '/projects/penfold'...
fatal: cannot run ssh: No such file or directory
fatal: unable to fork
``` 
I think this is because of the missing ssh binaries on the image. This also results on url factory to fail. Here is the devfile that I have used to easily reproduce.

```yaml
---
specVersion: 0.0.1
name: penfold-bot
projects:
  - name: penfold
    source:
      type: git
      location: 'git@github.com:gorkem/penfold.git'
tools:
  - name: theia-editor
    type: cheEditor
    id: org.eclipse.che.editor.theia:master
  - name: exec-plugin
    type: chePlugin
    id: che-machine-exec-plugin:0.0.1
  - name: typescript
    type: chePlugin
    id: ms-vscode.typescript:1.30.2
```
