### ISSUE TITLE
Set memory limit for sidecar plugins on devfile

### ISSUE THREAD

**Issue by gorkem** [eclipse-che/che#12981]
We should be able to set the memory limits for a sidecar container for a plugin on a devfile. There is already a `memoryLimit` property associated with the tools on the defile that applies to docker image types. We should extend it to include plugins as well.  I was thinking something like 

```yaml
tools:
  - name: theia-editor
    type: cheEditor
    id: org.eclipse.che.editor.theia:master
    memoryLimit: 256M
```

**Comment by garagatyi** [comment]
What should be the behavior when several containers are injected with the plugin?

**Comment by garagatyi** [comment]
Another option could be allowing overriding plugin configuration in devfile tool in the same format as merged meta.yaml will be.
So devfile part where user overrides tool components can be:
```yaml
tools:
  - name: theia-editor
    type: cheEditor
    id: org.eclipse.che.editor.theia:master
    spec:
# We override or complement endpoints here, aka exposed ports
        endpoints:
        -  name: "theia"
           public: true
           targetPort: 3100
           attributes:
             protocol: http 
             type: ide
             secure: true
             cookiesAuthEnabled: true
             discoverable: false
# We override parts of container(s) here or even add new ones
# if there is single container in the plugin no matching needed
# if there are several containers in the plugin container names are used for matching which container config gets overriden
        containers:
         - name: theia-ide
# We can rewrite image here if we want something truly customizable
           image: eclipse/che-theia:next
# We can add environment variables here
           env:
               - name: THEIA_PLUGINS
                 value: local-dir:///plugins
               - name: HOSTED_PLUGIN_HOSTNAME
                 value: 0.0.0.0
               - name: HOSTED_PLUGIN_PORT
                 value: 3130
# We can add volumes here
           volumes:
               - mountPath: "/plugins"
                 name: plugins
               - mountPath: "/projects"
                 name: projects
           ports:
               - exposedPort: 3100
           memoryLimit: "1536M"
     mountSources: true
``` 
or in the simplest case when only memory needs to be overriden:
```yaml
tools:
  - name: theia-editor
    type: cheEditor
    id: org.eclipse.che.editor.theia:master
    spec:
        containers:
         - memoryLimit: "1536M"
```
It doesn't look that pretty, I agree. On the other hand it brings additional features like overriding volumes/ports/env vars.
