### ISSUE TITLE
Add VS code extensions preferences in workspace configuration

### ISSUE THREAD

**Issue by l0rd** [eclipse-che/che#12992]
### Description

For example it should be possible to override the default JDT LS vmargs to match the sidecar container memory settings. Today that's not possible and we have 2 workarounds that are not really satisfactory:

- use a sidecar with > 1.5GB (may be too much for che.openshift.io)
- start the workspace and edit the JTD LS vmargs from Theia settings (but the UX is awful)

That same problem will exist for any VS Code plugin that has some defaults that may not work well when they run in a container.

Here is a proposal to include that in a `devfile` and `workspace.config`:

```yaml
  - name: java support
    type: chePlugin
    id: 'org.eclipse.che.vscode-redhat.java:0.38.0'
    preferences:
       java.jdt.ls.vmargs: '-noverify -Xmx1G -XX:+UseG1GC -XX:+UseStringDeduplication'
       java.home: '/home/user/jdk11'
```
**devfile**

and in json config

```json
"attributes": {
  "plugin.org.eclipse.che.vscode-redhat.java.java.jdt.ls.vmargs": "-noverify -Xmx1G -XX:+UseG1GC -XX:+UseStringDeduplication",
  "plugin.org.eclipse.che.vscode-redhat.java.java.home": "/home/user/jdk11"
...
}
```
**workspace config**
