### ISSUE TITLE
UD should show warning if plugin is deprecated

### ISSUE THREAD

**Issue by garagatyi** [eclipse-che/che#13021]
### Description
When plugin enabled in a workspace is deprecated:
```yaml
publisher: plugin_publisher
id: plugin_id
version: 1.2.3
name: Some plugin
deprecate:
   autoMigrate: true
   migrateTo: another_publisher/another_plugin_id:1.0.0
```
UD should show a sign (probably exclamation mark) on plugin that have this section and explain that these plugins are deprecated and it is better to migrate to plugin specified in `deprecate.migrateTo`.

See more details at https://github.com/eclipse/che-plugin-registry/issues/55#issuecomment-475674436
