### ISSUE TITLE
Plugin broker should use new plugin instead of old one if automigrate feature of the plugin is set to true 

### ISSUE THREAD

**Issue by garagatyi** [eclipse-che/che#13022]
### Description
Plugin registry notation changes will introduce field deprecated into meta.yaml:
```yaml
publisher: plugin_publisher
id: plugin_id
version: 1.2.3
name: Some plugin
deprecate:
   autoMigrate: true
   migrateTo: another_publisher/another_plugin_id:1.0.0
```
See explanation here eclipse/che-plugin-registry#55 (comment)

If `autoMigrate` field is set to `true` broker should use plugin specified in `migrateTo` instead of the one with the `deprecate` field.
If `deprecate` is missing or `autoMigrate` is set to `false` nothing needs to be done.
