### ISSUE TITLE
Error when starting workspace, created from devfile

### ISSUE THREAD

**Issue by evidolob** [eclipse-che/che#13040]
### Description
Got error:
```
Error: Failed to run the workspace: "Failure executing: POST at: https://10.96.0.1/apis/extensions/v1beta1/namespaces/che/ingresses. Message: Ingress.extensions "ingressu8jd0bx7" is invalid: metadata.labels: 
Invalid value: "serveri23ah6hp-theia-endpoint-runtime-che-machine-exec-server-4444": must be no more than 63 characters.
 Received status: Status(apiVersion=v1, code=422, details=StatusDetails(causes=[StatusCause(field=metadata.labels, message=Invalid value: "serveri23ah6hp-theia-endpoint-runtime-che-machine-exec-server-4444": 
must be no more than 63 characters, reason=FieldValueInvalid, additionalProperties={})], group=extensions, kind=Ingress, name=ingressu8jd0bx7, retryAfterSeconds=null, uid=null, additionalProperties={}), kind=Status, message=Ingress.extensions "ingressu8jd0bx7" is invalid: metadata.labels: 
Invalid value: "serveri23ah6hp-theia-endpoint-runtime-che-machine-exec-server-4444": 
must be no more than 63 characters, metadata=ListMeta(_continue=null, resourceVersion=null, selfLink=null, additionalProperties={}), reason=Invalid, status=Failure, additionalProperties={})."
```

### Reproduction Steps
1. Create workspace from devfile, using chectl
```
specVersion: 0.0.1
name: cheTheia-in-che-remote
projects:
  - name: che-theia-samples
    source:
      type: git
      location: 'https://github.com/eclipse/che-theia-samples.git'
  - name: theia
    source:
      type: git
      location: 'https://github.com/theia-ide/theia.git'
components:
  - name: theia-editor
    type: cheEditor
    id: org.eclipse.che.editor.theia:next
  - name: exec-plugin
    type: chePlugin
    id: che-machine-exec-plugin:0.0.1
  - name: theia-endpoint-runtime
    type: dockerimage
    image: eclipse/che-theia-endpoint-runtime:next
    endpoints:
      - name: theia-remote-end
        port: 10000
        attributes:
          protocol: ws
          public: 'true'
    memoryLimit: 1Gi
    mountSources: true
 # - name: git
 #   type: dockerimage
 #   image: sunix/git-devtools
 #   mountSources: true
 #   memoryLimit: 256M
  - name: che-dev
    type: chePlugin
    id: org.eclipse.che.theia.dev:0.0.1
commands:
  - name: init ... che-theia
    actions:
      - type: exec
        component: che-dev
        command: >
                 cd /projects/theia/ &&
                 che:theia init --dev
        workdir: /projects/theia
  - name: clean ... che-theia
    actions:
      - type: exec
        component: che-dev
        command: >
                 cd /projects/theia/ &&
                 che:theia clean
        workdir: /projects/theia
  - name: build ... che-theia
    actions:
      - type: exec
        component: che-dev
        command: >
                 killall node || true &&
                 cd /projects/theia/ &&
                 yarn
        workdir: /projects/theia
  - name: build ... hello-world-backend-plugin
    actions:
      - type: exec
        component: che-dev
        command: >
                 killall node || true &&
                 cd /projects/che-theia-samples/samples/hello-world-backend-plugin &&
                 yarn
        workdir: /projects/che-theia-samples/samples/
  - name: run ... remote theia endpoint
    actions:
      - type: exec
        component: theia-endpoint-runtime
        command: >
                 killall node || true &&
                 echo export THEIA_PLUGIN_REMOTE_ENDPOINT_helloworld='ws://${HOSTNAME}:10000' > /projects/endpoint.env &&
                 export THEIA_PLUGINS='local-dir:///projects/che-theia-samples/samples/hello-world-backend-plugin' &&
                 export THEIA_PLUGIN_ENDPOINT_PORT='10000' &&
                 node /home/theia/lib/node/plugin-remote.js
        workdir: /home/theia/
  - name: run ... che-theia
    actions:
      - type: exec
        component: che-dev
        command: >
                 killall node || true &&
                 mkdir -p /projects/theiadev_projects &&
                 export CHE_PROJECTS_ROOT=/projects/theiadev_projects &&
                 . /projects/endpoint.env &&
                 cd /projects/theia/examples/assembly &&
                 export GIT_EXEC_PATH=/usr/libexec/git-core && export USE_LOCAL_GIT=true && export LOCAL_GIT_DIRECTORY=/usr &&
                 yarn start /projects/theiadev_projects --hostname=0.0.0.0 --port=3010
        workdir: /projects/che-theia

  
```
2. Open workspace, on workspace loader you will see error:
![Screen Shot 2019-04-02 at 10 15 03](https://user-images.githubusercontent.com/929743/55383214-4f601980-5530-11e9-9373-42b8aa028cc2.png)

**Diagnostics:** 
Che master server has error log:
```
2019-04-02 07:14:24,228[aceSharedPool-0]  [WARN ] [.i.k.KubernetesInternalRuntime 245]  - Failed to start Kubernetes runtime of workspace workspacekkdhufqrba9weqwr. Cause: Failure executing: POST at: https://10.96.0.1/apis/extensions/v1beta1/namespaces/che/ingresses. Message: Ingress.extensions "ingressxab2vcva" is invalid: metadata.labels: Invalid value: "serverz8rxxvtk-theia-endpoint-runtime-che-machine-exec-server-4444": must be no more than 63 characters. Received status: Status(apiVersion=v1, code=422, details=StatusDetails(causes=[StatusCause(field=metadata.labels, message=Invalid value: "serverz8rxxvtk-theia-endpoint-runtime-che-machine-exec-server-4444": must be no more than 63 characters, reason=FieldValueInvalid, additionalProperties={})], group=extensions, kind=Ingress, name=ingressxab2vcva, retryAfterSeconds=null, uid=null, additionalProperties={}), kind=Status, message=Ingress.extensions "ingressxab2vcva" is invalid: metadata.labels: Invalid value: "serverz8rxxvtk-theia-endpoint-runtime-che-machine-exec-server-4444": must be no more than 63 characters, metadata=ListMeta(_continue=null, resourceVersion=null, selfLink=null, additionalProperties={}), reason=Invalid, status=Failure, additionalProperties={}).
2019-04-02 07:14:24,435[aceSharedPool-0]  [INFO ] [o.e.c.a.w.s.WorkspaceRuntimes 803]   - Workspace 'che:cheTheia-in-che-remote_1' with id 'workspacekkdhufqrba9weqwr' start failed
```
