### ISSUE TITLE
Devfile with gist url id for component became not valid

### ISSUE THREAD

**Issue by AndrienkoAleksandr** [eclipse-che/che#13055]
### Description
Devfile with gist url id for component became not valid

### Reproduction Steps
Create with swagger workspace from such devfile:

```
specVersion: 0.0.1
name: terminal-sample
components:
  - name: theia-ide
    type: cheEditor
    id: org.eclipse.che.editor.theia:next
  - name: exec-plugin
    type: chePlugin
    id: che-machine-exec-plugin:0.0.1
  - name: terminal-sample-plugin
    type: chePlugin
    id: https://raw.githubusercontent.com/azatsarynnyy/che7-plugin-registry/master/terminal-sample:0.0.1
```

Actual result: workspace creation fail: validation error for component id: https://raw.githubusercontent.com/azatsarynnyy/che7-plugin-registry/master/terminal-sample:0.0.1
Expected result: workspace successfully created.

**OS and version:**    
Kubuntu: 18.04

**Diagnostics:** 
Error: E_BAD_DEVFILE_FORMAT - Message: Devfile schema validation failed. Error: /devfile/components/2/id ECMA 262 regex "^[a-zA-Z0-9_/-/./]{1,}:[a-zA-Z0-9_/-/.]{1,}$" does not match input string "https://raw.githubusercontent.com/azatsarynnyy/che7-plugin-registry/master/terminal-sample:0.0.1"
    at CheHelper.<anonymous> (/snapshot/chectl/lib/api/che.js:0:0)
    at Generator.throw (<anonymous>)
    at rejected (/snapshot/chectl/node_modules/tslib/tslib.js:105:69)
