### ISSUE TITLE
Rename id field of chePlugin/cheEditor component in Devfile

### ISSUE THREAD

**Issue by sleshchenko** [eclipse-che/che#13062]
### Description
Currently, we have two possible formats for model of chePlugin/cheEditor component. First one is `{PLUGIN_ID}:{PLUGIN_VERSION}`, like the following
```yaml
  name: theia
  type: cheEditor
  id: org.eclipse.che-theia:v1.0.0
```
Or another possible way how id may be defined with Custom Plugin Registry: `{PLUGIN_REGISTRY_UR}/{PLUGIN_ID}:{PLUGIN_VERSION}`, like the following:
```yaml
  name: theia
  type: cheEditor
  id: https://my-plugin-registry.com/plugins/org.eclipse.che-theia:v1.0.0
```
And it's confusing that ID field is not identifier at all. 
The goal of this issue is to find a better name for `id` field and rename it.
The initial proposal is to use `reference` instead of `id`.
Then we will have the following
```yaml
  name: theia
  type: cheEditor
  reference: org.eclipse.che-theia:v1.0.0
```
```yaml
  name: theia
  type: cheEditor
  reference: https://my-plugin-registry.com/plugins/org.eclipse.che-theia:v1.0.0
```
It looks more logical.
Note that `kuberentes`/`openshift` component has `reference` field too but with different format, it is `{LOCAL_FILE_PATH}` or `{URL_TO_FILE_CONTENT}` for them.

Note that in plugin registry naming format changes are coming and format of `reference` will be changed to something like `<publisher>/<id>/<version>`. The following issue https://github.com/eclipse/che-plugin-registry/issues/55. Field value format can be handled in scope this issue or in a separate one.

**Comment by sleshchenko** [comment]
cc @l0rd @slemeur @ibuziuk @garagatyi @skabashnyuk @mshaposhnik 
Feel free to leave your opinion/alternative proposal as a comment or just react :+1: if you agree with proposed field renaming

**Comment by l0rd** [comment]
@sleshchenko I am not sure. 

An `id` is a name that identifies something in a unique way. A `reference` is a link to something. In the case of che-plugin it's a link to the `meta.yaml` you want to refer too?

In the simplest use case, when a user writes a `devfile`, he wants a simple way to define: 

- the project he wants to clone
- the plugins he wants to add to his workspace

A project will be identified by a `location` and an optional `branch` (`refspec` to be more precise...)
A plugin will be identified by an name (`org/plugin`), an optional `version` and an optional `repository-url`.

Wouldn't be simpler to describe it like this:

```yaml 
  type: cheEditor
  name: eclipse/che-theia
  version: v1.0.0                                        # optional
  repository-url: https://my-plugin-registry.com/plugins # optional 
```

**Comment by sleshchenko** [comment]
> In the case of che-plugin it's a link to the meta.yaml you want to refer too?

I know that guys from ide2 team use `meta.yaml` that is stored on gist which is not plugin registry at all. And then it could look like the following
```yaml
  type: cheEditor
  reference: https://gist.githubusercontent.com/sleshchenko/a3b3034e0fa0220/raw/3029/meta.yaml
```
Actually, now they have to make gist to pretend plugin registry, and they configure id as `https://raw.githubusercontent.com/eclipse/che-plugin-registry/upgrade-che-theia-dev/plugins/org.eclipse.che.theia.dev:0.0.1` when actual URL is `https://raw.githubusercontent.com/eclipse/che-plugin-registry/upgrade-che-theia-dev/plugins/org.eclipse.che.theia.dev/0.0.1/meta.yaml`.

For me, the following example looks logical
```yaml
  type: cheEditor
  name: eclipse/che-theia
  reference: org.eclipse.che-theia:v1.0.0
```
because I understand it as a reference relative to Plugin Registry configured on Che Server. A reference here could be without version here as well.

I agree that multiple fields may be more straightforward than the single field(`reference`) with multiple formats. But multiple fields are less flexible, I mean if we need to add one more ability, like URL link to meta.yaml content - then we probably would need to introduce a new field to Component model. With a single `reference` field we keep our model as is.

I do not have a strong opinion whether we should use single field or multiple fields and below are listed my thoughts. 
I think that URL to content of `meta.yaml` is a valid case that can be useful and actually is used now. So, we should consider it to support.

**Comment by sleshchenko** [comment]
Note that in case of multiple fields, id is not enough since new naming convention[1] declares that id is unique per publisher and then it would look like the following:
```yaml
  type: cheEditor
  name: theia-editor
  publisher: redhat
  id: eclipse/che-theia
  version: v1.0.0                                        # optional
  repository-url: https://my-plugin-registry.com/plugins # optional 
```
Or id should include publisher what is not obvious thing to do
```yaml
  type: cheEditor
  name: theia-editor
  id: redhat/eclipse/che-theia
  version: v1.0.0                                        # optional
  repository-url: https://my-plugin-registry.com/plugins # optional 
```
[1] https://github.com/eclipse/che-plugin-registry/issues/55

**Comment by l0rd** [comment]
I think there was a misunderstanding. In my proposal:

```yml
type: cheEditor
name: eclipse/che-theia
version: v1.0.0                                        # optional
repository-url: https://my-plugin-registry.com/plugins # optional
```

- the `name` field has already the publisher. In fact the format is <publisher>/<plugin> (i.e. `eclipse` in the sample is the publisher). We can split it in two distinct fields (`publisher` and `name` but the name without the publisher doesn't make sense)
- there is no `id` field anymore . That's because `id` and `name` looks redundant and the plugin is identified `name` + `version`
- what you call `reference` is actually 'repository-url/name/version` and the case of a meta.yaml in a gist is still supported

**Comment by sleshchenko** [comment]
Sorry, maybe I missed something in https://github.com/eclipse/che-plugin-registry/issues/55
Is there any plan to change format of `id` and `name` fields in `meta.yaml`? Because as far as I understand id should be used for identifying a plugin, and name is just a pretty name ( the same as diplayName in OpenShift)
Here is existing plugin where a name is just display name but not Identifier
https://github.com/eclipse/che-plugin-registry/blob/6a90b61f6aa713767f5c137d9fb55aba070a6cf1/plugins/ms-vscode.node-debug/1.32.1/meta.yaml#L1
And here is Alex sample with new `meta.yaml` where name looks like displayName but not identifier https://github.com/eclipse/che-plugin-registry/issues/55#issuecomment-475674436

Also, I think that it may be confusing to put publisher and name of plugin into component name field, because a component name field for other component types is just alias that may be used for referencing them by commands. So, a component name used to have a free value that the user wants, and user do not have to duplicate `publisher`/`pluginName` in all commands that references this component, for example(current format is used)
```yaml
specVersion: 0.0.1
name: test
components:
  - type: cheEditor
    name: theia
    id: org.eclipse.che-theia:next 
commands:
  - name: hello
    actions:
      type:exec
      component: theia
      command: echo Hello
  - name: currDir
    actions:
      type:exec
      component: theia
      command: pwd
```
Then if a user wants to use theia but defined as another editorId, or even own dockerimage component, we just modify the component, but not commands that reference it.

@l0rd Does it make sense?
