### ISSUE TITLE
`sudo: unable to send audit message: Operation not permitted` (Ubuntu 14.04)

### ISSUE THREAD

**Issue by rarkins** [eclipse-che/che#1318]
I'm using docker compose, here is the config YAML:

```
  che:
    image: codenvy/che:latest
    command: >
      bash -c "
      sudo rm -rf /home/user/che/lib-copy/* &&
      sudo rm -rf /home/user/che/tomcat/temp/local-storage/* &&
      mkdir -p /home/user/che/lib-copy/ &&
      sudo chown -R user:user /home/user/che &&
      cp -rf /home/user/che/lib/* /home/user/che/lib-copy &&
      /home/user/che/bin/che.sh run -d
      "
    network_mode: "host"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "/home/user/che/lib:/home/user/che/lib-copy"
      - "/home/user/che/workspaces:/home/user/che/workspaces"
      - "/home/user/che/tomcat/temp/local-storage:/home/user/che/tomcat/temp/local-storage"
    container_name: che
```

Note that I'm using version 2 of the compose yml so instead of `net: host` it's now `network_mode: host`.

I'm running a standard Ubuntu 14.04 server VM on EC2 with Docker 1.10.3 installed.

Here's what I see:

``` bash
ubuntu@rarkins2:/app$ docker version
Client:
 Version:      1.10.3
 API version:  1.22
 Go version:   go1.5.3
 Git commit:   20f81dd
 Built:        Thu Mar 10 15:54:52 2016
 OS/Arch:      linux/amd64

Server:
 Version:      1.10.3
 API version:  1.22
 Go version:   go1.5.3
 Git commit:   20f81dd
 Built:        Thu Mar 10 15:54:52 2016
 OS/Arch:      linux/amd64
ubuntu@rarkins2:/app$
ubuntu@rarkins2:/app$ ls -l /var/run/docker.sock
srwxrwxrwx 1 root docker 0 May 15 17:15 /var/run/docker.sock
ubuntu@rarkins2:/app$ docker-compose up che
Starting che
Attaching to che
che               | sudo: unable to send audit message: Operation not permitted
che               | bash: line 1:     6 Segmentation fault      (core dumped) sudo rm -rf /home/user/che/lib-copy/*
che exited with code 139
```

It seems like it's a combination of problems with Ubuntu 14.04, host networking, and sudo. Removing host networking instead gets the `Running 'docker' succeeded, but 'docker ps' failed. This usually means that docker cannot reach its daemon.` error.

**Comment by TylerJewell** [comment]
@rarkins Hi.  As a guide on what we do to run Docker within a Vagrantfile, you can take a look at the bash script within this file. It gives you a sense of the steps that we take to configure a Linux host to run the Docker container properly. There is some setup of the groups and file permissions.

Typically, you get the docker ps issue when rights to /var/run/docker.sock are not setup in a way that we can use it.  Could you `chmod 777 /var/run/docker.sock` and rerun the compose file, letting us know how it goes?

https://github.com/eclipse/che/blob/2fca5b224ad3cf940556ec0d8e3659f472a76a2c/Vagrantfile

**Comment by rarkins** [comment]
@TylerJewell I ran chmod on docker.sock previously and you can check the permissions in my above bash log actually - looks correct to you?

**Comment by TylerJewell** [comment]
@rarkins -- will you humor me and run the pull request Vagrantfile. Is this successful for you?  If so, then I think I see some errors in the compose file format that I'll need to work on.  This Vagrantfile has the Linux syntax for running Docker Che.  It's a bit more manual than compose, but if this file works then we have to back track to review the compose file.  I might even attempt a Vagrantfile that launches compose instead of Docker run to verify the syntax.

https://github.com/eclipse/che/pull/1279/files

**Comment by TylerJewell** [comment]
@rarkins - Hi.  I have been working on using Docker compose with our nightly build.  We have made some adjustments.  This compose file was able to work for me.  I'll also publish a Vagrantfile so that you can see the syntax that we use to create the VM to run this in as well.  In this particular example, my VM was IP address of 192.168.28.100, so you would replace that value with the IP of the machine you are on.

```
 che:
    image: codenvy/che:nightly
    command: --remote:192.168.28.100 --skip:client run
    net: "host"
    restart: always
    environment:
      CHE_LOCAL_CONF_DIR: /container
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /home/user/che/lib:/home/user/che/lib-copy
      - /home/user/che/workspaces:/home/user/che/workspaces
      - /home/user/che/storage:/home/user/che/storage
      - /home/user/che/che.properties:/container/che.properties
    container_name: che
```
