### ISSUE TITLE
Fix NPE when kubernetes component has broken reference content

### ISSUE THREAD

**Issue by sleshchenko** [eclipse-che/che#13230]
### Description
Fix NPE when kubernetes component has deployment without meta.

### Reproduction Steps 1
1. Create a workspace from the following Devfile
<details>

<summary>Devfile</summary>

```yaml
specVersion: 0.0.1
name: chectl-generated
projects:
  - name: nodejs-sample-appp
    source: 
      location: git
      type: 'https://github.com/sleshchenko/NodeJS-Sample-App.git'
components:
  - type: kubernetes
    alias: node-js-app
    referenceContent: |
      kind: List
      apiVersion: v1
      metadata:
        name: app.kubernetes.io/name=employee-manager
      items:
        - apiVersion: apps/v1
          kind: Deployment
          spec:
            template:
              spec:
                volumes:
                  - name: mongo-persistent-storage
                    persistentVolumeClaim:
                      claimName: mongo-persistent-storage
                containers:
                  - name: mongo
                    image: mongo
                    ports:
                      - name: mongo
                        containerPort: 27017
                        protocol: TCP
                    resources: {}
                    volumeMounts:
                      - name: mongo-persistent-storage
                        mountPath: /data/db
                    terminationMessagePath: /dev/termination-log
                    terminationMessagePolicy: File
                    imagePullPolicy: Always
                restartPolicy: Always
                terminationGracePeriodSeconds: 30
                dnsPolicy: ClusterFirst
                securityContext: {}
                schedulerName: default-scheduler
        - apiVersion: apps/v1
          kind: Deployment
          spec:
            template:
              spec:
                containers:
                  - name: web
                    image: 'sleshchenko/nodejs-mongo-sample:latest'
                    ports:
                      - name: http-server
                        containerPort: 3000
                        protocol: TCP
                    env:
                      - name: MONGO_HOST
                        value: mongo
                      - name: MONGO_PORT
                        value: '27017'
                    command: ['tail']
                    args: ['-f', '/dev/null']
                    resources: {}
                    terminationMessagePath: /dev/termination-log
                    terminationMessagePolicy: File
                    imagePullPolicy: Always
                restartPolicy: Always
                terminationGracePeriodSeconds: 30
                dnsPolicy: ClusterFirst
                securityContext: {}
                schedulerName: default-scheduler
        - kind: Service
          apiVersion: v1
          metadata:
            labels:
              app.kubernetes.io/component: database
              app.kubernetes.io/name: employee-manager
            name: mongo
          spec:
            type: ClusterIP
            selector:
              app.kubernetes.io/component: database
              app.kubernetes.io/name: employee-manager
            ports:
              - port: 27017
        - kind: Service
          apiVersion: v1
          metadata:
            labels:
              app.kubernetes.io/component: nodejs-app
              app.kubernetes.io/name: employee-manager
            name: web
          spec:
            type: LoadBalancer
            selector:
              app.kubernetes.io/component: nodejs-app
              app.kubernetes.io/name: employee-manager
            ports:
              - port: 80
        - kind: Ingress
          apiVersion: extensions/v1beta1
          metadata:
            labels:
              app.kubernetes.io/component: nodejs-app
              app.kubernetes.io/name: employee-manager
            name: nodejs-ingress
          spec:
            rules:
              - host: nodejs.192.168.99.100.nip.io
                http:
                  paths:
                    - path: /
                      backend:
                        serviceName: web
                        servicePort: 80
        - kind: PersistentVolumeClaim
          apiVersion: v1
          metadata:
            labels:
              app.kubernetes.io/component: database
              app.kubernetes.io/name: employee-manager
            name: mongo-persistent-storage
          spec:
            accessModes:
              - ReadWriteOnce
            resources:
              requests:
                storage: 1Gi
  - type: chePlugin
    alias: typescript-ls
    id: 'ms-vscode.typescript:1.30.2'
commands:
  - name: build
    actions:
      - type: exec
        component: node-js-app
        command: cd {PROJECTS_ROOT}/node-js-sample && npm install
  - name: run
    actions:
      - type: exec
        component: node-js-app
        command: cd {PROJECTS_ROOT}/node-js-sample && npm install
  - name: stop
    actions:
      - type: exec
        component: node-js-app
        command: kill -9 $(ps aux | grep nodejs | ...)
```
</details>

**Expected**: Error message is shown that content is broken, like meta is missing.
**Actual**: Failed to validate content reference of component 'node-js-app' of type 'kubernetes': null

![Screenshot_20190424_155325](https://user-images.githubusercontent.com/5887312/56661452-6d8de500-66aa-11e9-9fce-2a6b519091fa.png)

### Reproduction Steps 2
1. Create a workspace from the following Devfile
<details>

<summary>Devfile</summary>

```yaml
specVersion: 0.0.1
name: chectl-generated
projects:
  - name: nodejs-sample-appp
    source: 
      location: git
      type: 'https://github.com/sleshchenko/NodeJS-Sample-App.git'
components:
  - type: kubernetes
    alias: node-js-app
    referenceContent: |
      kind: List
      apiVersion: v1
      metadata:
        name: app.kubernetes.io/name=employee-manager
      items:
        - apiVersion: apps/v1
          kind: Deployment
          spec:
            template:
              spec:
                volumes:
                  - name: mongo-persistent-storage
                    persistentVolumeClaim:
                      claimName: mongo-persistent-storage
                containers:
                  - name: mongo
                    image: mongo
                    ports:
                      - name: mongo
                        containerPort: 27017
                        protocol: TCP
                 
```
</details>

**Expected**: Error message is shown that reference content is broker, like deployment meta is required.
**Actual**: Internal Server Error occurred, error time: 2019-04-24 12:54:03

![Screenshot_20190424_160237](https://user-images.githubusercontent.com/5887312/56661440-65ce4080-66aa-11e9-8c9e-9beea4151176.png)

**OS and version:**    

**Diagnostics:**
