### ISSUE TITLE
Not able to create workspace from devfile in some cases

### ISSUE THREAD

**Issue by skabashnyuk** [eclipse-che/che#13245]
### Description
```yaml
specVersion: 0.0.1
name: demo-operator
projects:
- name: demo-operator
  clonePath: src/github.com/eivantsov/demo-operator
  source:
    type: git
    location: https://github.com/eivantsov/demo-operator.git
components:
  - type: cheEditor
    id: org.eclipse.che.editor.theia:next
  - type: chePlugin
    id: che-machine-exec-plugin:0.0.1
  - type: chePlugin
    id: ms-kubernetes-tools.vscode-kubernetes-tools:0.1.17
  - type: chePlugin
    id: ms-vscode.go:0.9.2
    memoryLimit: 3Gi
  - type: dockerimage
    image: golang:1.12.4-alpine3.9
    command: ['tail']
    args: ['-f', '/dev/null']
    mountSources: true
    memoryLimit: 2Gi
    env:
      - name: GOPATH
        value: $(CHE_PROJECTS_ROOT)
      - name: GOCACHE
        value: $(GOPATH)/.cache
```
issue
![Знімок екрана  о 09 37 05](https://user-images.githubusercontent.com/1614429/56788131-426cd800-6807-11e9-942e-d13cb27d7656.png)
![Знімок екрана  о 09 39 17](https://user-images.githubusercontent.com/1614429/56788141-4ac51300-6807-11e9-8ebe-e0b795a8f8bf.png)

ws config
```
{
  "defaultEnv": "default",
  "environments": {
    "default": {
      "machines": {
        "golang-1.12.4-alpine3.9": {
          "attributes": {},
          "servers": {},
          "volumes": {
            "projects": {
              "path": "/projects"
            }
          },
          "installers": [],
          "env": {}
        }
      },
      "recipe": {
        "type": "kubernetes",
        "content": "---\napiVersion: \"v1\"\nkind: \"List\"\nitems:\n- apiVersion: \"apps/v1\"\n  kind: \"Deployment\"\n  metadata:\n    annotations: {}\n    labels:\n      che.component.name: \"golang-1.12.4-alpine3.9\"\n    name: \"golang-1.12.4-alpine3.9\"\n  spec:\n    selector:\n      matchLabels:\n        che.component.name: \"golang-1.12.4-alpine3.9\"\n    template:\n      metadata:\n        annotations:\n          org.eclipse.che.container.golang-1.12.4-alpine3.9.machine_name: \"golang-1.12.4-alpine3.9\"\n        labels:\n          che.component.name: \"golang-1.12.4-alpine3.9\"\n        name: \"golang-1.12.4-alpine3.9\"\n      spec:\n        containers:\n        - args:\n          - \"-f\"\n          - \"/dev/null\"\n          command:\n          - \"tail\"\n          env:\n          - name: \"GOPATH\"\n            value: \"$(CHE_PROJECTS_ROOT)\"\n          - name: \"GOCACHE\"\n            value: \"$(GOPATH)/.cache\"\n          image: \"golang:1.12.4-alpine3.9\"\n          name: \"golang-1.12.4-alpine3.9\"\n          resources:\n            limits:\n              memory: \"2Gi\"\n            requests: {}\n        nodeSelector: {}\n",
        "contentType": "application/x-yaml"
      }
    }
  },
  "projects": [
    {
      "links": [],
      "name": "demo-operator",
      "attributes": {},
      "source": {
        "location": "https://github.com/eivantsov/demo-operator.git",
        "type": "git",
        "parameters": {}
      },
      "path": "/src/github.com/eivantsov/demo-operator",
      "mixins": [],
      "problems": []
    }
  ],
  "name": "demo-operator",
  "attributes": {
    "editor": "org.eclipse.che.editor.theia:next",
    "sidecar.ms-vscode.go.memory_limit": "3Gi",
    "plugins": "che-machine-exec-plugin:0.0.1,ms-kubernetes-tools.vscode-kubernetes-tools:0.1.17,ms-vscode.go:0.9.2"
  },
  "commands": [],
  "links": []
}
```
