### ISSUE TITLE
How to define endpoint for kubernetes component in devfile?

### ISSUE THREAD

**Issue by makandre** [eclipse-che/che#13268]
### Description
 

In a stack definition, I can define a server for a machine:

```json
"ui": {
  "servers": {
    "dashboard": {
      "protocol": "http",
      "port": "8081"
    }
  }
}
```

Similarly, in devfile I can define endpoint for a `dockerimage` component:

```yaml
type: dockerimage
alias: ui
image: 'test-ui:latest'
memoryLimit: 0.5G
endpoints:
  - name: dashboard
    port: 8081
    attributes:
      protocol: http
```

In both cases, this creates an endpoint in Che workspace that I can click on to open a page on my server:

![image](https://user-images.githubusercontent.com/17596240/57050563-48b9e480-6c4b-11e9-9db2-4b4239d68288.png)

But I have not figure out how to do this with a kubernetes component, which I define below (I also tried adding an ingress as well but it does not get created):

```yaml
kind: List
items:
  - kind: Pod
    apiVersion: v1
    metadata:
      name: ws
    spec:
      containers:
        - image: 'test-ui:latest'
          name: ui
          ports:
            - containerPort: 8081
              protocol: TCP
          resources:
            limits:
              memory: 512Mi
  - kind: Service
    apiVersion: v1
    metadata:
      name: dashboard
    spec:
      selector:
        name: ws
      ports:
        - port: 8081
          targetPort: 8081
```

Thanks.

### Reproduction Steps

**OS and version:**    

Che 7 post beta3, on kubernetes

**Diagnostics:**
