### ISSUE TITLE
Add alias validation in devfile

### ISSUE THREAD

**Issue by metlos** [eclipse-che/che#13267]
### Description
We used the component `name` and as of 7 beta 4 `alias` for labeling the pods and services that are created for them yet we haven't done any validation on the name or the alias.

This is a problem, because kubernetes labels have a quite strict format requirements.

### Reproduction Steps
create a devfile with a component alias with a format invalid for kubernetes lables, e.g.:

```yaml
specVersion: 0.0.1
name: che-plugin-broker
projects:
- name: che-plugin-broker
  clonePath: src/github.com/eclipse/che-plugin-broker
  source:
    type: git
    location: https://github.com/eclipse/che-plugin-broker.git
components:
- alias: oh-noes/golang
  type: dockerimage
  image: golang
  memoryLimit: 512M
  mountSources: true
  command: ['sleep', 'infinity']
  env:
  - name: GOPATH
    value: $(CHE_PROJECTS_ROOT)
  - name: GOCACHE
    value: $(GOPATH)/.cache
commands:
- name: test
  actions:
  - type: exec
    component: oh-noes/golang
    command: "cd $GOPATH/src/github.com/eclipse/che-plugin-broker; go test -v -race ./..."
```
