### ISSUE TITLE
Devfile selector for k8s components doesn't work as expected

### ISSUE THREAD

**Issue by l0rd** [eclipse-che/che#13308]
### Description

When using a devfile with the following components:

```yaml
  - type: kubernetes
    alias: mvn-container
    reference: https://raw.githubusercontent.com/redhat-developer/devfile/update-petclinic/petclinic.yaml
    selector:
      app.kubernetes.io/component: webapp
  - type: kubernetes
    reference: https://raw.githubusercontent.com/redhat-developer/devfile/update-petclinic/petclinic.yaml
    selector:
      app.kubernetes.io/component: database
```

I get the following error:

![image](https://user-images.githubusercontent.com/606959/57534640-c911d100-7340-11e9-9c66-fbae4db815b2.png)

And if I look into the workspace recipe there are 2 services, 2 deployments etc...because they are not filtered out.

### Reproduction Steps

Create a workspace using the following devfile

```yaml
---
specVersion: 0.0.1
name: petclinic-dev-environment
projects:
  - name: petclinic
    source:
      type: git
      location: 'https://github.com/spring-projects/spring-petclinic.git'
components:
  - type: kubernetes
    alias: mvn-container
    reference: https://gist.githubusercontent.com/l0rd/52eda1d1b57878a218cba17c0c93a477/raw/9a2d56e777d22e77c25c45744caea35bb62d8688/petclinic.yaml
    selector:
      app.kubernetes.io/component: webapp
  - type: kubernetes
    reference: https://gist.githubusercontent.com/l0rd/52eda1d1b57878a218cba17c0c93a477/raw/9a2d56e777d22e77c25c45744caea35bb62d8688/petclinic.yaml
    selector:
      app.kubernetes.io/component: database
  - type: cheEditor
    id: eclipse/che-theia/next
  - type: chePlugin
    id: redhat/java/0.43.0
commands:
  - name: build
    actions:
      - type: exec
        component: mvn-container
        command: mvn package
        workdir: /projects/spring-petclinic
```

**OS and version:**    

Che 7 nightly
