### ISSUE TITLE
devfile: che plugins (vscode) and che editors should accept volumes

### ISSUE THREAD

**Issue by sunix** [eclipse-che/che#13318]
### Description
In some case, we would like to share a volume with a che plugin

for instance with this devfile, where we want to share the same volume for the `quay-io-quarku` component and the `java-ls` component
but the `java-ls` does not accept volumes:

```yaml
specVersion: 0.0.1
name: quarkus-che-demo
projects:
  - source:
      type: git
      location: 'https://github.com/sunix/che-quarkus-demo'
    name: che-quarkus-demo
components:
  - alias: quay-io-quarkus-cent
    type: dockerimage
    image: quay.io/quarkus/centos-quarkus-maven
    memoryLimit: 512M
    mountSources: true
    command:
      - tail
    args:
      - '-f'
      - /dev/null
    volumes:
      - name: mavenrepo
        containerPath: /root/.m2
  - type: chePlugin
    alias: java-ls
    id: redhat/java/0.43.0
    memoryLimit: 2Gi
    volumes:
      - name: mavenrepo
        containerPath: /root/.m2
  - type: cheEditor
    alias: theia-editor
    id: eclipse/che-theia/next
  -
    alias: git-devtools
    type: dockerimage
    image: sunix/git-devtools
    mountSources: true
    memoryLimit: 256M
    command:
      - tail
    args:
      - '-f'
      - /dev/null
commands:
  - name: 'mvn compile quarkus:dev'
    actions:
      - type: exec
        command: "kill -9 $(ps aux | grep 'java' | awk '{print $2}'); mvn compile quarkus:dev"
        component: quay-io-quarkus-cent
        workdir: /projects/che-quarkus-demo/sunix-quarkus-demo
```

But:

```
workspace:start --devfile=quarkus.devfile
  ✔ Retrieving Che Server URL...http://che-che.192.168.39.14.nip.io
  ✔ Verify if Che server is running
  ✖ Create workspace from Devfile quarkus.devfile
    → E_BAD_DEVFILE_FORMAT - Message: Devfile schema validation failed. Error: (/components/1/volumes):The object must not have a property whose name is "volumes".
Error: E_BAD_DEVFILE_FORMAT - Message: Devfile schema validation failed. Error: (/components/1/volumes):The object must not have a property whose name is "volumes".
    at CheHelper.<anonymous> (/projects/chectl/src/api/che.ts:230:15)
    at Generator.throw (<anonymous>)
    at rejected (/projects/chectl/src/api/che.ts:16:65)
/projects/chectl # 
```

**OS and version:**    
Minikube/chectl with helm single user.
