### ISSUE TITLE
Websocket over ingress instead direct access ?

### ISSUE THREAD

**Issue by langoureaux-s** [eclipse-che/che#13320]
## Description

When I deploy che from helm template, I shoold that all traffic throught out the ingress, but I look that websocket connect on host in port 8080. This a problem because of we use proxy server that allow only 80 / 443.

There are a way to use ingress for websocket when we create workspace ?

Reproduction Steps

Deploy che form helm with the following settings:

```yaml
global:
  multiuser: true
  cheNamespace: che
  cheWorkspacesNamespace: che
  ingressDomain: XXX.XXX.XXX.XXX.nip.io
```

## OS and version:
Debian 9, with kubernetes 1.13.5 and che 7.0.0-beta-5.0-SNAPSHOT

## Diagnostics:
Websocket use 8080 port instead to use ingress.
