### ISSUE TITLE
Add an ability to use Devfile as part of Stack API

### ISSUE THREAD

**Issue by sleshchenko** [eclipse-che/che#13338]
### Description
This is issues about adding an ability to use Defile as part of Stack.
It should cover `Stacks for End-User` user story of the following epic https://github.com/eclipse/che/issues/12924.

It includes reworking Stack API in the same way as we did with Workspace API.
Add a new field `devfile` to stack object, modify REST API, DAOs to respect it.
Then stack can be defined with workspace config or devfile mutually exclusive.

As an example of Stack with devfile defined

<details>
<summary>Stacks with Devfile in JSON format</summary>

```json
  {
    "id": "che7-preview",
    "creator": "ide",
    "name": "Che 7",
    "description": "Workspace.next sidecars and Theia as IDE",
    "scope": "general",
    "tags": [
      "ws.next",
      "Theia",
      "Java",
      "JDK",
      "Node.JS",
      "NPM",
      "Yeoman"
    ],
    "components": [
      {
        "name": "Centos",
        "version": "7"
      },
      {
        "name": "OpenJDK",
        "version": "1.8.0_181"
      },
      {
        "name": "NodeJS",
        "version": "8.12.0"
      },
      {
        "name": "NPM",
        "version": "6.4.1"
      }
    ],
    "devfile": {
      "name": "che7",
      "components": [
        {
          "type": "cheEditor",
          "id": "eclipse/che-theia/next"
        },
        {
          "type": "chePlugin",
          "id": "eclipse/che-machine-exec-plugin/0.0.1"
        },
        {
          "type": "kubernetes",
          "referenceContent": "kind: List\nitems:\n - \n  apiVersion: v1\n  kind: Pod\n  metadata:\n   name: ws\n  spec:\n   containers:\n    - \n     image: 'eclipse/che-dev:nightly'\n     name: dev\n     resources:\n      limits:\n       memory: 512Mi\n"
        }
      ]
    },
    "stackIcon": {
      "name": "type-che7.svg",
      "mediaType": "image/svg+xml"
    }
  }
```
</details>

<details>
<summary>Stacks with Devfile in YAML format</summary>

```yaml
---
id: che7-preview
creator: ide
name: Che 7
description: Workspace.next sidecars and Theia as IDE
scope: general
tags:
- ws.next
- Theia
- Java
- JDK
- Node.JS
- NPM
- Yeoman
components:
- name: Centos
  version: '7'
- name: OpenJDK
  version: 1.8.0_181
- name: NodeJS
  version: 8.12.0
- name: NPM
  version: 6.4.1
devfile:
  name: che7
  components:
  - type: cheEditor
    id: eclipse/che-theia/next
  - type: chePlugin
    id: eclipse/che-machine-exec-plugin/0.0.1
  - type: kubernetes
    referenceContent: |
      kind: List
      items:
      - 
      apiVersion: v1
      kind: Pod
      metadata:
        name: ws
      spec:
        containers:
        - image: 'eclipse/che-dev:nightly'
          name: dev
          resources:
            limits:
             memory: 512Mi
stackIcon:
  name: type-che7.svg
  mediaType: image/svg+xml
```
</details>
