### ISSUE TITLE
Unable to set `JAVA_OPTS` or `MAVEN_OPTS` in kubernetes component of devfile

### ISSUE THREAD

**Issue by sleshchenko** [eclipse-che/che#13340]
### Description
Unable to set `JAVA_OPTS` or `MAVEN_OPTS` in kubernetes component of devfile since Che Server overrides it with its owns values.

### Reproduction Steps
1. Create a workspace from the following Devfile.
<details>
<summary>Devfile</summary>

```yaml
specVersion: 0.0.1
name: spring-petclinic
projects:
  - name: spring-petclinic
    source:
      type: git
      location: 'https://github.com/sleshchenko/spring-petclinic.git'
components:
  - alias: theia-ide
    type: cheEditor
    id: eclipse/che-theia/next
  - alias: mysql
    type: openshift
    referenceContent: |
      apiVersion: v1
      kind: List
      items:
      - apiVersion: v1
        kind: Pod
        metadata:
          name: mysql-petclinic
          labels:
            app.kubernetes.io/name: petclinic
            app.kubernetes.io/component: mysql
        spec:
          containers:
          - name: mysql
            image: centos/mysql-57-centos7
            env:
            - name: MYSQL_USER
              value: petclinic
            - name: MYSQL_PASSWORD
              value: petclinic
            - name: MYSQL_ROOT_PASSWORD
              value: petclinic
            - name: MYSQL_DATABASE
              value: petclinic
            volumeMounts:
            - mountPath: /var/lib/mysql/data
              name: mysql-storage
            ports:
            - containerPort: 3306
              protocol: TCP
            resources:
              limits:
                memory: 512Mi
          volumes:
          - name: mysql-storage
            persistentVolumeClaim:
              claimName: mysql-storage
      - kind: Service
        apiVersion: v1
        metadata:
          name: mysql
          labels:
            app.kubernetes.io/name: petclinic
            app.kubernetes.io/component: mysql
        spec:
          ports:
            - name: mysql
              port: 3306
              targetPort: 3306
          selector:
            app.kubernetes.io/name: petclinic
            app.kubernetes.io/component: mysql
      - kind: PersistentVolumeClaim
        apiVersion: v1
        metadata:
          labels:
            app: petclinic
          name: mysql-storage
        spec:
          accessModes:
          - ReadWriteOnce
          resources:
            requests:
              storage: 1Gi
  - alias: petclinic
    type: openshift
    referenceContent: |
      apiVersion: v1
      kind: List
      items:
      - apiVersion: v1
        kind: Pod
        metadata:
          name: petclinic
          labels:
            app.kubernetes.io/name: petclinic
            app.kubernetes.io/component: web-app
        spec:
          containers:
          - name: server
            image: sleshchenko/petclinic
            ports:
            - containerPort: 8080
              protocol: TCP
            resources:
              limits:
                memory: 2Gi
            env:
            - name: MAVEN_OPTS
              value: '-Xmx1500m'
            volumeMounts:
            - mountPath: /projects
              name: projects
          volumes:
          - name: projects
            persistentVolumeClaim:
              claimName: projects
      - kind: Service
        apiVersion: v1
        metadata:
          name: petclinic
          labels:
            app.kubernetes.io/name: petclinic
            app.kubernetes.io/component: web-app
        spec:
          ports:
            - name: web
              port: 8080
              targetPort: 8080
          selector:
            app.kubernetes.io/name: petclinic
            app.kubernetes.io/component: web-app
      - apiVersion: v1
        kind: Route
        metadata:
          name: nodejs-web-endpoint
          labels:
            app.kubernetes.io/name: petclinic
            app.kubernetes.io/component: web-app
        spec:
          to:
            kind: Service
            name: petclinic
          port:
            targetPort: web
      - apiVersion: v1
        kind: PersistentVolumeClaim
        metadata:
          name: projects
          labels:
            app.kubernetes.io/name: petclinic
            app.kubernetes.io/component: web-app
        spec:
          accessModes:
           - ReadWriteOnce
          resources:
            requests:
              storage: 1Gi
    entrypoints:
      - containerName: server
        command: ["tail"]
        args: ["-f", "/dev/null"]
commands:
  - name: build
    actions:
      - type: exec
        component: petclinic
        command: './mvnw package'
        workdir: /projects/spring-petclinic
  - name: run
    actions:
      - type: exec
        component: petclinic
        command: java -jar /spring-petclinic-2.1.0.BUILD-SNAPSHOT.jar --spring.profiles.active=mysql
        workdir: /projects/spring-petclinic
  - name: mysql-version
    actions:
      - type: exec
        component: mysql
        command: mysql --version
```
</details>

2. Open a terminal in `server` container.
3. Check `MAVEN_OPTS` env var.
Expected: MAVEN_OPTS=-Xmx1500m
Actual: Value from Che Server configuration `-XX:MaxRAM=150m -XX:MaxRAMFraction=2 -... -Djava.security.egd=file:/dev/./urandom`
https://github.com/eclipse/che/blob/master/assembly/assembly-wsmaster-war/src/main/webapp/WEB-INF/classes/che/che.properties#L80
And as result maven build fails with `Out of memory`
