### ISSUE TITLE
Che not loading Theia extension specified in meta.yaml

### ISSUE THREAD

**Issue by johnmcollier** [eclipse-che/che#13363]
### Description
I have the following meta.yaml:
```
id: my-che-plugin
apiVersion: v2
version: 0.0.1
type: Che Plugin
name: my-che-plugin
title: my-che-plugin
description: Simple Che plugin
publisher: <me>
category: Other
url: http://<my-plugin-server>/0.0.1/my-che-plugin.tar.gz
firstPublicationDate: "2019-05-10"
spec:
  endpoints:
  - name: "my-che-sidecar-service"
    public: true
    targetPort: 8080
  containers:
  - name: my-che-sidecar
    image: johncollier/my-che-sidecar
    volumes:
      - mountPath: "/projects"
        name: projects
    ports:
      - exposedPort: 8080
  editors:
   - id: org.eclipse.che.editor.theia
     plugins: [my_plugin:1.0.0]
```

The tarball at `http://<my-plugin-server>/0.0.1/my-che-plugin.tar.gz` contains a `che-dependency.yaml` and a .theia file for my extension.

When I load a Che workspace that's pointing to this plugin, the sidecar image starts, but the Theia extension is never loaded. I don't see anything in the Theia container logs that shows it tried to load the extension, so it seems like Theia isn't even seeing it?

The following meta.yaml worked prior to the merged of `meta.yaml` and `che-plugin.yaml`, so I'm not sure if I'm missing something that now needs to be added:
```
id: my-che-plugin
version: 0.0.1
type: Che Plugin
name: my-che-plugin
title: my-che-plugin
description: Simple Che plugin
url: http://<my-plugin-server>/0.0.1/my-che-plugin.tar.gz
```

**OS and version:**    
OKD 3.11
Nightly image of Che 7

**Theia logs:** [theia_logs.txt](https://github.com/eclipse/che/files/3193293/theia_logs.txt)
