### ISSUE TITLE
mysql commands do not work via devfile commands (Theia Tasks)

### ISSUE THREAD

**Issue by sleshchenko** [eclipse-che/che#13416]
### Description
mysql commands do not work via devfile commands (Theia Tasks)

### Reproduction Steps
1. Create a workspace from the following Devfile
<details>
<summary>Devfile</summary>

```yaml
---
apiVersion: 1.0.0
metadata:
  name: java-mysql-theia-kubernetes
components:
  -
    type: cheEditor
    id: eclipse/che-theia/next
  -
    type: chePlugin
    id: eclipse/che-machine-exec-plugin/0.0.1
  -
    type: kubernetes
    alias: web
    referenceContent: |
      kind: List
      items:
      -
        apiVersion: v1
        kind: Pod
        metadata:
          name: web
        spec:
          containers:
          -
            image: registry.centos.org/che-stacks/centos-jdk8
            name: dev
            ports:
            - containerPort: 8080
              protocol: TCP
            resources:
              limits:
                memory: 512Mi
            volumeMounts:
            - name: projects
              mountPath: /projects
          volumes:
          - name: projects
            persistentVolumeClaim:
              claimName: projects
      -
        apiVersion: v1
        kind: PersistentVolumeClaim
        metadata:
          name: projects
          labels:
            app.kubernetes.io/name: employee-manager
            app.kubernetes.io/component: nodejs-app
        spec:
          accessModes:
           - ReadWriteOnce
          resources:
            requests:
              storage: 1Gi
  -
    type: kubernetes
    alias: mysql
    referenceContent: |
      kind: List
      items:
      -
        apiVersion: v1
        kind: Pod
        metadata:
          name: db
          labels:
            type: db
        spec:
          containers:
          -
            image: centos/mysql-57-centos7
            name: mysql
            ports:
            - name: mysql
              containerPort: 3306
              protocol: TCP
            env:
            - name: MYSQL_USER
              value: petclinic
            - name: MYSQL_ROOT_PASSWORD
              value: password
            - name: MYSQL_PASSWORD
              value: password
            - name: MYSQL_DATABASE
              value: petclinic
            resources:
              limits:
                memory: 256Mi
      -
        apiVersion: v1
        kind: Service
        metadata:
          name: db
        spec:
          selector:
            type: db
          ports:
          - name: mysql
            port: 3306
            protocol: TCP
            targetPort: mysql
commands:
  - name: open database command line
    actions:
    - type: exec
      component: mysql
      command: mysql -u $MYSQL_USER -p$MYSQL_PASSWORD --database=$MYSQL_DATABASE
```

</details>

2. Try to run `open database command line` tasks.
**Expected**: terminal with mysql is run
**Actual**: `mysql command is not found` message is shown

Note that if you open terminal in `mysql` container and execute command (`mysql -u $MYSQL_USER -p$MYSQL_PASSWORD --database=$MYSQL_DATABASE`) there then it works just fine.

Also, we did some short investigation with @AndrienkoAleksandr and made sure that exec-plugin and terminal have the same uid in shell.

**OS and version:**    
Was reproduced on Che deployed on Minishift.

**Diagnostics:**
