### ISSUE TITLE
Cannot create workspace from devfile via API when entrypoint is overridden

### ISSUE THREAD

**Issue by mmorhun** [eclipse-che/che#13422]
### Description
Che server responds with 500 error when try to create a workspace from some devfiles via Che API, where as chectl works fine with such devfiles. Probably, the reason is in restriction for parent name field [here](https://github.com/eclipse/che/blob/master/wsmaster/che-core-sql-schema/src/main/resources/che-schema/7.0.0-beta4.0/1__add_devfile.sql#L200).

### Reproduction Steps

Use the `POST <che-server>/api/workspace/devfile` method to create workspace from the following devfile:

<details>

```
specVersion: 0.0.1
name: chectl-generated
projects:
  - source:
      type: git
      location: 'https://github.com/sleshchenko/NodeJS-Sample-App.git'
    name: NodeJS-Sample-App.git
components:
  - type: cheEditor
    alias: theia-editor
    id: eclipse/che-theia/next
  - type: chePlugin
    alias: typescript-ls
    id: che-incubator/typescript/1.30.2
  - type: chePlugin
    id: eclipse/che-machine-exec-plugin/0.0.1
  - type: dockerimage
    alias: theia-dev
    image: eclipse/che-theia-dev:next
    endpoints:
       - name: desktop
         port: 6080
         attributes:
           protocol: http
           public: 'true'
    mountSources: true
    memoryLimit: 3072M
  - type: kubernetes
    alias: employee-manager
    reference: deploy_k8s.yaml
    referenceContent: |
      ---
      apiVersion: v1
      kind: List
      items:
      -
        apiVersion: apps/v1
        kind: Deployment
        metadata:
          name: mongo
          labels:
            app.kubernetes.io/name: employee-manager
            app.kubernetes.io/component: database
        spec:
          selector:
            matchLabels:
              app.kubernetes.io/name: employee-manager
              app.kubernetes.io/component: database
          template:
            metadata:
              labels:
                app.kubernetes.io/name: employee-manager
                app.kubernetes.io/component: database
              name: mongo
            spec:
              containers:
              - name: mongo
                image: mongo
                ports:
                - name: mongo
                  containerPort: 27017
                volumeMounts:
                    - name: mongo-persistent-storage
                      mountPath: /data/db
              volumes:
                - name: mongo-persistent-storage
                  persistentVolumeClaim:
                    claimName: mongo-persistent-storage
      -
        apiVersion: v1
        kind: Service
        metadata:
          name: mongo
          labels:
            app.kubernetes.io/name: employee-manager
            app.kubernetes.io/component: database
        spec:
          ports:
            - port: 27017
              targetPort: 27017
          selector:
            app.kubernetes.io/name: employee-manager
            app.kubernetes.io/component: database
      -
        apiVersion: v1
        kind: PersistentVolumeClaim
        metadata:
          name: mongo-persistent-storage
          labels:
            app.kubernetes.io/name: employee-manager
            app.kubernetes.io/component: database
        spec:
          accessModes:
          - ReadWriteOnce
          resources:
            requests:
              storage: 1Gi
      -
        apiVersion: apps/v1
        kind: Deployment
        metadata:
          name: nodejs-app
          labels:
            app.kubernetes.io/name: employee-manager
            app.kubernetes.io/component: nodejs-app
        spec:
          selector:
            matchLabels:
              app.kubernetes.io/name: employee-manager
              app.kubernetes.io/component: nodejs-app
          template:
            metadata:
              labels:
                app.kubernetes.io/name: employee-manager
                app.kubernetes.io/component: nodejs-app
              name: nodejs-app
            spec:
              containers:
              - name: web-app
                image: "sleshchenko/nodejs-mongo-sample:latest"
                ports:
                - containerPort: 3000
                  name: http-server
                env:
                  - name: MONGO_HOST
                    value: "mongo"
                  - name: MONGO_PORT
                    value: "27017"
                volumeMounts:
                  - name: projects
                    mountPath: /projects
              volumes:
                - name: projects
                  persistentVolumeClaim:
                    claimName: projects
      -
        apiVersion: v1
        kind: Service
        metadata:
          name: web
          labels:
            app.kubernetes.io/name: employee-manager
            app.kubernetes.io/component: nodejs-app
        spec:
          type: LoadBalancer
          ports:
            - name: web
              port: 80
              targetPort: 3000
              protocol: TCP
          selector:
            app.kubernetes.io/name: employee-manager
            app.kubernetes.io/component: nodejs-app
      -
        apiVersion: extensions/v1beta1
        kind: Ingress
        metadata:
          name: nodejs-ingress
          labels:
            app.kubernetes.io/name: employee-manager
            app.kubernetes.io/component: nodejs-app
          annotations:
            kubernetes.io/ingress.class: "nginx"
        spec:
          rules:
          - host: nodejs.192.168.99.100.nip.io
            http:
              paths:
              - path: /
                backend:
                  serviceName: web
                  servicePort: 80
      -
        apiVersion: v1
        kind: PersistentVolumeClaim
        metadata:
          name: projects
          labels:
            app.kubernetes.io/name: employee-manager
            app.kubernetes.io/component: nodejs-app
        spec:
          accessModes:
          - ReadWriteOnce
          resources:
            requests:
              storage: 1Gi

    entrypoints:
    - containerName: web-app
      command: ["tail"]
      args: ["-f", "/dev/null"]
commands:
  - name: Test echo hw
    actions:
      - type: exec
        component: employee-manager
        command: ls -l && echo ' hello world'
        workdir: /projects
  - name: Echo test works
    actions:
      - type: exec
        component: theia-dev
        command: ls -l && echo ' hello world'
        workdir: /projects
  - name: Test echo hw only
    actions:
      - type: exec
        component: employee-manager
        command: echo "hello world"
        workdir: /projects
  - name: run
    actions:
      - type: exec
        component: employee-manager
        command: cd ${CHE_PROJECTS_ROOT}/nodejs-mongo-app/EmployeeDB/ && npm install && node app.js
```

</details>
