### ISSUE TITLE
Java LS "Classpath is incomplete" warning when loading petclinic

### ISSUE THREAD

**Issue by l0rd** [eclipse-che/che#13427]
### Description

After I have created a workspace using the following devfile

```yaml
---
specVersion: 0.0.1
name: petclinic-dev-environment
projects:
  - name: petclinic
    source:
      type: git
      location: 'https://github.com/spring-projects/spring-petclinic.git'
components:
  - type: kubernetes
    alias: mvn-container
    reference: https://gist.githubusercontent.com/l0rd/52eda1d1b57878a218cba17c0c93a477/raw/9a2d56e777d22e77c25c45744caea35bb62d8688/petclinic.yaml
    selector:
      app.kubernetes.io/component: webapp
  - type: kubernetes
    reference: https://gist.githubusercontent.com/l0rd/52eda1d1b57878a218cba17c0c93a477/raw/9a2d56e777d22e77c25c45744caea35bb62d8688/petclinic.yaml
    selector:
      app.kubernetes.io/component: database
  - type: chePlugin
    id: redhat/java/0.45.0
  - type: chePlugin
    id: redhat/vscode-yaml/0.4.0
commands:
  - name: build
    actions:
      - type: exec
        component: mvn-container
        command: mvn package
        workdir: /projects/spring-petclinic
```
 
[a classpath incomplete warning](https://github.com/redhat-developer/vscode-java/wiki/%22Classpath-is-incomplete%22-warning
) is shown every time a Java file is opened:

![image](https://user-images.githubusercontent.com/606959/58441302-44b1a300-80e1-11e9-9541-247a7614ff9c.png) 

### Reproduction Steps

Start a workspace using [this devfile](https://gist.githubusercontent.com/l0rd/52eda1d1b57878a218cba17c0c93a477/raw/8ef7ff447a7164215395d6bc7d70b49363ebae86/devfile.yaml):

```
chectl workspace:start --devfile=https://gist.githubusercontent.com/l0rd/52eda1d1b57878a218cba17c0c93a477/raw/8ef7ff447a7164215395d6bc7d70b49363ebae86/devfile.yaml
```

**OS and version:** 

macOS / minikube / nightly che-server / chectl / helm / jtd ls 0.45.0
