### ISSUE TITLE
che.openshift.io: Cannot start workspace with the container image`jekyll/builder`

### ISSUE THREAD

**Issue by sunix** [eclipse-che/che#13475]
### Description
On che.openshift.io (works well with minikube), when trying to build a workspace with a container image `jekyll/builder`, the workspace is failling to start with the error:
```
[che-jwtproxy] Created container
[che-jwtproxy] Started container
[jekyll-builder] Successfully pulled image "jekyll/builder"
[jekyll-builder] Error: Error response from daemon: create 44bc6c8e3da4e514d609ac4b21734638fc21ab0e78995a43dd971ce962a96d25: error while creating volume path '/var/lib/docker/volumes/44bc6c8e3da4e514d609ac4b21734638fc21ab0e78995a43dd971ce962a96d25/_data': mkdir /var/lib/docker/volumes/44bc6c8e3da4e514d609ac4b21734638fc21ab0e78995a43dd971ce962a96d25: permission denied
[jekyll-builder] pulling image "eclipse/che-machine-exec"
[jekyll-builder] Successfully pulled image "eclipse/che-machine-exec"
[jekyll-builder] Created container
[jekyll-builder] Started container
[jekyll-builder] pulling image "eclipse/che-theia:next"
[jekyll-builder] Successfully pulled image "eclipse/che-theia:next"
[jekyll-builder] Created container
[jekyll-builder] Started container
[jekyll-builder] pulling image "jekyll/builder"
[jekyll-builder] Successfully pulled image "jekyll/builder"
[jekyll-builder] Error: Error response from daemon: create 121e553cb43099651122ac0edd9a8b49bdab5a595e44c167d929d6baedbfd264: error while creating volume path '/var/lib/docker/volumes/121e553cb43099651122ac0edd9a8b49bdab5a595e44c167d929d6baedbfd264/_data': mkdir /var/lib/docker/volumes/121e553cb43099651122ac0edd9a8b49bdab5a595e44c167d929d6baedbfd264: permission denied
```

### Reproduction Steps
Use a devfile with a container image like this one
```yaml
specVersion: 0.0.1
name: che-docs
projects:
  - source:
      type: git
      location: 'https://github.com/eclipse/che-docs'
    name: che-docs
components:
  - alias: jekyll-builder
    type: dockerimage
    image: jekyll/builder
    memoryLimit: 512M
    mountSources: true
    command:
      - tail
    args:
      - '-f'
      - /dev/null
commands:
  - name: jekyll serve --host 0.0.0.0
    actions:
      - type: exec
        command: >-
          mkdir -p /projects/che-docs/src/main/_site/ && jekyll serve --host
          0.0.0.0
        component: jekyll-builder
        workdir: /projects/che-docs/src/main
```
Run it as a factory on che.openshift.io:

https://che.openshift.io/f?url=http://che.openshift.io/?f=https://raw.githubusercontent.com/sunix/che-docs/687f4a18f88b8e3ce520d70ffc26b7e8bd6937a0/devfile.yaml

![Selection_273](https://user-images.githubusercontent.com/650571/58895200-b4ccb400-86f3-11e9-8bf0-babb71cf5b76.png)

![Selection_272](https://user-images.githubusercontent.com/650571/58895213-bac29500-86f3-11e9-9ae1-1ee894d49874.png)

**OS and version:**    
che.openshift.io
