### ISSUE TITLE
cannot execute `jekyll` command from a containerimage `jekyll/builder`

### ISSUE THREAD

**Issue by sunix** [eclipse-che/che#13481]
### Description
To investigate:
with a devfile containerimage `jekyll/builder` like this one:
```yaml
specVersion: 0.0.1
name: che-docs
projects:
  - source:
      type: git
      location: 'https://github.com/eclipse/che-docs'
    name: che-docs
components:
  - alias: jekyll-builder
    type: dockerimage
    image: jekyll/builder
    memoryLimit: 512M
    mountSources: true
    command:
      - tail
    args:
      - '-f'
      - /dev/null
commands:
  - name: jekyll serve --host 0.0.0.0
    actions:
      - type: exec
        command: >-
          mkdir -p /projects/che-docs/src/main/_site/ && jekyll serve --host
          0.0.0.0
        component: jekyll-builder
        workdir: /projects/che-docs/src/main
```
It is not possible to run the jekyll command:

```
/usr/jekyll/bin/jekyll: exec: line 15: /usr/local/bundle/bin/jekyll: not found
```
This was working 2 weeks ago ... and image has not changed recently so something has change in Che ? user and permession issue ?

**OS and version:**    
minikube, chectl single user

**Comment by sunix** [comment]
something is wrong because of 

https://github.com/envygeeks/jekyll-docker/blob/master/repos/jekyll/copy/all/usr/jekyll/bin/jekyll#L13

```
# --
# The assumption here is that if we aren't ID 0 then
#   something we wrapped, recalled us, so we need to ship
#   them to the right spot.  This can happen in one
#   scenario (when you do `jekyll new`.)
# --
if [ "$(id -u)" != "0" ]; then
  exec $BUNDLE_BIN/jekyll "$@"
fi
```
And we are no more user 0 in the latest version of Che on kubernetes i guess.

**Comment by sunix** [comment]
workaround:  performing a `bundle install` before running jekyll

```yaml
specVersion: 0.0.1
name: che-docs
projects:
  - source:
      type: git
      location: 'https://github.com/eclipse/che-docs'
    name: che-docs
components:
  - alias: jekyll-builder
    type: dockerimage
    image: jekyll/builder:3.8
    memoryLimit: 512M
    mountSources: true
    command: ['tail']
    args: ['-f', '/dev/null']
commands:
  - name: jekyll serve --host 0.0.0.0
    actions:
      - type: exec
        command: >-
          bundle install &&
          jekyll serve --host
          0.0.0.0
        component: jekyll-builder
        workdir: /projects/che-docs/src/main
```
