### ISSUE TITLE
The commands in project samples are not compatible with commands in devfile format

### ISSUE THREAD

**Issue by ashumilova** [eclipse-che/che#13514]
The commands, that are listed in project [samples](https://github.com/eclipse/che/blob/master/ide/che-core-ide-templates/src/main/resources/samples.json), have the following format
```
"commands": [
      {
        "name": "build and run",
        "type": "custom",
        "commandLine": "cd ${current.project.path} \ngcc -o Hello Hello.c \n./Hello",
        "attributes": {
          "previewUrl": "",
          "goal": "Run"
        }
      }
    ]
```
and are added to workspace along with the projects by dashboard. 
The format of those commands works fine with workspace config and is not compatible with devfile format. This can be fixed on the application side - like converting from one format to another. But there is one problem - setting the commands required field - **component**(where to be executed), on this stage it's not clear.
In devfile command format:
```
commands:
  - name: build
    actions:
      - type: exec
        component: petclinic
        command: './mvnw package'
        workdir: /projects/spring-petclinic
```
