### ISSUE TITLE
New devfile based stacks should contain samples

### ISSUE THREAD

**Issue by l0rd** [eclipse-che/che#13529]
### Description

Currently a Che stack (i.e. `java-maven`) is associated to one or more samples (e.g. `web-java-petclinic` and `console-java-simple`). But often different samples of the same stack requires different settings (env variables, memory, commands) and making generic stacks that work with every project is hard.

Another point is that from a UX point of view it's more straightforward to select a `vue.js` or a `angular` stack rather than selecting the node js stack and then the angular sample.

So this issue is about the proposal to associate every stack to one unique project sample. The project, as well as the commands, would be specified in the the stack devfiles. The user would still be able to override the sample stack project and commands.

![image](https://user-images.githubusercontent.com/606959/59353098-8158dd80-8d22-11e9-8e21-909e36887746.png)

**Comment by l0rd** [comment]
| stack | sample |
| ----- | ------ |
| java-maven | https://github.com/che-samples/console-java-simple |
| java-gradle | https://github.com/che-samples/console-java-simple |
| java-spring-web | https://github.com/che-samples/web-java-spring.git |
| java-vertx | https://github.com/vert-x3/vertx-examples |
| java-postgresql | https://github.com/che-samples/web-java-spring-petclinic/tree/ |
| apache-camel | https://github.com/apache/camel/tree/master/examples/camel-example-spring-boot |
| python3 | https://github.com/che-samples/console-python3-simple.git |
| django | https://github.com/gothinkster/django-realworld-example-app |
| c# | https://github.com/che-samples/dotnet-web-simple.git |
| ASP.NET | https://github.com/che-samples/dotnet-web-simple.git |
| Go | https://github.com/golang/example/tree/master/outyet |
| Go | https://github.com/xesina/golang-echo-realworld-example-app |
| PHP | https://github.com/che-samples/web-php-simple |
| PHP-laravel | https://github.com/gothinkster/laravel-realworld-example-app |
| PHP-symfony | https://github.com/gothinkster/laravel-realworld-example-app |
| PHP-mysql | https://github.com/taniarascia/pdo/tree/master |
| nodejs | https://github.com/che-samples/web-nodejs-sample |
| nodejs-mongo | https://github.com/gothinkster/node-express-realworld-example-app |
| react | https://github.com/gothinkster/react-redux-realworld-example-app |
| angular | https://github.com/gothinkster/angular-realworld-example-app |
| vuejs | https://github.com/gothinkster/vue-realworld-example-app |

**Comment by skabashnyuk** [comment]
@l0rd is this issue https://github.com/eclipse/che/issues/13533 will be handled in your pr  https://github.com/eclipse/che-devfile-registry/pull/15 ? Do you know?

**Comment by l0rd** [comment]
@skabashnyuk that issue looked related to an outdated sample. The devfile I have added in the PR is not affected by that problem.

**Comment by l0rd** [comment]
Other nice to have stacks...

| stack |
| ------ |
| quarkus |  
| jib |  
| ko |  
| micronaut |
| microprofile |
| kubernetes-operator |
| che |  
| theia |  
| che-operator |  
| chectl |  
| che-plugin-broker |  
| vs-code-extension-dev |  
| che-doc |

**Comment by skabashnyuk** [comment]
@l0rd are they blocker for GA?

**Comment by l0rd** [comment]
"nice to have"

**Comment by metlos** [comment]
Before I leave on vacation, let me describe the state of the outstanding samples as I am aware about them.

## Vuejs

We can either wait for #13672 to be finished or, if we postpone that issue to 7.1 but need to have a vuejs sample in 7.0, we can use the following devfile in the sample (it will lack support for Vue-specific stuff but will have support for typescript/javascript and npm):

```yaml
---
apiVersion: 1.0.0
metadata:
  name: vuejs
projects:
  -
    name: vuejs-app
    source:
      type: git
      location: "https://github.com/gothinkster/vue-realworld-example-app.git"
components:
  -
    type: chePlugin
    id: che-incubator/typescript/latest
    memoryLimit: 512Mi
  -
    type: dockerimage
    alias: nodejs
    image: registry.access.redhat.com/ubi8/nodejs-10
    command: ['sleep']
    args: ['infinity']
    env:
      - name: HOME
        value: /tmp/user
      - name: PS1
        value: $(echo ${0})\\$
    memoryLimit: 512Mi
    endpoints:
      - name: 'vuejs-app'
        port: 8080
        attributes:
          discoverable: 'true'
    mountSources: true
commands:
  -
    name: run the web app
    actions:
      - type: exec
        component: nodejs
        command: npm install && npm run serve
        workdir: ${CHE_PROJECTS_ROOT}/vuejs-app
  -
    name: enable app preview
    actions:
      - type: exec
        component: nodejs
        command: |
          echo "module.exports = {devServer: {disableHostCheck: true}};" > vue.config.js
        workdir: ${CHE_PROJECTS_ROOT}/vuejs-app
```

## Go with https://github.com/xesina/golang-echo-realworld-example-app

This needs discussion with @tolusha and @tsmaeder on how best to define the sample, because our che plugin for Go uses golang 1.10.7 but the project requires Go modules, which are available from golang 1.11.

## java-mysql

I updated this devfile to use the oficial spring petclinic project.

## java-spring-web

I swapped the example for the spring-petclinic so that we have a more modern Spring-based application. As such this sample only differs from `java-mysql` in the fact that it doesn't defin the MySQL component and uses H2 instead.

##java-vertx

I think this is ready as is in the PR mentioned in the table.
