### ISSUE TITLE
Unable to run command because of Unknown actor CheTask error

### ISSUE THREAD

**Issue by sleshchenko** [eclipse-che/che#13562]
### Description
Unable to run command because of Unknown actor CheTask error.

### Reproduction Steps
1. Create a workspace with the following Devfile 
<details>
<summary>Devfile to test</summary>

```yaml
---
apiVersion: 1.0.0
metadata:
  name: python-django
projects:
  -
    name: django-realworld-example-app
    source:
      type: git
      location: "https://github.com/gothinkster/django-realworld-example-app"
components:
  -
    type: chePlugin
    id: ms-python/python/latest
    memoryLimit: 512Mi
  -
    type: dockerimage
    alias: python
    image: centos/python-36-centos7:1
    command: ['sleep']
    args: ['infinity']
    env:
      - name: HOME
        value: /home/user
      - name: PS1
        value: $(echo ${0})\\$
    memoryLimit: 512Mi
    endpoints:
      - name: 'django'
        port: 7000
    mountSources: true
commands:
  -
    name: install requirements
    actions:
      -
        type: exec
        component: python
        command: cd ${CHE_PROJECTS_ROOT}/django-realworld-example-app && pip install -r requirements.txt
  -
    name: migrate
    actions:
      -
        type: exec
        component: python
        command: cd ${CHE_PROJECTS_ROOT}/django-realworld-example-app && python manage.py migrate
  -
    name: patch resources
    actions:
      -
        type: exec
        component: python
        command: cd ${CHE_PROJECTS_ROOT}/django-realworld-example-app && sed -i "s/ALLOWED_HOSTS = \[\]/ALLOWED_HOSTS = \['*'\]/g" conduit/settings.py
  -
    name: run server
    actions:
      -
        type: exec
        component: python
        command: cd ${CHE_PROJECTS_ROOT}/django-realworld-example-app && python manage.py runserver 0.0.0.0:7000
```
</details>

2. Start the created workspace.
3. Run `install requirements` command and wait until it finishes.
4. Try to run `migrate`/`path resources` task.

**Expected:** Message is shown that task is run successfully.
**Actual:** Looks like a task is run successfully but an error message is shown:
![Screenshot_20190618_112526](https://user-images.githubusercontent.com/5887312/59666669-f7938f00-91bd-11e9-9445-4b41c9172e7a.png)

See screencast:
![cheTaskActorError](https://user-images.githubusercontent.com/5887312/59667284-2100ea80-91bf-11e9-8042-e246640c689a.gif)

**OS and version:**    

**Diagnostics:** 
Che Machine Exec Logs
![Screenshot_20190618_113413](https://user-images.githubusercontent.com/5887312/59667125-de3f1280-91be-11e9-9969-aad3bc0f4832.png)

Python plugin logs:
![Screenshot_20190618_113512](https://user-images.githubusercontent.com/5887312/59667150-ebf49800-91be-11e9-908d-2df4a63fd5ef.png)

Theia logs:
![Screenshot_20190618_113501](https://user-images.githubusercontent.com/5887312/59667160-ef881f00-91be-11e9-87e3-bb3df793e07e.png)
