### ISSUE TITLE
Running two or more VSCode extension in the same sidecar is broken

### ISSUE THREAD

**Issue by mmorhun** [eclipse-che/che#13578]
### Description

According to plugins `meta.yaml` specification, it is possible to run in the same sidecar a few Che Theia plugins. If add two VSCode extensions, the plugin which contains them are displayed in the `Che Plugins panel` (select `Installed` filter), but none of them works.
I've checked the sidecar, it has both extensions binaries downloaded in `/plugins/sidecars/generate-plugin-id`.

### Reproduction Steps

Create a Che Theia plugin which has at least two extensions in the same container:

Snippet of meta.yaml :
```yaml
spec:
  containers:
  - image: org/sidecar:tag
    memoryLimit: "512Mi"
  extensions:
    - https://some-path/ext1.vsix
    - https://some-other-path/ext2.vsix
```

Run the workspace.

#### Infrastructure

Tested on openshift.io and minishift
