### ISSUE TITLE
Deployment failed with long named docker images.

### ISSUE THREAD

**Issue by monaka** [eclipse-che/che#13624]
### Description

K8s will reject deployments from Che with labels that is more than 63 characters.
 
### Reproduction Steps

Deploy with long named docker image. (Like follows but it won't use for reproduction checks because the container repository is private.)

```
metadata:
  name: toppers-ssp
projects:
  - name: toppers-ssp-aarch64
    source:
      location: 'https://github.com/nmiri-nagoya-nsaito/toppers-ssp-aarch64.git'
      type: git
components:
  - mountSources: true
    command:
      - sleep
    args:
      - infinity
    memoryLimit: 512Mi
    type: dockerimage
    image: camino.azurecr.io/cantinona/cross-arm-eabi
apiVersion: 1.0.0
```

**OS and version:**    

Che 7.0.0-RC-2.0-SNAPSHOT

**Diagnostics:** 

Logs.

```
Starting Init Plugin Broker
Cleaning /plugins dir
Unified Che Plugin Broker
List of plugins and editors to install
- eclipse/che-machine-exec-plugin/0.0.1 - Che Plug-in with che-machine-exec service to provide creation terminal or tasks for Eclipse CHE workspace machines.
- eclipse/che-theia/next - Eclipse Theia, get the latest release each day.
Starting Che plugins and editor processing
Starting VS Code and Theia plugins processing
All plugins have been successfully processed
Error: Failed to run the workspace: "Failure executing: POST at: https://camino-wus-2-4c0ff018.hcp.westus2.azmk8s.io/apis/apps/v1/namespaces/banco/deployments. Message: Deployment.apps "workspacene3ffsb4b3w1edth.camino-azurecr-io-cantinona-cross-arm-eabi" is invalid: [spec.selector.matchLabels: Invalid value: "workspacene3ffsb4b3w1edth.camino-azurecr-io-cantinona-cross-arm-eabi": must be no more than 63 characters, 
```
