### ISSUE TITLE
Even if the project is deleted from a VS Code workspace, it's back when the Che workspace is re-started

### ISSUE THREAD

**Issue by slemeur** [eclipse-che/che#13621]
### Description
Deleting a project, refreshing the workspace, the project is back.

![delete-project](https://user-images.githubusercontent.com/1636769/59962767-e910e480-94e9-11e9-8a28-12f03836ee6c.gif)

### Reproduction Steps

**OS and version:**    

**Diagnostics:**

**Comment by sunix** [comment]
@olexii4 you fix it i recommand you update these test with devfile: https://github.com/eclipse/che-theia/blob/master/plugins/factory-plugin/tests/projects.spec.ts#L164-L275

**Comment by olexii4** [comment]
@sunix  Ok
I tested it with the next version and standard devfile.
I depend on the work of a language server.

delete a project
https://youtu.be/FdHwE8zqrQk

Impossible to delete a project
https://youtu.be/-ymSH71kwbM

**Comment by sunix** [comment]
@olexii4 I have just reproduced the problem with 

```yaml
metadata:
  name: che7-readme-update-e
projects:
  - name: che
    source:
      location: 'https://github.com/eclipse/che'
      type: git
  - name: web-rails-simple
    source:
      location: 'https://github.com/che-samples/web-rails-simple.git'
      type: git
components:
  - mountSources: true
    command:
      - tail
    args:
      - '-f'
      - /dev/null
    memoryLimit: 512M
    type: dockerimage
    image: sunix/git-devtools
    alias: sunix-git-devtools
apiVersion: 1.0.0
```

try to check only the devfile tab. and refresh before and after.
