### ISSUE TITLE
Improve UX during ${current.project.path} macros usage

### ISSUE THREAD

**Issue by sleshchenko** [eclipse-che/che#13636]
### Description
I hope that there is much work to fix it, so I decided to describe several improvements in the same issue:
1. Improve UX when user tries to run a command which has  ${current.project.path} macros and there is no selected project.
**Actual**: Three error messages: `Can not resolve current.project.path ...`, and `Tasks is failed`, `sh: 1: Bad substitution`.
First time I got this:
![Screenshot_20190627_114007](https://user-images.githubusercontent.com/5887312/60251971-2acad200-98d2-11e9-84d2-94b2c45827c3.png)
And then
![Screenshot_20190627_113345](https://user-images.githubusercontent.com/5887312/60252117-5f3e8e00-98d2-11e9-91fb-a637477117c9.png)

**Expected**: Error message: please select a project before executing a command to make it possible to resolve the current project path. In my case there was only one project, so maybe it may be chosen automatically.

2. Make it possible to use `${current.project.path}` macros in workingDir field of Devfile. Currently, it just does not work:
![Screenshot_20190627_114022](https://user-images.githubusercontent.com/5887312/60252173-79786c00-98d2-11e9-8b30-f0f8dc718ac2.png)

I used the following Java Maven Devfile for testing:
<details>
<summary>Devfile.yaml</summary>

```yaml
---
apiVersion: 1.0.0
metadata:
  name: java-maven
projects:
  -
    name: console-java-simple
    source:
      type: git
      location: "https://github.com/che-samples/console-java-simple.git"
components:
  -
    type: chePlugin
    id: redhat/java/latest
  -
    type: dockerimage
    alias: maven
    image: maven:3.6.0-jdk-11
    command: ['sleep']
    args: ['infinity']
    env:
      - name: MAVEN_CONFIG
        value: /home/user/.m2
      - name: MAVEN_OPTS
        value: "-XX:MaxRAMPercentage=50 -XX:+UseParallelGC -XX:MinHeapFreeRatio=10
          -XX:MaxHeapFreeRatio=20 -XX:GCTimeRatio=4 -XX:AdaptiveSizePolicyWeight=90
          -Dsun.zip.disableMemoryMapping=true -Xms20m -Djava.security.egd=file:/dev/./urandom
          -Duser.home=/home/user"
      - name: JAVA_OPTS
        value: "-XX:MaxRAMPercentage=50 -XX:+UseParallelGC -XX:MinHeapFreeRatio=10
          -XX:MaxHeapFreeRatio=20 -XX:GCTimeRatio=4 -XX:AdaptiveSizePolicyWeight=90
          -Dsun.zip.disableMemoryMapping=true -Xms20m -Djava.security.egd=file:/dev/./urandom"
      - name: JAVA_TOOL_OPTIONS
        value: "-XX:MaxRAMPercentage=50 -XX:+UseParallelGC -XX:MinHeapFreeRatio=10
          -XX:MaxHeapFreeRatio=20 -XX:GCTimeRatio=4 -XX:AdaptiveSizePolicyWeight=90
          -Dsun.zip.disableMemoryMapping=true -Xms20m -Djava.security.egd=file:/dev/./urandom"
      - name: PS1
        value: $(echo ${0})\\$
      - name: HOME
        value: /home/user
    memoryLimit: 512Mi
    endpoints:
      - name: '8080/tcp'
        port: 8080
    mountSources: true
    volumes:
      - name: m2
        containerPath: /home/user/.m2
commands:
  -
    name: maven build
    actions:
      -
        type: exec
        component: maven
        command: "mvn -Duser.home=${HOME} clean install"
        workdir: ${current.project.path}
  -
    name: maven build and run
    actions:
      -
        type: exec
        component: maven
        command: "cd ${current.project.path} && mvn -Duser.home=${HOME} clean install && java -jar ./target/*.jar"

```
</details>
