### ISSUE TITLE
Misleading error message if URL specified in contentReference is unavailable

### ISSUE THREAD

**Issue by AndrienkoAleksandr** [eclipse-che/che#13631]
### Description
Misleading error message if URL specified in `contentReference` is unavailable
Devfile:
https://gist.github.com/AndrienkoAleksandr/5615d4d45c2e5c187320dd86df757a65

**Actual**:
<img width="740" alt="Screenshot_20190626_145841" src="https://user-images.githubusercontent.com/6873095/60180259-44174400-9828-11e9-9120-ccb67d1c6731.png">
**Expected**: 
Actual error message is - host can not be resolved, that can be K8s/OS cluster configuration issue,
<img width="473" alt="Screenshot_20190626_175920" src="https://user-images.githubusercontent.com/6873095/60191384-e80aea80-983c-11e9-9efb-e370786ccc8c.png">
While user receives only `invalid URL`. We should propagate original error message.
**OS and version:**    
Kubuntu 16.04 CHE server: 7.0.0-SNAPSHOT

**Comment by mshaposhnik** [comment]
Any underlying exception is logs ?

**Comment by AndrienkoAleksandr** [comment]
I didn't see any exception in the che-server logs.

**Comment by AndrienkoAleksandr** [comment]
thanks @sleshchenko . We found: openshift instance lost internet connection for some not clear reasons. But any way che-server should print clear error message, for example: 'Unable to download meta.yaml file. Check internet connection or link' or so on. So issue still actual.

<img width="473" alt="Screenshot_20190626_175920" src="https://user-images.githubusercontent.com/6873095/60191384-e80aea80-983c-11e9-9efb-e370786ccc8c.png">

**Comment by skabashnyuk** [comment]
@AndrienkoAleksandr there is an issue in a devfile that you've provided. 
```
Error occurred during creation a workspace from devfile located at `https://gist.githubusercontent.com/AndrienkoAleksandr/5615d4d45c2e5c187320dd86df757a65/raw/84f7c3e86fb0a1d302a5ddead7ad0fc9b888d79d/gistfile1.txt`. Cause: Unable to validate Devfile. Error: while scanning for the next token found character '\t(TAB)' that cannot start any token. (Do not use \t(TAB) for indentation) in 'reader', line 5, column 1: - ^ at [Source: (StringReader); line: 4, column: 11]
```
the fix is quite simple 

```
metadata:
  name: cheTheia-in-che-remote
apiVersion: 1.0.0
components:
-
    reference: >-
      https://raw.githubusercontent.com/eclipse/che-plugin-registry/master/v3/plugins/ms-python/python/2019.2.5433/meta.yaml
    type: chePlugin
projects:
  - source:
      location: 'https://github.com/eclipse/che-theia-samples.git'
      type: git
    name: che-theia-samples
  - source:
      location: 'https://github.com/theia-ide/theia.git'
      type: git
    name: theia
attributes: {}
```
