### ISSUE TITLE
Deleted `projects:` in devfiles.yaml on creating workspaces.

### ISSUE THREAD

**Issue by monaka** [eclipse-che/che#13678]
### Description

It looks all elements under `projects:` in all devfile.yaml is deleted by Dashboard.

### Reproduction Steps

1. Open Che.
2. Create workspace via `https://{che-host}/dashboard/#/create-workspace`
3. Check `devfile.yaml` stored in the workspace at `https://{che-host}/dashboard/#/workspace/{user}/{workspace-name}?tab=Devfile`

**OS and version:**    

Che 7.0.0-SNAPSHOT

**Diagnostics:** 

The result of `curl`
```
curl https://{che-devfile-registry}/devfiles/nodejs/devfile.yaml
---
apiVersion: 1.0.0
metadata:
  name: nodejs
projects:
  -
    name: nodejs-web-app
    source:
      type: git
      location: "https://github.com/che-samples/web-nodejs-sample.git"
components:
  -
    type: chePlugin
    id: che-incubator/typescript/latest
    memoryLimit: 512Mi
  -
    type: dockerimage
    alias: nodejs
    image: registry.access.redhat.com/ubi8/nodejs-10
    command: ['sleep']
    args: ['infinity']
    env:
      - name: HOME
        value: /home/user
      - name: PS1
        value: $(echo ${0})\\$
    memoryLimit: 512Mi
    endpoints:
      - name: 'nodejs'
        port: 3000
    mountSources: true
commands:
  -
    name: run the web app
    actions:
      - type: exec
        component: nodejs
        command: nodemon app.js
        workdir: ${CHE_PROJECTS_ROOT}/nodejs-web-app/app
```

Content in `https://{che-host}/dashboard/#/workspace/monaka/wksp-z8xv?tab=Devfile`

```
metadata:
  name: wksp-z8xv
components:
  - mountSources: false
    id: che-incubator/typescript/latest
    memoryLimit: 512Mi
    type: chePlugin
  - mountSources: true
    endpoints:
      - name: nodejs
        port: 3000
    command:
      - sleep
    args:
      - infinity
    memoryLimit: 512Mi
    type: dockerimage
    alias: nodejs
    image: registry.access.redhat.com/ubi8/nodejs-10
    env:
      - value: /home/user
        name: HOME
      - value: '$(echo ${0})\\$'
        name: PS1
apiVersion: 1.0.0
commands:
  - name: run the web app
    actions:
      - workdir: '${CHE_PROJECTS_ROOT}/nodejs-web-app/app'
        type: exec
        command: nodemon app.js
        component: nodejs
```
