### ISSUE TITLE
Add support for Vue.js

### ISSUE THREAD

**Issue by metlos** [eclipse-che/che#13672]
### Description

Currently our plugin registry doesn't support Vue.js nicely. We have support for typescript/javascript parts of the code but we lack support for the `.vue` files altogether (we don't even have syntax highlighting).

This issue is to support the vetur plugin https://marketplace.visualstudio.com/items?itemName=octref.vetur in Che.

I tried adding it naively through a custom plugin called `vuejs/vetur/latest` with the following `meta.yaml` to my custom plugin registry:

```yaml
apiVersion: v2
publisher: vuejs
name: vetur
version: 0.21.1
type: VS Code extension
displayName: Vetur
title: Rich Vue.js support
description: Vue tooling for VS Code
icon: https://upload.wikimedia.org/wikipedia/commons/9/95/Vue.js_Logo_2.svg
repository: https://github.com/vuejs/vetur.git
category: Language
firstPublicationDate: "2019-07-02"
spec:
  containers:
    - image: eclipse/che-theia-endpoint-runtime:next
      name: vetur
      memoryLimit: '512Mi'
  extensions:
    - https://github.com/vuejs/vetur/releases/download/v0.21.1/vetur-0.21.1.vsix
```

But that doesn't seem to work out of the box and will likely require some modifications to the environment the extension runs in or to the extension code itself. Note that the extension seems to run a language server (having little experience with Che plugin development I don't understand the consequences of that).

### Reproduction Steps

1) Configure Che to use a custom plugin registry with the above mentioned plugin.
1) Import the following devfile:

```yaml
---
apiVersion: 1.0.0
metadata:
  name: vuejs
projects:
  -
    name: vuejs-app
    source:
      type: git
      location: "https://github.com/gothinkster/vue-realworld-example-app.git"
components:
  - 
    type: chePlugin
    id: vuejs/vetur/latest
    memoryLimit: 1024Mi
  -
    type: chePlugin
    id: che-incubator/typescript/latest
    memoryLimit: 512Mi
  -
    type: dockerimage
    alias: nodejs
    image: registry.access.redhat.com/ubi8/nodejs-10
    command: ['sleep']
    args: ['infinity']
    env:
      - name: HOME
        value: /tmp/user
      - name: PS1
        value: $(echo ${0})\\$
    memoryLimit: 512Mi
    endpoints:
      - name: 'vuejs-app'
        port: 8080
        attributes:
          discoverable: 'true'
    mountSources: true
commands:
  -
    name: run the web app
    actions:
      - type: exec
        component: nodejs
        command: npm install && npm run serve
        workdir: ${CHE_PROJECTS_ROOT}/vuejs-app
  -
    name: enable app preview
    actions:
      - type: exec
        component: nodejs
        command: |
          echo "module.exports = {devServer: {disableHostCheck: true}};" > vue.config.js
        workdir: ${CHE_PROJECTS_ROOT}/vuejs-app
```

Notice the lack of any support for `.vue` files.

**OS and version:**    

**Diagnostics:** 
When a workspace created from the above devfile is opened for the first time and a `.vue` file is opened, no syntax highlighting is present:

![image](https://user-images.githubusercontent.com/19999/60513773-4ff78000-9cd8-11e9-8cb4-a970105fe0ff.png)

If the Theia window is reloaded, an error saying "Request initialize failed with message: Cannot read property 'suggest' of undefined" is shown. Strangely, the syntax highlighting suddenly seems work:

![image](https://user-images.githubusercontent.com/19999/60513884-8e8d3a80-9cd8-11e9-8ae3-76473de355c8.png)

but code navigation (that works in VS Code) still doesn't.

**Related issues:**

This issue might be related: https://github.com/eclipse/che/issues/11054
