### ISSUE TITLE
vscode typescript extension fails to start the TypeScript language service: `The TypeScript language service died 5 times right after it got started. The service will not be restarted.`

### ISSUE THREAD

**Issue by sunix** [eclipse-che/che#13732]
### Description
When adding the typescript extension, it is failing to start:

![Selection_211](https://user-images.githubusercontent.com/650571/55763002-9c2e7d80-5a65-11e9-9db1-ce79e03f7fc6.png)

### Reproduction Steps
Starting a workspace with the following devfile: https://github.com/sunix/devfiles/blob/6f59533d7912a1d274b921d7b24867413eedfcb7/che-in-che/che-theia.devfile.yaml

Including the vscode typescript extension:

```yaml
components:
  - name: vscode-typescript
    type: chePlugin
    id: ms-vscode.typescript:1.30.2
```

And start to code on a ts file, it is showing the error after few minutes:
```
The TypeScript language service died 5 times right after it got started. The service will not be restarted.
```

**OS and version:**    
Minikube and server started with chectl
