### ISSUE TITLE
`chectl devfile:generate` should be able to set multiple `dockerimage` and `command`

### ISSUE THREAD

**Issue by sunix** [eclipse-che/che#13785]
### Description
At the moment, we have the ability to generate a devfile with chectl and provide few components of the file:
- dockerimage
- command

For instance
```
chectl devfile:generate \
    --name=quarkus-che-demo \
    --language=java \
    --dockerimage=quay.io/quarkus/centos-quarkus-maven \
    --git-repo=https://github.com/sunix/che-quarkus-demo \
    --command="mvn compile quarkus:dev"
```
will generate
```yaml
apiVersion: 1.0.0
metadata:
  name: quarkus-che-demo
projects:
  - source:
      type: git
      location: 'https://github.com/sunix/che-quarkus-demo'
    name: che-quarkus-demo
components:
  - alias: quay-io-quarkus-cent
    type: dockerimage
    image: quay.io/quarkus/centos-quarkus-maven
    memoryLimit: 512M
    mountSources: true
    command:
      - tail
    args:
      - '-f'
      - /dev/null
  - type: chePlugin
    alias: java-ls
    id: redhat/java/latest
commands:
  - name: 'mvn compile quarkus:dev'
    actions:
      - type: exec
        command: 'mvn compile quarkus:dev'
        component: quay-io-quarkus-cent
        workdir: /projects/che-quarkus-demo
```
This is good but it would be nice to be able to provide multiple commands or container images:

```
chectl devfile:generate \
    --name=quarkus-che-demo \
    --language=java \
    --dockerimage=quay.io/quarkus/centos-quarkus-maven \
    --dockerimage=sunix/git-devtools \
    --git-repo=https://github.com/sunix/che-quarkus-demo \
    --command="mvn compile quarkus:dev" \
    --command="mvn compile -Pnative"
```

At the moment, chectl will only keep one of the 2 `dockerimage` arguments and one of the 2 `command` arguments.
