### ISSUE TITLE
Running any task fails after refresh

### ISSUE THREAD

**Issue by tolusha** [eclipse-che/che#13799]
### Description
 
It is not possible to run a task after workspace is refreshed.

### Reproduction Steps

1. start workspace
2. run any task
3. It is possible to run a task
4. refresh the tab
5. run any task
4. Error observed `Can't get task launch configuration for label`

**OS and version:**    
minishift v1.34.0+f5db7cb
che-7.0.0-rc-3

**Diagnostics:** 
![Screenshot from 2019-07-09 10-09-12](https://user-images.githubusercontent.com/1640675/60866671-a2352580-a231-11e9-90cb-51cf5a2409f8.png)

### Related issues:
https://github.com/eclipse/che/issues/13155

**Comment by l0rd** [comment]
@vparfonov @RomanNikitenko are you aware of this? Is it related to the tasks issues that you have in your sprint backlog or is it something new that we should add to milestone 7.0.0?

**Comment by RomanNikitenko** [comment]
The bug was caused by changing in theia project way to define  - is task detected or configured. I described the causes of the problem [here](https://github.com/theia-ide/theia/issues/4928). For **che commands** it will go away after merge https://github.com/eclipse/che-theia/pull/295. But I'm going to update the PR and check again this case to be sure, I let you know ASAP.

**Comment by RomanNikitenko** [comment]
I tested the case for https://github.com/eclipse/che-theia/pull/295 and can not reproduced it. So I think the cause of the problem described [here](https://github.com/eclipse/che/issues/13799#issuecomment-509945862) is correct.

@tolusha could you try to reproduce it:
- using image rnikitenko/che-theia:7.0.0-task-fix 
or
- using component in your devfile
```
- 
    alias: theia-editor
    reference: >-
      https://raw.githubusercontent.com/RomanNikitenko/che-plugin-registry/master/v3/plugins/eclipse/che-theia/custom/meta.yaml
    type: cheEditor
``` 
The image contains:
- 0.8.0 theia version + fix https://github.com/theia-ide/theia/pull/5591
- current 7.0.0 branch of che-theia + https://github.com/eclipse/che-theia/pull/295    

Thank you!

**Comment by tolusha** [comment]
@RomanNikitenko 
With you image provided I can't run any tasks at all event without refreshing the browser.
The good news is that I can't reproduce this issue anymore with `7.0.0-rc-3.0` version of Che Theia.

**Comment by RomanNikitenko** [comment]
@tolusha
I test it using the devfile:
```
apiVersion: 1.0.0
metadata:
 name: che
projects:
  - name: che-theia
    source:
      type: git
      location: 'https://github.com/eclipse/che-theia.git'
components:
  - 
    alias: che-dev
    type: dockerimage
    image: eclipse/che-theia-dev:next
    mountSources: true
    endpoints:
      - name: "theia-dev"
        port: 3130
        attributes:
          protocol: tcp
          public: 'true'
    memoryLimit: 4Gi
  - 
    alias: theia-editor
    reference: >-
      https://raw.githubusercontent.com/RomanNikitenko/che-plugin-registry/master/v3/plugins/eclipse/che-theia/custom/meta.yaml
    type: cheEditor

commands:
- name: theia:build
  actions:
  - type: exec
    component: che-dev
    command: >
              yarn
    workdir: /projects/che-theia

- name: theia:run:watch
  actions:
  - type: exec
    component: che-dev
    command: >
              yarn build
    workdir: /projects/che-theia

``` 
![che_version](https://user-images.githubusercontent.com/5676062/61202445-31d64a80-a6f0-11e9-9136-b0a693d967fe.png)

Could you provide `Help` => `About` screenshot for your assembly? 
Could you provide the way how did you test it?
