### ISSUE TITLE
devfile: dockerimage with command is not executing entrypoint

### ISSUE THREAD

**Issue by sunix** [eclipse-che/che#13817]
### Description
Hello,
I don't know if this is wanted but I have these two devfiles that use the same docker image:

```yaml
apiVersion: 1.0.0
metadata:
  name: without-command
projects:
  - name: devfiles
    source:
      location: 'https://github.com/sunix/devfiles'
      type: git
      branch: master
components:
  - alias: git
    mountSources: true
    memoryLimit: 512M
    type: dockerimage
    image: sunix/git-devtools
```

```yaml
metadata:
  name: with-command
projects:
  - name: devfiles
    source:
      location: 'https://github.com/sunix/devfiles'
      type: git
      branch: master
components:
  - alias: git
    mountSources: true
    memoryLimit: 512M
    type: dockerimage
    image: sunix/git-devtools
    command:
      - tail
     args:
      - '-f'
      - /dev/null
```
one have a command `tail -f /dev/null`
but the result is not the same when getting to the terminal:

with the command:
![Selection_337](https://user-images.githubusercontent.com/650571/61056726-2931fb80-a3f4-11e9-995b-9ddc5229ac99.png)

without the command (i have type `bash` manually and see ... no name)
![Selection_336](https://user-images.githubusercontent.com/650571/61056758-3818ae00-a3f4-11e9-951a-03df2efbe42b.png)

I suspect it is overriding my entrypoint ..
```Dockerfile
ENTRYPOINT ["/entrypoint.sh"]
CMD tail -f /dev/null
```
which is basically setting the arbitrary user

```sh

export USER_ID=$(id -u)
export GROUP_ID=$(id -g)

if ! grep -Fq "${USER_ID}" /etc/passwd; then
    # current user is an arbitrary
    # user (its uid is not in the
    # container /etc/passwd). Let's fix that
    cat ${HOME}/passwd.template | \
    sed "s/\${USER_ID}/${USER_ID}/g" | \
    sed "s/\${GROUP_ID}/${GROUP_ID}/g" | \
    sed "s/\${HOME}/\/home\/git/g" > /etc/passwd

    cat ${HOME}/group.template | \
    sed "s/\${USER_ID}/${USER_ID}/g" | \
    sed "s/\${GROUP_ID}/${GROUP_ID}/g" | \
    sed "s/\${HOME}/\/home\/git/g" > /etc/group
fi

```

but isn't `command` supposed to override CMD and not ENTRYPOINT ?

**Comment by benoitf** [comment]
the `I have no name` is because entrypoint is not executed yes

**Comment by benoitf** [comment]
BTW as your docker image is already having an infinity wait, why do you specify a tail command in the devfile ?

**Comment by sunix** [comment]
> BTW as your docker image is already having an infinity wait, why do you specify a tail command in the devfile ?

just the `chectl devfile:generate --dockerimage=myimage` is adding the command by default.

**Comment by l0rd** [comment]
That's the expected behavior yes. For `chectl` I expect that most of the time user won't have an entrypoint but we may add the option `--keep-image-entrypoint` or something similar.

**Comment by sunix** [comment]
what confuse me is `command` for `ENTRYPOINT` and not `CMD`

**Comment by l0rd** [comment]
> what confuse me is command for ENTRYPOINT and not CMD

What do you mean?

**Comment by sleshchenko** [comment]
@sunix See https://docs.openshift.com/container-platform/3.5/rest_api/kubernetes_v1.html
![Screenshot_20190716_115027](https://user-images.githubusercontent.com/5887312/61280058-eab78a80-a7bf-11e9-9bce-72a60bdd789e.png)
If you want to define command only but not entrypoint - you should define `args` only.

From Che perspective - docs can be improved. As far as I see now even Json Spec Page does not contain any info about it. https://redhat-developer.github.io/devfile/devfile#components
But JSON Spec itself contains some description https://github.com/eclipse/che/blob/master/wsmaster/che-core-api-workspace/src/main/resources/schema/devfile.json#L363

**Comment by sunix** [comment]
ok thanks
so according to https://kubernetes.io/docs/tasks/inject-data-application/define-command-argument-container/#notes, to do what i would expect i have just to provide `args` without `command`

**Comment by sleshchenko** [comment]
@sunix Should this issue be closed or reformulated to improve docs?

**Comment by sunix** [comment]
I think we should, in most of our devfile samples (i don't know if this is the case or not) where we provide a dockerimage with a `sleep infinitly` or `tail -f /dev/null`, override CMD and not ENTRYPOINT so for instance:

```yaml
components:
  - alias: sunix-mergepdf
    type: dockerimage
    image: sunix/mergepdf
    memoryLimit: 512M
    mountSources: true
    args:
      - sleep
      - infinity
```
I have provided an improvement in chectl: https://github.com/che-incubator/chectl/pull/222
