### ISSUE TITLE
OpenShift DevConsole Integration

### ISSUE THREAD

**Issue by l0rd** [eclipse-che/che#13820]
### Description

The OpenShift DevConsole is an OpenShift cluster dashboard that targets developers rather than administrators (OS 3 console target). 

One of the feature of the new OpenShift DevConsole is to allow a developer to provision a Che workspace and start coding an application that is deployed on the cluster.

To make this scenario possible the DevConsole should be able to:

1) Find out if Che is installed on the OpenShift cluster
2) Generate a Devfile and start a Che workspace (on behalf of the connected user)

This issue should not be added to the 7.0.0 milestone but the DevConsole code freeze (i.e. OS 4.2 code freeze) happens sometimes in August '19 hence we need to have clear idea on the approach for the beginning of August.

**Comment by l0rd** [comment]
### Simple implementation proposal:

**Che discovery**
DevConsole looks for the default Che namespace to find out if its installed

**Workspace provisioning**
DevConsole generates a devfile and redirect the HTTP request to the wsmaster providing the devfile as either 1) the body of a POST HTTP request or 2) a URL parameter (compressed) 

This approach should be easy to implement but discovery is not robust and workspaces would always be re-created (we could introduce a `reCreate=false` parameter to avoid this behaviour).

**Comment by l0rd** [comment]
### CRD based implementation proposal:

**Che discovery**
A new kind of CRD will be deployed: the `DevWorkspace` CRD (devfile based)
DevConsole discovers if Che is deployed on the cluster If the `DevWorkspace` API is available

**Workspace provisioning**
DevConsole creates a new `DevWorkspace` CR
The `DevWorkspace`creation event triggers the che-operator
che-operator generates a factory URL [1]
che-operator update the `DevWorkspace` CR adding the link to the factory URL 
DevConsole redirects the deveoloer to the factory URL

[1] `https://<che-host>/f?cr=<devworkspace-name>&namespace=<devworkspace-namespace>`

This approach should be harder to implement but would be a step forward to the Workspace CRD

**Comment by sbose78** [comment]
Third option proposed by @davidfestal :

1. Che operator would dump che server URLs in a specific `configmap` ( called `che-public-config`) in a specific namespace ( called `che-public` ) .
2. Console user should be able to read that. Based on that URLs read, the workspace redirection URL would be created. ( @davidfestal , for a Git project, how would be the devfile look like? )

I see the following RBAC resources that need to be created by che-operator

```
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: che-operator-home
  name: public-config-reader
rules:
- apiGroups: [""] # "" indicates the core API group
  resources: ["configmap"]
  verbs: ["get", "list"]

-----


apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: public-config-reader-binding
subjects:
- kind: Group
  name: manager # Name is case sensitive
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: Role
  name: public-config-reader
  apiGroup: rbac.authorization.k8s.io
```
