### ISSUE TITLE
chectl devfile:generate could show the command that have been used in the generated file

### ISSUE THREAD

**Issue by sunix** [eclipse-che/che#13824]
### Description
`chectl devfile:generate` generates a devfile. But it could be useful for the user to know how it has been generated originally. For instance:
```sh
$ chectl devfile:generate --name=expenses --dockerimage=sunix/mergepdf --command="pdftk *.pdf cat output large.pdf && pdf2ps large.pdf very_large.ps && ps2pdf very_large.ps final.pdf && rm large.pdf very_large.ps"
```
generates
```yaml
apiVersion: 1.0.0
metadata:
  name: expenses
components:
  - alias: sunix-mergepdf
    type: dockerimage
    image: sunix/mergepdf
    memoryLimit: 512M
    mountSources: true
    command:
      - tail
    args:
      - '-f'
      - /dev/null
commands:
  - name: >-
      pdftk *.pdf cat output large.pdf && pdf2ps large.pdf very_large.ps &&
      ps2pdf very_large.ps final.pdf && rm large.pdf very_large.ps
    actions:
      - type: exec
        command: >-
          pdftk *.pdf cat output large.pdf && pdf2ps large.pdf very_large.ps &&
          ps2pdf very_large.ps final.pdf && rm large.pdf very_large.ps
        component: sunix-mergepdf
        workdir: /projects/
```
but could generates
```yaml
# Generated by chectl (see https://github.com/che-incubator/chectl):
# chectl devfile:generate --name=expenses --dockerimage=sunix/mergepdf --command="pdftk *.pdf cat output large.pdf && pdf2ps large.pdf very_large.ps && ps2pdf very_large.ps final.pdf && rm large.pdf very_large.ps"

apiVersion: 1.0.0
metadata:
  name: expenses
components:
  - alias: sunix-mergepdf
    type: dockerimage
    image: sunix/mergepdf
    memoryLimit: 512M
    mountSources: true
    command:
      - tail
    args:
      - '-f'
      - /dev/null
commands:
  - name: >-
      pdftk *.pdf cat output large.pdf && pdf2ps large.pdf very_large.ps &&
      ps2pdf very_large.ps final.pdf && rm large.pdf very_large.ps
    actions:
      - type: exec
        command: >-
          pdftk *.pdf cat output large.pdf && pdf2ps large.pdf very_large.ps &&
          ps2pdf very_large.ps final.pdf && rm large.pdf very_large.ps
        component: sunix-mergepdf
        workdir: /projects/
```
