### ISSUE TITLE
Persist installed VS Code extensions

### ISSUE THREAD

**Issue by vitaliy-guliy** [eclipse-che/che#13834]
### Description

VS Code extensions that have been installed by Che Plugins panel must be present/working after restarting the workspace.

VS Code extension is not deployed to Theia while installing. The Plugins panel 
offers the user to restart the workspace to apply the changes. This is done intentionally to have the same behavior for VS Code extensions as we have when installing a plugin from plugin registry.

Supporting the separate directory is already implemented in Theia core.
We just forget to specify an environment variable for that in Theia editor component when moved it from `che-theia` to `che-plugin-registry`.

**Comment by sunix** [comment]
We should find a way to persist that in the devfile.

**Comment by vitaliy-guliy** [comment]
I see two options here:
 - one is to describe the extension in the devfile like you commented in the [PR](https://github.com/eclipse/che-plugin-registry/pull/180)
```
    - type: vscodeExtension
      id: 'vscode extension id',
    - type: vscodeExtension
      reference: 'link to the vscode ext binary',
```

- another one is to be able to inline content of the plugin meta.yaml in the devfile something like following
```
    - type: chePlugin
      pluginMetadata:
        apiVersion: v2
        publisher: camel-tooling
        name: vscode-apache-camel
        version: 0.0.14
        type: VS Code extension
        displayName: Language Support for Apache Camel
        title: Language Support for Apache Camel
        description: This VS Code extension provides support for Apache Camel.
        icon: https://www.eclipse.org/che/images/logo-eclipseche.svg
        repository: https://github.com/camel-tooling/camel-lsp-client-vscode
        category: Language
        firstPublicationDate: "2018-04-23"
        spec:
          containers:
          - image: eclipse/che-remote-plugin-runner-java11:7.0.0-rc-3.0
            name: vscode-apache-camel
            memoryLimit: 512Mi
          extensions:
          - https://github.com/camel-tooling/camel-lsp-client-vscode/releases/download/0.0.14/camel-tooling.vscode-apache-camel-0.0.14.vsix
        latestUpdateDate: "2019-07-05"
```

For me the first one is preferred
