### ISSUE TITLE
Improve che docs devfile section

### ISSUE THREAD

**Issue by sunix** [eclipse-che/che#13848]
Improve this part: 
https://www.eclipse.org/che/docs/che-7/using-developer-environments-workspaces.html#making-a-workspace-portable-using-a-devfile_using-developer-environments-workspaces

- [ ] First section [how to use instantiate a workspace from a devfile](https://www.eclipse.org/che/docs/che-7/using-developer-environments-workspaces.html#starting-a-workspace-with-a-devfile_making-a-workspace-portable-using-a-devfile) should come with a minimal devfile sample so user could just try out these commands before going to the next section. 
- [ ] in the section where we teach the user how to write the devfile, we should give the guided alternatives for each steps:
  - [ ] how to customize a specific part of the devfile with the dashboard
  - [ ] how to customize a specific part of the devfile with `chectl devfile:generate`

**Comment by nickboldt** [comment]
Relates to https://github.com/eclipse/che-docs/pull/737/files#diff-218593e58ca8c250a191fb0efa4f72a2R27 - new file will be src/main/pages/che-7/hands-on-guidance/proc_configuring-a-che-workspace-using-a-devfile.adoc

**Comment by nickboldt** [comment]
If you provide some info about how to use `devfile:generate`, I might be able to flesh out my doc (linked above) to provide an example of the chectl devfile generator. 

Docs in chectl repo seem pretty sparse. Can we only include one plugin in the generated devfile? One language? One project repo?

https://github.com/che-incubator/chectl#chectl-devfilegenerate

**Comment by l0rd** [comment]
@nickboldt yes `devfile:generate` is limited, there wasn't a PM requirement for that and it's kind of a MVP. If it's considered useful we will improve it: https://github.com/che-incubator/chectl/issues/100

**Comment by sunix** [comment]
hello nick,
- so yes at the moment we cannot include multiple kind of object. See https://github.com/eclipse/che/issues/13785.
- and yes it is not very clear how to use it

So in real life, it really depends on what i want to achieve but it is so convenient not having to go to the devfile documentation to see how to include source code.

1. I want to create a devfile for a project or I know I will have some changes to do on the generated devfile. I use `devfile:generate` just to bootstrap it and then I will made few change on it afterwards
```bash
# generate the devfile
chectl devfile:generate \
    --name=quarkus-che-demo \
    --language=java \
    --dockerimage=quay.io/quarkus/centos-quarkus-maven:graalvm-1.0.0-rc16 \
    --git-repo=https://github.com/sunix/che-quarkus-demo \
    --command="mvn compile quarkus:dev" \
 > devfile.yaml
# edit/test the devfile
# usually if i need more projects, duplicate from the first generated one, same for other language or dockerimage. in this example, i would add one more dockerimage, adapt the command and add other ones.
vim devfile.yaml
chectl workspace:start -f devfile.yaml
```

2. I want a *one shot* workspace. For instance when i just want to edit a README file ... I just shoot
```bash
chectl workspace:start -f <(chectl devfile:generate --name=readme-contribute --git-repo=https://github.com/eclipse/che)
```
that will generate the devfile and create a workspace on the fly.

For https://www.eclipse.org/che/docs/che-7/using-developer-environments-workspaces.html#preparing-a-minimal-devfile_making-a-workspace-portable-using-a-devfile everything could be generated with chectl
We could use:
```bash
chectl devfile:generate --name="minimal-workspace"
```
to generate your first example
```yaml
apiVersion: 1.0.0
metadata:
  name: minimal-workspace
```
And the second example:
```bash
chectl devfile:generate --name=petclinic-dev-environment --git-repo=https://github.com/spring-projects/spring-petclinic --language=java --command="./mvnw package && java -jar target/*.jar"
```
that will generates the devfile (compare to the example on the site, there is a command to build and run):
```yaml
apiVersion: 1.0.0
metadata:
  name: petclinic-dev-environment
projects:
  - source:
      type: git
      location: 'https://github.com/spring-projects/spring-petclinic'
    name: spring-petclinic
components:
  - type: chePlugin
    alias: java-ls
    id: redhat/java/latest
commands:
  - name: ./mvnw package && java -jar target/*.jar
    actions:
      - type: exec
        command: ./mvnw package && java -jar target/*.jar
        component: java-ls
        workdir: /projects/spring-petclinic
```

and to run that in one line
```bash
chectl workspace:start -f <(chectl devfile:generate --name=petclinic-dev-environment --git-repo=https://github.com/spring-projects/spring-petclinic --language=java --command="./mvnw package && java -jar target/*.jar")
  ✔ Retrieving Che Server URL...http://che-che.192.168.39.13.nip.io
  ✔ Verify if Che server is running
  ✔ Create workspace from Devfile /dev/fd/63

Workspace IDE URL:
http://che-che.192.168.39.13.nip.io/dashboard/#/ide/che/petclinic-dev-environment
```

here is how it looks like:
![Selection_342](https://user-images.githubusercontent.com/650571/61283260-26048a00-a7bd-11e9-81ec-1b9636fe22fb.png)
