### ISSUE TITLE
NPE when a devfile command references theia 

### ISSUE THREAD

**Issue by RomanNikitenko** [eclipse-che/che#13842]
Hello!
I had two components in my devFile and a lot of commands. I used minikube and chectl to start workspace from the devfile. My workspace was stuck every time and I couldn't understand what's the problem with my devfile.
![workspace_fail](https://user-images.githubusercontent.com/5676062/61186559-98675400-a66f-11e9-8b3b-e9a78f13695c.gif)

The problem was solved when I replaced the value of the `component` field  `theia-editor` by `che-dev` for one of the commands.

So, my question is: can I define `theia-editor` as `component` for commands?
If no, can we display some warning message for user for this case? For example, I get error: 
![start_workspace_error](https://user-images.githubusercontent.com/5676062/61186577-d6647800-a66f-11e9-850e-b6154301e404.png)
 when I just miss some letter for component field. So, maybe we can do something similar for described case. 

Maybe something wrong with my devfile, please take a look (I simplified the devfile as possible and left only two commands and two components - for example):
```
apiVersion: 1.0.0
metadata:
 name: che
projects:
  - name: che-theia
    source:
      type: git
      location: 'https://github.com/eclipse/che-theia.git'
components:
  - 
    alias: che-dev
    type: dockerimage
    image: eclipse/che-theia-dev:next
    mountSources: true
    endpoints:
      - name: "theia-dev"
        port: 3130
        attributes:
          protocol: tcp
          public: 'true'
    memoryLimit: 4Gi
  - 
    alias: theia-editor
    reference: >-
      https://raw.githubusercontent.com/eclipse/che-plugin-registry/master/v3/plugins/eclipse/che-theia/next/meta.yaml
    type: cheEditor

commands:
- name: theia:build
  actions:
  - type: exec
    component: che-dev
    command: >
              yarn
    workdir: /projects/theia

- name: theia:run:watch
  actions:
  - type: exec
    component: theia-editor
    command: >
              yarn watch
    workdir: /projects/theia

```
Thanks in advance!
