### ISSUE TITLE
Unable to create workspace if URL reference is used for component

### ISSUE THREAD

**Issue by sleshchenko** [eclipse-che/che#13861]
### Describe the bug
Unable to create workspace if URL reference is used for component.

### Che version

 - [ ] latest
 - [x] nightly
 - [ ] other: please specify

### Steps to reproduce

Two alternative ways:
1. Try to create a workspace with swagger with the following Devfile

<details>

<summary>https://raw.githubusercontent.com/eclipse/che/master/e2e/files/happy-path/containers-happy-path.yaml</summary>

```yaml
---
apiVersion: 1.0.0
metadata:
  name: petclinic-dev-environment
projects:
  - name: petclinic
    source:
      type: git
      location: 'https://github.com/spring-projects/spring-petclinic.git'
components:
  - type: kubernetes
    alias: petclinic-web
    reference: https://raw.githubusercontent.com/eclipse/che/master/e2e/files/happy-path/containers-happy-path.yaml
    selector:
      app.kubernetes.io/component: webapp
    entrypoints:
      - containerName: spring-boot
        command: ["tail"]
        args: ["-f", "/dev/null"]
  - type: kubernetes
    alias: petclinic-db
    reference: https://raw.githubusercontent.com/eclipse/che/master/e2e/files/happy-path/containers-happy-path.yaml
    selector:
      app.kubernetes.io/component: database
  - type: dockerimage
    alias: maven-container
    image: bujhtr5555/maven-with-artifacts:latest
    command: ['sleep']
    args: ['infinity']
    env:
      - name: MAVEN_CONFIG
        value: /home/user/.m2
    memoryLimit: 4Gi
    mountSources: true
  - type: chePlugin
    id: redhat/java/latest
  - type: chePlugin
    id: redhat/vscode-yaml/latest
commands:
  - name: build
    actions:
      - type: exec
        component: maven-container
        command: mvn clean package >> build.txt
        workdir: /projects/petclinic
  - name: build-file-output
    actions:
      - type: exec
        component: maven-container
        command: 'mkdir -p /projects/petclinic/?/.m2 && cp -r /.m2/* /projects/petclinic/?/.m2 && cd /projects/petclinic && mvn package >> build-output.txt'
        workdir: /projects/petclinic
  - name: run
    actions:
      - type: exec
        component: maven-container
        command: java -jar spring-petclinic-2.1.0.BUILD-SNAPSHOT.jar --spring.profiles.active=mysql
        workdir: /projects/petclinic/target
  - name: run-with-changes
    actions:
      - type: exec
        component: maven-container
        command: java -jar spring-petclinic-2.1.0.BUILD-SNAPSHOT.jar --spring.profiles.active=mysql
        workdir: /projects/petclinic/target
  - name: run-debug
    actions:
      - type: exec
        component: maven-container
        command: java -jar -Xdebug -Xrunjdwp:transport=dt_socket,server=y,suspend=n,address=1044 spring-petclinic-2.1.0.BUILD-SNAPSHOT.jar --spring.profiles.active=mysql
        workdir: /projects/petclinic/target
```

</details>
**Expected**: workspace is created and appears on dashboard.
**Actual**: Response contains the following error message

```
{
  "message": "Failed to validate content reference of component 'petclinic-web' of type 'kubernetes': 
Failed to fetch a file https://raw.githubusercontent.com/eclipse/che/master/e2e/files/happy-path/containers-happy-path.yaml specified in devfile null from URL https://raw.githubusercontent.com/eclipse/che/master/e2e/files/happy-path/containers-happy-path.yaml. 
Make sure the URL of the devfile points to the raw content of it (e.g. not to the webpage showing it but really just its contents). 
Additionally, if you're using  relative form, make sure the referenced files are actually stored relative to the devfile on the same host, or try to specify URL in absolute form. 
The current attempt to download the file failed with the following error message: raw.githubusercontent.com"
}
```

2. Try to create a workspace with a factory from a devfile where URL reference is used for component. To do it open `${CHE_HOST}/f?url=https://raw.githubusercontent.com/eclipse/che/master/e2e/files/happy-path/happy-path-workspace.yaml`
**Expected**: workspace is created and appears on dashboard.
**Actual**:
![Screenshot_20190716_153324](https://user-images.githubusercontent.com/5887312/61294697-10a05780-a7df-11e9-92dd-065929021d90.png)
![Screenshot_20190716_153339](https://user-images.githubusercontent.com/5887312/61294713-1b5aec80-a7df-11e9-9cd9-18cccb5ec236.png)

### Runtime
   - [ ] kubernetes (include output of `kubectl version`) 
   - [ ] Openshift (include output of `oc version`)
   - [ ] minikube (include output of `minikube version` and `kubectl version`)
   - [ ] minishift (include output of `minishift version` and `oc version`)
   - [ ] docker-desktop + K8S (include output of `docker version` and `kubectl version`)
   - [ ] other: (please specify)

### Installation method
   - [ ] chectl 
   - [ ] che-operator 
   - [ ] minishift-addon
   - [ ] I don't know

### Environment
   - [x] my computer 
       - [ ] Windows
       - [x] Linux
       - [ ] macOS
   - [ ] Cloud
       - [ ] Amazon
       - [ ] Azure
       - [ ] GCE
       - [ ] other (please specify) 
   - [ ] other: please specify
