### ISSUE TITLE
keycloak image init containers shouldn't do post-install stuff

### ISSUE THREAD

**Issue by benoitf** [eclipse-che/che#13870]
### Describe the bug
che-keycloak wait-for-postgres init container is doing
```
apk --no-update add curl jq
```
and with limited set of permissions it is not working, but in any case, image should have the binaries, not downloading them

### Che version

 - [ ] latest
 - [x] nightly
 - [ ] other: please specify

### Steps to reproduce

```
Init Containers:
  wait-for-postgres:
    Container ID:  docker://2aa46976f8727946c607aeae0445dd3b32b4a9a1a8da9137d2f4812518361c3f
    Image:         alpine:3.5
    Image ID:      docker-pullable://alpine@sha256:66952b313e51c3bd1987d7c4ddf5dba9bc0fb6e524eed2448fa660246b3e76ec
    Port:          <none>
    Host Port:     <none>
    Command:
      sh
      -c
      apk --no-cache add curl jq ; adresses_length=0; until [ $adresses_length -gt 0 ]; do echo waiting for postgres to be ready...; sleep 2; endpoints=`curl -s --cacert /var/run/secrets/kubernetes.io/serviceaccount/ca.crt -H "Authorization: Bearer $(cat /var/run/secrets/kubernetes.io/serviceaccount/token)"     https://kubernetes.default/api/v1/namespaces/$POD_NAMESPACE/endpoints/postgres`; adresses_length=`echo $endpoints | jq -r ".subsets[]?.addresses // [] | length"`; done;
    State:          Running
      Started:      Tue, 16 Jul 2019 16:32:39 +0200
    Ready:          False
    Restart Count:  0
    Environment:
      POD_NAMESPACE:  che (v1:metadata.namespace)
    Mounts:
      /var/run/secrets/kubernetes.io/serviceaccount from che-keycloak-token-7cwz9 (ro)

```

```
$ docker run --user "1000:0" --entrypoint sh -it alpine:3.5
/ $ apk --no-cache add curl jq
ERROR: Unable to lock database: Permission denied
ERROR: Failed to open apk database: Permission denied
/ $ id
uid=1000 gid=0(root)
```

reported through
https://github.com/eclipse/che/issues/13838

### Expected behavior
no error but I'm expecting that jq and curl are already in a docker image (no post-install of these dependencies) so there is no permission issue

### Runtime
   - [x] kubernetes (include output of `kubectl version`) 
   - [ ] Openshift (include output of `oc version`)
   - [ ] minikube (include output of `minikube version` and `kubectl version`)
   - [ ] minishift (include output of `minishift version` and `oc version`)
   - [ ] docker-desktop + K8S (include output of `docker version` and `kubectl version`)
   - [ ] other: (please specify)

### Installation method
   - [x] chectl 
   - [ ] che-operator 
   - [ ] minishift-addon
   - [ ] I don't know

### Environment
   - [ ] my computer 
       - [ ] Windows
       - [ ] Linux
       - [ ] macOS
   - [ ] Cloud
       - [ ] Amazon
       - [ ] Azure
       - [x] GCE
       - [ ] other (please specify) 
   - [ ] other: please specify

**Comment by benoitf** [comment]
Using in helm/che/custom-charts/che-keycloak/templates/deployment.yaml

```
    spec:
      initContainers:
      - name: wait-for-postgres
        image: everpeace/curl-jq
        command: ["sh", "-c", "adresses_length=0; until [ $adresses_length -gt 0 ]; do echo waiting for postgres to be ready...; sleep 2; endpoints=`curl -s --cacert /var/run/secrets/kubernetes.io/serviceaccount/ca.crt -H \"Authorization: Bearer $(cat /var/run/secrets/kubernetes.io/serviceaccount/token)\"     https://kubernetes.default/api/v1/namespaces/$POD_NAMESPACE/endpoints/postgres`; adresses_length=`echo $endpoints | jq -r \".subsets[]?.addresses // [] | length\"`; done;"]
```

che-postgres is having the same commands so probably need to update the init container as well even if permissions are ok

was ok (no apk install command and use of another image than alpine)
but well it's not kind of an official image :-)
