### ISSUE TITLE
Workspace isn't accessible right after installing a plugin

### ISSUE THREAD

**Issue by akurinnoy** [eclipse-che/che#13912]
### Describe the bug

After installing a plugin listed in "Che plugin" panel I tried to restart the workspace by click on the popup and confirming that in dialog window. Instead of the workspace-loader page I got server error. 

### Che version

 - [ ] latest
 - [x] nightly
 - [ ] other: please specify

### Steps to reproduce

1. Click on "View" and then click on "Che Plugins"
2. In "Che Plugins" panel click on "Install" button in the first plugin.
3. Wait until plugin gets installed.
4. Click on the green rectangular with text "Click here to apply changes ..." on the top of "Che Plugins" panel and then confirm your intention in modal dialog window.
5. See the server error on the page. 

### Expected behavior

Workspace is loading and workspace-loader shows loading logs.

### Runtime
   - [ ] kubernetes (include output of `kubectl version`) 
   - [ ] Openshift (include output of `oc version`)
   - [x] minikube (include output of `minikube version` and `kubectl version`)
```bash
$ minikube version
minikube version: v1.2.0
```
```bash
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.0", GitCommit:"e8462b5b5dc2584fdcd18e6bcfe9f1e4d970a529", GitTreeState:"clean", BuildDate:"2019-06-20T04:49:16Z", GoVersion:"go1.12.6", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.0", GitCommit:"e8462b5b5dc2584fdcd18e6bcfe9f1e4d970a529", GitTreeState:"clean", BuildDate:"2019-06-19T16:32:14Z", GoVersion:"go1.12.5", Compiler:"gc", Platform:"linux/amd64"}
```
   - [ ] minishift (include output of `minishift version` and `oc version`)
   - [ ] docker-desktop + K8S (include output of `docker version` and `kubectl version`)
   - [ ] other: (please specify)

### Screenshots

![Screen Recording 2019-07-18 at 15 45 23 2019-07-18 16_15_54](https://user-images.githubusercontent.com/16220722/61466107-99eb9180-a979-11e9-9f10-d8143b7a9349.gif)

### Installation method
   - [x] chectl 
   - [ ] che-operator 
   - [ ] minishift-addon
   - [ ] I don't know

### Environment
   - [x] my computer 
       - [ ] Windows
       - [ ] Linux
       - [x] macOS
   - [ ] Cloud
       - [ ] Amazon
       - [ ] Azure
       - [ ] GCE
       - [ ] other (please specify) 
   - [ ] other: please specify

**Comment by akurinnoy** [comment]
@rhopp workspace works well if you refresh the page.

I made a mistake - pointed wrong version of Che. I got the bug on nightly version. Description is updated.

**Comment by rhopp** [comment]
Even the workaround is pretty simple (F5), this looks like a nasty bug. I would vote for fixing this in GA.

**Comment by vitaliy-guliy** [comment]
I have the same issue in Che on minikube

![Screenshot from 2019-07-22 11-27-20](https://user-images.githubusercontent.com/1655894/61621784-dbc75100-ac73-11e9-9944-3d6ec8e9d05d.png)

It looks something has changed on the backend. Now before refreshing the page plugin manager should wait a bit until workspace has been stopped completely.

Devfile I am using to create a workspace

```yaml
metadata:
  name: che-theia-all
projects:
  - name: che-theia
    source:
      location: 'https://github.com/eclipse/che-theia.git'
      type: git
components:
  - mountSources: true
    endpoints:
      - name: theia-dev-flow
        attributes:
          protocol: http
          public: 'true'
        port: 3030
    memoryLimit: 4Gi
    type: dockerimage
    image: 'eclipse/che-theia-dev:next'
    alias: che-dev
  - id: redhat/vscode-yaml/latest
    type: chePlugin
  - id: che-incubator/typescript/latest
    memoryLimit: 2048M
    type: chePlugin
  - id: eclipse/che-theia/next
    type: cheEditor
    alias: theia-editor
  - id: redhat/php/latest
    type: chePlugin
apiVersion: 1.0.0
commands:
  - name: build ... DEV che-theia
    actions:
      - workdir: /projects/che-theia
        type: exec
        command: |
          yarn
        component: che-dev
```
