### ISSUE TITLE
Network issues on minishift

### ISSUE THREAD

**Issue by vitaliy-guliy** [eclipse-che/che#13928]
### Describe the bug

I have problems with Che running on minishift.
The first one is that Che Plugins panel become not working again. I played with it a lot. It looks like Theia cannot read a plugin list from the plugin registry by some reasons.
Then I tried to build Theia in dev container from souces.
Yarn command failed with an error explaining me that the error is related to network connectivity.

```
rror /projects/theia/node_modules/oniguruma: Command failed.
Exit code: 1
Command: node-gyp rebuild
Arguments: 
Directory: /projects/theia/node_modules/oniguruma
Output:
gyp info it worked if it ends with ok
gyp info using node-gyp@4.0.0
gyp info using node@10.16.0 | linux | x64
gyp http GET https://nodejs.org/download/release/v10.16.0/node-v10.16.0-headers.tar.gz
gyp WARN install got an error, rolling back install
gyp ERR! configure error 
gyp ERR! stack Error: This is most likely not a problem with node-gyp or the package itself and
gyp ERR! stack is related to network connectivity. In most cases you are behind a proxy or have bad 
gyp ERR! stack network settings.
gyp ERR! stack     at Request.<anonymous> (/projects/theia/node_modules/node-gyp/lib/install.js:187:21)
gyp ERR! stack     at Request.emit (events.js:198:13)
gyp ERR! stack     at Request.onRequestError (/projects/theia/node_modules/request/request.js:881:8)
gyp ERR! stack     at ClientRequest.emit (events.js:198:13)
gyp ERR! stack     at TLSSocket.socketErrorListener (_http_client.js:392:9)
gyp ERR! stack     at TLSSocket.emit (events.js:198:13)
gyp ERR! stack     at emitErrorNT (internal/streams/destroy.js:91:8)
gyp ERR! stack     at emitErrorAndCloseNT (internal/streams/destroy.js:59:3)
gyp ERR! stack     at process._tickCallback (internal/process/next_tick.js:63:19)
gyp ERR! System Linux 3.10.0-957.5.1.el7.x86_64
gyp ERR! command "/usr/local/bin/node" "/projects/theia/node_modules/.bin/node-gyp" "rebuild"
gyp ERR! cwd /projects/theia/node_modules/oniguruma
```

To create a workspace I used devfile
```
metadata:
  name: che-theia-all
projects:
  - name: che-theia
    source:
      location: 'https://github.com/eclipse/che-theia.git'
      type: git
components:
  - mountSources: true
    endpoints:
      - name: theia-dev-flow
        attributes:
          protocol: http
          public: 'true'
        port: 3030
    memoryLimit: 4Gi
    type: dockerimage
    image: 'eclipse/che-theia-dev:next'
    alias: che-dev
  - id: redhat/vscode-yaml/latest
    type: chePlugin
  - id: che-incubator/typescript/latest
    memoryLimit: 2048M
    type: chePlugin
  - id: eclipse/che-theia/next
    type: cheEditor
    alias: theia-editor
apiVersion: 1.0.0
commands:
  - name: build ... DEV che-theia
    actions:
      - workdir: /projects/che-theia
        type: exec
        command: |
          yarn
        component: che-dev
```

Switching between different versions of Theia gives nothing.

Commands to start minishift and deploy Che
```
minishift start --memory=10GB --cpus=4 --disk-size=20GB
./chectl-linux server:start --platform=minishift --installer=operator
```

### Che version

 - [x] latest
 - [x] nightly
 - [ ] other: please specify

### Runtime
   - [ ] kubernetes (include output of `kubectl version`) 
   - [ ] Openshift (include output of `oc version`)
   - [ ] minikube (include output of `minikube version` and `kubectl version`)
   - [x] minishift (include output of `minishift version` and `oc version`)
   - [ ] docker-desktop + K8S (include output of `docker version` and `kubectl version`)
   - [ ] other: (please specify)

### Screenshots

![Screenshot from 2019-07-19 15-03-24](https://user-images.githubusercontent.com/1655894/61537081-881bf400-aa36-11e9-813d-f49da2acd502.png)

### Installation method
   - [x] chectl 
   - [x] che-operator 
   - [x] minishift-addon
   - [ ] I don't know

### Environment
   - [x] my computer 
       - [ ] Windows
       - [x] Linux
       - [ ] macOS
   - [ ] Cloud
       - [ ] Amazon
       - [ ] Azure
       - [ ] GCE
       - [ ] other (please specify) 
   - [ ] other: please specify
