### ISSUE TITLE
A project defined in devfile is not cloned

### ISSUE THREAD

**Issue by RomanNikitenko** [eclipse-che/che#13944]
### Describe the bug
The bug is relevant to master branch assembly:
- theia version: https://github.com/theia-ide/theia/commit/3587c23
- che-theia version: https://github.com/eclipse/che-theia/commit/582b1c5

I start workspace from devfile and define in the devfile:
```
projects:
  - name: che-theia
    source:
      type: git
      location: 'https://github.com/eclipse/che-theia.git'
```
But the project is not present when workspace is started

### Che version

 - [ ] latest
 - [ ] nightly
 - [x] other: 7.0.0-rc-4.0-SNAPSHOT

### Steps to reproduce
1. Define in devfile projects section:
```
projects:
  - name: che-theia
    source:
      type: git
      location: 'https://github.com/eclipse/che-theia.git'
```

2. To use `eclipse/che-theia:next` image define in devfile:
```
- 
    alias: theia-editor
    reference: >-
      https://raw.githubusercontent.com/eclipse/che-plugin-registry/master/v3/plugins/eclipse/che-theia/next/meta.yaml
    type: cheEditor

```
3. `chectl workspace:start -f devfile.yaml`

### Expected behavior
The project is present when workspace is started

### Runtime
   - [ ] kubernetes (include output of `kubectl version`) 
   - [ ] Openshift (include output of `oc version`)
   - [x] minikube (minikube v1.0.0 on linux (amd64))
   - [ ] minishift (include output of `minishift version` and `oc version`)
   - [ ] docker-desktop + K8S (include output of `docker version` and `kubectl version`)
   - [ ] other: (please specify)

### Installation method
   - [x] chectl chectl/0.0.2-6d3894f linux-x64 node-v10.4.1)
   - [ ] che-operator 
   - [ ] minishift-addon
   - [ ] I don't know

### Environment
   - [ ] my computer 
       - [ ] Windows
       - [x] Linux
       - [ ] macOS
   - [ ] Cloud
       - [ ] Amazon
       - [ ] Azure
       - [ ] GCE
       - [ ] other (please specify) 
   - [ ] other: please specify
