### ISSUE TITLE
Task: Changing a command in the devfile of an existing workspace is not taken in account

### ISSUE THREAD

**Issue by sunix** [eclipse-che/che#13994]
### Describe the bug
Changing any of the devfile commands of an existing (and started) workspace from the dashboard is not affecting the workspace (even after restart).

### Che version

 - [ ] latest
 - [x] nightly
 - [ ] other: please specify

### Steps to reproduce
1. start a workspace with this devfile containing a command that would run on a plugin side car container. For instance:
   ```bash
    $ chectl workspace:start -f <(chectl devfile:generate --name=test-task-change-devfile --dockerimage=sunix/git-devtools --command="echo hello world")
      ✔ Retrieving Che Server URL...http://che-che.192.168.39.13.nip.io
      ✔ Verify if Che server is running...RUNNING (auth disabled)
      ✔ Create workspace from Devfile /dev/fd/63
    
    Workspace IDE URL:
    http://che-che.192.168.39.13.nip.io/dashboard/#/ide/che/test-task-change-devfile
    ```

    ```yaml
    apiVersion: 1.0.0
    metadata:
      name: test-task-change-devfile
    components:
      - alias: sunix-git-devtools
        type: dockerimage
        image: sunix/git-devtools
        memoryLimit: 512M
        mountSources: true
        command:
          - tail
        args:
          - '-f'
          - /dev/null
    commands:
      - name: echo hello world
        actions:
          - type: exec
            command: echo hello world
            component: sunix-git-devtools
            workdir: /projects/
   ```
2. open the workspace and execute the task: it works well
    ![Eclipse Che | test-task-change-devfile - Google Chrome_361](https://user-images.githubusercontent.com/650571/61791072-3948d280-ae19-11e9-8889-f9a4faeec655.png)

3. stop the workspace
4. go to the dashboard and edit the devfile. Change the command to display 'hello che world'
    ![Selection_362](https://user-images.githubusercontent.com/650571/61791053-28985c80-ae19-11e9-9a88-6e550cf0300e.png)

5. restart the workspace
6. rerun the task. It is displaying 'hello world' and not 'hello che world'
    ![Eclipse Che | test-task-change-devfile - Google Chrome_363](https://user-images.githubusercontent.com/650571/61791030-13233280-ae19-11e9-91e4-d236ebf5f83c.png)

### Runtime
   - [ ] kubernetes (include output of `kubectl version`) 
   - [ ] Openshift (include output of `oc version`)
   - [x] minikube (include output of `minikube version` and `kubectl version`)
   - [ ] minishift (include output of `minishift version` and `oc version`)
   - [ ] docker-desktop + K8S (include output of `docker version` and `kubectl version`)
   - [ ] other: (please specify)

### Installation method
   - [x] chectl 
   - [ ] che-operator 
   - [ ] minishift-addon
   - [ ] I don't know

### Environment
   - [x] my computer 
       - [ ] Windows
       - [x] Linux
       - [ ] macOS
   - [ ] Cloud
       - [ ] Amazon
       - [ ] Azure
       - [ ] GCE
       - [ ] other (please specify) 
   - [ ] other: please specify
