### ISSUE TITLE
che task: Cannot run a che command after workspace restart for some containers 

### ISSUE THREAD

**Issue by sunix** [eclipse-che/che#13993]
### Describe the bug
Cannot rerun commands that are targeting a plugin container after restart of a workspace.

### Che version
 - nightly
 
### Steps to reproduce
1. start a workspace with this devfile containing a command that would run on a plugin sidecar container. For instance:
   ```bash
    $ chectl workspace:start -f <(chectl devfile:generate --name=test-task-bug-restart --language=java --command="echo hello world")
      ✔ Retrieving Che Server URL...http://che-che.192.168.39.13.nip.io
      ✔ Verify if Che server is running...RUNNING (auth disabled)
      ✔ Create workspace from Devfile /dev/fd/63
    
    Workspace IDE URL:
    http://che-che.192.168.39.13.nip.io/dashboard/#/ide/che/test-task-bug-restart
    ```

    ```yaml
    apiVersion: 1.0.0
    metadata:
      name: test-task-bug-restart
    components:
      - type: chePlugin
        alias: java-ls
        id: redhat/java/latest
    commands:
      - name: echo hello world
        actions:
          - type: exec
            command: echo hello world
            component: java-ls
            workdir: /projects/
   ```
2. open the workspace and execute the task: it works well
3. stop the workspace
4. restart it and reopen it
5. Try to run the task again, it doesn't work anymore. The terminal is appearing but nothing is executed.
    ![Eclipse Che | test-task-bug-restart - Google Chrome_360](https://user-images.githubusercontent.com/650571/61789422-f38a0b00-ae14-11e9-9280-9b11e5f39112.png)

    The error `Uncaught (in promise) Error: container with name vscode-javaebs was not found. For workspace: workspaceeau9fy5dqm79n36l`. But the `vscode-javaebs` was the container name when it started the first time.
    Fixing the `/projects/.theia/tasks.json` with the right machineName works.

### Expected behavior
The task is supposed to be running after restart and display "hello world" (for the previous example)

### Runtime
   - minikube (include output of `minikube version` and `kubectl version`)

### Installation method
   - chectl 

### Environment
   - my computer 
       - Linux
