### ISSUE TITLE
Variables are not resolved for execution of che commands

### ISSUE THREAD

**Issue by RomanNikitenko** [eclipse-che/che#14031]
### Describe the bug
We have ability to define variables like `${file}` for che commands in a devfile.
It works well for theia tasks, but doesn't work for che commands.

### Che version

 - [ ] latest
 - [ ] nightly
 - [x] other: che-theia:7.0.0-next

### Steps to reproduce

1. Use in devfile command like:
```
- name: copy content
  actions:
  - type: exec
    component: che-dev
    command: >
              cp ${workspaceFolder}/.theia/tasks.json ${workspaceFolder}/cheCommands.json
    workdir: /projects
```
2. Run the task
3. You can see that task can not be executed because the variable is not resolved

### Expected behavior
The variable is resolved and the task is executed  

### Runtime
   - [ ] kubernetes (include output of `kubectl version`) 
   - [ ] Openshift (include output of `oc version`)
   - [x] minikube (v1.0.0)
   - [ ] minishift (include output of `minishift version` and `oc version`)
   - [ ] docker-desktop + K8S (include output of `docker version` and `kubectl version`)
   - [ ] other: (please specify)

### Installation method
   - [x] chectl chectl/0.0.2-6d3894f linux-x64 node-v10.4.1
   - [ ] che-operator 
   - [ ] minishift-addon
   - [ ] I don't know

### Environment
   - [x] my computer 
       - [ ] Windows
       - [x] Linux
       - [ ] macOS
   - [ ] Cloud
       - [ ] Amazon
       - [ ] Azure
       - [ ] GCE
       - [ ] other (please specify) 
   - [ ] other: please specify
