### ISSUE TITLE
Plugin brokering fails TLS, self-signed certificates and embedded registries 

### ISSUE THREAD

**Issue by davidfestal** [eclipse-che/che#14087]
### Describe the bug

When running Che with TLS, self-signed certificates enabled, and embedded registries (deployed behind Openshift routes), the plugin broker fails when trying to access the plugin registry because the certificate is unknown.

### Che version
 - [x] latest
 - [x] nightly
 - [ ] other: please specify

### Steps to reproduce

With the Operator or Che Ctl, install Che with the following custom resource:

```yaml
apiVersion: org.eclipse.che/v1
kind: CheCluster
metadata:
  name: eclipse-che
spec:
  server:
    cheImageTag: nightly
    devfileRegistryImage: 'quay.io/eclipse/che-devfile-registry:nightly'
    pluginRegistryImage: 'quay.io/eclipse/che-plugin-registry:nightly'
    tlsSupport: true
    selfSignedCert: true
  auth:
    openShiftoAuth: true
    identityProviderImage: 'eclipse/che-keycloak:nightly'
  storage:
    pvcStrategy: per-workspace
    pvcClaimSize: 1Gi
    preCreateSubPaths: true
```

And try to start a workspace. You will have an error coming from the plugin broker.

### Expected behavior

Workspace should start correctly.

### Runtime
   - [ ] kubernetes (include output of `kubectl version`) 
   - [x] Openshift (include output of `oc version`)
   - [ ] minikube (include output of `minikube version` and `kubectl version`)
   - [x] minishift (include output of `minishift version` and `oc version`)
   - [ ] docker-desktop + K8S (include output of `docker version` and `kubectl version`)
   - [ ] other: (please specify)

### Installation method
   - [ ] chectl 
   - [x] che-operator 
   - [ ] minishift-addon
   - [ ] I don't know

### Environment
   - [ ] my computer 
       - [ ] Windows
       - [ ] Linux
       - [ ] macOS
   - [ ] Cloud
       - [x] Amazon
       - [ ] Azure
       - [ ] GCE
       - [ ] other (please specify) 
   - [ ] other: please specify
