### ISSUE TITLE
Add marketplace Vscode plugin for Puppet seems not working

### ISSUE THREAD

**Issue by disaster37** [eclipse-che/che#14099]
Hi,
I currently use the lastest version of eclipse CHE 7.0.0-rc-4.0-SNAPSHOT and I try to use the Vscode plugin for puppet https://marketplace.visualstudio.com/items?itemName=jpogran.puppet-vscode.

I have following this article https://github.com/eclipse/che/wiki/CHE-7---Development-Workflow to do that, but it seems doesn't work.

The workspace run fine, the docker container that handle the puppet-vscode plugin run fine and download the vsix file, but it seems that theia never load it. In theia, on plugin view, the plugin seems not installed (I look the plugin with button install) and the code highlighting doesn't work.

Sample of devfile to reproduce it:
```
metadata:
  name: puppet
components:
  - type: chePlugin
    alias: puppet-plugin
    reference: >-
      https://raw.githubusercontent.com/disaster37/che-remote-plugin-puppet/f2930ce56c0c7322261425c6152ffdbc597dcc52/plugins/jpogran/puppet-vscode/latest/meta.yaml
  - mountSources: true
    memoryLimit: 512Mi
    type: dockerimage
    volumes:
      - name: userspace
        containerPath: /home/dev
    image: 'webcenter/che-puppet:latest'
    alias: puppet-cli
apiVersion: 1.0.0
```

Anybody know what is the mistake ?
