### ISSUE TITLE
Impossible to set boolean value for preferences via devfile

### ISSUE THREAD

**Issue by tolusha** [eclipse-che/che#14131]
### Describe the bug
Impossible to set boolean value for preferences via devfile.
It is automatically converted into a string.

### Che version

 - [ ] latest
 - [x] nightly
 - [ ] other: please specify

### Steps to reproduce

1. Add preferences into devfile
```
  preferences:
   some_attribute: false
```
2. It is automatically converted into:
```
  preferences:
   some_attribute: 'false'
```
3. Start a workspace
4. Check user preferences:
```
{
   some_attribute: "false"
}
```
5. The value of the attribute is treated as string instead of boolean

### Expected behavior
Expected boolean value for an attribute.

### Runtime
   - [ ] kubernetes (include output of `kubectl version`) 
   - [ ] Openshift (include output of `oc version`)
   - [ ] minikube (include output of `minikube version` and `kubectl version`)
   - [X] minishift (include output of `minishift version` and `oc version`)
   - [ ] docker-desktop + K8S (include output of `docker version` and `kubectl version`)
   - [ ] other: (please specify)

### Installation method
   - [X] chectl 
   - [ ] che-operator 
   - [ ] minishift-addon
   - [ ] I don't know

### Environment
   - [X] my computer 
       - [ ] Windows
       - [X] Linux
       - [ ] macOS
   - [ ] Cloud
       - [ ] Amazon
       - [ ] Azure
       - [ ] GCE
       - [ ] other (please specify) 
   - [ ] other: please specify

### Additional context
It is needed for https://github.com/eclipse/che/issues/13698

**Comment by benoitf** [comment]
feature issue is for `7.1.0` so putting the same milestone there

**Comment by benoitf** [comment]
cc @skabashnyuk @ibuziuk

**Comment by sleshchenko** [comment]
Seems it duplicates https://github.com/eclipse/che/issues/13302 but the title definitely is more precise here )

**Comment by mshaposhnik** [comment]
@tolusha am i correct - you mean the attributes of the root devfile object ? (there is no preferences field except the one in chePlugin type)?

**Comment by tolusha** [comment]
@mshaposhnik 
I mean in the preferences field of the chePlugin.

```
components:
-
  type: chePlugin
  reference: https://raw.githubusercontent.com/tolusha/plugins-registry/master/plugins/tolusha/cpptools/0.1/meta.yaml
  alias: cpp-plugin
  preferences:
    clangd.path: /usr/bin/clangd
    cdt.clangd.binaries.enable: false
```
