### ISSUE TITLE
Sometimes terminal colors cannot be removed

### ISSUE THREAD

**Issue by mmorhun** [eclipse-che/che#14159]
### Describe the bug
Sometimes after colored output terminal fails to reset attributes (like color, bold font). Even new opened terminals have last used color as default. For example, if maven build fails, text color in terminal will be red and if one opens new terminal it will have red color as default. If restart build and it finishes successfully, we'll have green text in this and all new terminals (but opened red-text terminals will still have red color). Reset doesn't help. Commands which reset color doesn't do it either (like `ls`).

### Che version
Che master nightly

### Steps to reproduce

Seems it could be reproduces in some cases, not all the time, but if it could be - it is reproducible 100%

1. Run a command which does color output
2. Open a new terminal

### Expected behavior
Command could undo colored output.
`reset` command from terminal returns output color to normal.

### Runtime
Minishift  v1.34.1+c2ff9cb

### Screenshots
![terminal-color-bug](https://user-images.githubusercontent.com/15607393/62708324-d9971d80-b9fb-11e9-87a0-c804ff2febe6.gif)

### Installation method
chectl

### Additional context

<details>
<summary>Devfile from which workspace was created</summary>

```
metadata:
  name: che-in-che
projects:
  - name: che
    source:
      location: 'https://github.com/eclipse/che.git'
      type: git
      branch: master
components:
  - referenceContent: |
      ---
      kind: List
      items:
       - apiVersion: v1
         kind: Pod
         metadata:
           name: ws
         spec:
           containers:
           - name: dev
             image: 'eclipse/che-dev:nightly'
             resources:
               limits:
                 memory: 5Gi
             volumeMounts:
             - mountPath: /projects
               name: projects
             - mountPath: /home/user/.m2
               name: maven
           volumes:
           - name: projects
             persistentVolumeClaim:
               claimName: projects
           - name: maven
             persistentVolumeClaim:
                claimName: maven
       - apiVersion: v1
         kind: PersistentVolumeClaim
         metadata:
           name: projects
         spec:
           accessModes:
            - ReadWriteOnce
           resources:
             requests:
               storage: 2Gi
       - apiVersion: v1
         kind: PersistentVolumeClaim
         metadata:
           name: maven
         spec:
           accessModes:
            - ReadWriteOnce
           resources:
             requests:
               storage: 3Gi
    type: kubernetes
    alias: che-dev
apiVersion: 1.0.0
commands:
  - name: fastbuild
    actions:
      - workdir: /projects/che
        type: exec
        command: cd /projects/che && mvn clean install -Pnative -DskipTests=true
        component: che-dev
```

</details>

Command which was run in Che root folder:
```
mvn clean install -Pnative -Dche-core-typescript-dto-maven-plugin.test.excludes="**/*TypeScriptDTOGeneratorMojoITest.java"
```

Che repository state: `30fec3173d6c25bdef53ed490970f75029092650`
