### ISSUE TITLE
Devfiles: Che doesn't expand projects in zip archives

### ISSUE THREAD

**Issue by johnmcollier** [eclipse-che/che#14206]
### Describe the bug
I saw that the Devfile spec supports zip archives, so I created a devfile that references a project in a zip archive (located [here](https://raw.githubusercontent.com/johnmcollier/devfiles/master/che/devfile_zip.yaml)):
```
---
apiVersion: 1.0.0
metadata:
  name: zip-che
projects:
  - name: microproj
    source:
      type: zip
      location: 'https://raw.githubusercontent.com/johnmcollier/codewind-appsody-templates/master/codewind-appsody-java-microprofile-master.zip'
components:
  - alias: theia-ide
    type: cheEditor
    id: eclipse/che-theia/7.0.0-rc-4.0
```

When I go to create a workspace, the workspace is created fine, however Che tries to git clone the zip archive, rather than unzipping it. What's interesting is that instead of reporting an error, Che doesn't report any problems and in fact, it says the clone was successful, despite the project location not being a git repo.

### Che version

 - [ ] latest
 - [x] nightly
 - [ ] other: please specify

### Steps to reproduce

Create a workspace from my devfile linked above. Workspace creation will succeed, but there will be no projects in the workspace. Theia will display a message saying the zip archived was git cloned `/projects` and checked out default breanch

### Expected behavior
Che downloads the zip archive and unzips it under `/projects/`

### Runtime
   - [ ] kubernetes (include output of `kubectl version`) 
   - [ ] Openshift (include output of `oc version`)
   - [ ] minikube (include output of `minikube version` and `kubectl version`)
   - [ ] minishift (include output of `minishift version` and `oc version`)
   - [x] docker-desktop + K8S (include output of `docker version` and `kubectl version`)
   - [ ] other: (please specify)

```
johns-mbp-3:~ johncollier$ docker version
Client: Docker Engine - Community
 Version:           19.03.0-rc2
 API version:       1.40
 Go version:        go1.12.5
 Git commit:        f97efcc
 Built:             Wed Jun  5 01:37:53 2019
 OS/Arch:           darwin/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          19.03.0-rc2
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.12.5
  Git commit:       f97efcc
  Built:            Wed Jun  5 01:42:10 2019
  OS/Arch:          linux/amd64
  Experimental:     true
 containerd:
  Version:          v1.2.6
  GitCommit:        894b81a4b802e4eb2a91d1ce216b8817763c29fb
 runc:
  Version:          1.0.0-rc8
  GitCommit:        425e105d5a03fabd737a126ad93d62a9eeede87f
 docker-init:
  Version:          0.18.0
  GitCommit:        fec3683

```

```
johns-mbp-3:~ johncollier$ k version
Client Version: version.Info{Major:"1", Minor:"13", GitVersion:"v1.13.3", GitCommit:"721bfa751924da8d1680787490c54b9179b1fed0", GitTreeState:"clean", BuildDate:"2019-02-01T20:08:12Z", GoVersion:"go1.11.5", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.3", GitCommit:"5e53fd6bc17c0dec8434817e69b04a25d8ae0ff0", GitTreeState:"clean", BuildDate:"2019-06-06T01:36:19Z", GoVersion:"go1.12.5", Compiler:"gc", Platform:"linux/amd64"}
```

### Screenshots
![Screen Shot 2019-08-12 at 2 24 02 PM](https://user-images.githubusercontent.com/6880023/62888245-db6b2480-bd0c-11e9-9a56-0f78cd955631.png)
