### ISSUE TITLE
Conflicting endpoints names for multiple users

### ISSUE THREAD

**Issue by ghost** [eclipse-che/che#14263]
When two users create workspaces from the same devfile template which has a separate mysql component (just an example), the second users workspace cannot create its own mysql component. This is because the mysql component (which has an discoverable endpoint) trys to create a kubernetes service with an already existing name.

```
  - alias: mysql
    type: dockerimage
    image: centos/mysql-57-centos7
    memoryLimit: 512Mi
    mountSources: false
    endpoints:
      - name: mysql
        attributes:
          discoverable: true
        port: 3306
```

A dynamic endpoint configuration like the one below could solve the issue but does not work.
```
    endpoints:
      - name: $(CHE_WORKSPACE_ID)-mysql
```
Is there a better approach to solve this problem?

The problem occurs in che multiuser 7.0.0 Kubernetes on GCP.
