### ISSUE TITLE
Failed to start sidecar container with c++ tools

### ISSUE THREAD

**Issue by tolusha** [eclipse-che/che#14290]
It is impossible to start a sidecar container with c++ tools due to error (see below)

### Che version

 - [ ] latest
 - [x] nightly
 - [ ] other: please specify

### Steps to reproduce

1. Create a workspace from the devfile below
2. Get a sidecat logs to observe the error below

### Expected behavior
Workspace is supposed to be started

### Runtime
   - [ ] kubernetes (include output of `kubectl version`) 
   - [ ] Openshift (include output of `oc version`)
   - [ ] minikube (include output of `minikube version` and `kubectl version`)
   - [x] minishift (include output of `minishift version` and `oc version`)
   - [ ] docker-desktop + K8S (include output of `docker version` and `kubectl version`)
   - [ ] other: (please specify)

### Installation method
   - [ ] chectl 
   - [x] che-operator 
   - [ ] minishift-addon
   - [ ] I don't know

### Environment
   - [x] my computer 
       - [ ] Windows
       - [x] Linux
       - [ ] macOS
   - [ ] Cloud
       - [ ] Amazon
       - [ ] Azure
       - [ ] GCE
       - [ ] other (please specify) 
   - [ ] other: please specify

### Additional context
devfile:
```yaml
metadata:
  name: cpp
projects:
  - name: cpp-hello-world
    source:
      location: 'https://github.com/che-samples/cpp-hello-world'
      type: git
      branch: master
components:
  - type: chePlugin
    alias: cpp-plugin
    reference: >-
      https://raw.githubusercontent.com/eclipse/che-plugin-registry/master/v3/plugins/che-incubator/cpptools/latest/meta.yaml
  - mountSources: true
    command:
      - sleep
    args:
      - infinity
    memoryLimit: 512Mi
    type: dockerimage
    image: registry.centos.org/centos/devtoolset-7-toolchain-centos7
    alias: cpp-dev
  - id: eclipse/che-theia/next
    type: cheEditor
apiVersion: 1.0.0
commands:
  - name: build
    actions:
      - workdir: '${CHE_PROJECTS_ROOT}/cpp-hello-world'
        type: exec
        command: g++ -g hello.cpp -o hello.out
        component: cpp-dev
  - name: debug
    actions:
      - referenceContent: |
          {
            "version": "0.2.0",
            "configurations": [
                {
                    "type": "gdb",
                    "name": "Debug c++ application",
                    "request": "launch",
                    "program": "/projects/cpp-hello-world/hello.out"
                }
            ]
          }
        type: vscode-launch
```

stacktrace: 
```
Resolved "che-incubator.cpptools.latest.uybytuisua.llvm-vs-code-extensions.vscode-clangd-0.0.16.vsix" to a VS Code extension "vscode-clangd@0.0.16" with engines: { vscode: '^1.36.0' }
--
  | /home/theia/node_modules/@theia/plugin-ext-vscode/lib/node/plugin-vscode-resolver.js:129
  | asset = extension.versions[0].files.filter(function (f) { return f.assetType === 'Microsoft.VisualStudio.Services.VSIXPackage'; })[0];
  | ^
  | TypeError: Cannot read property 'versions' of undefined
  | at Request._callback (/home/theia/node_modules/@theia/plugin-ext-vscode/lib/node/plugin-vscode-resolver.js:129:55)
  | at Request.self.callback (/home/theia/node_modules/request/request.js:185:22)
  | at Request.emit (events.js:198:13)
  | at Request.<anonymous> (/home/theia/node_modules/request/request.js:1161:10)
  | at Request.emit (events.js:198:13)
  | at IncomingMessage.<anonymous> (/home/theia/node_modules/request/request.js:1083:12)
  | at Object.onceWrapper (events.js:286:20)
  | at IncomingMessage.emit (events.js:203:15)
  | at endReadableNT (_stream_readable.js:1145:12)
  | at process._tickCallback (internal/process/next_tick.js:63:19)
```
