### ISSUE TITLE
Support customOIDCProvider as an option instead of forcing keycloak in Che k8s Operator

### ISSUE THREAD

**Issue by z0r0** [eclipse-che/che#14413]
### Is your enhancement related to a problem? Please describe.
Currently, the che operator seems to be the appropriate medium of configuration and manageability for large scale kubernetes deploys. Because of this, I'm trying to use this, in addition to an external postgres DB, and an external OIDC Provider. The external postgres configuration is complete, but the OIDC provider isn't supported (yet). We don't have a deployment of keycloak, and don't intend to if at all possible.

### Describe the solution you'd like
It's simple, the same configuration that's available within the helm deploy with the `customOidcProvider` flag, as well as `cheKeycloakClientId` should be used to deploy to a custom oidc provider.

### Describe alternatives you've considered
None

### Additional context
None

**Comment by tolusha** [comment]
All needed properties can be set into a CR under `spec.server.customCheProperties` field:

```yaml
spec:
  server:
    customCheProperties:
      CHE_KEYCLOAK_CLIENT__ID
      CHE_KEYCLOAK_CLIENT__ID: 
      CHE_KEYCLOAK_AUTH__SERVER__URL: 
      CHE_KEYCLOAK_REALM: 
      CHE_KEYCLOAK_OIDC__PROVIDER: 
```
