### ISSUE TITLE
Che Theia should inform the user if his workspace has deprecated plugin

### ISSUE THREAD

**Issue by vitaliy-guliy** [eclipse-che/che#14423]
### Is your enhancement related to a problem? Please describe.

A plugin could be deprecated by adding `deprecated` section:
```
publisher: plugin_publisher
id: plugin_id
version: 1.2.3
name: Some plugin
deprecate:
   autoMigrate: true
   migrateTo: another_publisher/another_plugin_id:1.0.0
```

This configuration has been copied from the coresponding issue for the Dashboard. But the latest V3 plugin definition should also have `deprecate` section. 

### Describe the solution you'd like

- Che Theia should inform the user that at least of one of the plugins he is using is deprecated.
- Notification message should have a button to update the plugin. Clicking on the button will update the plugin and will display a proposal to restart the workspace with applying changes. Restarting could be postponed.
- We have to mark a plugin as deprecated when displaying the list of plugins. For that we can use star or any other character displaying in the plugin entry. User should be able to update the plugin using Pluging view

Corresponding issue for Dashboard https://github.com/eclipse/che/issues/13021
