### ISSUE TITLE
[Dashboard] Plugins page is empty when workspace has third-party plugin

### ISSUE THREAD

**Issue by vitaliy-guliy** [eclipse-che/che#14424]
### Describe the bug

In Che-Theia we have an ability to add custom registry. If you add a plugin from that registry, the Plugins page on the Dashboard will be empty.
The same. We can add a third-party plugin by editing a devfile in the corresponding page on the Dashoard. If you add your custom plugin to the devfile, the Plugins will not work.

### Che version

 - [x] latest
 - [x] nightly

### Steps to reproduce
- Describe third party plugin in the devfile.
- Add a plugin from custom plugin registry using Plugins panel in Che-Theia

### Expected behavior

Plugins panel should display third-party plugin in the list. User should be able to disable/remove third-party plugin in Dashboard > Plugins page.

Does not depend on the runtime, installation method or environment.

### Screenshots

![dashboardpluginsfailed-3](https://user-images.githubusercontent.com/1655894/64271609-e39a3680-cf3d-11e9-9df1-7b7f75d8f974.gif)

Video with high resolution https://youtu.be/3dbmhXtuavY

### Devfile

Try to create a workspace with this devfile and switch to Plugins page in the dashboard

```yaml
metadata:
  name: che-theia-all
projects:
  - name: che-theia
    source:
      location: 'https://github.com/eclipse/che-theia.git'
      type: git
      branch: master
  - name: theia
    source:
      location: 'https://github.com/theia-ide/theia.git'
      type: git
      branch: master
components:
  - mountSources: true
    endpoints:
      - name: theia-dev-flow
        attributes:
          protocol: http
          public: 'true'
        port: 3010
    memoryLimit: 3Gi
    type: dockerimage
    image: 'eclipse/che-theia-dev:next'
    alias: che-dev
  - id: redhat/vscode-yaml/latest
    type: chePlugin
  - id: che-incubator/typescript/latest
    type: chePlugin
  - type: chePlugin
    reference: >-
      https://raw.githubusercontent.com/vitaliy-guliy/che-theia-plugin-registry/master/plugins/eclipse-che/tree-view-sample-plugin/latest/meta.yaml
apiVersion: 1.0.0
commands:
  - name: init ... DEV che-theia
    actions:
      - workdir: /projects/theia
        type: exec
        command: |
          che:theia init
        component: che-dev
```
