### ISSUE TITLE
Installed Python Modules Not Accessible

### ISSUE THREAD

**Issue by TuckAndRoll** [eclipse-che/che#14425]
I am very new to Che and I'm trying to get my own python environment set up. I have created my own python docker image that has a 3rd party python module (Pyomo) installed. When I create a workspace and pull this image in via the devfile I can't use the module. I can open a terminal to that image and see that it is installed, but when I run my python script in Theia it doesn't recognize it as being installed. When I try to run

```
import pyomo
```
it fails because it can't find it.

My devfile:
```
metadata:
  name: Pyomo
projects:
  - name: python-hello-world
    source:
      location: 'https://github.com/che-samples/python-hello-world.git'
      type: git
      branch: master
components:
  - id: ms-python/python/latest
    memoryLimit: 512Mi
    type: chePlugin
  - mountSources: true
    memoryLimit: 512Mi
    type: dockerimage
    alias: pyomo
    image: '<my-python-image>'
apiVersion: 1.0.0
commands:
  - name: run
    actions:
      - workdir: '${CHE_PROJECTS_ROOT}/python-hello-world'
        type: exec
        command: python hello-world.py
        component: python

```

My docker file for the custom python image:
```
FROM    192.168.1.8:5000/<ubuntu-image-base>

RUN     sudo apt-get purge -y python.* && \
        sudo apt autoremove -y && \
        sudo apt-get update && \
        sudo apt-get install -y --no-install-recommends \
        autoconf \
        automake \
        bzip2 \
        file \
        g++ \
        gcc \
        imagemagick \
        libbz2-dev \
        libc6-dev \
        libcurl4-openssl-dev libdb-dev libevent-dev libffi-dev libgdbm-dev libgeoip-dev libglib2.0-dev libjpeg-dev \
        libkrb5-dev liblzma-dev libmagickcore-dev libmagickwand-dev libmysqlclient-dev libncurses-dev libpng-dev \
        libpq-dev libreadline-dev libsqlite3-dev libssl-dev libtool libwebp-dev libxml2-dev libxslt-dev libyaml-dev make patch xz-utils zlib1g-dev
ENV     LANG=C.UTF-8
ENV     PYTHON_VERSION=3.7.4
ENV     PYTHON_PIP_VERSION=19.2.3
RUN     set -ex && \
        sudo curl -fSL "https://www.python.org/ftp/python/${PYTHON_VERSION%%[a-z]*}/Python-$PYTHON_VERSION.tar.xz" -o python.tar.xz && \
        sudo curl -fSL "https://www.python.org/ftp/python/${PYTHON_VERSION%%[a-z]*}/Python-$PYTHON_VERSION.tar.xz.asc" -o python.tar.xz.asc && \
        export GNUPGHOME="$(mktemp -d)" && \
        sudo rm -r "$GNUPGHOME" python.tar.xz.asc && \
        sudo mkdir -p /usr/src/python && \
        sudo tar -xJC /usr/src/python --strip-components=1 -f python.tar.xz && \
        sudo rm python.tar.xz && \
        cd /usr/src/python && \
        sudo ./configure --enable-shared --enable-unicode=ucs4 && \
        sudo make -j$(nproc) && \
        sudo make install && \
        sudo ldconfig && \
        sudo pip3 install --upgrade --ignore-installed pip==$PYTHON_PIP_VERSION && \
        sudo pip3 install pyomo && \
        sudo find /usr/local \( -type d -a -name test -o -name tests \) -o \( -type f -a -name '*.pyc' -o -name '*.pyo' \) -exec rm -rf '{}' + && \
        sudo rm -rf /usr/src/python
RUN     cd /usr/local/bin && \ 
        sudo ln -s easy_install-3.7 easy_install && \
        sudo ln -s idle3 idle && \
        sudo ln -s pydoc3 pydoc && \
        sudo ln -s python3 python && \
        sudo ln -s python-config3 python-config
RUN     sudo pip3 install --upgrade pip && \
        sudo pip3 install --no-cache-dir virtualenv && \
        sudo pip3 install --upgrade setuptools && \
        sudo pip3 install 'python-language-server[all]'
EXPOSE  8080
```

Any help would be greatly appreciated.
