### ISSUE TITLE
It isn't possible to start workspace once it has been stopped

### ISSUE THREAD

**Issue by vitaliy-guliy** [eclipse-che/che#14436]
Today morning it become not possible to start the workspace.
The day before I used to stop minikube, and after starting the minikube again my workspace become not accessible.

### Describe the bug

Nothing to describe. Just stop the minikube and start it in a day.
I believe that after deleting the minikube machine, updating chectl and creating the machine again everything could be fine. But it's not an option for the developer who is focused on doing his job.

### Che version

 - [ ] latest
 - [x] nightly

### Steps to reproduce

```
  $minikube stop
  $minikube start
```

### Expected behavior

Workspace must be running with alive IDE.

### Runtime
   - [x] minikube (include output of `minikube version` and `kubectl version`)

### Screenshots

![Screenshot from 2019-09-05 11-36-50](https://user-images.githubusercontent.com/1655894/64331620-66210580-cfd3-11e9-8ce1-81793b6f4f08.png)

![Screenshot from 2019-09-05 11-51-06](https://user-images.githubusercontent.com/1655894/64331649-7638e500-cfd3-11e9-9e85-bbdfa43a391e.png)

### Installation method
   - [x] chectl 

### Environment
   - [x] my computer 
       - [x] Linux

### Devfile
```yaml
metadata:
  name: che-theia-all
projects:
  - name: che-theia
    source:
      location: 'https://github.com/eclipse/che-theia.git'
      type: git
      branch: master
  - name: theia
    source:
      location: 'https://github.com/theia-ide/theia.git'
      type: git
      branch: master
components:
  - mountSources: true
    endpoints:
      - name: theia-dev-flow
        attributes:
          protocol: http
          public: 'true'
        port: 3010
    memoryLimit: 3Gi
    type: dockerimage
    image: 'eclipse/che-theia-dev:next'
    alias: che-dev
  - id: redhat/vscode-yaml/latest
    type: chePlugin
  - id: che-incubator/typescript/latest
    type: chePlugin
apiVersion: 1.0.0
commands:
  - name: init ... DEV che-theia
    actions:
      - workdir: /projects/theia
        type: exec
        command: |
          che:theia init
        component: che-dev
```

IDE2 team is using Che-Theia daily and expected that everything is always working.
Taking that into account I marked the issue as blocking.
