### ISSUE TITLE
Support git clone for repos with self-signed SSL certs

### ISSUE THREAD

**Issue by nickboldt** [eclipse-che/che#14527]
### Is your enhancement related to a problem? Please describe.

Say I'm a customer behind a firewall (air gap). 

I have company wide certs for connecting my local laptop to company internal git repos. 

But when I fire up Che 7, launch a workspace from a devfile...

```
projects:
  - name: java-maven-helloworld
    source:
      type: git
      location: "https://git.mycorp.com/projects-r-us/java-maven-helloworld.git"
```

... and try to clone from the repo, I can't connect:

The only workaround is to open a console in the Che 7 workspace, and do this:

```
git config --global http.sslverify “false”
git clone https://git.mycorp.com/projects-r-us/java-maven-helloworld.git
```

So... how can I get those certs into my che 7 workspace OOTB via the devfile, so I can clone from those repos as part of workspace creation, rather than via a manual step? 

### Describe the solution you'd like

We can do it in same way how it works for Keycloak at the moment, here [helm template](https://github.com/eclipse/che/blob/master/deploy/kubernetes/helm/che/templates/deployment.yaml#L80) and [Java code](https://github.com/eclipse/che/blob/master/infrastructures/kubernetes/src/main/java/org/eclipse/che/workspace/infrastructure/kubernetes/provision/CertificateProvisioner.java#L40) in Che repository. Also need to configure [git trust store](https://stackoverflow.com/questions/9072376/configure-git-to-accept-a-particular-self-signed-server-certificate-for-a-partic). 

Workflow will be:
- admin put somewhere correct SSL certificate for internal Git server (with name like CHE_GIT_SSL_CERT);
- during start workspace we will:
  - mount this certificate on each container as k8s secret, in specified path;
  - modify git config `git config --global http.sslCAInfo /home/some-path/git-certs/cert.pem;`

**Comment by tsmaeder** [comment]
Airgapped seems to be important and short term: p1

**Comment by nickboldt** [comment]
If we could somehow embed a cert inside a devfile, could we then use that cert when starting the workspace?

Or what about some sort of tiny cert-hosting container that a customer would create, which could be mounted into the theia container like https://stackoverflow.com/questions/26028971/docker-container-ssl-certificates ?

**Comment by skabashnyuk** [comment]
What I can suggest: we need to provide the ability of additional configuration for git plugin such as.

```yaml
projects:
  - name: java-maven-helloworld
    source:
      type: git
      location: "https://git.mycorp.com/projects-r-us/java-maven-helloworld.git"
      config:
            http.sslverify: false
            user.name: Scott Chacon
            user.email:  schacon@gmail.com
            color.status:  auto
            color.branch: auto
            color.interactive:  auto
            color.diff: auto
      
```
wdyt @l0rd @sunix @metlos @nickboldt @benoitf ?
