### ISSUE TITLE
When a devfile is included in a GitHub repo the project to clone should be inferred

### ISSUE THREAD

**Issue by maxandersen** [eclipse-che/che#14547]
If I have project without a `devfile.yaml` and links to it like https://che.openshift.io/f?url=https://github.com/maxandersen/quarkus-quickstarts/tree/che a empty workspace is setup but with the project checked out.

If I add a `devfile.yaml` the project is not checked out and so far I've only been able to get something imported by adding: 

```
projects:
  -
    name: quarkus-quickstarts
    source:
      type: git
      location: "https://github.com/maxandersen/quarkus-quickstarts.git"
```

but that now means I'm checking out a hardcoded path and thus the devfile.yaml inside a project is not really working well as I'm getting setup done from a branch potentially a completely different location/project and project checked out in che is from this hardcoded place.

@gorkem  suggested to try: 

```
projects:
  -
    name: quarkus-quickstarts
    source:
      type: git
``

but that gave me:  
"Error occurred during creation a workspace from devfile located at https://raw.githubusercontent.com/maxandersen/quarkus-quickstarts/che/devfile.yaml. Cause: Devfile schema validation failed. Error: (/projects/0/source):The object must have a property whose name is "location".""

Thus I can't see how to make a `devfile.yaml` that is easy to maintain as I would literally have to update that reference on every tag/branch I make for my project.
