### ISSUE TITLE
Cannot access workspace after upgrading from 7.0 to 7.1/7.2

### ISSUE THREAD

**Issue by davidwindell** [eclipse-che/che#14593]
I have just upgraded our helm deployment from 7.0 to 7.1 (and latest master) and we now get a bunch of CORS/Jwtproxy errors and can't access any workspaces :(

### Screenshots
![Screenshot from 2019-09-19 08-22-30](https://user-images.githubusercontent.com/1720090/65222579-4e5b7e00-dab7-11e9-9659-0320e5c31f29.png)

### Che version
 - [x] latest
 - [x] nightly
 - [x] other: 7.1.0 and above

### Steps to reproduce
Launch any workspace.

### Expected behaviour
Be able to launch a workspace and access it via a web browser

### Runtime
   - [x] kubernetes (include output of `kubectl version`) 

```
kubectl version
Client Version: version.Info{Major:"1", Minor:"13", GitVersion:"v1.13.9", GitCommit:"3e4f6a92de5f259ef313ad876bb008897f6a98f0", GitTreeState:"clean", BuildDate:"2019-08-05T09:22:00Z", GoVersion:"go1.11.5", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.6", GitCommit:"96fac5cd13a5dc064f7d9f4f23030a6aeface6cc", GitTreeState:"clean", BuildDate:"2019-08-19T11:05:16Z", GoVersion:"go1.12.9", Compiler:"gc", Platform:"linux/amd64"}
```

### Installation method
Helm charts via Rancher

### Environment
   - [x] my computer 
       - [x] Linux
   - [x] Cloud
       - [x] Amazon

### Additional context

The only changes from default helm chart are listed below
```
global: 
    cheWorkspacesNamespace: "che-hw4gt"
    ingressDomain: "che.che-test.XYZ.com"
    multiuser: "true"

CHE_INFRA_KUBERNETES_POD_SECURITY__CONTEXT_FS__GROUP: "0"
CHE_INFRA_KUBERNETES_POD_SECURITY__CONTEXT_RUN__AS__USER: "0"
```

**Comment by sleshchenko** [comment]
Looks like dashboard needs devfile based workspace in 7.1.0 while you have workspace config based.
Are you able to start new devfile based workspaces?

**Comment by davidwindell** [comment]
@sleshchenko I've created a new workspace from the web GUI but it still won't load (same error)

**Comment by davidwindell** [comment]
Any chance of any assistance with this? We are completely stuck, I've even tried creating a new helm deployment in a new namespace/new filesystem and the same errors persist

**Comment by amisevsk** [comment]
Any logs on Che server? Are the websocket ports accessible from the workspace pod?

**Comment by davidwindell** [comment]
Che server seems OK, as in workspace starts fine and shows as running:

```
2019-09-24 20:29:39,597[nio-8080-exec-6] [INFO ] [o.e.c.a.w.s.WorkspaceRuntimes 432] - Starting workspace 'admin/wksp-dk88' with id 'workspacexu6ell7bu0ypewlp' by user 'admin'
2019-09-24 20:30:52,891[aceSharedPool-0] [INFO ] [o.e.c.a.w.s.WorkspaceRuntimes 835] - Workspace 'admin:wksp-dk88' with id 'workspacexu6ell7bu0ypewlp' started by user 'admin'
```

Is there a CORS problem?

```
Access to XMLHttpRequest at 'http://servernssybnn8-jwtproxy-server-4401.che2.che-test.edge-servers.com/jwt/auth' from origin 'http://che-che2.che2.che-test.XYZ.com' has been blocked by CORS policy: Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource.
```

Or does the 404 error from this mean anything?

```
OPTIONS http://servernssybnn8-jwtproxy-server-4401.che2.che-test.edge-servers.com/jwt/auth 404 (Not Found)
```

**Comment by amisevsk** [comment]
Hm, I'm not terribly familiar with the JWTProxy stuff.

**Comment by skabashnyuk** [comment]
@davidwindell can you share workspace configuration? Is it che6 workspace(workspace config based) or che7(devfilebased)?

**Comment by davidwindell** [comment]
Sure, it's just a basic PHP devfile workspace (launched from the provided stack). All workspaces have the same problem:

```
metadata:
  name: wksp-ob28
projects:
  - name: php-web-simple
    source:
      location: 'https://github.com/che-samples/web-php-simple'
      type: git
components:
  - id: redhat/php/latest
    memoryLimit: 1Gi
    type: chePlugin
  - id: redhat/php-debugger/latest
    memoryLimit: 256Mi
    type: chePlugin
  - mountSources: true
    endpoints:
      - name: 8080/tcp
        port: 8080
    memoryLimit: 512Mi
    type: dockerimage
    volumes:
      - name: composer
        containerPath: /home/user/.composer
      - name: symfony
        containerPath: /home/user/.symfony
    image: 'quay.io/eclipse/che-php-7:nightly'
    alias: php
apiVersion: 1.0.0
commands:
  - name: Start Apache Web Server
    actions:
      - type: exec
        command: service apache2 start
        component: php
  - name: Stop Apache Web Server
    actions:
      - type: exec
        command: service apache2 stop
        component: php
  - name: Restart Apache Web Server
    actions:
      - type: exec
        command: service apache2 restart
        component: php
  - name: Configure Apache Web Server DocumentRoot
    actions:
      - type: exec
        command: >
          if grep -q '/projects$' /etc/apache2/sites-available/000-default.conf;
          then
            sed -i 's|DocumentRoot /projects|DocumentRoot /projects/php-web-simple|' /etc/apache2/sites-available/000-default.conf
          else
            echo "DocumentRoot already configured!"
          fi
        component: php
```
