### ISSUE TITLE
workspace fails after launching the dev-file via che url

### ISSUE THREAD

**Issue by SDAdham** [eclipse-che/che#14590]
### Describe the bug

When launching https://che.mydomain.com/f?url=https://path/to/your/raw/devfile, workspace fails to start
Dev file is not copied as is from the git repo, strange characters are added `>-` to `location` and `gs8sm` to `name`
```
metadata:
  name: MyWebAppgs8sm
projects:
  - name: MyWebApp
    source:
      location: >-
        https://github.com/MyWebApp.git
      type: git
      branch: master
components:
  - id: redhat/php/latest
    memoryLimit: 1Gi
    type: chePlugin
  - id: redhat/php-debugger/latest
    memoryLimit: 256Mi
    type: chePlugin
  - mountSources: true
    endpoints:
      - name: 8080/tcp
        port: 8080
    memoryLimit: 512Mi
    type: dockerimage
    volumes:
      - name: composer
        containerPath: /home/user/.composer
      - name: symfony
        containerPath: /home/user/.symfony
    alias: php
    image: 'quay.io/eclipse/che-php-7:nightly'
apiVersion: 1.0.0
commands:
  - name: Start Apache Web Server
    actions:
      - type: exec
        command: service apache2 start
        component: php
  - name: Stop Apache Web Server
    actions:
      - type: exec
        command: service apache2 stop
        component: php
  - name: Restart Apache Web Server
    actions:
      - type: exec
        command: service apache2 restart
        component: php
  - name: Configure Apache Web Server DocumentRoot
    actions:
      - type: exec
        command: >
          if grep -q '/projects$' /etc/apache2/sites-available/000-default.conf;
          then
            sed -i 's|DocumentRoot /projects|DocumentRoot /projects/MyWebApp/public_html|' /etc/apache2/sites-available/000-default.conf
          else
            echo "DocumentRoot already configured!"
          fi
        component: php
```

### Che version

 - [ ] latest
 - [ ] nightly
 - [X] other: please specify
7.1.0

### Runtime
   - [X] kubernetes (include output of `kubectl version`) 
   - [ ] Openshift (include output of `oc version`)
   - [ ] minikube (include output of `minikube version` and `kubectl version`)
   - [ ] minishift (include output of `minishift version` and `oc version`)
   - [ ] docker-desktop + K8S (include output of `docker version` and `kubectl version`)
   - [ ] other: (please specify)
```
Client Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.3", GitCommit:"2d3c76f9091b6bec110a5e63777c332469e0cba2", GitTreeState:"clean", BuildDate:"2019-08-21T15:34:43Z", GoVersion:"go1.12.9", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.3", GitCommit:"2d3c76f9091b6bec110a5e63777c332469e0cba2", GitTreeState:"clean", BuildDate:"2019-08-21T15:23:49Z", GoVersion:"go1.12.9", Compiler:"gc", Platform:"linux/amd64"}
```

### Screenshots

![image](https://user-images.githubusercontent.com/11182824/65192890-33d7d380-dabc-11e9-9746-85b95079f43e.png)
![image](https://user-images.githubusercontent.com/11182824/65192893-389c8780-dabc-11e9-9afb-f7f6b2921a02.png)

### Installation method
   - [X] chectl 
   - [ ] che-operator 
   - [ ] minishift-addon
   - [ ] I don't know
`chectl server:start --installer=helm --domain=MyDomain.com --multiuser --platform=k8s --tls`
### Environment
   - [X] my computer 
       - [ ] Windows
       - [X] Linux
       - [ ] macOS
   - [X] Cloud
       - [ ] Amazon
       - [ ] Azure
       - [ ] GCE
       - [X] other (please specify) 
   - [X] other: please specify
[Canonical deployment of Kubernetes](https://jaas.ai/kubernetes-core)
