### ISSUE TITLE
Replace the use of `custom` operator config map with a map inside the custom resource.

### ISSUE THREAD

**Issue by davidfestal** [eclipse-che/che#14635]
### Is your enhancement related to a problem? Please describe.

Avoid the need to use the `custom` config map to override any customized Che server property (not driven by the `CheCluster` custom resource).
Instead we shoud have a way to override Che server properties directly inside the Custom resource.

### Describe the solution you'd like

Have a map of values inside the `CheCluster` custom resource to allow overriding any Che server property. Something like:

```
 server:
    # server image used in Che deployment
    cheImage: ''
    # tag of an image used in Che deployment
    cheImageTag: 'nightly'
    ........ etc, etc ....
    overrideCheProperties:
    - name: CHE_SERVER_PROPERTY_1
       value: propValue1
    - name: CHE_SERVER_PROPERTY_2
       value: propValue2
  auth:
    .......etc, etc .....
```

**Comment by nickboldt** [comment]
Adding `installation` label as this is something we need for product.

**Comment by tomgeorge** [comment]
Is there a requirement that you cannot set things in `overrideCheProperties` that isn't a Che property? e.g. am I allowed to:

```yaml
overrideCheProperties:
  - name: CHE_FOO_PROP
    value: bar
```
