### ISSUE TITLE
Need to synchronize Hosted Che (stage / production) Grafana configMaps with Upstream

### ISSUE THREAD

**Issue by ibuziuk** [eclipse-che/che#14652]
### Is your enhancement related to a problem? Please describe.
Currently, there is a discrepancy between che / rhche Grafana cm in upstream and staging / production:

- name of the cm `che-grafana-dashboards` vs `grafana-dashboards`
- upstream cm contains `dasboards.yaml`

```
dashboards.yaml: |-
    apiVersion: 1
    providers:
    - name: 'default'
      orgId: 1
      folder: ''
      type: file
      disableDeletion: false
      updateIntervalSeconds: 10000
      options:
        path: /etc/grafana/provisioning/dashboards
```

### Describe the solution you'd like
Content of all cms is the same

### Describe alternatives you've considered
Currently, the update of Hosted Che Gragana cm requires manual changes in the content of the file. (renaming cm / removing `dashboards.yaml` definition). Ideally Hosted Che Grafana cm should be identical to upstream Cm
