### ISSUE TITLE
User should be able to set/retrieve secrets and see them mounted and/or as env variables

### ISSUE THREAD

**Issue by sunix** [eclipse-che/che#14680]
### Is your enhancement related to a problem? Please describe.
There is already some implementation related to saving ssh keys into secrets and mount them. But the user should be able to customize and not be restricted to ssh keys. The user should be able to store as secrets github token, aws access token. The user should be able choose to mount these values to the place of his choice or make them available as environment variable from the devfile.

https://kubernetes.io/docs/concepts/configuration/secret/#using-secrets-as-environment-variables

### Describe the solution you'd like
It could be using k8s secrets but this is not necessary.
Ideally it would be good to have a UI to set the values

UPD: The scope of this issue will be ability to mount secret as an file or ENV variable, and ability to override some properties in devfile. Applying settings from a configmap will be in separate one.
UPD2: devfile overrides have separate issue https://github.com/eclipse/che/issues/17079

**Comment by sunix** [comment]
We should try to do something similar to https://docs.openshift.com/container-platform/4.3/builds/creating-build-inputs.html#builds-adding-input-secrets-configmaps_creating-build-inputs

**Comment by sunix** [comment]
from https://github.com/eclipse/che/issues/15518#issuecomment-589086790
> The way I see it, is a section in the Dashboard where you could define these configmaps or secrets. We could also have configmaps or secret per organisation. and we could have a way to set these configmap or secrets through chectl.
> 
> I definitely do not see these values/files defined in the devfile. But references to secrets and configmap.
> These secrets and config maps could be used by any workspaces by just referencing them.
> 
> We could have default entries for configmaps and secrets that we use in our default devfiles. These ones could be overriden by the user.

**Comment by sunix** [comment]
This is important to setting up Airgap, for instance injecting a Maven `settings.xml` file that would contain:

- user/password to access to internal server (repositories)
- Several private repos and configurations
- Several  mirrors

See last lines of https://github.com/eclipse/che/issues/15503/#issuecomment-579677970

**Comment by sunix** [comment]
@tolusha I change that one to `severity/P1`
Let me know if it works for you.

**Comment by l0rd** [comment]
We should leverage labels on configmaps and secrets to automatically mount them in workspaces containers. 

For example:
If the a user creates a secret/configmap in his che workspaces namespace with the label `app.kubernetes.io/name: che` then the secret/configmap gets automatically mounted on the workspace pod containers.

**Comment by sunix** [comment]
in my opinion for each container, somehow we need to specify where to mount. It can not be done automatically. Others secrets may need to be exposed as env variable,not mounted.

**Comment by l0rd** [comment]
@sunix right. I think annotations should be used to specify the behaviour.

**Comment by l0rd** [comment]
@skabashnyuk this issue is about being able to mount the secret as a file in a container or used as an environment variable. The default would be to mount as a file but we could controle that as an annotation:

```yaml
---
apiVersion: v1
kind: Secret
metadata:
  name: mvn-settings-secret
  labels:
    app: che                # <--- mandatory: all secrets labeled `app: che` will be mounted
    targetContainer: maven  # <--- optional, if omitted will be mounted on all containers
  annotations:
    mavenSettingsPath: /home/user/.m2/
    mountSecretAsFile: true # <--- the default is false
```

**Comment by skabashnyuk** [comment]
After we add API to add secrets to users k8s namespace we will need also some dashboard UI to use these APIs.

**Comment by skabashnyuk** [comment]
>this issue is about being able to mount the secret as a file in a container or used as an environment variable. 

The name of the environment variable should be set with annotation too?

**Comment by sunix** [comment]
I thought we would be able to add the path where to mount in the container definition: https://github.com/eclipse/che/issues/15518#issuecomment-610624721

**Comment by sunix** [comment]
But I don't see how that could be generic setting an annotation name with mvn in it.

**Comment by skabashnyuk** [comment]
@l0rd from you POV how these secrets should appear in the system. Is it going to be some kind of Che API to do that?

**Comment by l0rd** [comment]
@skabashnyuk I don't think that we should work on dashboard side (and che API side) yet. It's ok if we just document how to manually create secrets in che-namespaces that wsmaster will automatically include in workspaces. When this is will be implemented we will have covered scenarios like che.osio where the che namespaces with their quotas, secrets, SA privileges etc...are pre-created and managed by an admin or a third party service. That's is imo the config that users and customers should use most of the time. Then we should adopt this new injection mechanism for SSH keys as well to avoid storing them in postgres. This issue doesn't include the update to SSH keys injections but I am mentioning here it to clarify the use cases.

> The name of the environment variable should be set with annotation too?
Yes I would use an annotation for that as well.

@sunix the path in the secret will be the default one. But that can be customized in the devfile as described [in the comment](https://github.com/eclipse/che/issues/15518#issuecomment-610624721) (I have updated the sample in the comment so that the annotation in the devfile and in the secret are identical).

**Comment by skabashnyuk** [comment]
@l0rd A few comments to https://github.com/eclipse/che/issues/14680#issuecomment-625186250
1. If we want to make Secrets feature generic it would be nice to have `mavenSettingsPath` key more generic, like `mountPath`
2. If we want to mount  Secrets as environment variable we need one more key `envName:...`

```yaml
---
apiVersion: v1
kind: Secret
metadata:
  name: mvn-settings-secret
  labels:
    app: che                
    targetContainer: maven  
  annotations:
    mountPath: /home/user/.m2/  #  <- Name of the key should be generic
    useSecretAsEnv: false    
    envName: MY_ENV             # <--- Used if useSecretAsEnv:true to mount as environment variable.
data:
  settings.xml:  ...
```
3. To be able to explicitly override `mountPath` or `envName` of concrete Secret we need a pair `secretName` and `key` that we want to override + value. It can look like this in devfile

```yaml
devfile.yaml
---
...
components:
 - type: dockerimage
   annotations:
      mvn-settings-secret: mountPath=/home/user2/.m2/
      mvn-settings-secret: envName=ENV_NAME2
   alias: maven
   image: maven:3.11
...
```
or 
```yaml    

devfile.yaml
---
...
components:
 - type: dockerimage
   alias: maven
   image: maven:3.11
   secrets:
      mvn-settings-secret:
         mountPath=/home/user2/.m2/
...      envName=ENV_NAME2 

```

wdyt?

**Comment by l0rd** [comment]
@skabashnyuk makes sense. I am not sure you can have 2 annotation with the same key though.

**Comment by mshaposhnik** [comment]
Just to make sure we can fit this issue into sprint, i propose to assume it as an ability to mount secret as file or ENV, and override it via devfile. Adding amaven settings via configmap can be done in separate one later. Is that works for you @sunix @l0rd  ?

**Comment by l0rd** [comment]
@mshaposhnik that works for me. You can even start with "secret as file" only and then iterate.

**Comment by mshaposhnik** [comment]
So i started to implement this task, and several things seems need to be confirmed.
First is about secret labeling:
Using just `app:che` seems too general for me, so I tend to make it configurable, i.e. having some property like `che.workspace.provision.secret.labels=app:che,foo:bar`, so we can choose which objects to pick-up easily. This will also minify risk of overlap with Che-server generated per-workspace secrets (SSH keys, tokens etc), even if they're will have `app:che`,  (plus, they're all have `che.workspace_id: abcdxyz` label)

**Comment by mshaposhnik** [comment]
Second thing is to allow bind multiple ENV variables by single secret. Proposal is following:
```
apiVersion: v1
data:
  mybar: YWRtaW4=
  myfoo: bXliYXI=
kind: Secret
metadata:
  annotations:
    mybar.envName: MY_BAR
    myfoo.envName: MY_FOO
    useSecretAsEnv: 'true'
  labels:
    app: che
    foo: bar
```
In case of sinle value, ENV name annotation can be either `myfoo.envName: MY_FOO` or simply `envName: MY_FOO`:

```
apiVersion: v1
data:
  myfoo: bXliYXI=
kind: Secret
metadata:
  annotations:
    envName: MY_FOO
    useSecretAsEnv: 'true'
```

**Comment by sunix** [comment]
hello @mshaposhnik this is looking nice. Would it be possible to make a first implementation as a preview feature? It means: that would be available for the user but we say that the api/format can change in the next releases: I would like to have that ASAP and test it in my flow to give you feedback.

**Comment by sunix** [comment]
@mshaposhnik eventually, I would like ssh keys to be stored using that mechanism.

**Comment by mshaposhnik** [comment]
@sunix let's not mix everything into single wineglass :)

**Comment by sunix** [comment]
yes, 
> eventually
:) but it really makes sense

**Comment by l0rd** [comment]
@mshaposhnik makes sense. For the naming I am not satisfied by `goal: mount`. Looking at  [kubernetes recommended labels](https://kubernetes.io/docs/concepts/overview/working-with-objects/common-labels/) I am thinking about `app.kubernetes.io/part-of: org.eclipse.che, app.kubernetes.io/component: workspace-secret`.

**Comment by mshaposhnik** [comment]
@l0rd @sunix   During testing, found an very annoying thing, not sure you were aware of it...
In short, every folder that is creaded using config map or secret as a soure, is readonly, no matter what we'll write in defenition. Here is K8S issue: https://github.com/kubernetes/kubernetes/issues/62099

So it means, for example, if we create foder `.m2` with some file inside by secret mount, it will be readonly, so maven cannot create `repository` here. 

Dunno if it's acceptable for us now? 

The workaround can be pre-creating such forders in image. Or what i saw in K8S issue discussion, here is also some way with launching init containers which will create shared folders so the secret mount haven't create them.

**Comment by sunix** [comment]
We have to change the current m2 volume to `/location.user.home/.m2/repository/` ... not `/location.user.home/.m2`
the settings.xml should come from configuration ... not volume.

**Comment by l0rd** [comment]
@mshaposhnik https://github.com/eclipse/che/issues/15518#issuecomment-625178344

**Comment by skabashnyuk** [comment]
@l0rd  here https://github.com/eclipse/che/pull/16895#discussion_r426422637 https://github.com/eclipse/che/pull/16895#discussion_r426423002 https://github.com/eclipse/che/pull/16895#discussion_r426451261 @metlos  have a few suggestions about annotation format. Can you take a look and tell us what do you think?

**Comment by l0rd** [comment]
@skabashnyuk @mshaposhnik I do like @metlos proposals

**Comment by mshaposhnik** [comment]
So, with the all recent updates, here is how the secrets will looks like:

1) File mount:
```
---
apiVersion: v1
kind: Secret
metadata:
  name: mvn-settings-secret
  labels:
    app.kubernetes.io/part-of: org.eclipse.che   
    app.kubernetes.io/component: workspace-secret
  annotations:
    org.eclipse.che/target-container: maven  
    org.eclipse.che/mount-path: /home/user/.m2/
    org.eclipse.che/mount-as: file
data:
  settings.xml:  ...
```
will result in `settings.xml` mount in `/home/user/.m2/`

2) Single ENV mount:
```
---
apiVersion: v1
kind: Secret
metadata:
  name: mvn-settings-env
  labels:
    app.kubernetes.io/part-of: org.eclipse.che   
    app.kubernetes.io/component: workspace-secret
  annotations:
    org.eclipse.che/target-container: maven  
    org.eclipse.che/mount-as: env
    org.eclipse.che/env-name: FOO_ENV
data:
  mykey: myvalue
```

will result in`FOO_ENV=myvalue` set in container.

2) Multiple ENV mount:
```
---
apiVersion: v1
kind: Secret
metadata:
  name: mvn-settings-env
  labels:
    app.kubernetes.io/part-of: org.eclipse.che   
    app.kubernetes.io/component: workspace-secret
  annotations:
    org.eclipse.che/target-container: maven  
    org.eclipse.che/mount-as: env
    org.eclipse.che/mykey_env-name: MYKEY_ENV
    org.eclipse.che/somekey_env-name: SOMEKEY_ENV
data:
  mykey: myvalue
  somekey: somevalue
```

will result in`MYKEY_ENV=myvalue` and `SOMEKEY_ENV=somevalue` set in container.
