### ISSUE TITLE
Make configurable images in both plugin and devfile registry

### ISSUE THREAD

**Issue by l0rd** [eclipse-che/che#14693]
### Is your enhancement related to a problem? Please describe.

In Air Gap mode a user needs to start a workspace using images from an internal/private container registry (not `docker.io`, not `quay.io`). 

Che server and other components images can be configured using che.properties (and config maps). 

But editors and plugins sidecars images are not currently configurable: they are hardcoded with the plugin registry. The same is true to the stack images in the devfile registry.

### Describe the solution you'd like

A user should be able to configure the plugin sidecars and the sample stack images URL and the repository. 

### Additional context

A possible solution would be to use a configmap and a bash script used as entrypoint that replaces the images.

The configmap would look like:

```yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: che-containers-registry
data:
  CHE_SIDECAR_CONTAINERS_REGISTRY_URL: "https://enterprise.container.registry:3000/"
  CHE_SIDECAR_CONTAINERS_REGISTRY_REPOSITORY: "che_sidecars"
```

Used in the deployment yaml as

```yaml
...
   containers:
   - image: {{ .Values.chePluginRegistryImage }}
      imagePullPolicy: {{ .Values.chePluginRegistryImagePullPolicy }}
      envFrom:
      - configMapRef:
          name: che-containers-registry
```

And the containers entrypoint should call a script that replaces the images url and repo in the index.json and the plugins meta.yaml.
