### ISSUE TITLE
Operator airgap mode support

### ISSUE THREAD

**Issue by l0rd** [eclipse-che/che#14734]
### Is your enhancement related to a problem?

A user that wants to install Che behind an enterprise firewall should be able to do so configuring the Checluster CR.

### Describe the solution you'd like

Add the following CR attributes that a user can configure during installation of Che:

```yaml
# airGapMode: 'true' ==> we won't need that (see comments below)
airGapContainerRegistryHostname: 'https://mycompany-registry/'
airGapContainerRegistryOrganisation: 'crw'
```

The default should be `airGapMode: 'false'`. When it's `true` the operator should use the specified hostname and repository to replace the images of the Che components, [the plugins sidecars and the devfile registry stacks](https://github.com/eclipse/che/issues/14693).
