### ISSUE TITLE
Projects with "type": "zip" are extracted to a subpath, breaking devfiles

### ISSUE THREAD

**Issue by amisevsk** [eclipse-che/che#14800]
### Describe the bug
Since https://github.com/eclipse/che/issues/14206 is resolved, Theia can handle projects downloaded as zips. However, typically zips (e.g. from github) unzip to a folder including the branch name, which causes the project to be unzipped to a subpath -- e.g.
```
/projects/console-java-simple/console-java-simple-master
```
instead of 
```
/projects/console-java-simple/
```

This breaks many devfile commands that depend on the project being in a known location.

### Che version
 - [x] nightly

### Steps to reproduce
Start a workspace using the devfile
```yaml
metadata:
  name: zip-project
projects:
  - name: console-java-simple
    source:
      location: 'https://github.com/che-samples/console-java-simple/archive/master.zip'
      type: zip
components:
  - id: redhat/java11/latest
    type: chePlugin
  - mountSources: true
    memoryLimit: 512Mi
    type: dockerimage
    volumes:
      - name: m2
        containerPath: /home/user/.m2
    image: 'quay.io/eclipse/che-java11-maven:nightly'
    alias: maven
    env:
      - value: /home/user/.m2
        name: MAVEN_CONFIG
      - value: >-
          -XX:MaxRAMPercentage=50 -XX:+UseParallelGC -XX:MinHeapFreeRatio=10
          -XX:MaxHeapFreeRatio=20 -XX:GCTimeRatio=4
          -XX:AdaptiveSizePolicyWeight=90 -Dsun.zip.disableMemoryMapping=true
          -Xms20m -Djava.security.egd=file:/dev/./urandom -Duser.home=/home/user
        name: MAVEN_OPTS
      - value: >-
          -XX:MaxRAMPercentage=50 -XX:+UseParallelGC -XX:MinHeapFreeRatio=10
          -XX:MaxHeapFreeRatio=20 -XX:GCTimeRatio=4
          -XX:AdaptiveSizePolicyWeight=90 -Dsun.zip.disableMemoryMapping=true
          -Xms20m -Djava.security.egd=file:/dev/./urandom
        name: JAVA_OPTS
      - value: >-
          -XX:MaxRAMPercentage=50 -XX:+UseParallelGC -XX:MinHeapFreeRatio=10
          -XX:MaxHeapFreeRatio=20 -XX:GCTimeRatio=4
          -XX:AdaptiveSizePolicyWeight=90 -Dsun.zip.disableMemoryMapping=true
          -Xms20m -Djava.security.egd=file:/dev/./urandom
        name: JAVA_TOOL_OPTIONS
apiVersion: 1.0.0
commands:
  - name: maven build
    actions:
      - workdir: '${CHE_PROJECTS_ROOT}/console-java-simple'
        type: exec
        command: mvn clean install
        component: maven
  - name: maven build and run
    actions:
      - workdir: '${CHE_PROJECTS_ROOT}/console-java-simple'
        type: exec
        command: mvn clean install && java -jar ./target/*.jar
        component: maven
```

### Expected behavior
Project is unzipped to the correct folder.

### Runtime
   - [x] OpenShift 3.11

### Screenshots
![Screenshot from 2019-10-07 15-59-54](https://user-images.githubusercontent.com/16168279/66344329-8f5aeb80-e91b-11e9-9e7e-e26e1be0accd.png)

### Additional Context
Impacts https://github.com/eclipse/che/issues/14733
