### ISSUE TITLE
Theia - variable in previewurl is not evaluated after clicking right-bottom notification popup

### ISSUE THREAD

**Issue by sparkoo** [eclipse-che/che#14820]
### Describe the bug
Having defined `previewUrl` in command. After running the command, right-bottom notification will pop-up. The URL that is shown in notification is properly evaluated. But clicking on "Preview" button opens un-evaluated URL.

The support for `previewUrl` in devfile is not merged yet. However, issue can be manually reproduced by editing `tasks.json` file. Follow steps to reproduce.

Simple devfile to test:
```
---
apiVersion: 1.0.0
metadata:
  generateName: dummy-go-server-with-one0endpoint
projects:
  -
    name: dummy-http-server
    source:
      type: git
      location: "https://github.com/sparkoo/dummy-http-server.git"
components:
  -
    type: dockerimage
    image: quay.io/eclipse/che-golang-1.10:nightly
    alias: go-cli
    mountSources: true
    memoryLimit: 256Mi
commands:
  -
    name: run 8080
    actions:
      -
        type: exec
        component: go-cli
        command: "go run main.go 8080 /hello"
        workdir: ${CHE_PROJECTS_ROOT}/dummy-http-server

```

### Che version
 - [x] nigihtly

### Steps to reproduce

1. start workspace with devfile above
1. open `.theia/tasks.json` file
1. add parameter to task `"previewUrl": "${server.theia}"`
1. save `.theia/tasks.json` and run the command
1. right-bottom notification with previewUrl should appear. URL to theia component is correct there
1. click on "Preview" button in the right-bottom notification
1. opened URL is `http://${server.theia}`, but it should be properly evaluated.

### Expected behavior
URL should be evaluated

### Runtime
   - [x] minikube (include output of `minikube version` and `kubectl version`)

### Screenshots
![previewurl_notif](https://user-images.githubusercontent.com/1160903/66461392-3d2fdc80-ea79-11e9-8d90-498f8d5f4fc6.png)
![previewurl_notif2](https://user-images.githubusercontent.com/1160903/66461398-3ef9a000-ea79-11e9-8429-6bef77b93e5a.png)

### Installation method
   - [x] helm

### Environment
   - [x] my computer 
       - [x] Linux

### Additional context
"Preview" button from bottom Previews panel works ok.

`previewUrl` support in devfile is currently in review.
