### ISSUE TITLE
Installing Java Test Runner Support for Java

### ISSUE THREAD

**Issue by thisHermit** [eclipse-che/che#14871]
## Issue
There seems to be no support for running Tests in Java on Che 7.

Adding the [Java Test Runner](https://marketplace.visualstudio.com/items?itemName=vscjava.vscode-java-test) extension would be a good solution to this problem as it would add support for both class level and function level tests.

## Steps tried
* Tried installing the plugin by copying the Code Quick Open from [here](https://marketplace.visualstudio.com/items?itemName=vscjava.vscode-java-test) as suggested over [here](https://www.eclipse.org/che/docs/che-7/using-a-visual-studio-code-extension-in-che/#proc_importing-a-visual-studio-code-extension-in-the-che-theia-editor-adoc_using-a-visual-studio-code-extension-in-che)
  * The installation failed as the extension was dependent on [redhat's language support](https://marketplace.visualstudio.com/items?itemName=redhat.java).
* Tried installing the plugin by publishing it as mentioned over [here](https://www.eclipse.org/che/docs/che-7/using-a-visual-studio-code-extension-in-che/#publishing-a-vs-code-extension-into-the-che-plug-in-registry_using-a-visual-studio-code-extension-in-che) by publishing it.
  * The publishing instructions were not very clear. On stumbling about, found [this page](https://www.eclipse.org/che/docs/che-7/customizing-the-devfile-and-plug-in-registries/) about customising the registries
* Tried editing the plugin registry at runtime as mentioned [here](https://www.eclipse.org/che/docs/che-7/editing-a-devfile-and-plug-in-at-runtime/).
  * The commands did not mention changing the namespace.
  * `kubectl exec $\{PLUGIN_REG_POD} -i -t -- 
  /var/www/html/index_v2.sh v3 > /var/www/html/v3/plugins/index.json` did not work. It kept confusing the files by trying to find the file on my local machine.

Help regarding any of the above solutions is much appreciated.

Here are the issues that are keeping this extension from working properly in Che:
[x] Support VS Code Standard Icons in Contributions https://github.com/eclipse-theia/theia/issues/7634
[x] Support `Command` Type for StatusBarItem.command https://github.com/eclipse-theia/theia/issues/8241
[x] Cannot resolve `/hostedPlugin/` Resources from Sidecar Containers #17517

**Comment by ibuziuk** [comment]
@tsmaeder do you happen to know about any ongoing work related to java test runner support ?

**Comment by tsmaeder** [comment]
> any ongoing work related to java test runner support ?

No, there is nothing planned.

**Comment by ibuziuk** [comment]
@tsmaeder moving to P2 and letting you prioritize accordingly ;-)

**Comment by thisHermit** [comment]
Running `kubectl logs <registry-pod-name> -n che` gave the following outuput.
>Checking meta /var/www/html/v3/plugins/ms-vscode/node-debug/latest/meta.yaml
    Updating image registry to https://github.com/microsoft/vscode-java-test
    Updating image organization to microsoft
    Updating image tag to vscode-java-test}

It seems to be repeated 103 times as indicated by this command
`kubectl logs <registry-pod-name> -n che | grep https://github.com/microsoft/vscode-java-test | wc -l`

which is very close to 101 times as returned by this command
`tree ./v3/plugins/ | grep meta.yaml | wc -l`
run inside the plugin-registry [repo](https://github.com/eclipse/che-plugin-registry)


My meta.yaml file for the java-test-runner (v2 used as mentioned in #14853's [comment](https://github.com/eclipse/che/issues/14853#issuecomment-541018476)):
> apiVersion: v2
publisher: microsoft
name: vscode-java-test
version: latest
type: VS Code extension
displayName: Tester
title: Java Test Runner
description: Run and Debug Java Unit Tests
category: Debugger
icon: https://www.eclipse.org/che/images/logo-eclipseche.svg
repository: https://github.com/microsoft/vscode-java-test.git
spec:
  extensions:
    - https://github.com/redhat-developer/vscode-java/releases/download/v0.47.0/redhat.java-0.47.0.vsix
    - https://github.com/microsoft/vscode-java-debug/releases/download/0.22.0/vscode-java-debug-0.22.0.vsix
    - https://github.com/microsoft/vscode-java-test/releases/download/0.20.0/vscode-java-test-0.20.0.vsix

**Comment by thisHermit** [comment]
As you have moved this to a P2 priority, would you mind if I take this up?

If yes, can you please suggest me the steps I should take?

**Comment by tolusha** [comment]
@thisHermit 
I suggest to add test extension into https://github.com/eclipse/che-plugin-registry/blob/master/v3/plugins/redhat/java/latest/meta.yaml, test if everything works fine and submit a PR

**Comment by tolusha** [comment]
In your case the meta yaml will be the following
```
apiVersion: v2
publisher: redhat
name: java
version: latest
type: VS Code extension
displayName: Language Support for Java(TM)
title: Language Support for Java(TM) by Red Hat
description: Java Linting, Intellisense, formatting, refactoring, Maven/Gradle support
  and more...
icon: https://www.eclipse.org/che/images/logo-eclipseche.svg
repository: https://github.com/redhat-developer/vscode-java
category: Language
firstPublicationDate: "2019-10-03"
spec:
  containers:
  - image: "docker.io/eclipse/che-remote-plugin-runner-java8:next"
    name: vscode-java
    memoryLimit: "1500Mi"
    volumes:
    - mountPath: "/home/theia/.m2"
      name: m2
  extensions:
  - https://github.com/microsoft/vscode-java-debug/releases/download/0.20.0/vscode-java-debug-0.20.0.vsix
  - https://download.jboss.org/jbosstools/static/jdt.ls/stable/java-0.50.0-1825.vsix
  - https://github.com/microsoft/vscode-java-test/releases/download/0.20.0/vscode-java-test-0.20.0.vsix
```
