### ISSUE TITLE
Devfile Commands changes are not propagated to IDE at following start

### ISSUE THREAD

**Issue by sparkoo** [eclipse-che/che#14876]
### Describe the bug
Changes in devfile commands are not propagated to IDE in following start up. Theia creates `tasks.json` at first startup of the workspace and after doing some changes in the devfile, this file is not updated with latest changes. From the server response, it is clear that server sends updated command.

Updating command name will add second command to the `tasks.json`, instead of replacing first one. `Run task` dialogue then offers both commands to run (before and after manual devfile update).

simple devfile to test:

```
---
apiVersion: 1.0.0
metadata:
  generateName: dummy-go-
projects:
  -
    name: dummy-http-server
    source:
      type: git
      location: "https://github.com/sparkoo/dummy-http-server.git"
components:
  -
    type: dockerimage
    image: quay.io/eclipse/che-golang-1.12:nightly
    alias: go-cli
    mountSources: true
    memoryLimit: 256Mi
commands:
  -
    name: run
    actions:
      -
        type: exec
        component: go-cli
        command: "go run main.go 8080"
        workdir: ${CHE_PROJECTS_ROOT}/dummy-http-server

```

### Che version
 - [x] latest

### Steps to reproduce
1. Create workspace with this devfile
1. Start the workspace
1. Stop the workspace
1. Go to the workspace devfile config and change command's action to `command: go version`
1. Save the devfile
1. Start workspace again
1. Run the command, it will still run old command starting the server, instead of just `go version`
1. Open `.theia/tasks.json` and see it still have `"command": "go run main.go 8080",` 
1. By checking network communication in the browser or by curl `/api/workspace/<workspaceid>` you can verify that server sends updated command

### Expected behavior
Theia should recognize changes and update `tasks.json` as needed.

### Runtime
   - [x] minikube (include output of `minikube version` and `kubectl version`)

### Installation method
   - [x] chectl 

### Environment
   - [x] my computer 
       - [x] Linux

### Additional context
I've created similar issue for previewUrl https://github.com/eclipse/che/issues/14803, but this one is general one
