### ISSUE TITLE
Support preferences for cheEditors

### ISSUE THREAD

**Issue by l0rd** [eclipse-che/che#14872]
### Is your enhancement related to a problem? 

Setting Theia properties is currently not working. For example:

```
components:
  - id: eclipse/che-theia/next
    type: cheEditor
    preferences:
       editor.fontSize: 14
       terminal.integrated.fontSize: 14
```

### Describe the solution you'd like

Support `preferences` for editors as well
