### ISSUE TITLE
Ability of running Che on subpath/subdir domain,e.g. http://a.firm.com/che

### ISSUE THREAD

**Issue by dmpe** [eclipse-che/che#14885]
It would be nice if there is a way in the official HELM chart to use Eclipse Che on subpath/subdir domain (`devops.company.com/che`), instead of on its own subdomain (e.g. `che.company.com`)

The reason would be restrictions in my company on how subdomains get created, etc. 
Indeed, I have just one subdomain and >5 web services running all on `devops.company.com`

Essentially: `devops.company.com/<different services, eg. gitlab, nexus, etc. - would love to have eclipse Che too>`

Running latest 1.16 minikube, self-hosted.

**Comment by dmpe** [comment]
At most where I could get is following setup:

`test_values.yaml`:

```
global:
  ingressDomain: devops.company.com/eclipse

ingress:
  enabled: true
  # Used to create an Ingress record.
  hosts:
    - path: /eclipse
  annotations:
    kubernetes.io/ingress.class: traefik
```
ingress
```
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: che-ingress
  labels:
  app: eclipse
  chart: {{ .Chart.Name }}
  release: {{ .Release.Name }}
  heritage: {{ .Release.Service }}
{{- if .Values.ingress.labels }}
{{ .Values.ingress.labels | toYaml | trimSuffix "\n"| indent 4 -}}
{{- end}}
{{- if .Values.ingress.annotations}}
  annotations:
    {{- range $key, $value := .Values.ingress.annotations }}
    {{ $key }}: {{ $value | quote }}
    {{- end }}
{{- end }}
spec:
  rules:
{{- $path := default "/" .path }}
{{- if ne .Values.global.serverStrategy "default-host" }}
  - host: {{ template "cheHost" . }}
    http:
{{- else }}
  - http:
{{- end }}
      paths:
      - path: {{ $path }}
        backend:
          serviceName: che-host
          servicePort: 8080

```
and in config map, uncommented lines dealing with `CHE_INFRA_KUBERNETES_INGRESS_ANNOTATIONS__JSON:`
