### ISSUE TITLE
How to set docker registry through a swagger API call

### ISSUE THREAD

**Issue by ssh24** [eclipse-che/che#14897]
## Summary
I was wondering if there is an API to set the registry (that is on the Administration panel) through a swagger call?

/cc @maysunfaisal

**Comment by skabashnyuk** [comment]
The plugin and devfile registry can be set only with the environment variables of the  Che server. Or you can specify direct url in devfile 
```
  components:
   - alias: exec-plugin
     type: chePlugin
     reference: https://raw.githubusercontent.com.../plugin/1.0.1/meta.yaml
```
