### ISSUE TITLE
Can't create workspace from devfile.yaml stored in git repo

### ISSUE THREAD

**Issue by anthonma** [eclipse-che/che#14914]
### Describe the bug

I'm trying to create a workspace from a devfile.yaml, which is stored in a github repo.
When I try it by using that link: http://my-che-host/f?url=https://github.com/my-github-username/my-repo, I get the following error:
````
Unable to validate Devfile. Error: mapping values are not allowed here
````

This is my devfile.yaml:
````
apiVersion: 1.0.0
metadata:
    name: exampleName
projects:
  - name:exampleProject
    source:
      type: git
      location: 'https://github.com/anthonma/cheTestRepo.git'
components:
 - alias: cpp
    type: chePlugin
      id: che-incubator/cpptools/latest
````
### Che version

 - [ ] latest
 - [ ] nightly
 - [x] other: 7.3.0

### Expected behavior

A workspace is created
### Runtime
   - [x] kubernetes (include output of `kubectl version`) 
````
Client Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.4", GitCommit:"67d2fcf276fcd9cf743ad4be9a9ef5828adc082f", GitTreeState:"clean", BuildDate:"2019-09-18T14:51:13Z", GoVersion:"go1.12.9", Compiler:"gc", Platform:"windows/amd64"}
Server Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.0", GitCommit:"2bd9643cee5b3b3a5ecbd3af49d09018f0773c77", GitTreeState:"clean", BuildDate:"2019-09-18T14:27:17Z", GoVersion:"go1.12.9", Compiler:"gc", Platform:"linux/amd64"}
````
   - [ ] Openshift (include output of `oc version`)
   - [ ] minikube (include output of `minikube version` and `kubectl version`)
   - [ ] minishift (include output of `minishift version` and `oc version`)
   - [ ] docker-desktop + K8S (include output of `docker version` and `kubectl version`)
   - [ ] other: (please specify)

### Installation method
   - [x] chectl 
   - [ ] che-operator 
   - [ ] minishift-addon
   - [ ] I don't know

### Environment
   - [x] my computer 
       - [x] Windows
       - [ ] Linux
       - [ ] macOS
   - [ ] Cloud
       - [ ] Amazon
       - [ ] Azure
       - [ ] GCE
       - [ ] other (please specify) 
   - [ ] other: please specify
