### ISSUE TITLE
che in kubernetes for the docker image eclipse/che-server-6.19.0  (websocket error)

### ISSUE THREAD

**Issue by sushmithakumar** [eclipse-che/che#14930]
### Che version

 - [ ] latest
 - [ ] nightly
 - [x] other: please specify

### Runtime
   - [ ] kubernetes (include output of `kubectl version`) 
   - [ ] Openshift (include output of `oc version`)
   - [ ] minikube (include output of `minikube version` and `kubectl version`)
   - [ ] minishift (include output of `minishift version` and `oc version`)
   - [ ] docker-desktop + K8S (include output of `docker version` and `kubectl version`)
   - [ ] other: (please specify)

### Installation method
   - [ ] chectl 
   - [ ] che-operator 
   - [ ] minishift-addon
   - [ ] I don't know

### Environment
   - [ ] my computer 
       - [ ] Windows
       - [ ] Linux
       - [ ] macOS
   - [ ] Cloud
       - [ ] Amazon
       - [ ] Azure
       - [ ] GCE
       - [ ] other (please specify) 
   - [ ] other: please specify

**Comment by sushmithakumar** [comment]
019/10/20 15:12:09 Start new terminal.
2019/10/20 15:15:09 Failed to send websocket message: , due to occurred error write tcp 100.96.137.160:4411->100.96.137.170:37656: write: broken pipe
2019/10/20 15:15:09 Error occurs on sending ping message to websocket. write tcp 100.96.137.160:4411->100.96.137.170:37656: write: broken pipe

**Comment by sushmithakumar** [comment]
CHE_API: http://###INGRESS_LB_URL###/api
  CHE_DEBUG_SERVER: "true"
  CHE_HOST: ###INGRESS_LB_URL###
  CHE_INFRA_KUBERNETES_BOOTSTRAPPER_BINARY__URL: http://###INGRESS_LB_URL###/agent-binaries/linux_amd64/bootstrapper/bootstrapper
  CHE_INFRA_KUBERNETES_INGRESS_ANNOTATIONS__JSON: '{"nginx.ingress.kubernetes.io/rewrite-target":
    "/","nginx.ingress.kubernetes.io/ssl-redirect": "false","nginx.ingress.kubernetes.io/proxy-connect-timeout":
    "3600","nginx.ingress.kubernetes.io/proxy-read-timeout": "3600"}'
  CHE_INFRA_KUBERNETES_INGRESS_DOMAIN: ###INGRESS_LB_URL###
  CHE_INFRA_KUBERNETES_MACHINE__START__TIMEOUT__MIN: "5"
  CHE_INFRA_KUBERNETES_MASTER__URL: https://api.CLIENTID.devops
  CHE_INFRA_KUBERNETES_NAMESPACE: namespace
  CHE_INFRA_KUBERNETES_POD_SECURITY__CONTEXT_FS__GROUP: "0"
  CHE_INFRA_KUBERNETES_POD_SECURITY__CONTEXT_RUN__AS__USER: "0"
  CHE_INFRA_KUBERNETES_PVC_PRECREATE__SUBPATHS: "false"
  CHE_INFRA_KUBERNETES_PVC_STRATEGY: unique
  CHE_INFRA_KUBERNETES_SERVER__STRATEGY: single-host
  CHE_INFRA_KUBERNETES_TRUST__CERTS: "false"
  CHE_INFRASTRUCTURE_ACTIVE: kubernetes
  CHE_JDBC_DATABASE: dbche
  CHE_JDBC_DRIVER__CLASS__NAME: org.postgresql.Driver
  CHE_JDBC_MAX__IDLE: "10"
  CHE_JDBC_MAX__TOTAL: "20"
  CHE_JDBC_MAX__WAIT__MILLIS: "-1"
  CHE_JDBC_PASSWORD: pgchepassword
  CHE_JDBC_URL: jdbc:postgresql://postgres-che:5432/dbche
  CHE_JDBC_USERNAME: pgche
  CHE_KEYCLOAK_AUTH__SERVER__URL: http://###INGRESS_LB_URL###/auth
  CHE_KEYCLOAK_CLIENT__ID: che-public
  CHE_KEYCLOAK_LOGOUT_ENDPOINT: http://###INGRESS_LB_URL###/auth/realms/che/protocol/openid-connect/logout
  CHE_KEYCLOAK_PASSWORD_ENDPOINT: http://###INGRESS_LB_URL###auth/realms/che/account/password
  CHE_KEYCLOAK_PROFILE_ENDPOINT: http://###INGRESS_LB_URL###/auth/realms/che/account
  CHE_KEYCLOAK_REALM: che
  CHE_KEYCLOAK_TOKEN_ENDPOINT: http://###INGRESS_LB_URL###/auth/realms/che/protocol/openid-connect/token
  CHE_LIMITS_WORKSPACE_IDLE_TIMEOUT: "0"
  CHE_LOCAL_CONF_DIR: /etc/conf
  CHE_LOG_LEVEL: INFO
  CHE_LOGS_APPENDERS_IMPL: plaintext
  CHE_LOGS_DIR: /data/logs
  CHE_MULTIUSER: "true"
  CHE_OAUTH_GITHUB_CLIENTID: ""
  CHE_OAUTH_GITHUB_CLIENTSECRET: ""
  CHE_PORT: "8080"
  CHE_PREDEFINED_STACKS_RELOAD__ON__START: "false"
  CHE_WEBSOCKET_ENDPOINT: ws:// ###INGRESS_LB_URL###/api/websocket
  CHE_WORKSPACE_AGENT_DEV_INACTIVE__STOP__TIMEOUT__MS: "0"
  CHE_INFRA_KUBERNETES_WORKSPACE__UNRECOVERABLE__EVENTS: FailedMount,FailedScheduling,MountVolume.SetUp failed,Failed to pull image,FailedCreate
  CHE_INFRA_KUBERNETES_PVC_QUANTITY: "20Gi"
  CHE_INFRA_KUBERENETES_INSTALLER__SERVER__MIN__PORT: "10000"
  CHE_INFRA_KUBERENTES_INSTALLER__SERVER__MAX__PORT: "20000"
  CHE_INFRA__KUBERNETES_CLIENT_HTTP_ASYNC__REQUESTS_MAX: "1000"
  CHE_INFRA_KUBERNETES_CLIENT_HTTP_ASYNC__REQUESTS_MAX__PER__HOST: "1000"
  CHE_INFRA_KUBERNETES_CLIENT_HTTP_CONNECTION__POOL_MAX__IDLE: "10"
  CHE_INFRA_KUBERNETES_CLIENT_HTTP_CONNECTION__POOL_KEEP__ALIVE__MIN: "10"
  CHE_WORKSPACE_AUTO_START: "false"
  CHE_WORKSPACE_FEATURE_API: http://marketplace:80
  JAVA_OPTS: '-XX:MaxRAMFraction=2 -XX:+UseParallelGC -XX:MinHeapFreeRatio=10 -XX:MaxHeapFreeRatio=20
    -XX:GCTimeRatio=4 -XX:AdaptiveSizePolicyWeight=90 -XX:+UnlockExperimentalVMOptions
    -XX:+UseCGroupMemoryLimitForHeap -Dsun.zip.disableMemoryMapping=true -Xms20m '
This is hosted on kubernetes cluster ec2 instance with the above config

**Comment by sushmithakumar** [comment]
any help would be appreciated
thanks

**Comment by sushmithakumar** [comment]
CHE_INFRA_DOCKER_MASTER__WEBSOCKET__ENDPOINT: ws://a60137324f3b711e9a65102cddcee26d-1529089738.sa-east-1.elb.amazonaws.com/${CHE_PORT}/api/websocket
  CHE_INFRA_DOCKER_MASTER__WEBSOCKET__MINOR__ENDPOINT: ws://a60137324f3b711e9a65102cddcee26d-1529089738.sa-east-1.elb.amazonaws.com/${CHE_PORT}/api/websocket-minor
  CHE_WORKSPACE_AGENT_DEV_INACTIVE__STOP__TIMEOUT__MS: "0"
  CHE_INFRA_KUBERNETES_WORKSPACE__UNRECOVERABLE__EVENTS: FailedMount,FailedScheduling,MountVolume.SetUp failed,Failed to pull image,FailedCreate
  CHE_INFRA_KUBERNETES_PVC_QUANTITY: "20Gi"
  CHE_INFRA_KUBERENETES_INSTALLER__SERVER__MIN__PORT: "10000"
  CHE_INFRA_KUBERENTES_INSTALLER__SERVER__MAX__PORT: "20000"
  CHE_INFRA__KUBERNETES_CLIENT_HTTP_ASYNC__REQUESTS_MAX: "1000"
  CHE_INFRA_KUBERNETES_CLIENT_HTTP_ASYNC__REQUESTS_MAX__PER__HOST: "1000"
  CHE_INFRA_KUBERNETES_CLIENT_HTTP_CONNECTION__POOL_MAX__IDLE: "10"
  CHE_INFRA_KUBERNETES_CLIENT_HTTP_CONNECTION__POOL_KEEP__ALIVE__MIN: "10"
  CHE_WORKSPACE_PLUGIN__BROKER_INIT_IMAGE: eclipe/che-init-plugin-broker:v0.22
  CHE_WORKSPACE_PLUGIN__BROKER_UNIFIED_IMAGE: eclipse/che-unified-plugin-broker:v0.22
  CHE_WORKSPACE_PLUGIN__BROKER_PULL__POLICY: Always
  CHE_WORKSPACE_PLUGIN__BROKER_WAIT__TIMEOUT__MIN: "7"
  CHE_CORE_JSONRPC_PROCESSOR__CORE__POOL__SIZE: "5"
  CHE_CORE_JSONRPC_PROCESSOR_MAX__POOL__SIZE: "50"
  CHE_CORE_JSONRPC_PROCESSOR__QUEUE__CAPACITY: "100000"
  CHE_CORE_JSONRPC_MINOR__PROCESSOR__MAX__POOL__SIZE: "100"
  CHE_CORE_JSONRPC_MINOR__PROCESSOR__CORE__POOL__SIZE: "15"
  CHE_CORE_JSONRPC_MINOR__PROCESSOR__QUEUE__CAPACITY: "10000"
  CHE_WORKSPACE_SERVER_PING__INTERVAL__MILLISECONDS: "3000"
  CHE_WORKSPACE_SERVER_PING__SUCCESS__THRESHOLD: "1"
  CHE_WORKSPACE_SREVER_PING__INTERVAL__MILLISECONDS: "3000"
  CHE_WORKSPACE_LOGS_ROOT__DIR: /workspace_logs
  CHE_WORKSPACE_POOL_TYPE: fixed
  CHE_WORKSPACE_POOL_EXACT__SIZE: "30"
  CHE_WORKSPACE_PROBE__POOL__SIZE: "10"
  CHE_WORKSPACE_HTTP__PROXY__JAVA__OPTIONS: ""
  CHE_WORKPACE_JAVA__OPTIONS: -XX:MaxRAM=150m -XX:MaxRAMFraction=2 -XX:+UseParallelGC -XX:MinHeapFreeRatio=10 -XX:MaxHeapFreeRatio=20 -XX:GCTimeRatio=4 -XX:AdaptiveSizePolicyWeight=90 -Dsun.zip.disableMemoryMapping=true -Xms20m -Djava.security.egd=file:/dev/./urandom
  CHE_WORKSPACE_MAVEN__OPTIONS: -XX:MaxRAM=150m -XX:MaxRAMFraction=2 -XX:+UseParallelGC -XX:MinHeapFreeRatio=10 -XX:MaxHeapFreeRatio=20 -XX:GCTimeRatio=4 -XX:AdaptiveSizePolicyWeight=90 -Dsun.zip.disableMemoryMapping=true -Xms20m -Djava.security.egd=file:/dev/./urandom
  CHE_WORKSPACE_WSAGENT__JAVA__OPTIONS: -XX:MaxRAM=600m -XX:MaxRAMFraction=1 -XX:+UseParallelGC -XX:MinHeapFreeRatio=10 -XX:MaxHeapFreeRatio=20 -XX:GCTimeRatio=4 -XX:AdaptiveSizePolicyWeight=90 -Dsun.zip.disableMemoryMapping=true -Xms50m -Dfile.encoding=UTF8 -Djava.security.egd=file:/dev/./urandom
  CHE_WORKSPACE_MAVEN__SERVER__JAVA__OPTIONS: -XX:MaxRAM=128m -XX:MaxRAMFraction=1 -XX:+UseParallelGC -XX:MinHeapFree
  JAVA_OPTS: '-XX:MaxRAMFraction=2 -XX:+UseParallelGC -XX:MinHeapFreeRatio=10 -XX:MaxHeapFreeRatio=20
    -XX:GCTimeRatio=4 -XX:AdaptiveSizePolicyWeight=90 -XX:+UnlockExperimentalVMOptions
    -XX:+UseCGroupMemoryLimitForHeap -Dsun.zip.disableMemoryMapping=true -Xms20m '
Have added further properties in configmap yaml

**Comment by ibuziuk** [comment]
@sushmithakumar would you mind adding a full description of the issues based on the template? There is no information other than some logs

**Comment by sushmithakumar** [comment]
I 'm trying to bring up eclipse-che in kubernetes. with default-backend pod,ingress ,postgres ,keycloak and che pod.

**Comment by sushmithakumar** [comment]
these are my yaml files with which I have tried bringing up eclipse-che altogether.

**Comment by sushmithakumar** [comment]
che-deployment.yaml 
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: che
  name: che
spec:
  replicas: 1
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      app: che
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        pod.alpha.kubernetes.io/init-containers: '[{"image":"busybox","imagePullPolicy":"IfNotPresent","name":"fmp-volume-permission","command":["chmod","777","/data"],"volumeMounts":[{"mountPath":"/data","name":"che-data-volume"}]}]'
      labels:
        app: che
    spec:
      containers:
        - name: che
          envFrom:
          - configMapRef:
              name: che
          image: eclipse/che-server:6.19.0
          imagePullPolicy: Always
          livenessProbe:
            httpGet:
              path: /api/system/state
              port: 8080
              scheme: HTTP
            initialDelaySeconds: 120
            timeoutSeconds: 10
          ports:
          - containerPort: 8080
            name: http
          - containerPort: 8000
            name: http-debug
          - containerPort: 8888
            name: jgroups-ping
          readinessProbe:
            httpGet:
              path: /api/system/state
              port: 8080
              scheme: HTTP
            initialDelaySeconds: 15
            timeoutSeconds: 60
          resources:
            limits:
              memory: 600Mi
            requests:
              memory: 256Mi
          volumeMounts:
          - mountPath: /data
            name: che-data-volume
      serviceAccountName: che
      volumes:
      - name: che-data-volume
        persistentVolumeClaim:
          claimName: che-data-volume

**Comment by sushmithakumar** [comment]
che-ingress.yaml
---------------------
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: che-ingress
  labels:
    app: che-ingress
  annotations:
#    nginx.ingress.kubernetes.io/rewrite-target: /
    nginx.ingress.kubernetes.io/proxy-read-timeout: "3600"
    nginx.ingress.kubernetes.io/proxy-connect-timeout: "3600"
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
#    nginx.ingress.kubernetes.io/ssl-services: "keycloak"
#    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
#    kubernetes.io/tls-acme: "true"
spec:
  rules:
  - host: ###INGRESS_LB_URL###
    http:
      paths:
      - path: /
        backend:
          serviceName: che-host
          servicePort: 8080
      - path: /auth/
        backend:
          serviceName: keycloak
          servicePort: 5050

**Comment by sushmithakumar** [comment]
che-keycloak.yaml 
-----------------------
```
---
apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app: che-keycloak
  name: che-keycloak
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: ethan
  name: che-endpoints-monitor
rules:
- apiGroups: [""]
  resources: ["services", "endpoints", "pods"]
  verbs: ["get", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: RoleBinding
metadata:
  name: ethan-keycloak-role-binding
roleRef:
  kind: Role
  name: che-endpoints-monitor
  apiGroup: rbac.authorization.k8s.io
subjects:
- kind: ServiceAccount
  name: che-keycloak
  namespace: ethan
---
apiVersion: v1
kind: Service
metadata:
  name: "keycloak"
spec:
  ports:
  - name: "5050"
    port: 5050
    targetPort: 8080
  - name: "https"
    port: 5051
    targetPort: 8443
  selector:
    app: keycloak
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: keycloak
  name: keycloak
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: keycloak
    spec:
      containers:
      - env:
        - name: POSTGRES_PORT_5432_TCP_ADDR
          value: postgres-che
        - name: POSTGRES_PORT_5432_TCP_PORT
          value: "5432"
        - name: POSTGRES_DATABASE
          value: keycloak
        - name: POSTGRES_USER
          value: keycloak
        - name: POSTGRES_PASSWORD
          value: keycloak
        - name: KEYCLOAK_USER
          value: admin-che
        - name: KEYCLOAK_PASSWORD
          value: admin-che
        - name: CHE_HOST
          value: ###INGRESS_LB_URL###
        - name: ROUTING_SUFFIX
          value: ###INGRESS_LB_URL###
        - name: NAMESPACE
          value: ethan
        - name: PROTOCOL
          value: http
        - name: PROXY_ADDRESS_FORWARDING
          value: "true"
        image: eclipse/che-keycloak:6.19.0
        command: ["/bin/sh"]
        args: ["-c", "/scripts/kc_realm_user.sh; /opt/jboss/keycloak/bin/kcadm.sh config credentials --server http://localhost:8080/auth --realm master --user admin-che --password admin-che; /opt/jboss/keycloak/bin/kcadm.sh update realms/master -s sslRequired=NONE"]
        imagePullPolicy: Always
        name: keycloak
        ports:
        - containerPort: 8080
        resources:
          limits:
            memory: 1536Mi
          requests:
            memory: 1024Mi
        volumeMounts:
        - mountPath: /opt/jboss/keycloak/standalone/data
          name: keycloak-data
      restartPolicy: Always
      serviceAccountName: che-keycloak
      volumes:
      - name: keycloak-data
        persistentVolumeClaim:
          claimName: keycloak-data
```

**Comment by sushmithakumar** [comment]
che-postgres.yaml
----------------------
```
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: postgres-che
    app: postgres-che
  name: postgres-che
spec:
  replicas: 1
  template:
    metadata:
      labels:
        io.kompose.service: postgres-che
    spec:
      securityContext:
        runAsUser: 26
        fsGroup: 26
      containers:
      - env:
        - name: POSTGRESQL_USER
          value: keycloak
        - name: POSTGRESQL_PASSWORD
          value: keycloak
        - name: POSTGRESQL_DATABASE
          value: keycloak
        - name: "CHE_POSTGRES_USERNAME"
          value: "pgche"
        - name: "CHE_POSTGRES_PASSWORD"
          value: "pgchepassword"
        - name: "CHE_POSTGRES_DATABASE"
          value: "dbche"
        image: eclipse/che-postgres:6.19.0
        securityContext:
          runAsUser: 26
        imagePullPolicy: Always
        name: postgres
        livenessProbe:
          failureThreshold: 3
          initialDelaySeconds: 30
          periodSeconds: 10
          successThreshold: 1
          tcpSocket:
            port: 5432
          timeoutSeconds: 1
        readinessProbe:
          exec:
            command:
            - bash
            - -c
            - psql -h 127.0.0.1 -U ${POSTGRESQL_USER} -q -d $POSTGRESQL_DATABASE -c "SELECT 1"
          failureThreshold: 10
          initialDelaySeconds: 5
          periodSeconds: 3
          successThreshold: 1
          timeoutSeconds: 1
        ports:
        - containerPort: 5432
        resources: {}
        volumeMounts:
        - mountPath: /var/lib/pgsql/data
          name: postgres-data
      restartPolicy: Always
      volumes:
      - name: postgres-data
        persistentVolumeClaim:
          claimName: postgres-che-data
---
apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: postgres-che
  name: postgres-che
spec:
  ports:
  - name: "5432"
    port: 5432
    targetPort: 5432
  selector:
    io.kompose.service: postgres-che
```

**Comment by sushmithakumar** [comment]
che-RBAC.yaml
-----------------
---
apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app: che
  name: che
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: che-clusterrolebinding
subjects:
- kind: ServiceAccount
  name: che
  namespace: ethan
roleRef:
  kind: ClusterRole
  name: cluster-admin
  apiGroup: ""

**Comment by sushmithakumar** [comment]
che-service.yaml
------------------
```
apiVersion: v1
kind: Service
metadata:
  labels:
    app: che
  name: che-host
spec:
  ports:
  - name: http
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: che
  type:
    ClusterIP
```

**Comment by sushmithakumar** [comment]
default-backend-deployment.yaml
------------------------------------------
```
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: default-backend
  labels:
    app: default-backend
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: default-backend
    spec:
      terminationGracePeriodSeconds: 60
      containers:
      - name: default-backend
        image: gcr.io/google_containers/defaultbackend:1.0
        livenessProbe:
          httpGet:
            path: /healthz
            port: 8080
            scheme: HTTP
          initialDelaySeconds: 30
          timeoutSeconds: 5
        ports:
        - containerPort: 8080
        resources:
          limits:
            cpu: 10m
            memory: 20Mi
          requests:
            cpu: 10m
            memory: 20Mi
```

**Comment by sushmithakumar** [comment]
default-backend-service.yaml
---------------------------------
```
apiVersion: v1
kind: Service
metadata:
  name: default-backend
  labels:
    app: default-backend
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 8080
  selector:
    app: default-backend
```

**Comment by sushmithakumar** [comment]
keycloak-ingress.yaml
--------------------------
```
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: che-ingress1
  labels:
    app: che-ingress1
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
    nginx.ingress.kubernetes.io/proxy-read-timeout: "3600"
    nginx.ingress.kubernetes.io/proxy-connect-timeout: "3600"
spec:
  rules:
  - host: 192.168.99.100.nip.io
    http:
      paths:
      - backend:
          serviceName: che-host
          servicePort: 8080
```

**Comment by sushmithakumar** [comment]
nginx-ingress-controller-configmap.yaml
----------------------------------------------
```
apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-ingress-controller-conf
  labels:
    app: nginx-ingress-lb
data:
  enable-vts-status: 'true'
```

**Comment by sushmithakumar** [comment]
ingress-controller-deployment.yaml
------------------------------------------
```
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: nginx-ingress-controller
  labels:
    app: nginx-ingress-controller
spec:
  replicas: 1
  revisionHistoryLimit: 3
  template:
    metadata:
      labels:
        app: nginx-ingress-lb
    spec:
      terminationGracePeriodSeconds: 60
      serviceAccount: nginx
      containers:
        - name: nginx-ingress-controller
          image: quay.io/kubernetes-ingress-controller/nginx-ingress-controller:0.9.0
          imagePullPolicy: Always
          readinessProbe:
            httpGet:
              path: /healthz
              port: 10254
              scheme: HTTP
          livenessProbe:
            httpGet:
              path: /healthz
              port: 10254
              scheme: HTTP
            initialDelaySeconds: 10
            timeoutSeconds: 5
          args:
            - /nginx-ingress-controller
            - --default-backend-service=ethan/default-backend
            - --configmap=\$(POD_NAMESPACE)/nginx-ingress-controller-conf
            - --v=2
            - --default-ssl-certificate=$(POD_NAMESPACE)/nginx-ssl-cert   
          env:
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: POD_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
          ports:
            - containerPort: 80
            - containerPort: 18080
            - containerPort: 443
          volumeMounts:
            - mountPath: /etc/nginx-ssl/dhparam
              name: tls-dhparam-vol
      volumes:
        - name: tls-dhparam-vol
          secret:
            secretName: nginx-ssl-cert
```
----------------------------------------------
ingress-service.yaml
-----------------------
```
apiVersion: v1
kind: Service
metadata:
  name: nginx-ingress
  labels:
    app: nginx-ingress
spec:
  type: LoadBalancer
  ports:
    - port: 80
      nodePort: 30000
      name: http
    - port: 18080
      nodePort: 32000
      name: http-mgmt
  selector:
    app: nginx-ingress-lb
  type:
    LoadBalancer
```
------------------------------------------------
ingress-RBAC.yaml
-------------------
```
apiVersion: v1
kind: ServiceAccount
metadata:
  name: nginx
  labels:
    app: nginx
---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: nginx-role
rules:
- apiGroups:
  - ""
  - "extensions"
  resources:
  - configmaps
  - secrets
  - endpoints
  - ingresses
  - nodes
  - pods
  verbs:
  - list
  - watch
- apiGroups:
  - ""
  resources:
  - services
  verbs:
  - list
  - watch
  - get
  - update
- apiGroups:
  - "extensions"
  resources:
  - ingresses
  verbs:
  - get
- apiGroups:
  - ""
  resources:
  - events
  verbs:
  - create
- apiGroups:
  - "extensions"
  resources:
  - ingresses/status
  verbs:
  - update
- apiGroups:
  - ""
  resources:
  - configmaps
  verbs:
  - get
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: nginx-role
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
- kind: ServiceAccount
  name: nginx
  namespace: name
```
------------------------------
storageclass.yaml
----------------------
```
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  labels:
    app: che
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"storage.k8s.io/v1","kind":"StorageClass","metadata":{"annotations":{"storageclass.beta.kubernetes.io/is-default-class":"true"},"labels":{"k8s-addon":"storage-aws.addons.k8s.io"},"name":"gp2","namespace":""},"parameters":{"type":"gp2"},"provisioner":"kubernetes.io/aws-ebs"}
    storageclass.beta.kubernetes.io/is-default-class: "true"
  creationTimestamp: 2018-06-15T13:11:35Z
  labels:
    k8s-addon: storage-aws.addons.k8s.io
  name: gp2
  resourceVersion: "218"
  selfLink: /apis/storage.k8s.io/v1/storageclasses/gp2
  uid: a177348f-709d-11e8-9ddd-02fb6b9cd9dc
parameters:
  type: gp2
  encrypted: "true"
provisioner: kubernetes.io/aws-ebs
reclaimPolicy: Delete
```
