### ISSUE TITLE
'Open Terminal in specific container' usability

### ISSUE THREAD

**Issue by RomanNikitenko** [eclipse-che/che#14987]
## Summary
`Open Terminal in specific container` action displays empty list of containers for case when user 
has only tool containers.

![containers_list](https://user-images.githubusercontent.com/5676062/67511579-e55fbb00-f69f-11e9-843c-f5e9c9558a76.png)

Please see https://youtu.be/khkxUxTVgH0

Is it expected behavior?
May be for this case list of tool containers should be displayed without empty dropdown list and additional actions from user's side.  
 
## Relevant information

<details>
<summary>Example of Devfile</summary>

```
apiVersion: 1.0.0
metadata:
  name: test-terminals
projects:
  - name: che-theia
    source:
      type: git
      location: 'https://github.com/eclipse/che-theia.git'
components:
  - reference: >-
      https://raw.githubusercontent.com/eclipse/che-plugin-registry/master/v3/plugins/eclipse/che-theia/next/meta.yaml
    type: cheEditor
    alias: theia-editor
commands:
  - name: test task
    actions:
      - workdir: /projects
        type: exec
        command: sleep 30 && echo "hello world"
        component: theia-editor

```
</details>
