### ISSUE TITLE
Plugin installation fails from che-theia workspace

### ISSUE THREAD

**Issue by JonasHelming** [eclipse-che/che#15006]
I have a trial instance of openshift.io and a default workspace (Java maven). When I open the plugin view and click on "install" on any plugin, I get:
"Unable to install plugin 'redhat/php-debugger/latest'. Request addPlugin failed unexpectedly without providing any details."

### Runtime
   - [ ] kubernetes (include output of `kubectl version`) 
   - [x] Openshift (include output of `oc version`)
   - [ ] minikube (include output of `minikube version` and `kubectl version`)
   - [ ] minishift (include output of `minishift version` and `oc version`)
   - [ ] docker-desktop + K8S (include output of `docker version` and `kubectl version`)
   - [ ] other: (please specify)

### Environment
   - [ ] my computer 
       - [ ] Windows
       - [ ] Linux
       - [ ] macOS
   - [ ] Cloud
       - [ ] Amazon
       - [ ] Azure
       - [ ] GCE
       - [x] openshift.io
   - [ ] other: please specify

**Comment by ibuziuk** [comment]
Also fails for me but with a bit different flow on 7.3.1:

![Peek 2019-11-04 20-25](https://user-images.githubusercontent.com/1461122/68151242-9b00f880-ff41-11e9-8f22-30781885ba48.gif)

**Comment by ibuziuk** [comment]
@evidolob any comments on that ^ ?

**Comment by skabashnyuk** [comment]
Reproduced
<img width="1678" alt="Знімок екрана  о 16 32 24" src="https://user-images.githubusercontent.com/1614429/68221565-e66ee180-ffe9-11e9-9886-ecf946215d74.png">

**Comment by evidolob** [comment]
che-theia use DELETE http request with `/api/workspace/{workspaceId}/runtime` URL.
When I do curl request on that URL, I got
```
Error: Failed to run the workspace: "Failure executing: POST at: https://f8osoproxy-test-dsaas-production.09b5.dsaas.openshiftapps.com/api/v1/namespaces/yvydolob-che/configmaps. 
Message: configmaps "workspacegyj2ynixetn1vkm2-gitconfig" already exists. Received status: 
Status(apiVersion=v1, code=409, details=StatusDetails(causes=[], group=null, kind=configmaps, name=workspacegyj2ynixetn1vkm2-gitconfig, retryAfterSeconds=null, uid=null, 
additionalProperties={}), kind=Status, message=configmaps "workspacegyj2ynixetn1vkm2-
gitconfig" already exists, metadata=ListMeta(_continue=null, resourceVersion=null, selfLink=null,
 additionalProperties={}), reason=AlreadyExists, status=Failure, additionalProperties={})."
```
error on ws-loader, 
I think problem in implementation of `/api/workspace/{workspaceId}/runtime` REST service

**Comment by ibuziuk** [comment]
@evidolob you execute delete and get `Failure executing: POST` ?
Also, could you please test locally (I see that you are still testing against Hosted Che)

**Comment by vitaliy-guliy** [comment]
To solve the problem we need:
- [ ] fix an error when updating the devfile of running workspace (Request addPlugin failed unexpectedly)
- [ ] check workpsace status before refreshing the page (should wait until workspace status has been changed)

**Comment by vitaliy-guliy** [comment]
@JonasHelming could you provide more information about your workspace? I need at least your devfile to reproduce the case and check the error when installing a plugin (addPlugin request).

I created a workspace from the following devfile but didn't get any errors.
```
metadata:
  name: che-theia-all
projects:
  - name: che-theia
    source:
      location: 'https://github.com/eclipse/che-theia.git'
      type: git
      branch: master
  - name: theia
    source:
      location: 'https://github.com/theia-ide/theia.git'
      type: git
      branch: master
components:
  - mountSources: true
    endpoints:
      - name: theia-dev-flow
        attributes:
          protocol: http
          public: 'true'
        port: 3010
    memoryLimit: 3000Mi
    type: dockerimage
    alias: che-dev
    image: 'eclipse/che-theia-dev:next'
apiVersion: 1.0.0
commands:
  - name: init ... DEV che-theia
    actions:
      - workdir: /projects/theia
        type: exec
        command: |
          che:theia init
        component: che-dev
```
