### ISSUE TITLE
Locate kubernetes tasks under corresponding containers 

### ISSUE THREAD

**Issue by RomanNikitenko** [eclipse-che/che#15042]
### Is your enhancement related to a problem? Please describe.
Please see the example of devfile:
<details>
<summary>Devfile</summary>

```
apiVersion: 1.0.0
metadata:
 name: k8s-tasks
projects:
  - name: dummy-http-server
    source:
      type: git
      location: "https://github.com/sparkoo/dummy-http-server.git"
components:
  -
    type: kubernetes
    alias: go-k8s
    mountSources: true
    referenceContent: |
          kind: List
          items:
          - kind: Pod
            apiVersion: v1
            metadata:
              name: go-runner
            spec:
              containers:
                - name: go-110-server
                  image: quay.io/eclipse/che-golang-1.10:nightly
                - name: go-112-server
                  image: quay.io/eclipse/che-golang-1.12:nightly
  
commands:
- name: test k8s component
  actions:
      -
        type: exec
        component: go-k8s
        command: "go run main.go 8080 /hello"
        workdir: ${CHE_PROJECTS_ROOT}/dummy-http-server

```
</details>

You can see defined `che` command with `component: go-k8s`, so it's expected that the command will be executed in `go-110-server` or `go-112-server`.
But such commands are displayed in `Workspace` panel for each container.
![k8s_tasks](https://user-images.githubusercontent.com/5676062/67933911-75858f00-fbcf-11e9-9f9a-62913f7f3b10.png)

The cause of the problem is: we get such commands by API without dedicated `machineName` attribute. So we can not match such commands to the corresponding container. 

### Describe the solution you'd like
Recently platform team provided ability to map `component` to `containerName` and we got ability to match such commands to the corresponding container using `componentAlias` attribute. 

![k8s_tasks_attribute](https://user-images.githubusercontent.com/5676062/67934123-e331bb00-fbcf-11e9-8ef8-1090a1a31af7.png)

So now we can improve this behavior.
