### ISSUE TITLE
Devfile icon caching for offline devfile registry

### ISSUE THREAD

**Issue by amisevsk** [eclipse-che/che#15090]
### Is your enhancement related to a problem? Please describe.
The offline devfile registry still refers to icons (stored in devfiles' `meta.yaml`) that aren't available in the offline environment. Instead, for offline builds, the devfile registry should cache icons and use the current offline-mode rewriting functionality to rewrite these URLs to point to the cached images.

E.g. the [meta.yaml](https://github.com/eclipse/che-devfile-registry/blob/master/devfiles/java-maven/meta.yaml) should be rewritten to

```yaml
---
displayName: Java Maven
description: Java Stack with OpenJDK 11 and Maven 3.6.0
tags: ["Java", "OpenJDK", "Maven", "Debian"]
icon: {{ DEVFILE_REGISTRY_URL }}/images/logo-eclipseche.svg
globalMemoryLimit: 2674Mi
```
which would get updated to
```yaml
---
displayName: Java Maven
description: Java Stack with OpenJDK 11 and Maven 3.6.0
tags: ["Java", "OpenJDK", "Maven", "Debian"]
icon: http://devfile-registry-url.com/images/logo-eclipseche.svg
globalMemoryLimit: 2674Mi
```
by the [entrypoint](https://github.com/eclipse/che-devfile-registry/blob/dcdb953a86189aedf65ab364cd853408e078b77c/build/dockerfiles/entrypoint.sh#L71) script.

### Related
https://github.com/eclipse/che/issues/15089
