### ISSUE TITLE
Workspace -> Editors is empty if a cheEditor is specified with a "reference"

### ISSUE THREAD

**Issue by apupier** [eclipse-che/che#15094]
### Describe the bug

when using a reference as component for a cheEditor, the Editors view is failing to load.

### Che version
7.3.1

### Steps to reproduce

1. Create a Workspace with a devfile containing a cheEditor reference. For instance:
```
metadata:
  name: VSCodeWeb
components:
  - type: cheEditor
    reference: >-
      https://raw.githubusercontent.com/eclipse/che-plugin-registry/6a976faca10be9f857d20f4a35349d094879d7d6/v3/plugins/cdr/code-server/2.1523-vsc1.38.1/meta.yaml
apiVersion: 1.0.0
```
2. wait that it is saved
3. go to another page (for instance click on "Workspaces in left menu)
4. Try to "Configure" the workspace
5. The "Editors" tab is empty

### Runtime
- minikube and che.openshift.io

### Screenshots
![Screenshot from 2019-11-05 11-28-52](https://user-images.githubusercontent.com/1105127/68200104-7fd4ce00-ffbf-11e9-9c41-9379ed8db46d.png)

### Installation method
chectl and che.openshift.io

### Environment
   -  my computer: linux
   - che.openshift.io

### Additional context

several errors in browser console log but the important one seems:
```
app-4e44664338.js:113 TypeError: Cannot read property 'split' of undefined
    at e.value (app-4e44664338.js:4736)
    at app-4e44664338.js:4736
    at c (app-4e44664338.js:113)
    at app-4e44664338.js:113
    at p.$digest (app-4e44664338.js:113)
    at p.$apply (app-4e44664338.js:113)
    at a (app-4e44664338.js:112)
    at v (app-4e44664338.js:112)
    at XMLHttpRequest.C.onload (app-4e44664338.js:112) "Possibly unhandled rejection: {}"
```
