### ISSUE TITLE
[Quarkus] Can't debug Quarkus application

### ISSUE THREAD

**Issue by svor** [eclipse-che/che#15114]
While testing vscode-quarkus extension I detected a problem: if execute **Quarkus: Debug Current Quarkus Project** command, I see a message:
`ERROR There is no debug configuration for undefined`  
in the browser console and the debugger doesn't execute, but the configuration was generated in launch.json file:
```json
   {
      "preLaunchTask": "quarkus:dev",
      "type": "java",
      "request": "attach",
      "hostName": "localhost",
      "name": "Debug Quarkus application",
      "port": 5005
   }
```
If try to run this configuration from Debug view, I see a message that `Task 'quarkus:dev' terminated with exit code 127`.

![screenshot-che-che 192 168 99 104 nip io-2019 11 06-11_04_46](https://user-images.githubusercontent.com/1271546/68284001-4bc3e080-0085-11ea-8961-78521ffbb3a7.png)
Probably this problem can be related to add support `integratedTerminal` for debugging https://github.com/eclipse-theia/theia/issues/6103

<details><summary>Che remote plugin with vscode-quarkus extension</summary><p> 

```
apiVersion: v2
publisher: redhat
name: quarkus
version: 1.1.1
type: VS Code extension
displayName: Quarkus Tools
title: Quarkus Tools by Red Hat
description: This plug-in provides support for Quarkus development via a Quarkus language server and a Quarkus jdt.ls extension.
icon: https://www.eclipse.org/che/images/logo-eclipseche.svg
repository: https://github.com/redhat-developer/vscode-quarkus
category: Language
firstPublicationDate: "2019-11-05"
spec:
  containers:
    - image: "docker.io/eclipse/che-remote-plugin-runner-java11:next"
      name: vscode-quarkus
      memoryLimit: "1500Mi"
      volumes:
      - mountPath: "/home/theia/.m2"
        name: m2
  extensions:
    - https://github.com/microsoft/vscode-java-debug/releases/download/0.20.0/vscode-java-debug-0.20.0.vsix
    - https://download.jboss.org/jbosstools/static/jdt.ls/stable/java-0.50.0-1825.vsix
    - https://download.jboss.org/jbosstools/vscode/snapshots/vscode-quarkus/vscode-quarkus-1.1.1-158.vsix

```

**Comment by tsmaeder** [comment]
@svor does it work if you ad the "console": "internal console" attribute to the launch config?

**Comment by svor** [comment]
@tsmaeder It is not possible to add the `console` attribute to the launch configuration which has value of "request" attribute as "attach", we could do that if the configuration has **"request": "launch"** attribute. So, probably I was mistaken when wrote that this is related to  https://github.com/eclipse-theia/theia/issues/6103

**Comment by tsmaeder** [comment]
Could very well be a duplicate of https://github.com/eclipse/che/issues/15117

**Comment by tsmaeder** [comment]
This might be a place to look. https://github.com/redhat-developer/vscode-quarkus/commit/04e7652182876bc6ef2da49d68d7328e4e9a77d8#diff-0dbbad2f7cd76714b5a5e9cba1b5495fR113 Suspicion: we are missing an environment variable.

**Comment by benoitf** [comment]
setting milestone 7.5.0 as it's your sprint @tsmaeder

**Comment by tolusha** [comment]
TODO: 
- https://github.com/eclipse-theia/theia/issues/6534
- https://github.com/eclipse-theia/theia/issues/6534

**Comment by amisevsk** [comment]
Shouldn't `"preLaunchTask": "quarkus:dev",` be `"preLaunchTask": "mvn quarkus:dev",`?

**Comment by svor** [comment]
@amisevsk `quarkus:dev` is task's name, the command is `mvn quarkus:dev`. Into debug configuration we have to put the name.

**Comment by amisevsk** [comment]
@svor Ah apologies, I misunderstood.

**Comment by tsmaeder** [comment]
The problem is that the pre-Launch task needs to be run in the dev container instead of the quarkus sidecar

**Comment by tsmaeder** [comment]
We propose to add configuration to the devfile that allows to execute tasks that are contributed by a VS Code extension in a different container, like:

task: "quarkus:dev"-> execute in: "quarkus-dev-machine". 
Where "quarkus-dev-machine" is the alias of a component.

**Comment by tsmaeder** [comment]
This needs to be addressed by the platform team.

**Comment by skabashnyuk** [comment]
>This needs to be addressed by the platform team.

@tsmaeder can you explain why? I don't understand the problem.

**Comment by sunix** [comment]
By default, I would run the task in the container where the extension is running.

**Comment by skabashnyuk** [comment]
@sunix are you working on this task at this moment?

**Comment by tsmaeder** [comment]
@skabashnyuk because we would need to be able to configure the container to execute in in the devfile.

**Comment by svor** [comment]
@tsmaeder 
I think the current task has two parts:
The first one (probably it is for platform team) is to make it possible to configure devfile to mark VS Code tasks (not  commands) which should be executed in special container. As for me the structure should be like 

```yaml
tasks:
-
  label:
  component:
```
The second part is to adapt task runner process on che-theia side. In that part we should analyze workspace configuration and execute tasks in related container
