### ISSUE TITLE
[Quarkus] quarkus:dev task was generated incorrectly

### ISSUE THREAD

**Issue by svor** [eclipse-che/che#15117]
While testing [vscode-quarkus](https://marketplace.visualstudio.com/items?itemName=redhat.vscode-quarkus) extension I detected a problem:
The generated task **quarkus:dev**  has not valid command:
```json
{
            "label": "quarkus:dev",
            "type": "shell",
            "command": "undefined quarkus:dev",
            "windows": {
                "command": "undefined quarkus:dev"
            },
            "isBackground": true,
            "problemMatcher": [
                {
                    "pattern": [
                        {
                            "regexp": "\\b\\B",
                            "file": 1,
                            "location": 2,
                            "message": 3
                        }
                    ],
                    "background": {
                        "activeOnStart": true,
                        "beginsPattern": "^.*Scanning for projects...*",
                        "endsPattern": "^.*Quarkus .* started in .*\\. Listening on:*"
                    }
                }
            ]
        }
``` 

<details><summary>Che remote plugin with vscode-quarkus extension</summary><p> 

```
apiVersion: v2
publisher: redhat
name: quarkus
version: 1.1.1
type: VS Code extension
displayName: Quarkus Tools
title: Quarkus Tools by Red Hat
description: This plug-in provides support for Quarkus development via a Quarkus language server and a Quarkus jdt.ls extension.
icon: https://www.eclipse.org/che/images/logo-eclipseche.svg
repository: https://github.com/redhat-developer/vscode-quarkus
category: Language
firstPublicationDate: "2019-11-05"
spec:
  containers:
    - image: "docker.io/eclipse/che-remote-plugin-runner-java11:next"
      name: vscode-quarkus
      memoryLimit: "1500Mi"
      volumes:
      - mountPath: "/home/theia/.m2"
        name: m2
  extensions:
    - https://github.com/microsoft/vscode-java-debug/releases/download/0.20.0/vscode-java-debug-0.20.0.vsix
    - https://download.jboss.org/jbosstools/static/jdt.ls/stable/java-0.50.0-1825.vsix
    - https://download.jboss.org/jbosstools/vscode/snapshots/vscode-quarkus/vscode-quarkus-1.1.1-158.vsix

```
