### ISSUE TITLE
I get a 503 error right after creating a workspace.

### ISSUE THREAD

**Issue by kellyhyomin** [eclipse-che/che#15110]
## Summary
- che version : 7.3.0
- runtime : kubernetes
- screenshots
![image](https://user-images.githubusercontent.com/29850624/68275937-1b456c00-00b0-11ea-9a7e-0e9dd29cfeac.png)
![image](https://user-images.githubusercontent.com/29850624/68275796-ed602780-00af-11ea-9fce-6e5cc4e49b78.png)
![image](https://user-images.githubusercontent.com/29850624/68276118-32845980-00b0-11ea-9cee-b48238bf8981.png)

- my test devfile.yaml
```
---
apiVersion: 1.0.0
metadata:
  generateName: cdr-
components:
-
  type: cheEditor
  id: cdr/code-server/2.1523-vsc1.38.1
  memoryLimit: 1024Mi
```

I registered the code-server(Editor) with devfile-registry and added a stack.
I get a 503 error right after creating a workspace on the stack.
But when I refresh the browser, I get a normal vscode screen.
I wonder if there is a way to fix it.

**Comment by benoitf** [comment]
@skabashnyuk liveness issue ?
https://github.com/eclipse/che/blob/e3bc0a0bdab5df5b0da7ed49fc0371ee2e015852/assembly/assembly-wsmaster-war/src/main/webapp/WEB-INF/classes/che/che.properties#L158

**Comment by skabashnyuk** [comment]
That is by design. We need to know endpoint name to ping that has to be running for any case. In our case, this is cheEditor endpoint name. The predefined list you can find in `che.workspace.server.liveness_probes` variable.
To handle that problem you have two options.
- adjust ` che.workspace.server.liveness_probes` or `CHE_WORKSPACE_SERVER_LIVENESS_PROBES`
- or rename you endpoint name to match predefined ```che.workspace.server.liveness_probes=wsagent/http,exec-agent/http,terminal,theia,jupyter,dirigible ```  https://github.com/eclipse/che-plugin-registry/blob/master/v3/plugins/dirigiblelabs/dirigible/3.4.0/meta.yaml#L15

**Comment by benoitf** [comment]
@skabashnyuk but code-server is provided by default on che so AFAIK che.properties should be updated according to all editors provided in Eclipse Che like https://github.com/eclipse/che-plugin-registry/blob/master/v3/plugins/cdr/code-server/2.1523-vsc1.38.1/meta.yaml#L15

**Comment by skabashnyuk** [comment]
Yes. Look so. @sr229 @kellyhyomin can you offer a pr?

**Comment by sr229** [comment]
I've been meaning to move it to the official images since my images were on testing phase, but officially this should have been fixed by some PRs in the che-plugin-registry already @sachinaraballi

**Comment by wonjooncho** [comment]
@skabashnyuk I wonder that If I create a new alternative IDE in che like this [link](https://www.eclipse.org/che/docs/che-7/using-alternative-ides-in-che/), should I use only the endpoint names in this list [wsagent/http, exec-agent/http, terminal, theia, jupyter, dirigible]?
I think there should be an other endpoint name for the alternate IDEs.
WDYT?

**Comment by skabashnyuk** [comment]
>I think there should be an other endpoint name for the alternate IDEs.

If you don't want to use already defined names you have to adjust che.workspace.server.liveness_probes or CHE_WORKSPACE_SERVER_LIVENESS_PROBES. We may add some neutral or generic names like `ide-server` to defaults if you want.

**Comment by kellyhyomin** [comment]
@skabashnyuk @wonjooncho 
I added the 'ide-server' you told me in the configmap.yaml file and restarted che.
#### **`che/deploy/kubernetes/helm/che/templates/configmap.yaml`**
```yaml
apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    app: che
    component: che
  name: che
data:
  CHE_HOST: {{ template "cheHost" . }}
  CHE_PORT: "8080"
  .
  .
  CHE_WORKSPACE_SERVER_LIVENESS_PROBES: wsagent/http,exec-agent/http,terminal,theia,jupyter,dirigible,ide-server
.
.
.
``` 

my new alternative IDE meta.yaml
```yaml
apiVersion: v2
publisher: popcornsar
name: webio
version: latest
type: Che Editor
displayName: AutoSAR Webio R19-03-V3
title: AutoSAR Webio R19-03
description: AutoSAR Webio
icon: https://www.eclipse.org/che/images/logo-eclipseche.svg
category: Editor
repository: https://github.com/ws-skeleton/che-editor-jupyter/
firstPublicationDate: '2019-02-05'
spec:
  endpoints:
  - name: ide-server
    public: true
    targetPort: 8080
    attributes:
      protocol: http
      type: ide
  containers:
  - name: webio
.
.
.
``` 
I specified ide-server as the endpoint name but I also faced a 503 error.
There is no 503 error when changing the endpoint name to 'theia' you provide.
I wonder if other settings are needed when using ide-server or other custom names.
