### ISSUE TITLE
[Quarkus] Can't add Quarkus extension to the project

### ISSUE THREAD

**Issue by svor** [eclipse-che/che#15116]
While testing [vscode-quarkus](https://marketplace.visualstudio.com/items?itemName=redhat.vscode-quarkus) extension I detected a problem:
There is not possible to add new Quarkus extension to the project. 
How to reproduce:
1. Go to `Quarkus: Add extension to currant project` command
2. Select some extension and press Enter
3. An error in Output view:
```log
ERROR:Remote plugin in vscode-quarkusare: promise rejection is not handled in two seconds: TypeError: Cannot read property 'endsWith' of undefined
ERROR:Remote plugin in vscode-quarkusare: promise rejection stack trace: TypeError: Cannot read property 'endsWith' of undefined
    at Object.s [as currentWindowsShell] (/tmp/vscode-unpacked/redhat.quarkus.latest.lanvsfyrgl.vscode-quarkus-1.1.1-158.vsix/extension/dist/extension.js:1:257525)
    at Object.<anonymous> (/tmp/vscode-unpacked/redhat.quarkus.latest.lanvsfyrgl.vscode-quarkus-1.1.1-158.vsix/extension/dist/extension.js:157:148239)
    at Generator.next (<anonymous>)
    at /tmp/vscode-unpacked/redhat.quarkus.latest.lanvsfyrgl.vscode-quarkus-1.1.1-158.vsix/extension/dist/extension.js:157:147815
    at new Promise (<anonymous>)
    at n (/tmp/vscode-unpacked/redhat.quarkus.latest.lanvsfyrgl.vscode-quarkus-1.1.1-158.vsix/extension/dist/extension.js:157:147592)
    at Object.runInTerminal (/tmp/vscode-unpacked/redhat.quarkus.latest.lanvsfyrgl.vscode-quarkus-1.1.1-158.vsix/extension/dist/extension.js:157:147989)
    at Object.<anonymous> (/tmp/vscode-unpacked/redhat.quarkus.latest.lanvsfyrgl.vscode-quarkus-1.1.1-158.vsix/extension/dist/extension.js:157:147463)
    at Generator.next (<anonymous>)
    at a (/tmp/vscode-unpacked/redhat.quarkus.latest.lanvsfyrgl.vscode-quarkus-1.1.1-158.vsix/extension/dist/extension.js:157:146696)
```
</details>
But if do it again, the extension will be installed

<details><summary>Che remote plugin with vscode-quarkus extension</summary><p> 

```
apiVersion: v2
publisher: redhat
name: quarkus
version: 1.1.1
type: VS Code extension
displayName: Quarkus Tools
title: Quarkus Tools by Red Hat
description: This plug-in provides support for Quarkus development via a Quarkus language server and a Quarkus jdt.ls extension.
icon: https://www.eclipse.org/che/images/logo-eclipseche.svg
repository: https://github.com/redhat-developer/vscode-quarkus
category: Language
firstPublicationDate: "2019-11-05"
spec:
  containers:
    - image: "docker.io/eclipse/che-remote-plugin-runner-java11:next"
      name: vscode-quarkus
      memoryLimit: "1500Mi"
      volumes:
      - mountPath: "/home/theia/.m2"
        name: m2
  extensions:
    - https://github.com/microsoft/vscode-java-debug/releases/download/0.20.0/vscode-java-debug-0.20.0.vsix
    - https://download.jboss.org/jbosstools/static/jdt.ls/stable/java-0.50.0-1825.vsix
    - https://download.jboss.org/jbosstools/vscode/snapshots/vscode-quarkus/vscode-quarkus-1.1.1-158.vsix

```
