### ISSUE TITLE
[Quarkus] Welcome page is empty

### ISSUE THREAD

**Issue by svor** [eclipse-che/che#15113]
While testing [vscode-quarkus](https://marketplace.visualstudio.com/items?itemName=redhat.vscode-quarkus) extension I detected a problem: if open Welcome page by `Quarkus: Welcome` command or it was opened automatically, It doesn't provide any information. 

![screenshot-che-che 192 168 99 104 nip io-2019 11 06-10_45_14](https://user-images.githubusercontent.com/1271546/68282555-98f28300-0082-11ea-95ac-0b7d350f1d3d.png)

<details><summary>In the Output view I see error messages:</summary><p>

```
root ERROR [hosted-plugin: 26341] Promise rejection not handled in one second: TypeError: this._panel.webview.asWebviewUri is not a function
root ERROR [hosted-plugin: 26341] With stack trace: TypeError: this._panel.webview.asWebviewUri is not a function
    at c.getCssUri (/tmp/vscode-unpacked/redhat.vscode-quarkus-1.1.1.vsix/extension/dist/extension.js:219:119008)
    at c.<anonymous> (/tmp/vscode-unpacked/redhat.vscode-quarkus-1.1.1.vsix/extension/dist/extension.js:219:118707)
    at Generator.next (<anonymous>)
    at /tmp/vscode-unpacked/redhat.vscode-quarkus-1.1.1.vsix/extension/dist/extension.js:219:117610
    at new Promise (<anonymous>)
    at n (/tmp/vscode-unpacked/redhat.vscode-quarkus-1.1.1.vsix/extension/dist/extension.js:219:117387)
    at c.getWebviewContent (/tmp/vscode-unpacked/redhat.vscode-quarkus-1.1.1.vsix/extension/dist/extension.js:219:118561)
    at c.<anonymous> (/tmp/vscode-unpacked/redhat.vscode-quarkus-1.1.1.vsix/extension/dist/extension.js:219:118512)
    at Generator.next (<anonymous>)
    at /tmp/vscode-unpacked/redhat.vscode-quarkus-1.1.1.vsix/extension/dist/extension.js:219:117610
    at new Promise (<anonymous>)
    at n (/tmp/vscode-unpacked/redhat.vscode-quarkus-1.1.1.vsix/extension/dist/extension.js:219:117387)
    at c.setPanelHtml (/tmp/vscode-unpacked/redhat.vscode-quarkus-1.1.1.vsix/extension/dist/extension.js:219:118443)
    at new c (/tmp/vscode-unpacked/redhat.vscode-quarkus-1.1.1.vsix/extension/dist/extension.js:219:117835)
    at Function.createOrShow (/tmp/vscode-unpacked/redhat.vscode-quarkus-1.1.1.vsix/extension/dist/extension.js:219:118065)
    at e.subscriptions.push.s.commands.registerCommand (/tmp/vscode-unpacked/redhat.vscode-quarkus-1.1.1.vsix/extension/dist/extension.js:157:46121)
    at /home/vsvydenko/codenvy/theia/packages/plugin-ext/lib/plugin/command-registry.js:126:28
    at CommandRegistryImpl.<anonymous> (/home/vsvydenko/codenvy/theia/packages/plugin-ext/lib/plugin/command-registry.js:182:51)
    at step (/home/vsvydenko/codenvy/theia/packages/plugin-ext/lib/plugin/command-registry.js:51:23)
    at Object.next (/home/vsvydenko/codenvy/theia/packages/plugin-ext/lib/plugin/command-registry.js:32:53)
    at /home/vsvydenko/codenvy/theia/packages/plugin-ext/lib/plugin/command-registry.js:26:71
    at new Promise (<anonymous>)
root ERROR TypeError: Cannot read property 'style' of undefined
    at http://localhost:3000/45.bundle.js:2128:30
    at http://localhost:3000/bundle.js:113857:33
    at CallbackList.../../packages/core/lib/common/event.js.CallbackList.invoke (http://localhost:3000/bundle.js:113872:39)
    at Emitter.../../packages/core/lib/common/event.js.Emitter.fire (http://localhost:3000/bundle.js:113960:29)
    at HTMLDivElement.ApplicationShellMouseTracker.mousedownListener (http://localhost:3000/bundle.js:99218:79)
```
</details>

<details><summary>Che remote plugin with vscode-quarkus extension:</summary><p> 

```
apiVersion: v2
publisher: redhat
name: quarkus
version: 1.1.1
type: VS Code extension
displayName: Quarkus Tools
title: Quarkus Tools by Red Hat
description: This plug-in provides support for Quarkus development via a Quarkus language server and a Quarkus jdt.ls extension.
icon: https://www.eclipse.org/che/images/logo-eclipseche.svg
repository: https://github.com/redhat-developer/vscode-quarkus
category: Language
firstPublicationDate: "2019-11-05"
spec:
  containers:
    - image: "docker.io/eclipse/che-remote-plugin-runner-java11:next"
      name: vscode-quarkus
      memoryLimit: "1500Mi"
      volumes:
      - mountPath: "/home/theia/.m2"
        name: m2
  extensions:
    - https://github.com/microsoft/vscode-java-debug/releases/download/0.20.0/vscode-java-debug-0.20.0.vsix
    - https://download.jboss.org/jbosstools/static/jdt.ls/stable/java-0.50.0-1825.vsix
    - https://download.jboss.org/jbosstools/vscode/snapshots/vscode-quarkus/vscode-quarkus-1.1.1-158.vsix

```
