### ISSUE TITLE
[che-operator] - install Prometheus CR

### ISSUE THREAD

**Issue by sparkoo** [eclipse-che/che#15212]
### Is your enhancement related to a problem? Please describe.
Task of this epic https://github.com/eclipse/che/issues/15046
To support monitoring of Che with Prometheus, we can instantiate the Prometheus with `Prometheus` CR managed by `prometheus-operator`.

### Describe the solution you'd like
Update `CheServer` CRD with:
```
metrics:
  prometheus:
    enable: # default false
```

This is applicable only if `metrics.enable: true`.
If `metrics.prometheus.enable:true` and `Prometheus` CRD is defined in the cluster, create `Prometheus` CR:
```
apiVersion: monitoring.coreos.com/v1
kind: Prometheus
metadata:
  name: prometheus
  labels:
    app: che
    component: prometheus
spec:
  serviceAccountName: prometheus-k8s
  serviceMonitorSelector: {}
  serviceMonitorNamespaceSelector: {}
```

##### Labels
`app=che` `component=prometheus`

##### ServiceAccount
We need to run Prometheus with service account that has `write, list` cluster permissions to `services, pods, endpoints`. prometheus-operator should create `prometheus-k8s` service account with such permissions. We can also use `che` ServiceAccount, but we need to make sure we have sufficient permissions.
 
##### Storage
Not the scope of this task.

##### Permissions
Operator should run with `prometheus-operator` ServiceAccout bound to `prometheus-operator` ClusterRole.

##### Namespace issue
prometheus-operator installed from Operator Hub runs with `'-namespaces=$(NAMESPACES)'` argument, where $(NAMESPACES) is set to annotation `olm.targetNamespaces: <installed-namespace>`. This limits the operator to work only in its own namespace. This would be ok for monitoring master from same namespace, but when we want to discover workspace services in different namespaces, this is a problem. To operate on whole cluster, we need to omit `-namespaces` parameter. This can be done in `ClusterServiceVersion` in `prometheus-operator` deployment.
We don't manage prometheus-operator, so this is something we need to document.

### Additional context
epic: https://github.com/eclipse/che/issues/15046
analysis: https://github.com/eclipse/che/issues/15136 proposal v3 https://github.com/eclipse/che/issues/15136#issuecomment-557533522
