### ISSUE TITLE
[che-operator] install Jaeger CR

### ISSUE THREAD

**Issue by sparkoo** [eclipse-che/che#15214]
### Is your enhancement related to a problem? Please describe.
Task of this epic https://github.com/eclipse/che/issues/15046
To support tracing with self manager Jaeger, we need che-operator to be able to install Jaeger.

### Describe the solution you'd like
Update `CheCluster` CRD with:
```
tracing:
  jaeger:
    enable: # default true
```
If `true` and `Jaeger` CRD is defined in the cluster, create `Jaeger` CR:
```
apiVersion: jaegertracing.io/v1
kind: Jaeger
metadata:
  name: che-jaeger
  labels:
    app: che
    component: jaeger
```

### Additional context
epic: https://github.com/eclipse/che/issues/15046
analysis: https://github.com/eclipse/che/issues/15136 proposal v3 https://github.com/eclipse/che/issues/15136#issuecomment-557533522
