### ISSUE TITLE
[che-operator] - enable che-server tracing

### ISSUE THREAD

**Issue by sparkoo** [eclipse-che/che#15213]
### Is your enhancement related to a problem? Please describe.
Task of this epic https://github.com/eclipse/che/issues/15046
To support tracing, we need to make it possible to enable and configure tracing of che server from che-operator.

### Describe the solution you'd like
On che-server, tracing is configured with several options https://www.eclipse.org/che/docs/che-7/tracing-che/. The minimal values we need to set are `CHE_TRACING_ENABLED` and `JAEGER_ENDPOINT`.
For that, we will update `CheCluster` CRD with:
```
tracing:
  enable: # default false
  jaegerClientConfig:	# optional
    serviceName:"che-server"
    endpoint: "http://jaeger-collector:14268/api/traces"	# endpoint is mandatory for external jaeger
    sampler:
      managerHostPort: "jaeger:5778"
      type:"const"
      param:"1"
    reporter:
      maxQueueSize: "10000"
```

If `tracing.enable:true` enable che-server tracing and set other tracing config values as set in `tracing.jaegerClientConfig` with defaults https://www.eclipse.org/che/docs/che-7/tracing-che/

 Set the default value of `tracing.jaegerClientConfig.endpoint` to instance we will create in our own namespace (https://github.com/eclipse/che/issues/15214). In case of external Jaeger, It must be set to `jaeger-collector` service endpoint (http://<jaeger-collector-servicename>.<jaeger-namespace>:14268/api/traces) -> `JAEGER_ENDPOINT="http://<jaeger-collector-servicename>.<jaeger-namespace>:14268/api/traces"`.

### Additional context
epic: https://github.com/eclipse/che/issues/15046
analysis: https://github.com/eclipse/che/issues/15136 proposal v3 https://github.com/eclipse/che/issues/15136#issuecomment-557533522
