### ISSUE TITLE
[che-operator] - create ServiceMonitor and GrafanaDashboard when CRDs available and monitoring enabled

### ISSUE THREAD

**Issue by sparkoo** [eclipse-che/che#15211]
### Is your enhancement related to a problem? Please describe.
Task of this epic https://github.com/eclipse/che/issues/15046
prometheus-operator and grafana-operator helps configure prometheus/grafana with CR objects. To support this setup, we need to create these objects so operators can discover them.
Prometheus operator uses ServiceMonitor CRD - https://github.com/coreos/prometheus-operator/blob/master/Documentation/user-guides/getting-started.md#related-resources https://github.com/coreos/prometheus-operator/blob/master/example/prometheus-operator-crd/servicemonitor.crd.yaml
Grafana operator uses GrafanaDashboard CRD - https://github.com/integr8ly/grafana-operator/blob/master/documentation/dashboards.md https://github.com/integr8ly/grafana-operator/blob/master/deploy/crds/GrafanaDashboard.yaml

### Describe the solution you'd like
Enhance `CheCluster` CRD with:
```
metrics:
  prometheusServicemonitor:
    enable: # default false
  grafanaDashboard:
    enable: # default false
```

This is applicable only if monitoring is enabled (`metrics.enable=true` #15210). If `metrics.prometheusServicemonitor.enable: true`/`metrics.grafanaDashboard.enable: true` and `ServiceMonitor`/`GrafanaDashboard` CRDs are defined in the cluster, create the objects.

`ServiceMonitor` for Che master (resolve `<che-namespace>` to real namespace where Che is being deployed):
```
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: che-master-monitoring
spec:
  endpoints:
  - port: metrics
  namespaceSelector:
	matchNames:
	- <che-namespace>
  selector:
	matchLabels:
	  app: che
```

`ServiceMonitor` for Che workspaces:
```
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: che-workspaces-monitoring
spec:
  endpoints:
  - port: server-3100
	interval: 15s
  selector:
	matchExpressions:
	- key: che.workspace_id
	  operator: Exists
```

`GrafanaDashboard` for Che master
```
apiVersion: integreatly.org/v1alpha1
kind: GrafanaDashboard
metadata:
  labels:
	app: che
        component: grafana
  name: che-master-dashboard
  namespace: che
spec:
  name: che-master-jvm.json
  json: |
	{
	  ...
	}
```

`GrafanaDashboard` for Che workspaces:
```
apiVersion: integreatly.org/v1alpha1
kind: GrafanaDashboard
metadata:
  labels:
	app: grafana
  name: che-workspaces-dashboard
  namespace: che
spec:
  name: che-workspaces-jvm.json
  json: |
	{
	  ...
	}
```

Take jsons content from here https://github.com/eclipse/che/blob/master/deploy/openshift/templates/monitoring/grafana-dashboards.yaml (?)

There is one open question with grafana json datasources: https://github.com/eclipse/che/issues/15136#issuecomment-553933112. I would suggest to pul default `Prometheus` value there, and create new issue to come up with more robust solution, if needed.

### Additional context
epic: https://github.com/eclipse/che/issues/15046
analysis: https://github.com/eclipse/che/issues/15136 proposal v3 https://github.com/eclipse/che/issues/15136#issuecomment-557533522
