### ISSUE TITLE
devfile should allow to set `env` to chePlugin

### ISSUE THREAD

**Issue by sunix** [eclipse-che/che#15258]
### Is your enhancement related to a problem? Please describe.
It is not possible to set env variable to a container of a che plugin

### Describe the solution you'd like
it would be nice if we could have in a devfile something that looks like:

```yaml
  - id: redhat/java/latest
    memoryLimit: 1536M
    type: chePlugin
    alias: java
    env:
      - value: '-Dmaven.repo.local=/projects/local/m2repo'
        name: MAVEN_OPTS
```
