### ISSUE TITLE
Incorrect highlighting of devfile yaml with multilines string by dashboard

### ISSUE THREAD

**Issue by sleshchenko** [eclipse-che/che#15276]
### Describe the bug
Incorrect highlighting of devfile yaml with multilines string by dashboard.

Note `env` field is highlighted in the same way as `referenceContent` value, but in fact, it's not a part of `referenceContent` value but a root field of component object. On the right hand side - you can see the right highlighting.

![Screenshot_20191121_144637](https://user-images.githubusercontent.com/5887312/69341535-68aa0780-0c72-11ea-9e72-6e4d78d7b76f.png)

Note that GitHub and Atom works in the same way
```yaml
metadata:
  name: env-override
components:
  - referenceContent: |
      apiVersion: apps/v1
      kind: Deployment
      ...
    env:
      - value: Hello!
        name: TEST
  - referenceContent: |
      apiVersion: apps/v1
```
```yaml
metadata:
  name: env-override
components:
  - referenceContent: > 
      value
    env:
      - value: Hello!
        name: TEST
  - referenceContent: |
      apiVersion: apps/v1
```
But the following is displayed correctly:
```yaml
metadata:
  name: env-override
components:
  - referenceContent: "
      blah-blah
     "
    env:
      - value: Hello!
        name: TEST
  - referenceContent: |
      apiVersion: apps/v1
```
And it works correctly even if we put some field before `referenceContent` :bomb: 
```yaml
metadata:
  name: env-override
components:
  - alias: my-component
    referenceContent: > 
      value
    env:
      - value: Hello!
        name: TEST
  - referenceContent: |
      apiVersion: apps/v1
```
Ready? One more way to make it work, just add new line:
```yaml
metadata:
  name: env-override
components:
  - 
    referenceContent: > 
      value
    env:
      - value: Hello!
        name: TEST
  - referenceContent: |
      apiVersion: apps/v1
```

I'm not sure if we are able to fix this issue on the Che side, but it makes it a bit important for Che since fields are sorted(by Che Server or Dashboard) in a way that brokes highlighting. 
As a workaround we could sort fields in a different way.
### Che version

 - [ ] latest
 - [x] nightly
 - [ ] other: please specify

### Steps to reproduce
1. Open edit Devfile in Dashboard.
2. Paste there the following content:
<details>
<summary>Devfile to test</summary>

```yaml
apiVersion: 1.0.0
metadata:
  name: env-override
components:
  - referenceContent: |
      apiVersion: apps/v1
      kind: Deployment
      metadata:
        name: empty-env
      spec:
        selector:
          matchLabels:
            app.kubernetes.io/name: empty-env
        template:
          metadata:
            labels:
              app.kubernetes.io/name: empty-env
            name: empty-env
          spec:
            containers:
            - name: empty-env
              image: alpine
              env: []
    type: kubernetes
    entrypoints:
      - command:
          - tail
          - '-f'
          - /dev/null
    alias: empty-env
    env:
      - value: Hello!
        name: TEST
  - referenceContent: |
      apiVersion: apps/v1
      kind: Deployment
      metadata:
        name: no-env
      spec:
        selector:
          matchLabels:
            app.kubernetes.io/name: no-env
        template:
          metadata:
            labels:
              app.kubernetes.io/name: no-env
            name: no-env
          spec:
            containers:
            - name: no-env
              image: alpine
    type: kubernetes
    entrypoints:
      - command:
          - tail
          - '-f'
          - /dev/null
    alias: no-env
    env:
      - value: Hello!
        name: TEST
```
</details>

### Expected behavior
`type`, `alias` fields are not highlighted in the same way as referecentContent value.
