### ISSUE TITLE
Provide referenceContent for the cheEditor type in yaml configuration

### ISSUE THREAD

**Issue by vzhukovs** [eclipse-che/che#15286]
### Is your enhancement related to a problem? Please describe.
It would be nice to have an ability to setup `referenceContent` to configure meta yaml for the cheEditor type. At this moment, there is only `reference` property, that consumes url of the meta.yaml, which describes configuration for the che editor.

Test devfile used for the workspace creation: [workspace.yaml](https://github.com/vzhukovskii/devfiles/blob/master/workspace.yaml). And che editor configuration: [meta.yaml](https://github.com/vzhukovskii/devfiles/blob/master/meta.yaml).

### Describe the solution you'd like
Nice to have a property `referenceContent` along with `reference` to combine two yaml files into single one.

<details>
<summary>Example devfile</summary>

```yaml
apiVersion: 1.0.0
metadata:
 name: workspace
components:
  - 
    id: ms-kubernetes-tools/vscode-kubernetes-tools/latest
    type: chePlugin
  - 
    alias: theia-editor
    type: cheEditor
    referenceContent: | 
      apiVersion: v2
      publisher: eclipse
      name: che-theia
      version: next
      type: Che Editor
      displayName: theia-ide
      title: Eclipse Theia development version.
      description: Eclipse Theia, get the latest release each day.
      icon: https://raw.githubusercontent.com/theia-ide/theia/master/logo/theia-logo-no-text-black.svg?sanitize=true
      category: Editor
      repository: https://github.com/eclipse/che-theia
      firstPublicationDat      apiVersion: v2
      publisher: eclipse
      name: che-theia
      version: next
      type: Che Editor
      displayName: theia-ide
      title: Eclipse Theia development version.
      description: Eclipse Theia, get the latest release each day.
      icon: https://raw.githubusercontent.com/theia-ide/theia/master/logo/theia-logo-no-text-black.svg?sanitize=true
      category: Editor
      repository: https://github.com/eclipse/che-theia
      firstPublicationDate: "2019-03-07"
      spec:
        endpoints:
         -  name: "theia"
            public: true
            targetPort: 3100
            attributes:
              protocol: http
              type: ide
              secure: true
              cookiesAuthEnabled: true
              discoverable: false
         -  name: "theia-dev"
            public: true
            targetPort: 3130
            attributes:
              protocol: http
              type: ide-dev
              discoverable: false
         -  name: "theia-redirect-1"
            public: true
            targetPort: 13131
            attributes:
              protocol: http
              discoverable: false
         -  name: "theia-redirect-2"
            public: true
            targetPort: 13132
            attributes:
              protocol: http
              discoverable: false
         -  name: "theia-redirect-3"
            public: true
            targetPort: 13133
            attributes:
              protocol: http
              discoverable: false
        containers:
         - name: theia-ide
           image: "vzhukovs/che-theia:next"
           env:
               - name: THEIA_PLUGINS
                 value: local-dir:///plugins
               - name: HOSTED_PLUGIN_HOSTNAME
                 value: 0.0.0.0
               - name: HOSTED_PLUGIN_PORT
                 value: "3130"
           volumes:
               - mountPath: "/plugins"
                 name: plugins
           mountSources: true
           ports:
               - exposedPort: 3100
               - exposedPort: 3130
               - exposedPort: 13131
               - exposedPort: 13132
               - exposedPort: 13133
           memoryLimit: "512M"
        initContainers:
        - name: remote-runtime-injector
          image: "vzhukovs/che-theia-endpoint-runtime-binary:next"
          volumes:
            - mountPath: "/remote-endpoint"
              name: remote-endpoint
              ephemeral: true
          env:
            - name: PLUGIN_REMOTE_ENDPOINT_EXECUTABLE
              value: /remote-endpoint/plugin-remote-endpoint
            - name: REMOTE_ENDPOINT_VOLUME_NAME
              value: remote-endpoint
          type: cheEditor
        - id: ms-kubernetes-tools/vscode-kubernetes-tools/latest
          type: chePlugine: "2019-03-07"
      spec:
        endpoints:
         -  name: "theia"
            public: true
            targetPort: 3100
            attributes:
              protocol: http
              type: ide
              secure: true
              cookiesAuthEnabled: true
              discoverable: false
         -  name: "theia-dev"
            public: true
            targetPort: 3130
            attributes:
              protocol: http
              type: ide-dev
              discoverable: false
         -  name: "theia-redirect-1"
            public: true
            targetPort: 13131
            attributes:
              protocol: http
              discoverable: false
         -  name: "theia-redirect-2"
            public: true
            targetPort: 13132
            attributes:
              protocol: http
              discoverable: false
         -  name: "theia-redirect-3"
            public: true
            targetPort: 13133
            attributes:
              protocol: http
              discoverable: false
        containers:
         - name: theia-ide
           image: "vzhukovs/che-theia:next"
           env:
               - name: THEIA_PLUGINS
                 value: local-dir:///plugins
               - name: HOSTED_PLUGIN_HOSTNAME
                 value: 0.0.0.0
               - name: HOSTED_PLUGIN_PORT
                 value: "3130"
           volumes:
               - mountPath: "/plugins"
                 name: plugins
           mountSources: true
           ports:
               - exposedPort: 3100
               - exposedPort: 3130
               - exposedPort: 13131
               - exposedPort: 13132
               - exposedPort: 13133
           memoryLimit: "512M"
        initContainers:
        - name: remote-runtime-injector
          image: "vzhukovs/che-theia-endpoint-runtime-binary:next"
          volumes:
            - mountPath: "/remote-endpoint"
              name: remote-endpoint
              ephemeral: true
          env:
            - name: PLUGIN_REMOTE_ENDPOINT_EXECUTABLE
              value: /remote-endpoint/plugin-remote-endpoint
            - name: REMOTE_ENDPOINT_VOLUME_NAME
              value: remote-endpoint
```
</details>

### Describe alternatives you've considered

–

### Additional context

–

P.S. It might be useful to specify referenceContent for `chePlugin`s as well. In a scope of this issue it's needed to implement referenceContent support for `chePlugin` or create a separate issue for that in case from implementation point of view it makes more sense.
