### ISSUE TITLE
[che-operator] - install Grafana CR

### ISSUE THREAD

**Issue by sparkoo** [eclipse-che/che#15299]
### Is your enhancement related to a problem? Please describe.
To support monitoring of Che with Prometheus and Grafana, we must instantiate the Grafana with Grafana CR managed by grafana-operator.

### Describe the solution you'd like
Update CheServer CRD with:
```
metrics:
  grafana:
    enable: # default false
  grafanaDatasource:
    enable: # default false
```

This is applicable only if metrics.enable: true.
If metrics.grafana.enable:true and Grafana CRD is defined in the cluster, create Grafana CR:
```
apiVersion: integreatly.org/v1alpha1
kind: Grafana
metadata:
  name: che-grafana
  labels:
	app: che
	component: grafana
spec:
  ingress:
	enabled: true
  config:
	auth:
	  disable_signout_menu: true
	auth.anonymous:
	  enabled: true
	log:
	  level: warn
	  mode: console
	security:
	  admin_password: secret
	  admin_user: root
  dashboardLabelSelector:
	- matchExpressions:
		- key: app
		  operator: In
		  values:
			- che
```

We also need to create `GrafanaDatasource` CR to connect with Prometheus:
```
apiVersion: integreatly.org/v1alpha1
kind: GrafanaDataSource
metadata:
  name: che-grafanadatasource
  namespace: monitoring
  labels:
    app: che
    component: grafana
spec:
  datasources:
	- access: proxy
	  editable: true
	  isDefault: true
	  jsonData:
		timeInterval: 5s
	  name: Prometheus
	  type: prometheus
	  url: 'http://prometheus-operated:9090'
	  version: 1
  name: che-datasources.yaml
```

##### Security
Not the scope of this task

### Additional context
epic: https://github.com/eclipse/che/issues/15046
analysis: https://github.com/eclipse/che/issues/15136 proposal v3 https://github.com/eclipse/che/issues/15136#issuecomment-557533522
