### ISSUE TITLE
[che-operator] when metrics enabled, create and configure full monitoring stack by default

### ISSUE THREAD

**Issue by sparkoo** [eclipse-che/che#15302]
### Is your enhancement related to a problem? Please describe.
After we're able to create full monitoring stack from che-operator, we should make it the default. 

### Describe the solution you'd like
If the global monitoring flag is enabled `metrics.enable: true`, install full monitoring stack. This would mean to set these defaults:
```
metrics:
  prometheus:
    enable: true
  prometheusServicemonitor:
    enable: true

  grafana:
    enable: true
  grafanaDashboard:
    enable: true
  grafanaDatasource:
    enable: true
```

This should ensure that setting `metrics.enable: true` is enough to install Prometheus and Grafana with all configuration needed to monitor che server and workspaces. `prometheus-operator` and `grafana-operator` are still up to admins and we're not installing or managing them.

### Additional context
these tasks must be done:
[che-operator] - enable che-server monitoring endpoint #15210
[che-operator] - create ServiceMonitor and GrafanaDashboard when CRDs available and monitoring enabled #15211
[che-operator] - install Prometheus with Prometheus CR #15212
[che-operator] - install Grafana with Grafana CR #15299

epic: https://github.com/eclipse/che/issues/15046
analysis: https://github.com/eclipse/che/issues/15136 proposal v3 https://github.com/eclipse/che/issues/15136#issuecomment-557533522
