### ISSUE TITLE
We should propose to fix workspaces terminating containers

### ISSUE THREAD

**Issue by l0rd** [eclipse-che/che#15348]
### Is your enhancement related to a problem? 

If a user adds a terminating container as a workspace component but forget to override its entrypoint, the workspace will fail to start (for example #14781).

### Describe the solution you'd like

I think we could do a couple of things to improve the UX:
1. Che can identify if a workspace is failing to start because of a terminating container and show an interactive dialog to the user proposing to automatically fix the container entrypoint and restart the workspace
2. Add an attribute `makeNonTerminating` to the devfile components that, if set to true, would override the entrypoint(s) with `tail -f /dev/null`. That make it easier to make a component non terminating then manually adding the entrypoint.

### Additional context

An example of such an error can be reproduced using this simple devfile

```yaml
apiVersion: 1.0.0
metadata:
  name: terminating
components:
  - type: dockerimage
    image: maven
    memoryLimit: 256M
```

And [using a factory](http://che.openshift.io/f?url=https://gist.githubusercontent.com/l0rd/d48deda277b716daf2fb83fb6e00b859/raw/bb72b78f2b38770eb6c54041e7219fa288cc5577/devfile.yaml)
