### ISSUE TITLE
Run vsx in same container if the container specs match

### ISSUE THREAD

**Issue by benoitf** [eclipse-che/che#15373]
### Is your enhancement related to a problem? Please describe.
As part of https://github.com/eclipse/che/issues/15272 to add support of VS Code Extension Pack, there is a need to have several VS Code extensions running in the same container.

### Describe the solution you'd like
Plug-in broker should use only one container for all VS Code extensions specified in a meta.yaml if the plug-in sidecar image is the same.

Example of current meta.yaml for `redhat/java11`:
```
...
spec:
  containers:
    - image: "docker.io/eclipse/che-remote-plugin-runner-java11:next"
      name: vscode-java
      memoryLimit: "1500Mi"
      volumes:
      - mountPath: "/home/theia/.m2"
        name: m2
  extensions:
    - https://github.com/microsoft/vscode-java-debug/releases/download/0.20.0/vscode-java-debug-0.20.0.vsix
    - https://download.jboss.org/jbosstools/static/jdt.ls/stable/java-0.50.0-1825.vsix
```

so if there is VS Code yaml with
```
repository: https://github.com/redhat-developer/vscode-xml
category: Language
firstPublicationDate: "2019-10-28"
spec:
  containers:
    - image: "docker.io/eclipse/che-remote-plugin-runner-java11:next"
      name: vscode-xml
      memoryLimit: "768Mi"
  extensions:
    - https://github.com/redhat-developer/vscode-xml/releases/download/0.9.1/redhat.vscode-xml-0.9.1.vsix
```

at the end, we should have only one container using the image `docker.io/eclipse/che-remote-plugin-runner-java11:next` and 3 vsix files will be provided in this container.

Note:
It works only if there is only one container defined or if we use `spec/container` instead of `spec/containers`

About the memory limit, for now it could be average or sum of memoryLimit

### Describe alternatives you've considered
None

### Additional context

JDT.ls need to have access to other jars files that are provided through VS code extensions.
Also some VS Code extensions may depend on other Extensions at runtime
