### ISSUE TITLE
Add type “Che plugin pack” in plug-in broker

### ISSUE THREAD

**Issue by benoitf** [eclipse-che/che#15377]
### Is your enhancement related to a problem? Please describe.
Today, it's possible to have `VS Code Extension` type with a set of vsix files and all the vsix files are loaded in the given container.

But as `VS Code extensions` may have dependencies to others, it's better to depend on a list of other plug-ins.

For example, we could define a `git` `Che plugin pack` that could depend on several VS Code extensions.
So a user could pick-up one `VS Code extension` or select a list or if the user is toggling the pack, all plug-ins are selected.

### Additional context
```yaml
publisher: che
name: git-extension-pack
version: 1.0.0
type: Che Plugin Pack
displayName: Set of nice git VS Code extensions
title: Git Extension Pack
description: Set of nice git VS Code extensions
icon: https://www.eclipse.org/che/images/logo-eclipseche.svg
category: SCM
spec:
  dependencies:
    -id: git/lens/latest
    -id: git/history/latest
    -id: git/gitignore/latest
    -reference: https://gist....
```

### Describe alternatives you've considered
We could replace `dependencies` by something else.

note: the type is Che Plugin and not specific to `VS Code` as it's generic enough to be just an alias / set of other plug-ins and it can be applied to all plug-ins.
