### ISSUE TITLE
Allow for different ingress controller (e.g. octavia)

### ISSUE THREAD

**Issue by mclegrand** [eclipse-che/che#15383]
### Is your enhancement related to a problem? Please describe.
I'm trying to install eclipse che in a cluster created in an openstack cloud by [magnum](https://wiki.openstack.org/wiki/Magnum). There is a nice integration between Magnum and Kubernetes with a cloud controller, and an ingress controller is integrated to provide external IPs from [octavia](https://wiki.openstack.org/wiki/Octavia). However, I've found that ingresses in eclipse che always had `kubernetes.io/ingress.class: nginx` (cf [here](https://github.com/eclipse/che/blob/3538ea4b33fc886d1e7b3039e490ea67879ab7f1/deploy/kubernetes/helm/che/templates/ingress.yaml#L15) for instance)

### Describe the solution you'd like

* ### A setting to make eclipse che work on an openstack-started cluster

* Work with an ingress controller other than nginx (in this case, octavia)

* create the ingress before the rest, to get its ip, as it's dynamically allocated by octavia from a pool, and allow using it as $ip.nip.io afterwards.

* Do not create lots of ingresses but edit the one created with the external IP (for external-facing services)

<details>
  <summary>I could launch che with this ingress:</summary>
  To be more precise for anyone seeking to reproduce this,  I create the ingress, then I *edit* it to fix the hosts with the IP given by octavia, *then* I create the che cluster so that the services pick the ingress. NB: As explained below, it works to launch che, but not to use it, as nginx ingresses get created on the fly for workspaces.
</details>

```yaml
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: openstack
    octavia.ingress.kubernetes.io/internal: "false"
  creationTimestamp: 2019-11-26T16:12:24Z
  name: che-ingress
  namespace: che
spec:
  rules:
  - host: che-che.REDACTED.nip.io
    http:
      paths:
      - backend:
          serviceName: che-host
          servicePort: 8080
        path: /
  - host: devfile-registry-che.REDACTED.nip.io
    http:
      paths:
      - backend:
          serviceName: devfile-registry
          servicePort: 8080
        path: /
  - host: plugin-registry-che.REDACTED.nip.io
    http:
      paths:
      - backend:
          serviceName: plugin-registry
          servicePort: 8080
        path: /
  - host: keycloak-che.REDACTED.nip.io
    http:
      paths:
      - backend:
          serviceName: keycloak
          servicePort: 5050
        path: /

```

which yields : 
```bash
ubuntu@bionic-kubectl:~$  kubectl get ingress -n che
NAME          HOSTS                                                                                                                               ADDRESS           PORTS     AGE
che-ingress   che-che.REDACTED.nip.io,devfile-registry-che.REDACTED.nip.io,plugin-registry-che.REDACTED.nip.io + 1 more...   REDACTED   80        1h

ubuntu@bionic-kubectl:~$ kubectl describe ingress -n che
Name:             che-ingress
Namespace:        che
Address:          REDACTED
Default backend:  default-http-backend:80 (<none>)
Rules:
  Host                                         Path  Backends
  ----                                         ----  --------
  che-che.REDACTED.nip.io               
                                               /   che-host:8080 (<none>)
  devfile-registry-che.REDACTED.nip.io  
                                               /   devfile-registry:8080 (<none>)
  plugin-registry-che.REDACTED.nip.io   
                                               /   plugin-registry:8080 (<none>)
  keycloak-che.REDACTED.nip.io          
                                               /   keycloak:5050 (<none>)
Annotations:
Events:  <none>
```

* Check the presence of a working StorageClass
(a little bit unrelated but I spent days making persistent volumes work)
```yaml
 apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: standard
  annotations:
    storageclass.beta.kubernetes.io/is-default-class: "true"
  labels:
    kubernetes.io/cluster-service: "true"
    addonmanager.kubernetes.io/mode: EnsureExists
provisioner: kubernetes.io/cinder
allowedTopologies:
- matchLabelExpressions:
  - key: failure-domain.beta.kubernetes.io/zone
    values:
    - nova
#volumeBindingMode: WaitForFirstConsumer
```
<details>
  <summary>(to anyone seeking to reproduce this)</summary>
By default, magnum does not set the zone on the nodes, make sure your nodes have 
      metadata -> label -> failure-domain.beta.kubernetes.io/zone: nova set in addition to the /region, or you will get volume creation issues.
</details>

### Describe alternatives you've considered
Alternatives was doing the manual work outlined above, which worked to create a running instance of che, but which was ultimately useless : when creating a workspace, ingresses get spawned which also have the nginx flag and they obviously fail (they would have to add their 7 lines of config to the working ingress). I did not yet consider using two ingress controllers (nginx+octavia) as I'm not sure how they will interact or pick the floating octavia external IP. 

### Additional context
REDACTED is a public internet-facing IP.
