### ISSUE TITLE
devfile verifier/saver put the argument before the command

### ISSUE THREAD

**Issue by agocorona** [eclipse-che/che#15484]
In my devfile, I have:

```
components:
  - id: eclipse/che-theia/latest
    type: cheEditor
  - mountSources: true
    command:
      - sleep
      - infinity
```

but when I touch the devfile, half of the time, che edit it and reverse the order of command:

```
components:
  - id: eclipse/che-theia/latest
    type: cheEditor
  - mountSources: true
    command:
      - Infinity
      - sleep
```
That happens even if if I write it as   `command=['sleep','infinity']`
