### ISSUE TITLE
Document Airgap Process for NPM

### ISSUE THREAD

**Issue by tsmaeder** [eclipse-che/che#15501]
Test and document the process of setting up an airgap solution for NPM. In particular,  configure a workspace based on our default nodejs devfile to use a npm repository that uses a self-signed certificate.

**Comment by tsmaeder** [comment]
Instructions should be attached to this issue.

**Comment by nickboldt** [comment]
Related: https://github.com/eclipse/che/issues/14857

**Comment by sunix** [comment]
Npm airgap devfile
Having that you have a remote NPM private registry and the npm  https://registry.npmjs.org. is not accessible from your network.

In your npm project devfile:


1. Zip your certificate and make it available through http to your workspace (tls.crt in our example).
2. Import your zip into the workspace from the devfile:
   ```
   - source:
      type: zip
      location: 'https://github.com/sunix/che-quarkus-demo/releases/download/nexus/config-nexus.zip'
    name: config-nexus
   ```
3. Add to the component where the npm commands will be executed, providing your npm registry location and the certificate location previously downloaded
  ```
   env:
    - name: NODE_EXTRA_CA_CERTS
      value: "/projects/config-nexus/tls.crt"
    - name: NPM_CONFIG_REGISTRY
      value: "https://snexus-airgap.apps.acme.com/repository/npm-proxy/"
  ```
