### ISSUE TITLE
Workspace does not start when using One namespace per user strategy strategy

### ISSUE THREAD

**Issue by svkr2k** [eclipse-che/che#15557]
Please refer to https://github.com/eclipse/che-docs/blob/master/src/main/pages/che-7/installation-guide/proc_configuring-namespace-strategies.adoc#one-namespace-per-user-strategy

I tried to setup che for One namespace per user strategy as shown below. Also, please note that I will be needing only one workspace per user.

In `che.properties`:
```
che.infra.kubernetes.namespace=
che.infra.kubernetes.namespace.default=<username>-che
che.infra.kubernetes.namespace.allow_user_defined=true
che.infra.kubernetes.pvc.strategy=common
che.infra.kubernetes.pvc.access_mode=ReadWriteOnce
che.infra.kubernetes.pvc.wait_bound=true
```

In `che/assembly/assembly-wsmaster-war/src/main/webapp/WEB-INF/classes/che/multiuser.properties`:
```
che.limits.user.workspaces.count=1
```

In `che-7.5.1/deploy/kubernetes/helm/che/values.yaml`
```
global:
  cheWorkspacesNamespace: "<username>-che"
  cheWorkspacesPVCStrategy: "common"
```

In `che-7.5.1/deploy/kubernetes/helm/che/templates/configmap.yaml`:
```
  CHE_INFRA_KUBERNETES_NAMESPACE: ""
  CHE_INFRA_KUBERNETES_NAMESPACE_DEFAULT: {{ .Values.global.cheWorkspacesNamespace | quote}}
  CHE_INFRA_KUBERNETES_PVC_STRATEGY: "{{ .Values.global.cheWorkspacesPVCStrategy }}"
```

Install che:
```
helm upgrade --install che --force --namespace che \
  --set global.cheDomain=mydomain.com \
  --set global.cheWorkspacesNamespace='<username>-che' \
  --set global.ingressDomain=mydomain.com \
  --set cheimage=<myregistry>/testorg/che-server:latest \
  -f /home/ubuntu/src/che-7.5.1/deploy/kubernetes/helm/che/values/tls.yaml \
  -f /home/ubuntu/src/che-7.5.1/deploy/kubernetes/helm/che/values/multi-user.yaml \
  /home/ubuntu/src/che-7.5.1/deploy/kubernetes/helm/che/
```

```
$ kubectl describe cm che -n che | grep -A 2 NAMESPACE
CHE_INFRA_KUBERNETES_NAMESPACE:
----

CHE_INFRA_KUBERNETES_NAMESPACE_DEFAULT:
----
<username>-che
```

In browser, after I login, i try to create my first workspace. The following is the log with errors shown:
```
AttachVolume.Attach succeeded for volume "pvc-5bf1584a-2217-11ea-acba-029ec662a75d" 
Container image "eclipse/che-init-plugin-broker:v0.24" already present on machine
Created container
Started container
Cleaning /plugins dir
Starting Init Plugin Broker
Container image "eclipse/che-unified-plugin-broker:v0.24" already present on machine
Created container
Started container
Unified Che Plugin Broker
List of plugins and editors to install
- eclipse/my-rest-server-plugin/0.0.1 - Debug container.
- cherxp/che-ide/7.4.0 - IDE contianer
Starting Che plugins and editor processing
Starting VS Code and Theia plugins processing
All plugins have been successfully processed
Error: Failed to run the workspace: "Failure executing: POST at: https://100.64.0.1/api/v1/namespaces/r1-che/services. Message: services "my-rest-server" already exists. Received status: Status(apiVersion=v1, code=409, details=StatusDetails(causes=[], group=null, kind=services, name=my-rest-server, retryAfterSeconds=null, uid=null, additionalProperties={}), kind=Status, message=services "my-rest-server" already exists, metadata=ListMeta(_continue=null, resourceVersion=null, selfLink=null, additionalProperties={}), reason=AlreadyExists, status=Failure, additionalProperties={})."
```

Here is devfile:
```
---
apiVersion: 1.0.0
metadata:
  name: xpress
components:
  -
    type: cheEditor
    reference: https://raw.githubusercontent.com/testreg/my-plugin-registry/master/meta.yaml
  -  
    type: chePlugin
    reference: https://raw.githubusercontent.com/testreg/my-plugin-registry/master/meta-my-rest-server.yaml
```

Please help me setup che. Thank you in advance.

**Comment by tolusha** [comment]
@svkr2k 
Is it the same https://github.com/eclipse/che/issues/15440 ?

**Comment by svkr2k** [comment]
Thank you, @tolusha. #15440 is related to chectl.
This issue seems to be there when we install che using helm.

**Comment by svkr2k** [comment]
any suggestions on workaround (till this issue gets resolved) will be very helpful.

**Comment by sleshchenko** [comment]
@svkr2k https://raw.githubusercontent.com/cherxp/my-plugin-registry/master/meta-my-rest-server.yaml is not available for me. Could you provide your plugin configuration?

**Comment by svkr2k** [comment]
Thank you, @sleshchenko . Here is the yaml file `https://raw.githubusercontent.com/cherxp/my-plugin-registry/master/meta-my-rest-server.yaml`:

```
apiVersion: v2
publisher: eclipse
name: my-rest-server-plugin
version: 0.0.1
type: Che Plugin
displayName: My rest Service
title: Che rest Service Plugin
description: Debug container.
icon: https://www.eclipse.org/che/images/logo-eclipseche.svg
repository: https://github.com/eclipse/che-machine-exec/
firstPublicationDate: "2019-11-06"
category: Other
spec:
  endpoints:
   -  name: "my-rest-server"
      public: true
      targetPort: 8080
      attributes:
      protocol: http
  containers:
   - name: my-rest-server
     image: "879521958254.dkr.ecr.us-east-1.amazonaws.com/myorg1/my-rest-server:latest"
     volumes:
       - mountPath: "/home/projects"
         name: myprojects
     mountSources: true
     ports:
       - exposedPort: 8080
     memoryLimit: "2Gi"
```

**Comment by sleshchenko** [comment]
@svkr2k If it's suitable in your case, you can try to add `discoverable: false` endpoint attribute.
<details>

<summary>Proposed configuration</summary>

```yaml
apiVersion: v2
publisher: eclipse
name: my-rest-server-plugin
version: 0.0.1
type: Che Plugin
displayName: My rest Service
title: Che rest Service Plugin
description: Debug container.
icon: https://www.eclipse.org/che/images/logo-eclipseche.svg
repository: https://github.com/eclipse/che-machine-exec/
firstPublicationDate: "2019-11-06"
category: Other
spec:
  endpoints:
   -  name: "my-rest-server"
      public: true
      targetPort: 8080
      attributes:
        discoverable: false
        protocol: http
  containers:
   - name: my-rest-server
     image: "879521958254.dkr.ecr.us-east-1.amazonaws.com/myorg1/my-rest-server:latest"
     volumes:
       - mountPath: "/home/projects"
         name: myprojects
     mountSources: true
     ports:
       - exposedPort: 8080
     memoryLimit: "2Gi"
```

</details>

More info about it you can find https://github.com/eclipse/che-plugin-registry, not sure if it contains accurate description )
