### ISSUE TITLE
A tutorial to create a multi(double)-machine workspace for ".Net Core" and "MSSQL".

### ISSUE THREAD

**Issue by mustafa-yilmaz-zz** [eclipse-che/che#15556]
### Is your task related to a problem? Please describe.

It is related to uncertainty about creating custom multi(double)-machine workspaces

### Describe the solution you'd like

I personally think that having a step by step tutorial would be a sufficient solution.

### Describe alternatives you've considered

None.

### Additional context

Hello all,

If it won't be spam I would kindly like to share my humble wish here.

Despite the various explanations on the internet regarding creating custom stacks for Eclipse Che, I still can not understand how to create a custom multi (double)-machine workspace (one for the application server and the other one for the database server) for an app to build through ".Net Core" and "MSSQL".  I would really love to have a step by step tutorial for that.

Might it be possible for me to get some extra help from someone? Thanks a lot in advance.

**Comment by tolusha** [comment]
I recommend to start looking at our sample [1] and devfile documentation [2]

[1] https://github.com/eclipse/che-devfile-registry/blob/master/devfiles/java-mysql/devfile.yaml
[2] https://redhat-developer.github.io/devfile/

**Comment by tolusha** [comment]
I would be really nice if you are able to contribute.

**Comment by mustafa-yilmaz** [comment]
> I recommend to start looking at our sample [1] and devfile documentation [2]
> 
> [1] https://github.com/eclipse/che-devfile-registry/blob/master/devfiles/java-mysql/devfile.yaml
> [2] https://redhat-developer.github.io/devfile/
> 
> Try the sample on che.openshift.io:
> https://che.openshift.io/f?url=https://raw.githubusercontent.com/redhat-developer/devfile/master/getting-started/spring-petclinic/devfile.yaml

I checked those tutorials and tried to customize the sample but I did not achieve to build my own for MSSQL . I would be so glad to get some additional help for my wish.

>It would be really nice if you are able to contribute.

I already started to prepare something at https://medium.com/@mustafa.yilmaz/how-to-develop-blazor-web-apps-using-just-a-web-browser-part-1-64d72563419e.

I am able to customize the sample for ".Net Core"  but as I said, I couldn't do the same for "MSSQL" so far.

Thanks once again.

**Comment by tolusha** [comment]
@mustafa-yilmaz 
What kind of issues do you have?

/cc @svor

**Comment by mustafa-yilmaz** [comment]
> @mustafa-yilmaz
> What kind of issues do you have?
> 
Just I can not fill in (build) the "devfile" for an MSSQL Database server. In somehow, all my tries returned errors so far. Perhaps some issues are related to some missing points at Microsoft side, just I am not sure since I am worse than a newbie for the sense of "devfile" / dockers /containers / Kubernetes etc. 

Having a ready blank double-machine workspace would be also a good alternative solution for such an issue to install wanted stuff (infrastructure) through terminal screens.

**Comment by IveJ** [comment]
Hi Mustafa,

Plz check this for customize devfile and seeking to register resources you
need that justify in devfile:
https://www.eclipse.org/che/docs/che-7/editing-a-devfile-and-plug-in-at-runtime/

Nice.

**Comment by tolusha** [comment]
@mustafa-yilmaz 
Try to start from the dockerfile bellow.
Check if server is available from another container, configure it using env variables, add some project to use the server.
```
metadata:
  name: mssql
components:
  - id: redhat/java/latest
    memoryLimit: 1280MiB
    type: chePlugin
  - mountSources: true
    endpoints:
      - name: 8080/tcp
        port: 8080
    memoryLimit: 700Mi
    type: dockerimage
    volumes:
      - name: m2
        containerPath: /home/user/.m2
    alias: tools
    image: 'quay.io/eclipse/che-java8-maven:nightly'
    env:
      - value: ''
        name: MAVEN_CONFIG
      - value: >-
          -XX:MaxRAMPercentage=50.0 -XX:+UseParallelGC -XX:MinHeapFreeRatio=10
          -XX:MaxHeapFreeRatio=20 -XX:GCTimeRatio=4
          -XX:AdaptiveSizePolicyWeight=90 -Dsun.zip.disableMemoryMapping=true
          -Xms20m -Djava.security.egd=file:/dev/./urandom -Duser.home=/home/user
        name: JAVA_OPTS
      - value: $(JAVA_OPTS)
        name: MAVEN_OPTS
  - mountSources: true
    endpoints:
      - name: db
        port: 1433
        attributes:
          discoverable: 'true'
          public: 'false'
    command:
      - sleep
    args:
      - infinity
    memoryLimit: 1500Mi
    type: dockerimage
    alias: mysql
    image: mcr.microsoft.com/mssql/server
apiVersion: 1.0.0
```
