### ISSUE TITLE
Duplicate directory specifying multiple projects in a devfile.

### ISSUE THREAD

**Issue by Mbd06b** [eclipse-che/che#15607]
Is there a way with a multi-project devfile to not duplicate the root of a project already defined in source control? 

Gitlab / github
![image](https://user-images.githubusercontent.com/12649222/71792457-6ae7db80-2ffe-11ea-88da-db34a7e3ff42.png)

devfile ( it's a bit of a mess, but I'm trying different things) 

```
projects:
  - name: parent
    source:
      location: 'https://gitlab.example.com/User/project.git'
      type: git
      sparseCheckoutDir: /parent/
    clonePath: projects
  - name: config-service
    source:
      location: 'https://gitlab.example.com/User/project.git'
      type: git
      sparseCheckoutDir: /config-service/
    clonePath: ''
  - name: gateway-service
    source:
      location: 'https://gitlab.example.com/User/project.git'
      type: git
      sparseCheckoutDir: /gateway-service/
    clonePath: projects
  - name: discovery-service
    source:
      location: 'https://gitlab.example.com/User/project.git'
      type: git
      sparseCheckoutDir: /discovery-service*
```

Workspace RESULT: Duplicated project root directory when using sparseCheckoutDir to add a project in source control.
![image](https://user-images.githubusercontent.com/12649222/71792222-8acacf80-2ffd-11ea-96a6-a15de9d98cbf.png)

che version 7.6.0
