### ISSUE TITLE
Devfile Editor does not suggest all action types

### ISSUE THREAD

**Issue by tsmaeder** [eclipse-che/che#15611]
It seems the schema we use to drive the devfile editor is not functioning well for content assist in some cases: 

1. In a devfile in the dashboard, add a command like so:
```
commands:
  - name: zoz
    actions:
      - name: bla
        type: <cursor position> 
```
2. invoke content assist for the `type` field.
3. observe: you only get `exec` suggested as the possible type. However, there are other types like `vscode-launch` are also admissible at this point and should be suggested.
