### ISSUE TITLE
How to restore workspaces when restarting Che?

### ISSUE THREAD

**Issue by wn092943** [eclipse-che/che#1561]
hi,
Steps to reproduce:
1. start che through executing `bin/che.bat`
2.visit `localhost:8080`
3.create a new workspace and create a simple java project
4.stop che through closing the command shell where is executing `bin/che.bat`
5.execute `bin/che.bat` again
6.can't find any workspace and project when visiting `localhost:8080`

 I find the size of file `.docker/macine/macines/che/disk.vmdk` increase when I create workspace, so I guess some information about workspace have been stored, so how to restore workspace when I restart che?

I run che on Wins 7, and the version of Che is 4.3.4(I try to use other version but get same result).

Thanks in advance.

**Comment by ddementieva** [comment]
Can you try starting and stopping workspace and then shutting down the server?

**Comment by wn092943** [comment]
@ddementieva I can successfully run and stop workspace if i don't stop or restart che server.
However, I also can't find any workspaces when I restart che server after starting and stopping workspace. any ideas I missed?

**Comment by ddementieva** [comment]
Can you check if there is anything in the /che/storage directory?

**Comment by wn092943** [comment]
@ddementieva There is a file `preferences.json`, and when I create a new workspace this file can record some contents about the workspace I created, like 
`\"workspacexhx8euul56epaze9\":{\"actions\":[{\"parameters\":{\"showHiddenFiles\":\"false\"}, \"id\":\"showHideHiddenFiles\"}]}}, \"recentWorkspaceId\":\"workspacexhx8euul56epaze9\"`. `workspacexhx8euul56epaze9` is the id of workspace I created just now.
When I stop che and restart che, the content of  `preferences.json` has no change, but the dashboard still can't show any workspaces or projects.

**Comment by ghost** [comment]
Can you give it a try with a nightly build https://install.codenvycorp.com/che/eclipse-che-nightly.zip?

**Comment by wn092943** [comment]
@eivantsov I restore workspaces successfully. Thanks for your advice.
By the way, after creating workspaces, only executed `che stop` command, these workspaces can be restored. 
If I restart che server using `che start` or `che run` command, skiping the step that execute `che stop` command, workspaces aren't restored.

**Comment by ghost** [comment]
But how do you then terminate the process? Yes, I think that the server needs to be gracefully stopped for the workspaces to be saved into local storage.

**Comment by mhworth** [comment]
I have the same issue on Mac while using Docker for Mac. Perhaps the problem is that I'm not sure how to gracefully shutdown the server so the workspaces are restored. In general, it'd be nice if we didn't have to worry about graceful shutdown, as unexpected shutdowns are pretty likely on a workstation, and I'd hate to lose all my workspaces if that were to happen.

Note: I'm using the nightly build; I couldn't get the stable build to work with Docker for Mac.

Here's what I'm doing:

docker-compose.yml:

```
che:
   image: codenvy/che:nightly
   command: --remote:${DOCKER_VM_IP}
   restart: always
   ports:
   - "8080:8080"
   environment:
     CHE_LOCAL_CONF_DIR: /container
   volumes:
     - /var/run/docker.sock:/var/run/docker.sock
     - /home/user/che/lib:/home/user/che/lib-copy
     - /home/user/che/workspaces:/home/user/che/workspaces
     - /home/user/che/storage:/home/user/che/storage
     - /home/user/che:/container
   container_name: che
```

Shell commands:

```
# Grabs the IP address of the Xhyve VM
export DOCKER_VM_IP=$(docker run --rm --net host alpine sh -c "ip a show eth0" | \
                    grep 'inet ' | cut -d/ -f1 | awk '{ print $2}')

# Sets the loopback alias for this IP
# You will be asked for your root password
sudo ifconfig lo0 alias $DOCKER_VM_IP

# Prints the IP address
echo $DOCKER_VM_IP

# Bring up Che
docker-compose up -d

# Create some workspaces, work, etc....

# Shut down Che
docker-compose stop

# Start it up again
docker-compose start

# No more workspaces
```

There is a preferences.json and workspaces are present in /home/user/che, but it's not picking them up on restart for whatever reason. Am I doing something wrong in the way I'm setting it up or something?
