### ISSUE TITLE
[HTTPS] Using Che with self-signed-certs on OpenShift is frustrating.

### ISSUE THREAD

**Issue by johnmcollier** [eclipse-che/che#15658]
### Describe the bug

I'm running Che 7.6.0 on OCP 4.2, where the cluster's certificates are self-signed. I installed Che from OperatorHub and used the following CheCluster yaml:
```
apiVersion: org.eclipse.che/v1
kind: CheCluster
metadata:
  name: eclipse-che
  namespace: che
spec:
  server:
    cheImageTag: ''
    devfileRegistryImage: ''
    pluginRegistryImage: ''
    tlsSupport: true
    selfSignedCert: true
  database:
    externalDb: false
    chePostgresHostName: ''
    chePostgresPort: ''
    chePostgresUser: ''
    chePostgresPassword: ''
    chePostgresDb: ''
  auth:
    openShiftoAuth: true
    identityProviderImage: ''
    externalIdentityProvider: false
    identityProviderURL: ''
    identityProviderRealm: ''
    identityProviderClientId: ''
  storage:
    pvcStrategy: per-workspace
    pvcClaimSize: 1Gi
    preCreateSubPaths: true
```

In order to properly access Che and create/start/use a workspace, I had to do the following:
1) If I access the Che dashboard immediately after install, I get the following error in my browser:
![Screen Shot 2020-01-10 at 3 19 21 PM](https://user-images.githubusercontent.com/6880023/72183705-9a129a00-33bc-11ea-8204-c42ce126b588.png)

     - To resolve this, I have to go to the Keyloak URL and whitelist its certificate in my browser.

2) Once #1 has been resolved, I can create an account and log in to Che. However, none of the devfiles from the devfile registry will load:
![Screen Shot 2020-01-10 at 3 21 10 PM](https://user-images.githubusercontent.com/6880023/72183793-de059f00-33bc-11ea-8dd0-4b59d6240157.png)

    - As before, the error in the Javascript console indicates that the certificate for the devfile registry is being rejected. So I have to look up the URL of the devfile registry and whitelist it in my browser

3) Once #2 has been resolved, I can create a workspace, but I cannot access it, as the certificates for the workspace's routes need to be whitelisted too
![Screen Shot 2020-01-10 at 3 36 35 PM](https://user-images.githubusercontent.com/6880023/72185456-d34d0900-33c0-11ea-86a3-3814c3cdb885.png)

   - As before, the certificates for that route needs to be whitelisted as well.

This continued for each route in Che I encountered. I ended up needing to whitelist over 10 routes just to get a functioning Che workspace

Now that Theia webviews require HTTPS (https://github.com/eclipse/che/issues/15635, https://github.com/eclipse-theia/theia/pull/6465#issuecomment-557494879), anything that requires WebViews in Che-Theia effectively requires an HTTPS install of Che. 

I know that https://github.com/eclipse/che/issues/15298 and https://github.com/eclipse/che-docs/pull/1007 should help with some of my concerns. But having to indvidually (and manually) add the certificates for the 5+ routes that Che relies on (Or retrieving my cluster's ca.crt) still creates a bad user experience in my opinion. A lot of on-prem installs of Kube & OpenShift will use self-signed certificates, so I wouldn't consider what I'm trying to do here an edge case either. It also makes setting up Che on a local Kubernetes (Minikube, CRC, etc) much more complicated, and thus harder for newcomers to try out.

If I follow the instructions being prepared in https://github.com/eclipse/che-docs/pull/1007, I could generate new certificates and reconfigure the router with those certificates, and add the ca.crt to my browser. But that seems like a ton of work just to use Che with self-signed certs, and I wouldn't necessarily want or be able to change the router's certificates. Furthermore, I would need to share the ca.crt with each user that I wanted to access my Che instance.

Is there any way we can make the setup process for Che with self-signed certs drastically easier on OpenShift? **Ideally I would only need to whitelist the certs once in my browser, and wouldn't have to generate custom certificates (unless I wanted to).**
