### ISSUE TITLE
Ability to mount the same PV across mutiple workspaces (one workspace running at a time)

### ISSUE THREAD

**Issue by davidwindell** [eclipse-che/che#15652]
### Is your enhancement related to a problem? Please describe.
We would like to be able to attach a persistent volume (in our case an EFS volume) that is shared across multiple workspaces on Che. This would allow us to share static assets that are stored on an NFS drive with all workspaces of the same project. We work on large web projects where GBs of media needs to be mounted into the workspace.

### Describe the solution you'd like
It would be great to be able to define this in the devfile, for example:

 ```
   volumes:
      - claimName: pvc-name
        containerPath: "/home/user/media"
 ```
### Describe alternatives you've considered
We thought of using the Kubernetes custom resource section of the devfile but this doesn't seem to work.

**Comment by davidwindell** [comment]
In summary, it would be amazing if we could just attach an existing Kubernetes PersistentVolume to all workspaces, specifying the subpath in the volume to use in the devfile.

 This would make a huge difference to our developers performance as we rely on database backed media storage at the moment to share it amongst workspaces.

**Comment by skabashnyuk** [comment]
@davidwindell that sounds like an interesting use case. Would you like to propose a patch?

**Comment by sleshchenko** [comment]
I wonder if user may want to reconfigure source for all components, like editor/plugins. If yes then what should be a better format:
1. Add an ability to configure/override volumes for all components:
```yaml
components:
- id: eclipse/che-theia/7.10.0
  volumes: #Here are overrides for https://github.com/eclipse/che-plugin-registry/blob/master/v3/plugins/eclipse/che-theia/7.8.0/meta.yaml#L59
    - name: projects
      containerPath: /projects
      subfolder: /${workspaceName}/projects
      claimName: my-claim #probably must be the same across devfile for all `projects` volumes
    - name: plugins
      containerPath: /plugins
      subfolder: /${workspaceName}/plugins
      claimName: my-claim
- id: redhat/java/latest
  volumes:
    - name: projects
      containerPath: /projects
      subfolder: /${workspaceName}/projects
    - name: plugins
      containerPath: /plugins
      subfolder: /${workspaceName}/plugins
- type: dockerimage
  volumes:
    - name: projects
      containerPath: /projects
      subfolder: /${workspaceName}/projects
```
2. Or as an alternative it could be a separate section to tune volumes configuration, like:
```yaml
components:
- id: eclipse/che-theia/7.10.0
  type: cheEditor
- id: redhat/java/latest
  type: chePlugin
- type: dockerimage
  volumes:
    - name: projects
      containerPath: /projects
volumes: #We know which volumes are used in our workspace and tune that here for all components
  - name: project
    pvcSource:
      pvcName: projects
      subfolder: /${workspaceName}/projects
```
