### ISSUE TITLE
How can I set an idle timeout for a workspace while using alternative IDE instead of che-theia in che?

### ISSUE THREAD

**Issue by kellyhyomin** [eclipse-che/che#15747]
## Summary

I am bringing my completely different web IDE into Che.
I attach my plugin meta.yaml file and devfile.yaml file below.
- meta.yaml
```
apiVersion: v2
publisher: popcornsar
name: webio-r19-03
version: latest
type: Che Editor
displayName: AutoSAR Webio R19-03-V3
title: AutoSAR Webio R19-03
description: AutoSAR Webio
icon: https://www.eclipse.org/che/images/logo-eclipseche.svg
category: Editor
repository: https://github.com/AutoSARioDeveloper/docker-autosar-webio
firstPublicationDate: '2019-12-03'
spec:
  endpoints:
    - name: theia
      public: true
      targetPort: 8080
      attributes:
        protocol: http
        type: ide
        discoverable: false
  containers:
    - name: webio
      image: docker.io/popcornsar/autosar-webio:R19-03-v3
      mountSources: true
      ports:
        - exposedPort: 8080
      memoryLimit: 2048Mi
```
- devfile.yaml
```
---
apiVersion: 1.0.0
metadata:
  name: webio
components:
-
  type: cheEditor
  id: popcornsar/webio-r19-03/latest
  alias: webio
```

How can I set an idle timeout for a workspace while using alternative IDE instead of che-theia in che?
Even though I'm writing code in my alternative IDE, the workspace stops when the idletimeout time is up.
