### ISSUE TITLE
PreviewUrl doesn't honor secure attribute of endpoints

### ISSUE THREAD

**Issue by metlos** [eclipse-che/che#15756]
### Describe the bug
If there is a secure endpoint and a custom preview url on command for the same port as the secure endpoint, the preview url exposes the "naked" service, circumventing jwt proxy that should be used to secure the endpoint.

### Che version
 - latest

### Steps to reproduce
1. Deploy the below mentioned devfile
1. Start the workspace
1. Click on the "build & run" command
1. On the "Preview URL" tab, click on the link
1. You can also copy the URL and curl it
1. Notice that the page displays/curl downloads without any authentication

### Expected behavior
The previewUrl should go through the jwt proxy as is configured on the endpoint for the given port

### Additional Context

This is an example devfile:
```yaml
apiVersion: 1.0.0
metadata:
  name: spring-petclinic
projects:
  - name: spring-petclinic
    source:
      type: git
      location: 'https://github.com/che-samples/web-java-spring-petclinic.git'
components:
  - alias: dev
    type: dockerimage
    image: rhche/centos_jdk8
    mountSources: true
    endpoints:
      - name: petclinic-web-server
        port: 8080
        attributes:
          protocol: http
          secure: 'true'
          public: 'true'
          discoverable: 'false'
    memoryLimit: 2048M
commands:
  - name: build_&_run
    actions:
      - type: exec
        component: dev
        command: "cd $CHE_PROJECTS_ROOT/spring-petclinic && mvn clean install && cp $CHE_PROJECTS_ROOT/spring-petclinic/target/*.war $TOMCAT_HOME/webapps/ROOT.war && $TOMCAT_HOME/bin/catalina.sh run 2>&1"
    previewUrl:
      path: "/"
      port: 8080
  - name: stop
    actions:
      - type: exec
        component: dev
        command: "$TOMCAT_HOME/bin/catalina.sh stop 2>&1"
```
