### ISSUE TITLE
Enable some user defined plugins by default when starting a workspace

### ISSUE THREAD

**Issue by themr0c** [eclipse-che/che#15766]
Different users would add different tools/extensions to achieve the same workload.
Usually, users would add their preferred extensions to all of their workspaces.
Currently, there is no way to "always add this additional extension to my workspaces". 
It means that creating a devfile implies reaching a team agreement on stuff that is a personal preference.

It would be nice to enable some user define plugins by default when starting a workspace from a factory

**Comment by themr0c** [comment]
@sunix Here is the issue as requested.

**Comment by l0rd** [comment]
That's a good enhancement @themr0c. I remember that I have discussed that recently with someone but I don't know who. There may be already an issue about that. cc @slemeur

**Comment by l0rd** [comment]
cc @skabashnyuk @ericwill

**Comment by ericwill** [comment]
This makes a lot of sense, for example a good use case would be plugins that are common to all workspaces (git related plugins come to mind).

**Comment by slemeur** [comment]
Definitely +1 ! That's something we've been discussing indeed.

Moving the thinking a bit further, that really comes to the "user preferences and settings". If a user wants to configure some plugins for all his workspaces and these plugins have their own "configuration options" those should be also reused.

The user should have the ability to configure different elements which will be applicable to across all his different workspaces:
- Plugins
- Settings and Configuration (keybinding, themes, fonts, editor config)

As a user, I want to get my preferences shared across my different workspaces so that they are kept in sync and making my developer experience more enjoyable as I'll not have to configure the same things each time I'm using a new workspace.

An example:
- If the user is using the K8S/OpenShift plugin into different workspaces
- The user is likely going to configure information about the K8S/OpenShift cluster(s) he has access to.
- If the user is using multiple workspace, he would prefer to configure once the information about the cluster(s) and get those into all his workspaces.

**Comment by ericwill** [comment]
> As a user, I want to get my preferences shared across my different workspaces so that they are kept in sync and making my developer experience more enjoyable as I'll not have to configure the same things each time I'm using a new workspace.
> 
> An example:
> 
>     * If the user is using the K8S/OpenShift plugin into different workspaces
> 
>     * The user is likely going to configure information about the K8S/OpenShift cluster(s) he has access to.
> 
>     * If the user is using multiple workspace, he would prefer to configure once the information about the cluster(s) and get those into all his workspaces.

This is a really good point. Conversely it would be nice to have an opt-out mechanism -- like in the example above, maybe the user wants one workspace not to follow the "global" settings? Something like a checkbox on workspace creation titled "Ignore global plugin settings" or "Use default plugin settings for this workspace".

**Comment by slemeur** [comment]
Yes exactly ! good point @ericwill

**Comment by azatsarynnyy** [comment]
Just an idea to investigate...
In the context of Che-Code, we can look at how we can use [the VS Code Profiles](https://code.visualstudio.com/docs/editor/profiles) to persist/restore the editor customizations across the user's workspaces.

**Comment by AObuchow** [comment]
> Just an idea to investigate...
In the context of Che-Code, we can look at how we can use [the VS Code Profiles](https://code.visualstudio.com/docs/editor/profiles) to persist/restore the editor customizations across the user's workspaces.


Thank you for the lead @azatsarynnyy :pray: 

I did a bit of initial investigation on VSCode Profiles in Che-Code, here are my current findings:
Using a VSCode profile in Che-Code will automatically install and enable extensions (if they can be found in the plugin registry). If a theme extension is installed and enabled in the profile, Che-Code will use this theme.

You can import a VSCode profile into Che-Code either as a GitHub gist, or as a file.

### VSCode Profiles as Gists in Che-Code
#### Exporting 
Che-Code currently doesn't seem to be able to export profiles as gists. Trying to do so gives the following error:

```
2023-06-09 17:37:04.100 [error] Not Found: HttpError: Not Found
	at /checode/checode-linux-libc/extensions/configuration-editing/dist/configurationEditingMain.js:2:25686
	at processTicksAndRejections (node:internal/process/task_queues:96:5)
	at async Object.saveProfile (/checode/checode-linux-libc/extensions/configuration-editing/dist/configurationEditingMain.js:2:148847)
```


#### Importing
Since Che-Code doesn't currently support exporting profiles, I exported my local VSCode profile as Gist and imported it into Che-Code.

Che-Code was able to successfully import my VSCode profile as a gist. Extensions which were installed on my local VSCode but not available in the plugin registry were logged and skipped (which is nice - you can already directly import your local VSCode profile into Che). 

### VSCode Profiles as files in Che-Code
#### Exporting 
Exporting a profile to a file works as expected, though you have to ensure Che-Code has write permissions for the directory you're exporting to. 

#### Importing
Importing works as expected as well. Currently, I'm experimenting with DWO's automount functionality in order to mount a VSCode profile to all of my Che workspaces. To do so, I've created and applied the following configmap:

```YAML
apiVersion: v1
kind: ConfigMap
metadata:
  name: workspace-vscode-profile
  labels:
    controller.devfile.io/mount-to-devworkspace: "true"
    controller.devfile.io/watch-configmap: "true"
  annotations:
    controller.devfile.io/mount-as: subpath
    controller.devfile.io/mount-path: /home/user/
data:
 test-profile.code-profile: |
    {"name":"test-profile-1","settings":... (rest of .code-profile contents)
```

Then in Che-Code, you can load the profile by clicking on the settings icon in the bottom left -> profiles -> import profile -> Create from profile template file -> type in `/home/user/test-profile.code-profile/` as the path -> ok. It will then display the profile's contents -> click on "Create Profile". You will then be prompted to either overwrite the profile file or create a new one, both options work. Che-Code will get refreshed, and the profile will be loaded.

I wonder if it'd be possible to automate/bypass this UI procedure so that the user could provide their VSCode profile through a secret or configmap and have Che-Code automatically load their profile. That would be really nice. 

As a side note, the [default location for VSCode profiles](https://code.visualstudio.com/docs/editor/profiles#_where-are-profiles-kept) is intended to be `$HOME/.config/Code/User/profiles`

**Comment by AObuchow** [comment]
> I wonder if it'd be possible to automate/bypass this UI procedure so that the user could provide their VSCode profile through a secret or configmap and have Che-Code automatically load their profile. That would be really nice. 

This might be possible without too much effort (hopefully).

@rgrunber brought to my attention that there is a `--profile` CLI option for VSCode. 

```
  --profile <profileName>                    Opens the provided folder or
                                             workspace with the given profile
                                             and associates the profile with
                                             the workspace. If the profile
                                             does not exist, a new empty one
                                             is created. A folder or workspace
                                             must be provided for the profile
                                             to take effect.
```

In theory, we should be able to modify the [entrypoint](https://github.com/che-incubator/che-code/blob/main/build/scripts/entrypoint.sh#L38) of Che-Code to add the `--profile` argument and supply it an environment variable that points to the profile's path. 

Something like:
`/checode-linux-musl/node /checode-linux-musl/out/server-main.js --host "${CODE_HOST}" --port 3100 --profile "${PROFILE_PATH}"`

Then, you could mount your profile with a configmap or secret, as previously shown:
```YAML
apiVersion: v1
kind: ConfigMap
metadata:
  name: workspace-vscode-profile
  labels:
    controller.devfile.io/mount-to-devworkspace: "true"
    controller.devfile.io/watch-configmap: "true"
  annotations:
    controller.devfile.io/mount-as: subpath
    controller.devfile.io/mount-path: /home/user/
data:
 my-profile.code-profile: |
    {"name":"my-vscode-profile","settings":... (rest of .code-profile contents)
```

And set the $PROFILE_PATH environment variable in a second configmap:

```YAML
apiVersion: v1
kind: ConfigMap
metadata:
  name: workspace-vscode-profile-path
  labels:
    controller.devfile.io/mount-to-devworkspace: "true"
    controller.devfile.io/watch-configmap: "true"
  annotations:
    controller.devfile.io/mount-as: env
data:
  PROFILE_PATH: /home/user/my-profile.code-profile
```

I haven't had a chance to test this yet.
