### ISSUE TITLE
[Dogfooding] Cannot access my workspace

### ISSUE THREAD

**Issue by vitaliy-guliy** [eclipse-che/che#15787]
### Describe the bug

I'm using che.openshift.io for dogfooding. My workspace has been created two weeks ago and has been restarted dozens of times due to idle timeout and changing the devfile.
This morning it become inaccessible.
I don't remember exactly, but it could have happened after login to che.openshift.io in another browser tab.
After that my working Theia become unstable and after refreshing the browser tab I got a message that my workspace is already running and cannot be started.
Having switched to the dashboard, I can see that my workspace is stopped. But under the hood it stay working.

I even cannot start another workspace due to the limit on running workspaces.
```
Error: Failed to run the workspace: "Unrecoverable event occurred: 'FailedCreate', 'Error creating: pods "workspace54hbwwq23bfudgw7.go-cli-7ffb9dbc7c-7rwm8" is forbidden: exceeded quota: compute-resources, requested: limits.cpu=3245m,limits.memory=1743028224, used: limits.cpu=15190m,limits.memory=8157003776, limited: limits.cpu=16,limits.memory=8Gi', 'workspace54hbwwq23bfudgw7.go-cli-7ffb9dbc7c'"
```

It's critical issue, as the user can loose his sources. 

### Steps to reproduce
Difficult to say. In general, just use che.openshift.io for daily work.
You can also open another browser tab and try to logout/login to che.openshift.io.

Devfile, which I'm using for my workspace
```yaml
apiVersion: 1.0.0
metadata:
  name: che-theia-all
projects:

  - name: theia
    source:
      location: 'https://github.com/vitaliy-guliy/theia.git'
      type: git
      branch: master

  - name: che-theia
    source:
      location: 'https://github.com/eclipse/che-theia.git'
      type: git
      branch: master

components:
  - id: redhat/vscode-yaml/latest
    type: chePlugin

  - mountSources: true
    endpoints:
      - name: theia-dev-flow
        attributes:
          protocol: http
          public: 'true'
        port: 3010
    memoryLimit: 3Gi
    type: dockerimage
    alias: che-dev
    image: 'vgulyy/che-theia-dev:osio1'

  - id: che-incubator/typescript/latest
    memoryLimit: 2048M
    type: chePlugin

  - id: eclipse/che-machine-exec-plugin/latest
    type: chePlugin

  - id: eclipse/che-theia/latest
    memoryLimit: 2Gi
    type: cheEditor
    alias: theia-editor

commands:
  - name: '0. List projects'
    actions:
      - component: che-dev
        workdir: /projects
        type: exec
        command: |
          echo '# ls -la /projects'; \
          echo sleep 1; \
          ls -la; \
          echo -e "\e[32mDone\e[0m"

  - name: '1. Prepare theia-* dirs'
    actions:
      - component: theia-editor
        workdir: /projects
        type: exec
        command: |
          mkdir /projects/theia-default-plugins; \
          mkdir /projects/theia-plugins; \
          mkdir /projects/theia-projects-dir; \
          cd /default-theia-plugins; \
          cp * /projects/theia-default-plugins/; \
          echo -e "\e[32mDone\e[0m"

  - name: '2. Sync'
    actions:
      - component: che-dev
        workdir: /projects
        type: exec
        command: |
          rsync -rtv --exclude='node_mobules' /projects/theia/ /tmp/theia/; \
          echo -e "\e[32mDone\e[0m"

  - name: '3. Init che:theia'
    actions:
      - component: che-dev
        workdir: /tmp/theia
        type: exec
        command: |
          che:theia init; \
          echo -e "\e[32mDone\e[0m"

  - name: '4. Build che:theia'
    actions:
      - component: che-dev
        workdir: /tmp/theia
        type: exec
        command: |
          yarn; \
          echo -e "\e[32mDone\e[0m"

  - name: '5. Launch'
    actions:
      - component: che-dev
        workdir: /tmp/theia/examples/assembly
        type: exec
        command: |
          export CHE_PROJECTS_ROOT="/projects/theia-projects-dir"; \
          export THEIA_DEFAULT_PLUGINS="local-dir:///projects/theia-default-plugins"; \
          export THEIA_PLUGINS="local-dir:///projects/theia-plugins"; \
          export THEIA_PLUGIN_ENDPOINT_DISCOVERY_PORT='2506'; \
          yarn theia start /projects/theia-projects-dir --hostname=0.0.0.0 --port=3010; \
          echo -e "\e[32mDone\e[0m"
```

### Expected behavior
The workspace must be working.

### Runtime
   - [x] che.openshift.io

### Screenshots

Screencast
https://www.youtube.com/watch?v=QbIllmqNyg8

![Screenshot from 2020-01-22 13-19-18](https://user-images.githubusercontent.com/1655894/72901508-95da6b00-3d32-11ea-934d-7f6e7c88b3bd.png)

![Screenshot from 2020-01-22 13-26-48](https://user-images.githubusercontent.com/1655894/72901517-9bd04c00-3d32-11ea-8883-59e5a5c2965e.png)

![Screenshot from 2020-01-22 13-27-56](https://user-images.githubusercontent.com/1655894/72901544-a7bc0e00-3d32-11ea-9117-888156522070.png)

URI to my workspace
https://che.openshift.io/dashboard/#/ide/vgulyy/che-theia-all

URI to openshift console
https://console.starter-us-east-2.openshift.com/console/project/vgulyy-che/overview

Workspace ID: workspacemibz4bsd0u4mlwff

**Comment by ibuziuk** [comment]
@skabashnyuk  some logs, any ideas?
` Runtime for workspace 'workspacemibz4bsd0u4mlwff' is requested but there is no cached one. Recovering it.`
`Unable to generate signature keypair for ws workspacemibz4bsd0u4mlwff. Cause: Signature key pair for workspace 'workspacemibz4bsd0u4mlwff' already exists`

**Comment by vitaliy-guliy** [comment]
After removing the workspace and creating next one using the same devfile I got a message that quota is exceeded

![Screenshot from 2020-01-23 11-28-16](https://user-images.githubusercontent.com/1655894/72973487-05556680-3dd6-11ea-942f-605efdf69c13.png)

**Comment by vitaliy-guliy** [comment]
The same with this devfile
```
metadata:
  name: mini-ws
projects:
  - name: che-theia
    source:
      location: 'https://github.com/eclipse/che-theia.git'
      type: git
      branch: master
apiVersion: 1.0.0
```
