### ISSUE TITLE
[devworkspace] Revise DevWorkspace CR structure

### ISSUE THREAD

**Issue by sleshchenko** [eclipse-che/che#15783]
### Is your task related to a problem? Please describe.
DevWorkspace Controller POC has DevWorkspace CR[[1](https://github.com/che-incubator/che-workspace-crd-operator/blob/master/samples/java-mysql.yaml)] that is slightly different from one proposed as part of DevWorkspace API[[2](https://github.com/che-incubator/devworkspace-api)].

Ideally, it would make DevWorkspaceCR depending on DevWorkspace API but since there is no agreement made on the final format, so at this stage, I think it would be enough to revise model in DevWorkspace Controller and make it more or less similar to DevWorkspace API, differences I know:
1. `kind: Workspace` vs `kind: DevWorkspace`
2. `kind: WorkspaceExposure` vs `kind: WorkspaceRouting` vs `WorkspaceRouter`
3. 
```yaml
spec:
  devfile:
    components:
      - kind: cheEditor
        alias: any
        id: "eclipse/cloud-shell/latest"
```
vs
```yaml
spec:
  devfile:
    components:
     cheEditor:
        alias: any
        id: "eclipse/cloud-shell/latest"
```

**Comment by sleshchenko** [comment]
I've decided that the current workspace CRD is good enough to proceed with it and later it can be improved during reconciling loop refactoring. And here is a list of items that may be considered to improve later:
1.
```
apiVersion: workspace.che.eclipse.org/v1alpha1
kind: Workspace
metadata:
  uid: 652e4ceb-4654-4165-8207-fdbe0754f09a
  ...
status:
  # workpace ID is generated basing on WorkpaceCR UID
  workspaceId: workspace652e4ceb46544165
```
Do we really needs workspaceID? Why?
Maybe it can be replaced by using UID and namespace/workspaceName

2. 
```yaml
apiVersion: workspace.che.eclipse.org/v1alpha1
kind: Workspace
metadata:
  ...
spec:
  ...
status:
  additionalFields:
    org.eclipse.che.workspace/componentstatuses: '[{"containers":{"che-machine-exec":{"attributes":{"memoryLimitBytes":"128000000","memoryRequestBytes":"128000000","plugin":"eclipse/cloud-shell/nightly","source":"tool"},"ports":[4444]}}},{"containers":{"dev":{"attributes":{"memoryLimitBytes":"268435456","memoryRequestBytes":"268435456","source":"recipe"}}}}]'
    org.eclipse.che.workspace/runtime: '{"activeEnv":"default","machines":{"che-machine-exec":{"attributes":{"memoryLimitBytes":"128000000","memoryRequestBytes":"128000000","plugin":"eclipse/cloud-shell/nightly","source":"tool"},"servers":{"cloud-shell":{"attributes":{"cookiesAuthEnabled":"true","discoverable":"false","internal":"false","protocol":"http","secure":"true","type":"ide"},"status":"UNKNOWN","url":"http://server652e4ceb46544165-che-machine-exec-4444-default.192.168.99.100.nip.io"}}},"dev":{"attributes":{"memoryLimitBytes":"268435456","memoryRequestBytes":"268435456","source":"recipe"}}}}'
```
having such inline JSONs does look pretty. I wonder if we can:
2.1 To get rid `org.eclipse.che.workspace/componentstatuses` we could introduce typed array into status or even introduce a separate CR for components, similar what deployment does with replicas set. 
2.2 To get rid of `org.eclipse.che.workspace/runtime` I wonder is WorkspaceCR could expose everything that is needed to CheRest API to construct that JSON by itself.

3. 
```yaml
apiVersion: workspace.che.eclipse.org/v1alpha1
kind: Workspace
metadata:
...
status:
  ...
  members:
    ready:
    - che-rest-apis
    - dev
    unready:
    - che-machine-exec
```
Well, member item is actually container name and it's good to know some indication what are "detailed" status of workspace start process but:
3.1 It's not really possible to match it with components user described.
3.2 We have willing to run multiple deployments in the same workspace and then containers name won't be unique anymore.
So, I wonder if we can improve it in the way like following:
```yaml
status:
  componentStatuses:
    - alias: "theia-editor"
      containers:
        - deploymentName: ""
          name: ""
...
```

4.
```yaml
apiVersion: workspace.che.eclipse.org/v1alpha1
kind: Workspace
metadata:
...
status:
  ...
  ideUrl: http://server652e4ceb46544165-che-machine-exec-4444-default.192.168.99.100.nip.io
```
I believe we should revise ideUrl field name since in case of cloud-shell workspace we don't have ide at all.
According to Che Plugins model, it could be `editorURL` or even it makes sense to make it even more general like `entrypointServer`

**WorkspaceRouting CR**
1. 	
```go
//TODO What is a point of creating Routing without exposing it?
// Like when workspace is stopped then we should clean up all related Services, Ingress?
// If yes, then it may be changed when Routing will contribute to final effective environment
//Should the workspace be exposed ?
Exposed bool `json:"exposed"`
```
2. 
```go
	// ingress global domain (corresponds to the OpenShift route suffix)
	//TODO Consider renaming it to baseHost, which is optional in case of OpenShift platform
	IngressGlobalDomain string `json:"ingressGlobalDomain"`
```
3.
```go
	// Selector that should be used by created services to point to the workspace Pod
	// TODO We need to rework WorkspaceRouting to contribute pod in WorkspacePod... Then I believe it will be removed at all.
	WorkspacePodSelector map[string]string `json:"workspacePodSelector"`
```
4.
```go
	//TODO what is machine name? Is it container name?
	// since containers use the same ports pool, in fact this endpoint can proxy
	// traffic to different container from originally supposed
	// so, maybe it makes sense to consider make it just []Endpoint?
	//Services by machine name
	Services map[string]ServiceDescription `json:"services"`
```
5.
```go 	
        //TODO Where we could find a reason of failure?
	WorkspaceRoutingFailed WorkspaceRoutingPhase = "Failed"
```
