### ISSUE TITLE
[airgap] Plugins that have dependencies will fail to start in airgap mode.

### ISSUE THREAD

**Issue by amisevsk** [eclipse-che/che#15795]
### Describe the bug
Upstream Theia includes [functionality](https://github.com/eclipse-theia/theia/commit/2d4c8457c09cc6ca37fc5480d14eb080a74ed85a) to download extension dependencies on workspace start (e.g. it will download vscode-yaml if starting a workspace with kubernetes-tooling). Since this download [does not](https://github.com/eclipse-theia/theia/blob/8033853cde81a33589864637b2d99d6590649399/packages/plugin-ext-vscode/src/node/plugin-vscode-resolver.ts#L36) try to pull from the plugin registry, in airgapped scenarios Theia is unable to download extensions' dependencies, which causes them to fail to start.

### Che version

 - [x] nightly

### Steps to reproduce
Start workspace with devfile
```yaml
apiVersion: 1.0.0
metadata:
  name: plugin-dependencies
components:
  - id: ms-kubernetes-tools/vscode-kubernetes-tools/latest
    type: chePlugin
```
in an airgapped cluster with no access to the public internet and check plugin for failure to initialize.

### Additional context
Related to https://github.com/eclipse/che/issues/15794, https://github.com/eclipse/che/issues/15730

**Comment by tsmaeder** [comment]
That resolver needs to disappear: we can't use the VS Code marketplace.

**Comment by amisevsk** [comment]
I agree, though the resolver is the only reason many of our plugins work currently.

**Comment by tsmaeder** [comment]
So two bugs cancel each other 🤦‍♂

**Comment by tsmaeder** [comment]
@l0rd besides breaking air-gapped, this could really land us in hot water with MS.

**Comment by l0rd** [comment]
@tsmaeder agreed. If we cannot remove this resolve how can we fix the problem?

**Comment by amisevsk** [comment]
@l0rd I can prioritize supporting plugin dependencies at the broker level, that could be done relatively quickly. However, I'm still not sure if plugins support cross-container activations (if I start a workspace without the resolver and e.g. the k8s and yaml plugins, will k8s work?)

I can try to look into this further, but it's hard to test since there's no easy way to get rid of the resolver, as far as I know.

**Comment by amisevsk** [comment]
A stop-gap solution that could be implemented more quickly would be to include dependencies explicitly in each plugin as extensions, e.g. the k8s plugin becomes
```yaml
apiVersion: v2
publisher: ms-kubernetes-tools
name: vscode-kubernetes-tools
version: latest
type: VS Code extension
displayName: Kubernetes
title: Kubernetes Tools
description: Develop, deploy and debug Kubernetes applications
icon: https://www.eclipse.org/che/images/logo-eclipseche.svg
repository: https://github.com/Azure/vscode-kubernetes-tools
category: Other
firstPublicationDate: '2020-01-14'
spec:
  containers:
    - image: quay.io/eclipse/che-sidecar-kubernetes-tooling:1.0.9-a40b3bb
      name: vscode-kubernetes-tools
      memoryLimit: 1G
  extensions:
    - https://download.jboss.org/jbosstools/vscode/3rdparty/vscode-kubernetes-tools/vscode-kubernetes-tools-1.0.9.vsix
    - https://github.com/redhat-developer/vscode-yaml/releases/download/0.4.0/redhat.vscode-yaml-0.4.0.vsix # include vscode-yaml directly
latestUpdateDate: "2020-01-23"
```
This would resolve the issue of hitting the vscode marketplace and be quicker to implement than a full dependency resolution scheme.
