### ISSUE TITLE
Errors with Scala language server VS Code extensions (Metals)

### ISSUE THREAD

**Issue by sideeffffect** [eclipse-che/che#15820]
This error is logged when testing Scala VS Code extensions (Metals) in Che

https://github.com/eclipse/che-plugin-registry/pull/356

```
LOG:PLUGIN_HOST(1): PluginManagerExtImpl/init()
LOG:PLUGIN_HOST(1): initializing(metals@1.7.2 with /remote-endpoint/node_modules/@theia/plugin-ext-vscode/lib/node/plugin-vscode-init.js)
LOG:Debugger contribution has been registered: scala
LOG:PLUGIN_HOST(1): initializing(scala@0.3.8 with /remote-endpoint/node_modules/@theia/plugin-ext-vscode/lib/node/plugin-vscode-init.js)
LOG:PLUGIN_HOST(1): PluginManagerExtImpl/loadPlugin(undefined)
ERROR:TypeError [ERR_INVALID_ARG_TYPE]: The "id" argument must be of type string. Received type undefined
LOG:plugin Scala Syntax (official), activate method is undefined so the module is the extension's exports
LOG:PLUGIN_HOST(1): PluginManagerExtImpl/loadPlugin(/tmp/vscode-unpacked/scalameta.metals.1.7.2.hzqeobsacq.scalameta.metals-1.7.2.vsix/extension/out/extension)
LOG:Debug configuration provider has been registered: scala
ERROR:Remote plugin in vscode-metals1k5: promise rejection is not handled in two seconds: Error: Command metals-logs-toggle already exist
ERROR:Remote plugin in vscode-metals1k5: promise rejection stack trace: Error: Command metals-logs-toggle already exist
    at CommandRegistryImpl.registerCommand (/remote-endpoint/node_modules/@theia/plugin-ext/lib/plugin/command-registry.js:99:19)
    at registerCommand (/remote-endpoint/node_modules/@theia/plugin-ext/lib/plugin/plugin-context.js:135:40)
    at Object.vscode.commands.registerCommand (/remote-endpoint/node_modules/@theia/plugin-ext-vscode/lib/node/plugin-vscode-init.js:45:20)
    at registerCommand (/tmp/vscode-unpacked/scalameta.metals.1.7.2.hzqeobsacq.scalameta.metals-1.7.2.vsix/extension/out/extension.js:177:54)
    at vscode_1.commands.getCommands.then.values (/tmp/vscode-unpacked/scalameta.metals.1.7.2.hzqeobsacq.scalameta.metals-1.7.2.vsix/extension/out/extension.js:324:25)
    at process._tickCallback (internal/process/next_tick.js:68:7)
```

**Comment by azatsarynnyy** [comment]
Hello @sideeffffect 

> ERROR:Remote plugin in vscode-metals1k5: promise rejection stack trace: Error: Command metals-logs-toggle already exist

please, check that VS Code extension isn't loaded twice. Through the Che plugin and through the Theia command palette for example. Thanks!

**Comment by sideeffffect** [comment]
This is the devfile for the workspace I'm testing this on
```yaml
metadata:
  name: wksp-0s1g
projects:
  - name: console-scala-simple
    source:
      location: 'https://github.com/sideeffffect/console-scala-simple.git'
      type: git
      branch: master
attributes:
  persistVolumes: 'false'
components:
  - mountSources: true
    memoryLimit: 512Mi
    type: dockerimage
    volumes:
      - name: m2
        containerPath: /home/user/.m2
    alias: maven
    image: 'quay.io/eclipse/che-java8-maven:nightly'
    env:
      - value: ''
        name: MAVEN_CONFIG
      - value: >-
          -XX:MaxRAMPercentage=50 -XX:+UseParallelGC -XX:MinHeapFreeRatio=10
          -XX:MaxHeapFreeRatio=20 -XX:GCTimeRatio=4
          -XX:AdaptiveSizePolicyWeight=90 -Dsun.zip.disableMemoryMapping=true
          -Xms20m -Djava.security.egd=file:/dev/./urandom -Duser.home=/home/user
        name: MAVEN_OPTS
      - value: >-
          -XX:MaxRAMPercentage=50 -XX:+UseParallelGC -XX:MinHeapFreeRatio=10
          -XX:MaxHeapFreeRatio=20 -XX:GCTimeRatio=4
          -XX:AdaptiveSizePolicyWeight=90 -Dsun.zip.disableMemoryMapping=true
          -Xms20m -Djava.security.egd=file:/dev/./urandom
        name: JAVA_OPTS
      - value: >-
          -XX:MaxRAMPercentage=50 -XX:+UseParallelGC -XX:MinHeapFreeRatio=10
          -XX:MaxHeapFreeRatio=20 -XX:GCTimeRatio=4
          -XX:AdaptiveSizePolicyWeight=90 -Dsun.zip.disableMemoryMapping=true
          -Xms20m -Djava.security.egd=file:/dev/./urandom
        name: JAVA_TOOL_OPTIONS
  - type: chePlugin
    reference: >-
      https://raw.githubusercontent.com/sideeffffect/che-plugin-registry/scala/v3/plugins/scalameta/metals/1.7.2/meta.yaml
apiVersion: 1.0.0
commands:
  - name: maven build
    actions:
      - workdir: '${CHE_PROJECTS_ROOT}/console-java-simple'
        type: exec
        command: mvn clean install
        component: maven
  - name: maven build and run
    actions:
      - workdir: '${CHE_PROJECTS_ROOT}/console-java-simple'
        type: exec
        command: mvn clean install && java -jar ./target/*.jar
        component: maven
```
