### ISSUE TITLE
JWT Proxy auth procedure doesn't work if secure server has a non-root path

### ISSUE THREAD

**Issue by sleshchenko** [eclipse-che/che#15867]
### Is your task related to a problem? Please describe.
If a secure server has a non-root path - then our jwtproxy authentication does not work as expected.
It's a case of CloudShell where web resources are serving on `/static` path but not `/`.
We workaround that issue for CloudShell by redirecting on Machine Exec side from `/` to `/static` but in general that issue is still actual. So it can be reproduced with the following Devfile
```yaml
metadata:
  name: cloud-shell
components:
  - reference: https://gist.githubusercontent.com/sleshchenko/ef7ec1da049c9b70ea3383e677695218/raw/98ccf88454912809694f1240b1deadda2feffd48/meta.yaml
    type: cheEditor
    alias: cloudShell
  - memoryLimit: 256Mi
    type: dockerimage
    alias: dev
    image: 'eclipse/che-remote-plugin-openshift-connector-0.0.17:7.2.0'
    env:
      - value: '\[\e[34m\]>\[\e[m\]\[\e[33m\]>\[\e[m\]'
        name: PS1
apiVersion: 1.0.0
```
![Screenshot_20200129_124344](https://user-images.githubusercontent.com/5887312/73350240-56150580-4295-11ea-9561-04a438dbd4e6.png)
![Screenshot_20200129_124401](https://user-images.githubusercontent.com/5887312/73350242-56150580-4295-11ea-8531-5319939c7a19.png)
![Screenshot_20200129_124413](https://user-images.githubusercontent.com/5887312/73350243-56ad9c00-4295-11ea-9400-75d431a78ba2.png)

The failure is caused by the fact that jwtproxy listened on `/jwt/auth` while workspace loader sends requests to `/static/jwt/auth` since `/static` part is already included into server url.

The possible solution could be used here - jwtproxy could let workspace loader know the root-relative link where it listened to requests and sets cookies.

The open question: when users/plugin developer sets cookiesEnabled for secure servers with a non-root path, what is expected cookies path to be used?
In case of CloudShell it's `/` since cookies is supposed to be used for `/connect` and `/attach` WebSocket requests, but we could imagine another scenario.

P.S. It's not a critical issue since we workaround it with a redirect, but it's a good thing to make that issue more visible since in some cases, it may be not possible to configure such redirects.
