### ISSUE TITLE
CloudShell opens terminal in a wrong container

### ISSUE THREAD

**Issue by sleshchenko** [eclipse-che/che#15893]
### Describe the bug
CloudShell opens a terminal in the first container where it's possible and depending on containers order it may be not user expected by machine-exec container itself.

### Che version

 - [ ] latest
 - [x] nightly
 - [ ] other: please specify

### Steps to reproduce
1. execute `kubectl create namespace test`
2. Apply the following workspace to get CloudShell workspace 
<details>

<summary>Resources to apply</summary>

```yaml

---
  apiVersion: apps/v1
  kind: Deployment
  metadata:
    labels:
      che.component.name: dev
      che.original_name: dev
      che.workspace_id: workspacemjqhlw7ouk928pp6
    name: workspacemjqhlw7ouk928pp6.dev
    namespace: test
  spec:
    replicas: 1
    selector:
      matchLabels:
        che.component.name: dev
        che.deployment_name: workspacemjqhlw7ouk928pp6.dev
        che.original_name: dev
        che.workspace_id: workspacemjqhlw7ouk928pp6
    template:
      metadata:
        annotations:
          org.eclipse.che.container.display-name/che-machine-exec9zw: che-machine-exec9zw
          org.eclipse.che.container.display-name/dev: dev
        labels:
          che.component.name: dev
          che.deployment_name: workspacemjqhlw7ouk928pp6.dev
          che.original_name: dev
          che.workspace_id: workspacemjqhlw7ouk928pp6
        name: workspacemjqhlw7ouk928pp6.dev
        namespace: che
      spec:
        serviceAccount: che-workspace
        automountServiceAccountToken: true
        containers:
        - env:
          - name: CHE_WORKSPACE_NAME
            value: che4z-iywig
          - name: CHE_WORKSPACE_LOGS_ROOT__DIR
            value: /workspace_logs
          - name: CHE_MACHINE_TOKEN
          - name: CHE_WORKSPACE_NAMESPACE
            value: che
          - name: CHE_MACHINE_NAME
            value: che-machine-exec9zw
          - name: CHE_API_INTERNAL
            value: http://che-che.192.168.99.100.nip.io/api
          - name: CHE_WORKSPACE_ID
            value: workspacemjqhlw7ouk928pp6
          - name: CHE_PROJECTS_ROOT
            value: /projects
          - name: CHE_API_EXTERNAL
            value: http://che-che.192.168.99.100.nip.io/api
          - name: CHE_API
            value: http://che-che.192.168.99.100.nip.io/api
          image: quay.io/eclipse/che-machine-exec:nightly
          imagePullPolicy: Always
          name: che-machine-exec9zw
          ports:
          - containerPort: 4444
            protocol: TCP
          resources:
            limits:
              memory: "134217728"
            requests:
              memory: "134217728"
        - env:
          - name: CHE_WORKSPACE_NAME
            value: che4z-iywig
          - name: CHE_WORKSPACE_LOGS_ROOT__DIR
            value: /workspace_logs
          - name: CHE_MACHINE_TOKEN
          - name: CHE_WORKSPACE_NAMESPACE
            value: che
          - name: CHE_MACHINE_NAME
            value: dev
          - name: CHE_API_INTERNAL
            value: http://che-che.192.168.99.100.nip.io/api
          - name: CHE_WORKSPACE_ID
            value: workspacemjqhlw7ouk928pp6
          - name: CHE_PROJECTS_ROOT
            value: /projects
          - name: CHE_API_EXTERNAL
            value: http://che-che.192.168.99.100.nip.io/api
          - name: CHE_API
            value: http://che-che.192.168.99.100.nip.io/api
          - name: PS1
            value: \[\e[34m\]>\[\e[m\]\[\e[33m\]>\[\e[m\]
          image: eclipse/che-remote-plugin-openshift-connector-0.0.17:7.2.0
          imagePullPolicy: IfNotPresent
          name: dev
          resources:
            limits:
              memory: "268435456"
            requests:
              memory: "268435456"
        restartPolicy: Always
        securityContext:
          fsGroup: 1724
          runAsUser: 1724
---
  apiVersion: v1
  kind: Service
  metadata:
    annotations:
      org.eclipse.che.machine.name: che-machine-exec9zw
    labels:
      che.workspace_id: workspacemjqhlw7ouk928pp6
    name: servert1zndtwi-che-machine-exec9zw
    namespace: test
  spec:
    ports:
    - name: server-4444
      port: 4444
      protocol: TCP
      targetPort: 4444
    selector:
      che.original_name: dev
      che.workspace_id: workspacemjqhlw7ouk928pp6
    type: ClusterIP
---
  apiVersion: extensions/v1beta1
  kind: Ingress
  metadata:
    annotations:
      kubernetes.io/ingress.class: nginx
      nginx.ingress.kubernetes.io/proxy-connect-timeout: "3600"
      nginx.ingress.kubernetes.io/proxy-read-timeout: "3600"
      nginx.ingress.kubernetes.io/rewrite-target: /$1
      nginx.ingress.kubernetes.io/ssl-redirect: "false"
      org.eclipse.che.machine.name: che-machine-exec9zw
      org.eclipse.che.server.cloud-shell.attributes: '{"internal":"false","discoverable":"false","cookiesAuthEnabled":"true","secure":"true","type":"ide"}'
      org.eclipse.che.server.cloud-shell.port: 4444/tcp
      org.eclipse.che.server.cloud-shell.protocol: http
    labels:
      che.original_name: servert1zndtwi-che-machine-exec9zw-server-4444
      che.workspace_id: workspacemjqhlw7ouk928pp6
    name: ingressakcsxyj6
    namespace: test
  spec:
    rules:
    - host: test-machine-exec.192.168.99.100.nip.io
      http:
        paths:
        - backend:
            serviceName: servert1zndtwi-che-machine-exec9zw
            servicePort: server-4444
          path: /(.*)
  status:
    loadBalancer:
      ingress:
      - ip: 192.168.99.100
---
  apiVersion: v1
  kind: ServiceAccount
  metadata:
    name: che-workspace
    namespace: test
---
  apiVersion: rbac.authorization.k8s.io/v1
  kind: Role
  metadata:
    name: exec
    namespace: test
  rules:
  - apiGroups:
    - ""
    resources:
    - pods/exec
    verbs:
    - create
  - apiGroups:
    - ""
    resources:
    - pods
    - services
    verbs:
    - list
---
  apiVersion: rbac.authorization.k8s.io/v1
  kind: RoleBinding
  metadata:
    name: che-workspace-exec
    namespace: test
  roleRef:
    apiGroup: rbac.authorization.k8s.io
    kind: Role
    name: exec
  subjects:
  - kind: ServiceAccount
    name: che-workspace
    namespace: test

```
</details>

3. Open http://test-machine-exec.192.168.99.100.nip.io/static/ in browser.
Expected: Terminal in Dev container is opened
![Screenshot_20200131_155744](https://user-images.githubusercontent.com/5887312/73544722-77ffbb00-4442-11ea-8aa3-f1bf3f37ff06.png)
Actual: Terminal in machine-exec is opened:
![Screenshot_20200131_155756](https://user-images.githubusercontent.com/5887312/73544742-83eb7d00-4442-11ea-880c-9cc6f08242f8.png)
P.S. Note if you reorder containers in the shared Deployment - terminal will be opened in the right container.

### Runtime
   - [x] kubernetes (include output of `kubectl version`) 
   - [x] Openshift (include output of `oc version`)
   - [x] minikube (include output of `minikube version` and `kubectl version`)
   - [x] minishift (include output of `minishift version` and `oc version`)
   - [ ] docker-desktop + K8S (include output of `docker version` and `kubectl version`)
   - [ ] other: (please specify)

### Installation method
   - [ ] chectl 
   - [ ] che-operator 
   - [ ] minishift-addon
   - [ ] I don't know

### Environment
   - [x] my computer 
       - [ ] Windows
       - [x] Linux
       - [ ] macOS
   - [ ] Cloud
       - [ ] Amazon
       - [ ] Azure
       - [ ] GCE
       - [ ] other (please specify) 
   - [ ] other: please specify
