### ISSUE TITLE
Question: How do I get the service name in my tomcat container

### ISSUE THREAD

**Issue by sonntag-dev** [eclipse-che/che#15897]
Hello, 

thanks for the great work with eclipse che. We want to use eclipse che to deploy our own workspace. Part of this workspace is a tomcat container, in which we are planning to run our own app. 

This app generates different URLs that make the various app components accessible. The app has an init process to set these URLs. So we need the from eclipse che generated tomcat service name (see image below) before we start the init process.

![image](https://user-images.githubusercontent.com/60471467/73555318-b5b61100-444d-11ea-81fb-08093f3be259.png)

Is there a possibility to get this name within the tomcat container? 

I would appreciate if you could give me some help. Thank you.

**Comment by sleshchenko** [comment]
Unfortunately, there is not really easy way to do it, you can create a feature request, I wonder if we can inject value you need with env var.
While it's not  implemented yet, the only way I know - it's requesting Che API, like `curl $CHE_API/workspace/$CHE_WORKSPACE_ID?token=CHE_MACHINE_TOKEN`
Where you get
```json
{ 
   "links":{ 
      "self":"http://che-che.192.168.99.100.nip.io/api/workspace/workspacek5figooh89z74f8t",
      "ide":"http://che-che.192.168.99.100.nip.io/che/wksp-voiu",
      "environment/statusChannel":"ws://che-che.192.
168.99.100.nip.io/api/websocket",
      "environment/outputChannel":"ws://che-che.192.168.99.100.nip.io/api/websocket"
   },
   "attributes":{ 
      "stackName":"Java Gradle",
      "org.eclipse.che.runtimes_id":"runtimesafkyvt3rk
65nd6ql",
      "infrastructureNamespace":"che",
      "updated":"1580737469057",
      "created":"1580737177090"
   },
   "namespace":"che",
   "temporary":false,
   "id":"workspacek5figooh89z74f8t",
   "status":"RUNNING",
   "runtime":{ 
      "machines":{ 
         "gradle":{ 
            "attributes":{ 
               "memoryLimitBytes":"536870912",
               "memoryRequestBytes":"536870912",
               "component":"gradle",
               "source":"recipe"
            },
            "servers":{ 
               "tomcat":{ 
                  "url":"http://servernyb67a6i-gradle-server-8080.192.168.99.100.nip.io/",
                  "attributes":{ 
                     "port":"8080"
                  },
                  "status":"UNKNOWN"
               }
            },
            "status":"RUNNING"
         },
         ....
}
```

<details>
<summary>Devfile I used to get such server info from Che Server</summary>

```yaml
metadata:
  name: wksp-voiu
projects:
  - name: console-java-simple
    source:
      location: 'https://github.com/che-samples/console-java-simple.git'
      type: git
      branch: java1.11
components:
  - id: redhat/java11/latest
    type: chePlugin
  - mountSources: true
    endpoints:
      - name: tomcat
        port: 8080
        attributes:
          public: 'true'
    memoryLimit: 512Mi
    type: dockerimage
    volumes:
      - name: gradle
        containerPath: /home/gradle/.gradle
    alias: gradle
    image: 'quay.io/eclipse/che-java11-gradle:nightly'
    env:
      - value: /home/gradle/.gradle
        name: GRADLE_USER_HOME
      - value: >-
          -XX:MaxRAMPercentage=50 -XX:+UseParallelGC -XX:MinHeapFreeRatio=10
          -XX:MaxHeapFreeRatio=20 -XX:GCTimeRatio=4
          -XX:AdaptiveSizePolicyWeight=90 -Dsun.zip.disableMemoryMapping=true
          -Xms20m -Djava.security.egd=file:/dev/./urandom
        name: JAVA_OPTS
      - value: >-
          -XX:MaxRAMPercentage=50 -XX:+UseParallelGC -XX:MinHeapFreeRatio=10
          -XX:MaxHeapFreeRatio=20 -XX:GCTimeRatio=4
          -XX:AdaptiveSizePolicyWeight=90 -Dsun.zip.disableMemoryMapping=true
          -Xms20m -Djava.security.egd=file:/dev/./urandom
        name: JAVA_TOOL_OPTIONS
      - value: /home/gradle
        name: HOME
apiVersion: 1.0.0
commands:
  - name: gradle build
    actions:
      - workdir: '${CHE_PROJECTS_ROOT}/console-java-simple'
        type: exec
        command: gradle build
        component: gradle
  - name: gradle run
    actions:
      - workdir: '${CHE_PROJECTS_ROOT}/console-java-simple'
        type: exec
        command: gradle run
        component: gradle
```
</details>
