### ISSUE TITLE
Workspace failed to start if there are conflicting volumes configuration on unique PVC strategy

### ISSUE THREAD

**Issue by sleshchenko** [eclipse-che/che#15913]
### Describe the bug
There is not real use-case when it prevents a user from using Che and I discovered this bug occasionally.
So, in case user defines emptyDir in their k8s component, there is persisted volume in plugin/editor with the same name, workpace fails to start with quite unclear and confusing error message
![Screenshot_20200204_104927](https://user-images.githubusercontent.com/5887312/73729004-f909cb80-473c-11ea-87c8-7a4a40b83d02.png)

### Che version

 - [ ] latest
 - [x] nightly
 - [ ] other: please specify

### Steps to reproduce
0. Seems it can be reproduced only with a unique PVC strategy. So, configure your Che installation to use such PVC strategy.
1. Create and start a workspace with the following Devfile:
<details>

<summary>Devfile to test</summary>

```yaml
metadata:
  name: volumesTest
components:
  - referenceContent: |
      apiVersion: apps/v1
      kind: Deployment
      metadata:
        name: empty-env
      spec:
        selector:
          matchLabels:
            app.kubernetes.io/name: empty-env
        template:
          metadata:
            labels:
              app.kubernetes.io/name: empty-env
            name: empty-env
          spec:
            containers:
            - name: container
              image: alpine
              command:  ["sh", "-c"]
              args: [tail -f /dev/null"]
              volumeMounts: 
              - name: plugins
                mountPath: /plugins
            volumes:
              - name: plugins
                emptyDir: {}
    type: kubernetes
apiVersion: 1.0.0

```
</details>

### Expected behavior
**Actual**: Workspace failed to start because of duplicated volumes.
**Expected**: Maybe Che Server reports an error that there are two volumes with the same name but different configuration - persisted and non-persisted.

### Runtime
   - [ ] kubernetes (include output of `kubectl version`) 
   - [ ] Openshift (include output of `oc version`)
   - [x] minikube (include output of `minikube version` and `kubectl version`)
   - [x] minishift (include output of `minishift version` and `oc version`)
   - [ ] docker-desktop + K8S (include output of `docker version` and `kubectl version`)
   - [ ] other: (please specify)

### Installation method
   - [x] chectl 
   - [ ] che-operator 
   - [ ] minishift-addon
   - [ ] I don't know

### Environment
   - [x] my computer 
       - [ ] Windows
       - [x] Linux
       - [ ] macOS
   - [ ] Cloud
       - [ ] Amazon
       - [ ] Azure
       - [ ] GCE
       - [ ] other (please specify) 
   - [ ] other: please specify
