### ISSUE TITLE
Che workspace start fails if che-workspace serviceaccount given anyuid scc

### ISSUE THREAD

**Issue by johnmcollier** [eclipse-che/che#15924]
### Che version

nightly

### Steps to reproduce

I'm running Che on OpenShift and I have a Che plugin that has a container that's using buildah to build container images, and needs to run as privileged to do so.

Before starting the Che workspace, I run:
`oc adm policy add-scc-to-user privileged system:serviceaccount:che:che-workspace`.

Workspace start fails because Che machine exec hits the following error

```
Pulling image "quay.io/eclipse/che-machine-exec:nightly"
Successfully pulled image "quay.io/eclipse/che-machine-exec:nightly"
Error: unable to find user unprivilegeduser: no matching entries in passwd file
Pulling image "quay.io/eclipse/che-theia:next"
Successfully pulled image "quay.io/eclipse/che-theia:next"
Created container theia-ide1jq
Started container theia-ide1jq
Pulling image "quay.io/eclipse/che-machine-exec:nightly"
Successfully pulled image "quay.io/eclipse/che-machine-exec:nightly"
Pulling image "quay.io/eclipse/che-machine-exec:nightly"
Error: Failed to run the workspace: "Waiting for Kubernetes environment 'default' of the workspace'workspaced16ci6b2k23vxkxo' reached timeout"
```

### Expected behavior

The che workspace doesn't fail if the privileged SCC is given to its service account

### Runtime

Openshift

### Installation method

che-operator

### Environment
   - [ ] my computer 
       - [ ] Windows
       - [ ] Linux
       - [ ] macOS
   - [ ] Cloud
       - [ ] Amazon
       - [ ] Azure
       - [ ] GCE
       - [ ] other (please specify) 
   - [ ] other: please specify

### Additional context

I'm unable to reproduce on Che 7.6.0 and earlier

**Comment by l0rd** [comment]
@johnmcollier I am not able to reproduce the problem with a quarkus sample (even after making the che-workspace SA privileged) on a local CodeReady Container instance. Can you provide some additional informations:
- the devfile you are using to start the workspace
- the openshift events on the workspace namespace when this happens (`oc get events --watch-only`)?
- the description of the workspace pod if the pod gets created (`oc describe pod <workspace-pod-name>`)
- the logs of the pods containers if available

**Comment by johnmcollier** [comment]
@l0rd I was able to reproduce on CodeReady Containers. Turns out I also had the wrong SCC, `anyuid` is causing the issue, not `privileged`. 

With the latest CodeReady Containers:
1) I installed the latest version of Che from OperatorHub
2) Ran `oc adm policy add-scc-to-user anyuid system:serviceaccount:che:che-workspace`
3) Created a Go workspace from the Go devfile available on Che
4) Encountered the same error I posted above

Logs:
- Devfile: https://github.com/eclipse/che-devfile-registry/blob/7.7.x/devfiles/go/devfile.yaml
- OpenShift Events: [oc-events-che.txt](https://github.com/eclipse/che/files/4161408/oc-events-che.txt)
- Workspace Pod description: [workspace-describe.txt](https://github.com/eclipse/che/file
- Workspace start logs: 
[workspace-start-logs.txt](https://github.com/eclipse/che/files/4161424/workspace-start-logs.txt)

**Comment by johnmcollier** [comment]
Hi, any updates on this issue?

**Comment by sleshchenko** [comment]
I faced the same error in other case https://github.com/eclipse/che/issues/15888
So, maybe the following PR will fix your issue as well https://github.com/eclipse/che-machine-exec/pull/81.

quay.io/eclipse/che-machine-exec:7.9.0 already contains the fix

**Comment by sleshchenko** [comment]
<details>
<summary>Devfile to check</summary>

```yaml
---
apiVersion: 1.0.0
metadata:
  generateName: golang-
projects:
-
  name: example
  source:
    type: git
    location: https://github.com/golang/example.git
  clonePath: src/github.com/golang/example/
components:
-
  type: chePlugin
  reference: https://raw.githubusercontent.com/eclipse/che-plugin-registry/master/v3/plugins/eclipse/che-machine-exec-plugin/7.9.0/meta.yaml
-
  type: chePlugin
  id: ms-vscode/go/latest
  alias: go-plugin
  memoryLimit: 512Mi
-
  type: dockerimage
  # this version is used in the plugin
  image: quay.io/eclipse/che-golang-1.12:nightly
  alias: go-cli
  env:
    - name: GOPATH
      # replicate the GOPATH from the plugin
      value: /go:$(CHE_PROJECTS_ROOT)
    - name: GOCACHE
      # replicate the GOCACHE from the plugin, even though the cache is not shared
      # between the two
      value: /tmp/.cache
  endpoints:
    - name: '8080/tcp'
      port: 8080
  memoryLimit: 512Mi
  mountSources: true
commands:
-
  name: run outyet
  actions:
  - type: exec
    component: go-cli
    command: go get -d && go run main.go
    workdir: ${CHE_PROJECTS_ROOT}/src/github.com/golang/example/outyet
-
  name: stop outyet
  actions:
  - type: exec
    component: go-cli
    command: kill $(pidof go)
-
  name: test outyet
  actions:
  - type: exec
    component: go-cli
    command: go test
    workdir: ${CHE_PROJECTS_ROOT}/src/github.com/golang/example/outyet
-
  name: run current file
  actions:
  - type: exec
    component: go-cli
    command: go get -d && go run ${file}
    workdir: ${fileDirname}
-
  name: Debug current file
  actions:
  - type: vscode-launch
    referenceContent: |
      {
        "version": "0.2.0",
        "configurations": [
          {
            "name": "Debug current file",
            "type": "go",
            "request": "launch",
            "mode": "auto",
            "program": "${fileDirname}",
          },
        ]
      }
```

</details>
