### ISSUE TITLE
che in che development is broken

### ISSUE THREAD

**Issue by RomanNikitenko** [eclipse-che/che#15932]
### Describe the bug
It's impossible to start hosted instance for che-in-che development at the moment.

### Che version

 - [x] latest
 - [ ] nightly
 - [ ] other: please specify

### Steps to reproduce

1. Start a workspace from the devfile:

<details>
<summary>Devfile</summary>
 
```
apiVersion: 1.0.0
metadata:
 name: wksp-test
projects:
  - name: che-theia
    source:
      type: git
      location: 'https://github.com/eclipse/che-theia.git'
  - name: theia
    source:
      type: git
      location: 'https://github.com/theia-ide/theia.git'
components:
  - 
    alias: che-dev
    type: dockerimage
    image: eclipse/che-theia-dev:next
    mountSources: true
    endpoints:
      - name: "theia-dev"
        port: 3130
        attributes:
          protocol: tcp
          public: 'true'
    memoryLimit: 4Gi
  - 
    alias: theia-editor
    reference: >-
      https://raw.githubusercontent.com/eclipse/che-plugin-registry/master/v3/plugins/eclipse/che-theia/next/meta.yaml
    type: cheEditor
  
  - 
    id: che-incubator/typescript/1.30.2
    alias: tsc
    type: chePlugin
    memoryLimit: 2048M

commands:
- name: start hosted instance
  actions:
  - type: exec
    component: che-dev
    command: >
              yarn theia start --hostname=0.0.0.0 --port=3130
    workdir: /projects/theia/examples/assembly

- name: che:theia:init
  actions:
  - type: exec
    component: che-dev
    command: >
              che:theia init
    workdir: /projects/theia

- name: theia:build
  actions:
  - type: exec
    component: che-dev
    command: >
              yarn
    workdir: /projects/theia

- name: che-theia:build
  actions:
  - type: exec
    component: che-dev
    command: >
              yarn
    workdir: /projects/che-theia

```
</details>

2. Run `che:theia:init` task
3. Run `theia:build` task
4. Run `start hosted instance` task 
5. You can see the errors, please see the screenshot

### Expected behavior
hosted instance has started

### Runtime
   - [ ] kubernetes (include output of `kubectl version`) 
   - [ ] Openshift (include output of `oc version`)
   - [x] minikube (include output of `minikube version` and `kubectl version`)
   - [ ] minishift (include output of `minishift version` and `oc version`)
   - [ ] docker-desktop + K8S (include output of `docker version` and `kubectl version`)
   - [ ] other: (please specify)

### Screenshots
![che_in_che_errors](https://user-images.githubusercontent.com/5676062/73829193-3fc5f700-480b-11ea-9926-47faeaa2528e.png)

### Installation method
   - [x] chectl 
   - [ ] che-operator 
   - [ ] minishift-addon
   - [ ] I don't know

### Environment
   - [ ] my computer 
       - [ ] Windows
       - [x] Linux
       - [ ] macOS
   - [ ] Cloud
       - [ ] Amazon
       - [ ] Azure
       - [ ] GCE
       - [ ] other (please specify) 
   - [ ] other: please specify
