### ISSUE TITLE
Terminal doesn't work

### ISSUE THREAD

**Issue by sharoncafa01** [eclipse-che/che#15969]
Hi.
For 5 days I tried to start the terminal.
After I wrote a program i wanted to check and start it, but the terminal didn't work.
It's like it doesn't work, in fact I can't write on it.
What can I do?

**Comment by RomanNikitenko** [comment]
@sharoncafa01 
thank you for reporting the issue!

I tried to start a new terminal and it works for me!
I use:
- minikube version: v1.6.2
- chectl/0.0.20200207-next.b3dcac3 linux-x64 node-v10.19.0
- che version
![che-version](https://user-images.githubusercontent.com/5676062/74101011-e2e57c00-4b3d-11ea-8715-240f64567ef4.png)

could you provide more details how to reproduce the issue?

**Comment by sharoncafa01** [comment]
Hi, thank you for reply.
The che version is: 





When I try to check a program by the “gcc” command, and I wanted to start the terminal, after press (ctrl + ò), the terminal window opens, but it doesn’t work.
In fact, when I try to write on it for move, check, or do other action, it remains like this:






I tried to write, copy something ect but it’s like it doesn’t receive the command.
What can I do?
Da: RomanNikitenko
Inviato: domenica 9 febbraio 2020 12:15
A: eclipse/che
Cc: sharoncafa01; Mention
Oggetto: Re: [eclipse/che] Terminal doesn't work (#15969)

@sharoncafa01
thank you for reporting the issue!
I tried to start a new terminal and it works for me!
I use:
• minikube version: v1.6.2
• chectl/0.0.20200207-next.b3dcac3 linux-x64 node-v10.19.0
• che version

could you provide more details how to reproduce the issue?

**Comment by ibuziuk** [comment]
@RomanNikitenko thank you for following up on that. I have added the `info-needed` label, since this does look like abnormal behavior
@sharoncafa01 please, provide more details wirh steps to reproduce

**Comment by RomanNikitenko** [comment]
@sharoncafa01 
I see your answer, but there are empty areas instead of screenshots:

![empty](https://user-images.githubusercontent.com/5676062/74220955-98890a00-4cb9-11ea-881e-85b30ede71d7.png)

So, more details will help to reproduce and fix the issue.
thank you!

**Comment by dublmozga** [comment]
The same thing with READY-TO-GO STACK in 
Stack with C/C++ and Clang 8 workspace. also i tried the stack for GO and in this time all worked properly

**Comment by RomanNikitenko** [comment]
@dublmozga 
I tried 
> Stack with C/C++ and Clang 8 workspace

and can not reproduce the issue.
![cpp_terminal](https://user-images.githubusercontent.com/5676062/74227108-76e24f80-4cc6-11ea-9bfb-0d291ed29133.gif)

Please provide more info about your assembly and steps to reproduce.
thank you!

**Comment by RomanNikitenko** [comment]
I can reproduce it on https://che.openshift.io for Stack with C/C++ and Clang 8 workspace.

**Comment by RomanNikitenko** [comment]
As workaround, user can change version of `machine-exec` service, it helped me to get terminal working.

![workaround_terminal](https://user-images.githubusercontent.com/5676062/74231840-32f44800-4cd0-11ea-9cf0-18b7b97169e5.png)

**Comment by dublmozga** [comment]
Yes, thanks. That helped to me too.

**Comment by azatsarynnyy** [comment]
it's interesting that the terminal works well after disabling the cpp-tools plugin

**Comment by rhopp** [comment]
One thing I noticed, that tasks works, if the terminal wasn't opened before... But once the terminal is opened, tasks stop working as well...

**Comment by sleshchenko** [comment]
Recently, I faced a similar issue on minishift, and it was by entrypoint I specified in my Devfile.
I quickly checked and it seems to be the same issue. So, I've created a fix into devfile registry that workarounds the problem https://github.com/eclipse/che-devfile-registry/pull/196

I'll try to handle the default shell detector issue in one of my PRs in che-machine-exec if I fail - will create a dedicated issue for that.

**Comment by sleshchenko** [comment]
@rhopp @sharoncafa01 
Are you able to check with update Devfile:
<details>
<summary>Devfile without overridden entrypoint</summary>

```yaml
metadata:
  name: cpp-terminal-test
projects:
  - name: cpp-hello-world
    source:
      location: 'https://github.com/che-samples/cpp-hello-world'
      type: git
      branch: master
attributes:
  persistVolumes: 'false'
components:
  - id: che-incubator/cpptools/latest
    preferences:
      clangd.path: /usr/bin/clangd
      cdt.clangd.binaries.enable: false
    type: chePlugin
    alias: cpp-plugin
  - mountSources: true
    memoryLimit: 512Mi
    type: dockerimage
    alias: cpp-dev
    image: 'quay.io/eclipse/che-cpp-rhel7:nightly'
apiVersion: 1.0.0
commands:
  - name: build
    actions:
      - workdir: '${CHE_PROJECTS_ROOT}/cpp-hello-world'
        type: exec
        command: g++ -g hello.cpp -o hello.out && echo "Build complete"
        component: cpp-dev
  - name: run
    actions:
      - workdir: '${CHE_PROJECTS_ROOT}/cpp-hello-world'
        type: exec
        command: ./hello.out
        component: cpp-dev
  - name: debug
    actions:
      - referenceContent: |
          {
            "version": "0.2.0",
            "configurations": [
                {
                    "type": "gdb",
                    "name": "Debug c++ application",
                    "request": "launch",
                    "program": "/projects/cpp-hello-world/hello.out"
                }
            ]
          }
        type: vscode-launch
```
</details>
