### ISSUE TITLE
[docs] How to add VSCode Extension to Eclipse Che?

### ISSUE THREAD

**Issue by leehyeongrak** [eclipse-che/che#15982]
### Problem
I've seen in the documentation that I can add an extension of vscode to eclipse.
https://che.eclipse.org/eclipse-che-7-extending-developer-workspaces-to-run-vs-code-extensions-in-the-cloud-cbe97e11d4d4
But it only show the possibility and doesn't seem to tell me how to use it in eclipse che.

I'm using theia as the default frontend IDE of Eclipse Che
I know how to add the plugin provided by che, but I don't know how to add various plugins of vscode.
I know that there is a jenkins plugin in vscode.
I want to add Jenkins Extension to Eclipse Che
How to add VSCode Extension to Eclipse Che?

### Relevant information
I have using eclipse che latest version

**Comment by tolusha** [comment]
I completed the following steps:

1. Prepare a docker container with all necessary dependencies. It is a container where your plugin will be run
2. Create a `meta.yaml` file, see my example [1]. Basically you have to define your container and vsix files here.
3. In the workspace configuration add a section with reference to your `meta.yaml`
```yaml
-
    alias: apache-pig-plugin
    type: chePlugin
    reference: https://raw.githubusercontent.com/tolusha/plugins-registry/master/plugins/tolusha/apache-pig-debug/0.0.1/meta.yaml
```

[1] https://github.com/tolusha/plugins-registry/blob/master/plugins/tolusha/apache-pig-debug/0.0.1/meta.yaml

/cc @tsmaeder
