### ISSUE TITLE
Eclipse Che One of Container terminates unexpectedly

### ISSUE THREAD

**Issue by jswordfish** [eclipse-che/che#16171]
## Summary
I am trying to start a Dot net v3 workspace in Eclipse Che v 7.7.1.  I am trying to pull the following dot net image - mcr.microsoft.com/dotnet/core/sdk:3.0

## Relevant information
Here's my dev file
```yaml
metadata:
  name: dotnet-web
projects:
  - name: dotnet-web-simple
    source:
      location: 'https://github.com/che-samples/dotnet-web-simple'
      type: git
      branch: netcoreapp2.2
attributes:
  persistVolumes: 'false'
components:
  - id: redhat-developer/che-omnisharp-plugin/latest
    memoryLimit: 1024Mi
    type: chePlugin
    alias: omnisharp
  - id: redhat-developer/netcoredbg-theia-plugin/latest
    memoryLimit: 512Mi
    type: chePlugin
    alias: netcoredbg
  - mountSources: true
    endpoints:
      - name: 5000/tcp
        port: 5000
    memoryLimit: 512Mi
    type: dockerimage
    volumes:
      - name: dotnet3
        containerPath: /home/user
    alias: dotnet3
    image: 'mcr.microsoft.com/dotnet/core/sdk:3.0'
apiVersion: 1.0.0
commands:
  - name: build
    actions:
      - workdir: '${CHE_PROJECTS_ROOT}/dotnet-web-simple'
        type: exec
        command: dotnet build
        component: dotnet3
```

Workspace opening fails with this message - 
Successfully pulled image "eclipse/che-init-plugin-broker:v0.24"
Created container
Started container
Starting Init Plugin Broker
Cleaning /plugins dir
pulling image "eclipse/che-unified-plugin-broker:v0.24"
Successfully pulled image "eclipse/che-unified-plugin-broker:v0.24"
Created container
Started container
Unified Che Plugin Broker
Starting Che plugins and editor processing
Downloading VS Code extension for plugin 'redhat-developer/che-omnisharp-plugin/latest'
List of plugins and editors to install
- redhat-developer/che-omnisharp-plugin/latest - This plug-in registers omnisharp-roslyn as a language server and provides project dependencies and language syntax.
- redhat-developer/netcoredbg-theia-plugin/latest - This plug-in provides Samsung/netcoredbg which implements VSCode Debug Adapter protocol and allows to debug .NET apps under .NET Core runtime.
- eclipse/che-machine-exec-plugin/7.7.0 - Che Plug-in with che-machine-exec service to provide creation terminal or tasks for Eclipse CHE workspace containers.
- eclipse/che-theia/7.7.0 - Eclipse Theia
Starting VS Code and Theia plugins processing
Downloading VS Code extension for plugin 'redhat-developer/netcoredbg-theia-plugin/latest'
All plugins have been successfully processed
pulling image "quay.io/eclipse/che-theia-endpoint-runtime-binary:7.7.0"
Successfully pulled image "quay.io/eclipse/che-theia-endpoint-runtime-binary:7.7.0"
Created container
Started container
pulling image "eclipse/che-unified-plugin-broker:v0.24"
Successfully pulled image "eclipse/che-unified-plugin-broker:v0.24"
Created container
Started container
Unified Che Plugin Broker
Starting Che plugins and editor processing
Downloading VS Code extension for plugin 'redhat-developer/che-omnisharp-plugin/latest'
Starting VS Code and Theia plugins processing
List of plugins and editors to install
- redhat-developer/che-omnisharp-plugin/latest - This plug-in registers omnisharp-roslyn as a language server and provides project dependencies and language syntax.
- redhat-developer/netcoredbg-theia-plugin/latest - This plug-in provides Samsung/netcoredbg which implements VSCode Debug Adapter protocol and allows to debug .NET apps under .NET Core runtime.
- eclipse/che-machine-exec-plugin/7.7.0 - Che Plug-in with che-machine-exec service to provide creation terminal or tasks for Eclipse CHE workspace containers.
- eclipse/che-theia/7.7.0 - Eclipse Theia
Downloading VS Code extension for plugin 'redhat-developer/netcoredbg-theia-plugin/latest'
All plugins have been successfully processed
Container image "mcr.microsoft.com/dotnet/core/sdk:3.0" already present on machine
Created container
Started container
pulling image "quay.io/eclipse/che-machine-exec:7.7.0"
Successfully pulled image "quay.io/eclipse/che-machine-exec:7.7.0"
Created container
Started container
pulling image "quay.io/eclipse/che-theia:7.7.0"
Successfully pulled image "quay.io/eclipse/che-theia:7.7.0"
Created container
Started container
pulling image "quay.io/eclipse/che-sidecar-dotnet:2.2.105-2fd6e78"
Successfully pulled image "quay.io/eclipse/che-sidecar-dotnet:2.2.105-2fd6e78"
Created container
Started container
pulling image "quay.io/eclipse/che-sidecar-dotnet:2.2.105-2fd6e78"
Successfully pulled image "quay.io/eclipse/che-sidecar-dotnet:2.2.105-2fd6e78"
Error: Failed to run the workspace: "The following containers have terminated:
dotnet: reason = 'Completed', exit code = 0, message = 'null'"

Also I can't see any relevant logs on the back end.

Kindly let me know what i am missing in above dev file?

Thanks!
