### ISSUE TITLE
Share files and folders between containers within a workspace

### ISSUE THREAD

**Issue by svkr2k** [eclipse-che/che#16197]
I would like to share a large set of files between two containers in a workspace.

Currently, in order to share the certain files under a folder, I included the following mount paths in the plugin description yaml (which is referenced in devfile) for both the containers:

```
  containers:
     volumes:
         - mountPath: "/home/testFolder"
           name: myTestFolder
```

This seem to work when the testFolder is empty. so that the files generated by one container can be accessed by another container.

But, I would like to share the folders that are "pre-populated" or it already contains a large set of files and multiple containers with in a workspace needs to use them.

How can it be done ? mountPath doesnt seem to work. When I tried to mounth the path as shown above, the container sees an empty mounted folder. Please help.
