### ISSUE TITLE
Store credentials into secrets instead of plain text of CheCluster CR fields

### ISSUE THREAD

**Issue by sleshchenko** [eclipse-che/che#16243]
### Is your task related to a problem? Please describe.
In K8s world, it's a good practice storing credentials, especially password in secrets. It would be great if che-operator follow this approach.

### Describe the solution you'd like
I believe we must store in plain-text only non-sensitive info, let's say users can share with others. Everything else must be stored in secrets.

![Screenshot_20200305_152204](https://user-images.githubusercontent.com/5887312/75985912-cb5ba200-5ef5-11ea-823a-57359a533458.png)
instead we could have
```
spec:
  auth:
    identityProviderPassword:
      secretName: postgres
      key: keycloak-password
    identityProviderUsername:
      secretName: postgres
      key: keycloak-username
  database:
    password:
      secretName: postgres
      key: che-password
    chePostgresUsername:
      secretName: postgres
      key: che-username
```
