### ISSUE TITLE
Define Tekton tasks in the devfile.

### ISSUE THREAD

**Issue by sunix** [eclipse-che/che#16304]
### Is your enhancement related to a problem? Please describe.

Here it is about how we could take advantage of the fact that
- Tekton is built on k8s
- Che is built on k8s

to perform builds as close as what we have in the CI but in the inner loop (before pushing to git).

Here would be the requirements:
- We want to avoid having to transfert any files elsewhere: sources and built binaries have to stay in the workspace volumes. (maybe restricted to tasks with file/folder output resources)
- Declaring a Tekton task in the devfile should have the same syntax as a classic Tekton task.
- It should be easy to trigger a tekton task from Che Theia UI (my workspace panel or command pallet)
- In the devfile, we may want to define cpu/memory requirements for a specific task ... to be discussed

**Comment by sunix** [comment]
cc @l0rd @vdemeester WDYT ?

**Comment by l0rd** [comment]
@sunix can you provide an example of such a devfile? Are you thinking about a new command type (i.e. `type: tektonTask`)? How would we mount the source code in the pipeline containers?

**Comment by gattytto** [comment]
maybe this can be related? https://github.com/eclipse/che/issues/15752

**Comment by sunix** [comment]
> @sunix can you provide an example of such a devfile? Are you thinking about a new command type (i.e. `type: tektonTask`)? How would we mount the source code in the pipeline containers?

@l0rd 
Could be, I am unsure what would be the implementation. A Che command would make sense, then it means that a task could bring other type of resources (container, etc ...). To me that would be fine.

**Comment by gattytto** [comment]
for getting resources in tekton I have followed a guide with this as example:

````yaml
apiVersion: tekton.dev/v1alpha1
kind: PipelineResource
metadata:
  name: github-repo
  namespace: che
spec:
  type: git
  params:
    - name: url
      value: https://github.com/user/repo
````

but then if the repo needs authentication it requires this:

````yaml
apiVersion: tekton.dev/v1alpha1
kind: TaskRun
metadata:
  name: pipeline-test-auth
  namespace: che
spec:
  serviceAccountName: build-bot
  taskRef:
    name: read-task
  inputs:
    resources:
      - name: github-repo
        resourceRef:
          name: github-repo

---
apiVersion: v1
kind: Secret
metadata:
  name: basic-user-pass
  namespace: che
  annotations:
    tekton.dev/git-0: https://github.com/gattytto/gopos
type: kubernetes.io/basic-auth
stringData:
  username: username
  password: pass #out in the open!!

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: build-bot
  namespace: che
secrets:
  - name: basic-user-pass
````

**Comment by sunix** [comment]
to me these kind of secrets/config have to be enabled in Che https://github.com/eclipse/che/issues/14680

**Comment by gattytto** [comment]
could there be a che dashboard plugin? so to have an extra option in 
![image](https://user-images.githubusercontent.com/407397/76545412-804b0d00-6468-11ea-93c4-97e28e44d289.png) to manage kubeconfigs, tekton objects and other cluster custom-resources.

workspace edit section of the dashboard could have an extra tab for adding those resources to the workspace (instead of manually editing the devfile), like the plugins section. 

acces to those resources could be fine-grained using keycloak?

as of now when I open the tekton workspace I need to get into the sidecar terminal and add the ./kube/config every time the IDE restarts from inactivity (token expiry/idle timeout). 

if I had the che server running in a cluster, and the tekton operator running in a separate cluster of the same network, how could I use theia to push the right kubeconfig to the tekton extension?.

**Comment by gorkem** [comment]
A Tekton `Task`, a `ConfigMap`, or a `ServiceBindingRequest` these are all kubernetes resources that a developer may want to apply along with the workspace. Wouldn't extending the Kubernetes component type to allow us to create any resource via devfile be a more generic solution?

To author and manage Tekton resources, we have the [vscode-tekton ](https://github.com/redhat-developer/vscode-tekton) extension that is progressing well and it needs to be made available also on Che. 

Overall, we have a persistence problem with `kubeconfig` that is effecting openshift extension but will also effect tekton and knative extensions. I think we need to find a solution to that problem. 

If you are using a devfile one thing that can make life easier is to keep your ./kube/config in the git repo and set the env `KUBECONFIG` to point to that file in your devfile.

**Comment by gattytto** [comment]
https://github.com/che-dockerfiles/che-sidecar-tekton/pull/2 is coming! and I can see "octant" in the docker file that's good.

**Comment by gattytto** [comment]
> Overall, we have a persistence problem with `kubeconfig` that is effecting openshift extension but will also effect tekton and knative extensions. I think we need to find a solution to that problem.

I have come with [this](https://github.com/gattytto/che-plugin-registry/blob/b66f415a8d1dcece03195327b6dfb52d4f003ea3/v3/plugins/ms-vscode/tekton/0.0.3/meta.yaml#L19) as a temporary workaround for the kubeconfig persistence problem, also useful for bazel cache, and now gopls works also for the go modules /.cache folder

**Comment by gattytto** [comment]
> @sunix can you provide an example of such a devfile? Are you thinking about a new command type (i.e. `type: tektonTask`)? How would we mount the source code in the pipeline containers?

the second part of your question I have been testing, not specifically for the projects folder but for the huge cache produced from bazel sidecar when referencing many external repos in /workspace file:
within the project's build folder create something.sh with:
````bash
#!/bin/sh
kubectl delete -f ../tekton/task/bazel_build_gen.yaml -f ../tekton/task/taskrun.yml
kubectl delete -f bazelcache.yml
kubectl apply -f bazelcache.yml
kubectl apply -f ../tekton/task/bazel_build_gen.yaml
kubectl apply -f ../tekton/task/taskrun.yml
tkn taskrun logs pipeline-test-auth -f
````
next to it in bazelcache.yaml:
````yaml
apiVersion: v1  
kind: PersistentVolume  
metadata:  
  name: bazelcache  
  labels:  
    type: local  
spec:  
  storageClassName: bazelcache  
  capacity: 
    storage: 5Gi 
  accessModes:  
    - ReadWriteMany 
  hostPath:  
    path: "/data/wksp/workspaceax6ccroy58gxem8n/bazelcache/_bazel_user" 

--- 

kind: StorageClass  
apiVersion: storage.k8s.io/v1  
metadata:  
  name: bazelcache  
  annotations:  
    storageclass.kubernetes.io/is-default-class: "false"  
provisioner: k8s.io/minikube-hostpath  
reclaimPolicy: Retain 
````
