### ISSUE TITLE
[chectl] Make it possible to install Eclipse Che with "--no-tls" option

### ISSUE THREAD

**Issue by dmytro-ndp** [eclipse-che/che#16302]
### Is your enhancement related to a problem? Please describe.
There is no chectl option to install _Eclipse Che_ without TLS support which is default now.
At the same time `-s, --tls` doesn't make much sense so as **chectl** installing Eclipse Che with TLS mode enabled by default by both operator and helm chart.

### Describe the solution you'd like
- add support of `--no-tls` option which to install Eclipse Che without TLS encryption
- remove `-s, --tls` option which looks useless now

**Comment by l0rd** [comment]
That's a good point @dmytro-ndp. For who is going to work on that: there is an interesting [`allowNo` attribute](https://github.com/oclif/parser/blob/master/src/flags.ts#L27) of the oclif booleans flags...

**Comment by sleshchenko** [comment]
@dmytro-ndp I've already asked Mykola about --no-tls flag in his first PR related to TLS by default. The answer was

> My plan was to remove that option at all when TLS by default is finished. In most cases people use default Che-Theia editor which in some cases doesn't work properly without TLS (all webview are broken). And, of course, the security...

From https://github.com/che-incubator/chectl/pull/476#discussion_r373383036
So, could you elaborate more about cases when Che with no-tls and broken Theia Webview is needed? Maybe it's better to support TLS installation only?

**Comment by tolusha** [comment]
@dmytro-ndp 
Do you still have cases to deploy Che with no tls?

**Comment by dmytro-ndp** [comment]
Eclipse Che and CRW are actually support http-mode, and it's not actually simple to configure TLS mode on minishift.

**Comment by l0rd** [comment]
@dmytro-ndp @l0rd we need to support OpenShift 3.11 but we do NOT need to support minishift at all. If we can run Che on OpenShift 3.11 with TLS enabled I would deprecate TLS installation and disabled it at all in a couple of sprints.

**Comment by nickboldt** [comment]
+1 to "remove -s, --tls options", since HTTP + Theia = broken. 

Similarly, CRW 2.x is now TLS-mode-only. HTTP is no longer supported and let's be real, it's 2020. Security is important.

**Comment by azatsarynnyy** [comment]
Note, that VS Code compatible Theia WebView Plugin API [won't work on http](https://github.com/eclipse-theia/theia/pull/6465#issuecomment-557494879).
As it works in the secure contexts only: https and localhost.
Today, more and more VS Code extensions are adopting WebView API, e.g. OpenShift Connector.
Not only Che Theia Welcome Plugin that provides WebView-based Welcome page.

**Comment by dmytro-ndp** [comment]
I see. So, closing the issue with "**won't fix**" resolution.

**Comment by nickboldt** [comment]
Actions from today's call:

**Should we allow users to have no-TLS mode in Eclipse Che deployed to minikube | openshift?**

- [ ] we should drop all flags related to tls as Che should only supports TLS
- [ ] drop non-secure http
- [ ] minishift addon is not supported anymore (and has been unsupported for some time)

all options around TLS should be gone: 
- [ ] operator hub UI
- [ ] CSV
- [ ] chectl / crwctl

-[ ] Need to investigate about breaking compatibility on the custom resource

**Comment by l0rd** [comment]
@nickboldt in the meantime I had created this one https://github.com/eclipse/che/issues/17012

**Comment by gorshkov-leonid** [comment]
Hello, this is my case:
I ran custom devfile/plugin registries  over http, because I don't need WebView and http is easier - no certificates, no extra steps. But as you suggested I cannot disable https in che-server. As result, my custom regestries won't work with Che over http because browser refuses it.
Hw do you think about my case?

**Comment by tolusha** [comment]
@gorshkov-leonid
Could you clarify:
- infrastructure ?
- installation method (operator, helm) ?

In general when Eclipse Che is deployed, you should import the certificate into a browser.
To extract certificate we introduce `chectl cacert:export` command.

**Comment by gorshkov-leonid** [comment]
I use 
* `minikube` platform
* operator (by default)
* custom regestries
Command looks like  `chectl server:start --platform minikube --devfile-registry-url=http://${CHE_LOCALHOST}:8083 --plugin-registry-url=http://${CHE_LOCALHOST}:8082/v3` . 
I know that I can get ca sertificate via `cacert:export`. But I do not know how to use it with regestries. Is it true that regestries can be not runned before running of Che Server? And goal is to run regestries with usage of this certificate? May be I missed something in documentation?

**Comment by tolusha** [comment]
I see. so, either
1. Run registries over https (I don't know what `${CHE_LOCALHOST}` means)
or
2. Deploy Eclipse Che without tls, it is still possible with litter trick: https://www.eclipse.org/lists/che-dev/msg03674.html

**Comment by gorshkov-leonid** [comment]
@tolusha 
1) `export CHE_LOCALHOST=$(netsh interface ip show addresses name="vEthernet (Default Switch)" | findstr "IP Address" | egrep -o '([[:digit:]]|\.)+')` - localhost where regestries where ran but translated to subnet of VM, windows specific, but the same can be done via ifconfig or ip in linux. 
2) `Che without tls` I tried this variant but not successfully, because even under http Che sends request to keycloak via https.. .have no idea why. 

Here full config:
```
apiVersion: org.eclipse.che/v1
kind: CheCluster
metadata:
  name: eclipse-che
spec:
  server:
    cheImage: 'quay.io/eclipse/che-server'
    cheImageTag: '7.15.0'
    externalDevfileRegistry: true
    devfileRegistryUrl: 'http://192.168.251.161:8083'
    externalPluginRegistry: true
    pluginRegistryUrl: 'http://192.168.251.161:8082/v3'
    cheFlavor: ''
    cheWorkspaceClusterRole: ''
    selfSignedCert: false
    gitSelfSignedCert: false
    tlsSupport: false
    proxyURL: ''
    proxyPort: ''
    proxyUser: ''
    proxyPassword: ''
    nonProxyHosts: ''
    serverMemoryRequest: ''
    serverMemoryLimit: ''
    workspaceNamespaceDefault: ''
    allowUserDefinedWorkspaceNamespaces: false
    airGapContainerRegistryHostname: ''
    customCheProperties:
      CHE_LIMITS_WORKSPACE_IDLE_TIMEOUT: '-1'
  database:
    externalDb: false
    chePostgresHostName: ''
    chePostgresPort: ''
    chePostgresUser: ''
    chePostgresPassword: ''
    chePostgresDb: ''
    postgresImage: 'centos/postgresql-96-centos7:9.6'
  storage:
    pvcStrategy: 'common'
    pvcClaimSize: '1Gi'
    preCreateSubPaths: true
    pvcJobsImage: ''
    postgresPVCStorageClassName: ''
    workspacePVCStorageClassName: ''

  auth:
    externalIdentityProvider: false
    identityProviderURL: ''
    keycloakPostgresPassword: ''
    identityProviderAdminUserName: ''
    identityProviderPassword: 'admin'
    identityProviderRealm: ''
    identityProviderClientId: ''
    openShiftoAuth: false
    oAuthClientName: ''
    oAuthSecret: ''
    identityProviderImage: 'quay.io/eclipse/che-keycloak:7.15.0'
  k8s:
    ingressDomain: '192.168.251.167.nip.io'
    ingressClass: ''
    ingressStrategy: ''
    tlsSecretName: ''
    securityContextFsGroup: ''
    securityContextRunAsUser: ''
  metrics:
    enable: false
```
