### ISSUE TITLE
Plugin broker does not handle meta.yaml with version in x.x format

### ISSUE THREAD

**Issue by SDAdham** [eclipse-che/che#16340]
### Is your enhancement related to a problem? Please describe.
Devfile to test. Reproduced on che.openshift.io
```yaml
metadata:
  name: test
components:
  - type: chePlugin
    reference: >-
      https://gist.githubusercontent.com/sleshchenko/4e5a1ab9c6d20c926449ecdb5eeda54a/raw/ca9a13ac80f2f6cb7e43d6fc76d3d00ce8c5ef1b/meta.yaml
apiVersion: 1.0.0

```
<details>

<summary>Used meta.yaml<summary>

```yaml
apiVersion: v2
publisher: eamodio
name: gitlens
version: 10.2
type: VS Code extension
displayName: GitLens
title: GitLens
description: Supercharge the Git capabilities built into Visual Studio Code — Visualize code authorship at a glance via Git blame annotations and code lens, seamlessly navigate and explore Git repositories, gain valuable insights via powerful comparison commands, and so much more
icon: https://github.com/eamodio/vscode-gitlens/blob/master/images/gitlens-icon.png?raw=true
repository: https://github.com/eamodio/vscode-gitlens
category: Language
firstPublicationDate: '2020-03-12'
spec:
  extensions:
    - https://github.com/eamodio/vscode-gitlens/releases/download/v10.2.1/gitlens-10.2.1.vsix
```

</details>

here is the error:
```
Error: Failed to run the workspace: "The downloaded plugin 'eamodio/gitlens/10.2' configuration does not have the corresponding component in devfile. Devfile contains the following cheEditor/chePlugins: [redhat-developer/che-workspace-telemetry-woopra-backend/0.0.1, eclipse/che-theia/7.9.1, eclipse/che-machine-exec-plugin/7.9.1, eamodio/gitlens/null]"
```

### Describe the solution you'd like
The workspace is started OR plugin broker clearly describes that version is expected to be in x.x.x format

### Describe alternatives you've considered

I just have to be extra careful when creating `meta.yaml` and `path`

### Additional context

![image](https://user-images.githubusercontent.com/11182824/76530670-29752000-64c8-11ea-8014-51b57794098f.png)
