### ISSUE TITLE
Project tree become unavailable after deleting an OpenshiftConnector component

### ISSUE THREAD

**Issue by musienko-maxim** [eclipse-che/che#16360]
**Workspace template:**
```
metadata:
  name: test-workspace
projects:
  - name: node-js
    source:
      location: 'https://github.com/maxura/nodejs-hello-world.git'
      type: git
      branch: master
components:
  - id: redhat/vscode-openshift-connector/latest
    type: chePlugin
apiVersion: 1.0.0
```
**Env.:** minishift with deployed CHE based on Openshift 3.11, Fedora 29
**Steps to reproduce:**

1) Create a workspace with Openshift plugin and login into current cluster with UI (we can use the ws. template from this the issue)
2) Create component: select a folder  -> new component -> Create new Application -> Provide app name -> Workspace Directory -> select node-js project - Add context folder ...->Provide Component name ->select component type(nodejs latest). Push the component.
3) Delete just created component and switch to the Project explorer

**Expected result**  the Project Explorer should present
**Actual result**  There are no any items.

**Screencast:**
![openshift-connector](https://user-images.githubusercontent.com/1640058/76650203-c12b4a80-656a-11ea-8de7-be0e23e140f5.gif)
