### ISSUE TITLE
Increase amount of user namespaces on che.openshift.io fo be able to build images with buildah

### ISSUE THREAD

**Issue by vitaliy-guliy** [eclipse-che/che#16398]
### Describe the bug

Buildah require some amount of user namespaces to be allowed in the system.

https://github.com/containers/libpod/blob/master/docs/tutorials/rootless_tutorial.md#enable-user-namespaces-on-rhel7-machines

On [che.openshift.io](che.openshift.io) it set to 0 (zero).

![Screenshot from 2020-03-19 13-12-42](https://user-images.githubusercontent.com/1655894/77064529-4d64c400-69e8-11ea-883f-042f65bfbad5.png)

We need to set it to a value (15000) as it described in [buildah tutorial](https://github.com/containers/libpod/blob/master/docs/tutorials/rootless_tutorial.md#enable-user-namespaces-on-rhel7-machines).

### Steps to reproduce

1. Go to che.openshift.io and create a workspace using this devfile
```
apiVersion: 1.0.0
metadata:
  name: test-k8s2
projects:
  - name: simple-nodejs-weather-app
    source:
      location: 'https://github.com/azatsarynnyy/simple-nodejs-weather-app'
      type: git
      branch: master
components:

  - type: chePlugin
    reference: >-
      https://raw.githubusercontent.com/eclipse/che-plugin-registry/master/v3/plugins/ms-kubernetes-tools/vscode-kubernetes-tools/1.1.0/meta.yaml
    memoryLimit: 4096M

  - type: cheEditor
    reference: >-
      https://raw.githubusercontent.com/eclipse/che-plugin-registry/master/v3/plugins/eclipse/che-theia/7.10.0/meta.yaml
    memoryLimit: 1500M
```

2. Open a terminal in `vscode-kubernetes-tools` container, and run
```
$ cd /projects/simple-nodejs-weather-app/
$ buildah bud .
```

### Expected behavior
Built image.

### Runtime
   - [x] Openshift (include output of `oc version`)
