### ISSUE TITLE
Unable to clone private projects specified in devfile with login/password

### ISSUE THREAD

**Issue by benoitf** [eclipse-che/che#16402]
### Describe the bug
In the devfile I can specify projects and these projects can be private projects.

For example let's take https://bitbucket.org/f-benoit/my-private-repository.git as an example.
It's a private repository and I can enter in a devfile

```
projects:
  -
    name: private-project
    source:
      type: git
      location: "https://bitbucket.org/f-benoit/my-private-repository.git"  
```

the issue is that when the IDE is being loading, I can see the following error

Couldn't clone https://bitbucket.org/f-benoit/my-private-repository.git: Cloning into '/projects/private-project'... fatal: could not read Username for 'https://bitbucket.org': No such device or address

![image](https://user-images.githubusercontent.com/436777/77080359-80638380-69f9-11ea-9bed-b856eb4a4432.png)

The username is never prompted.

Note that performing "git clone...." and specifying the URL is asking me the login and password.

### Che version

 - [x] latest
 - [x] nightly
 - [ ] other: please specify

### Steps to reproduce

https://che.openshift.io/f?url=https://gist.githubusercontent.com/benoitf/b6f95a9c89e5083c7a30a8dd258fd1cb/raw/e46d904651e2715c59112a3f32cfcf83a015a776/git-devfile.yaml

### Expected behavior
When inside the IDE, I should be prompted for my login and password
