### ISSUE TITLE
Workspace reached timeout instead of early failure when there is exited container

### ISSUE THREAD

**Issue by sleshchenko** [eclipse-che/che#16400]
### Describe the bug
This case was already covered in the scope of https://github.com/eclipse/che/pull/15449 but seems it's broken now.

### Che version

 - [ ] latest
 - [x] nightly
 - [ ] other: please specify

### Steps to reproduce
1. Create a workspace with the following Devfile:
<defails>
<summary>Devfile</summary>

```yaml
apiVersion: 1.0.0
metadata:
  name: angular-uq3pt
components:
  - mountSources: true
    endpoints:
      - name: angular
        port: 4200
    command:
      - exit
    args:
      - '1'
    memoryLimit: 1Gi
    type: dockerimage
    image: 'quay.io/eclipse/che-nodejs10-community:7.10.0'
    alias: nodejs
```
</defails>
2. Start the workspace and wait until it reaches timeout

### Expected behavior
The workspace is early failed with error - `Container exited ....`

### Actual behavior
Workspace is failed to start because of reaching timeout although output contains error entry: failed to start container nodejs ...
![Screenshot_20200319_151401](https://user-images.githubusercontent.com/5887312/77072581-9d4a8780-69f6-11ea-8ea6-7388bdfa17cf.png)

### Runtime
   - [x] kubernetes (include output of `kubectl version`)
   - [ ] Openshift (include output of `oc version`)
   - [ ] OCP 4.4
   - [ ] minikube (include output of `minikube version` and `kubectl version`)
   - [ ] minishift (include output of `minishift version` and `oc version`)
   - [ ] docker-desktop + K8S (include output of `docker version` and `kubectl version`)
   - [ ] other: (please specify)

### Installation method
   - [x] chectl 
   - [ ] che-operator 
   - [ ] minishift-addon
   - [ ] I don't know

### Environment
   - [x] my computer
       - [ ] Windows
       - [x] Linux
       - [ ] macOS
   - [x] Cloud
       - [x] Amazon
       - [ ] Azure
       - [ ] GCE
       - [ ] other (please specify)
   - [ ] other: please specify

### Eclipse Che Logs
Sorry, I stopped VM before taking logs. Let me know if it's needed.
