### ISSUE TITLE
Add ability to specify custom labels and annotations to user namespaces

### ISSUE THREAD

**Issue by mingfang** [eclipse-che/che#16426]
### Is your enhancement related to a problem? Please describe.
Currently user namespaces are created without any labels or annotations.
I need to attach annotations to each user namespace in order to integrate with the PodNodeSelector admission controller, https://www.mgasch.com/post/podnodesel/.

### Describe the solution you'd like
I would like two new configuration settings similar to CHE_INFRA_KUBERNETES_INGRESS_ANNOTATIONS__JSON. 
Maybe call them
`CHE_INFRA_KUBERNETES_NAMESPACE_ANNOTATIONS__JSON` and `CHE_INFRA_KUBERNETES_NAMESPACE_LABELS__JSON`.
New user namespaces are either created or updated with these labels and annotations.

### Describe alternatives you've considered
My current workaround is to use the Open Policy Agent admission Webhook to add the needed annotations.  This works but it's overly complicated and lots can go wrong.
https://github.com/mingfang/terraform-k8s-modules/blob/master/examples/opa/policies/mutating.rego

### Additional context
Currently use namespaces look like this
```yaml
apiVersion: v1                                                                                                                                                                                            
kind: Namespace                                                                                                                                                                                           
metadata:                                                                                                                                                                                                 
  name: legionx-mingfang                                                                                                                                                                                  
```
But I need it to looks like this
```yaml 
apiVersion: v1
kind: Namespace
metadata:
  annotations:
    scheduler.alpha.kubernetes.io/defaultTolerations: '[{"operator": "Exists", "effect": "NoSchedule", "key": "spotInstance"}]'
    scheduler.alpha.kubernetes.io/node-selector: role=spot
  name: legionx-mingfang
```

### Release Notes Text

Che server is now able to set some custom labels and annotations on users namespaces.

For example the following labels/annotations are added to users namespace:

    label: field.cattle.io/projectId=p-8j45h
    annotation: field.cattle.io/projectId=c-57d7n:p-8j45h

if the following `customCheProperties` are added in the `CheCluster` CR:

```yaml
customCheProperties:
      CHE_INFRA_KUBERNETES_NAMESPACE_ANNOTATIONS: che.eclipse.org/username=<username>,field.cattle.io/projectId=c-57d7n:p-8j45h
      CHE_INFRA_KUBERNETES_NAMESPACE_LABELS: app.kubernetes.io/part-of=che.eclipse.org,app.kubernetes.io/component=workspaces-namespace,field.cattle.io/projectId=p-8j45h
```
