### ISSUE TITLE
 Can't access to port 22 from theia.

### ISSUE THREAD

**Issue by kellyhyomin** [eclipse-che/che#16422]
## Summary

My custom devfile.yaml is below.
```yaml
---
apiVersion: 1.0.0
metadata:
  generateName: r19-11-apd-2020-03-03
components:
- type: dockerimage 
  alias: ssh-test-container
  image: popcornsar/ssh-custom-image
  endpoints:
    - name: 'ssh-test-container'
      port: 22
      attributes:
        discoverable: "true"
        public: "false"
  mountSources: true
  memoryLimit: 2048Mi
  command: ['tail']
  args: ['-f', '/dev/null']
-
  type: dockerimage
  alias: mysql
  image: docker.io/centos/mysql-57-centos7
  env:
    - name: MYSQL_USER
      value: petclinic
    - name: MYSQL_PASSWORD
      value: petclinic
    - name: MYSQL_DATABASE
      value: petclinic
    - name: PS1
      value: $(echo ${0})\\$
  memoryLimit: 300Mi
  endpoints:
    - name: 'db'
      port: 3306
      attributes:
        discoverable: "true"
        public: "false"
  mountSources: true
``` 
When creating a workspace with the stack, the mysql container 3306 port can be connected from theia terminal. 
However, I cannot connect to the ssh-test-container port 22.
I want to access port 22 from theia. How can i solve this problem?

### Che version
7.4.0

### Installation method
helm

### Environment
Amazon EKS

**Comment by ibuziuk** [comment]
@kellyhyomin are you exposing port 22 on in the `popcornsar/ssh-custom-image` ?

**Comment by kellyhyomin** [comment]
@ibuziuk 
Yes. We exposed port 22 in the image.

**Comment by ibuziuk** [comment]
@kellyhyomin could you please point to the dockerfile?

**Comment by kellyhyomin** [comment]
@ibuziuk 

Thank you for your help.
Do I just need EXPOSE 22 in the Dockerfile?

**Comment by ibuziuk** [comment]
well, if the port is not exposed on the image level, it will not be accessible for sure.

**Comment by kellyhyomin** [comment]
@ibuziuk 
Port 22 is set to EXPOSE.
Our Dockerfile works fine when run with docker.
I cannot connect to 22 only when I run it with devfile.yaml.
I wonder if I need any other settings.

**Comment by ibuziuk** [comment]
@skabashnyuk any comments^ ?

**Comment by skabashnyuk** [comment]
sshd not running?

**Comment by kellyhyomin** [comment]
@skabashnyuk 
sshd is running.
When running in docker with the same image, ssh connection is possible without any problem.

**Comment by kellyhyomin** [comment]
I tested it by changing the endpoint of the java-mysql stack from port 3306 to port 3307.(https://github.com/eclipse/che-devfile-registry/blob/5a41b4b0c85893a6ee99059fcceab35b8a71780c/devfiles/java-mysql/devfile.yaml#L55)
However, only the 3306 port is connected.
I would appreciate it if you could confirm this.

**Comment by kellyhyomin** [comment]
The screenshot below is a screen that normally accessed ssh when I ran the same image as a docker.
![image (3)](https://user-images.githubusercontent.com/29850624/77519640-2b28e580-6ec3-11ea-949f-7ad49d98d3ba.png)
I tested all the settings I could do in the devfile on by one, but the ssh connection is not working.
All I want is to connect to the ssh of another container(expose 22) in the same pod from theia terminal.
Please help me.

**Comment by skabashnyuk** [comment]
@kellyhyomin can you share devfile with public images so I can test it? Unfortunately, I can't pull `popcornsar/ssh-custom-image`  looks like it is private.

**Comment by kellyhyomin** [comment]
Thank you for your reply.

Here is our devfile.yaml
The image(popcornsar/ap-virtual-simulator:port22) is currently public.

```yaml
---
apiVersion: 1.0.0
metadata:
  generateName: r19-11-apd-2020-03-03
components:
-
  type: cheEditor
  id: popcornsar/r19-11-apd/2020-03-03-multi
  alias: r19-11-apd-2020-03-03
- 
  type: dockerimage 
  alias: ap-virtual-simulator
  image: popcornsar/ap-virtual-simulator:port22
  endpoints: 
    - name: ap-virtual-simulator
      port: 22
      attributes:
        discoverable: "true"
        public: "true"
  mountSources: true
  memoryLimit: 2048Mi
``` 
Our editor is theia, not che-theia.
However, when tested on che-theia, I also cannot connect to port 22.

**Comment by sleshchenko** [comment]
@kellyhyomin Are you connecting via ssh through server URL provided by Che from outside of Kubernetes cluster?
If yes - then probably Ingress is not able to proxy ssh protocol =( You can try to search more info on the internet, AFAIK @vparfonov tried to achieve it and did not manage to do.
The way how you can work around it - use `kubectl portforward`

If you're trying to establish ssh connection withing workspace ( from one container to another) then since all containers in the same pod share the same ports range, try to connect to localhost:22 instead of using server url.

**Comment by kellyhyomin** [comment]
I have tried to establish ssh connection within workspace(from on container(thiea) to another) but the connection to localhost:22 is not working.

![image](https://user-images.githubusercontent.com/29850624/77625687-5b39bc80-6f87-11ea-80b7-d4838c8e7863.png)

I also know that containers within the same pod share the same port range, but I don't know why I can't connect.

**Comment by sleshchenko** [comment]
> @skabashnyuk
> sshd is running.
> When running in docker with the same image, ssh connection is possible without any problem.

@kellyhyomin  But when you run it with docker you don't override entrypoint.
But in devfile you have
```
- type: dockerimage 
  alias: ssh-test-container
  image: popcornsar/ssh-custom-image
  endpoints:
    - name: 'ssh-test-container'
      port: 22
      attributes:
        discoverable: "true"
        public: "false"
  mountSources: true
  memoryLimit: 2048Mi
  command: ['tail']
  args: ['-f', '/dev/null']
```
So, the only process is launched in container is `tail`...
Could you try to remove command/args from here or launch ssh daemon explicitly?
I may be wrong =)
