### ISSUE TITLE
override `workdir` in devfile dockerimage component type

### ISSUE THREAD

**Issue by sunix** [eclipse-che/che#16487]
### Is your enhancement related to a problem? Please describe.
Override or set `workdir` for a dockerimage. So when opening the terminal we jump into a custom folder like `/projects`

### Describe the solution you'd like
In the devfile, be able to have a `workdir` attribute:

```yaml
  - alias: asciidoctor
    mountSources: true
    args:
      - sleep
      - infinity
    memoryLimit: 768Mi
    type: dockerimage
    image: quay.io/sunix/asciidoctor
    workdir: '/projects'
```
