### ISSUE TITLE
Failed to get the workspace: Unauthorized

### ISSUE THREAD

**Issue by RomanNikitenko** [eclipse-che/che#16507]
### Describe the bug
I get the error `Failed to get the workspace: Unauthorized` each time I create a new workspace
The issue is fixed by refreshing a page

### Che version

 - [ ] latest
 - [x] nightly
 - [ ] other: please specify

### Steps to reproduce
1. `minikube start --driver=kvm2 --memory=16384 --cpus=4`
2. `chectl server:start --self-signed-cert --installer=operator --platform=minikube`
3. Go to dashborad using Firefox
4. `Add Workspace` -> `Import Devfile` ->  `YAML`
5. Put content of a devfile, for example:
<details>
<summary>Devfile</summary>

```
metadata:
  name: che-in-che-theia
attributes:
  persistVolumes: 'false'
projects:
  - name: che-theia
    source:
      location: 'https://github.com/eclipse/che-theia.git'
      type: git
  - name: theia
    source:
      location: 'https://github.com/eclipse-theia/theia.git'
      type: git
      branch: master
components:
  - mountSources: true
    endpoints:
      - name: theia-dev-flow
        port: 3010
        attributes:
          protocol: http
          public: 'true'
    memoryLimit: 4Gi
    type: dockerimage
    alias: che-dev
    image: 'quay.io/eclipse/che-theia-dev:next'
  - id: redhat/vscode-yaml/latest
    type: chePlugin
  - id: che-incubator/typescript/latest
    memoryLimit: 2048M
    type: chePlugin
  - id: eclipse/che-theia/next
    memoryLimit: 2Gi
    type: cheEditor
    alias: theia-editor
apiVersion: 1.0.0
commands:
  - name: start hosted instance
    actions:
      - workdir: /projects/theia/examples/assembly
        type: exec
        command: >
          yarn theia start --hostname=0.0.0.0 --port=3130
          --plugins=local-dir:../../../che-theia/plugins
        component: che-dev
  - name: 'che:theia:init'
    actions:
      - workdir: /projects/theia
        type: exec
        command: |
          che-theia init
        component: che-dev
  - name: 'theia:build'
    actions:
      - workdir: /projects/theia
        type: exec
        command: |
          yarn
        component: che-dev
  - name: 'che-theia:build'
    actions:
      - workdir: /projects/che-theia
        type: exec
        command: |
          yarn
        component: che-dev

```
</details>

6. `Create and Open`

### Runtime
   - [ ] kubernetes (include output of `kubectl version`)
   - [ ] Openshift (include output of `oc version`)
   - [x] minikube (include output of `minikube version` and `kubectl version`)
   - [ ] minishift (include output of `minishift version` and `oc version`)
   - [ ] docker-desktop + K8S (include output of `docker version` and `kubectl version`)
   - [ ] other: (please specify)

### Screenshots
![unauthorized](https://user-images.githubusercontent.com/5676062/78127234-750e5000-741c-11ea-8264-5da450868d5c.gif)

### Installation method
   - [x] chectl 
   - [ ] che-operator 
   - [ ] minishift-addon
   - [ ] I don't know

### Environment
   - [ ] my computer
       - [ ] Windows
       - [x] Linux
       - [ ] macOS
   - [ ] Cloud
       - [ ] Amazon
       - [ ] Azure
       - [ ] GCE
       - [ ] other (please specify)
   - [ ] other: please specify
