### ISSUE TITLE
[devworkspace] Initialize kubeconfig with user's token if useBearerToken is configured

### ISSUE THREAD

**Issue by sleshchenko** [eclipse-che/che#16576]
### Is your task related to a problem? Please describe.
There is a plan to initialize kubectx for the current user to avoid additional login.
This task is about initializing kubeconfig with user's token if useBearerToken is configured.
There are two ways to achieve it:

1. Init kubeconfig somewhere like `/tmp/.kube/config` and set KUBECONFIG env var:

<details>
<summary>Kube Context Template</summary>

```yaml
apiVersion: v1
clusters:
- cluster:
    certificate-authority-data: $(cat /var/run/secrets/kubernetes.io/serviceaccount/ca.crt)
    server: https://$KUBERNETES_SERVICE_HOST:$KUBERNETES_SERVICE_PORT_HTTPS
  name: kubernetes-service
users:
- name: $(USER_NAME, like the output of oc whoami or some hardcoded)
  user:
    token: $(USER_TOKEN_HERE)
contexts:
- context:
    cluster: kubernetes-service
    namespace: ????
    user: USER_NAME
  name: $(CTX_NAME any)
current-context: $CTX_NAME
kind: Config
```
</details>

2. Do oc login and let oc init kubeconfig in the default location `~/.kube/config`
`oc login --token=$(TOKEN_HERE) https://$KUBERNETES_SERVICE_HOST:$KUBERNETES_SERVICE_PORT_HTTPS --certificate-authority=/var/run/secrets/kubernetes.io/serviceaccount/ca.crt`
^ it won't work is oc is not available in PATH... the first is more general and would work with kubectl.

P.S. The user's token is available only when Cloud-Shell is opened in browser (not container start). And this token might be expired. So it makes sense to update token in kubeconfig after each page reload.

P.S.S. I wonder that some issues may happen during context initialing. In such case I would not break terminal initializing but would propagate that user needs do `oc login manually` or try refresh a page.
