### ISSUE TITLE
pulling a custom docker image from a local not HTTPS docker registry

### ISSUE THREAD

**Issue by ultrafab** [eclipse-che/che#16614]
Hello, i've created a test devfile to pull an Ubuntu image with custom tools:

```
metadata:
  name: MyDevfile
components:
  - mountSources: true
    command:
      - sleep
      - infinity
    memoryLimit: 512Mi
    type: dockerimage
    alias: ubuntu
    image: '192.168.69.206:5000/my-ubuntu:2.0'
apiVersion: 1.0.0
```
Running the workspace i receive this error:

`Error: Failed to run the workspace: "Unrecoverable event occurred: 'Failed', 'Failed to pull image "192.168.69.206:5000/my-ubuntu:2.0": rpc error: code = Unknown desc = Error response from daemon: Get https://192.168.69.206:5000/v2/: http: server gave HTTP response to HTTPS client', 'workspace1grh40aawaiokuav.ubuntu-64948c686f-nkwxc'"`

Is there a way to pull the image from the local registry, without an HTTPS connection?

Pulling the same docker from command line doesn't give any error.

Thanks!
