### ISSUE TITLE
I have no name! instead of user name in terminal running custom devfile

### ISSUE THREAD

**Issue by ultrafab** [eclipse-che/che#16618]
After creating a custom minimal devfile:
```
metadata:
  name: MyDevfile
components:
  - mountSources: true
    args:
      - sleep
      - infinity
    memoryLimit: 512Mi
    type: dockerimage
    alias: ubuntu
    image: picoded/ubuntu-openjdk-8-jdk
apiVersion: 1.0.0
```
Opening the terminal and executing `/bin/bash` the user has no name:
`I have no name!@workspace1grh40aawaiokuav:/workspace$`

Also any command requiring root privileges is unauthorized.

I'm trying using multiple standard docker images, but found the same problem.
I need a vanilla system where i can try to install some tools, so having a basic user, sudo and root privileges is mandatory.
