### ISSUE TITLE
don't create an extra service for discoverable endpoint

### ISSUE THREAD

**Issue by sparkoo** [eclipse-che/che#16657]
### Describe the bug
Currently we create 2 services for every discoverable endpoint. This is waste of resources as we don't need it to do our job done.

devfile
```yaml
metadata:
  name: wksp-buoj
projects:
  - name: example
    source:
      location: 'https://github.com/golang/example.git'
      type: git
    clonePath: src/github.com/golang/example/
components:
  - mountSources: true
    endpoints:
      - name: go-tcp
        port: 8080
        attributes:
          discoverable: 'true'
    memoryLimit: 512Mi
    type: dockerimage
    alias: go-cli
    image: 'quay.io/eclipse/che-golang-1.12:nightly'
apiVersion: 1.0.0
commands:
  - name: run outyet
    actions:
      - workdir: '${CHE_PROJECTS_ROOT}/src/github.com/golang/example/outyet'
        type: exec
        command: go get -d && go run main.go
        component: go-cli
```

### Che version

 - [x] latest

### Steps to reproduce

1. create workspace from devfile above
1. see services it created
  ```
[~] λ kc get services -n che-che
NAME                          TYPE        CLUSTER-IP      EXTERNAL-IP   PORT(S)                                  AGE
go-tcp                        ClusterIP   10.106.37.118   <none>        8080/TCP                                 4m18s
server0428va3l-go-cli         ClusterIP   10.111.36.196   <none>        8080/TCP                                 4m18s
serverlzh40tkp-jwtproxy       ClusterIP   10.100.27.253   <none>        4400/TCP,4401/TCP,4402/TCP               4m18s
serverv9yts2xr-theia-idee6b   ClusterIP   10.100.110.63   <none>        3130/TCP,13133/TCP,13132/TCP,13131/TCP   4m18s
```
There are 2 services for 8080, first has discoverable `go-tcp` name, and second has generated one.

### Expected behavior
We should create only one service and use it. The name of the service should be determined based on `discoverable` attribute.

### Runtime
   - [x] minikube (include output of `minikube version` and `kubectl version`)

### Installation method
   - [x] chectl 

### Environment
   - [x] my computer
       - [x] Linux
