### ISSUE TITLE
secure discoverable endpoint is not secure

### ISSUE THREAD

**Issue by sparkoo** [eclipse-che/che#16656]
### Describe the bug
having an endpoint that is both `secure` and `discoverable`, makes the endpoint unsecure.

We're hiding *secure* endpoints behind jwtproxy AND we're creating extra service for *discoverable* endpoints so it have predictable name. This makes every discoverable endpoint unsecure.

devfile:
```yaml
metadata:
  name: wksp-buoj
projects:
  - name: example
    source:
      location: 'https://github.com/golang/example.git'
      type: git
    clonePath: src/github.com/golang/example/
components:
  - mountSources: true
    endpoints:
      - name: go-endpoint
        port: 8080
        attributes:
          secure: 'true'
          discoverable: 'true'
    memoryLimit: 512Mi
    type: dockerimage
    alias: go-cli
    image: 'quay.io/eclipse/che-golang-1.12:nightly'
apiVersion: 1.0.0
commands:
  - name: run outyet
    actions:
      - workdir: '${CHE_PROJECTS_ROOT}/src/github.com/golang/example/outyet'
        type: exec
        command: go get -d && go run main.go
        component: go-cli
```

### Che version
 - [x] latest

### Steps to reproduce
1. create workspace from devfile above
1. see services it created. There should be `go-endpoint` service, that is accessible without any security.

### Expected behavior
I can see 3 possible solutions to this:
 1. somehow make it possible to have secure&discoverable endpoint (I don't know how)
 1. forbid such combination and fail as soon as possible
 1. document the issue and keep current behavior as is

### Runtime
   - [x] minikube (include output of `minikube version` and `kubectl version`)

### Installation method
   - [x] chectl 

### Environment
   - [x] my computer
       - [x] Linux
