### ISSUE TITLE
Adding Label, NodeSelector and Ressource to che-operator CR

### ISSUE THREAD

**Issue by startxfr** [eclipse-che/che#16662]
### Is your enhancement related to a problem? Please describe.
Che Operator CR doesn't have capacity to add custom label and nodeSelector

### Describe the solution you'd like
Add a label, resource and nodeSelector section in the org.eclipse.che/v1 CheCluster CR for server, database and auth section 
example : 
```yaml
    nodeSelector:
      infra: true
    label:
      app.kubernetes.io/name: "Che keycloack"
    resources:
      limits:
        cpu: 1000m
        memory: 256Mi
      requests:
        cpu: 200m
        memory: 128Mi
```

### Describe alternatives you've considered
Possibility to add a global section describing nodeSelector and label to apply for all deployable resources

### Additional context
Che CR example 

```yaml
kind: CheCluster
apiVersion: org.eclipse.che/v1
metadata:
  name: codeready-workspaces
  namespace: example
spec:
  server:
    cheDebug: "false"
    cheLogLevel: INFO
    cheImageTag: ""
    cheFlavor: codeready
    devfileRegistryImage: ""
    pluginRegistryImage: ""
    externalDevfileRegistry: false
    externalPluginRegistry: false
    tlsSupport: false
    selfSignedCert: false
    nodeSelector:
      infra: true
    label:
      app.kubernetes.io/name: "Che server"
    resources:
      limits:
        cpu: 1000m
        memory: 256Mi
      requests:
        cpu: 200m
        memory: 128Mi
  database:
    externalDb: false
    chePostgresHostName: postgres
    chePostgresPort: "5432"
    chePostgresUser: pgche
    chePostgresPassword: 6OywNH2H6xBF
    chePostgresDb: dbche
    nodeSelector:
      infra: true
    label:
      app.kubernetes.io/name: "Che database"
    resources:
      limits:
        cpu: 1000m
        memory: 256Mi
      requests:
        cpu: 200m
        memory: 128Mi
  auth:
    openShiftoAuth: true
    identityProviderImage: ""
    externalIdentityProvider: false
    identityProviderURL: ""
    identityProviderRealm: "codeready"
    identityProviderClientId: "codeready-public"
    updateAdminPassword: false
    identityProviderPostgresPassword: DPYk6Cg14U76
    identityProviderPassword: xh6zPMBQRBp8
    identityProviderAdminUserName: admin
    nodeSelector:
      infra: true
    label:
      app.kubernetes.io/name: "Che keycloack"
    resources:
      limits:
        cpu: 1000m
        memory: 256Mi
      requests:
        cpu: 200m
        memory: 128Mi
  storage:
    preCreateSubPaths: true
    pvcClaimSize: 1Gi
    pvcStrategy: per-workspace
```

**Comment by tolusha** [comment]
@startxfr 
Could you provide more details, why do you need custom labels?

**Comment by startxfr** [comment]
Hi @tolusha 

Indeed, my example with a `app.kubernetes.io/name` label is not the best use case ;)

`labels` could be useful to group che pods with a comon label shared with other pods runing in the same or other namespaces. 
When doing logging or monitoring whe can agregate related information. 
When doing metering for chargeback, we could have a common label to calculate consumed resources for a given developer, or customer.

```yaml
label:
      customer: "my-customer-id"
      developer: "my-user-id"
```

`NodeSelector` is more useful for placing pod on node dedicated to infrastructure, or software-factory thus optimizing the cluster capacity and resource partitionning.

`resource` will also allow us to configure fine-grained usage of consimed resource and improve usage of Quota and limitRange.
