### ISSUE TITLE
Shared volumes in K8S initContainers

### ISSUE THREAD

**Issue by filipkroupa** [eclipse-che/che#16745]
## Relevant information

Following #16505 we tried to use volume sharing. We need sharing between types `chePlugin `and `kubernetes`, specifically `kubernetes` defined inline by `referenceContent ` and containing `initContainers`.
```
apiVersion: 1.0.0
metadata:
  name: MainframeBasicStackInternal-volshr
components:
- 
  type: chePlugin
  id: bitlang/cobol/latest
-
  type: chePlugin
  id: broadcommfd/cobol-language-support/latest
  volumes:
   -
    name: zowe-home
    containerPath: /home/user/.zowe
- alias: zowe-cli
  type: kubernetes
  mountSources: true
  volumes:
   -
    name: zowe-home
    containerPath: /.zowe
  referenceContent: |
    kind: List
    items:
     -
      apiVersion: v1
      kind: Pod
      metadata:
       name: zowe
      spec:
       containers:
        -
         image: 'ca-docker-brightside-docker.bintray.io/cli-mainframe-basic-stack:2020-02-13T23-41-08'
         env:
          - name: THEIA_PLUGINS
            value: local-dir:///plugins
          - name: ZOWE_CLI_HOME
            value: /home/user/.zowe
         name: cli
         resources:
          limits:
           memory: 1024Mi
       initContainers:
        -
         name: plugin-container
         image: 'ca-docker-brightside-docker.bintray.io/cli-mainframe-basic-plugins:2020-02-13T23-41-08'
         command: ["/bin/sh", "-c", "if [ -z \"$(ls -1A /.zowe)\" ]; then cp -r /.zowe_init/* /.zowe; fi"]
```

Unfortunately it seems volume is only shared with container and not shared with the initContainer, which is needed in this scenario. Is there a change in devfile configuration which would achieve sharing of volume between container and initContainer? Or should I open it as proposal for enhancement?
