### ISSUE TITLE
Support shared volumes in K8S initContainers 

### ISSUE THREAD

**Issue by filipkroupa** [eclipse-che/che#16775]
### Is your enhancement related to a problem? Please describe.

We need sharing of volumes for type `kubernetes` to also share volume to `initContainers`, not just `contianers`. Consider devfile like this:
```
apiVersion: 1.0.0
metadata:
  name: MainframeBasicStackInternal-volshr
components:
- 
  type: chePlugin
  id: bitlang/cobol/latest
-
  type: chePlugin
  id: broadcommfd/cobol-language-support/latest
  volumes:
   -
    name: zowe-home
    containerPath: /home/user/.zowe
- alias: zowe-cli
  type: kubernetes
  mountSources: true
  volumes:
   -
    name: zowe-home
    containerPath: /.zowe
  referenceContent: |
    kind: List
    items:
     -
      apiVersion: v1
      kind: Pod
      metadata:
       name: zowe
      spec:
       containers:
        -
         image: 'ca-docker-brightside-docker.bintray.io/cli-mainframe-basic-stack:2020-02-13T23-41-08'
         env:
          - name: THEIA_PLUGINS
            value: local-dir:///plugins
          - name: ZOWE_CLI_HOME
            value: /home/user/.zowe
         name: cli
         resources:
          limits:
           memory: 1024Mi
       initContainers:
        -
         name: plugin-container
         image: 'ca-docker-brightside-docker.bintray.io/cli-mainframe-basic-plugins:2020-02-13T23-41-08'
         command: ["/bin/sh", "-c", "if [ -z \"$(ls -1A /.zowe)\" ]; then cp -r /.zowe_init/* /.zowe; fi"]
```

### Describe the solution you'd like

When `volumes` property is used for type `kubernetes`,  defined volume is shared between `initContainers` and `contianers`.
Absolutely ideal would be, if `volumes` would have new property `initContainerPath` describing path for initContainer - in cases where mount paths in pod's containers and initContainers are different. Otherwise using shared volume might require change in initContainer code.

### Additional context

Related question #16745
