### ISSUE TITLE
Using plugin toggles in dashboard removes all non registry plugins

### ISSUE THREAD

**Issue by amisevsk** [eclipse-che/che#16783]
### Describe the bug
Using the toggles in the plugins tab will remove all plugins in the devfile that are not listed by `id`. This change cannot be undone, potentially losing any plugin customization in the devfile permanently.

### Che version

 - [x] latest
 - [x] CRW 2.1.1

### Steps to reproduce

1. Create workspace from the devfile `initial-devfile.yaml` below
2. Go to workspace details -> plugins tab, enable a plugin (e.g. Java)
3. Check workspace devfile, golang plugin added by `reference:` is removed (see `updated-devfile.yaml`)

<details><summary>initial-devfile.yaml</summary>
<p>

```yaml
apiVersion: 1.0.0
metadata:
  name: plugins-test
projects:
  - name: example
    source:
      location: 'https://github.com/golang/example.git'
      type: git
    clonePath: src/github.com/golang/example/
attributes:
  persistVolumes: 'false'
components:
  - memoryLimit: 512Mi
    preferences:
      go.lintFlags: '--fast'
      go.useLanguageServer: true
      go.lintTool: golangci-lint
    type: chePlugin
    reference: >-
      https://raw.githubusercontent.com/eclipse/che-plugin-registry/master/v3/plugins/ms-vscode/go/0.11.4/meta.yaml
    alias: go-plugin
    env:
      - value: 'off'
        name: GO111MODULE
  - mountSources: true
    endpoints:
      - name: 8080/tcp
        port: 8080
    memoryLimit: 512Mi
    type: dockerimage
    image: 'quay.io/eclipse/che-golang-1.12:nightly'
    alias: go-cli
    env:
      - value: '/go:$(CHE_PROJECTS_ROOT)'
        name: GOPATH
      - value: /tmp/.cache
        name: GOCACHE

```

</p>
</details>

<details><summary>updated-devfile.yaml</summary>
<p>

```yaml
metadata:
  name: plugins-test
projects:
  - name: example
    source:
      location: 'https://github.com/golang/example.git'
      type: git
    clonePath: src/github.com/golang/example/
attributes:
  persistVolumes: 'false'
components:
  - mountSources: true
    endpoints:
      - name: 8080/tcp
        port: 8080
    memoryLimit: 512Mi
    type: dockerimage
    image: 'quay.io/eclipse/che-golang-1.12:nightly'
    alias: go-cli
    env:
      - value: '/go:$(CHE_PROJECTS_ROOT)'
        name: GOPATH
      - value: /tmp/.cache
        name: GOCACHE
  - id: redhat/java/latest
    type: chePlugin
apiVersion: 1.0.0
```

</p>
</details>

### Expected behavior
Plugins that are not imported from the plugin registry should not be affected by plugin toggles.
