### ISSUE TITLE
[UD] Devfile editor sometimes reorders fields

### ISSUE THREAD

**Issue by akurinnoy** [eclipse-che/che#16797]
### Is your task related to a problem? Please describe.

While dumping a devfile object the order of fields may change from time to time. This behaviour is quite confusing so we need make the devfile editor to preserve fields order.

### Describe the solution you'd like

Yaml parser used in Dashboard has ability to provide the `sortKeys` callback. We need to provide reliable function for sorting the devfile keys.

### Describe alternatives you've considered

Set the `sortKeys` option as `true` will force yaml parser to sort fields alphabetically. 

### Additional context

https://github.com/eclipse/che-dashboard/pull/22#pullrequestreview-401731334

**Comment by sleshchenko** [comment]
I think instead of sorting keys alphabetically it makes more sense to prepare order that will be easy to read...
Like with alphabetic order we would have
```yaml
apiVersion: 1.0.0
commands:
  - name: build without tests
    actions:
      - 
        command: mvn clean install -DskipTests
        component: maven
        type: exec
        workdir: ${CHE_PROJECTS_ROOT}/che
components:
  - 
    alias: maven
    image: quay.io/eclipse/che-java11-maven:nightly
    memoryLimit: 2Gi
    mountSources: true
    type: dockerimage
    volumes:
      - name: maven
        containerPath: /home/user/.m2
  - type: chePlugin
    id: redhat/java11/latest
metadata:
  name: che-server-in-che
```
When the order is logical and we used to:
```yaml
apiVersion: 1.0.0
metadata: # it's a short section that identifies devfile. It's why it's at the beginning
  name: che-server-in-che
components:
  - type: dockerimage // everycomponent has type, it tells reader what expect from fields above
    alias: maven
    image: quay.io/eclipse/che-java11-maven:nightly // the most important and required field for dockerimage
    mountSources: true
    memoryLimit: 2Gi
    volumes:
      - name: maven
        containerPath: /home/user/.m2
  - type: chePlugin
    id: redhat/java11/latest
commands:
  - name: build without tests
    actions:
      - type: exec
        component: maven
        command: mvn clean install -DskipTests
        workdir: ${CHE_PROJECTS_ROOT}/che
```
Kubernetes/OpenShift seems to order objects fields in some custom way as well. Probably even on server-side (better to double-check)

**Comment by sleshchenko** [comment]
As the first step, we're going to sort the top-level fields in the following way:
```yaml
apiVersion: ...
metadata: ...
components: ...
commands: ...
attributes: ...
```
Then it's less critical and we will need to agree on the fields order on the lower levels:
- metadata
- sorting components like by type: cheEditor, chePlugins, dockerimage, kubernetes, openshift?
- components fields per each time
- attributes (probably we should leave them as is)
