### ISSUE TITLE
Jupyter Notebooks native support through latest Python VS Code extension

### ISSUE THREAD

**Issue by l0rd** [eclipse-che/che#16818]
### Is your enhancement related to a problem? Please describe.

Latest python extension includes [jupyter support](https://code.visualstudio.com/docs/python/jupyter-support). I have tried it out but loading a jupyter notebook failed.

![image](https://user-images.githubusercontent.com/606959/80770537-d840ee80-8b50-11ea-812e-e7b486ea110a.png)

To try it out on che.osio --> [![Contribute](https://che.openshift.io/factory/resources/factory-contribute.svg)](https://che.openshift.io/f?url=https://gist.githubusercontent.com/l0rd/7190c65773a23f393a839598b22f3c1a/raw/ded49ccffa023c243a1c6e26f292696cc02ff504/devfile.yaml)

### Describe the solution you'd like

This is the devfile I have been using:

```yaml
devfile.yaml
---
apiVersion: 1.0.0
metadata:
  name: python-workspace
projects:
  - name: jupyter-hello-world1
    source:
      location: 'https://github.com/chasbecker/TextAnalysis.git'
      type: git
components:
  - type: chePlugin
    alias: ms-python/python/latest
    reference: https://gist.github.com/l0rd/7190c65773a23f393a839598b22f3c1a/raw/meta.yaml
    memoryLimit: 512Mi
  - type: cheEditor
    alias: che-theia
    reference: https://gist.github.com/l0rd/7190c65773a23f393a839598b22f3c1a/raw/theia.yaml
    memoryLimit: 512Mi
  - type: chePlugin
    alias: machine-exec
    id: eclipse/che-machine-exec-plugin/latest
```

vscode python meta.yaml

```yaml
vscode-python-meta.yaml
---
apiVersion: v2
publisher: ms-python
name: python
version: 2020.4.76186
type: VS Code extension
displayName: Python
title: Python extension
description: Linting, Debugging (multi-threaded, remote), Intellisense, code formatting,
  refactoring, unit tests, snippets, and more.
icon: https://www.eclipse.org/che/images/logo-eclipseche.svg
repository: https://github.com/Microsoft/vscode-python
category: Language
firstPublicationDate: '2020-04-27'
spec:
  containers:
  - image: "quay.io/eclipse/che-sidecar-python:3.7.3-8f39348"
    name: vscode-python
    memoryLimit: '512Mi'
  extensions:
  - https://github.com/microsoft/vscode-python/releases/download/2020.2.62710/ms-python-release.vsix
```

### Describe alternatives you've considered

I have also tried to add python in che-theia container:

```dockerfile
FROM quay.io/eclipse/che-theia:7.12.0

USER root

RUN apk add --no-cache python3

# make some useful symlinks that are expected to exist
RUN cd /usr/bin \
	&& ln -s idle3 idle \
	&& ln -s pydoc3 pydoc \
	&& ln -s python3 python \
	&& ln -s python3-config python-config

USER theia
```

But it didn't help

### Sub-tasks
- [x] `vscode.workspace.fs` API https://github.com/eclipse-theia/theia/pull/7908
- [x] Adapt Che Theia to the new Theia FS API https://github.com/eclipse/che/issues/17357
- [x] Che Theia Web View doesn't work properly when a plugin is running in its own sidecar https://github.com/eclipse/che/issues/16870
- [x] Adapt `vscode.workspace.fs` Plug-in API to Che-Theia's remote plugin system https://github.com/eclipse/che/issues/19110
