### ISSUE TITLE
Implement a single host version of the happy-path test

### ISSUE THREAD

**Issue by l0rd** [eclipse-che/che#16842]
### Is your task related to a problem? Please describe.

[Single host](https://www.eclipse.org/che/docs/che-7/configuring-workspace-exposure-strategies/#single-host-strategy) is not currently tested.

### Describe the solution you'd like

Implement an happy path tests to address that.

cc @dmytro-ndp @rhopp

**Comment by l0rd** [comment]
That's important considered #16702 and #12914

**Comment by rhopp** [comment]
@l0rd Should single host already work also for Openshift, or is it still just a k8s (ingress) thing? (Asking to beter understand a scope of this)

**Comment by l0rd** [comment]
@rhopp it only works on Kubernetes right now. We are working on https://github.com/eclipse/che/issues/16702 and https://github.com/openshift/origin/issues/20474 to have support on OpenShift routes as well.

**Comment by l0rd** [comment]
> Also... If we would have to make a decision which "version" (single vs multi host) should be the "primary" target for our testing - is it safe to assume, that single-host will be the more important (in the near future)?

Yes

**Comment by rhopp** [comment]
I've created "subtask" for switching k8s based tests/jobs to single-host: https://github.com/eclipse/che/issues/16904

**Comment by sparkoo** [comment]
as of today, gateway single-host **che-server** part is merged in master and is in nightly images at `quay.io/eclipse/che-server:nightly`. We're working on the che-operator. There is "working" testing image `quay.io/lkrejci/che-operator:gateway`.

to deploy gateway single-host, use this CheCluster patch:
```
apiVersion: org.eclipse.che/v1
kind: CheCluster
metadata:
  name: eclipse-che
spec:
  server:
    serverExposureStrategy: 'single-host'
    singleHostWorkspaceExposureType: 'gateway'
    customCheProperties:
      CHE_INFRA_KUBERNETES_SINGLEHOST_WORKSPACE_EXPOSURE: 'gateway'
```
with this chectl command (don't forget to set `<platform>`):
```
chectl server:start --installer=operator --platform=<platform> --che-operator-image=quay.io/lkrejci/che-operator:gateway --che-operator-cr-patch-yaml=op.patch
```

There are these known limitations/WIP:
 - the extra `CHE_INFRA_KUBERNETES_SINGLEHOST_WORKSPACE_EXPOSURE` property is needed, because we've changed the parameter name in che-server and it is not yet synced in che-operator image (will be managed with `singleHostWorkspaceExposureType: 'gateway'`)
 - devfile/plugin registries and keycloak are still deployed with their own Ingress/Route. (under development)
