### ISSUE TITLE
How to develop Multi-Pod workspace

### ISSUE THREAD

**Issue by haiye1018** [eclipse-che/che#16850]
I want to develop microservice app using Eclipse che deployed in k8s, as you know, all containers defined in one devfile are deployed in one k8s pod, this will get some difficult. In the che document, I guess one workspace pod is one k8s pod, but i find the post, 
- https://che.eclipse.org/using-eclipse-che-to-develop-multi-container-apps-eb45b32ffe5b
Yevhen's workspace has Machines, Installers, Servers menu, Anyone who know how to get this style workspace?

this is my devfile, these container will be in one k8s pod, 
```yaml
apiVersion: 1.0.0
metadata:
  generateName: hdev-
components:
  - alias: hdev
    type: kubernetes
    reference: hdevc.yaml
    referenceContent: |
      apiVersion: v1
      kind: List
      items:
      -
        apiVersion: v1
        kind: Pod
        metadata:
          name: h1
        spec:
          restartPolicy: Never
          containers:
          - name: h1
            image: ...
            imagePullPolicy: IfNotPresent
            env:
            - name: app-11
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
      -
        apiVersion: v1
        kind: Pod
        metadata:
          name: h2
        spec:
          restartPolicy: Never
          containers:
          - name: h2
            image: ...
            imagePullPolicy: IfNotPresent
            env:
            - name: app-12
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
```
