### ISSUE TITLE
Lifecycle description doesn't respect if described in meta.yaml in plugin registry

### ISSUE THREAD

**Issue by vparfonov** [eclipse-che/che#16855]
1. Add to the meta.yaml description like this
```
....
spec:
  containers:
   - name: che-rsync
     image: "image:tag"
     lifecycle:
      postStart:
        exec:
          command: ["/bin/sh", "-c", "/scripts/restore.sh"]
      preStop:
        exec:
          command: ["/bin/sh","-c","/scripts/backup.sh"] 
     ....
```
2. Try to add such plugin to the workspace.
3. Expect to seen `Lifecycle` configuration in resulting workspace Pod
4. But looks like this section skipped during transferring  `meta.yaml` to the `Devfile`.

Need for https://github.com/eclipse/che/issues/15384
