### ISSUE TITLE
php stack: the command `Configure Apache Web Server DocumentRoot` should be done in the entrypoint (command) or CMD (args)

### ISSUE THREAD

**Issue by sunix** [eclipse-che/che#16869]
### Is your enhancement related to a problem? Please describe.
Starting the php stack, we ask the user to do a step that could be done automatically:

https://github.com/eclipse/che-devfile-registry/blob/master/devfiles/php-web-simple/devfile.yaml#L53
```yaml
- name: Configure Apache Web Server DocumentRoot
  actions:
    - type: exec
      component: php
      command: |
        if grep -q '/projects$' /etc/apache2/sites-available/000-default.conf; then
          sed -i 's|DocumentRoot /projects|DocumentRoot /projects/php-web-simple|' /etc/apache2/sites-available/000-default.conf
        else
          echo "DocumentRoot already configured!"
        fi
```
We could simply call that script in the entrypoint ( following by sleep as usual ).
it would avoid user having to do that him self

![image](https://user-images.githubusercontent.com/650571/81297399-795d0700-9073-11ea-9a64-ed75c0e5f3c6.png)
