### ISSUE TITLE
Che Theia Web View doesn't work properly when a plugin is running in its own sidecar

### ISSUE THREAD

**Issue by azatsarynnyy** [eclipse-che/che#16870]
### Describe the bug
Che Theia Web View doesn't work properly when a plugin is running in its own sidecar.

### Steps to reproduce

1. Start a Workspace with the following plugin descriptor:
```yaml
apiVersion: v2
publisher: redhat
name: vscode-didact
version: 0.1.14
type: VS Code extension
displayName: YAML
title: Didact Tutorial Tools by Red Hat
description: Provides interactive tutorial support to Visual Studio Code, via didact links calling VS Code commands, Markdown, AsciiDoc, and the VS Code webview.
icon: https://www.eclipse.org/che/images/logo-eclipseche.svg
repository: https://github.com/redhat-developer/vscode-didact
category: Other
firstPublicationDate: "2020-05-06"
spec:
  containers:
    - image: "quay.io/eclipse/che-sidecar-node:10-0cb5d78"
      name: vscode-didact
      memoryLimit: "256Mi"
  extensions:
    - https://github.com/redhat-developer/vscode-didact/releases/download/0.1.14/vscode-didact-0.1.14.vsix
```

2. Go to `DIDACT TUTORIALS` view and run `Didact Demo`
![image](https://user-images.githubusercontent.com/1636395/81304200-6c491380-9085-11ea-9591-b7e5495f817f.png)

3. The page is opened in Theia Web View has no styles applied:
![image](https://user-images.githubusercontent.com/1636395/81307427-51789e00-9089-11ea-98e7-bdeab64f0e77.png)

Also, the links that calling the commands aren't working.

### Expected behavior
The page is opened in Theia Web View should have the styles applied:
![image](https://user-images.githubusercontent.com/1636395/81307951-e4b1d380-9089-11ea-86ef-f12cc56446f7.png)

The links that calling the commands should work.

### Additional context
From the browser's dev console:
```
main.js:469 GET https://routegp3bizjr-azatsary-che.8a09.starter-us-east-2.openshiftapps.com/webview/theia-resource/file/tmp/vscode-unpacked/redhat.vscode-didact.0.1.14.mnjqnseceg.vscode-didact-0.1.14.vsix/extension/media/webviewslim.css net::ERR_ABORTED 404
(anonymous) @ main.js:469
setTimeout (async)
(anonymous) @ main.js:466
main.js:469 GET https://routegp3bizjr-azatsary-che.8a09.starter-us-east-2.openshiftapps.com/webview/theia-resource/file/tmp/vscode-unpacked/redhat.vscode-didact.0.1.14.mnjqnseceg.vscode-didact-0.1.14.vsix/extension/media/main.js net::ERR_ABORTED 404
```

### Sub-tasks
- [x] Implement simple file system provider to fetch files from containerized plugin https://github.com/eclipse/che/issues/18405
