### ISSUE TITLE
Option in `dockerimage` components to mount `/remote-endpoint/plugin-remote-endpoint`

### ISSUE THREAD

**Issue by sunix** [eclipse-che/che#16884]
### Is your enhancement related to a problem? Please describe.
It would be nice to be able to mount `/remote-endpoint/plugin-remote-endpoint` in `dockerimage` component.
- It would be useful for dogfooding: not having to copy the files in the right container to run a vscode extension in development mode.
- We would also be able to dynamically add extensions that would run in specific container thanks to that.
- It would allow to run a plugin without having to declare a meta.yaml file.
- It would also allow to make the dev of https://github.com/eclipse/che/issues/4949 a lot easier

### Describe the solution you'd like

```
  - alias: node-frontend-dev
    mountSources: true
    mountPluginRemoteEndpoint: true
    image: 'quay.io/eclipse/che-nodejs8-centos:7.2.0'
    memoryLimit: 768Mi
    type: dockerimage
    endpoints:
      - name: '3000-tcp'
        port: 3000
```
