### ISSUE TITLE
Use --che-operator-cr-patch-yaml for modifying checluster CR in tests

### ISSUE THREAD

**Issue by rhopp** [eclipse-che/che#16905]
### Is your task related to a problem? Please describe.
Currently we are downloading checluster CR from internet and then modifying it by using `sed` commands.
This is not very convenient for multiple reasons
* Easy mistakes
* Making sure we use correct checluster CR

### Describe the solution you'd like
Instead of downloading checluster CR and modifying it by `sed`, we can create checluster.patch like so (example):
```
cat >/tmp/che-cr-patch.yaml <<EOL
spec:
  server:
    pluginRegistryImage: $IMAGE_NAME
    selfSignedCert: true
  auth:
    updateAdminPassword: false
EOL
```
and then pass it to chectl like so:
```
chectl server:start --listr-renderer=verbose -a operator -p openshift --k8spodreadytimeout=360000 --che-operator-cr-patch-yaml=/tmp/che-cr-patch.yaml
```
