### ISSUE TITLE
Inline Che Theia plugins and Che Editors definitions in devfile v2

### ISSUE THREAD

**Issue by sunix** [eclipse-che/che#16994]
### Is your enhancement related to a problem? Please describe.
At the moment, adding a cheplugin is requiring the user to have a plugin registry and point the meta.yaml to use to another external http available resource.

### Describe the solution you'd like
It would be nice if we could inline the definition of a Che Theia plugin or of a Che editor in a v2  devfile (syntax details are in [this other issue](https://github.com/eclipse/che/issues/18668)):

```yaml
schemaVersion: 2.1.0  
metadata:  
  name: my-example  
attributes:  
  .che/che-theia-plugins.yaml: |  
    - id: redhat/java
  .vscode/extensions.json: |  
    {  
      "recommendations": [  
        "ms-vscode.vscode-github-pullrequest"  
      ]  
    }
  .che/che-editor.yaml: |  
      id: che-incubator/che-code/insiders
components:
(...)
```

Once we have that, we could even imagine composing new workspace by adding custom cheplugins from the dashboard: would just choose a container image and 1+ vsx extensions from openvsx marketplace

**Comment by l0rd** [comment]
@sunix this is a good suggestion. We need to think if it's worth adding it to the v1.0 spec or we include it in the devfile 2.0 spec.

**Comment by sunix** [comment]
@l0rd  I would say ASAP so both ... this is a high value enhancement and low cost as we have almost everything in place to achieve that. Would make testing new vscode extensions or sharing unsupported vscode extension or che plugin in draft mode a lot easier.
To me this is important as it will help to show the value of Che, running vscode exts in sidecar containers, to users and futur contributors.

**Comment by sunix** [comment]
devfile 2.0 https://github.com/devfile/kubernetes-api/issues/95

**Comment by themr0c** [comment]
I agree it would be really a very nice feature. It feels awkward to have the creation of a custom plug-in registry (administrator task, out of the hands of an end-user) as a dependency to add an IDE  extension (routine end-user task).

**Comment by ericwill** [comment]
> I agree it would be really a very nice feature. It feels awkward to have the creation of a custom plug-in registry (administrator task, out of the hands of an end-user) as a dependency to add an IDE extension (routine end-user task).

There is another way, and that is putting a meta.yaml somewhere (GH branch, or GH gist) and pointing to that in your devfile.

https://www.eclipse.org/che/docs/che-7/administration-guide/using-a-visual-studio-code-extension-in-che/#adding-the-vs-code-extension-using-the-workspace-configuration_adding-che-plug-in-registry-vs-code-extension-to-a-workspace

**Comment by sunix** [comment]
> > I agree it would be really a very nice feature. It feels awkward to have the creation of a custom plug-in registry (administrator task, out of the hands of an end-user) as a dependency to add an IDE extension (routine end-user task).
> 
> There is another way, and that is putting a meta.yaml somewhere (GH branch, or GH gist) and pointing to that in your devfile.
> 
> https://www.eclipse.org/che/docs/che-7/administration-guide/using-a-visual-studio-code-extension-in-che/#adding-the-vs-code-extension-using-the-workspace-configuration_adding-che-plug-in-registry-vs-code-extension-to-a-workspace

Ok it works but hosting meta.yaml somewhere else is still painful. It is adding x2 confusion and complexity compare to this proposal.

**Comment by ericwill** [comment]
I agree, I was more suggesting that in the meantime we shouldn't encourage people to deploy an entire registry just for one extension if the hosted meta.yaml way also works. At least until we have a fix for this ticket.

**Comment by themr0c** [comment]
https://www.eclipse.org/che/docs/che-7/administration-guide/using-a-visual-studio-code-extension-in-che/#adding-the-vs-code-extension-using-the-workspace-configuration_adding-che-plug-in-registry-vs-code-extension-to-a-workspace I read:

"Change the current registry to the registry in which the VS Code extension was added."

So this is an erroneous statement.

**Comment by themr0c** [comment]
I'll try to address that in https://github.com/eclipse/che-docs/pull/1633

**Comment by mickaelistria** [comment]
+1, I think that would be consistent with other IDEs if we want devfile to address them. The devfile could then contain for each IDE a description of the recommended extensions to install in a format that's relatively native to them. For Che, it would be content of a meta.yaml, for Eclipse IDE or VSCode it'd be some of their marketplace entries, for Theia some vsix URLs and so on...

**Comment by l0rd** [comment]
@sunix I have updated the description/title of this issue to make it clear that we will implement it in the context of the devfile v2.

**Comment by sunix** [comment]
As a che user, I am confuse seeing file names in the devfile: "che-editor.yaml" or "che-theia-plugins.yaml" what is these filename referring to ?

**Comment by l0rd** [comment]
@sunix those are the new `meta.yaml` (c.f. [the issue where those files are described](https://github.com/eclipse/che/issues/18668))

**Comment by sunix** [comment]
@l0rd
My point is that there is too many indirections to files and registries etc. If we could make it simpler to read and to compose.

As I understand it is not a replacement of `meta.yaml` as those would stay in the registries. We are just adding an extra layer and more files to deal with.

I would love to see a comparaison with some projects like: https://github.com/sunix/scratch-kubernetes or  https://github.com/redhat-developer-demos/quarkus-reactjs-postit-app. If a 2.0 devfile is harder to read and maintain and if it is even bigger. I don't see the point.

**Comment by l0rd** [comment]
> I would love to see a comparaison with some projects like: [sunix/scratch-kubernetes](https://github.com/sunix/scratch-kubernetes) or [redhat-developer-demos/quarkus-reactjs-postit-app](https://github.com/redhat-developer-demos/quarkus-reactjs-postit-app). If a 2.0 devfile is harder to read and maintain and if it is even bigger. I don't see the point.

Are we discussing inline here or are we discussing [how to reference plugins when using a devfile v2](https://github.com/eclipse/che/issues/18668)?
I am asking because your examples are not about inlining and this issue is about inlining.

**Comment by sunix** [comment]
these are all related, I am just giving my feedback here because I see the file names in your proposal and it looks too complex having 2 more files references. But maybe I am wrong, and that would be fine for users that will use Che and other editors. So I hope it will work if we go that way.

**Comment by sunix** [comment]
For vscode, if we say that we use `.vscode` it means that the devfile with inlining could override `.vscode`? same for `.idea`

**Comment by sunix** [comment]
also at some point, Some may just want to inline 1 plugin and not all. So that would be harder with this proposal.

**Comment by ericwill** [comment]
> also at some point, Some may just want to inline 1 plugin and not all. So that would be harder with this proposal.

I don't believe you have to inline all entries, if you want to inline just one plugin you only inline the `che-theia-plugins.yaml` file with one entry.

**Comment by sunix** [comment]
Let's say you have these plugins: https://github.com/redhat-developer-demos/quarkus-reactjs-postit-app/blob/master/devfile.yaml#L99-L118
You have all of these in a `che-theia-plugins.yaml` file. And you decide to inline the `openshift-connector` plugin. With this format, the logical way to do is to copy paste the whole `che-theia-plugins.yaml` in the devfile and modify just the `openshift-connector` part providing overrides.
The original goal of this issue was to inline what we had in a meta.yaml file. But the new proposal is to inline `che-theia-plugins.yaml`. The original proposal is covered with the `override` capabilities in `che-theia-plugins.yaml`.

This is all to say that it is not simplifying but making more complexe for user to understand and to use.

**Comment by sunix** [comment]
@l0rd could you provide a concrete example of how would the new inline in devfile 2.0 could be for that example (proposed initially):

```yaml
    - type: chePlugin
      referenceContent: |
        apiVersion: v2
        name: vscode-apache-camel
        version: 0.0.14
        type: VS Code extension
        displayName: Language Support for Apache Camel
        title: Language Support for Apache Camel
        description: This VS Code extension provides support for Apache Camel.
        category: Language
        firstPublicationDate: "2018-04-23"
        spec:
          containers:
          - image: eclipse/che-remote-plugin-runner-java11:7.0.0-rc-3.0
            name: vscode-apache-camel
            memoryLimit: 512Mi
          extensions:
          - https://github.com/camel-tooling/camel-lsp-client-vscode/releases/download/0.0.14/camel-tooling.vscode-apache-camel-0.0.14.vsix
```

**Comment by benoitf** [comment]
I guess it will be what you're finding there for a VS Code extension:

https://github.com/eclipse/che-plugin-registry/blob/master/che-theia-plugins.yaml#L422-L433

except that `directory` will be replaced by `image`

**Comment by sunix** [comment]
To me it is unclear how we deal with the usecase:

- I am using che-theia-plugins.yaml in my repo with 3 plugins
- I want to add a new one, but inline meta.yaml of this new one and keep the 3 other plugins.

**Comment by benoitf** [comment]
For now top level attributes is not in devfile specification, so che-server is failing at validation level with such devfile

**Comment by l0rd** [comment]
> For now top level attributes is not in devfile specification, so che-server is failing at validation level with such devfile

Top level attributes are not in the spec yet. The following PR need to be merged https://github.com/devfile/api/pull/352

**Comment by sleshchenko** [comment]
Well, there is nothing to do on devfile/v2 format with that.
Dashboard already supports che-editor.yaml.
Theia lib already supports che-plugins.yaml (name is not exact). So, assigning Theia to check the state and possible close.
@benoitf If I'm not mistaken it's you who implemented that part.

**Comment by l0rd** [comment]
It's currently possible to specify theia plugins inline in a devfile but the missing piece is the possibility to specify the editor. That should probably be a dashboard responsibility.

**implemented:**

```yaml
schemaVersion: 2.1.0  
metadata:  
  name: my-example  
attributes:  
  .che/che-theia-plugins.yaml: |  
    - id: redhat/java
  .vscode/extensions.json: |  
    {  
      "recommendations": [  
        "ms-vscode.vscode-github-pullrequest"  
      ]  
    }
components:
  (...)
```

**not implemented yet:**

```yaml
schemaVersion: 2.1.0  
metadata:  
  name: my-example  
attributes:  
  .che/che-editor.yaml: |  
    - id: che-incubator/che-code/insiders
components:
  (...)
```

[Here is a full devfile example](https://gist.github.com/l0rd/8722551b624ea077f13f180a1a681cc7).
