### ISSUE TITLE
Multiple workspaces not possible for `kubernetes` components using `endpoints`

### ISSUE THREAD

**Issue by miwurster** [eclipse-che/che#17028]
Hi, I have a question on how to use the `endpoints` configuration properly for `kubernetes` components in a devfile.

## Summary

We are using a devfile configuration to spin up a workspace in Che. The devfile defines a component of type `kubernetes` which specifies an endpoint (`radon-gmt` on port `8080`) - see the full devfile below.

This works fine for the first time when we start a workspace. However, if we start a second workspace we get the error `services "radon-gmt" already exists`:

```
Error: Failed to run the workspace: "Failure executing: POST at: 10.96.0.1/api/v1/namespaces/che/services. Message: services "radon-gmt" already exists. Received status: Status(apiVersion=v1, code=409, details=StatusDetails(causes=[], group=null, kind=services, name=radon-gmt, retryAfterSeconds=null, uid=null, additionalProperties={}), kind=Status, message=services "radon-gmt" already exists, metadata=ListMeta(_continue=null, remainingItemCount=null, resourceVersion=null, selfLink=null, additionalProperties={}), reason=AlreadyExists, status=Failure, additionalProperties={})."
```

When looking onto the underlying Kubernetes cluster, it seems that Che creates a dedicated Kubernetes service for the specified endpoint, which of course is unique for the respective `namespace`. 

**Is this the desired behavior? Shouldn't it be possible to start multiple workspaces based on such a devfile config?**

Further, when we stop and delete the first workspace, we cannot even start a new workspace because we get the same error message from above. It seems the respective Kubernetes service isn't properly deleted on the underlying cluster.

I appreciate any help!

## Relevant information

devfile:

```
apiVersion: 1.0.0
metadata:
  generateName: radon-workspace-
projects:
  - name: radon-particles
    source:
      type: git
      location: https://github.com/radon-h2020/radon-particles
components:
  - alias: theia-editor
    type: cheEditor
    id: eclipse/che-theia/next
  - alias: radon-gmt
    type: kubernetes
    endpoints:
      - name: radon-gmt
        port: 8080
        attributes:
          protocol: http
          secure: "false"
          discoverable: "true"
          public: "true"
    mountSources: true
    referenceContent: |
      ---
      apiVersion: apps/v1
      kind: Deployment
      metadata:
        name: winery-deployment
        labels:
          app: winery
          tier: frontend
      spec:
        replicas: 1
        selector:
          matchLabels:
            app: winery
            tier: frontend
        template:
          metadata:
            labels:
              app: winery
              tier: frontend
          spec:
            containers:
              - name: winery
                image: opentosca/radon-gmt:latest
                imagePullPolicy: Always
                ports:
                  - containerPort: 8080
                env:
                  - name: WINERY_FEATURE_RADON
                    value: "true"
                  - name: WINERY_REPOSITORY_PROVIDER
                    value: "yaml"
                  - name: WINERY_REPOSITORY_URL
                    value: "https://github.com/radon-h2020/radon-particles"
                  - name: WINERY_REPOSITORY_PATH
                    value: "/projects/radon-particles"
                  - name: WINERY_CSAR_OUTPUT_PATH
                    value: "/projects/radon-csars"
```
