### ISSUE TITLE
The rust getting started sample should use the vscode extension

### ISSUE THREAD

**Issue by sunix** [eclipse-che/che#17069]
### Is your enhancement related to a problem? Please describe.
At the moment, testing the rust devfile from getting started section in the dashboard: we can build and run ... but no code completion ... nor debug
Could https://github.com/rust-lang/rls-vscode/releases be tested and integrated?

Also it would be nice to see if we could enable the debug mode.

**Comment by sunix** [comment]
Progress:
- Created a cheplugin https://gist.github.com/sunix/eb86fdf6802afbfb4de059ed19f08d37 for testing
- Problem with the vscode extension: can’t load module rust-analysis, though it works from the terminal.
- Investigation:
  - Creating a devfile to run the rust ext from source and execute it in a sidecar. https://github.com/eclipse/che-theia/blob/sunix-rust-extension-devfile/devfiles/vscode-rust-devfile.yaml 
    ```
    2020-11-25 13:13:55.129 task INFO Created new task, id: 0, process id: 0, OS PID: 4996, context: file:///projects 
    2020-11-25 13:13:55.352 terminal ERROR Couldn't attach - can't find terminal with id: 0  
    2020-11-25 13:13:55.655 root ERROR Couldn't resize terminal -1, because it doesn't exist. 
    2020-11-25 13:13:55.656 terminal ERROR Error attaching to terminal id 0, the terminal is most likely gone. Starting up a new terminal instead.
    ```
  - https://github.com/rust-lang/vscode-rust/blob/master/src/tasks.ts#L137 my guess is that the task is invoked in the theia-ide container, not the rust one.

So currently the options could be:
- test if we could install the dependencies (but it won’t solve the problem
- do not use tasks to exec: use exec + output channel in rust-ext and propose a PR?
- somehow detect tasks created and started from a plugin and run these in the right container. Or be able to override tasks and tell them to run in container

To mention during daily meeting:
- Accidentally found another rust vscode extension: https://github.com/editor-rs/vscode-rust (tested https://github.com/rust-lang/vscode-rust )
- Dog fooding: 2 theia in the same container … one gets killed from time to time ….

**Comment by sunix** [comment]
Progress:
- Build a che-theia editor with rust: https://quay.io/repository/sunix/che-theia-rust
- runing it with the che-editor https://gist.github.com/sunix/a1295a1150f129ad40d2a11c59a3c063

Running in rust vscode ext in the che-theia-rust editor container is also failing: it seems to be something wrong with attaching terminal and not a dependency issue.

**Comment by sunix** [comment]
Progress:
- I managed to have the extension working by preinstalling the dependencies that the extension were not able to install in the theia-ide container.
   ```
   rustup component add rust-src --toolchain 1.48.0-x86_64-unknown-linux-musl; \
   rustup component add rust-analysis --toolchain 1.48.0-x86_64-unknown-linux-musl; \
   rustup component add rls --toolchain 1.48.0-x86_64-unknown-linux-musl;
   ```

next step: trying if providing these dependencies work in a sidecar

**Comment by sunix** [comment]
installing the rust component in the sidecar and running the extension on top of it seems to do the trick:
```bash
bash-5.0 /projects $ rustc --version
rustc 1.39.0 (4560ea788 2019-11-04)
bash-5.0 /projects $ rustup component add rust-src --toolchain 1.39.0-x86_64-unknown-linux-gnu
info: downloading component 'rust-src'
info: installing component 'rust-src'
bash-5.0 /projects $ rustup component add rust-analysis --toolchain 1.39.0-x86_64-unknown-linux-gnu
info: downloading component 'rust-analysis'
info: installing component 'rust-analysis'
bash-5.0 /projects $ rustup component add rls --toolchain 1.39.0-x86_64-unknown-linux-gnu
info: downloading component 'rls'
info: installing component 'rls'
bash-5.0 /projects $ 
```

**Comment by gattytto** [comment]
> We can package it. However the task provided by the extension are still not functional. not a big deal for this issue.

could it be they are dynamic tasks as mentioned in [this issue](https://github.com/eclipse/che/issues/17807)?

**Comment by gattytto** [comment]
@sunix can you share the sidecar's source? I don't see it in either plugin-registry / che-dockerfiles repos

**Comment by sunix** [comment]
@gattytto yes this is WIP :)

**Comment by sunix** [comment]
@gattytto you can give a try:
```yaml
apiVersion: 1.0.0
metadata:
  generateName: rust-
projects:
  - name: HelloWorld-Rust
    source:
      location: 'https://github.com/che-samples/helloworld-rust.git'
      type: git
      branch: master
components:
  - mountSources: true
    memoryLimit: 512Mi
    type: dockerimage
    alias: rust
    image: quay.io/eclipse/che-rust-1.39:nightly
 
  - type: chePlugin
    reference: 'https://gist.githubusercontent.com/sunix/eb86fdf6802afbfb4de059ed19f08d37/raw/41515915211723ca3c740d28263d7b8a87e0a8b6/meta.yaml'
 
commands:
  - name: build
    actions:
      - workdir: '${CHE_PROJECTS_ROOT}/HelloWorld-Rust'
        type: exec
        command: cargo build
        component: rust
  - name: run
    actions:
      - workdir: '${CHE_PROJECTS_ROOT}/HelloWorld-Rust'
        type: exec
        command: cargo run
        component: rust

```
