### ISSUE TITLE
Ability to override automount secret properties in devfile

### ISSUE THREAD

**Issue by mshaposhnik** [eclipse-che/che#17079]
### Is your task related to a problem? Please describe.
Atref implementing #14680 users can have secrets mounted to theirs workspace contaibers as files on env variabes. At the same time, user may need some variabitilty, like changing environment var name or mount path without affecting the original secret in namespace. So that can de done by updating the devfile of the perticular workspace.

### Describe the solution you'd like

Initial idea (copied from #14680, probably needs to be revised and refactored) :

To be able to explicitly override mountPath or envName of concrete Secret we need a pair secretName and key that we want to override + value. It can look like this in devfile
devfile.yaml

```
...
components:
 - type: dockerimage
   annotations:
      mvn-settings-secret: mountPath=/home/user2/.m2/
      mvn-settings-secret: envName=ENV_NAME2
   alias: maven
   image: maven:3.11
...
```
or

devfile.yaml
```
...
components:
 - type: dockerimage
   alias: maven
   image: maven:3.11
   secrets:
      mvn-settings-secret:
         mountPath=/home/user2/.m2/
...      envName=ENV_NAME2 
```

**Comment by mshaposhnik** [comment]
Since secrets may be applied to any container of any component in devfile, it seems to me that 
overriding properties should not be described on component-s level, but more globally for whole devfile, so metadata section seems to be more appropriate place. Moreover, that matches with secrets description, so it looks more uniform for the writer.

So, thats is the first draft proposal for discussion beginning (it supposes devfile owner knows the secret names, but i'm not sure it is always true). 

```
apiVersion: 1.0.0
metadata:
  name: petclinic-dev-environment
  generateName: petclinic-
  secrets-override:
      - <mvn-settings-secret-name>:
            mount-path: /home/user2/.m2/
            target-container: maven
     - <single-env-var-secret-name>
            env-name: ENV_NAME2
            target-container: maven
      - <multi-env-var-secret-name>
            key1_env-name: FOO1
            bar1_env-name: BAR1
            target-container: theia
projects:
....
```

**Comment by mshaposhnik** [comment]
Ok, so after having some internal discussion, we see the two different approaches, with different flexibility and usage complexity. Generally, it's per-component or per-devfile overrides.

First one initially proposed by Sergey, with examples in issue description, it's per-component override.
So it will affect only component where this override is described. But user may need to know container names provided by that component, and need to write the same override definition multipe times if he wants his changes to be applied to serveral components across workspace. Also, there is a question with default components, which are not present in devfile. So to have them be re-configured, they need to be defined explicitly in devfile and overrides then written into theirs specification.

Second is proposed by me in comment above, it-s per devfile override, authomatically applying override all changes per all components, so it can be written just once. But of cource it less flexibility, not allowing to change something in just one component (but you can still override just one target component if you know it's name).

As for me, mounting same secret into ALL containers is an quite unusual exceprional case. In most usecases, thre will be just one target container where the secret shoult be applied. So, IMO, having single definition is just enough if you want to change this container and/or modify mount path or ENV name. So with 2nd case you dont even need to care in which component iths container is.

So let's try to choose one that fit our needs better, to stay on right track.
 @l0rd @benoitf @sunix

**Comment by l0rd** [comment]
I was looking at the automounting of a SA account token that has some analogies with this use case and here are some considerations:

**Automounting**

To avoid that the SA token get automatically mounted on every containers k8s API provides the attribute `automountServiceAccountToken` that [can be set at the SA level and at the Pod level](https://kubernetes.io/docs/tasks/configure-pod-container/configure-service-account/#use-the-default-service-account-to-access-the-api-server). 
 The value at Pod level has higher priority. 

For our use case we should have a similar attribute `automountWorkspaceSecrets` at secret and devfile.component level instead of relying on `targetContainer` at secret level. And the value at devfile.component level should have higher priority.

**Overriding Secrets Paths**

To override SA token default mount path (`/var/run/secrets/kubernetes.io/serviceaccount/token`) k8s API provides [SA token volume projection](https://kubernetes.io/docs/tasks/configure-pod-container/configure-service-account/#service-account-token-volume-projection). The path get overriden by the `containers[].volumeMounts[].mountPath`. 

For our use case I would get inspiration from it (again) and have something similar:

```yaml
components:
 - type: dockerimage
   alias: maven
   image: maven:3.11
   volumes:
     - name: <secret-name>
       containerPath: /my/new/path
```

**Cross component Volume Definition**

I would wait devfile 2.0 for that as there is a proposal for something that would address that https://github.com/devfile/kubernetes-api/issues/19#issuecomment-590691321.
