### ISSUE TITLE
At times or a lot, a sudden crash for all extensions and it starts to reload/reactivate the extensions again

### ISSUE THREAD

**Issue by SDAdham** [eclipse-che/che#17133]
### Describe the bug

To be honest, I'm not sure what is the exact issue but as mentioned in the title.

### Che version

 - [X] latest 7.14.1
 - [ ] nightly
 - [ ] other: please specify

### Expected behavior

Once extensions loaded, they should stay loaded
### Runtime
   - [X] kubernetes (include output of `kubectl version`)
   - [ ] Openshift (include output of `oc version`)
   - [ ] minikube (include output of `minikube version` and `kubectl version`)
   - [ ] minishift (include output of `minishift version` and `oc version`)
   - [ ] docker-desktop + K8S (include output of `docker version` and `kubectl version`)
   - [ ] other: (please specify)

### Installation method
   - [X] chectl
     * provide a full command that was used to deploy Eclipse Che (including the output)
     * provide an output of `chectl version` command
   - [ ] OperatorHub
   - [ ] I don't know

### Environment
   - [ ] my computer
       - [ ] Windows
       - [ ] Linux
       - [ ] macOS
   - [ ] Cloud
       - [ ] Amazon
       - [ ] Azure
       - [ ] GCE
       - [ ] other (please specify)
   - [X] other: please specify

**Comment by sunix** [comment]
@SDAdham could you give more details? screencast? screenshare? logs? how to reproduce?

**Comment by SDAdham** [comment]
@sunix i cant capture a straight forward screenshot.

at the bottom left corner, the area where it says plugin. Thats it. It every once in a while, this says activating plugins. But when it does, i already start to notice autocomplete is not working (except generic keywords) and many other plugins

**Comment by sleshchenko** [comment]
@SDAdham Could you provide workspace's devfile where you face the issue? Do you think Theia has enough memory configured?

**Comment by SDAdham** [comment]
@sleshchenko 
```
metadata:
  name: name-3oa0b
projects:
  - name: <project-name-1>
    source:
      location: 'git@<domain>:<project-1>.git'
      type: git
  - name: <project-name-2>
    source:
      location: 'git@<domain>:<project-2>.git'
      type: git
components:
  - id: redhat/vscode-apache-camel/latest
    type: chePlugin
  - type: chePlugin
    reference: >-
      https://<domain>/<subpath>/v3/plugins/thegeoffstevens/best-dark-themes-pack/1.0.1/meta.yaml
    alias: thegeoffstevens-best-dark-themes-pack
  - type: chePlugin
    reference: >-
      https://<domain>/<subpath>/v3/plugins/alexiv/vscode-angular2-files/1.6.2/meta.yaml
    alias: vscode-angular2-files
  - mountSources: true
    endpoints:
      - name: <proj-2>-web
        port: 8080
    memoryLimit: 512Mi
    type: dockerimage
    volumes:
      - name: composer
        containerPath: /home/user/.composer
    image: <private-registry-url>/<image-1>
    alias: <proj-2>-server
    env:
      - value: 'SOMEVAL'
	    name: ENVNAME
  - mountSources: false
    endpoints:
      - name: <end-point-1>
        port: 8085
    memoryLimit: 256Mi
    type: dockerimage
    image: <private-registry-url>/<image-2>
    alias: <end-point-1>-server
  - type: chePlugin
    reference: >-
      https://<domain>/<subpath>/v3/plugins/danwahlin/angular2-snippets/1.0.22/meta.yaml
    alias: angular2-snippets
  - type: chePlugin
    reference: >-
      https://<domain>/<subpath>/v3/plugins/infinity1207/angular2-switcher/0.3.3/meta.yaml
    alias: angular2-switcher
  - type: chePlugin
    reference: >-
      https://<domain>/<subpath>/v3/plugins/ktriek/ng-bootstrap-snippets/1.0.0/meta.yaml
    alias: ng-bootstrap-snippets
  - id: redhat/vscode-yaml/latest
    type: chePlugin
  - id: redhat/php/latest
    memoryLimit: 1Gi
    type: chePlugin
  - mountSources: false
    endpoints:
      - name: <end-point-2>-db
        port: 3306
        attributes:
          discoverable: 'true'
    memoryLimit: 256Mi
    type: dockerimage
    volumes:
      - name: data
        containerPath: /var/lib/mysql/data
    image: docker.io/centos/mysql-57-centos7
    alias: <end-point-2>-db-server
  - type: chePlugin
    reference: >-
      https://<domain>/<subpath>/v3/plugins/Equinusocio/vsc-material-theme/32.5.0/meta.yaml
    alias: vsc-material-theme
  - id: che-incubator/typescript/latest
    type: chePlugin
  - id: joaompinto/vscode-asciidoctor/latest
    type: chePlugin
  - id: redhat/vscode-xml/latest
    type: chePlugin
  - mountSources: true
    endpoints:
      - name: <end-point-2>-web
        port: 4200
    memoryLimit: 1Gi
    type: dockerimage
    image: 'quay.io/eclipse/che-nodejs10-community:7.14.1'
    alias: <end-point-2>-server
  - id: eclipse/che-theia/7.14.1
    memoryLimit: 4Gi
    type: cheEditor
  - type: chePlugin
    reference: >-
      https://<domain>/<subpath>/v3/plugins/ms-vscode/vscode-typescript-tslint-plugin/1.2.3/meta.yaml
    alias: ms-tslint-plugin
  - id: eamodio/vscode-gitlens/latest
    type: chePlugin
  - type: chePlugin
    reference: >-
      https://<domain>/<subpath>/v3/plugins/johnpapa/Angular2/9.1.2/meta.yaml
    alias: johnpapa-Angular2
  - id: sonarsource/sonarlint-vscode/latest
    type: chePlugin
  - type: chePlugin
    reference: >-
      https://<domain>/<subpath>/v3/plugins/angular/ng-template/0.901.9/meta.yaml
    alias: angular-ng-template
  - id: redhat/php-debugger/latest
    memoryLimit: 256Mi
    type: chePlugin
  - type: chePlugin
    reference: >-
      https://<domain>/<subpath>/v3/plugins/natewallace/angular2-inline/0.0.17/meta.yaml
    alias: natewallace-angular2-inline
  - type: chePlugin
    reference: >-
      https://<domain>/<subpath>/v3/plugins/neilbrayfield/php-docblocker/2.0.1/meta.yaml
    alias: php-docblocker
apiVersion: 1.0.0
```
