### ISSUE TITLE
How to stop and restart in single-user with non-volatile persistent workspace storage

### ISSUE THREAD

**Issue by olberger** [eclipse-che/che#17148]
## Summary
I'm experimenting with embedding Eclipse Che inside a Vagrant-controlled VM (see https://gitlab.com/olberger/vagrant-minikube-eclipse-che/-/tree/single-user) in order to allow downloading an Eclipse Che-ready VM with Vagrant. I plan to use this in an academic context to allow students to run Che locally without a Cloud access.

I'd like to be able to stop/restart the VM being able to keep the current workspaces after restart.

I've configured the persistent volume for the workspaces to use a fixed hostpath, which is actually set inside a shared folder that Vagrant mounts from the host machine. Thus, in all cases, there's a backup of contents of the projects on the host.

The problem is it seems that after a restart, I'm not seeing the previous workspaces anymore.

Is there a clean way to stop Che single-user and start it again, possibly restoring the workspaces from files in the persisted storage dir ?

## Relevant information
The Che startup script I'm using: https://gitlab.com/olberger/vagrant-minikube-eclipse-che/-/blob/single-user/chescript.sh

**Comment by sleshchenko** [comment]
@olberger 

> I've configured the persistent volume for the workspaces to use a fixed hostpath, which is actually set inside a shared folder that Vagrant mounts from the host machine. Thus, in all cases, there's a backup of contents of the projects on the host.
> 
> The problem is it seems that after a restart, I'm not seeing the previous workspaces anymore.

Single-User Che Server stores workspaces in file-based database which is stored in another PVC https://github.com/eclipse/che/blob/master/deploy/kubernetes/helm/che/templates/pvc.yaml#L10
So, make sure that that PVC content is backed-up as well as workspaces and after that everything should work as expected (or at least that workspaces are not lost)  :crossed_fingers:

**Comment by olberger** [comment]
I see... I'm just not sure how to divert it from the standard storageClassName, which leads to storing into /tmp/hostpath-provisioner, and to use a specific PV.

Could you suggest an addendum to https://www.eclipse.org/che/docs/che-7/installing-che-using-storage-classes/ ? That would be much helpful

**Comment by olberger** [comment]
FWIW, I've managed to use this manifest prior to starting installation with chectl. I think the `claimRef` for `name: che-data-volume` should be the trick that allows binding to a custom dir...

```
apiVersion: v1
kind: PersistentVolume
metadata:
  name: che-data-volume
  labels:
    type: local
spec:
  storageClassName: che-data-storage
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/home/vagrant/che-data-storage"
  claimRef:
    namespace: che
    name: che-data-volume
```
I'm not yet fully confident this works.
