### ISSUE TITLE
Usage of multiple `mountSources: true` in devfile?

### ISSUE THREAD

**Issue by miwurster** [eclipse-che/che#17147]
## Summary

We are experimenting with a devfile configuration containing two Kubernetes components (see config below). Both components utilize the `mountSources: true`. However, when we try to start the workspace, this fails with the following error message:

```
Environment can not contain two 'PersistentVolumeClaim' objects with the same name 'projects'
```

From the [documentation](https://www.eclipse.org/che/docs/che-7/making-a-workspace-portable-using-a-devfile/#specifying-mount-source-option), to me it seems that this should work with more than one component.

So, can the `mountSources` be used for more than one defined component?

Thanks,
Michael

## Relevant information

Tested with version `7.14.1`.

devfile:
```
apiVersion: 1.0.0
metadata:
  generateName: workspace-
projects:
  - ...
components:
  - alias: theia-editor
    type: cheEditor
    id: eclipse/che-theia/next
  - alias: radon-gmt
    type: kubernetes
    mountSources: true
    endpoints:
      - name: radon-gmt
        port: 8080
        attributes:
          protocol: http
          secure: "false"
          discoverable: "false"
          public: "true"
    reference: ...
  - alias: radon-vt
    type: kubernetes   
    mountSources: true
    endpoints:
      - name: radon-vt
        port: 5000
        attributes:
          protocol: http
          public: 'true'
          discoverable: 'false'
          secure: 'false'
    referenceContent: |
      ---
      ...
```
