### ISSUE TITLE
Secret mount as file does not work on OpenShift 3.11

### ISSUE THREAD

**Issue by sparkoo** [eclipse-che/che#17213]
### Describe the bug
Secret mount as file does not work on OpenShift 3.11. After this patch https://github.com/eclipse/che/pull/17168 we've introduced usage of `subPath` in VolumeMount. However, this is supported and enabled-by default only from Kubernetes v1.15 (https://kubernetes.io/docs/concepts/storage/volumes/#using-subpath-with-expanded-environment-variables). OS 3.11 is based on k8s 1.11

### Che version
 - [x] nightly

### Steps to reproduce
1. create Secret that will be mount as file. for example:
  ```
---
apiVersion: v1
kind: Secret
metadata:
  name: maven-settings-secret
  labels:
    app.kubernetes.io/part-of: che.eclipse.org
    app.kubernetes.io/component: workspace-secret
  annotations:
    che.eclipse.org/target-container: maven
    che.eclipse.org/mount-path: /home/user/.m2
    che.eclipse.org/mount-as: file
type: Opaque
data:
  settings.xml: PHNldHRpbmdzIHhtbG5zPSJodHRwOi8vbWF2ZW4uYXBhY2hlLm9yZy9TRVRUSU5HUy8xLjAuMCIKICAgICAgICAgIHhtbG5zOnhzaT0iaHR0cDovL3d3dy53My5vcmcvMjAwMS9YTUxTY2hlbWEtaW5zdGFuY2UiCiAgICAgICAgICB4c2k6c2NoZW1hTG9jYXRpb249Imh0dHA6Ly9tYXZlbi5hcGFjaGUub3JnL1NFVFRJTkdTLzEuMC4wCiAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIGh0dHBzOi8vbWF2ZW4uYXBhY2hlLm9yZy94c2Qvc2V0dGluZ3MtMS4wLjAueHNkIj4KICA8c2VydmVycz4KICAgIDxzZXJ2ZXI+CiAgICAgIDxpZD5yZXBvc2l0b3J5LWlkPC9pZD4KICAgICAgPHVzZXJuYW1lPnVzZXJuYW1lPC91c2VybmFtZT4KICAgICAgPHBhc3N3b3JkPnBhc3N3b3JkMTIzPC9wYXNzd29yZD4KICAgIDwvc2VydmVyPgogIDwvc2VydmVycz4KPC9zZXR0aW5ncz4K
```
2. start a workspace with `maven` component (for example secret)
3. see fail with message like `Failed to start Kubernetes runtime of workspace workspace0b5p0d49dwk6ldfv. Cause: Unrecoverable event occurred: 'Failed', 'Error: failed to create subPath directory for volumeMount "secret-maven" of container "go-cli"', 'workspace0b5p0d49dwk6ldfv.go-cli-8bbd8dd9c-c7dr6'`

### Expected behavior
 - workspace must start
 - volume should be properly mounted
   - Implementing `subPath`-like functionality on OpenShift 3.11 would be significant effort, so we should mount secret as files without this on OpenShift 3.11, leaving there limitations of such mounts (https://github.com/eclipse/che/issues/17113)
     - preferably detect programatically whether k8s version support subpath (k8s version is possible to get with KubernetesClient#getVersion() https://github.com/fabric8io/kubernetes-client/blob/master/kubernetes-client/src/main/java/io/fabric8/kubernetes/client/KubernetesClient.java#L163 `VersionInfo` -> https://github.com/fabric8io/kubernetes-client/blob/master/kubernetes-client/src/main/java/io/fabric8/kubernetes/client/VersionInfo.java)
     - alternatively introduce new Secret annotation that switch subpath on/off

### Runtime
   - [x] Openshift 3.11 (include output of `oc version`)

### Installation method
   - [x] chectl

### Environment
   - [x] my computer
       - [x] Linux

### Additional context
https://github.com/eclipse/che/issues/17113
