### ISSUE TITLE
[AKS] Unable to clone git repositories

### ISSUE THREAD

**Issue by danielang** [eclipse-che/che#17229]
## Summary
If I try to clone a git repository in the theia IDE the operation fails with the following error:
```
Cloning into '/projects/app'...
error: chmod on /projects/app/.git/config.lock failed: Operation not permitted
fatal: could not set 'core.filemode' to 'false'
> git rev-parse --show-toplevel
fatal: not a git repository (or any parent up to mount point /)
Stopping at filesystem boundary (GIT_DISCOVERY_ACROSS_FILESYSTEM not set).
```

## Relevant information
K8S:
* AKS (Azure)
* v1.15.11
* Storage Class
  - default
  - azurefile
* PVC
  - keycloak-data : default
  - keycloak-log : default
  - postgres-data : default
  - workspace-data : azurefile

Che
* v7.14.3

**Comment by sunix** [comment]
hi Daniel,
Could you describe how you deployed Che?

**Comment by danielang** [comment]
I tryed to follow the official documentation and adapt it where things had evolved further.

### [1. Preparing Azure for installing Che ](https://www.eclipse.org/che/docs/che-7/installing-eclipse-che-on-microsoft-azure/#preparing-azure-for-installing-che_installing-che-on-microsoft-azure)
Up to date


### [2. Installing Ingress on Kubernetes](https://www.eclipse.org/che/docs/che-7/installing-eclipse-che-on-microsoft-azure/#installing-ingress-on-kubernetes_installing-che-on-microsoft-azure)
**Step 1 & 2** becomes:
```
$ kubectl apply -f https://raw.githubusercontent.com/kubernetes/ingress-nginx/master/deploy/static/provider/cloud/deploy.yaml
```

### [3. Configuring DNS on Azure](https://www.eclipse.org/che/docs/che-7/installing-eclipse-che-on-microsoft-azure/#configuring-DNS-on-azure_installing-che-on-microsoft-azure)
Up to date

### [4. Enabling the TLS and DNS challenge on Azure](https://www.eclipse.org/che/docs/che-7/installing-eclipse-che-on-microsoft-azure/#enabling-the-TLS-DNS-challenge-on-azure_installing-che-on-microsoft-azure)
**Step 1**
Install cert-manager see [https://cert-manager.io/docs/installation/kubernetes/](https://cert-manager.io/docs/installation/kubernetes/). I used helm:

Create the namespace:
```
$ kubectl create namespace cert-manager
```

Add cert-manager to the helm repositories:
```
$ helm repo add jetstack https://charts.jetstack.io
```

Update local Helm chart repository cache:
```
$ helm repo update
```

Install cert-manager with `installCRDs` option set to `true`:
```
# Helm v3+
$ helm install \
  cert-manager jetstack/cert-manager \
  --namespace cert-manager \
  --version v0.15.1 \
  --set installCRDs=true
```

After that I followed the [AzureDNS](https://cert-manager.io/docs/configuration/acme/dns01/azuredns/) guide of cert-manager. But instead of an `Issuer` I created an `ClusterIssuer`:
```
cat <<EOF | kubectl apply -f -
apiVersion: cert-manager.io/v1alpha2
kind: ClusterIssuer
metadata:
  name: che-certificate-issuer
spec:
  acme:
    email: my@mail.example
    server: https://acme-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      name: letsencrypt
    solvers:
    - dns01:
        azuredns:
          clientID: AZURE_CERT_MANAGER_SP_APP_ID
          clientSecretSecretRef:
          # The following is the secret we created in Kubernetes. Issuer will use this to present challenge to Azure DNS.
            name: azuredns-config
            key: client-secret
          subscriptionID: AZURE_SUBSCRIPTION_ID
          tenantID: AZURE_TENANT_ID
          resourceGroupName: AZURE_DNS_ZONE_RESOURCE_GROUP
           # The DNS Zone to use
          hostedZoneName: azr.my-ide.cloud
          # Azure Cloud Environment, default to AzurePublicCloud
          environment: AzurePublicCloud
EOF
```

### [5. Creating a Service Account Secret on Azure](https://www.eclipse.org/che/docs/che-7/installing-eclipse-che-on-microsoft-azure/#creating-a-service-account-secret-on-azure_installing-che-on-microsoft-azure)

Create the `che` namespace:
```
$ kubectl create namespace che
```

Create the wildecard certificate:
```
cat <<EOF | kubectl apply -f -
apiVersion: cert-manager.io/v1alpha2
kind: Certificate
metadata:
 name: che-tls
 namespace: che
spec:
 secretName: che-tls
 issuerRef:
   name: che-certificate-issuer
   kind: ClusterIssuer 
 dnsNames:
   - '*.azr.my-ide.cloud'
EOF
```

For a reason I dont know, the `chectl server:start` command later wants to read the `self-signed-certificate` secret, but the `che-tls` was successfully detected. **Maybe it is a bug**. So I created another certificate with `self-signed-certificate` as name of the secret:

```
cat <<EOF | kubectl apply -f -
apiVersion: cert-manager.io/v1alpha2
kind: Certificate
metadata:
 name: self-signed-certificate
 namespace: che
spec:
 secretName: self-signed-certificate
 issuerRef:
   name: che-certificate-issuer
   kind: ClusterIssuer 
 dnsNames:
   - '*.azr.my-ide.cloud'
EOF
```

*** [6. Installing Che on Azure using the chectl command](https://www.eclipse.org/che/docs/che-7/installing-eclipse-che-on-microsoft-azure/#installing-che-on-azure-using-the-chectl-command_installing-che-on-microsoft-azure)
After some unsuccessfull trys with the `helm` installer option I switched to `olm` which works well:
```
$ chectl server:start --installer=olm --platform=k8s   --domain=che.online-ide.info --multiuser   --tls   --workspace-pvc-storage-class-name=azurefile
```

These were my steps to deploy che on my AKS instance. Perhaps these instructions could help some other people as well.
