### ISSUE TITLE
Provide git credential storage mechanism

### ISSUE THREAD

**Issue by l0rd** [eclipse-che/che#17251]
### Is your enhancement related to a problem? Please describe.

When using git with HTTPS protocol all the connection needs a username and password. To avoid prompting for credential at every connection git allows to configure a credential storage mechanism:

**cache with timeout**
```bash
$ git config --global credential.helper 'cache --timeout=3600'
``` 

**local file with cleartext username/password (never expires)**
```bash
git config --global credential.helper 'store --file ~/.git-store/credentials'
```

This is described [here](https://git-scm.com/book/en/v2/Git-Tools-Credential-Storage).

That can be done manually on che workspaces but requires a manual step (`git config` command) that needs to be repeated at every restart of the workspace.

### Describe the solution you'd like

We should document how to use the [secret injection mechanism](https://www.eclipse.org/che/docs/che-7/mounting-a-secret-as-a-file-or-an-environment-variable-into-a-workspace-container/) to inject a file with the username and password and set the git config `credential.helper` accordingly:

```yaml
apiVersion: v1
kind: Secret
metadata:
  name: git-credentials-secret
  annotations:
    che.eclipse.org/automount-workspace-secret: true
    che.eclipse.org/mount-path: /home/user/.git-store/
    che.eclipse.org/mount-as: file
  data:
     credentials: <base64 encoded file>
```

And in the git configuration:
```
[credential]
        helper = store --file ~/.git-store/credentials
```

**Comment by l0rd** [comment]
The problem here is how to set the `credential.helper` to match the secret `che.eclipse.org/mount-path:`. I see a few options:

1. Set git configuration `credential.helper` to `store --file ~/.git-store/credentials` by default: if a secret exists and its mount path is `~/.git-store/` and data `credentials` then the user won't be prompted for username/password. It will be promoted otherwise.

2. Use 2 secrets: one to mount the credentials file in a given path, and another one to mount the global git config file (`~/.gitconfig`) that points to the path where the credential file will be mounted.

3. Use a custom credential storage as described at the end of https://git-scm.com/book/en/v2/Git-Tools-Credential-Storage#_credential_caching

@davidfestal @ericwill @sunix

**Comment by sunix** [comment]
Some thoughts: https://github.com/eclipse/che/issues/13611

**Comment by sunix** [comment]
also if we have https://github.com/eclipse/che/issues/14217#issuecomment-650018142, we could reuse the token and password ... for GH at least.

**Comment by mshaposhnik** [comment]
Yes it seems we didn't have much choice - mount whole `.gitconfig` or execute ` git config credential.helper <...>` either with file or own script. As a fluent idea, i have in mind to run this command via devfile commands, adding it into required component and add like `autorun` flag to make it executed without any user action (like we have post-load actions in factories), wdyt ?

**Comment by sunix** [comment]
We could also alias or wrap the git command so it does what we want in our container at least

**Comment by sunix** [comment]
But finally i think it would be good to let the user store with credential storage from git and keep that in a secret. (1. from Mario) https://git-scm.com/book/en/v2/Git-Tools-Credential-Storage

**Comment by sunix** [comment]
we could patch, in the containers where we would use git, `/etc/gitconfig` and set `credential.helper` where it is usually mounted.

**Comment by nickboldt** [comment]
Please treat this as a highly important P1 for the current 7.17 sprint, per Parag's comments on https://issues.redhat.com/browse/CRW-1025?focusedCommentId=14177136&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-14177136

**Comment by skabashnyuk** [comment]
on it.

**Comment by skabashnyuk** [comment]
>we could patch, in the containers where we would use git, /etc/gitconfig and set credential.helper where it is usually mounted. Then use secrets to mount the credential storage file.

What if we add new annotation `che.eclipse.org/git-credential: true` that gives us a hint that we should add 
`credential.helper` to /etc/gitconfig in https://github.com/eclipse/che/blob/master/infrastructures/kubernetes/src/main/java/org/eclipse/che/workspace/infrastructure/kubernetes/provision/GitConfigProvisioner.java  or we can use the predefined secret name `git-credentials-secret`?

```
apiVersion: v1
kind: Secret
metadata:
  name: git-credentials-secret
  labels:
    app.kubernetes.io/part-of: che.eclipse.org
    app.kubernetes.io/component: workspace-secret
  annotations:
    che.eclipse.org/git-credential: true
    che.eclipse.org/mount-path: /home/theia/.git-credentials
    che.eclipse.org/mount-as: file
data:
  credentials: .... 
```
@l0rd @mshaposhnik @sunix wdyt?
