### ISSUE TITLE
no python in code-server workspace; how do I get it there?

### ISSUE THREAD

**Issue by rholland** [eclipse-che/che#17267]
1. I set up a workspace with Python.
2. I chose code-server as the editor
3. From the terminal I type python and python is not found

How do I get python and pip in the code-server environment?

Thanks.

Here is the dev file:
```
metadata:
  name: python-ger3h
projects:
  - name: python-hello-world
    source:
      location: 'https://github.com/che-samples/python-hello-world.git'
      type: git
      branch: master
components:
  - mountSources: true
    memoryLimit: 512Mi
    type: dockerimage
    image: 'quay.io/eclipse/che-python-3.7:7.14.3'
    alias: python
  - id: cdr/code-server/latest
    type: cheEditor
apiVersion: 1.0.0
commands:
  - name: run
    actions:
      - workdir: '${CHE_PROJECTS_ROOT}/python-hello-world'
        type: exec
        command: python hello-world.py
        component: python
```
