### ISSUE TITLE
A vsx that works fine on Gitpod and VS Code but does NOT on Che

### ISSUE THREAD

**Issue by erlansan** [eclipse-che/che#17354]
Hello,

i'm currently running a minikube cluster with che server on it. 
My goal is to add a VS extension to it. 
I followed this tutorial on how to add a VS extension to a custom plug-in registry: https://www.eclipse.org/che/docs/che-7/building-and-running-a-custom-registry-image/#building-a-custom-devfile-registry_building-and-running-a-custom-registry-image
I'm stuck at step 5. Running `docker build -t my-devfile-registry` gives me the following output: 
`PS C:\repositories\che-plugin-registry> docker build -t che-plugin-registry `                                           
` "docker build" requires exactly 1 argument.`
I've tried running **.build.sh** file from powershell, but it briefly opens a window and closes it, without any result. 
I've tried adding this folder in Plug-in view in Che Editor, but it didn't add anything new.

My question is, what am i missing?

**Comment by benoitf** [comment]
Hello @erlansan 

you could use gist to host some files

create a meta.yaml on https://gist.githubusercontent.com/

and paste the content of what you need for you VS Code extension (basically the path to the vsix and an optional runtime container)

```json
apiVersion: v2
publisher: erlansan
name: typescript
version: 1.0.0
type: VS Code extension
displayName: erlansan
title: erlansan
description: erlansan
icon: https://www.eclipse.org/che/images/logo-eclipseche.svg
repository: https://github.com/erlansan
category: Language
firstPublicationDate: '2020-07-08'
spec:
  containers:
    - image: "quay.io/fbenoit/che-typescript-plugin:latest"
      name: vscode-typescript
      memoryLimit: '512Mi'
  extensions:
    - https:/THE-LINK-TO-THE.vsix
```


and then create a devfile in your workspace

and add a new component (url of this gist)

```json
components:
  -
    type: chePlugin
  ...
  ...
  -
    type: chePlugin
    reference: https://raw.githubusercontent.com/erlansan/........GIST_URL......./meta.yaml
    memoryLimit: 512Mi
...
  -
    type: chePlugin
```

**Comment by erlansan** [comment]
I tried it, seems not to have any effect on the number of plugins i have available. The second component seems to work completely fine.
Part of my Devfile content: 
```
...
components:
  - memoryLimit: 512Mi
    type: chePlugin
    reference: >-
      https://gist.githubusercontent.com/erlansan/c15872800c6c7366fa743d98c10d9274/raw/458c7f0ed8c8cc6db2bba86967353a424634c305/meta.yaml
    alias: debugVisualizer           this is my component that doesn't appear in plugin view
  - id: redhat/java11/latest        this component appears in plugin view as installed
    type: chePlugin
  - mountSources: true
    memoryLimit: 512Mi
    type: dockerimage
    volumes:
      - name: m2
        containerPath: /home/user/.m2
    image: 'quay.io/eclipse/che-java11-maven:7.15.0'
...
```
![image](https://user-images.githubusercontent.com/22366719/86926258-21ee1c80-c132-11ea-8d49-fb15a5ee1b77.png)

The VS extension i added doesn't appear in the list

**Comment by erlansan** [comment]
@tolusha even tho the workspace is being created after adding the VS extension to devfile, it doesn't seem to have any effect. I've tried redoing it many times, the Plugin View stays the same. 
Is there any other approach i can try? 
Is there a possibility to access the plugin registry i'm currently running, and adding my VS extension to it? 
I tried following this guide: https://github.com/redhat-developer/codeready-workspaces/blob/master/devdoc/building/build-vsix-extension.adoc , but all the links are broken.

**Comment by benoitf** [comment]
vsix link should be https://github.com/erlansan/debug_visualizer/raw/master/hediet.debug-visualizer-1.1.0.vsix

**Comment by erlansan** [comment]
@benoitf thank you for the link! It works now. I have the commands from this VS extension available in the IDE.

**Comment by benoitf** [comment]
closing the issue then 👍

**Comment by erlansan** [comment]
Hello again :D 
I would like to reopen the issue. I tested the extension, and it didn't work as expected. But then i tried running the same VS extension in gitpod, which has embedded Theia IDE. 
Gitpod has this nice feature, where you can drag and drop VSIX files into plugin view, and they will be installed right away. The problem now is, that the VS extension works differently in gitpod than in my Che server.
I also tried running the same extension in VS Code itself, to know how it should've behaved. 
Here are the comparisons: 
Screenshot from VSC:
![image](https://user-images.githubusercontent.com/22366719/87161373-b8524780-c2c4-11ea-96b7-4abd889b9b67.png)

Screenshot from GitPod: 
![image](https://user-images.githubusercontent.com/22366719/87161559-ff403d00-c2c4-11ea-980b-f3bc76abc260.png)
You can see how GitPod has the same Debug View, but it doesn't read the values. The link to GitPod [workspace.](https://gitpod.io/#snapshot/3ac8fb90-12b4-4063-8af5-9337cadc8264)

Screenshot from local Che server:
![image](https://user-images.githubusercontent.com/22366719/87162310-0ddb2400-c2c6-11ea-98c8-58b754fd3aae.png)
As you can see, it's not the same as in GitPod. Whereas i would expect the same result from the same VS extension and same code snippets.

My Devfile components from Che server:
```
...
components:
  - memoryLimit: 512Mi
    type: chePlugin
    reference: >-  https://gist.githubusercontent.com/erlansan/4be0ef7b7177f79ce3a5205a9855c725/raw/a658bc27d56a026f72535769219eb8ff7f5f6dc1/meta.yaml
    alias: debugVisualizer
...
```
Content of **.gitpod.yml** from GitPod:
```
vscode:
  extensions:
    - hediet.debug-visualizer@1.1.0:e28CNc27zo2UDGVVCEGN0A==
```
My question is, how can i make my local installation of VS extension at least the same as in GitPod? Is there any way they are differently installed?
