### ISSUE TITLE
Support multiple remotes in devfile project spec

### ISSUE THREAD

**Issue by amisevsk** [eclipse-che/che#17449]
### Is your enhancement related to a problem? Please describe.
The current devfile spec makes using a forking git workflow a little cumbersome, as devfiles are either tied to the fork they're stored in or hard-code a specific remote. This means that common tasks such as 
- Grab changes from upstream and push to personal fork
- Work on local fork but grab changes from another remote
- Rebase a local branch onto latest upstream master

require manually adding a remote

### Describe the solution you'd like
Update devfile spec to allow additional `remoteName -> url` pairs
```yaml
projects:
  - name: che-plugin-broker
    source:
      location: 'https://github.com/amisevsk/che-plugin-broker.git'
      type: git
      branch: master
      remotes:
        upstream: https://github.com/eclipse/che-plugin-broker.git
        gh-collaborator: https://github.com/gh-collaborator/che-plugin-broker.git
    clonePath: src/github.com/eclipse/che-plugin-broker
```
To support the current common flow (no project -> use current repo), location/branch could be optional

### Describe alternatives you've considered
There's likely a better way to specify remotes structurally, this is just the first option that came to mind.

**Comment by ibuziuk** [comment]
I'm wondering about supporting ssh remotes, not only vanilla https. Can this be also addressed in this issue or do we need another one?

**Comment by l0rd** [comment]
I would rather consider that for devfile 2.0. And we may rename `location` into `origin`.

**Comment by ibuziuk** [comment]
> I would rather consider that for devfile 2.0. And we may rename location into origin.

Another idea could be removal of the `location` completely and adding some attribute e.g 'primary` to the `remotes` spec: 

```
    source:
      type: git
      branch: master
      remotes:
        upstream: https://github.com/eclipse/che-plugin-broker.git
            primary: 'true'
        gh-collaborator: https://github.com/gh-collaborator/che-plugin-broker.git
        some-ssh-remote: git@github.com:eclipse/che-plugin-broker.git
```
