### ISSUE TITLE
[dashboard] - having cheEditor component as reference fail to render Editors tab in workspace configuration

### ISSUE THREAD

**Issue by sparkoo** [eclipse-che/che#17467]
### Describe the bug
When devfile has `cheEditor` defined with reference, like example below, it fails to render Editors tab on workspace configuration.

```
apiVersion: 1.0.0
metadata:
  name: java-mysql-7ke6h
components:
  - type: cheEditor
    reference: >-
      https://gist.githubusercontent.com/sparkoo/89014d54200a1af0e5fcc4bd06965741/raw/48de009d215f7f7868c415bf2d8cdfce51a8bb93/gistfile1.txt
    alias: che-theia
```

Browser console log:
```
TypeError: e is undefined
    value app-d2302619c0.js:360163
    value app-d2302619c0.js:359998
    l app-d2302619c0.js:237154
    u app-d2302619c0.js:237202
    $digest app-d2302619c0.js:238321
    $apply app-d2302619c0.js:238709
    a app-d2302619c0.js:232552
    v app-d2302619c0.js:232809
    onload app-d2302619c0.js:232714
 Possibly unhandled rejection: {} app-d2302619c0.js:234776:41
```

It seems to work ok when you edit the devfile, save, and immediately go to Editors tab. To reproduce the issue, you must have saved devfile and start from Workspaces list page.

### Che version
 - [x] nightly

### Steps to reproduce
1. Create workspace with `cheEditor` defined with reference (example above)
1. Go to main workspaces list page
1. Go to Configure workspace page and open Editors tab

### Expected behavior
Page should be properly rendered

### Runtime
   - [x] minikube (include output of `minikube version` and `kubectl version`)

### Screenshots

![20200723_084526_1920x2160_scrot](https://user-images.githubusercontent.com/1160903/88258684-ff770a00-ccc0-11ea-86e3-137304c2a9a5.png)

### Installation method
   - [x] chectl

### Environment
   - [x] my computer
       - [x] Linux
