### ISSUE TITLE
If there is no plug-in for Lombok, it can be provided.

### ISSUE THREAD

**Issue by xiazhijian** [eclipse-che/che#17483]
### Is your enhancement related to a problem? Please describe.

Lombok is used in Java projects, but eclipse Che has no Lombok plug-in.
### Describe the solution you'd like

Provide Lombok plug-in
### Describe alternatives you've considered

Attempt to migrate reference [links ](https://www.eclipse.org/che/docs/che-7/building-and-running-a-custom-registry-image/#building-a-custom-devfile-registry_building-and-running-a-custom-registry-image)from vscode failed.

**Comment by xiazhijian** [comment]
In devfile JAVA_OPTS Add - javaagent :/projects/ lombok.jar And it doesn't work.
How to use - javaagent

**Comment by xiazhijian** [comment]
`metadata:
  name: highlands
projects:
  - name: iot-core
    source:
      location: 'git@scm.highlands.ltd:zxzx-iot/iot-core.git'
      type: git
      branch: master
  - name: iot-parent
    source:
      location: 'git@scm.highlands.ltd:zxzx-iot/iot-parent.git'
      type: git
  - name: iot-base
    source:
      location: 'git@scm.highlands.ltd:zxzx-iot/iot-base.git'
      type: git
      branch: master
  - name: iot-base-parent
    source:
      location: 'git@scm.highlands.ltd:zxzx-iot/iot-base-parent.git'
      type: git
      branch: master
components:
  - mountSources: true
    endpoints:
      - name: 8080/tcp
        port: 8080
    memoryLimit: 768Mi
    type: dockerimage
    volumes:
      - name: m2
        containerPath: /projects/.m2
    alias: tools
    image: 'quay.io/eclipse/che-java8-maven:nightly'
    env:
      - value: ''
        name: MAVEN_CONFIG
      - value: >-
          -javaagent:/projects/lombok.jar -XX:MaxRAMPercentage=50.0
          -XX:+UseParallelGC -XX:MinHeapFreeRatio=10 -XX:MaxHeapFreeRatio=20
          -XX:GCTimeRatio=4 -XX:AdaptiveSizePolicyWeight=90
          -Dsun.zip.disableMemoryMapping=true -Xms20m
          -Djava.security.egd=file:/dev/./urandom -Duser.home=/home/user
        name: JAVA_OPTS
      - value: >-
          -XX:MaxRAMPercentage=50.0 -XX:+UseParallelGC -XX:MinHeapFreeRatio=10
          -XX:MaxHeapFreeRatio=20 -XX:GCTimeRatio=4
          -XX:AdaptiveSizePolicyWeight=90 -Dsun.zip.disableMemoryMapping=true
          -Xms20m -Djava.security.egd=file:/dev/./urandom -Duser.home=/home/user
        name: MAVEN_OPTS
  - id: redhat/java8/latest
    type: chePlugin
apiVersion: 1.0.0
commands:
  - name: maven build iot-base-parent
    actions:
      - workdir: '${CHE_PROJECTS_ROOT}/iot-base-parent'
        type: exec
        command: mvn clean install --settings /projects/settings.xml
        component: tools
  - name: maven build iot-base
    actions:
      - workdir: '${CHE_PROJECTS_ROOT}/iot-base'
        type: exec
        command: mvn clean install --settings /projects/settings.xml
        component: tools
  - name: maven build iot-parent
    actions:
      - workdir: '${CHE_PROJECTS_ROOT}/iot-parent'
        type: exec
        command: mvn clean install --settings /projects/settings.xml
        component: tools
  - name: maven build iot-core
    actions:
      - workdir: '${CHE_PROJECTS_ROOT}/iot-core'
        type: exec
        command: mvn clean install --settings /projects/settings.xml
        component: tools
  - name: Debug remote java application
    actions:
      - referenceContent: |
          {
          "version": "0.2.0",
          "configurations": [
            {
              "type": "java",
              "name": "Debug (Attach) - Remote",
              "request": "attach",
              "hostName": "localhost",
              "port": 5005
            }]
          }
        type: vscode-launch
`

**Comment by ericwill** [comment]
Hi, you can test a plugin by adding it to a devfile, and putting the `meta.yaml` in a GitHub gist. You can find docs on how to do it here: https://www.eclipse.org/che/docs/che-7/using-a-visual-studio-code-extension-in-che/#adding-the-vs-code-extension-using-the-workspace-configuration_adding-che-plug-in-registry-vs-code-extension-to-a-workspace

**Comment by gattytto** [comment]
works https://github.com/gattytto/che-plugin-registry/blob/gopos/v3/plugins/ms-vscode/lombok/1.0.1/meta.yaml

![image](https://user-images.githubusercontent.com/407397/88612418-8af5ef80-d061-11ea-8e36-6bc14c33c043.png)

**Comment by gattytto** [comment]
can you try this devfile?
````yaml
metadata:
  name: lombok
projects:
  - name: iot-core
    source:
      location: 'git@scm.highlands.ltd:zxzx-iot/iot-core.git'
      type: git
      branch: master
  - name: iot-parent
    source:
      location: 'git@scm.highlands.ltd:zxzx-iot/iot-parent.git'
      type: git
  - name: iot-base
    source:
      location: 'git@scm.highlands.ltd:zxzx-iot/iot-base.git'
      type: git
      branch: master
  - name: iot-base-parent
    source:
      location: 'git@scm.highlands.ltd:zxzx-iot/iot-base-parent.git'
      type: git
      branch: master
components:
  - id: eclipse/che-theia/next
    type: cheEditor
  - id: redhat/java8/latest
    type: chePlugin
  - type: chePlugin
    reference: >-
      https://raw.githubusercontent.com/gattytto/che-plugin-registry/gopos/v3/plugins/ms-vscode/lombok/1.0.1/meta.yaml
    alias: lombok
  - type: dockerimage
    alias: maven
    image: quay.io/eclipse/che-java8-maven:nightly
    env:
      - name: MAVEN_CONFIG
        value: >-
          -javaagent:/projects/lombok.jar -XX:MaxRAMPercentage=50.0
          -XX:+UseParallelGC -XX:MinHeapFreeRatio=10 -XX:MaxHeapFreeRatio=20
          -XX:GCTimeRatio=4 -XX:AdaptiveSizePolicyWeight=90
          -Dsun.zip.disableMemoryMapping=true -Xms20m
          -Djava.security.egd=file:/dev/./urandom -Duser.home=/home/user
      - name: MAVEN_OPTS
        value: "-XX:MaxRAMPercentage=50 -XX:+UseParallelGC -XX:MinHeapFreeRatio=10
          -XX:MaxHeapFreeRatio=20 -XX:GCTimeRatio=4 -XX:AdaptiveSizePolicyWeight=90
          -Dsun.zip.disableMemoryMapping=true -Xms20m -Djava.security.egd=file:/dev/./urandom
          -Duser.home=/home/user"
      - name: JAVA_OPTS
        value: >-
          -XX:MaxRAMPercentage=50.0 -XX:+UseParallelGC -XX:MinHeapFreeRatio=10
          -XX:MaxHeapFreeRatio=20 -XX:GCTimeRatio=4
          -XX:AdaptiveSizePolicyWeight=90 -Dsun.zip.disableMemoryMapping=true
          -Xms20m -Djava.security.egd=file:/dev/./urandom -Duser.home=/home/user
      - name: JAVA_TOOL_OPTIONS
        value: "-XX:MaxRAMPercentage=50 -XX:+UseParallelGC -XX:MinHeapFreeRatio=10
          -XX:MaxHeapFreeRatio=20 -XX:GCTimeRatio=4 -XX:AdaptiveSizePolicyWeight=90
          -Dsun.zip.disableMemoryMapping=true -Xms20m -Djava.security.egd=file:/dev/./urandom"
    memoryLimit: 512Mi
    mountSources: true
    volumes:
      - name: m2
        containerPath: /home/user/.m2
    endpoints:
      - name: 8080/tcp
        port: 8080
apiVersion: 1.0.0
````

**Comment by xiazhijian** [comment]
> can you try this devfile?
> 
> ```yaml
> metadata:
>   name: lombok
> projects:
>   - name: iot-core
>     source:
>       location: 'git@scm.highlands.ltd:zxzx-iot/iot-core.git'
>       type: git
>       branch: master
>   - name: iot-parent
>     source:
>       location: 'git@scm.highlands.ltd:zxzx-iot/iot-parent.git'
>       type: git
>   - name: iot-base
>     source:
>       location: 'git@scm.highlands.ltd:zxzx-iot/iot-base.git'
>       type: git
>       branch: master
>   - name: iot-base-parent
>     source:
>       location: 'git@scm.highlands.ltd:zxzx-iot/iot-base-parent.git'
>       type: git
>       branch: master
> components:
>   - id: eclipse/che-theia/next
>     type: cheEditor
>   - id: redhat/java8/latest
>     type: chePlugin
>   - type: chePlugin
>     reference: >-
>       https://raw.githubusercontent.com/gattytto/che-plugin-registry/gopos/v3/plugins/ms-vscode/lombok/1.0.1/meta.yaml
>     alias: lombok
>   - type: dockerimage
>     alias: maven
>     image: quay.io/eclipse/che-java8-maven:nightly
>     env:
>       - name: MAVEN_CONFIG
>         value: >-
>           -javaagent:/projects/lombok.jar -XX:MaxRAMPercentage=50.0
>           -XX:+UseParallelGC -XX:MinHeapFreeRatio=10 -XX:MaxHeapFreeRatio=20
>           -XX:GCTimeRatio=4 -XX:AdaptiveSizePolicyWeight=90
>           -Dsun.zip.disableMemoryMapping=true -Xms20m
>           -Djava.security.egd=file:/dev/./urandom -Duser.home=/home/user
>       - name: MAVEN_OPTS
>         value: "-XX:MaxRAMPercentage=50 -XX:+UseParallelGC -XX:MinHeapFreeRatio=10
>           -XX:MaxHeapFreeRatio=20 -XX:GCTimeRatio=4 -XX:AdaptiveSizePolicyWeight=90
>           -Dsun.zip.disableMemoryMapping=true -Xms20m -Djava.security.egd=file:/dev/./urandom
>           -Duser.home=/home/user"
>       - name: JAVA_OPTS
>         value: >-
>           -XX:MaxRAMPercentage=50.0 -XX:+UseParallelGC -XX:MinHeapFreeRatio=10
>           -XX:MaxHeapFreeRatio=20 -XX:GCTimeRatio=4
>           -XX:AdaptiveSizePolicyWeight=90 -Dsun.zip.disableMemoryMapping=true
>           -Xms20m -Djava.security.egd=file:/dev/./urandom -Duser.home=/home/user
>       - name: JAVA_TOOL_OPTIONS
>         value: "-XX:MaxRAMPercentage=50 -XX:+UseParallelGC -XX:MinHeapFreeRatio=10
>           -XX:MaxHeapFreeRatio=20 -XX:GCTimeRatio=4 -XX:AdaptiveSizePolicyWeight=90
>           -Dsun.zip.disableMemoryMapping=true -Xms20m -Djava.security.egd=file:/dev/./urandom"
>     memoryLimit: 512Mi
>     mountSources: true
>     volumes:
>       - name: m2
>         containerPath: /home/user/.m2
>     endpoints:
>       - name: 8080/tcp
>         port: 8080
> apiVersion: 1.0.0
> ```

{
  message: 'Starting Java server with: /usr/lib/jvm/default-jvm/bin/java -Declipse.application=org.eclipse.jdt.ls.core.id1 -Dosgi.bundles.defaultStartLevel=4 -Declipse.product=org.eclipse.jdt.ls.core.product -Dfile.encoding=utf8 -XX:+UseParallelGC -XX:GCTimeRatio=4 -XX:AdaptiveSizePolicyWeight=90 -Dsun.zip.disableMemoryMapping=true -Xmx1G -Xms100m -javaagent:/tmp/vscode-unpacked/ms-vscode.lombok.1.0.2.cmkuzimeix.GabrielBB.vscode-lombok-1.0.2.vsix/extension/server/lombok.jar -noverify -jar /tmp/vscode-unpacked/redhat.java8.latest.euusuztoxn.java-0.63.0-2222.vsix/extension/server/plugins/org.eclipse.equinox.launcher_1.5.700.v20200207-2156.jar -configuration /home/theia/home/theia/redhat.java/0.63.0/config_ss_linux -data /home/theia/home/theia/redhat.java/ss_ws',
  level: 'info',
  timestamp: '2020-07-28 03:58:03.884'
}
{
  message: 'Starting Java server with: /usr/lib/jvm/default-jvm/bin/java -Declipse.application=org.eclipse.jdt.ls.core.id1 -Dosgi.bundles.defaultStartLevel=4 -Declipse.product=org.eclipse.jdt.ls.core.product -Dfile.encoding=utf8 -XX:+UseParallelGC -XX:GCTimeRatio=4 -XX:AdaptiveSizePolicyWeight=90 -Dsun.zip.disableMemoryMapping=true -Xmx1G -Xms100m -javaagent:/tmp/vscode-unpacked/ms-vscode.lombok.1.0.2.cmkuzimeix.GabrielBB.vscode-lombok-1.0.2.vsix/extension/server/lombok.jar -noverify -jar /tmp/vscode-unpacked/redhat.java8.latest.euusuztoxn.java-0.63.0-2222.vsix/extension/server/plugins/org.eclipse.equinox.launcher_1.5.700.v20200207-2156.jar -configuration /home/theia/home/theia/redhat.java/0.63.0/config_linux -data /home/theia/home/theia/redhat.java/jdt_ws',
  level: 'info',
  timestamp: '2020-07-28 03:58:03.897'
}
{
  message: 'Error opening zip file or JAR manifest missing : /tmp/vscode-unpacked/ms-vscode.lombok.1.0.2.cmkuzimeix.GabrielBB.vscode-lombok-1.0.2.vsix/extension/server/lombok.jar\n',
  level: 'info',
  timestamp: '2020-07-28 03:58:03.912'
}
{
  message: 'Error opening zip file or JAR manifest missing : /tmp/vscode-unpacked/ms-vscode.lombok.1.0.2.cmkuzimeix.GabrielBB.vscode-lombok-1.0.2.vsix/extension/server/lombok.jar\n',
  level: 'info',
  timestamp: '2020-07-28 03:58:03.913'
}
{
  message: 'The Language Support for Java server crashed and will restart.',
  level: 'error',
  timestamp: '2020-07-28 03:58:03.914'
}
{
  message: '[Info  - 3:58:03 AM] Connection to server got closed. Server will restart.',
  level: 'info',
  timestamp: '2020-07-28 03:58:03.916'
}
{
  message: 'The Language Support for Java (Syntax Server) server crashed and will restart.',
  level: 'error',
  timestamp: '2020-07-28 03:58:03.916'
}
{
  message: '[Info  - 3:58:03 AM] Connection to server got closed. Server will restart.',
  level: 'info',
  timestamp: '2020-07-28 03:58:03.917'
}
{
  message: 'Language Support for Java (Syntax Server) server encountered error and will shut down: undefined, Error: write EPIPE',
  level: 'error',
  timestamp: '2020-07-28 03:58:03.927'
}
{
  message: '[Error - 3:58:03 AM] Connection to server is erroring. Shutting down server.',
  level: 'info',
  timestamp: '2020-07-28 03:58:03.927'
}
{
  message: 'Language Support for Java (Syntax Server) server encountered error and will shut down: undefined, Error [ERR_STREAM_DESTROYED]: Cannot call write after a stream was destroyed',
  level: 'error',
  timestamp: '2020-07-28 03:58:03.929'
}
{
  message: '[Error - 3:58:03 AM] Connection to server is erroring. Shutting down server.',
  level: 'info',
  timestamp: '2020-07-28 03:58:03.930'
}
{
  message: 'Language Support for Java (Syntax Server) server encountered error and will shut down: undefined, Error [ERR_STREAM_DESTROYED]: Cannot call write after a stream was destroyed',
  level: 'error',
  timestamp: '2020-07-28 03:58:03.930'
}
{
  message: '[Error - 3:58:03 AM] Connection to server is erroring. Shutting down server.',
  level: 'info',
  timestamp: '2020-07-28 03:58:03.930'
}
{
  message: 'Language Support for Java (Syntax Server) server encountered error and will shut down: undefined, Error [ERR_STREAM_DESTROYED]: Cannot call write after a stream was destroyed',
  level: 'error',
  timestamp: '2020-07-28 03:58:03.930'
}
{
  message: '[Error - 3:58:03 AM] Connection to server is erroring. Shutting down server.',
  level: 'info',
  timestamp: '2020-07-28 03:58:03.931'
}
{
  message: 'Error opening zip file or JAR manifest missing : /tmp/vscode-unpacked/ms-vscode.lombok.1.0.2.cmkuzimeix.GabrielBB.vscode-lombok-1.0.2.vsix/extension/server/lombok.jar\n',
  level: 'info',
  timestamp: '2020-07-28 03:58:03.932'
}
{
  message: 'Error opening zip file or JAR manifest missing : /tmp/vscode-unpacked/ms-vscode.lombok.1.0.2.cmkuzimeix.GabrielBB.vscode-lombok-1.0.2.vsix/extension/server/lombok.jar\n',
  level: 'info',
  timestamp: '2020-07-28 03:58:03.932'
}
{
  message: 'The Language Support for Java server crashed and will restart.',
  level: 'error',
  timestamp: '2020-07-28 03:58:03.932'
}
{
  message: '[Info  - 3:58:03 AM] Connection to server got closed. Server will restart.',
  level: 'info',
  timestamp: '2020-07-28 03:58:03.932'
}
{
  message: 'Error opening zip file or JAR manifest missing : /tmp/vscode-unpacked/ms-vscode.lombok.1.0.2.cmkuzimeix.GabrielBB.vscode-lombok-1.0.2.vsix/extension/server/lombok.jar\n',
  level: 'info',
  timestamp: '2020-07-28 03:58:03.939'
}
{
  message: 'The Language Support for Java server crashed and will restart.',
  level: 'error',
  timestamp: '2020-07-28 03:58:03.940'
}
{
  message: '[Info  - 3:58:03 AM] Connection to server got closed. Server will restart.',
  level: 'info',
  timestamp: '2020-07-28 03:58:03.940'
}
{
  message: 'Error opening zip file or JAR manifest missing : /tmp/vscode-unpacked/ms-vscode.lombok.1.0.2.cmkuzimeix.GabrielBB.vscode-lombok-1.0.2.vsix/extension/server/lombok.jar\n',
  level: 'info',
  timestamp: '2020-07-28 03:58:03.949'
}
{
  message: 'The Language Support for Java server crashed and will restart.',
  level: 'error',
  timestamp: '2020-07-28 03:58:03.949'
}
{
  message: '[Info  - 3:58:03 AM] Connection to server got closed. Server will restart.',
  level: 'info',
  timestamp: '2020-07-28 03:58:03.950'
}
{
  message: 'Error opening zip file or JAR manifest missing : /tmp/vscode-unpacked/ms-vscode.lombok.1.0.2.cmkuzimeix.GabrielBB.vscode-lombok-1.0.2.vsix/extension/server/lombok.jar\n',
  level: 'info',
  timestamp: '2020-07-28 03:58:03.956'
}
{
  message: 'The Language Support for Java server crashed 5 times in the last 3 minutes. The server will not be restarted.',
  level: 'error',
  timestamp: '2020-07-28 03:58:03.957'
}
{
  message: '[Error - 3:58:03 AM] Connection to server got closed. Server will not be restarted.',
  level: 'info',
  timestamp: '2020-07-28 03:58:03.958'
}

**Comment by gattytto** [comment]
ok, it's an advance, this might mean lombok.jar needs to be included in the sidecar, I'll take a look in a few hours because my internet is not working properly now, maybe other users here can do some more testings. 

Don't give up

**Comment by xiazhijian** [comment]
> ok, it's an advance, this might mean lombok.jar needs to be included in the sidecar, I'll take a look in a few hours because my internet is not working properly now, maybe other users here can do some more testings.
> 
> Don't give up

That's OK. Thank you very much!

**Comment by gattytto** [comment]
I have edited the extension yaml, can you try again? please test the specifics and report any detail that can be useful to have it 100% working, I don't have access to the repos you are using so I don't know what should work and how. Good luck @xiazhijian 

![image](https://user-images.githubusercontent.com/407397/88747594-7e3acf80-d125-11ea-9c8c-24327b24dffd.png)

**Comment by gattytto** [comment]
@ericwill I think this is proof that lombok can be added to che but I haven't really tested what has to work and what doesn't. Still, no errors in tests, but issue author seems to be out of interest. Maybe this issue can be closed?

**Comment by asavin-cl** [comment]
Hi @gattytto, I also try to add Lombok support to my workspace but it does not work properly.
Are you have any advice about how I can realize support Lombok in my workspace.

**Comment by gattytto** [comment]
@asavin-cl you can add your project to this devfile to test lombok. Please report what's working and what isn't.

````yaml
metadata:
  name: lombok
projects:
  - name: iot-core
    source:
      location: 'git@github.com:user/project.git'
      type: git
      branch: master
components:
  - id: eclipse/che-theia/next
    type: cheEditor
  - id: redhat/java8/latest
    type: chePlugin
  - type: chePlugin
    reference: >-
      https://raw.githubusercontent.com/gattytto/cheplugins/master/lombok/1.0.1/meta.yaml
    alias: lombok
  - type: dockerimage
    alias: maven
    image: quay.io/eclipse/che-java8-maven:nightly
    env:
      - name: MAVEN_CONFIG
        value: >-
          -javaagent:/projects/lombok.jar -XX:MaxRAMPercentage=50.0
          -XX:+UseParallelGC -XX:MinHeapFreeRatio=10 -XX:MaxHeapFreeRatio=20
          -XX:GCTimeRatio=4 -XX:AdaptiveSizePolicyWeight=90
          -Dsun.zip.disableMemoryMapping=true -Xms20m
          -Djava.security.egd=file:/dev/./urandom -Duser.home=/home/user
      - name: MAVEN_OPTS
        value: "-XX:MaxRAMPercentage=50 -XX:+UseParallelGC -XX:MinHeapFreeRatio=10
          -XX:MaxHeapFreeRatio=20 -XX:GCTimeRatio=4 -XX:AdaptiveSizePolicyWeight=90
          -Dsun.zip.disableMemoryMapping=true -Xms20m -Djava.security.egd=file:/dev/./urandom
          -Duser.home=/home/user"
      - name: JAVA_OPTS
        value: >-
          -XX:MaxRAMPercentage=50.0 -XX:+UseParallelGC -XX:MinHeapFreeRatio=10
          -XX:MaxHeapFreeRatio=20 -XX:GCTimeRatio=4
          -XX:AdaptiveSizePolicyWeight=90 -Dsun.zip.disableMemoryMapping=true
          -Xms20m -Djava.security.egd=file:/dev/./urandom -Duser.home=/home/user
      - name: JAVA_TOOL_OPTIONS
        value: "-XX:MaxRAMPercentage=50 -XX:+UseParallelGC -XX:MinHeapFreeRatio=10
          -XX:MaxHeapFreeRatio=20 -XX:GCTimeRatio=4 -XX:AdaptiveSizePolicyWeight=90
          -Dsun.zip.disableMemoryMapping=true -Xms20m -Djava.security.egd=file:/dev/./urandom"
    memoryLimit: 512Mi
    mountSources: true
    volumes:
      - name: m2
        containerPath: /home/user/.m2
    endpoints:
      - name: 8080/tcp
        port: 8080
apiVersion: 1.0.0
````

**Comment by asavin-cl** [comment]
@gattytto 
When I have more than one workspace with **Lombok** extension I got the error.
```
  message: 'Error opening zip file or JAR manifest missing : /tmp/vscode-unpacked/gabrielbb.lombok.1.0.1.uvkoluuenm.GabrielBB.vscode-lombok-1.0.1.vsix/extension/server/lombok.jar\n',
  level: 'info',
  timestamp: '2020-09-02 15:07:33.897'
}
{
  message: 'The Language Support for Java server crashed 5 times in the last 3 minutes. The server will not be restarted.',
  level: 'error',
  timestamp: '2020-09-02 15:07:33.898'
}
{
  message: '[Error - 3:07:33 PM] Connection to server got closed. Server will not be restarted.',
  level: 'info',
  timestamp: '2020-09-02 15:07:33.898'
}
```
But in the container path to the file is different.
```
/projects $ ls -la /tmp/vscode-unpacked/
total 12
drwxr-xr-x    3 user     root          4096 Sep  2 15:05 .
drwxrwxrwt    1 root     root          4096 Sep  2 15:05 ..
drwxr-xr-x    3 user     root          4096 Sep  2 15:05 ms-vscode.lombok.1.0.1.suzmvrjiia.GabrielBB.vscode-lombok-1.0.1.vsix
```

**Comment by asavin-cl** [comment]
I think a problem with the startup-config. Unfortunately, I do not understand where the value can be assigned.
The value is **-javaagent:/tmp/vscode-unpacked/gabrielbb.lombok.1.0.1.uvkoluuenm.GabrielBB.vscode-lombok-1.0.1.vsix/extension/server/lombok.jar**
```
{
  message: 'Starting Java server with: /usr/lib/jvm/default-jvm/bin/java -Declipse.application=org.eclipse.jdt.ls.core.id1 -Dosgi.bundles.defaultStartLevel=4 -Declipse.product=org.eclipse.jdt.ls.core.product -Dfile.encoding=utf8 -XX:+UseParallelGC -XX:GCTimeRatio=4 -XX:AdaptiveSizePolicyWeight=90 -Dsun.zip.disableMemoryMapping=true -Xmx1G -Xms100m -javaagent:/tmp/vscode-unpacked/gabrielbb.lombok.1.0.1.uvkoluuenm.GabrielBB.vscode-lombok-1.0.1.vsix/extension/server/lombok.jar -noverify -jar /tmp/vscode-unpacked/redhat.java8.0.63.0.kjyvusrhoz.java-0.63.0-2222.vsix/extension/server/plugins/org.eclipse.equinox.launcher_1.5.700.v20200207-2156.jar -configuration /home/theia/home/theia/redhat.java/0.63.0/config_linux -data /home/theia/home/theia/redhat.java/jdt_ws',
  level: 'info',
  timestamp: '2020-09-02 15:50:08.777'
}
```

**Comment by asavin-cl** [comment]
Now I use that plugin configuration,
And that allows me to reconfigure Jdt settings.json configuration automatically.
```
apiVersion: v2
publisher: redhat
name: java8
version: 0.64.1
type: VS Code extension
displayName: Language Support for Java 8
title: Language Support for Java(TM) by Red Hat
description: Java Linting, Intellisense, formatting, refactoring, Maven/Gradle support and more...
icon: https://raw.githubusercontent.com/redhat-developer/vscode-java/v0.63.0/icons/icon128.png
repository: https://github.com/redhat-developer/vscode-java
category: Language
firstPublicationDate: "2020-06-11"
spec:
  containers:
    - image: "quay.io/eclipse/che-sidecar-java:8-0cfbacb"
      name: vscode-java
      memoryLimit: "2000Mi"
      volumes:
      - mountPath: "/home/theia/.m2"
        name: m2
  extensions:
    - https://open-vsx.org/api/vscjava/vscode-java-debug/0.28.0/file/vscjava.vscode-java-debug-0.28.0.vsix
    - https://open-vsx.org/api/redhat/java/0.64.1/file/redhat.java-0.64.1.vsix
    - https://open-vsx.org/api/vscjava/vscode-java-test/0.24.0/file/vscjava.vscode-java-test-0.24.0.vsix
    - https://open-vsx.org/api/cool2k/vscode-lombok/1.0.2/file/cool2k.vscode-lombok-1.0.2.vsix
```
But because that value applying for User settings.json I need restart Workspace each time.
I if the Lombok will be changing Workspace settings.json it will more convenient.

**Comment by gattytto** [comment]
Thank you for the info I'll be checking on this

**Comment by asavin-cl** [comment]
Hi @gattytto 
Any updates?

**Comment by oleksandr-ilin** [comment]
Is there any workaround for this bug? We need to use Lombok in multiple workspaces for one user and this issue is blocker. Thanks.

**Comment by gattytto** [comment]
> Now I use that plugin configuration,
> And that allows me to reconfigure Jdt settings.json configuration automatically.

same as the env: part of the devfile I posted earlier, you can use env vars in the sidecar too, will that suffice to persist the config?
refer to this doc: https://access.redhat.com/documentation/en-us/red_hat_codeready_workspaces/2.2/html-single/end-user_guide/index Table 4.3. spec.containers

**Comment by gattytto** [comment]
@asavin-cl can you get to mattermost.eclipse.org in channel #eclipse che, so we can talk more fluidly?

**Comment by gattytto** [comment]
I have made some changes to the devfile and the plugin meta.yaml, please try this devfile with your own project:
````yaml
apiVersion: 1.0.0
metadata:
  name: Lombok
projects:
  - name: iot-core
    source:
      location: 'https://github.com/chuucks/LOMBOK-PROJECT-EXAMPLE'
      type: git
      branch: master
components:
  - id: redhat/java8/latest
    type: chePlugin
    volumes:
      - containerPath: /tmp/vscode-unpacked
        name: lombok-java-unpacked
    preferences:
      java.jdt.ls.vmargs: -javaagent:/tmp/vscode-unpacked/lombok.jar
  - type: chePlugin
    reference: >-
      https://raw.githubusercontent.com/gattytto/cheplugins/master/lombok/1.0.1/meta.yaml
    volumes:
      - containerPath: /tmp/vscode-unpacked
        name: lombok-java-unpacked
    alias: lombok
  - id: eclipse/che-theia/next
    type: cheEditor
  - type: dockerimage
    command:
      - sh
      - -c
    args:
      - until [ -d /tmp/vscode-unpacked/*lombok* ]; do sleep 1; done; cp $(find /tmp |grep lombok |grep jar) /tmp/vscode-unpacked/; sleep infinity
    alias: maven
    image: quay.io/eclipse/che-java8-maven:nightly
    env:
      - name: MAVEN_CONFIG
        value: >-
          -javaagent:/tmp/vscode-unpacked/lombok.jar -XX:MaxRAMPercentage=50.0
          -XX:+UseParallelGC -XX:MinHeapFreeRatio=10 -XX:MaxHeapFreeRatio=20
          -XX:GCTimeRatio=4 -XX:AdaptiveSizePolicyWeight=90
          -Dsun.zip.disableMemoryMapping=true -Xms20m
          -Djava.security.egd=file:/dev/./urandom -Duser.home=/home/user
      - name: MAVEN_OPTS
        value: >-
          -XX:MaxRAMPercentage=50 -XX:+UseParallelGC -XX:MinHeapFreeRatio=10
          -XX:MaxHeapFreeRatio=20 -XX:GCTimeRatio=4 -XX:AdaptiveSizePolicyWeight=90
          -Dsun.zip.disableMemoryMapping=true -Xms20m -Djava.security.egd=file:/dev/./urandom
          -Duser.home=/home/user
      - name: JAVA_OPTS
        value: >-
          -XX:MaxRAMPercentage=50.0 -XX:+UseParallelGC -XX:MinHeapFreeRatio=10
          -XX:MaxHeapFreeRatio=20 -XX:GCTimeRatio=4
          -XX:AdaptiveSizePolicyWeight=90 -Dsun.zip.disableMemoryMapping=true
          -Xms20m -Djava.security.egd=file:/dev/./urandom -Duser.home=/home/user
      - name: JAVA_TOOL_OPTIONS
        value: >-
          -XX:MaxRAMPercentage=50 -XX:+UseParallelGC -XX:MinHeapFreeRatio=10
          -XX:MaxHeapFreeRatio=20 -XX:GCTimeRatio=4 -XX:AdaptiveSizePolicyWeight=90
          -Dsun.zip.disableMemoryMapping=true -Xms20m -Djava.security.egd=file:/dev/./urandom
    memoryLimit: 512Mi
    mountSources: true
    volumes:
      - name: m2
        containerPath: /home/user/.m2
      - name: lombok-java-unpacked
        containerPath: /tmp/vscode-unpacked
    endpoints:
      - name: 8080/tcp
        port: 8080
````

**Comment by sunix** [comment]
@gattytto @asavin-cl @oleksandr-ilin @xiazhijian 
we decided not to use the vscode-lombok extension. All it was doing was to provide the lombok.jar and setting the location of the jar in the user settings. It doesn't work with Che because the user could start a Java workspace without the lombok extension and be looking for the jar file which would not be present.

The proposed approach is to include lombok.jar in the java sidecar container and the user could just activated in the devfile with 
```
  - id: redhat/java/latest
    type: chePlugin
    preferences:
      java.jdt.ls.vmargs: -javaagent:/home/theia/lombok.jar
```
There is a devfile you could try out in the PR: https://github.com/eclipse/che-plugin-registry/pull/761#issuecomment-784020645
