### ISSUE TITLE
Workspaces namespaces should be labelled

### ISSUE THREAD

**Issue by l0rd** [eclipse-che/che#17504]
### Is your enhancement related to a problem? Please describe.

If users are manually creating their workspace namespaces there is no way to do a cleanup of those workspaces.

### Describe the solution you'd like

If the che-server is creating the namespace it should add some labels:

```yaml
  labels:
    app.kubernetes.io/part-of: che.eclipse.org
    app.kubernetes.io/component: workspace-namespace
```
