### ISSUE TITLE
Add a possibility to ship metrics over secure channel

### ISSUE THREAD

**Issue by ibuziuk** [eclipse-che/che#17509]
### Is your task related to a problem? Please describe.
Currently, `che-host` svc exposes the 8087 TCP port for metrics endpoint:

```
Port:              metrics  8087/TCP
TargetPort:        8087/TCP
Endpoints:         10.129.158.6:8087
```

This allows creating the following ServiceMonitor that would scrape the metrics over http://che-host:8087 (svc name _ port combo)

```
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: openshift-workspaces-exporter
spec:
  endpoints:
  - interval: 30s
    port: metrics
    scheme: http
  namespaceSelector:
    matchNames:
    - openshift-workspaces
  selector:
    matchLabels:
      component: che
```

However, when using OpenShift components like OpenShift cluster monitoring (opinionated Prometheus install) it is strongly recommended to use https and secure `/metrics` endpoint on the emitter side. 

### Describe the solution you'd like
the usual recommendation was to put `kube-rbac-proxy` sidecar and let it handle https traffic - 
example: https://github.com/openshift/cluster-monitoring-operator/blob/master/assets/node-exporter/daemonset.yaml#L53-L79

### Describe alternatives you've considered
Continue using http, but this is not recommended and at some point, it will not be possible to use vanilla http scheme for openshift cluster monitoring. 

e2e OCP test - https://github.com/openshift/origin/blob/master/test/extended/prometheus/prometheus.go#L255-L294

for the first iteration, it is possible to be added to the exclude list, but this is a technical debt that must be addressed in the future iterations.

### Additional context
if the `http` sheme is specified then data will be scraped over the insecure channel. Specifying `https` forces to specify additional parameters to ensure transport over the secure channel. 

Example: https://github.com/openshift/cluster-monitoring-operator/blob/master/assets/node-exporter/service-monitor.yaml

NOTE: Metrics are exposed over http and that's what OpenShuft cluster Prometheus expects. TCP sheme is NOT supported.
