### ISSUE TITLE
Document how to deploy gateway singlehost with Chectl

### ISSUE THREAD

**Issue by metlos** [eclipse-che/che#17525]
`chectl` should support deploying the che server in single-host mode with gateway. This will probably build on top of #17064 and #17065 that implement this on the lower level in helm chart and the operator.

### Describe the solution you'd like
Use `CheCluster` patch (might not be final, watch https://github.com/eclipse/che-operator/pull/378 for final form):
```
apiVersion: org.eclipse.che/v1
kind: CheCluster
metadata:
  name: eclipse-che
spec:
  server:
    serverExposureStrategy: 'single-host'
    singleHostExposureType: 'gateway'
```
together with chectl:
```
chectl server:start --che-operator-cr-patch-yaml=<patch> ...
```

Chectl already supports applying custom `CheCluster` patch. 
Goal of this issue is to **document** how to deploy Che with chectl:
 - [ ] using Operator with custom `CheCluster` patch
 - [ ] using helm with custom templates

### Additional context
This is a subtask of #12914.
