### ISSUE TITLE
Workspace is failing due to failing containers

### ISSUE THREAD

**Issue by awsompankaj** [eclipse-che/che#17561]
My custom stack which is running fine on eclipse che hosted on OCP 3.11 is running fine.

the same stack when i run on echipse che hosted on kubernetes cluster it is failing.

![image](https://user-images.githubusercontent.com/1574955/89300770-5815b200-d686-11ea-9480-b258ee532d82.png)

below is the devfile.
```yaml
metadata:
  name: Demostack
components:
  - id: che-incubator/typescript/latest
    memoryLimit: 512Mi
    type: chePlugin
  - mountSources: true
    endpoints:
      - name: nodejs
        port: 3001
    memoryLimit: 512Mi
    type: dockerimage
    image: 'docker.io/awsompankaj/skytap:v5'
    alias: nodejs
  - mountSources: true
    endpoints:
      - name: postwoman
        port: 3000
    memoryLimit: 1024Mi
    type: dockerimage
    image: docker.io/liyasthomas/postwoman
    alias: postwomen
  - mountSources: true
    endpoints:
      - name: omnidb
        port: 8080
      - name: socket
        port: 25482
    memoryLimit: 1024Mi
    type: dockerimage
    image: docker.io/awsompankaj/omnidb:v1
    alias: omnidb
  - mountSources: true
    endpoints:
      - name: mongo
        port: 27017
    env:
      - name: MONGO_INITDB_ROOT_USERNAME
        value: root
      - name: MONGO_INITDB_ROOT_PASSWORD
        value: admin123
    memoryLimit: 1024Mi
    type: dockerimage
    image: docker.io/mongo
    alias: mongo
  - mountSources: true
    endpoints:
      - name: admin-mongo
        port: 1234
    memoryLimit: 1024Mi
    type: dockerimage
    image: docker.io/awsompankaj/admin-mongo:v4
    alias: admin-mongo
  - mountSources: true
    endpoints:
      - name: nginx
        port: 80
    memoryLimit: 1024Mi
    type: dockerimage
    image: docker.io/awsompankaj/nginx-skytap
    alias: nginx-skytap
apiVersion: 1.0.0
```
