### ISSUE TITLE
Configubump tool produces incorrect configuration in some cases

### ISSUE THREAD

**Issue by skabashnyuk** [eclipse-che/che#17567]
### Describe the bug

Configubump tool produces incorrect configuration in some cases
https://github.com/che-incubator/configbump
Expected config

### Che version

 - [x] latest
 - [ ] nightly
 - [ ] other: please specify

### Steps to reproduce
TODO
### Expected behavior
```yaml
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  labels:
    app: che
    component: che
  name: che
spec:
  rules:
  - host: 192.168.39.214.nip.io
    http:
      paths:
      - backend:
          serviceName: che-gateway
          servicePort: 8080
        path: /
        pathType: Prefix
  tls:
  - hosts:
    - 192.168.39.214.nip.io
    secretName: che-tls
---
kind: Service
apiVersion: v1
metadata:
  name: che-gateway
spec:
  selector:
    app: che-gateway
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: che-gateway
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: che-gateway
rules:
- verbs:
  - watch
  - get
  - list
  apiGroups:
  - ""
  resources:
  - configmaps
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: che-gateway
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: che-gateway
subjects:
- kind: ServiceAccount
  name: che-gateway
---
kind: ConfigMap
apiVersion: v1
metadata:
  name: che-gateway-config
data:
  traefik.yml: |
    global:
      checkNewVersion: false
      sendAnonymousUsage: false
    entrypoints:
      http:
        address: ":8080"
      https:
        address: ":8443"   
    providers:
      file:
        directory: "/dynamic-config"
        watch: true
    log:
      level: "DEBUG"
---
kind: ConfigMap
apiVersion: v1
metadata:
  name: che-gateway-che
  labels:
    app: che
    role: gateway-config
data:
  che.yml: |
    http:
      routers:
        che:
          rule: "PathPrefix(`/`)"
          service: che
          priority: 1
        plugin-registry:
          rule: "PathPrefix(`/plugin-registry`)"
          service: plugin-registry
          middlewares: [plugin-registry]
          priority: 10
        devfile-registry:
          rule: "PathPrefix(`/devfile-registry`)"
          service: devfile-registry
          middlewares: [devfile-registry]
          priority: 10
      services:
        che:
          loadBalancer:
            servers:
            - url: 'http://che-host:8080'
        plugin-registry:
          loadBalancer:
            servers:
            - url: 'http://plugin-registry:8080'
        devfile-registry:
          loadBalancer:
            servers:
            - url: 'http://devfile-registry:8080'
      middlewares:
        plugin-registry:
          stripPrefix:
            prefixes:
            - '/plugin-registry'
        devfile-registry:
          stripPrefix:
            prefixes:
            - '/devfile-registry'
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: che-gateway
  labels:
    app: che-gateway
spec:
  replicas: 1
  selector:
    matchLabels:
      app: che-gateway
  template:
    metadata:
      labels:
        app: che-gateway
    spec:
      serviceAccount: che-gateway
      serviceAccountName: che-gateway
      containers:
      - name: traefik
        image: docker.io/traefik:v2.2.8
        volumeMounts:
        - name: static-config
          mountPath: /etc/traefik
        - name: dynamic-config
          mountPath: "/dynamic-config"
      - name: configbump
        image: quay.io/che-incubator/configbump:latest
        env:
        - name: CONFIG_BUMP_DIR
          value: "/dynamic-config"
        - name: CONFIG_BUMP_LABELS
          value: "app=che,role=gateway-config"
        - name: CONFIG_BUMP_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        volumeMounts:
        - name: dynamic-config
          mountPath: "/dynamic-config"
      volumes:
      - name: static-config
        configMap:
          name: che-gateway-config
      - name: dynamic-config
        emptyDir: {}
```

### Runtime
   - [x] kubernetes (include output of `kubectl version`)
   - [x] Openshift (include output of `oc version`)
   - [ ] minikube (include output of `minikube version` and `kubectl version`)
   - [ ] minishift (include output of `minishift version` and `oc version`)
   - [ ] docker-desktop + K8S (include output of `docker version` and `kubectl version`)
   - [ ] other: (please specify)

### Screenshots
n/a

### Installation method
   - [ ] chectl
     * provide a full command that was used to deploy Eclipse Che (including the output)
     * provide an output of `chectl version` command
   - [ ] OperatorHub
   - [x] I don't know

### Environment
   - [ ] my computer
       - [ ] Windows
       - [ ] Linux
       - [ ] macOS
   - [ ] Cloud
       - [ ] Amazon
       - [ ] Azure
       - [ ] GCE
       - [ ] other (please specify)
   - [ ] other: please specify

### Eclipse Che Logs
n/a
### Additional context
n/a
