### ISSUE TITLE
Volume for Theia data directory missing (plugin settings permanence)

### ISSUE THREAD

**Issue by matthewfisch** [eclipse-che/che#17587]
As described in the original issues related to PR https://github.com/eclipse/che-theia/pull/191 , a volume mount was required to enable state permanence in Theia plugin settings (allows plugins to store their settings, such as Atlascode's session cookies).

This was fixed merged into master, but was subsequently lost in a regression.

Here's the commit that was regressed: https://github.com/eclipse/che-theia/commit/c866bc4c45a22bc91d0f514cff051a02bf18ffa8

This can be resolved via Devfile component fixup, but should be resolved upstream in che-theia:
```
  - id: eclipse/che-theia/next
    type: cheEditor
    volumes:
      - name: theia-data
        containerPath: /home/theia/.theia
    alias: theia-editor
    env:
      - value: "0"
        name: NODE_TLS_REJECT_UNAUTHORIZED
```
