### ISSUE TITLE
Add an automated test of upgrade using a trusted SSL certificate

### ISSUE THREAD

**Issue by nickboldt** [eclipse-che/che#17595]
This may already exist, but if not we definitely need a concise process documented and scripted for performing automated install-and-upgrade tests of Che 7.y to 7.y+1

One suggested path forward here is to use a Subscription to the nightly Che application in Quay, but point to an older release, eg.,

```
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  # are these 2 items correct?
  name: eclipse-che
  namespace: che 
spec:
  channel: nightly
  installPlanApproval: Automatic
  name: eclipse-che-preview-openshift
  source: eclipse-che-operator-openshift
  sourceNamespace: openshift-marketplace
  startingCSV: cheoperator.v7.16.0
```
For testing updates from one RELEASED GA version to another:

```
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  # are these 2 items correct?
  name: eclipse-che
  namespace: che 
spec:
  channel: stable
  installPlanApproval: Automatic
  name: eclipse-che-preview-openshift
  source: eclipse-che-operator-openshift
  sourceNamespace: openshift-marketplace
  startingCSV: cheoperator.v7.16.0
```
then
`oc apply -f subscription.yaml`

There's also a Kubernetes application, so presumably we would want to do the above 2 tests x 2 to cover k8s as well as os:

https://quay.io/application/eclipse-che-operator-kubernetes/eclipse-che-preview-kubernetes?tab=description

Additional notes:

Here are the application registries in Quay to use in your Subscriptions. Note that the VERSIONS do not align to anything in reality, so 9.9.* = CI/nightly

* https://quay.io/application/eclipse-che-operator-kubernetes/eclipse-che-preview-kubernetes?tab=description
* https://quay.io/application/eclipse-che-operator-openshift/eclipse-che-preview-openshift?tab=description
and
* official CRW releases: https://quay.io/application/redhat-operators/codeready-workspaces
* nightly: https://quay.io/repository/crw/crw-2-rhel8-operator-metadata?tag=latest&tab=tags -> https://quay.io/application/crw/codeready-workspaces
* nightly including CVE respins: https://quay.io/application/rh-osbs-operators/codeready-workspaces
