### ISSUE TITLE
Keeps going "offline"

### ISSUE THREAD

**Issue by LaneGeek** [eclipse-che/che#17598]
I am a new user and loving Che. It is a great product. I have it running in Minikube on my Mac.

However, after a short period of inactivity (an hour?), the IDE goes "offline". This is very annoying. When I then restart the workspace, it takes a while to load and then all my open windows, terminal, etc are all gone! Yes, changes to files are not lost, but this is still very annoying.

Is there a way I can disable this time out or at the very least extended it to say 9999 hours? I want it to be always "online".

Thanks!

**Comment by benoitf** [comment]
Hello, you could use
```
server:
    ...
    customCheProperties:
      CHE_LIMITS_WORKSPACE_IDLE_TIMEOUT: '-1'
 ```
 to disable idle timeout
