### ISSUE TITLE
Kubernetes plugin fails with error: Unknown actor CheTelemetry

### ISSUE THREAD

**Issue by vitaliy-guliy** [eclipse-che/che#17609]
### Describe the bug

I'm trying to build the Kubernetes plugin from sources and launch.
The plugin adds a dedicated view to the left but any its command fails with a message 'Unknown actor CheTelemetry'

![Screenshot from 2020-08-10 16-15-20](https://user-images.githubusercontent.com/1655894/89786531-c0501200-db24-11ea-9ac3-f5f0edb55a7e.png)

![Screenshot from 2020-08-10 15-19-32](https://user-images.githubusercontent.com/1655894/89786330-6bac9700-db24-11ea-9895-2b6738eb5234.png)

### Steps to reproduce

1. Create a workspace from the devfile
2. Build the extension by commands 1.1, 1.2 from the devfile
3. Build runner for remote plugins with command 1.3
4. Run kubernetes extension as a remote plugin using command 2.1
5. Run Che-Theia with command 2.2
6. Open Che-Theia by `theia-dev` link for `theia-ide` container
7. Run any command provided by Kubernetes extension

Devfile to create the workspace

```
# Copyright (c) 2020 Red Hat, Inc.
# This program and the accompanying materials are made
# available under the terms of the Eclipse Public License 2.0
# which is available at https://www.eclipse.org/legal/epl-2.0/
#
# SPDX-License-Identifier: EPL-2.0
#
# See: https://sipb.mit.edu/doc/safe-shell/

apiVersion: 1.0.0

metadata:
  name: kubernetes-tooling-dev

projects:
  - name: che-sidecar-kubernetes-tooling
    source:
      location: 'https://github.com/che-dockerfiles/che-sidecar-kubernetes-tooling'
      type: git
      branch: '1.1.0'

  - name: vscode-kubernetes-tools
    source:
      location: 'https://github.com/Azure/vscode-kubernetes-tools'
      type: git
      branch: master

  - name: che-theia
    source:
      location: 'https://github.com/eclipse/che-theia'
      type: git
      branch: master

components:
  - type: cheEditor
    id: eclipse/che-theia/next
    alias: che-theia
    memoryLimit: 3072Mi

  - type: dockerimage
    image: 'quay.io/eclipse/che-theia-dev:next'
    alias: che-dev
    mountSources: true
    endpoints:
      - name: theia-dev-flow
        port: 3010
        attributes:
          protocol: http
          public: 'true'
    memoryLimit: 2048Mi

  - type: dockerimage
    image: 'quay.io/eclipse/che-sidecar-kubernetes-tooling:1.1.0-31a8464'
    alias: buildah-dev
    mountSources: true
    memoryLimit: 1536Mi
    env:
      - name: PLUGIN_REMOTE_ENDPOINT_EXECUTABLE
        value: 'tail -f /dev/null'

commands:

  #
  # Installs node dependencies, compiles VSCode Kubernetes extension
  #
  - name: '1.1 Kubernetes Plugin :: Install dependencies'
    actions:
      - workdir: /projects/vscode-kubernetes-tools
        type: exec
        command: |
          npm install
          echo -e "\n\e[32mDone.\e[0m"
        component: che-dev

  #
  # Packages VSCode Kubernetes extension to vsx file
  #
  - name: '1.2 Kubernetes Plugin :: Package'
    actions:
      - workdir: /projects/vscode-kubernetes-tools
        type: exec
        command: |
          vsce package
          echo -e "\n\e[32mPackaging complete.\e[0m"
        component: che-dev
  
  #
  # Compiles che-theia-plugin-remote
  #
  - name: '1.3 Che-Theia plugin-remote :: Compile'
    actions:
      - workdir: /projects/che-theia/extensions/eclipse-che-theia-plugin-remote
        type: exec
        command: |
          yarn
          echo -e "\n\e[32mDone.\e[0m"
        component: che-dev

  #
  # Runs remote VSCode Kubernetes extension
  #
  - name: '2.1 Run :: Remote Kubernetes extension'
    actions:
      - workdir: /tmp
        type: exec
        command: |
          mkdir -p /tmp/vscode-plugins
          cd /tmp/vscode-plugins
          curl -O -L https://github.com/redhat-developer/vscode-yaml/releases/download/0.7.2/redhat.vscode-yaml-0.7.2.vsix
          cp -f -v /projects/vscode-kubernetes-tools/vscode-kubernetes-tools-*.vsix /tmp/vscode-plugins/
          export THEIA_PLUGIN_ENDPOINT_DISCOVERY_PORT='2504'
          export THEIA_PLUGINS='local-dir:///tmp/vscode-plugins'
          node /projects/che-theia/extensions/eclipse-che-theia-plugin-remote/lib/node/plugin-remote.js
          echo -e "\n\e[32mDone.\e[0m"
        component: buildah-dev

  #
  # Runs test Che-Theia instance
  #
  - name: '2.2 Run :: Che-Theia'
    actions:
      - workdir: /home/theia
        type: exec
        command: |
          mkdir -p /tmp/theiadev_projects
          export CHE_PROJECTS_ROOT=/tmp/theiadev_projects
          export THEIA_PLUGIN_ENDPOINT_DISCOVERY_PORT='2504'
          node src-gen/backend/main.js /tmp/theiadev_projects --hostname=0.0.0.0 --port=3130
          echo -e "\e[32mDone.\e[0m"
        component: che-theia

  #
  # Logins to quay.io
  #
  - name: '3.1 Login to quay.io'
    actions:
      - workdir: /projects/che-sidecar-kubernetes-tooling
        type: exec
        command: |
          if [ ! -f "/tmp/username" ]; then
            read -p "Username: " USERNAME &&
            buildah login --username $USERNAME quay.io &&
            echo $USERNAME > /tmp/username &&
            echo -e "\e[32mDone.\e[0m"
          else
            echo 'You already logged in as' `cat /tmp/username`
          fi
        component: buildah-dev

  #
  # Builds image with Kubernetes plugin
  #
  - name: '3.2 Build the image'
    actions:
      - workdir: /projects/che-sidecar-kubernetes-tooling
        type: exec
        command: |
          if [ -f "/tmp/username" ]; then
              USERNAME=`cat /tmp/username`
              buildah bud -t quay.io/$USERNAME/che-sidecar-kubernetes-tooling:dev .
              echo 'Image built'
              buildah images
              echo -e "\e[32mDone.\e[0m"
          else
              echo 'You need to login the first'
          fi
        component: buildah-dev

  #
  # Pushes the image to quay.io
  # 
  - name: '3.3 Push to quay.io'
    actions:
      - workdir: /projects/che-sidecar-kubernetes-tooling
        type: exec
        command: |
          if [ -f "/tmp/username" ]; then
              USERNAME=`cat /tmp/username`
              PLUGIN_IMAGE_ID=`buildah images -q quay.io/$USERNAME/che-sidecar-kubernetes-tooling`
              echo 'The last built image ID is :' $PLUGIN_IMAGE_ID
              PLUGIN_IMAGE=quay.io/$USERNAME/che-sidecar-kubernetes-tooling:dev
              echo 'Pushing image' $PLUGIN_IMAGE
              echo $PLUGIN_IMAGE > /tmp/plugin_image
              buildah push $PLUGIN_IMAGE_ID docker://$PLUGIN_IMAGE
              echo -e "\e[32mDone.\e[0m"
          else
              echo 'The first, you need to login and build the image'
          fi
        component: buildah-dev

```

### Runtime
   - [x] minikube (include output of `minikube version` and `kubectl version`)

### Environment
   - [x] my computer
       - [x] Linux

**Comment by tsmaeder** [comment]
Note that I get the same exception when running a self-hosting workspace. I get hundreds of exceptions sometime, siginificantly slowing down Che.
 ```
Uncaught (in promise) Error: Unknown actor CheTelemetry
     at /remote-endpoint/node_modules/ theia/plugin-ext/lib/common/rpc-protocol.js:101
     at /remote-endpoint/node_modules/ theia/plugin-ext/lib/common/rpc-protocol.js:316
     at /remote-endpoint/node_modules/ theia/core/lib/common/event.js:176
theia.9492888ee606d68b680c.js:1:767722
    receiveReplyErr theia.9492888ee606d68b680c.js:1
    receiveOneMessage theia.9492888ee606d68b680c.js:1
    multiplexor theia.9492888ee606d68b680c.js:1
    t theia.9492888ee606d68b680c.js:1
    phsZ/u</e.prototype[Symbol.iterator]/</< theia.9492888ee606d68b680c.js:1
    invoke theia.9492888ee606d68b680c.js:1
    fire theia.9492888ee606d68b680c.js:1
    postMessage theia.9492888ee606d68b680c.js:1
    onRequest theia.9492888ee606d68b680c.js:1
    s theia.9492888ee606d68b680c.js:1
    s theia.9492888ee606d68b680c.js:1
    r theia.9492888ee606d68b680c.js:1
    r theia.9492888ee606d68b680c.js:1
    onRequest theia.9492888ee606d68b680c.js:1
```

**Comment by RomanNikitenko** [comment]
@vitaliy-guliy 

You could use `details` tags in the description, like here

<details>
<summary>Devfile</summary>

```
# Copyright (c) 2020 Red Hat, Inc.
# This program and the accompanying materials are made
# available under the terms of the Eclipse Public License 2.0
# which is available at https://www.eclipse.org/legal/epl-2.0/
#
# SPDX-License-Identifier: EPL-2.0
#
# See: https://sipb.mit.edu/doc/safe-shell/

apiVersion: 1.0.0

metadata:
  name: kubernetes-tooling-dev

projects:
  - name: che-sidecar-kubernetes-tooling
    source:
      location: 'https://github.com/che-dockerfiles/che-sidecar-kubernetes-tooling'
      type: git
      branch: '1.1.0'

  - name: vscode-kubernetes-tools
    source:
      location: 'https://github.com/Azure/vscode-kubernetes-tools'
      type: git
      branch: master

  - name: che-theia
    source:
      location: 'https://github.com/eclipse/che-theia'
      type: git
      branch: master

components:
  - type: cheEditor
    id: eclipse/che-theia/next
    alias: che-theia
    memoryLimit: 3072Mi

  - type: dockerimage
    image: 'quay.io/eclipse/che-theia-dev:next'
    alias: che-dev
    mountSources: true
    endpoints:
      - name: theia-dev-flow
        port: 3010
        attributes:
          protocol: http
          public: 'true'
    memoryLimit: 2048Mi

  - type: dockerimage
    image: 'quay.io/eclipse/che-sidecar-kubernetes-tooling:1.1.0-31a8464'
    alias: buildah-dev
    mountSources: true
    memoryLimit: 1536Mi
    env:
      - name: PLUGIN_REMOTE_ENDPOINT_EXECUTABLE
        value: 'tail -f /dev/null'

commands:

  #
  # Installs node dependencies, compiles VSCode Kubernetes extension
  #
  - name: '1.1 Kubernetes Plugin :: Install dependencies'
    actions:
      - workdir: /projects/vscode-kubernetes-tools
        type: exec
        command: |
          npm install
          echo -e "\n\e[32mDone.\e[0m"
        component: che-dev

  #
  # Packages VSCode Kubernetes extension to vsx file
  #
  - name: '1.2 Kubernetes Plugin :: Package'
    actions:
      - workdir: /projects/vscode-kubernetes-tools
        type: exec
        command: |
          vsce package
          echo -e "\n\e[32mPackaging complete.\e[0m"
        component: che-dev
  
  #
  # Compiles che-theia-plugin-remote
  #
  - name: '1.3 Che-Theia plugin-remote :: Compile'
    actions:
      - workdir: /projects/che-theia/extensions/eclipse-che-theia-plugin-remote
        type: exec
        command: |
          yarn
          echo -e "\n\e[32mDone.\e[0m"
        component: che-dev

  #
  # Runs remote VSCode Kubernetes extension
  #
  - name: '2.1 Run :: Remote Kubernetes extension'
    actions:
      - workdir: /tmp
        type: exec
        command: |
          mkdir -p /tmp/vscode-plugins
          cd /tmp/vscode-plugins
          curl -O -L https://github.com/redhat-developer/vscode-yaml/releases/download/0.7.2/redhat.vscode-yaml-0.7.2.vsix
          cp -f -v /projects/vscode-kubernetes-tools/vscode-kubernetes-tools-*.vsix /tmp/vscode-plugins/
          export THEIA_PLUGIN_ENDPOINT_DISCOVERY_PORT='2504'
          export THEIA_PLUGINS='local-dir:///tmp/vscode-plugins'
          node /projects/che-theia/extensions/eclipse-che-theia-plugin-remote/lib/node/plugin-remote.js
          echo -e "\n\e[32mDone.\e[0m"
        component: buildah-dev

  #
  # Runs test Che-Theia instance
  #
  - name: '2.2 Run :: Che-Theia'
    actions:
      - workdir: /home/theia
        type: exec
        command: |
          mkdir -p /tmp/theiadev_projects
          export CHE_PROJECTS_ROOT=/tmp/theiadev_projects
          export THEIA_PLUGIN_ENDPOINT_DISCOVERY_PORT='2504'
          node src-gen/backend/main.js /tmp/theiadev_projects --hostname=0.0.0.0 --port=3130
          echo -e "\e[32mDone.\e[0m"
        component: che-theia

  #
  # Logins to quay.io
  #
  - name: '3.1 Login to quay.io'
    actions:
      - workdir: /projects/che-sidecar-kubernetes-tooling
        type: exec
        command: |
          if [ ! -f "/tmp/username" ]; then
            read -p "Username: " USERNAME &&
            buildah login --username $USERNAME quay.io &&
            echo $USERNAME > /tmp/username &&
            echo -e "\e[32mDone.\e[0m"
          else
            echo 'You already logged in as' `cat /tmp/username`
          fi
        component: buildah-dev

  #
  # Builds image with Kubernetes plugin
  #
  - name: '3.2 Build the image'
    actions:
      - workdir: /projects/che-sidecar-kubernetes-tooling
        type: exec
        command: |
          if [ -f "/tmp/username" ]; then
              USERNAME=`cat /tmp/username`
              buildah bud -t quay.io/$USERNAME/che-sidecar-kubernetes-tooling:dev .
              echo 'Image built'
              buildah images
              echo -e "\e[32mDone.\e[0m"
          else
              echo 'You need to login the first'
          fi
        component: buildah-dev

  #
  # Pushes the image to quay.io
  # 
  - name: '3.3 Push to quay.io'
    actions:
      - workdir: /projects/che-sidecar-kubernetes-tooling
        type: exec
        command: |
          if [ -f "/tmp/username" ]; then
              USERNAME=`cat /tmp/username`
              PLUGIN_IMAGE_ID=`buildah images -q quay.io/$USERNAME/che-sidecar-kubernetes-tooling`
              echo 'The last built image ID is :' $PLUGIN_IMAGE_ID
              PLUGIN_IMAGE=quay.io/$USERNAME/che-sidecar-kubernetes-tooling:dev
              echo 'Pushing image' $PLUGIN_IMAGE
              echo $PLUGIN_IMAGE > /tmp/plugin_image
              buildah push $PLUGIN_IMAGE_ID docker://$PLUGIN_IMAGE
              echo -e "\e[32mDone.\e[0m"
          else
              echo 'The first, you need to login and build the image'
          fi
        component: buildah-dev

```
</details>

Sorry for the comment not related to the issue :-)
