### ISSUE TITLE
Can't login to Che Dashboard after updating Operator to 1.17.0

### ISSUE THREAD

**Issue by alexeykazakov** [eclipse-che/che#17638]
### Describe the bug
We have a Che Operator installed on an OCP cluster.
Recently we updated the operator to the latest 1.17.0 (from 1.16.2). Now the existing users (were created before the update) can't login:

```
Error: Failed to run the workspace: "Failure executing: POST at: https://172.30.0.1/api/v1/namespaces/ibuziuk-code/persistentvolumeclaims. Message: Forbidden!Configured service account doesn't have access. Service account may have been revoked. persistentvolumeclaims "claim-che-workspace" is forbidden: exceeded quota: for-ibuziuk, requested: requests.storage=5Gi, used: requests.storage=6Gi, limited: requests.storage=7Gi. The error may be caused by an expired token or changed password. Update Che server deployment with a new token or password."
```
This is the configuration we use: https://github.com/codeready-toolchain/toolchain-infra/blob/master/config/operators/che/che_cluster.yaml

But the users which can't login now were created with a bit different configuration.

So, we had:

```
  storage:
    preCreateSubPaths: true
    pvcClaimSize: 3Gi
    pvcStrategy: per-workspace
```
And the users could login.
Then we updated the configuration to 
```
  storage:
    preCreateSubPaths: true
    pvcClaimSize: 5Gi
    pvcStrategy: common
```
Then we updated the operator to 1.17.0.
And now the existing users can't login.

### Runtime
   - [x] Openshift (include output of `oc version`)

### Installation method
   - [x] OperatorHub

### Environment
   - [x] Cloud
       - [x] Amazon

### Eclipse Che Logs
https://gist.github.com/alexeykazakov/07d4897f5f10a438a50cc132b9981b37 (Look at the 'ibuziuk' user errors).
