### ISSUE TITLE
Add additional PVC for workspace

### ISSUE THREAD

**Issue by svkr2k** [eclipse-che/che#17653]
Dear forum members,

I'm running che in Minikube. I have a Persistent Volume (PV) created within the minikube single node.

and would like to access this PV from within my workspace. As this is not currently supported, I would like to try implementing it with your guidance.

Kindly provide me guidance on where I need to look to make changes to the code.
So far, I have seen the code in `infrastructures/kubernetes/src/main/java/org/eclipse/che/workspace/infrastructure/kubernetes`.
I have read `UniqueWorkspacePVCStrategy`, `PVCProvisioner.java`, etc.

@skabashnyuk , forum members recommended that I get in touch with you regarding this. Thank you !

**Comment by metlos** [comment]
I would also look into `PodMerger` and into `KubernetesInternalRuntime`.

**Comment by metlos** [comment]
And thank you for the willingness to help us out with this. Much appreciated! Please don't hesitate to bombard us with further questions :smile:

**Comment by svkr2k** [comment]
Thank you @metlos for encouraging ...
I would like to create a prototype first as a proof of concept... looking for a quick and dirty way to "hard-code" the pvc creation ...

**Comment by skabashnyuk** [comment]
@svkr2k how this feature will work? What if we use the same approach as we use with secrets? If PVC exists in the namespace with some labels we can mount it to the workspace?   See https://www.eclipse.org/che/docs/che-7/mounting-a-secret-as-a-file-or-an-environment-variable-into-a-workspace-container/
CC @l0rd

**Comment by svkr2k** [comment]
The approach for prototype that I'm going to try is as follows:
1. I shall create a PV for a host path such as `/home/huge-set-of-files`.
2. When a workspace is created, create a PVC that claims the PV created in step #17463 
3. Mount the PVC to a path `/home/huge-set-of-files` in the IDE container of the workspace

Hope this sounds okay ?
Finally, if this works, I would like to change the hostPath-based PV into a NFS-based PV.

**Comment by whafra** [comment]
@svkr2k  ，hi, how is the result?
i have the same  demand and  i deployed eclipse-che in k8s (private cloud enviroment and operator installer ).
 i tested the hostPath PV and NFS PV ,  i can get it  using kubectl command , however  the pv or pvc can not be mounted  into the workspace.
 It seemed that  the Volume attribute in devfile is not valid.
@skabashnyuk  ,could you give me some advice ? 
thanks a lot.

**Comment by skabashnyuk** [comment]
What about 

A volume that is going to be mounted to the all containers of the workspace pod.
```
apiVersion: v1
kind: PersistentVolume
metadata:
  name: task-pv-volume
  labels:
    type: local
    app.kubernetes.io/part-of: che.eclipse.org
    app.kubernetes.io/component: workspace-shared-volume
  annotations:
    che.eclipse.org/automount-workspace-shared-volume: 'true'
    che.eclipse.org/mount-path:/home/huge-set-of-files 
spec:
  storageClassName: manual
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/data"
```

A volume that is going to be mounted to the specific container of the workspace pod.
```
apiVersion: v1
kind: PersistentVolume
metadata:
  name: task-m2-voluem
  labels:
    type: local
    app.kubernetes.io/part-of: che.eclipse.org
    app.kubernetes.io/component: workspace-shared-volume
  annotations:
    che.eclipse.org/target-container: maven
    che.eclipse.org/mount-path:/home/user/.m2/repository
spec:
  storageClassName: manual
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/data"
```
CC @mshaposhnik @l0rd  Wdyt?
