### ISSUE TITLE
You are not allowed to start more workspaces

### ISSUE THREAD

**Issue by davidwindell** [eclipse-che/che#17662]
## Summary

We often see the error "You are not allowed to start more workspaces" and one of the team has to stop running a workspace so another team member can start more than one.

What is the actual cause of this error behind the scenes and how can we avoid it?

## Relevant information

Che 7.16.1 on Rancher / Kubernetes

**Comment by benoitf** [comment]
Hello,

default is 1 workspace limit

to increase to 3 for example:

```yaml
spec:
  server:
    customCheProperties:
        CHE_LIMITS_USER_WORKSPACES_RUN_COUNT: '3'
```
