### ISSUE TITLE
Introduce the preferable order for top-level Devfile fields

### ISSUE THREAD

**Issue by sleshchenko** [eclipse-che/che#17726]
### Is your task related to a problem? Please describe.
This issue is about introducing the preferable top-level Devfile fields order.
It means that we use that in our documentation and when Dashboard load any devfile - it reorders top-level fields in the agreed order. It's going to be:
```yaml
apiVersion: ...
metadata: ...
attributes: ...
projects: ...
components: ...
commands: ...
```
