### ISSUE TITLE
Add Flutter ms-vscode extension and sidecar to che

### ISSUE THREAD

**Issue by gattytto** [eclipse-che/che#17731]
extension urls:
https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter
https://flutter.dev/docs/development/tools/devtools/vscode
https://github.com/cirruslabs/docker-images-flutter

test sidecar source: https://github.com/gattytto/che-sidecar-flutter
sidecar-related stuff:
https://github.com/thedrhax-dockerfiles/android-avd it will be interesting to see how kvm (nested virt) arg can be passed to the workspace pod (thus to ct's) from extension meta.yaml ](https://github.com/eclipse/che/issues/17761). android sdk includes qemu binaries so it's good POC for [cloud based IoT dev](https://medium.com/@napperley/kotlin-native-for-iot-e5237b889c41). VNC sounds like a good way to have a webview of the running device ready for debugging. 

test devfile:
````yaml
metadata:
  name: fluttertproj
projects:
  - name: flutter-sdk-samples
    source:
      location: 'https://github.com/flutter/samples'
      type: git
components:
  - id: eclipse/che-theia/next
    type: cheEditor
  - type: chePlugin
    reference: >-
      https://raw.githubusercontent.com/gattytto/cheplugins/master/flutter/3.13.2/meta.yaml
    alias: flutterext
apiVersion: 1.0.0
````
