### ISSUE TITLE
add dart ms-vscode extension and sidecar to che

### ISSUE THREAD

**Issue by gattytto** [eclipse-che/che#17732]
in case anyone is up to testing / doing this, I'll be adding as much info as I find about officially maintained stuff (docker images/sources, spread binaries). 

there's plenty of "mixed" documentation about dart<>flutter but only dart is within google's dockerhub. So it is recommended to not "mix" dart stuff with flutter stuff in che because they will probably follow separate paths.

extension site:
https://marketplace.visualstudio.com/items?itemName=Dart-Code.dart-code
https://github.com/dart-lang/sdk
https://github.com/dart-lang/dart_docker

dockerimages:
https://github.com/dart-lang/dart_docker

test sidecar source: https://github.com/gattytto/che-sidecar-dart

test devfile:
````yaml
metadata:
  name: dartproj
projects:
  - name: dart-lang-samples
    source:
      location: 'https://github.com/dart-lang/samples'
      type: git
components:
  - id: eclipse/che-theia/next
    type: cheEditor
  - type: chePlugin
    reference: >-
      https://raw.githubusercontent.com/gattytto/cheplugins/master/dart/3.13.2/meta.yaml
    alias: dartext
apiVersion: 1.0.0
````

DOESN'T WORK: 
outline
