### ISSUE TITLE
Plugins used in devfiles lead to duplicate images

### ISSUE THREAD

**Issue by amisevsk** [eclipse-che/che#17737]
### Is your enhancement related to a problem? Please describe.
A couple of devfiles in the devfile registry include plugins that result in pulling both the java8 and java11 sidecar:
```yaml
- name: apache-camel-springboot-
  plugins:
    - redhat/vscode-xml/latest          (uses) quay.io/eclipse/che-sidecar-java:11-f76ca45
    - redhat/vscode-apache-camel/latest (uses) quay.io/eclipse/che-sidecar-java:11-f76ca45
    - redhat/java/latest                (uses) quay.io/eclipse/che-sidecar-java:8-0cfbacb
- name: che4z-
  plugins:
    - broadcommfd/cobol-language-support/latest (uses) quay.io/eclipse/che-sidecar-java:11-f76ca45
    - broadcommfd/debugger-for-mainframe/latest (uses) quay.io/eclipse/che-sidecar-java:8-0cfbacb
    - zowe/vscode-extension-for-zowe/latest     (uses) quay.io/eclipse/che-sidecar-node:10-0cb5d78
```
This results in the workspace pulling both sidecars and slows down workspace startup.

### Describe the solution you'd like
For `apache-camel-springboot`, we should verify that the sample project works with `redhat/java11/latest` and if so, switch to that plugin by default. For `che4z`, we should figure out if `broadcommfd/debugger-for-mainframe/latest` runs normally in the java11 sidecar.

### Describe alternatives you've considered
It's not a huge issue, so doing nothing is definitely an option
