### ISSUE TITLE
How to programmatically determine public URL of created Kubernetes component endpoint?

### ISSUE THREAD

**Issue by miwurster** [eclipse-che/che#17756]
Hey guys, 

we want to develop a very simple Che-Theia plugin to open the public endpoints of a devfile in a new browser window. For testing, we use the devfile below. However, atm we are stuck because it's not clear from where we can get/query the endpoint information for all registered Kubernetes components. 

Similarly to the "My Workspace" view, we have to query somehow the available user runtimes and their registered endpoints (see screenshot).
![image](https://user-images.githubusercontent.com/2610997/91724112-1b61ab80-eb9d-11ea-9fe4-4aebad6879b9.png)

We a apreciate any tipp or hint how to query such information.

Thanks in advance for your help,
Michael

---

## Relevant information

Example devfile:
```
apiVersion: 1.0.0
metadata:
  generateName: radon-workspace-
components:
  - alias: theia-editor
    type: cheEditor
    id: eclipse/che-theia/next
  - alias: radon-gmt
    type: kubernetes
    endpoints:
      - name: radon-gmt
        port: 8080
        attributes:
          protocol: http
          secure: "false"
          discoverable: "false"
          public: "true"
    mountSources: true
    reference: ...
```
