### ISSUE TITLE
tekton sidecar: missing octant daemon autostart and allowed hosts ENV var.

### ISSUE THREAD

**Issue by gattytto** [eclipse-che/che#17769]
octant requires an ENV VAR in the sidecar with a list of allowed hosts and the octant (web ui) daemon is not started automatically inside the tekton sidecar.

it is possible to set a wildcard to the octant allowed hosts.
https://github.com/vmware-tanzu/octant/issues/199#issuecomment-523563021

should the daemon be autostarted in the entrypoint.sh?.

**Comment by ericwill** [comment]
> should the daemon be autostarted in the entrypoint.sh?.

Can't it be auto-started as part of the container setup?

**Comment by gattytto** [comment]
@ericwill what I mean is, it's not "needed", only when the octant UI wants to be used.

**Comment by gattytto** [comment]
OCTANT_ACCEPTED_HOSTS env var should be set to 0.0.0.0

**Comment by gattytto** [comment]
I think it would be better set as "command" in tekton's plugin meta.yaml 
````yaml
commands:          # development commands available to plugin container
        - name:
          runOctant:
          command:       # list of commands + arguments, e.g.:
            - octant
            - -p or whatever --port arg
````
