### ISSUE TITLE
FR: add podTemplate + runtimeClassName to Workspace in devfile

### ISSUE THREAD

**Issue by gattytto** [eclipse-che/che#17761]
Hello

I first found the runtimeClass property from kubernetes when testing the Tekton extension, I wanted to run some taskruns using gVisor to see how it crashes, it crashed good (as was expected for the test), then I tried with kata-containers and it worked like a charm. 
````yaml
apiVersion: tekton.dev/v1alpha1
kind: TaskRun
metadata:
  name: pipeline-test-auth
  namespace: che
spec:
  params:
    - name: revision
      value: v1alpha1
  serviceAccountName: build-bot
  podTemplate:
    securityContext:
      runAsNonRoot: true
      runAsUser: 1724
    runtimeClassName: kata
````
I don't know about Docker / others but for cri-o it's pretty trivial (easy) to add runtimes to the crio.conf, then they become available to kubernetes as runtimeClasses that can be used by PODS.

Now for the Che specific stuff, I am now playing around with [flutter in che](https://github.com/eclipse/che/issues/17731) and since it's focused on mobile development flutter has the means to run android virtual devices using the sdkmanager from android sdk. 

I NEED NESTED VIRTUALIZATION AVAILABLE for the sidecar container (in docker it's done by adding "--device /dev/kvm")

I tried to think of an easy way to make my flutter sidecar run with a different runtimeClass, with no avail. then I thought it would break che's convention of workspace-in-a-pod if I wanted only the sidecar to be running in a different runtimeclass, and then I thought running the "special" sidecar in a separate pod would probably break communication with the extension or the che server.

so maybe there could be a property in the devfile to set a runtimeClass to the workspace pod? this would allow to use for example the kata-containers runtime which has an extra configuration layer using .toml files that makes it easy to give more properties to the containers run by the pod, like nested virtualization (but later on, additional network devices, custom virtual devices or even pass-through gpu's). 

WHY?

I think it would be nice to have the kotlin/flutter/android sidecars automate the process of spinning up a virtual android device and opening the VNC viewer in a webview to follow the native android app execution without the need of the user to find some other place to start the virtual device and keep it all within che's control-plane

HOW?
for the case of the android/flutter sidecar, both kind of rely on avd manager, avd manager then runs (and includes) the qemu binaries. NOTE: this may require providing host's modules folder access to the container using a volume binding.

proof of concept: https://hub.docker.com/r/thedrhax/android-avd
