### ISSUE TITLE
Jupyter based workspace is not working

### ISSUE THREAD

**Issue by KOSSOKO** [eclipse-che/che#17781]
### Che version
Latest

### Steps to reproduce
After running the command to instanciate an eclispse multi-user, single-host on kubernetes using an helm template (used to enable a storageCLassName for the keyclock PVC).

`chectl server:start --platform=k8s --installer=helm --multiuser --domain=che-dev.esa-maap.org --k8spodwaittimeout=400000 --postgres-pvc-storage-class-name="sata-iac-0b" --workspace-pvc-storage-class-name="sata-iac-0b" --templates=/home/cloud/chectl-templates/DEV/templates`

We have a fresh instance of che running. When we tried to create a workspace, it failed without any log  in the pod up and down quickly (5s):

```
workspacelcdkxz0gq8s7o61d.che-plugin-broker   0/1   Pending   0     0s
workspacelcdkxz0gq8s7o61d.che-plugin-broker   0/1   Pending   0     0s
workspacelcdkxz0gq8s7o61d.che-plugin-broker   0/1   ContainerCreating   0     0s
workspacelcdkxz0gq8s7o61d.che-plugin-broker   0/1   Terminating   0     5s
workspacelcdkxz0gq8s7o61d.che-plugin-broker   0/1   Terminating   0     5s
```

In the ingress controller we can see :

```
172.16.0.49 - - [03/Sep/2020:13:07:14 +0000] "GET /api/workspace/workspaceoma0eirhe30xk4vg HTTP/2.0" 200 1466 "https://che-dev.esa-maap.org/workspace-loader/admin/angular-bln86?uid=10718" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/84.0.4147.125 Safari/537.36" 1517 0.010 [che-che-host-8080] [] 172.16.0.16:8080 3512 0.009 200 746f46d32a2baa0f9d27b01be55143d0
W0903 13:08:06.845532       8 controller.go:919] Service "che/server2p05oun5-jwtproxy" does not have any active Endpoint.
W0903 13:08:06.845557       8 controller.go:919] Service "che/servertauyur1g-theia-ideaty" does not have any active Endpoint.
W0903 13:08:06.845569       8 controller.go:919] Service "che/servertauyur1g-theia-ideaty" does not have any active Endpoint.
W0903 13:08:06.845580       8 controller.go:919] Service "che/server2p05oun5-jwtproxy" does not have any active Endpoint.
W0903 13:08:06.845590       8 controller.go:919] Service "che/server2p05oun5-jwtproxy" does not have any active Endpoint.
W0903 13:08:06.845602       8 controller.go:919] Service "che/servertauyur1g-theia-ideaty" does not have any active Endpoint.
```

The k8s event seems good :
```
72s         Normal   SuccessfulMountVolume   Pod       Successfully mounted volumes for pod "workspaceoma0eirhe30xk4vg.che-plugin-broker_che(3c7f1ff8-edf4-11ea-801b-fa163e6c591b)"
72s         Normal   Scheduled               Pod       Successfully assigned che/workspaceoma0eirhe30xk4vg.che-plugin-broker to 192.168.0.208
71s         Normal   Pulling                 Pod       pulling image "quay.io/eclipse/che-plugin-metadata-broker:v3.3.0"
69s         Normal   Started                 Pod       Started container
69s         Normal   SuccessfulCreate        Pod       Created container
70s         Normal   Pulled                  Pod       Successfully pulled image "quay.io/eclipse/che-plugin-metadata-broker:v3.3.0"
68s         Normal   CREATE                  Ingress   Ingress che/ingressvotn16ea
68s         Normal   CREATE                  Ingress   Ingress che/ingressv4gp0r51
68s         Normal   CREATE                  Ingress   Ingress che/ingresstyrs0l3s
68s         Normal   CREATE                  Ingress   Ingress che/ingressr348sl0a
68s         Normal   CREATE                  Ingress   Ingress che/ingressljd7sr5b
68s         Normal   CREATE                  Ingress   Ingress che/ingressjrkfr8vh
68s         Normal   CREATE                  Ingress   Ingress che/ingressfdnal9k9
68s         Normal   CREATE                  Ingress   Ingress che/ingress9plc5czm
```

The share folder for the workspace contains en empty file for the log :
`/mnt/dev-iac/DEV/che/workspaceoma0eirhe30xk4vg/che-logs-che-plugin-broker`

After some minutes the che log contains:

```
2020-09-03 13:03:02,198[nio-8080-exec-9]  [INFO ] [o.e.c.a.w.s.WorkspaceRuntimes 480]   - Starting workspace 'admin/angular-bln86' with id 'workspaceoma0eirhe30xk4vg' by user 'admin'
2020-09-03 13:08:06,786[aceSharedPool-8]  [WARN ] [.i.k.KubernetesInternalRuntime 247]  - Failed to start Kubernetes runtime of workspace workspaceoma0eirhe30xk4vg. Cause: Waiting for ingress 'ingress92p434bq' reached timeout
2020-09-03 13:08:07,047[aceSharedPool-8]  [INFO ] [o.e.c.a.w.s.WorkspaceRuntimes 984]   - Workspace 'admin:angular-bln86' with id 'workspaceoma0eirhe30xk4vg' start failed
```

### Expected behavior
Che started and workspace created without issues

### Runtime
   - [ ] kubernetes (include output of `kubectl version`)
Client Version: version.Info{Major:"1", Minor:"12", GitVersion:"v1.12.0", GitCommit:"0ed33881dc4355495f623c6f22e7dd0b7632b7c0", GitTreeState:"clean", BuildDate:"2018-09-27T17:05:32Z", GoVersion:"go1.10.4", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"13+", GitVersion:"v1.13.10-r0-CCE2.0.26.B001", GitCommit:"dd2361511301aa78e37385126753ad08eb0f616e", GitTreeState:"clean", BuildDate:"2019-09-09T19:19:38Z", GoVersion:"go1.11.13", Compiler:"gc", Platform:"linux/amd64"}

### Screenshots
![OCS_CHE_WORKSPACE_FAILED_TO_START](https://user-images.githubusercontent.com/11942543/92136102-e909b580-ee0b-11ea-8501-7e1aeaf68dbe.jpg)

### Installation method
   - [x] chectl
chectl server:start --platform=k8s --installer=helm --multiuser --domain=che-dev.esa-maap.org --k8spodwaittimeout=400000 --postgres-pvc-storage-class-name="sata-iac-0b" --workspace-pvc-storage-class-name="sata-iac-0b" --templates=/home/cloud/chectl-templates/DEV/templates

### Environment
   - [ ] Cloud Orange

### Eclipse Che Logs
We are not able to find correct log

**Comment by skabashnyuk** [comment]
@KOSSOKO can you try to use che-operator instead of helm?

**Comment by tolusha** [comment]
Also
`kubectl get ingress -n che`

**Comment by KOSSOKO** [comment]
@tolusha for ingress
che-ingress        che-dev.esa-maap.org             80, 443   42h
devfile-registry   che-dev.esa-maap.org             80, 443   42h
keycloak-ingress   che-dev.esa-maap.org             80, 443   42h
plugin-registry    che-dev.esa-maap.org             80, 443   42h

**Comment by KOSSOKO** [comment]
@skabashnyuk we started the installation with che-operator before switching to helm. The result was the same

**Comment by jegithubpro** [comment]
We notice that only the che-plugin-broker is launched
kc get pod -w
NAME                               READY   STATUS    RESTARTS   AGE
che-5698cbd85d-67n42               1/1     Running   0          15h
devfile-registry-5578964f5-n4w5g   1/1     Running   0          42h
keycloak-cddc85df4-8flgh           1/1     Running   0          42h
plugin-registry-8669fc7ff9-kkjjs   1/1     Running   0          42h
postgres-748444bb55-rh9tz          1/1     Running   0          42h


workspacelcdkxz0gq8s7o61d.che-plugin-broker   0/1   Pending   0     0s
workspacelcdkxz0gq8s7o61d.che-plugin-broker   0/1   Pending   0     0s
workspacelcdkxz0gq8s7o61d.che-plugin-broker   0/1   ContainerCreating   0     0s
workspacelcdkxz0gq8s7o61d.che-plugin-broker   1/1   Running   0     4s
workspacelcdkxz0gq8s7o61d.che-plugin-broker   1/1   Terminating   0     4s
workspacelcdkxz0gq8s7o61d.che-plugin-broker   1/1   Terminating   0     4s

And impossible to see the logs

**Comment by jegithubpro** [comment]
We notice that the ingress and the associated service are created on the fly waiting for the pod creation with the labels
`  selector:
    che.original_name: che-workspace-pod
    che.workspace_id: workspacelcdkxz0gq8s7o61d
`
Nevertheless, only the pod "che-plugin-broker" poped.
`kc get pod -w
NAME                               READY   STATUS    RESTARTS   AGE
che-5698cbd85d-67n42               1/1     Running   0          18h
devfile-registry-5578964f5-n4w5g   1/1     Running   0          45h
keycloak-cddc85df4-8flgh           1/1     Running   0          45h
plugin-registry-8669fc7ff9-kkjjs   1/1     Running   0          45h
postgres-748444bb55-rh9tz          1/1     Running   0          45h
workspacelcdkxz0gq8s7o61d.che-plugin-broker   0/1   Pending   0     0s
workspacelcdkxz0gq8s7o61d.che-plugin-broker   0/1   Pending   0     0s
workspacelcdkxz0gq8s7o61d.che-plugin-broker   0/1   ContainerCreating   0     0s
workspacelcdkxz0gq8s7o61d.che-plugin-broker   0/1   Terminating   0     4s
workspacelcdkxz0gq8s7o61d.che-plugin-broker   0/1   Terminating   0     4s
`

**Comment by tolusha** [comment]
To get more:
1. Run workspace in debug mode:
![3](https://user-images.githubusercontent.com/1640675/92254333-664f2c00-eed9-11ea-814b-8f97629fc199.png)
2. Use `chectl workspace:logs` command before staring a workspace.

**Comment by KOSSOKO** [comment]
@tolusha we just run in debug mode, and run chectl:logs -w workspaceId, and no log appear

**Comment by KOSSOKO** [comment]
We succeeded starting che with a specific version of ingress 0.22 with chart 31...But workspace crashes when we use jupyter Ide
```

PS C:\Users\tkossoko> kubectl describe pod workspace8htm1eo7zn29arf4.python-5968bfdcb9-pgdjk  -n che
Pod 'workspace8htm1eo7zn29arf4.python-5968bfdcb9-pgdjk': error 'pods "workspace8htm1eo7zn29arf4.python-5968bfdcb9-pgdjk" not found', but found events.
Events:
  Type     Reason                 Age               From                  Message
  ----     ------                 ----              ----                  -------
  Normal   Scheduled              30s               default-scheduler     Successfully assigned che/workspace8htm1eo7zn29arf4.python-5968bfdcb9-pgdjk to 192.168.0.7
  Normal   Pulling                15s               kubelet, 192.168.0.7  pulling image "quay.io/eclipse/che-plugin-artifacts-broker:v3.3.0"
  Normal   Pulled                 14s               kubelet, 192.168.0.7  Successfully pulled image "quay.io/eclipse/che-plugin-artifacts-broker:v3.3.0"
  Normal   SuccessfulCreate       13s               kubelet, 192.168.0.7  Created container
  Normal   Started                13s               kubelet, 192.168.0.7  Started container
  Normal   Pulling                12s               kubelet, 192.168.0.7  pulling image "quay.io/eclipse/che-python-3.7:7.18.0"
  Normal   SuccessfulCreate       11s               kubelet, 192.168.0.7  Created container
  Normal   Pulled                 11s               kubelet, 192.168.0.7  Successfully pulled image "quay.io/eclipse/che-python-3.7:7.18.0"
  Normal   Started                10s               kubelet, 192.168.0.7  Started container
  Normal   Pulling                8s                kubelet, 192.168.0.7  pulling image "docker.io/ksmster/che-editor-jupyter:5.7.0"
  Normal   Pulled                 7s                kubelet, 192.168.0.7  Successfully pulled image "docker.io/ksmster/che-editor-jupyter:5.7.0"
  Normal   Pulling                6s (x2 over 10s)  kubelet, 192.168.0.7  pulling image "quay.io/eclipse/che-sidecar-python:3.7.3-8f39348"
  Normal   Started                6s                kubelet, 192.168.0.7  Started container
  Normal   SuccessfulMountVolume  6s (x2 over 16s)  kubelet, 192.168.0.7  Successfully mounted volumes for pod "workspace8htm1eo7zn29arf4.python-5968bfdcb9-pgdjk_che(36f9155a-f10b-11ea-a942
-fa163e6c591b)"
  Normal   SuccessfulCreate       6s                kubelet, 192.168.0.7  Created container
  Normal   Pulled                 5s (x2 over 9s)   kubelet, 192.168.0.7  Successfully pulled image "quay.io/eclipse/che-sidecar-python:3.7.3-8f39348"
  Normal   SuccessfulCreate       4s (x2 over 8s)   kubelet, 192.168.0.7  Created container
  Normal   Started                4s (x2 over 8s)   kubelet, 192.168.0.7  Started container
  Warning  BackOffStart           2s (x2 over 3s)   kubelet, 192.168.0.7  Back-off restarting failed container
```

**Comment by KOSSOKO** [comment]
I tried with the editor eclipse, same result
```


Successfully assigned che/workspace8htm1eo7zn29arf4.che-plugin-broker to 192.168.0.86

Successfully mounted volumes for pod "workspace8htm1eo7zn29arf4.che-plugin-broker_che(78c4b5e2-f117-11ea-a942-fa163e6c591b)"

pulling image "quay.io/eclipse/che-plugin-metadata-broker:v3.3.0"

Successfully pulled image "quay.io/eclipse/che-plugin-metadata-broker:v3.3.0"

Created container

Started container

Starting plugin metadata broker

List of plugins and editors to install
- ms-python/python/latest - Linting, Debugging (multi-threaded, remote), Intellisense, code formatting, refactoring, unit tests, snippets, and more.
- ws-skeleton/eclipseide/latest - Eclipse running on the Web with Broadway

All plugin metadata has been successfully processed

Successfully mounted volumes for pod "workspace8htm1eo7zn29arf4.python-668dbc69c6-f526j_che(821ebb16-f117-11ea-a942-fa163e6c591b)"

pulling image "quay.io/eclipse/che-plugin-artifacts-broker:v3.3.0"

Successfully pulled image "quay.io/eclipse/che-plugin-artifacts-broker:v3.3.0"

Started container

Successfully pulled image "docker.io/wsskeleton/eclipse-broadway"

Created container

Started container

Successfully mounted volumes for pod "workspace8htm1eo7zn29arf4.python-668dbc69c6-f526j_che(821ebb16-f117-11ea-a942-fa163e6c591b)"

Error: Failed to run the workspace: "The following containers have terminated:
vscode-pythonrye: reason = 'Completed', exit code = 0, message = 'null'"

```

**Comment by KOSSOKO** [comment]
The only working IDE is theia

**Comment by tolusha** [comment]
@azatsarynnyy @skabashnyuk 
Are you aware of any issues with jupyter ide ?

**Comment by skabashnyuk** [comment]
@tolusha anything could happen. I'm not aware that anything except theia is continuously tested and supported.

**Comment by KOSSOKO** [comment]
@skabashnyuk how could we do to have a logs ? It is extremely difficult to try to correct this issue without logs. Even with chectl logs, we have 0 log.

**Comment by skabashnyuk** [comment]
@KOSSOKO you have issues with Jupiter based workspace,  default workspace templates are working. Am I right?

**Comment by KOSSOKO** [comment]
@skabashnyuk yes, default workspace is working fine. It is when I change IDE and select Jupyter that I have the errors above.

**Comment by skabashnyuk** [comment]
Ok. Can you share the whole devfile?

**Comment by KOSSOKO** [comment]
@skabashnyuk this is the dev file

```
metadata:
  name: python-6v2pc
projects:
  - name: python-hello-world
    source:
      location: 'https://github.com/che-samples/python-hello-world.git'
      type: git
      branch: master
  - name: access-test
    source:
      location: 'https://repo.uat.maap-project.org/tkossoko/access-test.git'
      type: git
      branch: master
components:
  - id: ms-python/python/latest
    memoryLimit: 512Mi
    type: chePlugin
  - mountSources: true
    memoryLimit: 512Mi
    type: dockerimage
    image: 'quay.io/eclipse/che-python-3.7:7.18.0'
    alias: python
  - id: eclipse/che-theia/latest
    type: cheEditor
  - id: eamodio/vscode-gitlens/latest
    type: chePlugin
  - id: che-incubator/theia-dev/latest
    type: chePlugin
apiVersion: 1.0.0
commands:
  - name: run
    actions:
      - workdir: '${CHE_PROJECTS_ROOT}/python-hello-world'
        type: exec
        command: python hello-world.py
        component: python

```

**Comment by KOSSOKO** [comment]
With Jupyter the devfile is the following:

```
metadata:
  name: python-6v2pc
projects:
  - name: python-hello-world
    source:
      location: 'https://github.com/che-samples/python-hello-world.git'
      type: git
      branch: master
  - name: access-test
    source:
      location: 'https://repo.uat.maap-project.org/tkossoko/access-test.git'
      type: git
      branch: master
components:
  - id: ms-python/python/latest
    memoryLimit: 512Mi
    type: chePlugin
  - mountSources: true
    memoryLimit: 512Mi
    type: dockerimage
    image: 'quay.io/eclipse/che-python-3.7:7.18.0'
    alias: python
  - id: eamodio/vscode-gitlens/latest
    type: chePlugin
  - id: che-incubator/theia-dev/latest
    type: chePlugin
  - id: ws-skeleton/jupyter/latest
    type: cheEditor
apiVersion: 1.0.0
commands:
  - name: run
    actions:
      - workdir: '${CHE_PROJECTS_ROOT}/python-hello-world'
        type: exec
        command: python hello-world.py
        component: python

```

**Comment by skabashnyuk** [comment]
@KOSSOKO  just curious why do you need all of these plugins which are intended to work only with Theia and have a little sense to me with `jupyter ` editor.

**Comment by KOSSOKO** [comment]
@skabashnyuk yes, we need all these plugins. We are building a platfom for ESA-NASA scientists for the Europen space mission Biomass. One of our requirements is to be able to have same features with Theai and Jupyter. That's why the embedded Jupyter is a perfect solution. We have just to create a workspace then to switch IDE if we want Theai or Jupyter.

**Comment by skabashnyuk** [comment]
Jupyter is working
```
metadata:
  name: python-6v2pc
projects:
  - name: python-hello-world
    source:
      location: 'https://github.com/che-samples/python-hello-world.git'
      type: git
      branch: master
  - name: access-test
    source:
      location: 'https://repo.uat.maap-project.org/tkossoko/access-test.git'
      type: git
      branch: master
components:
  - id: ws-skeleton/jupyter/latest
    type: cheEditor
apiVersion: 1.0.0

```
@KOSSOKO  your example https://github.com/eclipse/che/issues/17781#issuecomment-688822891 is not working with error
```
reated container theia-dev9xg
Started container theia-dev9xg
Pulling image "docker.io/ksmster/che-editor-jupyter:5.7.0"
Successfully pulled image "docker.io/ksmster/che-editor-jupyter:5.7.0"
Created container jupyter-notebookk1j
Started container jupyter-notebookk1j
Pulling image "quay.io/eclipse/che-sidecar-python:3.7.3-8f39348"
Error: Failed to run the workspace: "The following containers have terminated:
vscode-pythonbr0: reason = 'Completed', exit code = 0, message = 'null'"
```

**Comment by KOSSOKO** [comment]
@skabashnyuk  thanks for your answer, I tested your config by copy pasting your conf, and got a weird result:
![image](https://user-images.githubusercontent.com/11942543/92583065-16ce7e80-f292-11ea-841d-020ef5e7657f.png)

Our che dev is here: https://che-dev.esa-maap.org with username admin and password BmaapDEV2020

**Comment by KOSSOKO** [comment]
@skabashnyuk  we succeeded having logs with watch 

```
at org.eclipse.che.workspace.infrastructure.kubernetes.namespace.KubernetesDeployments.handleStartingPodStatus(KubernetesDeployments.java:465)
        at org.eclipse.che.workspace.infrastructure.kubernetes.namespace.KubernetesDeployments.access$100(KubernetesDeployments.java:94)
        at org.eclipse.che.workspace.infrastructure.kubernetes.namespace.KubernetesDeployments$2.eventReceived(KubernetesDeployments.java:378)
        at org.eclipse.che.workspace.infrastructure.kubernetes.namespace.KubernetesDeployments$2.eventReceived(KubernetesDeployments.java:375)
        at io.fabric8.kubernetes.client.utils.WatcherToggle.eventReceived(WatcherToggle.java:49)
        at io.fabric8.kubernetes.client.dsl.internal.WatchConnectionManager$1.onMessage(WatchConnectionManager.java:237)
        at okhttp3.internal.ws.RealWebSocket.onReadMessage(RealWebSocket.java:323)
        at okhttp3.internal.ws.WebSocketReader.readMessageFrame(WebSocketReader.java:219)
        at okhttp3.internal.ws.WebSocketReader.processNextFrame(WebSocketReader.java:105)
        at okhttp3.internal.ws.RealWebSocket.loopReader(RealWebSocket.java:274)
        at okhttp3.internal.ws.RealWebSocket$2.onResponse(RealWebSocket.java:214)
        at okhttp3.RealCall$AsyncCall.execute(RealCall.java:203)
        at okhttp3.internal.NamedRunnable.run(NamedRunnable.java:32)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
        at java.base/java.lang.Thread.run(Unknown Source)
```

**Comment by KOSSOKO** [comment]
We did a new test by comparing config file for a workspace with theia and another with Jupyter


    Comparing the two .yaml files we find :                                                   Jupyter                           `Theia  *

                                         Container Jwt Proxy                           No                           Yes                                           Container "che-machine-exec"                           No                           Yes                                           Container "vscode-python"                           Yes                           Yes                                           Container "python"                           Yes                           Yes                                           Container "theia-ide"                           No                           Yes                                           Container "jupyter-notebook"                           Yes                           No                                           Init Container         "che-plugin-artifacts-broker-v3-3-0"                           Yes                           Yes                                           Init Container "remote-runtime-injector"                           No                           Yes |   | Jupyter | Theia | Container Jwt Proxy | No | Yes | Container "che-machine-exec" | No | Yes | Container "vscode-python" | Yes | Yes | Container "python" | Yes | Yes | Container "theia-ide" | No | Yes | Container "jupyter-notebook" | Yes | No | Init Container         "che-plugin-artifacts-broker-v3-3-0" | Yes | Yes | Init Container "remote-runtime-injector" | No | Yes`
```
  | Jupyter | Theia
Container Jwt Proxy | No | Yes
Container "che-machine-exec" | No | Yes
Container "vscode-python" | Yes | Yes
Container "python" | Yes | Yes
Container "theia-ide" | No | Yes
Container "jupyter-notebook" | Yes | No
Init Container         "che-plugin-artifacts-broker-v3-3-0" | Yes | Yes
Init Container "remote-runtime-injector" | No | Yes

```

**Comment by sleshchenko** [comment]
I've taken a quick look on the shared cluster and the issue with two workspace loaders is caused by `Jupyter editor is not compatible with Single Host Mode of Che`. As you see here - jupyter sends absolute redirections to `/tree` which leads to dashboard. Instead jupyter should send redirection to `./tree`
![Screenshot_20200910_102609](https://user-images.githubusercontent.com/5887312/92695294-eb5e9900-f350-11ea-850f-ed0196976efd.png)
But even then if you open /tree directly, Jupyter tries to load other resources via absolute reference.
![Screenshot_20200910_103425](https://user-images.githubusercontent.com/5887312/92695678-7b9cde00-f351-11ea-9b27-841332b9f762.png)

@KOSSOKO The solution for you could try a multi-host server strategy or contribute to Jupyter and makes it use relative references.

**Comment by KOSSOKO** [comment]
@sleshchenko Thanks a lot for this answer. We will try both solutions and put the result here.

**Comment by KOSSOKO** [comment]
@skabashnyuk, once again thanks for your answer. We switch to multi-host server and succeeded to have Jupyter.

We have a questions: Is it possible to switch editor without creating new workspace ?

1- lets say, I create workspace A to dev python using the default template. This launch Vscode by default. I dev my code. 

**Default dev file**
```
metadata:
  name: python-jw63v
projects:
  - name: python-hello-world
    source:
      location: 'https://github.com/che-samples/python-hello-world.git'
      type: git
      branch: master
components:
  - id: ms-python/python/latest
    memoryLimit: 512Mi
    type: chePlugin
  - mountSources: true
    memoryLimit: 512Mi
    type: dockerimage
    image: 'quay.io/eclipse/che-python-3.7:7.18.0'
    alias: python
apiVersion: 1.0.0
commands:
  - name: run
    actions:
      - workdir: '${CHE_PROJECTS_ROOT}/python-hello-world'
        type: exec
        command: python hello-world.py
        component: python
```

Then I decided to swith editor to use Jupyter to visualise the result.
**Dev file generated after switch**
```
metadata:
  name: python-jw63v
projects:
  - name: python-hello-world
    source:
      location: 'https://github.com/che-samples/python-hello-world.git'
      type: git
      branch: master
components:
  - id: ms-python/python/latest
    memoryLimit: 512Mi
    type: chePlugin
  - mountSources: true
    memoryLimit: 512Mi
    type: dockerimage
    image: 'quay.io/eclipse/che-python-3.7:7.18.0'
    alias: python
  - id: ws-skeleton/jupyter/latest
    type: cheEditor
apiVersion: 1.0.0
commands:
  - name: run
    actions:
      - workdir: '${CHE_PROJECTS_ROOT}/python-hello-world'
        type: exec
        command: python hello-world.py
        component: python
```


```
Successfully pulled image "quay.io/eclipse/che-python-3.7:7.18.0"
Created container
Started container
pulling image "quay.io/eclipse/che-sidecar-python:3.7.3-8f39348"
Successfully pulled image "quay.io/eclipse/che-sidecar-python:3.7.3-8f39348"
Created container
Started container
pulling image "docker.io/ksmster/che-editor-jupyter:5.7.0"
Successfully pulled image "docker.io/ksmster/che-editor-jupyter:5.7.0"
Created container
Started container
Successfully mounted volumes for pod "workspacegqnbn6op0f74dv2z.python-6d4df66fdb-n2p79_che(e9b613db-f81d-11ea-b4ab-fa163ee96da3)"
pulling image "quay.io/eclipse/che-sidecar-python:3.7.3-8f39348"
Error: Failed to run the workspace: "The following containers have terminated:
vscode-python046: reason = 'Completed', exit code = 0, message = 'null'"
```

The only way to have jupyter is to use the dev file provided by @skabashnyuk above.
```
metadata:
  name: python-6v2pc
projects:
  - name: python-hello-world
    source:
      location: 'https://github.com/che-samples/python-hello-world.git'
      type: git
      branch: master
  - name: access-test
    source:
      location: 'https://repo.uat.maap-project.org/tkossoko/access-test.git'
      type: git
      branch: master
components:
  - id: ws-skeleton/jupyter/latest
    type: cheEditor
apiVersion: 1.0.0
```

When we try to use Eclipse che Editor same result



```
Successfully mounted volumes for pod "workspacegqnbn6op0f74dv2z.che-plugin-broker_che(b9bfe556-f81e-11ea-b4ab-fa163ee96da3)"
pulling image "quay.io/eclipse/che-plugin-metadata-broker:v3.3.0"
Successfully pulled image "quay.io/eclipse/che-plugin-metadata-broker:v3.3.0"
Created container
Started container
Starting plugin metadata broker
All plugin metadata has been successfully processed
List of plugins and editors to install
- ms-python/python/latest - Linting, Debugging (multi-threaded, remote), Intellisense, code formatting, refactoring, unit tests, snippets, and more.
- mads-hartmann/bash-ide/latest - Visual Studio Code extension utilizing the bash language server, that is based on Tree Sitter and its grammar for Bash and supports explainshell integration.
- che-incubator/theia-dev/latest - Che Theia Dev Plugin
- eclipse/che-machine-exec-plugin/latest - Che Plug-in with che-machine-exec service to provide creation terminal or tasks for Eclipse Che workspace containers.
- ws-skeleton/eclipseide/latest - Eclipse running on the Web with Broadway

Successfully mounted volumes for pod "workspacegqnbn6op0f74dv2z.python-8676459bd9-2h7l2_che(e41ecd4d-f81e-11ea-b4ab-fa163ee96da3)"
pulling image "quay.io/eclipse/che-plugin-artifacts-broker:v3.3.0"
Successfully pulled image "quay.io/eclipse/che-plugin-artifacts-broker:v3.3.0"
Created container
Started container
Starting plugin artifacts broker
Processing plugin ms-python/python/latest
  Installing plugin extension 1/1
    Plugin already downloaded
Processing plugin mads-hartmann/bash-ide/latest
  Installing plugin extension 1/1
    Downloading plugin from https://open-vsx.org/api/mads-hartmann/bash-ide-vscode/1.10.2/file/mads-hartmann.bash-ide-vscode-1.10.2.vsix
All plugin artifacts have been successfully downloaded
Saving log of installed plugins
pulling image "quay.io/eclipse/che-jwtproxy:0.10.0"
Successfully pulled image "quay.io/eclipse/che-jwtproxy:0.10.0"
Created container
Started container
pulling image "quay.io/eclipse/che-python-3.7:7.18.0"
Successfully pulled image "quay.io/eclipse/che-python-3.7:7.18.0"
Created container
Started container
pulling image "quay.io/eclipse/che-sidecar-python:3.7.3-8f39348"
Successfully pulled image "quay.io/eclipse/che-sidecar-python:3.7.3-8f39348"
Created container
Started container
pulling image "quay.io/eclipse/che-theia-dev:next"
Successfully pulled image "quay.io/eclipse/che-theia-dev:next"
Created container
Started container
pulling image "quay.io/eclipse/che-machine-exec:7.18.0"
Successfully pulled image "quay.io/eclipse/che-machine-exec:7.18.0"
Created container
Started container
Error: Failed to run the workspace: "The following containers have terminated:
vscode-pythonu9m: reason = 'Completed', exit code = 0, message = 'null'"
```
