### ISSUE TITLE
Using iframe to open a webpage from a Docker container (in workspace) exposing public http url

### ISSUE THREAD

**Issue by svkr2k** [eclipse-che/che#17808]
Hi all,

I'm tried creating a workspace with a devfile shown below.
<details>
<summary>myDevfile.yaml</summary>
<p>

```
---
apiVersion: 1.0.0
metadata:
  name: test-devfile

components:
  - type: cheEditor
    reference: >-
      https://raw.githubusercontent.com/my-repo/my-plugin-registry/master/meta-my-theia-editor.yaml
  - alias: xyz
    type: dockerimage
    image: localhost:5000/plugin-09-sep:latest
    endpoints:
      - name: view-server
        port: 2000
        attributes:
           protocol: http
           secure: 'false'
      - name: websocket-server
        port: 30001
        attributes:
           protocol: ws
           secure: 'false'
    memoryLimit: 1536M
```

</p>
</details>

In the custom theia editor's extension, I have a widget that has an iFrame to show the web page exposed by the docker container in port 2000.
The render code for the widget is given below.

<details>
<summary>Widget code in eclipse theia extension</summary>
<p>

```
    public render(): React.ReactNode {
        return <React.Fragment>
            <div className='web-view-content'>
                <div className="web-view-content-inner">
                    <iframe src="http://serverzq4xmzlr-xyz-server-2000.100.92.1.23.nip.io/html/plugin/bootstrap.html?key=1&port=30001"></iframe>
                </div>
            </div>
        </React.Fragment>
    }
```

</p>
</details>

when the widget is shown, the html page is successfully downloaded, but the scripts within the html page are not loaded.
i.e., within the downloaded html page, there is a script `<script src="{{someScript}}"></script>`
this doesnt get downloaded.

Please help.
