### ISSUE TITLE
Wrong JWT proxy configuration for secure endpoints in dockeimage type components

### ISSUE THREAD

**Issue by mshaposhnik** [eclipse-che/che#17852]
### Describe the bug

The following component was created by user:

```
components:
  - type: dockerimage
    image: xxx
    alias: foo
    env:
       .....
    endpoints:
      - name: "jupyterc"
        port: 8888
        attributes:
          type: ide
          protocol: http
          secure: 'true'
          cookiesAuthEnabled: 'true'
          discoverable: 'false'
```
providing  **secure: 'true'**. But passthrough configuration is actually applied to jwtproxy:

```
erifier_proxies:
  - listen_addr: ":4400"
    verifier:
      audience: "workspace19f5udw4h6sd9k3w"
      auth_cookies_enabled: false
      claims_verifiers:
      - options:
          iss: "wsmaster"
        type: "static"
      cookie_path: "/"
      excludes:
      - "/"
```

The nature of the bug probably due to different ways of provisioning `plugin` and `dockerimage` type components (K8S env  vs workspace env).

### Che version

 - [x] latest
 - [ ] nightly
 - [ ] other: please specify

### Steps to reproduce
Create & run devfile with dockeimage component with secure endpoint. Open the endpoint URL in anonymous window. 

### Expected behavior
Forbidden error should be returned. But we see resource accessible.

### Runtime
   - [x] kubernetes (include output of `kubectl version`)
   - [x] Openshift (include output of `oc version`)
   - [ ] minikube (include output of `minikube version` and `kubectl version`)
   - [ ] minishift (include output of `minishift version` and `oc version`)
   - [ ] docker-desktop + K8S (include output of `docker version` and `kubectl version`)
   - [ ] other: (please specify)

### Installation method
   - [ ] chectl
     * provide a full command that was used to deploy Eclipse Che (including the output)
     * provide an output of `chectl version` command
   - [ ] OperatorHub
   - [ ] I don't know

### Environment
   - [ ] my computer
       - [ ] Windows
       - [ ] Linux
       - [ ] macOS
   - [ ] Cloud
       - [ ] Amazon
       - [ ] Azure
       - [ ] GCE
       - [ ] other (please specify)
   - [ ] other: please specify
