### ISSUE TITLE
Full support for Devfile 2.x spec

### ISSUE THREAD

**Issue by sleshchenko** [eclipse-che/che#17883]
### Is your enhancement related to a problem? Please describe.
Currently, devworkspace controller supports only limited of devfile 2.x format. This is epic to track which parts needs to be implemented.
```yaml
schemaVersion: 2.0.0
metadata:
  name: nodejs-stack
projects:
  - name: project    
    git:
      remotes:                                                           # The only one remote is supported on Che Theia side
        origin: "https://github.com/che-samples/web-nodejs-sample.git"
components:
  - name: editor
    plugin:
      id: eclipse/che-theia/7.1.0
  - name: terminal
    plugin:
      id: eclipse/che-machine-exec-plugin/7.1.0
  - name: typescript-plugin
    plugin:
      id: che-incubator/typescript/1.30.2                                 # patching of plugins configuration are not supported yet
      components:
        - name: "??"
          container:
            memoryLimit: 512Mi
  - name: nodejs
    container:
      image: quay.io/eclipse/che-nodejs10-ubi:nightly
      memoryLimit: 512Mi
      endpoints:
        - name: nodejs
          protocol: http
          targetPort: 3000
      mountSources: true
  - name: cleanup-job
    kubernetes:
      inlined: |
        apiVersion: batch/v1
        kind: Job
        metadata:
          name: pi
        spec:
          template:
            spec:
              containers:
              - name: job
                image: someimage
                command: ["some",  "command", "with", "parameters"]
              restartPolicy: Never
          backoffLimit: 4
  - name: postgres
    kubernetes:                                               # kubernete component is not supported yet
      inlined: |
        kind: Deployment
        metadata:
          name: pi
        spec:
          template:
            spec:
              containers:
              - name: job
                image: someimage
                command: ["some",  "command", "with", "parameters"]
              restartPolicy: Never
          backoffLimit: 4
volumes:                                                    ## volumes are not implemented on that level
  - name: ...
commands:
  - id: download dependencies
    exec:
      component: nodejs
      commandLine: npm install
      workingDir: ${PROJECTS_ROOT}/project/app
      group:
        kind: build                                              # groups are not supported yet
commands:
  - id: cleanup-job
    apply:
      component: cleanup-job 
events:
  postStop:
    - cleanup-job
  preStop: ...
  preStart: ...
  postStart: ...
```
This issue is not well-described yet. More details will be provided soon.

| Devfile 2.0 Feature | Supported | Issue |
| --- | --- | --- |
| ~~[Plugin mechanism](https://github.com/che-incubator/devworkspace-api/issues/31)~~ | removed from the spec | https://github.com/devfile/api/pull/333 |
| [Parent devfiles](https://github.com/che-incubator/devworkspace-api/issues/25) | ✅ | https://github.com/devfile/devworkspace-operator/pull/346 |
| [Allow volumes to be shared across components](https://github.com/che-incubator/devworkspace-api/issues/19) | ✅ |  https://github.com/devfile/devworkspace-operator/pull/237 |
| [kubernetes component](https://github.com/eclipse/che/issues/17894) | ✅ |  | 
| [projects](https://github.com/devfile/api/issues/104) |  ✅ |  |
| [starterProjects](https://github.com/devfile/api/issues/42) |  |  |
| [Components sourceMapping](https://github.com/che-incubator/devworkspace-api/issues/17) | ✅ |  |
| [Specify size of volume for component](https://github.com/che-incubator/devworkspace-api/issues/14) | ✅ | https://github.com/devfile/devworkspace-operator/pull/827 |
| [Environment variables for a specific command](https://github.com/che-incubator/devworkspace-api/issues/21) | ✅ |  |
| [Commands group (application lifecycle)](https://github.com/che-incubator/devworkspace-api/issues/27) |  |  |
| [Out of main pod containers](https://github.com/devfile/kubernetes-api/issues/48) |  |  |
| [Stacks/Devfile matching rules](https://github.com/devfile/kubernetes-api/issues/40) | not in the spec yet |  |
| [Devfile metadata: add a link to an external website](https://github.com/devfile/kubernetes-api/issues/38) | ✅ |  |
| [Add lifecycle bindings to bind commands to specific events](https://github.com/che-incubator/devworkspace-api/issues/32) | pre-start only | https://github.com/devfile/devworkspace-operator/issues/629 |
| [Containers endpoints (routes/ingresses)](https://github.com/che-incubator/devworkspace-api/issues/33) | ✅ |  |
| [New type of command to `apply` a component](https://github.com/devfile/kubernetes-api/issues/56) |  |  |
| [Run exec commands as specified user](https://github.com/devfile/kubernetes-api/issues/34) |  |  |
| [hotReloadCapable](https://github.com/devfile/api/issues/64) |  |  |
| [image component](https://github.com/devfile/api/issues/51) | | https://github.com/eclipse/che/issues/21187 |
| [outer loop components of type image and kubernetes](https://docs.google.com/document/d/1SL3ZJyAy8lp973EzQpY36VjTJHoyGXl2zUXokPiXwK8/edit) | | https://github.com/eclipse/che/issues/21186 |
