### ISSUE TITLE
Mount a file from an external source not in /projects (like settings.xml)

### ISSUE THREAD

**Issue by DarthBlair** [eclipse-che/che#17915]
Hi, i have an other question: I am trying to provide a central settings.xml for maven. How can a Che user mount that file with no access to kubernetes.

- creating a Secret and appying annotations requires kubernetes
- maybe moutn the file with a configmap volume -> but how? with the devfile
- mounting it from git ...also how?

Do you have any ideas?
thanks

ref:
https://www.eclipse.org/che/docs/che-7/end-user-guide/using-maven-artifact-repositories/

**Comment by sleshchenko** [comment]
@mshaposhnik any ideas?

**Comment by metlos** [comment]
Do you, as the provider of the central settings.xml, have access to Kubernetes? If so, you can try the procedure https://www.eclipse.org/che/docs/che-7/end-user-guide/using-maven-artifact-repositories/#proc_defining-maven-settings-xml-file-across-workspaces_using-maven-artifact-repositories.

If even you don't have access to Kubernetes, things start to get more complicated, because you will have to instruct the users to  manage the downloading of the settings.xml on their own.

You can for example instruct your users to download it from within their workspaces and copy it into `~/.m2` of the maven component in their workspaces. You can do that in several ways - for example instruct the users to add a project to the workspace which contains your settings.xml and then copy it to the appropriate location (in the appropriate component), or make sure they have a component in their workspaces that has curl available and start from there, etc. But it is never going to be that easy as providing the settings.xml from within the cluster.

Or is there a better option that I am not seeing @mshaposhnik ?

**Comment by mshaposhnik** [comment]
Nope..  for now the only recommended way is mount from secret.

**Comment by DarthBlair** [comment]
@metlos @mshaposhnik 
i read the article, but is there a way to combine the secrete with a kubenetes deployment in the devfile during the start of the workspace?

**Comment by mshaposhnik** [comment]
secret can be mount into any component container, no matter is this a kubernetes type component  or plugin etc

**Comment by DarthBlair** [comment]
Alright, could you provide a example devfile, because i am not talking about kubernetes. Somthing like:
```yaml
apiVersion: 1.0.0
projects:
  - name: console-java-simple
    source:
      type: zip
      location: >-
        http://10.8.6.252:8080/resources/java-maven-console-java-simple-java1.11.zip
metadata:
  generateName: java-maven-
components:
  - type: chePlugin
    id: redhat/java11/latest
  - type: dockerimage
    alias: maven
    image: 'quay.io/eclipse/che-java11-maven:nightly'
    mountSources: true
    volumes:
      - name: m2
        containerPath: /home/user/.m2
  - type: kubernetes
    alias: maven-secret
    referenceContent: |
        apiVersion: v1
        kind: Secret
        metadata:
           name: maven-settings-secret
         labels:
           app.kubernetes.io/part-of: che.eclipse.org
           app.kubernetes.io/component: workspace-secret
         annotations:
           che.eclipse.org/automount-workspace-secret: true
           che.eclipse.org/mount-path: /home/user/.m2
           che.eclipse.org/mount-as: file
       type: Opaque
       data:
         settings.xml: PHNldHRpbmdzIHhtbG5zPSJodHRwOi8vbWF2ZW4uYXBhY2hlLm9yZy9TRVRUSU5HUy8xLjAuMCIKICAgICAgICAgIHhtbG5zOnhzaT0iaHR0cDovL3d3dy53My5vcmcvMjAwMS9YTUxTY2hlbWEtaW5zdGFuY2UiCiAgICAgICAgICB4c2k6c2NoZW1hTG9jYXRpb249Imh0dHA6Ly9tYXZlbi5hcGFjaGUub3JnL1NFVFRJTkdTLzEuMC4wCiAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIGh0dHBzOi8vbWF2ZW4uYXBhY2hlLm9yZy94c2Qvc2V0dGluZ3MtMS4wLjAueHNkIj4KICA8c2VydmVycz4KICAgIDxzZXJ2ZXI+CiAgICAgIDxpZD5yZXBvc2l0b3J5LWlkPC9pZD4KICAgICAgPHVzZXJuYW1lPnVzZXJuYW1lPC91c2VybmFtZT4KICAgICAgPHBhc3N3b3JkPnBhc3N3b3JkMTIzPC9wYXNzd29yZD4KICAgIDwvc2VydmVyPgogIDwvc2VydmVycz4KPC9zZXR0aW5ncz4K
```
But working....
