### ISSUE TITLE
Add ms-vscode plantUML extension to che

### ISSUE THREAD

**Issue by gattytto** [eclipse-che/che#17916]
I just forgot to create an issue, sidecar repo is already created (thank you @ericwill), I will close this issue when extension is added. 

extension repo: https://github.com/qjebbs/vscode-plantuml
test sidecar source: https://github.com/gattytto/che-sidecar-plantuml

test devfile:
````yaml
apiVersion: 1.0.0
metadata:
  generateName: che-plantuml-

components:
  - type: chePlugin
    reference: >-
      https://raw.githubusercontent.com/gattytto/cheplugins/master/plantuml/2.13.12/meta.yaml
````
unpublished quay image until pr is merged: ```` https://pr-check-783-alpine-che-plugin-registry.surge.sh/v3/plugins/qjebbs/vscode-plantuml/latest/meta.yaml ````

meta yaml 
````yaml
apiVersion: v2
publisher: qjebbs
name: vscode-plantuml
version: latest
type: VS Code extension
displayName: PlantUML
title: PlantUML
description: Rich PlantUML support for Visual Studio Code.
icon: /v3/images/jebbs-plantuml-icon.png
category: Programming Languages
repository: https://github.com/qjebbs/vscode-plantuml.git
firstPublicationDate: '2020-08-06'
deprecate:
  automigrate: true
  migrateTo: jebbs/plantuml/latest
spec:
  containers:
    - image: quay.io/eclipse/che-plugin-sidecar:plantuml-4180443
      name: vscode-plantuml
      memoryLimit: 512Mi
  extensions:
    - https://open-vsx.org/api/jebbs/plantuml/2.13.12/file/jebbs.plantuml-2.13.12.vsix
latestUpdateDate: "2020-12-23"
````

![image](https://user-images.githubusercontent.com/407397/93915098-e4833f00-fcdd-11ea-868e-025bd5e3d7f4.png)
![image](https://user-images.githubusercontent.com/407397/93915237-1a282800-fcde-11ea-88da-a3d2b38ed24e.png)
