### ISSUE TITLE
Che-theia: Webview resources within non-theia sidecars return 404

### ISSUE THREAD

**Issue by gattytto** [eclipse-che/che#17931]
if you check the screenshot, extensions that need to serve files directly and use a sidecar return 404 errors for resources that are contained outside of the theia sidecar filesystem. 

I guess this could be solved by adding workaround volume for theia in the devfile, but this is something that will be always required by certain extensions (like [plantUML](https://github.com/eclipse/che/issues/17916)), so I think it would be better to add an extra property in plugin yaml volumes, like:

````yaml
apiVersion: v2
publisher: gattytto
name: plantuml
version: 2.13.13
type: VS Code extension
displayName: PlantUML
title: PlantUML support
description: This extension adds support for the PlantUML Server
icon: https://github.com/gattytto/vscode-plantuml/raw/master/images/icon.png
repository: https://github.com/gattytto/vscode-plantuml
category: Language
firstPublicationDate: '2020-09-22'
spec:
  containers:
    - image: "quay.io/eclipse/che-sidecar-plantuml:2.13.13-ee2987c"
      name: vscode-plantuml
      memoryLimit: '512Mi'
      volumes:
        - mountPath: "/tmp/vscode-unpacked"
          name: "previewassets"
          **alsoMountInTheia: true**
  extensions:
    - https://github.com/gattytto/vscode-plantuml/releases/download/2.13.13/plantuml-2.13.13.vsix
````
![image](https://user-images.githubusercontent.com/407397/93919507-2fa05080-fce4-11ea-9a31-78316b03aa6b.png)
