### ISSUE TITLE
Implement tests for single host in Openshift CI

### ISSUE THREAD

**Issue by flacatus** [eclipse-che/che#17944]
### Is your task related to a problem? Please describe.

Actually in the operator side or chectl we don't have any tests implemented which tests single host mode.
### Describe the solution you'd like

After merging https://github.com/eclipse/che-operator/pull/378 we should create tests in operator side to install single host mode in Openshift 4.X.

**Comment by tolusha** [comment]
For this issue I would like to have 3 tests with the following configuration:

1. OpenShift
```
spec:
  server:
    serverExposureStrategy: 'single-host'
```
2. Minikube
```
spec:
  server:
    serverExposureStrategy: 'single-host'
  k8s:
    singleHostExposureType: 'gateway'
```
3. Minikube
```
spec:
  server:
    serverExposureStrategy: 'single-host'
```
