### ISSUE TITLE
Endpoint path not honored in gateway singlehost

### ISSUE THREAD

**Issue by metlos** [eclipse-che/che#18028]
### Describe the bug
When Che is running in the single host mode using a gateway, the path of the endpoints is not honored and the endpoints are hardcoded to have the `/` as their path.

### Che version
 - [x] latest
 - [ ] nightly
 - [ ] other: please specify

### Steps to reproduce

1. Define a workspace using the below devfile
1. Start the workspace
1. Run the "Start Development mode (Hot reload + debug)" command
1. Once it is running, click on the endpoint link

### Expected behavior

The endpoint link should point to `<che>/<server>/hello` but points to `<che>/<server>` instead.

### Additional context

The test devfile:

```yaml
metadata:
  name: test-for-17852
projects:
  - name: quarkus-quickstarts
    source:
      location: 'https://github.com/quarkusio/quarkus-quickstarts.git'
      type: git
      sparseCheckoutDir: getting-started
components:
  - id: redhat/quarkus-java11/latest
    type: chePlugin
  - mountSources: true
    endpoints:
      - name: hello-greeting-endpoint
        port: 8080
        attributes:
          cookiesAuthEnabled: 'true'
          path: /hello
          secure: 'true'
    memoryLimit: 4927M
    type: dockerimage
    volumes:
      - name: m2
        containerPath: /home/user/.m2
    alias: centos-quarkus-maven
    image: 'quay.io/eclipse/che-quarkus:nightly'
    env:
      - value: >-
          -XX:MaxRAMPercentage=50.0 -XX:+UseParallelGC -XX:MinHeapFreeRatio=10
          -XX:MaxHeapFreeRatio=20 -XX:GCTimeRatio=4
          -XX:AdaptiveSizePolicyWeight=90 -Dsun.zip.disableMemoryMapping=true
          -Xms20m -Djava.security.egd=file:/dev/./urandom -Duser.home=/home/user
        name: JAVA_OPTS
      - value: $(JAVA_OPTS)
        name: MAVEN_OPTS
apiVersion: 1.0.0
commands:
  - name: Start Development mode (Hot reload + debug)
    actions:
      - workdir: '${CHE_PROJECTS_ROOT}/quarkus-quickstarts/getting-started'
        type: exec
        command: './mvnw compile quarkus:dev'
        component: centos-quarkus-maven
```
