### ISSUE TITLE
Allow users to define workspace deployment labels

### ISSUE THREAD

**Issue by skabashnyuk** [eclipse-che/che#18027]
### Is your task related to a problem? Please describe.

Eclipse Che workspace can be run in Kubernetes with additional cloud software like istio.
It might be useful to allow users to define custom workspace deployment labels.
These labels can be used by that `cloud software` to manipulate with trafik of applications that are running inside of the workspace.

### Describe the solution you'd like
For example in this way
```yaml
apiVersion: 1.0.0
metadata:
  name: petclinic-dev-environment
projects:
  - name: petclinic
    source:
      type: git
      location: 'https://github.com/che-samples/web-java-spring-petclinic.git'
attributes:
   workspaceDeploymentLabels: ike.target=preference-v1,ike.session=test
```
### Describe alternatives you've considered
ConfigMap with labels in workspace's namespace

```yaml

apiVersion: v1
kind: ConfigMap
metadata:
  name: workspace-labels
  labels:
    app.kubernetes.io/part-of: che.eclipse.org
    app.kubernetes.io/component: workspace-deployment-labels
  annotations:
    che.eclipse.org/automount-workspace-deployment-labels: 'true'
data:
  ike.target: preference-v1
  ike.session: test
```

### Additional context
n/a

**Comment by sleshchenko** [comment]
Seems to be something that also needs to be addressed in devfile 2.x.
cc @davidfestal @l0rd

**Comment by l0rd** [comment]
I am not a big fan of the first option: devfiles live in a git repository and it does make any sense to store ike target and session in a git repo. These are more runtime properties that would be in a `DevWorkspace` object but not part of the `DevWorkspaceTemplate`.

The second option though would require the startup of a "labelled" workspace as 2 steps operation:
1. Create the CM that specifies the deployment labels
2. Call the che server api to start a workspace

In a `DevWorkspace` world that could be squashed in a unique operation.

**Comment by skabashnyuk** [comment]
WDYT about adding  `che.eclipse.org/workspace-name: my-ws` instead of `che.eclipse.org/automount-workspace-deployment-labels: 'true'`
```yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: workspace-labels
  labels:
    app.kubernetes.io/part-of: che.eclipse.org
    app.kubernetes.io/component: workspace-deployment-labels
  annotations:
    che.eclipse.org/automount-workspace-deployment-labels: 'true'
data:
  ike.target: preference-v1
  ike.session: test
```

**Comment by l0rd** [comment]
@skabashnyuk thinking again about that using a configmap to set some deployment labels looks weird. 

What about using a factory link parameter:

`https://<che-host>/f?url=<devfile-url>&workspaceDeploymentLabels=ike.target%3A%20preference-v1%2Cike.session%3A%20test&workspaceDeploymentAnnotations=ike.target%3A%20preference-v1%2Cike.session%3A%20test`

**Comment by skabashnyuk** [comment]
@l0rd it is more about workspace definition (devfile). We need to put workspaceDeploymentAnnotations somewhere in the workspace.
```yaml
apiVersion: 1.0.0
metadata:
  name: petclinic-dev-environment
projects:
  - name: petclinic
    source:
      type: git
      location: 'https://github.com/che-samples/web-java-spring-petclinic.git'
attributes:
   workspaceDeploymentAnnotations: ike.target=preference-v1,ike.session=test
```
