### ISSUE TITLE
Secure endpoints with requireSubdomain don't work in singlehost mode

### ISSUE THREAD

**Issue by metlos** [eclipse-che/che#18065]
### Describe the bug
When declaring endpoints, one can require them to be on subdomains. This is the **default** behavior for endpoints in the devfile components and can be configured in plugins using the `requireSubdomain: true` attribute in the meta.yaml of plugins.

Such endpoints do not function properly when they are also `secure` and che server is in the singlehost mode.

The are at least 3 things that are problematic:

* HTTP only does not make sense together with "secure"
* Apart from the fact that http only subdomains don't make sense with secure, it also makes any XHR calls fail because code loaded using HTTPS cannot make XHR requests for http only endpoints. This breaks our plugins, because they are called dynamically from within Theia, which is loaded through a secure endpoint itself.
* JWT proxy creates incorrect redirects, because it currently doesn't take into account the possibility of subdomain endpoints in singlehost mode at all.

### Che version
 - nightly

### Steps to reproduce
1. Create a devfile from the sample below
1. Start the "Start Development Mode" command
1. Once the command has started the user app, click on the preview URL under the command
1. Observe the auth error in the new browser tab.

### Expected behavior
When `secure`, the endpoint should be acessible over https and the requests should be routed through JWT proxy correctly.

### Runtime
   - [x] kubernetes (include output of `kubectl version`)
   - [x] Openshift (include output of `oc version`)
   - [x] minikube (include output of `minikube version` and `kubectl version`)
   - [x] minishift (include output of `minishift version` and `oc version`)

### Screenshots
N/A

### Additional context
Devfile to reproduce this:

```yaml
metadata:
  name: secure-endpoints-reproducer
projects:
  - name: quarkus-quickstarts
    source:
      location: 'https://github.com/quarkusio/quarkus-quickstarts.git'
      type: git
      sparseCheckoutDir: getting-started
components:
  - id: redhat/quarkus-java11/latest
    type: chePlugin
  - mountSources: true
    endpoints:
      - name: hello-greeting-endpoint
        port: 8080
        attributes:
          secure: 'true'
          cookiesAuthEnabled: 'true'
    memoryLimit: 4927M
    type: dockerimage
    volumes:
      - name: m2
        containerPath: /home/user/.m2
    alias: centos-quarkus-maven
    image: 'quay.io/eclipse/che-quarkus:nightly'
    env:
      - value: >-
          -XX:MaxRAMPercentage=50.0 -XX:+UseParallelGC -XX:MinHeapFreeRatio=10
          -XX:MaxHeapFreeRatio=20 -XX:GCTimeRatio=4
          -XX:AdaptiveSizePolicyWeight=90 -Dsun.zip.disableMemoryMapping=true
          -Xms20m -Djava.security.egd=file:/dev/./urandom -Duser.home=/home/user
        name: JAVA_OPTS
      - value: $(JAVA_OPTS)
        name: MAVEN_OPTS
  - mountSources: true
    endpoints:
      - name: hello-greeting-endpoint
        port: 8080
        attributes:
          path: /hello/greeting/che-user
    command:
      - tail
    args:
      - '-f'
      - /dev/null
    memoryLimit: 32M
    type: dockerimage
    alias: ubi-minimal
    image: registry.access.redhat.com/ubi8/ubi-minimal
apiVersion: 1.0.0
commands:
  - name: Package
    actions:
      - workdir: '${CHE_PROJECTS_ROOT}/quarkus-quickstarts/getting-started'
        type: exec
        command: ./mvnw package
        component: centos-quarkus-maven
  - name: Start Development mode (Hot reload + debug)
    actions:
      - workdir: '${CHE_PROJECTS_ROOT}/quarkus-quickstarts/getting-started'
        type: exec
        command: './mvnw compile quarkus:dev'
        component: centos-quarkus-maven
  - name: Package Native
    actions:
      - workdir: '${CHE_PROJECTS_ROOT}/quarkus-quickstarts/getting-started'
        type: exec
        command: ./mvnw package -Dnative -Dmaven.test.skip
        component: centos-quarkus-maven
  - name: Start Native
    actions:
      - workdir: '${CHE_PROJECTS_ROOT}/quarkus-quickstarts/getting-started/target'
        type: exec
        command: ./getting-started-1.0-SNAPSHOT-runner
        component: ubi-minimal
  - name: Attach remote debugger
    actions:
      - referenceContent: |
          {
            "version": "0.2.0",
            "configurations": [
              {
                "type": "java",
                "request": "attach",
                "name": "Attach to Remote Quarkus App",
                "hostName": "localhost",
                "port": 5005
              }
            ]
          }
        type: vscode-launch
```
