### ISSUE TITLE
Che should be able to deal with large git projects. Allowing `git clone --depth 1` in the devfile.

### ISSUE THREAD

**Issue by sunix** [eclipse-che/che#18114]
### Is your enhancement related to a problem? Please describe.
Che should be able deal with large project:
adding option
```
git clone --depth 1 https://github.com/llk/scratch-gui.git
```
should be possible from the devfile.

My workaround to clone these kind of projects was not ideal:
- fork projects
- clone locally and remove all branches except develop
    ```
   git branch -r | grep 'origin' | grep -v 'develop$' | grep -v HEAD | cut -d/ -f2- | while read line; do git push origin :heads/$line; done;
   ```
- add the forked repo to the devfile.

### Describe the solution you'd like
In the devfile:
```
 - source:
      type: git
      location: 'https://github.com/redhat-developer-demos/quarkus-reactjs-postit-app'
      depth: 1
    name: postit-app
```
or more generic
```
 - source:
      type: git
      location: 'https://github.com/redhat-developer-demos/quarkus-reactjs-postit-app'
      cloneArgs: '--depth 1'
    name: postit-app
```
