### ISSUE TITLE
add remote server protocol extensions to che (vscode-rsp-ui, vscode.server-connector, vscode.community-server-connector)

### ISSUE THREAD

**Issue by robstryker** [eclipse-che/che#18123]
Having problems with a custom che devfile to test if my 3 inter-related vsix files can work in che. The url for the devfile is https://che.openshift.io/f/?url=https://raw.githubusercontent.com/robstryker/testRSPinCheAndTheia/master/devfile.yaml

The dev env comes with 3 vsix packages, one called rsp-ui, one called server-connector, and one called community-server-connector.  The rsp-ui package is supposed to be loaded / run first. The other two can discover rsp-ui and add contributions to its model via what amounts to a call to vscode.extensions.getExtension<RSPModel>(rsp-ui-id) and then acting on the returned value.

This seems to work fine in vscode but when I tried it in the che devfile environment, the rsp-ui extension does not seem to function properly in a few ways. First, the view 'Servers' won't load at all. When you try to show it, nothing happens.  Second, an action in the rsp-ui which depends on the other two vsix files being available seems to indicate that the other two are not being registered into the ui's model. The error is an expected error that we can replicate in vscode if we only install the ui vsix and don't install either of the other two.

Any ideas what can be going wrong here? Also is there a better place to have the discussion or is this the best spot?

The github repos for the 3 vsix files are:
1) https://github.com/redhat-developer/vscode-rsp-ui/
2) https://github.com/redhat-developer/vscode-server-connector/
3) https://github.com/redhat-developer/rsp-server-community/

The marketplace urls for these are:
1) https://marketplace.visualstudio.com/items?itemName=redhat.vscode-rsp-ui
2) https://marketplace.visualstudio.com/items?itemName=redhat.vscode-server-connector
3) https://marketplace.visualstudio.com/items?itemName=redhat.vscode-community-server-connector

It's worth noting that all three of these depend on a node.js lib called vscode-server-connector-api found at https://github.com/redhat-developer/vscode-server-connector-api   which basically wraps around the vscode.extensions.getExtension<RSPModel> calls and provides some useful interface for us to use those calls more cleanly. 

The third repo / vsix file (community server connector / rsp-server-community)  is not strictly necessary. If we can get it to work with just the first 2 that would probably fix the third one. Also the third repo is a bit more complicated (it has a mvn build in one folder that is a pre-req for the vsix build) so it might be worthwhile to ignore or remove that third vsix from the devfile unless you're very ambitious.

**Comment by benoitf** [comment]
Can you say how to reproduce problems ? Like if we need to open files or run some commands, start some servers etc ?
Or we just need to enable extensions and wait ?

**Comment by gattytto** [comment]
@robstryker thank you for summarizing the info sources for all extensions, please change the title to something like "add RSP UI extension to che (remote server protocol)" to help indexing in not so smart search engines 😉. 

it seems like you are adding an extra layer that you can avoid here. for this you can use a java (maven/gradle) based sidecar, as noted by the main extension docs:

> "java.home: Specifies the path to a JDK (version 8 or newer) which will be used to launch the Runtime Server Protocol (RSP) Server, as well as be the default java to launch any Java-based runtimes that the RSP will control."

windows specific stuff is not important since sidecar images are linux based.

> It's worth noting that all three of these depend on a node.js lib called vscode-server-connector-api found at https://github.com/redhat-developer/vscode-server-connector-api which basically wraps around the vscode.extensions.getExtension calls and provides some useful interface for us to use those calls more cleanly.

so having a base docker-image sidecar container running as the runtime host of the 3 extensions, they will share any additional binary you throw inside the sidecar, at this point you can EXTEND the java sidecar to add the language server implementation the extension requires, using this setting: "rsp-ui.enableStartServerOnActivation: " from the devfile, for this first you need to extend the sidecar making a Dockerfile that goes like:
````Dockerfile
FROM quay.io/eclipse/che-sidecar-java:8
````
then run the needed commands as instructed by: https://github.com/redhat-developer/rsp-server#building-the-client-and-server. Then you will have a java-based sidecar that also includes your language-server and client, 

after doing this you can declare a che plugin meta.yaml like:
 ````yaml
apiVersion: v2
publisher: ms-vscode
name: RSPUI
version: x.y
type: VS Code extension
displayName: Support for Remote Server Protocol and redhat premium/community server connector
title: RSP UI with RH Server Connector
description: all you need to use red hat server connector from your browser
icon: https://raw.githubusercontent.com/redhat-developer/vscode-java/v0.63.0/icons/icon128.png
repository: https://github.com/user/repo
category: Language
firstPublicationDate: "2020-06-11"
spec:
  containers:
    - image: "quay.io/your-user/che-sidecar-rspui:latest" #here comes your extended sidecar
      name: vscode-rspui
      memoryLimit: "2Gi"
      volumes:
      - mountPath: "/home/theia/.m2"
        name: m2
  extensions:
    - https://link/to/main/extension.vsix
    - https://link/to/another/extension.vsix
    - https://link/to/community/extension.vsix
 ````

after all this you can have a devfile like:
````yaml
---
apiVersion: 1.0.0
metadata:
  generateName: redhat-serverconnector-
projects:
.....etc
- preferences:
      rsp-ui.enableStartServerOnActivation: '/opt/rspui-language-server/bin/rspls
    type: chePlugin
    reference: 'https://github.com/your-username/your_plugin_meta.yaml'
    alias: rspui
````
