### ISSUE TITLE
As an Admin, during the Eclipse Che installation flow, I want to have a possibility to optionally install the kubernetes-image-puller for faster workspace startup

### ISSUE THREAD

**Issue by ibuziuk** [eclipse-che/che#18133]
### Is your task related to a problem? Please describe.
Currently, kubernetes-image-puller is the operator which is installed and managed separately from the Eclipse Che operator - https://www.eclipse.org/che/docs/che-7/administration-guide/caching-images-for-faster-workspace-start/

Need to explore the possibility of making kubernetes-image-puller as an optional dependency of the Eclipse Che operator. 

### Describe the solution you'd like

The installation flow could be the following:

- Admin installs Eclipse Che operator via OperatorHub
- During the `CheCluster` CR creation there should be an option to enable k8s-image-puller (via both yaml an UI) similar to how the `OpenShift oAuth / TLS mode` are currently managed.

![image](https://user-images.githubusercontent.com/1461122/96451265-9b100c00-1217-11eb-9cf3-b3fd8a1aefda.png)

- If `kubetenets-image-puller` option is enabled Eclipse Che operator should create the `KubernetesImagePuller` with the set of images for pre-pulling that is relevant for the current version of Eclipse Che e.g. for version `7.20.0` :

```
apiVersion: che.eclipse.org/v1alpha1
kind: KubernetesImagePuller
metadata:
  name: image-puller
spec:
  daemonsetName: k8s-image-puller
  images: >-
    java11-maven=quay.io/eclipse/che-java11-maven:7.20.0;che-theia=quay.io/eclipse/che-theia:7.20.0
```
 
### Describe alternatives you've considered

Manage Eclipse Che and Image Puller operators separately as it currently works today - https://www.eclipse.org/che/docs/che-7/administration-guide/caching-images-for-faster-workspace-start/

### Additional context
N/A
