### ISSUE TITLE
[chectl] "Error: ENOENT: no such file or directory, mkdir" error when start workspace on minikube

### ISSUE THREAD

**Issue by dmytro-ndp** [eclipse-che/che#18169]
### Describe the bug
`workspace:create --start` command of **chectl/0.0.20201021-next.74d8309 linux-x64 node-v10.22.1** failed on minikube 1.1.1:
https://codeready-workspaces-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/job/basic-MultiUser-Che-check-e2e-tests-against-k8s/2544/console
```
+ chectl workspace:create --start --devfile=test-workspace-devfile.yaml --access-token <access-token> --chenamespace=eclipse-che
› Current Kubernetes context: 'minikube'
    Error: ENOENT: no such file or directory, mkdir 
    '/home/hudson/.config/chectl'
    Code: ENOENT
``` 
where test-workspace-devfile.yaml is from https://github.com/eclipse/che/blob/master/tests/e2e/files/happy-path/happy-path-workspace.yaml

Regular workspace had started successfully from Che Dashboard.

The problem wasn't reproduced on minishift 3.11.

### Che version

 - [ ] latest
 - [x] nightly
 - [ ] other: please specify

### Steps to reproduce

1. Download next chectl https://github.com/che-incubator/chectl/releases/download/20201021165031/chectl-linux-x64.tar.gz
1. Deploy Che to minikube 1.1.1:
```
chectl server:start --k8spodreadytimeout=180000 --listr-renderer=verbose --platform=minikube --che-operator-cr-patch-yaml=custom-resource-patch.yaml --chenamespace=eclipse-che
```
where custom-resource-patch.yaml:
```
spec:
  server:
    cheImage: 'quay.io/eclipse/che-server'
    cheImageTag: 'nightly'
    customCheProperties:
      CHE_LIMITS_USER_WORKSPACES_RUN_COUNT: '-1'
  auth:
    updateAdminPassword: false
```
3. Execute command:
```
 chectl workspace:create --start --devfile=test-workspace-devfile.yaml --access-token <access-token> --chenamespace=eclipse-che
› Current Kubernetes context: 'minikube'
    Error: ENOENT: no such file or directory, mkdir 
    '/home/hudson/.config/chectl'
    Code: ENOENT
``` 
where test-workspace-devfile.yaml is from https://github.com/eclipse/che/blob/master/tests/e2e/files/happy-path/happy-path-workspace.yaml

### Runtime
   - [ ] kubernetes (include output of `kubectl version`)
   - [ ] Openshift (include output of `oc version`)
   - [x] minikube 1.1.1
   - [ ] minishift (include output of `minishift version` and `oc version`)
   - [ ] docker-desktop + K8S (include output of `docker version` and `kubectl version`)
   - [ ] other: (please specify)

### Installation method
   - [x] chectl/0.0.20201021-next.74d8309 linux-x64 node-v10.22.1
```
chectl server:start --k8spodreadytimeout=180000 --listr-renderer=verbose --platform=minikube --che-operator-cr-patch-yaml=custom-resource-patch.yaml --chenamespace=eclipse-che
```
where custom-resource-patch.yaml:
```
spec:
  server:
    cheImage: 'quay.io/eclipse/che-server'
    cheImageTag: 'nightly'
    customCheProperties:
      CHE_LIMITS_USER_WORKSPACES_RUN_COUNT: '-1'
  auth:
    updateAdminPassword: false
```

   - [ ] OperatorHub
   - [ ] I don't know

### Environment
   - [ ] my computer
       - [ ] Windows
       - [ ] Linux
       - [ ] macOS
   - [ ] Cloud
       - [ ] Amazon
       - [ ] Azure
       - [ ] GCE
       - [ ] other (please specify)
   - [x] other: CRW CCI

### Additional context
Possible reason: https://github.com/che-incubator/chectl/blob/f448adc0877dfa46b0bcfbe9bbe0a8f0a85d4a84/src/api/che-login-manager.ts#L144
