### ISSUE TITLE
Ability to run tests of a vscode extension on top of che-theia

### ISSUE THREAD

**Issue by benoitf** [eclipse-che/che#18219]
### Is your task related to a problem? Please describe.
A VS Code extension can declare some tests that can be run usually with `test` script.
https://code.visualstudio.com/api/working-with-extensions/testing-extension

It would be great to be able to execute these tests on top of a Che-Theia instance to validate if the extension behaves as expected.

### Describe the solution you'd like
Have a way to easily provide an extension (or a set of extensions) and grab the result of the tests.

### Additional context
Some of the `vscode-test` module is unpacking a VS Code instance, etc so we need to be sure that it can be launched as expected on top of Che-Theia

**Comment by svor** [comment]
@benoitf As you wrote in the description some extensions like [helloworld-test-sample](https://github.com/microsoft/vscode-extension-samples/tree/master/helloworld-test-sample) download VS Code and run the Mocha tests on it.  I've made it possible to run these tests from che in VS Code instance (i've just prepared an image for that) but I don't see the reason of it.
So, am I correct that we have to override this operation to run these tests in che instance NOT in VS Code.

**Comment by benoitf** [comment]
@svor yes it needs to tests within a Che instance, not VS Code (the goal is to check if tests are passing in Che, not on VS Code)

**Comment by svor** [comment]
@benoitf @ericwill 
Could you please take a look at this instructions which I'm trying to implement right now and please let me know if you see some concerns or problems here. 

The main idea is:

1. Start a workspace by using the devfile which includes:

   -  A sidecar plugin with VSCode extension which should be tested
   -  Tested extension's source code (clone into /projects) 
   -  New theia plugin which will collect all tests from VSCode extension, run them and build the report.

 So, the devfile will be like:
```yaml
apiVersion: 1.0.0
metadata:
  name: test-runner
projects:
  - name: vscode-yaml //extension which needs to be tested
    source:
      location: 'https://github.com/redhat-developer/vscode-yaml.git'
      type: git
      branch: master
  - name: vscode-extension-test-runner
    source:
      location: 'https://github.com/vscode-extension-test-runner.git'
      type: git
      branch: main
components:
  - type: chePlugin
    reference: 'https://raw.githubusercontent.com/vscode-extension-test-runner/meta.yaml'
  - id: redhat/vscode-yaml/latest
    type: chePlugin
  - id: eclipse/che-theia/next
    memoryLimit: 1024Mi
    type: cheEditor
```
2. When the workspace was started, the next steps are:
    - Build VS Code extension's source code
    - Execute some registered command by the new theia plugin to collect Mocha tests and run them
    - Generate testReport file with the results

**Comment by ericwill** [comment]
I think it's a good first step. The end goal is to automate this in a CI job, whenever a new plugin is added/updated.

>     1. When the workspace was started, the next steps are:
>        
>        * Build VS Code extension's source code
>        * Execute some registered command by the new theia plugin to collect Mocha tests and run them
>        * Generate testReport file with the results

I guess the tests have to be run at build time, correct?

**Comment by benoitf** [comment]
@svor I would say that intermediate devfile is not so important on the goal. (detail of implementation that belongs to you)

as Eric was saying:
When I submit a change to `che-theia-plugins.yaml` for every new VS Code extension added or updated, I need to run the tests contained by the provided Vsix files.

so yes basically it should contain a minkube deployment, che deployment and run a custom workspace based on a devfile 

> 
> When the workspace was started, the next steps are:
> Build VS Code extension's source code
> Execute some registered command by the new theia plugin to collect Mocha tests and run them
> Generate testReport file with the results

Here it's what is uncleared to me. You may just add different parameters to a Che-Theia instance starting in "test mode" and will execute tests and exit at the end. (0 = succeed, 1 = failure) as it's done on VS Code tests.

**Comment by ericwill** [comment]
> @svor I would say that intermediate devfile is not so important on the goal. (detail of implementation that belongs to you)

I would say we could include such a devfile in the plugin registry repo, as an example for users who want to test an extension inside their Che.

**Comment by benoitf** [comment]
maybe if you want to test from inside Che, you might just want to run a command

open che-theia terminal
```
$ che-theia test /path-to-my.vsix
```

but yes I'm not against having examples

**Comment by svor** [comment]
> When I submit a change to che-theia-plugins.yaml for every new VS Code extension added or updated, I need to run the tests contained by the provided Vsix files.
As I know vsix don't provide tests

**Comment by benoitf** [comment]
I mean' if you change in che-theia-plugins file some extensions/vsix then we need to test these VCode extensions. And we've repository/revision to grab associated source code ( of at least one extension) or if test folder is embedded in vsix

**Comment by svor** [comment]
### <p align=center>Current status</p>
I've created an utility Theia pluin [che-vscode-extension-tests](https://github.com/svor/che-vscode-extension-tests). This plug-in provides a command which collects all `*.test.js` files from `/projects` folder and runs them one by one by using `mocha`. Also this plug-in contains a devfile which was adapted to work with [helloworld-test-sample](https://github.com/microsoft/vscode-extension-samples/tree/master/helloworld-test-sample)  - it is a simple VS Code extension sample which shows how to write tests.
<details>
<summary><b>Devfile</b></summary>

```yaml
  apiVersion: 1.0.0
metadata:
  name: che-helloworld-test-sample
projects:
  - name: helloworld-test-sample
    source:
      location: 'https://github.com/svor/helloworld-test-sample.git'
      type: git
      branch: main
components:
  - mountSources: true
    memoryLimit: 3Gi
    type: dockerimage
    image: 'quay.io/eclipse/che-theia-dev:next'
    alias: che-dev
  - type: chePlugin
    reference: 'https://raw.githubusercontent.com/svor/che-vscode-extension-tests/main/meta.yaml'
  - id: eclipse/che-theia/next
    memoryLimit: 1024Mi
    type: cheEditor
commands:
  - name: 1. Build extension
    actions:
    - type: exec
      component: che-dev
      command: yarn && yarn compile
      workdir: ${CHE_PROJECTS_ROOT}/helloworld-test-sample
```
</details> 

<details>

<summary><b>Che plug-in meta.yaml</b></summary>

```yaml

apiVersion: v2
publisher: Red Hat
name: Smoke-Test-Plugin
version: 0.0.1
type: Theia plugin
displayName: Smoke Test Plugin
title: Smoke-Test-Plugin
description: This plug-in runs tests
icon: https://www.eclipse.org/che/images/logo-eclipseche.svg
repository: https://github.com/svor/che-vscode-extension-tests
category: Language
firstPublicationDate: "2021-01-28"
spec:
  extensions:
    - https://raw.githubusercontent.com/svor/che-vscode-extension-tests/main/che_vscode_test_theia_plugin.theia
    - https://raw.githubusercontent.com/svor/helloworld-test-sample/main/helloworld-sample-0.0.1.vsix
```

</details>

If start the a workspace by using this devfile, it will initialize 2 plugins: the one is VS Extension which needs to be tested and another to collect and execute tests, also it'll clone source code of the tested extension into the workspace. By executing `1.Build extension` command we build the VS Code extension's source code to prepare tests files.
![screenshot-che-dogfooding apps che-dev x6e0 p1 openshiftapps com-2021 02 02-15_27_48](https://user-images.githubusercontent.com/1271546/106610161-14d1c880-656f-11eb-8673-6b684f7e8de7.png)

When `/projects/tested_extension/**/*test.js` files were generated we can run them by using the command from utility Theia plu-gin:
![screenshot-che-dogfooding apps che-dev x6e0 p1 openshiftapps com-2021 02 02-15_28_41](https://user-images.githubusercontent.com/1271546/106610661-b5c08380-656f-11eb-8165-f2d3dfd901dd.png)
The result of tests execution was entered into `/projects/test.log` file.

### <p align=center>TODO</p>
The next my step is to automate this flow and run tests when some of the vsix url from `che-theia-plugins.yaml` will be changed. For this I need:

- [ ] Analyze somehow which extension is going to be updated and get source's url
- [ ] Generate a new plug-in meta.yaml with tested extension to activate it in tested Che environment (for each extension which runs as a sidecar it should be individual with its own image)
- [ ] Generate a new devfile with a project from the task1, with a plug-in from the taks2 and one more utility plug-in to collect and run tests 
- [ ] In the workspace build the extension's source code and run tests (make it automatically).

**Comment by svor** [comment]
@benoitf @ericwill some updates:

- I've added a new [GitHub action](https://github.com/svor/che-plugin-registry/blob/sv/vscode-test/.github/workflows/vscode-extension-tests-check.yaml) to run tests from VScode extension in my branch. The main script is [here](https://github.com/svor/che-plugin-registry/blob/sv/vscode-test/.ci/prepare-extension-project.sh) 
- The result of the execution is [here](https://github.com/svor/che-plugin-registry/runs/1934952549?check_suite_focus=true) 

Currently it only runs tests for [vscode-yaml extension](https://github.com/svor/che-plugin-registry/blob/sv/vscode-test/.ci/prepare-extension-project.sh#L27). I haven't found a solution how to get the repository of the changed extension via analyzing changes in che-theia-plugins.yaml yet.

**Comment by benoitf** [comment]
if you do a diff of localche-theia-plugins.yaml against master (when it's inside a branch) or against the rebase branch (in case of PR mode) you should be able to know which plug-in is added/modified and then you can grab the registry definition from yaml file

then iterating over repository entries until you've line numbers should give you the entry

`git diff -U0` should help there or `git diff -U0 che-theia-plugins.yaml | grep @@ | cut -d ' ' -f 3`
so you have starting lines and it's easy to match the modified/added repository

**Comment by svor** [comment]
@ericwill looks like the decision to grep tests from the extension which was cloned and built in /projects folder was wrong. Some execution of vscode API doesn't work as expected, for example `vscode.extensions` always returns `undefined`(that's why I've created an issue for that https://github.com/eclipse/che/issues/19172), but for example `vscode.workspace.*` works as expected.
I've created a [VSCode extension](https://github.com/svor/extension-tests-runner) to check tests execution 
```yaml
apiVersion: 1.0.0
metadata:
  name: che-helloworld-test-sample
projects:
  - name: extension-tests-runner
    source:
      location: 'https://github.com/svor/extension-tests-runner.git'
      type: git
components:
  - mountSources: true
    memoryLimit: 3Gi
    type: dockerimage
    image: 'quay.io/eclipse/che-theia-dev:next'
    alias: che-dev
  - type: chePlugin
    reference: 'https://raw.githubusercontent.com/svor/extension-tests-runner/main/meta.yaml'
  - id: timonwong/shellcheck/latest
    type: chePlugin
  - id: eclipse/che-theia/next
    memoryLimit: 1024Mi
    type: cheEditor
```
And tried to execute the same tests from different places:
1. From `/projects/extension-tests-runner/out/test/suit/extension.test.js` (**Run VSCode Extension's Tests From /projects** command)
2. From the extension which is running in theia-ide container `/tmp/vscode-unpacked/extension-tests-runner/out/test/suit/extension.test.js` (**Run VSCode Extension's Tests from extension** command)

In the first case it was failed but in the second it was successfully finished.
So, needs to find another way how to execute extension's tests
