### ISSUE TITLE
migrate vscode-extensions.json to a che-theia-plugins file

### ISSUE THREAD

**Issue by benoitf** [eclipse-che/che#18215]
### Is your task related to a problem? Please describe.
Today, vscode-extensions.json file defines a list of vsix to analyze to detect new updates.
But we've some che plugins referencing multiple vsix and some vsix are not available as a single che-plugin.

and then we still have the `v3/plugins` folder so contributors need to update different files with the same information

### Describe the solution you'd like
Have a single file describing all plug-ins:
 - it should include the minimal information if a chePlugin match a single vsix
 - if a che plugin includes several vsix, then we can specify the information about vsix alongside.

example to list several vsix:
```yaml
---
chePlugins:
- id: redhat/java
  ...
  sidecar:
   image: quay.io/eclipse/che-sidecar-java:11-7bd8c8c
   source:
     repository: https://github.com/che-dockerfiles/che-sidecar-java
  extensions:
  - repository: https://github.com/redhat-developer/vscode-java
    revision: v0.69.0
  - repository: https://github.com/redhat-developer/vscode-java-debug
    revision: v0.1.2.3
```

example if we want to have a vsix directly exposed as a chePlugin with all default options:
```yaml
chePlugins:
- repository: https://github.com/microsoft/vscode-pull-request-github
  revision: 0.20.0
```

### Describe alternatives you've considered
could be json or yaml but maybe as we may include fragments of devfile.yaml should be done in yaml.

### Additional context
Idea is to be able to completely remove `v3/plugins` folder and have `index.json` and `meta.yaml` files automatically generated
This file should be used to generate devfile 2.0 yaml files as well

one source, multiple outputs
