### ISSUE TITLE
[che-operator] Che SA can get permissions to update namespaces

### ISSUE THREAD

**Issue by sparkoo** [eclipse-che/che#18272]
### Is your enhancement related to a problem? Please describe.

We need `update` and `get` `namespaces` cluster-wide permissions for `che` SA to be able to label namespaces. https://github.com/eclipse/che/issues/17504

### Describe the solution you'd like

Che-operator should get new ClusterRole to be able to `update` and `get` `namespaces`. then with some new CheCluster configuration, it will assign this ClusterRole to `che` SA.

for more context, read this comment + reply: https://github.com/eclipse/che/issues/17504#issuecomment-718858659

Once we introduce option to disable labeling on che-server side (https://github.com/eclipse/che/issues/18301), we may want to set this property from che-operator as well. This depends on what CheCluster CR configuration form we choose here.

I think we will need to do these steps:
 - [x] prepare new ClusterRole and ClusterRoleBinding for che-operator (https://github.com/eclipse/che-operator/pull/520) 
 - [ ] update chectl to deploy che-operator ServiceAccount with these ClusterRole and ClusterRoleBinding (https://github.com/che-incubator/chectl/pull/977)
 - [ ] introduce new property into CheCluster CRD. If this property is configured in certain way, che-operator will create ClusterRoleBinding for `che` ServiceAccount with the new ClusterRole

##### ClusterRole
```
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: che-namespace-editor
rules:
  - apiGroups:
      - ""
    resources:
      - namespaces
    verbs:
      - update
      - get
```
##### ClusterRoleBinding
```
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: che-operator-namespace-editor
subjects:
  - kind: ServiceAccount
    name: che-operator
    namespace: che
roleRef:
  kind: ClusterRole
  name: che-namespace-editor
  apiGroup: rbac.authorization.k8s.io
```
##### CheCluster
```
spec:
  server:
    labelNamespaces: `true|false` # enables the che-server label-namespace property and sets the permissions to che SA
```
XOR
```
spec:
  server:
    namespaceEditorClusterRole: `true|false` # sets permissions
    labelNmaespaces: `true|false` # sets che-server label-namespace property
```
XOR
```
spec:
  server:
    cheClusterRoles: `che-namespace-editor`  # Comma separated list of cluster roles that should be assigned to che ServiceAccout
    labelNamespace: `true|false` # sets che-server label-namespace property
```

### Additional context

https://github.com/eclipse/che/issues/17504

**Comment by sparkoo** [comment]
cc: @davidfestal @tolusha are you ok with che-operator getting cluster-wide permissions to `update` and `get` `namespaces`?

**Comment by azatsarynnyy** [comment]
I'm setting P2, but feel free to re-prioritize it if needed.

**Comment by davidfestal** [comment]
I think we should just ensure whether adding those cluster-wide permissions to the operator would have impact on the OSD CRW addon (are there maximum permissions above which single-namespaced addons cannot be installed ?) 
cc @ibuziuk

**Comment by sparkoo** [comment]
We would need additional ClusterRoleBinding cluster-wide permissions for che-operator, so it can create the ClusterRoleBinding for che ServiceAccount. I didn't realize it's not doing that already.
New permissions are:
```
  - apiGroups:
      - rbac.authorization.k8s.io
    resources:
      - clusterrolebindings
    verbs:
      - list
      - create
      - watch
```
PR: https://github.com/eclipse/che-operator/pull/520

cc: @tolusha @l0rd @davidfestal
