### ISSUE TITLE
Per-volume ephemeral attribute in devfile

### ISSUE THREAD

**Issue by mshaposhnik** [eclipse-che/che#18271]
### Is your task related to a problem? Please describe.
Che-plugins allow to set `ephemeral` mode for container volumes described in meta.yaml. 
To share such a volume with some other component, it is need to be possible to set `ephemeral` in the target component volume definition as well, since the same volume cannot be bound in ephemeral and persistent mode at the same time.

### Additional context
https://github.com/eclipse/che/issues/17102#issuecomment-720671430
Expected devfile format:

<details>
   <summary>devfile</summary>

```
apiVersion: 1.0.0
metadata:
  name: testJDKVersionKube
attributes:
  persistVolumes: 'true'
projects:
  - name: console-java-simple
    source:
      location: 'https://github.com/che-samples/console-java-simple.git'
      type: git
      branch: java1.11
components:
  - referenceContent: |
      apiVersion: v1
      kind: Pod
      metadata:
        name: ws
      spec:
        initContainers:
          - name: init-myservice
            image: adoptopenjdk/openjdk15-openj9
            command: ['sh', '-c', "echo copying jdk... && cp -R /opt/java/openjdk/ /tmp/jdk && echo done"]
    type: kubernetes
    volumes:
      - name: jdk
        containerPath: /tmp/jdk
        ephemeral: true
  - id: redhat/java11/latest
    preferences:
      java.configuration.runtimes: |-
        [
          {
            "name": "Open J9 15",
            "path": "/tmp/jdk/openjdk",
            "default": true
          }
        ]
    type: chePlugin
    volumes:
      - name: jdk
        containerPath: /tmp/jdk
  - mountSources: true
    memoryLimit: 512Mi
    type: dockerimage
    volumes:
      - name: jdk
        containerPath: /tmp/jdk
        ephemeral: true
      - name: m2
        containerPath: /home/user/.m2
    image: 'quay.io/eclipse/che-java11-maven:7.13.1'
    alias: maven
    env:
      - value: /tmp/jdk/openjdk
        name: JAVA_HOME
      - value: ''
        name: MAVEN_CONFIG
      - value: '-XX:MaxRAMPercentage=50 -XX:+UseParallelGC -XX:MinHeapFreeRatio=10 -XX:MaxHeapFreeRatio=20 -XX:GCTimeRatio=4 -XX:AdaptiveSizePolicyWeight=90 -Dsun.zip.disableMemoryMapping=true -Xms20m -Djava.security.egd=file:/dev/./urandom'
        name: JAVA_OPTS
      - value: '-XX:MaxRAMPercentage=50 -XX:+UseParallelGC -XX:MinHeapFreeRatio=10 -XX:MaxHeapFreeRatio=20 -XX:GCTimeRatio=4 -XX:AdaptiveSizePolicyWeight=90 -Dsun.zip.disableMemoryMapping=true -Xms20m -Djava.security.egd=file:/dev/./urandom -Duser.home=/home/user'
        name: MAVEN_OPTS
      - value: '-XX:MaxRAMPercentage=50 -XX:+UseParallelGC -XX:MinHeapFreeRatio=10 -XX:MaxHeapFreeRatio=20 -XX:GCTimeRatio=4 -XX:AdaptiveSizePolicyWeight=90 -Dsun.zip.disableMemoryMapping=true -Xms20m -Djava.security.egd=file:/dev/./urandom'
        name: JAVA_TOOL_OPTIONS
commands:
  - name: maven build
    actions:
      - workdir: '${CHE_PROJECTS_ROOT}/console-java-simple'
        type: exec
        command: mvn clean install
        component: maven
  - name: maven build and run
    actions:
      - workdir: '${CHE_PROJECTS_ROOT}/console-java-simple'
        type: exec
        command: mvn clean install && java -jar ./target/*.jar
        component: maven
```
</details>
