### ISSUE TITLE
The Scala language extension (Metals language server) fails with Quota exceeded

### ISSUE THREAD

**Issue by sideeffffect** [eclipse-che/che#18286]
### Describe the bug
When starting a workspace from the Scala stack, importing the project fails with "Quota exceeded".

### Che version

 - [ ] latest
 - [ ] nightly
 - [x] other: on `che.openshift.io`: `Che-Theia@66ce79d using Theia@eb1136b11`

### Steps to reproduce

1. Create a new project from the Che Scala template (see the screenshot above)
2. Open the directory `console-scala-simple`
3. Import the project (a pop-up window in the bottom right corner)
4. This fails, the logs can be seen in Metals' (the Scala language server) logs
	1. click the Metals "M" icon in the side toolbar
    1. click "Help and feedback"
    1. click Check logs

```
Caused by: org.eclipse.lsp4j.jsonrpc.ResponseErrorException: /home/theia/.cache/coursier/v1/.structure.lock (Quota exceeded)
	at org.eclipse.lsp4j.jsonrpc.RemoteEndpoint.handleResponse(RemoteEndpoint.java:209)
	at org.eclipse.lsp4j.jsonrpc.RemoteEndpoint.consume(RemoteEndpoint.java:193)
	at org.eclipse.lsp4j.jsonrpc.json.StreamMessageProducer.handleMessage(StreamMessageProducer.java:194)
	at org.eclipse.lsp4j.jsonrpc.json.StreamMessageProducer.listen(StreamMessageProducer.java:94)
	at org.eclipse.lsp4j.jsonrpc.json.ConcurrentMessageProcessor.run(ConcurrentMessageProcessor.java:113)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.lang.Thread.run(Thread.java:834)
```

### Expected behavior
This used to work for me. I don't know what changed. I am a normal, non-paying, non-premium `che.openshift.io` user, so maybe my account's quote lowered?
Could somebody with higher quota check, that Scala works well inside Chec (`che.openshift.io`). We created a special image (`che-sidecar-scala`) which already contains most of the binaries for Metals, so I find it weird that I would hit quota merely by importing the project (which transitively causes downloading of the Metals language server and other tools, like Scala compiler, etc). As I've said, it used to work for me before.
Maybe the `che-sidecar-scala` image is not mounted properly, so that the artifacts (Metals, Scala compiler) are not reused?

/cc @ericwill

### Runtime
   - [ ] kubernetes (include output of `kubectl version`)
   - [x] Openshift (include output of `oc version`)
   - [ ] minikube (include output of `minikube version` and `kubectl version`)
   - [ ] minishift (include output of `minishift version` and `oc version`)
   - [ ] docker-desktop + K8S (include output of `docker version` and `kubectl version`)
   - [ ] other: (please specify)

### Screenshots

![image](https://user-images.githubusercontent.com/9019485/98185933-f75c7680-1f0d-11eb-8efc-5cfa8a2d51c3.png)

![image](https://user-images.githubusercontent.com/9019485/98186324-cd578400-1f0e-11eb-8de1-d3748626177c.png)

### Installation method
   - [ ] chectl
     * provide a full command that was used to deploy Eclipse Che (including the output)
     * provide an output of `chectl version` command
   - [ ] OperatorHub
   - [x] I don't know

### Environment
   - [ ] my computer
       - [ ] Windows
       - [ ] Linux
       - [ ] macOS
   - [x] Cloud
       - [ ] Amazon
       - [ ] Azure
       - [ ] GCE
       - [x] other: `che.openshift.io`
   - [ ] other

### Additional context

Relevant repos:
https://github.com/che-dockerfiles/che-sidecar-scala
https://github.com/eclipse/che-plugin-registry/tree/master/v3/plugins/scalameta/metals
https://github.com/eclipse/che-devfile-registry/tree/master/devfiles/scala-sbt

**Comment by ericwill** [comment]
Does importing the project trigger some sort of build action? Is it a large project? I'm trying to figure out what could be exceeding the quota.

**Comment by sideeffffect** [comment]
It does trigger a build action. But the project is very small (https://github.com/sideeffffect/console-scala-simple) and as I've said, the very same setup used to work couple of months ago.
I suspect that what takes up a lot of the space (and eventually hits the quota) is downloading all the artifacts -- it's not just the libraries the project is directly using, but also the Scala compiler, the Metals language server, etc. All of these are just JARs being downloaded from Maven Central.

**Comment by ericwill** [comment]
> It does trigger a build action. But the project is very small (https://github.com/sideeffffect/console-scala-simple) and as I've said, the very same setup used to work couple of months ago.
> I suspect that what takes up a lot of the space (and eventually hits the quota) is downloading all the artifacts -- it's not just the libraries the project is directly using, but also the Scala compiler, the Metals language server, etc. All of these are just JARs being downloaded from Maven Central.

Yes that would do it. This isn't the first time this has come up, several other language stacks also have quota issues when building.

Thanks for the bug report, I'll see if there isn't something we can do about it.

**Comment by sideeffffect** [comment]
But we made the sidecar specifically, so that the JARs (or most of them) are already present, and don't need to be re-downloaded while taking up quota. It seems like the JARs from the sidecar are not used or available.
Do you think you could check it out?
The usual places where these JARs reside are `~/.sbt`, `~/.ivy2` and `~/.cache/coursier`.

**Comment by gattytto** [comment]
@sideeffffect maybe check the meta.yaml you are using, if you are defining volumes in the meta.yaml for those ~/.sbt and others, the content of those folders in the sidecar will be emptied and the new volume will be linked to your available storage quota, so maybe if you can share the meta.yaml you are using could bring some more cluse about the issue

**Comment by sideeffffect** [comment]
@gattytto This is the devfile I'm using
https://github.com/eclipse/che-devfile-registry/blob/master/devfiles/scala-sbt/devfile.yaml
are you saying that I should actually _remove_ those parts about `~/.sbt` & co. from the devfile?

**Comment by gattytto** [comment]
not for the "dockerimage" component, but if you check the plugin-registry [meta.yaml](https://github.com/eclipse/che-plugin-registry/blob/master/v3/plugins/scalameta/metals/1.9.4/meta.yaml) for the scala plugin: 
````yaml
apiVersion: v2
publisher: scalameta
name: metals
version: 1.9.4
type: VS Code extension
displayName: Scala (Metals)
title: Scala language server with rich IDE features
description: This plug-in provides support for Scala development via the Metals language server.
icon: https://raw.githubusercontent.com/scalameta/metals-vscode/v1.9.4/images/logo.png
repository: https://github.com/scalameta/metals-vscode
category: Language
firstPublicationDate: "2020-09-21"
spec:
  containers:
    - image: "quay.io/eclipse/che-sidecar-scala:0.9.0-b92a5f9"
      name: vscode-metals
      memoryLimit: "1500Mi"
      volumes:
      **- name: sbt
        mountPath: "/home/theia/.sbt"
      - name: ivy2
        mountPath: "/home/theia/.ivy2"
      - name: coursier
        mountPath: "/home/theia/.cache/coursier"
      - name: metals
        mountPath: "/home/theia/.cache/metals"
      - name: bloop
        mountPath: "/home/theia/.cache/bloop"**
  extensions:
    - https://github.com/scala/vscode-scala-syntax/releases/download/0.4.5/scala-lang.scala-0.4.5.vsix
    - https://github.com/scalameta/metals-vscode/releases/download/v1.9.4/scalameta.metals-1.9.4.vsix
```` 

this is when anything coming from the sidecar Dockerfile stage will be ignored and re-mapped to an empty (first time if not ephemereal) folder in your workspaces volumeclaim within the che free account. 

RECAP:
CLI (or defined in devfile) containers have no relation to the extension, but the actual sidecar container image is defined in the plugin meta.yaml, if that meta.yaml has volumes for folders pre-existent in the docker image, they will be ignored. Thus causing the extension to re-download the stuff. So it's the meta.yaml that you need to customize and reference in your defile where you add the: 
````yaml
components:
  -
    type: chePlugin
    id: scalameta/metals/latest
````
you should instead use a reference to a custom meta.yaml that uses a sidecar with the pre-fillled content and WITHOUT the volumes, so the data persists from the Dockerfile stage and it isn't taken in account as part of your free storage in che.osio

**Comment by gattytto** [comment]
@ericwill maybe removing this volumes from the meta.yaml to let the sidecar image intact could help? cli container will still redownload but at least the extension won't.

**Comment by sideeffffect** [comment]
If I have the devfile like this, it unfortunately doesn't work at all.
The good thing is that I can see the downloaded/cached artefacts when browsing from bash terminal. But they are owned by `root`.
Which is probably the reason why running the Metals extension fails with
```
Java home: /usr/lib/jvm/default-jvm/
Metals version: 0.9.4
Error while downloading https://repo1.maven.org/maven2/com/github/alexarchambault/case-app-annotations_2.12/2.0.0-M9/case-app-annotations_2.12-2.0.0-M9.jar: /home/theia/.cache/coursier/v1/.structure.lock (Permission denied), ignoring it
Error while downloading https://repo1.maven.org/maven2/io/get-coursier/coursier-cache_2.12/2.0.0-RC5-3/coursier-cache_2.12-2.0.0-RC5-3.jar: /home/theia/.cache/coursier/v1/.structure.lock (Permission denied), ignoring it
Error while downloading https://repo1.maven.org/maven2/io/get-coursier/coursier-cli_2.12/2.0.0-RC5-3/coursier-cli_2.12-2.0.0-RC5-3.jar: /home/theia/.cache/coursier/v1/.structure.lock (Permission denied), ignoring it
```

Do you have any other suggestion @gattytto that I could try?

```yaml
apiVersion: 1.0.0
metadata:
  name: wksp-0s1g
attributes:
  persistVolumes: 'false'
projects:
  - name: console-scala-simple
    source:
      location: 'https://github.com/sideeffffect/console-scala-simple.git'
      type: git
      branch: master
components:
  - type: chePlugin
    reference: 'https://github.com/sideeffffect/che-plugin-registry/raw/scala-metals-1.9.5/v3/plugins/scalameta/metals/1.9.5/meta.yaml'
  - mountSources: true
    memoryLimit: 2000Mi
    type: dockerimage
    volumes:
      - name: bloop
        containerPath: /home/user/.cache/bloop
      - name: coursier
        containerPath: /home/user/.cache/coursier
      - name: ivy2
        containerPath: /home/user/.ivy2
      - name: metals
        containerPath: /home/user/.cache/metals
      - name: sbt
        containerPath: /home/user/.sbt
    image: 'quay.io/eclipse/che-java11-maven:nightly'
    alias: sbt
    env:
      - value: '-J-XX:MaxRAMPercentage=50 -J-XX:+UseParallelGC -J-XX:MinHeapFreeRatio=10 -J-XX:MaxHeapFreeRatio=20 -J-XX:GCTimeRatio=4 -J-XX:AdaptiveSizePolicyWeight=90 -Dsun.zip.disableMemoryMapping=true -J-Xms20m -Djava.security.egd=file:/dev/./urandom -Duser.home=/home/user'
        name: SBT_OPTS
      - value: '-XX:MaxRAMPercentage=50 -XX:+UseParallelGC -XX:MinHeapFreeRatio=10 -XX:MaxHeapFreeRatio=20 -XX:GCTimeRatio=4 -XX:AdaptiveSizePolicyWeight=90 -Dsun.zip.disableMemoryMapping=true -Xms20m -Djava.security.egd=file:/dev/./urandom'
        name: JAVA_OPTS
      - value: '-XX:MaxRAMPercentage=50 -XX:+UseParallelGC -XX:MinHeapFreeRatio=10 -XX:MaxHeapFreeRatio=20 -XX:GCTimeRatio=4 -XX:AdaptiveSizePolicyWeight=90 -Dsun.zip.disableMemoryMapping=true -Xms20m -Djava.security.egd=file:/dev/./urandom'
        name: JAVA_TOOL_OPTIONS
```
