### ISSUE TITLE
Container or pods should specify resource limits

### ISSUE THREAD

**Issue by kristinochka** [eclipse-che/che#18356]
### Is your enhancement related to a problem? Please describe.

All pods should specify container resources.  `operator.yaml` and `operator-local.yaml` don't specify resource limits. 

### Describe the solution you'd like

operator.yaml and operator-local.yaml should specify one or more of the following:
spec.containers[].resources.limits.cpu
spec.containers[].resources.limits.memory
spec.containers[].resources.requests.cpu
spec.containers[].resources.requests.memory

For example:
```
spec:
  containers:
  - resources:
      limits:
        cpu: "1"
        memory: 512Mi
      requests:
        cpu: "0.5"
        memory: 256Mi
```

### Additional context

This is useful for people who deploy production Che to production environments to make sure pods do not consume too much resources.
