### ISSUE TITLE
Define Required Metadata Labels on deployment definitions 

### ISSUE THREAD

**Issue by kristinochka** [eclipse-che/che#18357]
### Is your enhancement related to a problem? Please describe.

The labels that Kubernetes recommends provide useful identification information used by Kubernetes, users of the cluster, and other resources.
 Following files do not have required Kubernetes metadata labels:
```
deploy/cluster_role.yaml
deploy/cluster_role_binding.yaml
```
"app.kubernetes.io/instance" "app.kubernetes.io/managed-by" "app.kubernetes.io/name" labels are missing. 

### Describe the solution you'd like

Example how this can be fixed:
```
metadata:
  labels:
    app.kubernetes.io/instance: my-instance
    app.kubernetes.io/managed-by: my-heritage
    app.kubernetes.io/name: my-name
    helm.sh/chart: my-chart

```
