### ISSUE TITLE
Unable to clone git sample repository when using Azure file share as persistent volume

### ISSUE THREAD

**Issue by UmeshIghe** [eclipse-che/che#18350]
I am trying to use Eclipse che and using Azure file share as persistent volume in Azure kubernetes services. When I am trying to create a workspace , Eclipse che clones a sample repo in Azure file share , while doing that I am getting below error :

Couldn't clone https://github.com/che-samples/console-java-simple.git: Cloning into '/projects/console-java-simple'... error: chmod on /projects/console-java-simple/.git/config.lock failed: Operation not permitted fatal: could not set 'core.filemode' to 'false'

Eclipse che creates a folder with podname in azure fileshare and under it tries to clone a repo which is faling. When i try to manually i get the same error.

`/projects $ git clone https://github.com/che-samples/react-web-app.git
Cloning into 'react-web-app'...
error: chmod on /projects/react-web-app/.git/config.lock failed: Operation not permitted
fatal: could not set 'core.filemode' to 'false'`

Below is my storage class file:
```
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: workspace-storage
provisioner: kubernetes.io/azure-file
reclaimPolicy: Retain
allowVolumeExpansion: true
parameters:
  skuName: Standard_LRS
  location: eastus
  storageAccount: storagename
mountOptions:
  - dir_mode=0777
  - file_mode=0777
```

**Comment by chopraaakash91** [comment]
HI Team, any suggestions on this error?

**Comment by gattytto** [comment]
this seems git specific, as from https://stackoverflow.com/questions/1580596/how-do-i-make-git-ignore-file-mode-chmod-changes

**Comment by UmeshIghe** [comment]
using noprem on the mount settings resolved my issue.
```
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: workspace-storage
provisioner: kubernetes.io/azure-file
reclaimPolicy: Retain
allowVolumeExpansion: true
parameters:
  skuName: Standard_LRS
  location: eastus
  storageAccount: storagename
mountOptions:
  - dir_mode=0777
  - file_mode=0777
  - noprem
```
