### ISSUE TITLE
Containers must be dropping all capabilities, and only adding the ones they need.

### ISSUE THREAD

**Issue by kristinochka** [eclipse-che/che#18359]
### Is your enhancement related to a problem? Please describe.

For best security practices containers must implement the principle of least privilege to minimize security risks by explicitly dropping ALL capabilities and only adding ones they need. 

### Describe the solution you'd like

The following deployments should have drop ALL
```
deploy/operator-local.yaml
deploy/operator.yaml
```
Example:
```
spec:
  containers:
  - securityContext:
      capabilities:
        drop:
        - ALL
```
