### ISSUE TITLE
Each pod should declare it's securityContext

### ISSUE THREAD

**Issue by kristinochka** [eclipse-che/che#18362]
### Is your enhancement related to a problem? Please describe.

For best security practices, the securityContext under each Pod must be fully declared in order to clearly communicate the workload's security posture. In order to be declarative about their security posture, Pods must define every parameter available in its securityContext and each container's securityContext. 

### Describe the solution you'd like

The following deployment don't have security definitions:
deploy/operator-local.yaml
deploy/operator.yaml

For example:
```
kind: Pod
spec:
  containers:
  - securityContext:
      allowPrivilegeEscalation: false
      capabilities:
        drop:
        - ALL
      privileged: false
      readOnlyRootFilesystem: true
      runAsNonRoot: true
      runAsUser: 1001
  hostIPC: false
  hostNetwork: false
  hostPID: false
  securityContext:
    runAsNonRoot: true
    runAsUser: 1001

```
