### ISSUE TITLE
Pods must define architecture-based node affinity.

### ISSUE THREAD

**Issue by kristinochka** [eclipse-che/che#18361]
### Is your enhancement related to a problem? Please describe.

For best practices Pods should define architecture-based node affinity. Without it, the scheduler may repeatedly attempt to schedule a Pod on an unsupported node where it will never start. As an example, a Power-only pod/container cannot be scheduled on an Intel-based node.

### Describe the solution you'd like

The following files should specify architecture they can run on:
deploy/operator.yaml
deploy/operator-local.yaml

Example:
```
spec:
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
          - key: kubernetes.io/arch
```
