### ISSUE TITLE
Obtain and persist Bitbucket personal access token as k8s secret

### ISSUE THREAD

**Issue by skabashnyuk** [eclipse-che/che#18388]
### Is your task related to a problem? Please describe.
To be able to use Bitbucket personal access token during factory resolution https://github.com/eclipse/che/issues/18386
and git operations we want to persist them as k8s secrets

### Describe the solution you'd like
Obtain and persist Bitbucket personal access token as k8s secret

```yaml
apiVersion: v1
kind: Secret
metadata:
  name: bitbucket-personal-access-token-secret
  labels:
    app.kubernetes.io/part-of: che.eclipse.org
    app.kubernetes.io/component: bitbucket-personal-access-token
  annotations:
    che.eclipse.org/expired-after: 12323423
    che.eclipse.org/che-userid: 7234090-45345234
    che.eclipse.org/bitbucket-userid: 34593094509
    che.eclipse.org/bitbucket-username: 'tshevchenko'
data:
  token: ZHNhZmFkZmFzZGZxMzRyMzRyMTM0
```

```yaml
apiVersion: v1
kind: Secret
metadata:
  name: git-credentials-secret
  labels:
    app.kubernetes.io/part-of: che.eclipse.org
    app.kubernetes.io/component: workspace-secret
  annotations:
    che.eclipse.org/expired-after: 12323423  
    che.eclipse.org/che-userid: 7234090-45345234
    che.eclipse.org/automount-workspace-secret: 'true'
    che.eclipse.org/mount-path: /home/theia/.git-credentials
    che.eclipse.org/mount-as: file
    che.eclipse.org/git-credential: 'true'
    che.eclipse.org/bitbucket-personal-access-token-secret: 'bitbucket-personal-access-token-secret'
data:
  credentials: aHR0cHM6Ly91c2VyOnBhc3NAZXhhbXBsZS5jb20K
```

### Describe alternatives you've considered
n/a
### Additional context
https://github.com/eclipse/che/issues/18385
