### ISSUE TITLE
Using Bitbucket personal access token as k8s secret during factory resolution

### ISSUE THREAD

**Issue by skabashnyuk** [eclipse-che/che#18386]
### Is your task related to a problem? Please describe.
We want to be able to access devfile content that is stored in the Bitbucket server.

### Describe the solution you'd like

Implement ability to use 
k8s secret with bitbucket personal access token
during the factory resolution process.

```yaml
apiVersion: v1
kind: Secret
metadata:
  name: bitbucket-personal-access-token-secret
  labels:
    app.kubernetes.io/part-of: che.eclipse.org
    app.kubernetes.io/component: bitbucket-personal-access-token
  annotations:
    che.eclipse.org/expired-after: 12323423
    che.eclipse.org/che-userid: 7234090-45345234
    che.eclipse.org/bitbucket-userid: 34593094509
    che.eclipse.org/bitbucket-username: 'tshevchenko'
data:
  token: ZHNhZmFkZmFzZGZxMzRyMzRyMTM0
```
Nodes :
 - secrets with missed or expired date should not be taken into account.

### Describe alternatives you've considered
n/a
### Additional context
https://github.com/eclipse/che/issues/18226#issuecomment-727887994
