### ISSUE TITLE
che-identity-secret and che-postgres-secret are gone after pods are evicted from node using kubernetes operator

### ISSUE THREAD

**Issue by guydog28** [eclipse-che/che#18395]
### Describe the bug

It took me a long time to figure out what is happening.  This is the 4th time my che cluster has been hosed.  It has been working for a long time, and I realize that is because I haven't made any updates to the cluster that required the pods to be evicted from the nodes.  We use kops to maintain our kubernetes cluster and when performing a `kops rolling-update cluster --yes` command, the cluster one by one replaces the nodes in the cluster.  This time, it was to upgrade from kubernetes 1.18.8 to 1.18.10.  When the cluster comes back, eclipse che does not.  Postgres will not start because the che-postgres-secret is no longer in the namespace.  I can only assume this is due to a bug in the operator?

### Che version

 - [x] latest
 - [ ] nightly
 - [ ] other: please specify

### Expected behavior
Che comes back up as expected.

### Runtime
   - [x] kubernetes (include output of `kubectl version`) 1.18.10
   - [ ] Openshift (include output of `oc version`)
   - [ ] minikube (include output of `minikube version` and `kubectl version`)
   - [ ] minishift (include output of `minishift version` and `oc version`)
   - [ ] docker-desktop + K8S (include output of `docker version` and `kubectl version`)
   - [ ] other: (please specify)

### Installation method
   - [x] chectl
     * chectl server:start -a operator -p k8s -b dev.myfqdn.com --che-operator-cr-yaml=/path/to/k8s-eclipse-che.yaml
     * chectl/7.21.1 darwin-x64 node-v10.23.0
   - [ ] OperatorHub
   - [ ] I don't know

### Environment
   - [ ] my computer
       - [ ] Windows
       - [ ] Linux
       - [ ] macOS
   - [x] Cloud
       - [x] Amazon
       - [ ] Azure
       - [ ] GCE
       - [ ] other (please specify)
   - [ ] other: please specify

### Additional context

The contents of k8s-eclipse-che.yaml that I used to create the cluster:
```
apiVersion: org.eclipse.che/v1
kind: CheCluster
metadata:
  name: eclipse-che
  namespace: che
spec:
  auth:
    externalIdentityProvider: false
  database:
    externalDb: false
  k8s:
    ingressDomain: dev.myfqdn.com
    tlsSecretName: dev-myfqdn-com-tls
  metrics:
    enable: true
  server:
    cheFlavor: che
    customCheProperties:
      CHE_WORKSPACE_DEFAULTMEMORYLIMIT__MB: "4096"
      CHE_INFRA_KUBERNETES_NAMESPACE_DEFAULT: "che-ws-<workspaceid>"
      CHE_INFRA_KUBERNETES_WORKSPACE__START__TIMEOUT__MIN: "15"
      CHE_WORKSPACE_PLUGIN__BROKER_WAIT__TIMEOUT__MIN: "15"
      CHE_INFRA_KUBERNETES_CLIENT_HTTP_CONNECTION__POOL_KEEP__ALIVE__MIN: "60"
      CHE_LIMITS_WORKSPACE_IDLE_TIMEOUT: "3600000"
      CHE_INFRA_KUBERNETES_WORKSPACE__UNRECOVERABLE__EVENTS: "FailedMount,MountVolume.SetUpfailed,Failed to pull image,FailedCreate"
    devfileRegistryImage: url.to.my/custom-devfile-registry:latest
    devfileRegistryPullPolicy: latest
    selfSignedCert: false
    tlsSupport: true
  storage:
    postgresPVCStorageClassName: encrypted-xfs
    preCreateSubPaths: true
    pvcClaimSize: 100Gi
    pvcStrategy: per-workspace
    workspacePVCStorageClassName: encrypted-xfs
```

In the above, the tlsSecretName referred to was created by cert-manager using LetsEncrypt.
devFileRegistryImage extends the che default one and adds some custom stacks.
encrypted-xfs is a custom storage class like so:
```
kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: encrypted-xfs
provisioner: kubernetes.io/aws-ebs
volumeBindingMode: WaitForFirstConsumer
parameters:
  type: gp2 
  iopsPerGB: "10" 
  fsType: "xfs"
  encrypted: "true"
```

Additionally, I had to create the following in order for che to be able to create workspaces in a new namespace (if this is no longer necessary in 7.21.2 let me know so i can remove it):
```
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: che-more
  labels:
    app: che
    component: che
rules:
  - verbs:
      - get
      - create
    apiGroups:
      - authorization.openshift.io
      - rbac.authorization.k8s.io
    resources:
      - roles
  - verbs:
      - get
      - update
      - create
    apiGroups:
      - authorization.openshift.io
      - rbac.authorization.k8s.io
    resources:
      - rolebindings
  - verbs:
      - get
    apiGroups:
      - project.openshift.io
    resources:
      - projects
  - verbs:
      - get
      - create
      - watch
    apiGroups:
      - ''
    resources:
      - serviceaccounts
  - verbs:
      - create
    apiGroups:
      - ''
    resources:
      - pods/exec
  - verbs:
      - list
    apiGroups:
      - ''
    resources:
      - persistentvolumeclaims
      - configmaps
  - verbs:
      - list
    apiGroups:
      - apps
    resources:
      - secrets
  - verbs:
      - list
      - create
      - delete
    apiGroups:
      - ''
    resources:
      - secrets
  - verbs:
      - create
      - get
      - watch
    apiGroups:
      - ''
    resources:
      - persistentvolumeclaims
  - verbs:
      - get
      - list
      - create
      - watch
      - delete
    apiGroups:
      - ''
    resources:
      - pods
  - verbs:
      - get
      - list
      - create
      - patch
      - watch
      - delete
    apiGroups:
      - apps
    resources:
      - deployments
  - verbs:
      - list
      - create
      - delete
    apiGroups:
      - ''
    resources:
      - services
  - verbs:
      - create
      - delete
    apiGroups:
      - ''
    resources:
      - configmaps
  - verbs:
      - list
      - create
      - delete
    apiGroups:
      - route.openshift.io
    resources:
      - routes
  - verbs:
      - watch
    apiGroups:
      - ''
    resources:
      - events
  - verbs:
      - list
      - get
      - patch
      - delete
    apiGroups:
      - apps
    resources:
      - replicasets
  - apiGroups:
      - extensions
    resources:
      - ingresses
    verbs:
      - list
      - create
      - watch
      - get
      - delete
  - apiGroups:
      - ''
    resources:
      - namespaces
    verbs:
      - get
      - create
      - list
      - delete
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: che-more
subjects:
- kind: ServiceAccount
  name: che
  namespace: che
roleRef:
  kind: ClusterRole
  name: che-more
  apiGroup: rbac.authorization.k8s.io
```

**Comment by tolusha** [comment]
If `checlusters` CR is deleted then all resources (like secrets, configmaps) will be deleted as well.
Is that your case?

**Comment by guydog28** [comment]
@tolusha No.  Everything exists as it was, I have only done a rolling-update to the cluster to replace the nodes with new nodes using a new K8S version.  I have not deleted the CR or CRD.

**Comment by tolusha** [comment]
Actually I don't know how rolling-update works.
Does it recreate some objects?

**Comment by guydog28** [comment]
It just drains a node (meaning it schedules the pods on that node to be redeployed on a different node), then removes that node, brings up a new updated node and adds it to the cluster, and then allows those pods to be scheduled on it.  Then it moves on to the next node, and so on and so forth.

**Comment by guydog28** [comment]
I guess I should point out that everything else in the cluster came back up as expected after the update except che.  and the errors in che namespace were that the postgres and keycloak pods could not find the secrets che-postgres-secret, che-identity-secret, and che-identity-postgres-secret

**Comment by tolusha** [comment]
I see. I still don't understand why those secrets are removed :(
`kubectl get checlusters eclipse-che -n che`  what is the AGE of the resource? 

Meanwhile it is possible to put all credentials into CR instead of secrets (by default), see the descriptions of those fields for more details:
* https://github.com/eclipse/che-operator/blob/master/deploy/crds/org_v1_che_crd.yaml#L132-L141
* https://github.com/eclipse/che-operator/blob/master/deploy/crds/org_v1_che_crd.yaml#L107-L115
* https://github.com/eclipse/che-operator/blob/master/deploy/crds/org_v1_che_crd.yaml#L199-L208

**Comment by guydog28** [comment]
I can't tell you the age.  I had a dev team that needed to use che, so i had to blow it away and start from scratch. 

putting the credentials there would be plaintext, correct?  I certainly prefer them in the secrets, just wish i could understand why they are disappearing.

**Comment by tolusha** [comment]
Yes, in plain text.

**Comment by tolusha** [comment]
`kubectl get secrets che-identity-secret -n che`:

```
 ownerReferences:
  - apiVersion: org.eclipse.che/v1
    blockOwnerDeletion: true
    controller: true
    kind: CheCluster
    name: eclipse-che
```
So, secret will be deleted automatically if CR is deleted. I don't see another reason for now.
