### ISSUE TITLE
chectl requireing domain flag on che-operator-cr-yaml install

### ISSUE THREAD

**Issue by gnoejuan** [eclipse-che/che#18447]
### Describe the bug

According to https://github.com/che-incubator/chectl/blob/14fd73f22ca7cdef6503a64306f11c727d2e997d/src/commands/server/deploy.ts#L293 , the domain flag should be ignored while deploying with the operator and supplying a cr file.

### Che version

 - [ x ] latest
 - [ ] nightly
 - [ ] other: please specify

### Steps to reproduce

1. `chectl server:deploy --che-operator-cr-yaml=/media/charlesrod/KINGSTON/kubernetes/k8s/che/che-cluster.yaml -a operator -p k8s`

![image](https://user-images.githubusercontent.com/4656027/100108446-67388f80-2e30-11eb-878e-924eff2409ca.png)

### Expected behavior

Domain flag should not be required

### Runtime
   - [ x ] kubernetes (include output of `kubectl version`)
```
Client Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.4", GitCommit:"d360454c9bcd1634cf4cc52d1867af5491dc9c5f", GitTreeState:"clean", BuildDate:"2020-11-16T17:18:52Z", GoVersion:"go1.15.4", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.9+k3s1", GitCommit:"630bebf94b9dce6b8cd3d402644ed023b3af8f90", GitTreeState:"clean", BuildDate:"2020-09-17T19:05:07Z", GoVersion:"go1.13.15", Compiler:"gc", Platform:"linux/amd64"}

```
   - [ ] Openshift (include output of `oc version`)
   - [ ] minikube (include output of `minikube version` and `kubectl version`)
   - [ ] minishift (include output of `minishift version` and `oc version`)
   - [ ] docker-desktop + K8S (include output of `docker version` and `kubectl version`)
   - [ ] other: (please specify)

### Installation method
   - [ x ] chectl
     * provide a full command that was used to deploy Eclipse Che (including the output)
     * provide an output of `chectl version` command: `chectl/7.22.0 linux-x64 node-v10.23.0`
   - [ ] OperatorHub
   - [ ] I don't know

### Environment
   - [ ] my computer
       - [ ] Windows
       - [ x ] Linux
       - [ ] macOS
   - [ ] Cloud
       - [ ] Amazon
       - [ ] Azure
       - [ ] GCE
       - [ x ] other (please specify): k3os
   - [ ] other: please specify

**Comment by tolusha** [comment]
@gnoejuan
Did set
`spec.k8s.ingressDomain` in your cr file ?

**Comment by gnoejuan** [comment]
Yes, here is the yaml with some changes for security's sake

```
apiVersion: org.eclipse.che/v1
kind: CheCluster
metadata:
  name: eclipse-che
spec:
  auth:
    externalIdentityProvider: false
    identityProviderAdminUserName: 'charlesrod'
    identityProviderPassword: '####'
  database:
    externalDb: false
  server:
    selfSignedCert: false
    gitSelfSignedCert: false
#    tlsSupport: true
    serverExposureStrategy: 'single-host'
    workspaceNamespaceDefault: 'default'
  storage:
    pvcStrategy: 'unique'
    pvcClaimSize: '5Gi'
    workspacePVCStorageClassName: "local-path"
    postgresPVCStorageClassName: 'local-path'
#    workspacePVCStorageClassName: "longhorn"
#    postgresPVCStorageClassName: 'longhorn'
  k8s:
    ingressStrategy: 'single-host'
    ingressDomain: 'che-che.url.com'
    tlsSecretName: 'acme-secret-prod'
```
