### ISSUE TITLE
Kube.ts: ClusterIssuer Detection 

### ISSUE THREAD

**Issue by gnoejuan** [eclipse-che/che#18450]
### Describe the bug

https://github.com/che-incubator/chectl/blob/14fd73f22ca7cdef6503a64306f11c727d2e997d/src/api/kube.ts#L1869

It looks like kube.ts doesn't account for other versions. 

![image](https://user-images.githubusercontent.com/4656027/100147026-67508380-2e60-11eb-8ff2-247237408938.png)

I cannot confirm right now, I'm currently chasing a different issue, but here is my current clusterissuer

```yaml
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-prod
spec:
  acme:
    email: user@email.com
    server: https://acme-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      # Secret resource that will be used to store the account's private key.
      name: letsencrypt-prod-key
    solvers:
    - dns01:
        cloudflare:
          email: user@email.com
          apiKeySecretRef:
            name: cloudflare-api-token-secret
            key: api-token
      selector: {}
```

In the task list, a self-signed certificate is queued. 

![image](https://user-images.githubusercontent.com/4656027/100150353-14c59600-2e65-11eb-8a20-672d0e308009.png)

### Che version

 - [ x ] latest
 - [ ] nightly
 - [ ] other: please specify

### Runtime
   - [ x ] kubernetes (include output of `kubectl version`)
   - [ ] Openshift (include output of `oc version`)
   - [ ] minikube (include output of `minikube version` and `kubectl version`)
   - [ ] minishift (include output of `minishift version` and `oc version`)
   - [ ] docker-desktop + K8S (include output of `docker version` and `kubectl version`)
   - [ ] other: (please specify)

### Installation method
   - [ x ] chectl
     * provide a full command that was used to deploy Eclipse Che (including the output)

`chectl server:deploy --che-operator-cr-yaml='/media/charlesrod/KINGSTON/kubernetes/k8s/che/che-cluster.yaml' -a operator -p k8s -b che-che.charlesrod.me`

     * provide an output of `chectl version` command

`chectl/7.22.0 linux-x64 node-v10.23.0`

   - [ ] OperatorHub
   - [ ] I don't know

### Environment
   - [ ] my computer
       - [ ] Windows
       - [ x ] Linux
       - [ ] macOS
   - [ ] Cloud
       - [ ] Amazon
       - [ ] Azure
       - [ ] GCE
       - [ x ] other (please specify): k3os
   - [ ] other: please specify
