### ISSUE TITLE
Eclipse che unable to configure AzureFiles as a static Persistent Volume

### ISSUE THREAD

**Issue by chopraaakash91** [eclipse-che/che#18469]
I am trying to configure Azure Files as a static persistent volume for che workspaces using the document - https://www.eclipse.org/che/docs/che-7/installation-guide/installing-che-using-storage-classes/

I tried the steps mentioned in point#3 - Bind static provisioned volumes using class names

Below is my PV yaml -
```yaml
apiVersion: v1
kind: PersistentVolume
metadata:
  name: che-azurefile
spec:
  capacity:
    storage: 50Gi
  accessModes:
    - ReadWriteMany
  storageClassName: che-azurefile
  azureFile:
    secretName: azure-secret
    shareName: chefileshare
    secretNamespace: cloudspace-akash
    readOnly: false
  mountOptions:
  - dir_mode=0777
  - file_mode=0777
  - uid=1000
  - gid=1000
  - mfsymlinks
  - nobrl
```
Below is my che-cluster CR -
```yaml
apiVersion: org.eclipse.che/v1
kind: CheCluster
metadata:
  name: eclipse-che
spec:
  server:
    workspaceNamespaceDefault: 'cloudspace-akash'
  auth:
    updateAdminPassword: false
  storage:
    workspacePVCStorageClassName: 'che-azurefile'
    pvcClaimSize: '2Gi'
    pvcStrategy: 'common'
```
The PV gets created succesfully.
When i create the WS, the pvc gets into the pending status.

persistentvolumeclaim/claim-che-workspace   Pending                                                                        che-azurefile   14m

Below is the output from describe pvc - 
Events:
```
  Type     Reason              Age                   From                         Message
  ----     ------              ----                  ----                         -------
  Warning  ProvisioningFailed  4m25s (x42 over 14m)  persistentvolume-controller  storageclass.storage.k8s.io "che-azurefile" not found
```
The same PV gets succesully mounted, if I create a PVC manually. Below is the sample pvc yaml (just for testing)
```yaml
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: che-azurefile
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: che-azurefile
  resources:
    requests:
      storage: 5Gi
```
This PVC gets succesfully bound to the PV, but che fails in doing so.
Also, the same steps work fine with Azure Disks.
