### ISSUE TITLE
Error: Failed to run the workspace: "The following containers have terminated: vscode-java25e: reason = 'Completed', exit code = 0, message = 'null'"

### ISSUE THREAD

**Issue by tencent-lu** [eclipse-che/che#18476]
### Describe the bug
My che is running now and can start a workspace with theia-ide. However, failed with other editors, that's disappointing.What's more, no error shows in logs.
### Che Version
7.21.2
### Steps to reproduce
deployed in k8s by chectl in helm way
```bash
chectl deploy:start -a helm -b ide.com -p k8s --multiuser --k8spodreadytimeout=13000000 --k8spodwaittimeout=30000000
```
### Error Report
```
Pulling image "quay.io/eclipse/che-plugin-metadata-broker:v3.4.0"
Successfully pulled image "quay.io/eclipse/che-plugin-metadata-broker:v3.4.0"
Created container che-plugin-metadata-broker-v3-4-0
Started container che-plugin-metadata-broker-v3-4-0
Starting plugin metadata broker
List of plugins and editors to install
- redhat/java/latest - Java Linting, Intellisense, formatting, refactoring, Maven/Gradle support and more...
- che-incubator/intellij-community/latest - IntelliJ IDEA Community Edition running on the Web with noVNC
All plugin metadata has been successfully processed
Pulling image "quay.io/eclipse/che-plugin-artifacts-broker:v3.4.0"
Successfully pulled image "quay.io/eclipse/che-plugin-artifacts-broker:v3.4.0"
Created container che-plugin-artifacts-broker-v3-4-0
Started container che-plugin-artifacts-broker-v3-4-0
Starting plugin artifacts broker
Processing plugin redhat/java/latest
  Installing plugin extension 1/3
    Plugin already downloaded
  Installing plugin extension 2/3
    Plugin already downloaded
  Installing plugin extension 3/3
    Plugin already downloaded
Saving log of installed plugins
All plugin artifacts have been successfully downloaded
Pulling image "quay.io/eclipse/che-java11-maven:7.21.2"
Successfully pulled image "quay.io/eclipse/che-java11-maven:7.21.2"
Created container tools
Started container tools
Pulling image "quay.io/eclipse/che-sidecar-java:11-7bd8c8c"
Successfully pulled image "quay.io/eclipse/che-sidecar-java:11-7bd8c8c"
Created container vscode-java25e
Started container vscode-java25e
Pulling image "quay.io/che-incubator/che-editor-intellij-community:2020.2-0759693"
Successfully pulled image "quay.io/che-incubator/che-editor-intellij-community:2020.2-0759693"
Created container intellij-novnc4d9
Started container intellij-novnc4d9
Pulling image "quay.io/eclipse/che-sidecar-java:11-7bd8c8c"
Error: Failed to run the workspace: "The following containers have terminated:
vscode-java25e: reason = 'Completed', exit code = 0, message = 'null'"
```
Who can give my a hand ? :(

**Comment by tolusha** [comment]
@tencent-lu 
Could you share a devfile which is used to created a workpace.

**Comment by amisevsk** [comment]
@tencent-lu Note also that the `redhat/java/latest` is a Theia plugin, so it'll have no effect if you're using the IntelliJ editor.

**Comment by tencent-lu** [comment]
> @tencent-lu
> Could you share a devfile which is used to created a workpace.

```yaml
apiVersion: 1.0.0
metadata:
  name: java-web-spring-0u18r
projects:
  - name: java-web-spring
    source:
      location: 'https://github.com/spring-projects/spring-petclinic.git'
      type: git
      commitId: 4953f87917b449a404a7f1f4e2457836b9eafbbc
components:
  - id: redhat/java/latest
    memoryLimit: 1512Mi
    preferences:
      java.server.launchMode: Standard
    type: chePlugin
  - mountSources: true
    endpoints:
      - name: 8080-tcp
        port: 8080
    memoryLimit: 768Mi
    type: dockerimage
    volumes:
      - name: m2
        containerPath: /home/user/.m2
    image: 'quay.io/eclipse/che-java11-maven:7.21.2'
    alias: tools
    env:
      - value: ''
        name: MAVEN_CONFIG
      - value: '-XX:MaxRAMPercentage=50.0 -XX:+UseParallelGC -XX:MinHeapFreeRatio=10 -XX:MaxHeapFreeRatio=20 -XX:GCTimeRatio=4 -XX:AdaptiveSizePolicyWeight=90 -Dsun.zip.disableMemoryMapping=true -Xms20m -Djava.security.egd=file:/dev/./urandom -Duser.home=/home/user'
        name: JAVA_OPTS
      - value: $(JAVA_OPTS)
        name: MAVEN_OPTS
  - id: che-incubator/intellij-community/latest
    type: cheEditor
commands:
  - name: maven build
    actions:
      - workdir: '${CHE_PROJECTS_ROOT}/java-web-spring'
        type: exec
        command: mvn clean install
        component: tools
  - name: run webapp
    actions:
      - workdir: '${CHE_PROJECTS_ROOT}/java-web-spring'
        type: exec
        command: |
          java -jar -Xdebug -Xrunjdwp:transport=dt_socket,server=y,suspend=n,address=5005 \
          target/*.jar
        component: tools
  - name: Debug remote java application
    actions:
      - referenceContent: |
          {
          "version": "0.2.0",
          "configurations": [
            {
              "type": "java",
              "name": "Debug (Attach) - Remote",
              "request": "attach",
              "hostName": "localhost",
              "port": 5005
            }]
          }
        type: vscode-launch
```
This is my devfile and it was a sample that I chose in `Get Started`

**Comment by tencent-lu** [comment]
> @tencent-lu Note also that the `redhat/java/latest` is a Theia plugin, so it'll have no effect if you're using the IntelliJ editor.

you mean if I change components.id to Idea's range then it will work?

**Comment by tencent-lu** [comment]
However, I changed my devfile it failed again showing that it failed to connect with server
![image](https://user-images.githubusercontent.com/75114389/100497138-596a6d80-3194-11eb-8136-e7cd065f2868.png)
here is my devfile
```yaml
apiVersion: 1.0.0
metadata:
  name: wksp-custom-6pk0w
components:
  - id: che-incubator/intellij-community/latest
    type: cheEditor
```
and it's disappointing that websocket showed 302
![image](https://user-images.githubusercontent.com/75114389/100497169-89b20c00-3194-11eb-9ee4-b5596eedcc37.png)
