### ISSUE TITLE
Che Theia with low CPU limit doesn't work properly

### ISSUE THREAD

**Issue by l0rd** [eclipse-che/che#18472]
### Describe the bug

This is an example setting 0.4 cores as Theia CPU limit (63 seconds to load Theia, and ports plugin is not even there):

![three](https://user-images.githubusercontent.com/606959/100352244-fee2dd00-2fec-11eb-88ac-bed1a1b496c3.gif)

And another example setting 1.5 cores as Theia CPU limit (18 seconds to load Theia, port plugins included):

![four](https://user-images.githubusercontent.com/606959/100352911-f7700380-2fed-11eb-8fd0-4af877db6ef4.gif)

So 0.4 core is not enough and 1.5 core are fine but probably even with a lower value the bootstrap would be fast. 

In the short term we should:

- Have a rough idea of the minimum value of CPU limit that makes Theia start fast enough
- Specify Theia CPU limit in meta.yaml

In the long term we should (not this issue):

- Benchmark Theia requirements in terms of CPU and memory and have some automated test to verify that
- Have a mechanism to dynamically adapt sidecars CPU limits to the namespace quota: if the cpu limit quota is 10 cores we should make sure that a workspace will use those resources if it needs too.

### Che version

7.2.1

### Steps to reproduce

In this devfile Theia is set with 400m:

```
apiVersion: 1.0.0
metadata:
  name: notenoughcpu
components:
  - cpuLimit: 400m
    id: eclipse/che-theia/next
    type: cheEditor
```

and it can be compared with Theia that has a fair amount of CPU:

```
apiVersion: 1.0.0
metadata:
  name: alotofcpu
components:
  - cpuLimit: 1500m
    id: eclipse/che-theia/next
    type: cheEditor
```

### Runtime

[devsandbox cluster](https://che-toolchain-che.apps.che-dev.x6e0.p1.openshiftapps.com/)

### Additional context

Even if we currently do not explicitly specify Che Theia CPU limit in its `meta.yaml` we can set sidecars (including Theia) CPU limits if through:
- Che property `CHE_WORKSPACE_DEFAULT__CPU__LIMIT__CORES` is set
- The namespace LimitRange `spec.limits[.type == "Container"].default.cpu`

But those values are usually low (0.4 core on devsandbox for example). That's because the sum of sidecars limits has to be lower than the namespace quotas `spec.quota.hard.limit.cpu` (4 cores on devsandbox for example).

Theia bootstrap can be significantly slower and unstable if the CPU is too limited.
