### ISSUE TITLE
CPU request / limit in the plugin meta.yaml is not correctly translated on the k8s level

### ISSUE THREAD

**Issue by ibuziuk** [eclipse-che/che#18484]
### Describe the bug
CPU request in the plugin meta.yaml is not correctly translated on the k8s level

e.g. `cpuRequest: "30m"` is translated to 30 cores (should be either 30m or 0.03):

### Che version
 - [ ] 7.22.0

### Steps to reproduce

devfile to reproduce:
```
metadata:
  name: test-cpulimit22qho
attributes:
  persistVolumes: 'false'
components:
  - type: cheEditor
    reference: >-
      https://gist.githubusercontent.com/sparkoo/cb5105fa1f01f29bf73eb238f6ae622f/raw/090062b9eca6a25ef5226d566ef9626d8a2ca012/theia_meta.yaml
    alias: che-theia
apiVersion: 1.0.0
```

Details in the 
- https://github.com/eclipse/che-plugin-registry/pull/716
- https://github.com/eclipse/che-plugin-registry/pull/716#issuecomment-735729772

### Expected behavior

`cpuRequest: "30m"` is transated to either `30m` or `0.03`

### Runtime
   - Openshift 4.6
