### ISSUE TITLE
Importing several private projects in a single devfile fails

### ISSUE THREAD

**Issue by rromannissen** [eclipse-che/che#18494]
### Describe the bug

I have tried importing a devfile with multiple projects stored in private GitHub repositories using the /f?url= API. The result is that Che fails to clone the repositories without even prompting for the credentials. Only the password request for the last repository is prompted (without previously asking for the user):

![Screenshot from 2020-12-01 10-38-09](https://user-images.githubusercontent.com/15966456/100723957-a5025e80-33c2-11eb-8199-fd1eca009373.png)

After entering the right password, that last clone fails as well and the projects list ends up empty:

![Screenshot from 2020-12-01 10-49-22](https://user-images.githubusercontent.com/15966456/100724295-00cce780-33c3-11eb-9a8d-c292a6173a84.png)

The devfile used to reproduce this error is the following:

```
apiVersion: 1.0.0
metadata:
  name: order-management
projects:
- name: gateway
  source:
    type: git
    location: https://github.com/rromannissen/gateway-crw.git
    branch: master
- name: orders
  source:
    type: git
    location: https://github.com/rromannissen/orders-crw.git
    branch: master
- name: inventory
  source:
    type: git
    location: https://github.com/rromannissen/inventory-crw.git
    branch: master
- name: customers
  source:
    type: git
    location: https://github.com/rromannissen/customers-crw.git
    branch: master
```

### Che version

 - [x] latest
 - [ ] nightly
 - [ ] other: please specify

Che-Theia@5e48d39 using Theia@e2098321a in https://che.openshift.io and Che-Theia@4587314 using Theia@eb1136b11 in CodeReady Workspaces in OCP 4.6.4.

### Steps to reproduce

The devfile used to reproduce this error is the following:

```
apiVersion: 1.0.0
metadata:
  name: order-management
projects:
- name: gateway
  source:
    type: git
    location: https://github.com/rromannissen/gateway-crw.git
    branch: master
- name: orders
  source:
    type: git
    location: https://github.com/rromannissen/orders-crw.git
    branch: master
- name: inventory
  source:
    type: git
    location: https://github.com/rromannissen/inventory-crw.git
    branch: master
- name: customers
  source:
    type: git
    location: https://github.com/rromannissen/customers-crw.git
    branch: master
```

Just import it using the /f?url= API.

### Expected behavior

Che asks for the credentials of each repository and executes the clone correctly for all projects.

### Runtime
   - [ ] kubernetes (include output of `kubectl version`)
   - [x] Openshift (include output of `oc version`)
   - [ ] minikube (include output of `minikube version` and `kubectl version`)
   - [ ] minishift (include output of `minishift version` and `oc version`)
   - [ ] docker-desktop + K8S (include output of `docker version` and `kubectl version`)
   - [ ] other: (please specify)

Reproduced in https://che.openshift.io and CodeReady Workspaces 2.5.0 in OCP 4.6.4.

### Installation method
   - [ ] chectl
     * provide a full command that was used to deploy Eclipse Che (including the output)
     * provide an output of `chectl version` command
   - [x] OperatorHub
   - [ ] I don't know

OperatorHub for CodeReady Workspaces 2.5.0 in OCP 4.6.4. 

### Environment
   - [ ] my computer
       - [ ] Windows
       - [ ] Linux
       - [ ] macOS
   - [ ] Cloud
       - [ ] Amazon
       - [ ] Azure
       - [ ] GCE
       - [x] other (please specify)
   - [ ] other: please specify

Reproduced in https://che.openshift.io and CodeReady Workspaces 2.5.0 in OCP 4.6.4.
