### ISSUE TITLE
Failed to load devfiles meta list --when using external devfile registry

### ISSUE THREAD

**Issue by whafra** [eclipse-che/che#18578]
the enviroment (air-gap ):
OS :ubuntu 18.04.5 LTS
kubernetes version:v1.18.6
eclipse-che version: 7.21.0
install cmd:
chectl server:start --installer=operator --platform k8s --multiuser ....

I have deplyed the eclipse-che successfully .
Now i tried to use external devfile registry and plugin registry .
the following is the my steps :
1) build the airgap offline image 
2) deployed the offline image use the  che-operator-cr-patch.yaml  and success .( refer to https://www.eclipse.org/che/docs/che-7/installation-guide/installing-che-in-a-restricted-environment/)
3) tried the external devfile registry and plugin registry
   I run the command as following in the test machine .
      docker run -it --rm -p 9080:8080  "devfile registry offline image"
      docker run -it --rm -p 7080:8080  "plugin registry offline image"
  and config the che-operator-cr-patch.yaml 
```yaml
   spec:
       server:
            devfileRegistryUrl: http://TEST_IP:9080
            externalDevfileRegistry: true
            externalPluginRegistry: true
            pluginRegistryUrl: http://TEST_IP:7080
```
then, i deploy the che. and the process seems ok.
However ,when i open the main interface ,the  pop-ups shows up  "Failed to load devfiles meta list" .
And i  tried the "load devfile" using  URL ,the content can  be loaded .
So ,how can i solve the problem ?
thank you .
