### ISSUE TITLE
Allow Map of configMap to Keycloak Deployment

### ISSUE THREAD

**Issue by DanArlowski** [eclipse-che/che#18607]
### Is your enhancement related to a problem? Please describe.

When Deploying an Codeready/CHE Deployment using the Operator, a Keycloak is being deployed if not stated otherwise to use external one for secret management, the problem is that when you want to load a Keytab file in order to allow kerberos authentication, when you edit the keycloak deployment, the Operator "catch" the change, reconciles, and remove it.

### Describe the solution you'd like
There should be a way to say in the operator fields something like this:
```yaml
spec:
  auth:
    mountConfigMap(s):
      configMap: <name of configmap>
      path: /path/to/file
      fileName: filename.file

```
the same can be created for secrets of course.

than the operator will add it as `volume`, if present, and as `volumeMount` to the Keycloak/RHSSO deployment

### Describe alternatives you've considered
Alternative solution is load an external Auth management (RH SSO/Keycloak), the problem is the configuration is extremely complicated IMHO, and I couldn't make it to work even with all the fields entered correctly. probably something I'm missing..

### Additional context
A workaround as i stated is to deploy it externally, but even then the fields for implementing it are extremely-not-straight-forward.

I think this option is Must-Have. as CRW/CHE are targeted to be used in enterprises, I think that kerberos authentication is a major must-have functionality, that is being affected by the operator as you cant load a keytab file to the Auth Management, and you have to use an external Keycloak(/RH SSO) which affect ease of use
 
Urgency is rather high, but as it is needed for next week, we will probably use an external key management instead of the out of the box option.

**Comment by tolusha** [comment]
We have a way how to mount secret as a file or an environment variable into a workspace container [1]
I believe we can use the same approach and other Che components (keycloak ,che-server, postgres..)
[1] https://www.eclipse.org/che/docs/che-7/end-user-guide/mounting-a-secret-as-a-file-or-an-environment-variable-into-a-workspace-container/

**Comment by azatsarynnyy** [comment]
I'm setting P2. Feel free to reprioritize it if needed.

**Comment by tolusha** [comment]
@l0rd 
WDYT about this?
https://github.com/eclipse/che/issues/18607#issuecomment-744299924

**Comment by l0rd** [comment]
@tolusha yes absolutely

**Comment by patlachance** [comment]
We also need to be able to mount configMap in **che/codeready** pod as well, for example to customize dashboard branding or control which features to enable or disable (ex: tweaking assets/product.json file).

**Comment by l0rd** [comment]
@patlachance that's a good use case too, we could use that for registries
as well

>

**Comment by skabashnyuk** [comment]
@tolusha how about such format 

```yaml
apiVersion: v1
kind: Secret
metadata:
  name: keycloak-settings-secret
  labels:
    app.kubernetes.io/part-of: che.eclipse.org
    app.kubernetes.io/component: keycloak-secret
  annotations:
    che.eclipse.org/mount-path: /home/user/keycloak/
data:
  somefile.xml: <base64 encoded data content here>
```

```yaml
apiVersion: v1
kind: Secret
metadata:
  name: che-server-settings-secret
  labels:
    app.kubernetes.io/part-of: che.eclipse.org
    app.kubernetes.io/component: che-server-secret
  annotations:
    che.eclipse.org/mount-path: /home/user/che-server/settings/
data:
  somefile.xml: <base64 encoded data content here>  
```

**Comment by DanArlowski** [comment]
Hi guys,
sorry to interrupt:

your solution can work,
but keytab is a necessary file just like you have a specific field for public-certs, and you're not using it from the configmap (in the operator) there should be a specific mount point, for the keytab file something default like: `/etc/krb5/kadm5.keytab`

so like we have the field:

```yaml
...
spec:
  server:
    serverTrustStoreConfigMapName: <TrustStore-CM>
...
```

we should have the field:

```yaml
...
spec: 
  auth:
    authKeytabFileConfigMapName: <keytab-CM>
#OR
    authKeytabFileSecretName: <keytab-Secret>
```

I understand the want to make it atomic for more files, but this should be an easy to use field, that can work concurrently with your proposition, and will make this basic necessity rather easy for the users, instead of deploying Configmaps with specific labels & annotations.

Operator(s) main goal is to make it easier for deploying the application, and additional field in the CRD is easier to use for basic functionality.

if you are an advanced user that need additional maps and secrets in their respective pod your proposition is right, but for the basic user, this should be an easier-to-use functionality.
