### ISSUE TITLE
Investigate if Projector-based IntelliJ Che editor provides some benefits comparing to openVNC we have now

### ISSUE THREAD

**Issue by azatsarynnyy** [eclipse-che/che#18619]
### Is your task related to a problem? Please describe.
JetBrains provides a server-side library for running Swing applications remotely
https://github.com/JetBrains/projector-server/blob/master/docs/Projector.md
and a set of scripts to run a Docker container with Projector-based IntelliJ IDE
https://github.com/JetBrains/projector-docker

It may provide some benefits comparing to openVNC solution we're using now.

### Describe the solution you'd like
Investigate if Projector-based IntelliJ Che editor could provide some benefits comparing to the currently used openVNC solution.

**Comment by azatsarynnyy** [comment]
Projector is GA now https://blog.jetbrains.com/blog/2021/03/11/projector-is-out/

**Comment by l0rd** [comment]
I have raised the severity to P1. That’s because JetBrains officially support running their IDEs in containers/kube now. And it makes much more sense for us to provide first class integration then.

**Comment by azatsarynnyy** [comment]
@vzhukovs please provide a Devfile to test the Projector-based IDEA Che editor as soon as you get it.

**Comment by azatsarynnyy** [comment]
Related upstream issue https://youtrack.jetbrains.com/issue/PRJ-413 and PR https://github.com/JetBrains/projector-client/pull/19

**Comment by azatsarynnyy** [comment]
WIP PR https://github.com/che-incubator/jetbrains-editor-images/pull/21

**Comment by azatsarynnyy** [comment]
@vzhukovs could you describe the benefits of Projector-based solution comparing to openVNC, if there's any

**Comment by vzhukovs** [comment]
>Related upstream issue https://youtrack.jetbrains.com/issue/PRJ-413 and PR JetBrains/projector-client#19

Yep. The main problem which was related to Projector Client is not handling any key events, when client is opened inside iframe. This is because the bowser security limitations. According to specification [Privacy Mitigations](https://wicg.github.io/keyboard-map/#privacy-mitigations) any calls to Keyboard API should be called directly from the top-level browsing context because of security checks provided by the browser. See also [top level browsing context](https://html.spec.whatwg.org/multipage/browsers.html#top-level-browsing-context) and [secure context](https://html.spec.whatwg.org/multipage/webappapis.html#secure-context). So, in a few words, the html snippet won't work:

```html
<!DOCTYPE html>
<html lang="en">
<head>
    <title>Projector web client inside iframe</title>
</head>
<body>
    <iframe src="http://localhost:8887" style="width: 1024px; height: 720px; padding: 10px; background: black"></iframe>
</body>
</html>
```

This is the main problem, because the IDE window opens inside iframe. But, there is a workaround. Forked repository [contains the fix](https://github.com/JetBrains/projector-client/pull/19) for this use case. Waiting for the PR review.

On the other hand, there is an ability to clone forked [projector-client](https://github.com/vzhukovs/projector-client/tree/PRJ-413) and upstream [projector-server](https://github.com/JetBrains/projector-server), link them into single build and provide fixed bundle to docker build, which is performed in the following script: [clone-projector.sh](https://github.com/che-incubator/jetbrains-editor-images/blob/projector/clone-projector.sh).

So, the main work is performed under WIP PR: https://github.com/che-incubator/jetbrains-editor-images/pull/21

I've prepared a few workspace configurations, with different JetBrains IDEs:

- PyCharm Community 2020.3.5:
```yaml
apiVersion: 1.0.0
metadata:
  name: projector-pycharm-c
components:
  - type: cheEditor
    reference: 'https://gist.github.com/vzhukovs/a0358b1a4eff61b9248b57c430965767/raw/3d9b0838843402e2050a5fe2101e0131f6101ef8/che-projector-pycharm-c.yaml'
    alias: projector-pycharm-c
```

- PyCharm Professional 2020.3.5:
```yaml
apiVersion: 1.0.0
metadata:
  name: projector-pycharm-p
components:
  - automountWorkspaceSecrets: true
    type: cheEditor
    reference: 'https://gist.github.com/vzhukovs/f0e539c8a486497ea0947e95ae898e4b/raw/b2378eb6b314eb9dd2ca60cafc58c11791f70f9d/che-projector-pycharm-p.yaml'
    alias: projector-pycharm-p
```

- WebStorm 2020.3.3:
```yaml
apiVersion: 1.0.0
metadata:
  name: projector-webstorm
components:
  - automountWorkspaceSecrets: true
    type: cheEditor
    reference: 'https://gist.github.com/vzhukovs/7e953144a98a1a573eec421e8e2db637/raw/96c6e4b374943c72f26a1aa21a2673fbb987e8bc/che-projector-webstorm.yaml'
    alias: projector-webstorm
```

- IntelliJ IDEA Community 2020.3.3:
```yaml
apiVersion: 1.0.0
metadata:
  name: projector-idea-c
components:
  - type: cheEditor
    reference: 'https://gist.github.com/vzhukovs/1136ae609f19b6898affd3e4b3accf8d/raw/c0cb0e7815edd5ccdeb984146a68c29ceaf356ef/che-projector-idea-c.yaml'
    alias: projector-idea-c
```

- IntelliJ IDEA Ultimate 2020.3.3:
```yaml
apiVersion: 1.0.0
metadata:
  name: projector-idea-u
components:
  - automountWorkspaceSecrets: true
    type: cheEditor
    reference: 'https://gist.github.com/vzhukovs/7a398422ec361d5c2ec785b55c1c95e8/raw/1fc786a5c781b3ec618739778036df912bddf2dd/che-projector-idea-u.yaml'
    alias: projector-idea-u
```

If you want to provide the offline activation code for IDEA Ultimate or WebStorm, then you need to create a secret:
```yaml
apiVersion: v1
kind: Secret
metadata:
  name: jetbrains-offline-activation-code
  labels:
    app.kubernetes.io/component: workspace-secret
    app.kubernetes.io/part-of: che.eclipse.org
  annotations:
    che.eclipse.org/automount-workspace-secret: 'false'
    che.eclipse.org/mount-path: /tmp/
    che.eclipse.org/mount-as: file
data:
  idea.key: <base64 encoded data content here>
  webstorm.key: <base64 encoded data content here>
  pycharm.key: <base64 encoded data content here>
```
Don’t forget to remove not needed key to provide the offline activation code, if you run only one IDE. This is just an example how to provide several activation keys.

A few words, from the pros of using Projector:

- no need to run a desktop environment. Projector runs in headless mode, so `fedora:32` for the community image version and ubi8-minimal for the CRW based images will be enough.
- no need to install VNC-related stuff, like tigerVNC and noVNC (less third-party dependencies)
- rendering of the UI is performed by Projector Client, so UI stuff is the same as it would be run on the desktop environment (I mean, we get rid of smoothing effect from using VNC)
- easy way to set up https for endpoint (disabled by default in current implementation)
- flexible configuration of Projector Client
- ability to run any JetBrains based IDE, like Android Studio(at least, JetBrains declares that it is possible)
- one way to organize a single Dockerfile for different type of IDE (PyCharm, IntelliJ IDEA, WebStorm, etc.)
- easy to maintain the whole build infrastructure, because it is possible to make a contributions to Projector Client and Projector Server repository

Cons:

- requires JDK 11 to build the Projector (minor cons, but anyway)

cc @azatsarynnyy @l0rd
