### ISSUE TITLE
Investigate if Che-theia is providing the right path for vscode.extensions.getExtension(extensionId)..extensionPath

### ISSUE THREAD

**Issue by sunix** [eclipse-che/che#18632]
### Describe the bug
Testing the lombok extension with
```yaml
apiVersion: v2
publisher: cool2k
name: vscode-lombok
version: latest
type: VS Code extension
displayName: Lombok Annotations Support for VS Codium
title: Lombok Annotations Support for VS Codium
description: A lightweight extension to support Lombok annotations processing in Visual
  Studio Code (published to open-vsx by cool2k)
icon: /v3/images/cool2k-vscode-lombok-icon.png
category: Other
repository: https://github.com/GabrielBB/vscode-lombok.git
firstPublicationDate: '2020-07-01'
spec:
  containers:
    - image: quay.io/eclipse/che-plugin-sidecar:java-b8f0528
      name: vscode-lombok
      volumes:
        - name: m2
          mountPath: /home/theia/.m2
      memoryLimit: 2Gi
  extensions:
    - https://open-vsx.org/api/cool2k/vscode-lombok/1.0.2/file/cool2k.vscode-lombok-1.0.2.vsix
    - https://download.jboss.org/jbosstools/static/jdt.ls/stable/java-0.69.0-2547.vsix
    - https://download.jboss.org/jbosstools/vscode/3rdparty/vscode-java-debug/vscode-java-debug-0.26.0.vsix
    - https://open-vsx.org/api/vscjava/vscode-java-test/0.24.0/file/vscjava.vscode-java-test-0.24.0.vsix
latestUpdateDate: "2020-12-16"
```

the Java language server can't start.
```
Error opening zip file or JAR manifest missing : /tmp/vscode-unpacked/lombok.jar
[Info  - 4:55:06 PM] Connection to server got closed. Server will restart.
Error opening zip file or JAR manifest missing : /tmp/vscode-unpacked/lombok.jar
[Info  - 4:55:06 PM] Connection to server got closed. Server will restart.
Error opening zip file or JAR manifest missing : /tmp/vscode-unpacked/lombok.jar
[Info  - 4:55:06 PM] Connection to server got closed. Server will restart.
Error opening zip file or JAR manifest missing : /tmp/vscode-unpacked/lombok.jar
[Info  - 4:55:06 PM] Connection to server got closed. Server will restart.
Error opening zip file or JAR manifest missing : /tmp/vscode-unpacked/lombok.jar
[Error - 4:55:06 PM] Connection to server got closed. Server will not be restarted.
```

The lombok.jar is located elsewhere:
```
/projects $ cd /tmp/
/tmp $ find -name "lombok.jar"
./vscode-unpacked/cool2k.vscode-lombok.latest.djbmbyzfnu.cool2k.vscode-lombok-1.0.2.vsix/extension/server/lombok.jar
/tmp $ 
```

This is working in Che: https://github.com/microsoft/vscode-java-debug/blob/master/package.json#L49-L51
```
    "javaExtensions": [
      "./server/com.microsoft.java.debug.plugin-0.29.0.jar"
    ],
```
But maybe something is wrong here for the lombok extension: https://github.com/GabrielBB/vscode-lombok/blob/6b3b150b5780d48368d2864876ba1856349c568d/src/lombok-installer.ts#L26
```
export const getJarPath = () => path.join(getExtensionInstance().extensionPath, "server", "lombok.jar");
```

The goal of this issue is to investigate and compare with VSCode.

**Comment by benoitf** [comment]
would be interesting to compare `vscode.extensions.getExtension(extensionId).extensionPath` result across VS Code/Theia/Che-Theia

**Comment by benoitf** [comment]
also most of extensions are using `ExtensionContext.extensionPath`

**Comment by gattytto** [comment]
[this devfile](https://github.com/eclipse/che-devfile-registry/pull/316) illustrates the steps needed. 

One is to pass the setting to the Java extension, wether it's in the same meta.yaml(quarkus) or in a separate plugin (my proposal pr for Lombok)

The second step is to make a mount shared by both extensions in which (in the third step) the Lombok engine jar gets copied after its unpacked from the vsix extension. 

I don't think bundling the Lombok extension with Java ones in the same meta.yaml is a proper fix because it adds having to maintain extensions vsix version updates for both standalone Java meta.yaml and all others like quarkus or Lombok.

About the subject of this issue, this extension code checks the existence of the jar within its own context which is valid once the vsix is unpacked and initialized, but this code:"  await getWorkspaceConfig().update(VM_ARGS_KEY, value, ConfigurationTarget.Global);" is the one that should work, expected that Java extension actually makes use of it

**Comment by gattytto** [comment]
> ### Describe the bug
> Testing the lombok extension with
> ...
> the Java language server can't start.

this is because the previous setting from my proposed devfile and tests is persisted in /home/theia/.theia/settings.json, so the new option added by the extension is put AFTER the previously persisted one. Getting rid of that option in the che osio /home/theia/.theia/settings.json and starting a new workspace with:
````yaml
apiVersion: 1.0.0
metadata:
  name: Lombok
projects:
  - name: iot-core
    source:
      location: 'https://github.com/chuucks/LOMBOK-PROJECT-EXAMPLE'
      type: git
      branch: master
components:
  - type: chePlugin
    reference: >-
      https://raw.githubusercontent.com/gattytto/cheplugins/master/lombok/1.0.1/meta2.yaml
    alias: lombok
  - id: eclipse/che-theia/next
    type: cheEditor
````

works as expected and settings.json gets:
````json
"java.jdt.ls.vmargs": "-XX:+UseParallelGC -XX:GCTimeRatio=4 -XX:AdaptiveSizePolicyWeight=90 -Dsun.zip.disableMemoryMapping=true -Xmx1G -Xms100m -javaagent:\"/tmp/vscode-unpacked/cool2k.vscode-lombok.latest.mkrvmqkxpm.cool2k.vscode-lombok-1.0.2.vsix/extension/server/lombok.jar\""
````
