### ISSUE TITLE
Failure to clone zip projects when using OpenShift trusted CA bundle

### ISSUE THREAD

**Issue by l0rd** [eclipse-che/che#18654]
### Describe the bug

Theia uses `curl` to download projects zip files. When a zip file is hosted on a server that uses a TLS cert signed by an untrusted CA `curl` fails to download the file. That's normal.

But if Che is running on OpenShift and the CA certificate is added into OpenShift CA trusted bundle ([as described here](https://docs.openshift.com/container-platform/4.4/networking/configuring-a-custom-pki.html#nw-proxy-configure-object_configuring-a-custom-pki)) `curl` should not fail anymore. The certificates are correctly mounted in the container where `curl` runs (theia container) but `curl` doesn't take them into account.

This is the error:

```
Couldn't import https://devfile-registry-cip-crw-common.apps.xxxxx.com/resources/spring-boot-http-booster-spring-boot-http-booster-sb-2.3.x.zip:
curl: (60) SSL certificate problem: unable to get local issuer certificate More details here: https://curl.haxx.se/docs/sslcerts.html
curl failed to verify the legitimacy of the server and therefore could not establish a secure connection
to it. To learn more about this situation and how to fix it,
please visit the web page mentioned above.
```

### Che version

nightly

### Steps to reproduce

N/A

### Expected behavior

[Currently](https://github.com/eclipse/che-theia/blob/master/plugins/workspace-plugin/src/theia-commands.ts#L246) Theia looks for an hardcoded crt file (`/tmp/che/secret/ca.crt`) and if it founds runs curl with the unsecure option `-k`. The problem is that `crt` files are currently mounted in folder `/public-certs` and we should avoid using `curl` option `-k` anyway.

### Runtime

OpenShift

### Installation method

OperatorHub

### Environment

Cloud

**Comment by l0rd** [comment]
A workaround is to pre-create a secret in the workspace namespace so that Che will inject file `/tmp/che/secret/ca.crt` in every workspace container such as:

```yaml
apiVersion: v1
kind: Secret
metadata:
  name: file-to-inject
  annotations:
    "che.eclipse.org/automount-workspace-secret": "true"
    "che.eclipse.org/mount-path": "/tmp/che/secret"
    "che.eclipse.org/mount-as": file
  labels:
    app.kubernetes.io/part-of: che.eclipse.org
    app.kubernetes.io/component: workspace-secret
data:
  ca.crt: "bWlubmllCg=="
```
