### ISSUE TITLE
Expand support of devfile v2 in Che to include definition of Editors and Theia Plugins

### ISSUE THREAD

**Issue by l0rd** [eclipse-che/che#18668]
### Is your enhancement related to a problem? Please describe.

[Devfile plugins are not suited to specify che-theia plugins](https://github.com/eclipse/che/issues/18669).

### Describe the solution you'd like

Beyond recommendations in `.vscode/extensions.json`(covered by [this issue](https://github.com/eclipse/che/issues/18274)) Che workspaces should support those configuration files in `.che` folder:

```
.che
  |--- che-theia-plugins.yaml
  |___ che-editor.yaml
```

And it should be possible to inline those files as annotations in a devfile (there is [a separate issue for that](https://github.com/eclipse/che/issues/16994)):

```yaml
schemaVersion: 2.0.0
attributes:
  che-editor.yaml:
    <yaml content>
  che-theia-plugins.yaml:
    <yaml content>
```

### Additional context

Editors and theia plugins, can be specified in 3 different ways in a `che-editor.yaml` or `che-theia.yaml` file:

- **by id**: the definition is in the Che plugin registry and referenced by the `id` field (mandatory)
- **by url**: the definition is published at the URL specified in the `reference` field (mandatory)
- **inline**: the spec is provided inline

#### Che Theia Plugin Definition Syntax

A Che Theia plugin is specified using the file [che-theia-plugins.yaml of the che-plugin-registry](https://github.com/eclipse/che-plugin-registry/blob/master/che-theia-plugins.yaml) syntax.

#### Che Editor Definition Syntax

A Che editor is specified using the file [che-editors.yaml](https://github.com/eclipse/che-plugin-registry/blob/master/che-editors.yaml) syntax (but we should [move che-editors to devfile v2 syntax](https://github.com/eclipse/che/issues/19034))

#### Overriding fields

Overriding of a registry or web reference is allowed through json merge patch.

##### che-editor.yaml

```yaml
# Contains the spec of just ONE editor. 
# Here I am providing 3 examples separted with ---
---
# EXAMPLE 1 - registry reference
id: eclipse/che-theia/nigthly         # mandatory
registryUrl: https://my-registry.com  # optional
override:                             # optional
  containers:
    - name: theia-ide
      memoryLimit: 1280Mi
---
# EXAMPLE 2 - web reference
reference: https://gist.github.com/.../che-editor.yaml # mandatory
override:                                              # optional
  containers:
      - name: theia-ide
        memoryLimit: 1280Mi 
---
# EXAMPLE 3 - inline
inline:        # <--- that's current syntax of https://github.com/eclipse/che-plugin-registry/blob/master/che-editors.yaml
               #      but we should use devfile v2 instead 
  endpoints:
    - name: "theia"
      public: true
      targetPort: 3100
      attributes:
        protocol: http
        type: ide
        secure: true
        cookiesAuthEnabled: true
        discoverable: false
    (...)
  containers:
    - name: theia-ide
      image: "quay.io/eclipse/che-theia:next"
      env:
        - name: THEIA_PLUGINS
          value: local-dir:///plugins
      volumeMounts:
        - name: plugins
          path: "/plugins"
        - name: theia-local
          path: "/home/theia/.theia"
      mountSources: true
      ports:
        - exposedPort: 3100
      memoryLimit: "512M"
      cpuLimit: 1000m
      cpuRequest: 100m
  initContainers:
    - name: remote-runtime-injector
      image: "quay.io/eclipse/che-theia-endpoint-runtime-binary:next"
      volumeMounts:
        - name: remote-endpoint
          path: "/remote-endpoint"
          ephemeral: true
      env:
        - name: PLUGIN_REMOTE_ENDPOINT_EXECUTABLE
          value: /remote-endpoint/plugin-remote-endpoint
        - name: REMOTE_ENDPOINT_VOLUME_NAME
          value: remote-endpoint
```

##### che-theia-plugins.yaml

```yaml
- id: redhat/java8/latest               # mandatory 
  registryUrl: https://my-registry.com  # optional 
  override:                             # optional 
    sidecar:
      memoryLimit: 1280Mi
- reference: https://gist.github.com/.../che-theia-plugin.yaml # mandatory 
  override:                                                    # optional 
    sidecar:
      memoryLimit: 1280Mi 
- inline:       # <--- same syntax as https://github.com/eclipse/che-plugin-registry/blob/master/che-theia-plugins.yaml
    sidecar:
      image: 'quay.io/eclipse/che-plugin-sidecar:go-c939ba4'
      name: vscode-go
      memoryLimit: 512Mi
      env:
        - name: GOPATH
           value: '/go:$(CHE_PROJECTS_ROOT)'
      extensions:
        - 'https://github.com/golang/vscode-go/releases/download/v0.16.1/go-0.16.1.vsix'
```

#### Subtasks

- [x] [Provides high-level library for managing DevWorkspace objects for clients](https://github.com/eclipse/che/issues/18402)
- [x] [Allow resolver API to resolve other files than [.]devfile.yaml](https://github.com/eclipse/che/issues/19540)
- [x] [Generate fragment / che-theia-plugin.yaml for each plug-in in the registry](https://github.com/eclipse/che/issues/19545)
- [x] Dashboard should resolve editor and plugins from repo during factory flow https://github.com/eclipse/che/issues/19927
- [x] Support of definitions in `.che/*.yaml` files
	- Support for `.che/che-theia-plugins.yaml` files
		- che server
		- dashboard
		- che-devworkspace-client
	- Support for `.che/che-editor.yaml` file
		- che server
		- dashboard
		- che-devworkspace-client
- [x] Inline definition support ([issue](https://github.com/eclipse/che/issues/16994)):
	- Support for `che-theia-plugins.yaml` devfile attribute
		- dashboard
		- che-devworkspace-client
	- Support for `che-editor.yaml` devfile attribute
		- dashboard
		- che-devworkspace-client
- [ ] Adapt QE tests

**Comment by sleshchenko** [comment]
Is `che/che-theia-plugins.yaml` supposed to be just a recommendation as well?
Like the following use-case `vscode/extensions.json`:
```json
{
   "recommendations": [
       "redhat.java"
   ]
}
```
`.che/che-theia-plugins.yaml`
```
recommendations:
- id: redhat/java8/latest
  sidecar:
    memoryLimit: 1280Mi
```
Theia detects both files and proposes a user to:
- to enable redhat java
  - the recommended configuration(1280);
  - or default (that came from registry);
- or procced without recommended extensions.
