### ISSUE TITLE
How to modify dash board contens?

### ISSUE THREAD

**Issue by codingmeee** [eclipse-che/che#18675]
## Relevant information

I had made of dashboard images modified (i already testes localhost:3000)

I modified dockerfiles/che/Dockerfile of eclipse/che git as bottom

ARG CHE_DASHBOARD_ORGANIZATION=codingmeee.com:4567/eclipse
ARG CHE_DASHBOARD_NEXT_ORGANIZATION=codingmeee.com:4567/eclipse
ARG CHE_DASHBOARD_VERSION=0.0.1
ARG CHE_DASHBOARD_NEXT_VERSION=0.0.1
ARG CHE_WORKSPACE_LOADER_ORGANIZATION=codingmeee.com:4567/eclipse
ARG CHE_WORKSPACE_LOADER_VERSION=0.0.1

and ,I executed this command ./build.sh --organization:codingmeee.com/eclipse --tag:0.0.1 --dockerfile:Dockerfile

But, after executing this command(sudo chectl server:deploy -n che --platform=minikube -m --che-operator-cr-yaml=che-custom.yaml) 
<che-custom.yaml>
cheImage: 'codingmeee.com/eclipse/che-server'

I can not see changed contents. 

How to modify dashboard contents???

**Comment by ibuziuk** [comment]
@sleshchenko @olexii4 folks, could you please take this one?

**Comment by sleshchenko** [comment]
Hello, @codingmeee
instead of modifying arguments in the source code, you should be able to set them for build.sh, like the following:
```sh
./build.sh --organization:codingmeee.com/eclipse --tag:0.0.1 \
  --build-arg:CHE_DASHBOARD_NEXT_ORGANIZATION=codingmeee.com:4567/eclipse --build-arg:CHE_DASHBOARD_NEXT_VERSION=0.0.1 \
  --build-arg:CHE_DASHBOARD_ORGANIZATION=codingmeee.com:4567/eclipse --build-arg:CHE_DASHBOARD_VERSION=0.0.1 \
  --build-arg:CHE_WORKSPACE_LOADER_ORGANIZATION=codingmeee.com:4567/eclipse --build-arg:CHE_WORKSPACE_LOADER_VERSION=0.0.1 \
  --dockerfile:Dockerfile
```

but it's not related to issue you face.
Could you provide the full yaml content che-custom.yaml? It is
just 
```yaml
cheImage: 'codingmeee.com/eclipse/che-server'
```
if yes - it's the reason. It should be like the following:
```yaml
spec:
  server:
    cheImage: 'codingmeee.com/eclipse/che-server'
    cheImageTag: '0.0.1'
    cheImagePullPolicy: Always
```
 ^ instead of redeploying Che, you should be able to provision the following values into `kubectl edit checluster eclipse-che -n che`

**Comment by codingmeee** [comment]
Thank you for reply my question.
But, Unfortunally, If i use che Image Pull Policy option,  i can not execute chectl.

Errror message
```bash
 → Failed to download image, reason: ImagePullBackOff, message: Back-off pulling image "codingmeee.com/eclipse/che-server:0.0.1".
```

And my che-custom.yaml is same as follow.
```YAML
apiVersion: org.eclipse.che/v1
kind: CheCluster
metadata:
  name: eclipse-che
spec:
  server:
    # server image used in Che deployment
    cheImage: 'codingmeee.com/eclipse/che-server'
    # tag of an image used in Che deployment
    cheImageTag: '0.0.1'
    # cheImagePullPolicy: Always
    # image:tag used in Devfile registry deployment
    devfileRegistryImage: 'codingmeee.com/eclipse/che-devfile-registry:0.0.1'
    # image:tag used in plugin registry deployment
    pluginRegistryImage: 'quay.io/eclipse/che-plugin-registry:nightly'
    # defaults to `che`. When set to `codeready`, CodeReady Workspaces is deployed
    # the difference is in images, labels, exec commands
    cheFlavor: ''
    # when set to true the operator will attempt to get a secret in OpenShift router namespace
    # to add it to Java trust store of Che server. Requires cluster-admin privileges for operator service account
    selfSignedCert: false
    # TLS mode for Che. Make sure you either have public cert, or set selfSignedCert to true
    tlsSupport: false
    # protocol+hostname of a proxy server. Automatically added as JAVA_OPTS and https(s)_proxy
    # to Che server and workspaces containers
    proxyURL: ''
    # port of a proxy server
    proxyPort: ''
    # username for a proxy server
    proxyUser: ''
    # password for a proxy user
    proxyPassword: ''
    # a list of non-proxy hosts. Use | as delimiter, eg localhost|my.host.com|123.42.12.32
    nonProxyHosts: ''
  database:
    # when set to true, the operator skips deploying Postgres, and passes connection details of existing DB to Che server
    # otherwise a Postgres deployment is created
    externalDb: false
    # Postgres deployment in format image:tag. Defaults to registry.redhat.io/rhscl/postgresql-96-rhel7 (see pkg/deploy/defaults.go for latest tag)
    postgresImage: 'codingmeee.com/eclipse/che-postgres:0.0.1'
  storage:
    # persistent volume claim strategy for Che server. Can be common (all workspaces PVCs in one volume),
    # per-workspace (one PVC per workspace for all declared volumes) and unique (one PVC per declared volume). Defaults to common
    pvcStrategy: 'per-workspace'
    # size of a persistent volume claim for workspaces. Defaults to 1Gi
    pvcClaimSize: '1Gi'
    # instruct Che server to launch a special pod to precreate a subpath in a PV
    preCreateSubPaths: true
    # image:tag for preCreateSubPaths jobs
    #pvcJobsImage: 'quay.io/nickboldt/airgap-ubi8-minimal:nightly'
  auth:
    # instructs operator on whether or not to deploy Keycloak/RH SSO instance. When set to true provision connection details
    externalIdentityProvider: false
    # retrieved from respective route/ingress unless explicitly specified in CR (when ExternalKeycloak is true)
    # instructs an Operator to enable OpenShift v3 identity provider in Keycloak,
    # as well as create respective oAuthClient and configure Che configMap accordingly
    openShiftoAuth: false
    # image:tag used in Keycloak deployment
    identityProviderImage: 'codingmeee.com/eclipse/che-keycloak:0.0.1'
  k8s:
    # your global ingress domain
    ingressDomain: '192.168.49.2.nip.io'
  metrics:
    enable: true
```
