### ISSUE TITLE
CODE-SERVER Issue.

### ISSUE THREAD

**Issue by Manou80096** [eclipse-che/che#18686]
### Describe the bug

 We are using code-server in Eclipse Che. We were able to clone the code from the git repository, but whenever we are stopping and starting the workspace the code is lost. We will have to clone it again. 
Also, we were not able to open the maven terminal which is attached to the same workspace.
Dev file posted below for reference.

https://mattermost.eclipse.org/eclipse/pl/r9gwgtgxjjndxrm4kw5y3e5rac

### Che version

Version: 7.23 and 7.22

### Steps to reproduce

1. Create a new workspace with a code-server using below devfile.
```yaml
apiVersion: 1.0.0
metadata:
  name: vscode
projects:
  - name: ###
    source:
      location: '#####'
      type: git
      branch: ####
components:
  - id: cdr/code-server/latest
    type: cheEditor
    env:
      - value: '1234'
        name: PASSWORD
  - mountSources: true
    endpoints:
      - attributes:
          public: 'false'
        name: debug
        port: 5005
    memoryLimit: 512Mi
    type: dockerimage
    volumes:
      - name: m2
        containerPath: /home/user/.m2
    image: 'quay.io/eclipse/che-java11-maven:nightly'
    alias: maven
    env:
      - value: ''
        name: MAVEN_CONFIG
      - value: '-XX:MaxRAMPercentage=50 -XX:+UseParallelGC -XX:MinHeapFreeRatio=10 -XX:MaxHeapFreeRatio=20 -XX:GCTimeRatio=4 -XX:AdaptiveSizePolicyWeight=90 -Dsun.zip.disableMemoryMapping=true -Xms20m -Djava.security.egd=file:/dev/./urandom -Duser.home=/home/user'
        name: MAVEN_OPTS
      - value: '-XX:MaxRAMPercentage=50 -XX:+UseParallelGC -XX:MinHeapFreeRatio=10 -XX:MaxHeapFreeRatio=20 -XX:GCTimeRatio=4 -XX:AdaptiveSizePolicyWeight=90 -Dsun.zip.disableMemoryMapping=true -Xms20m -Djava.security.egd=file:/dev/./urandom'
        name: JAVA_OPTS
      - value: '-XX:MaxRAMPercentage=50 -XX:+UseParallelGC -XX:MinHeapFreeRatio=10 -XX:MaxHeapFreeRatio=20 -XX:GCTimeRatio=4 -XX:AdaptiveSizePolicyWeight=90 -Dsun.zip.disableMemoryMapping=true -Xms20m -Djava.security.egd=file:/dev/./urandom'
        name: JAVA_TOOL_OPTIONS
commands:
  - name: maven build
    actions:
      - workdir: '${CHE_PROJECTS_ROOT}/SkMateChe'
        type: exec
        command: mvn clean install
        component: maven
```
2. Clone any sample code from a git repository.
3. Try opening a Maven terminal - not working
4. stop and restart the workspace. - code will be lost, have to clone again.

### Expected behavior

1. Code should be available persistently even after restarting the workspace.
2. We should be able to access the maven container terminal.

### Runtime
Kubernetes running on GCP.
kubectl version - v1.16.15

### Installation method

 Command used to deploy: chectl server:start --installer=helm --platform=k8s --domain=sk.t4testing.com --multiuser
 Chectl version: chectl/0.0.20201015-next.e71b2f8 win32-x64 node-v10.22.1

### Environment
   - [ ] Cloud
       - [ ] GCE
