### ISSUE TITLE
Make Bitbucket's sensitive configuration file-based

### ISSUE THREAD

**Issue by skabashnyuk** [eclipse-che/che#18710]
### Is your task related to a problem? Please describe.

At this moment `CHE_OAUTH1_BITBUCKET_CONSUMERKEY` and `CHE_OAUTH1_BITBUCKET_PRIVATEKEY` configured as environment variables
or configuration properties. We would like to move these values to the file to make them more secured.

### Describe the solution you'd like

Sensitive configuration should be configured with Secrets and mounted  https://github.com/eclipse/che-operator/pull/595 with che-operator as a file to che-server container.
Example:
```yaml
apiVersion: v1
kind: Secret
metadata:
  name: che-server-settings-secret
  labels:
    app.kubernetes.io/part-of: che.eclipse.org
    app.kubernetes.io/component: che-secret
  annotations:
    che.eclipse.org/mount-path: /home/user/che-server/settings/
data:
  bitbucket_consumer_key: <base64 encoded data content here>  
  bitbucket_private_key: <base64 encoded data content here>  
```
```java
  @Inject
  public BitbucketServerOAuthAuthenticator(
      @Named("/home/user/che-server/settings/bitbucket_consumer_key") File consumerKey,
      @Named("/home/user/che-server/settings/bitbucket_private_key") File privateKey,
      @Named("che.oauth1.bitbucket.endpoint") String bitbucketEndpoint,
      @Named("che.api") String apiEndpoint) {
    super
```

TBD 
 1. Concrete `che.eclipse.org/mount-path`
 2. ```@Named("file:/home/user/che-server/settings/bitbucket_private_key") String privateKey``` - injection of file values.
 3. `che.oauth1.bitbucket.endpoint` - configure with file too.

### Describe alternatives you've considered
n/a
### Additional context
https://github.com/eclipse/che/issues/18385
