### ISSUE TITLE
Ability to mount more than one Git credential secret

### ISSUE THREAD

**Issue by mshaposhnik** [eclipse-che/che#18721]
### Is your task related to a problem? Please describe.
Right now, having Git credential secret in form:

```
apiVersion: v1
kind: Secret
metadata:
  name: git-credentials-secret
  labels:
    app.kubernetes.io/part-of: che.eclipse.org
    app.kubernetes.io/component: workspace-secret
  annotations:
    che.eclipse.org/automount-workspace-secret: 'true'
    che.eclipse.org/mount-path: /home/theia/.git-credentials
    che.eclipse.org/mount-as: file
    che.eclipse.org/git-credential: 'true'
data:
  credentials: <https://user:pass@example.com in Base64 > 
```

will result in file mount to each container:

**_/home/theia/.git-credentials/credentials_**

```
https://user:pass@example.com
``` 

But if we want to have more than one credential secret, for example, one for GitHub and one for Bitbucket, 
secret provisioner will fail. We need to fix that situation.

### Describe the solution you'd like
Right now we're not managing content of the files, we just creating volume mount poining to the secret, which will be mount as file on FS by Kubernetes. 
So `GitCredentialStorageFileSecretApplier` should be reworked and allow multiple secrets to be merged into single credential file which will lools like:

**_/home/theia/.git-credentials/credentials_**
```
https://user:pass@server1.com
https://user:pass@server2.com
... etc
```
