### ISSUE TITLE
che-plugin: The environment variable must be applied to cheEditor if the plugin does not describe a container

### ISSUE THREAD

**Issue by vitaliy-guliy** [eclipse-che/che#18759]
### Describe the bug

If the user specify an environment variable for the plugin, but this plugin does not describe any container, the variable must be set to the editor container.

In following devfile a greeting plugin is added to the workspace.
It takes all the environment variables with prefix ` GREETING_` and opens webviews with URLs, taken from values of that variables.

If the variables are specified for the plugin in `env` section, the plugin does not display anything, as the variables has been just ignored.

The plugin brings .vsix extension, that runs inside editor container. That's why it make sense to apply all the variables from `env` section to the container, in which editor is running.

```
---
apiVersion: 1.0.0
metadata:
  generateName: greeting-
projects:
  -
    name: greeting-extension
    source:
      type: git
      location: "https://github.com/vitaliy-guliy/greeting-extension"
      branch: "0.0.1-iframe"
components:
  - 
    type: cheEditor
    id: eclipse/che-theia/latest
    env:
      -
        name: GREETING_A
        value: https://nodejs.org/en/knowledge/HTTP/servers/how-to-create-a-HTTP-server/
      -
        name: GREETING_B
        value: https://nodejs.org/en/download/
  -
    type: chePlugin
    reference: https://gist.githubusercontent.com/vitaliy-guliy/987318d957c052ff7a2bdd1a20c7f955/raw/8ecde4acd14575774704caa9cdb1b16876367808/plugin.meta.yaml
    env:
      -
        name: GREETING_1
        value: https://nodejs.org/en/knowledge/HTTP/servers/how-to-create-a-HTTP-server/
      -
        name: GREETING_2
        value: https://nodejs.org/en/download/
```

For this demo we must have 4 opened URLs, but got only 2.

### Che version

 - [x] latest

### Runtime
   - [x] minikube (include output of `minikube version` and `kubectl version`)

### Screenshots

![Screenshot from 2021-01-08 13-38-10](https://user-images.githubusercontent.com/1655894/104011445-c8d17500-51b6-11eb-9c70-ec76813f918b.png)

### Environment
   - [x] my computer
       - [x] Linux
