### ISSUE TITLE
chectl update failing should give more info

### ISSUE THREAD

**Issue by sunix** [eclipse-che/che#18775]
### Describe the bug
I tried `chectl update` but it failed

### Steps to reproduce
Running `chectl update` worked from `7.22.1` to `7.23.2`, but failed from `7.23.2` to `7.24.0`.

Terminal and `chectl update` from the `chectl` container from that devfile on che.openshift.io:
```yaml
apiVersion: 1.0.0
metadata:
  name: che-in-gcloud-zd9ru
components:
  - mountSources: true
    command:
      - tail
      - '-f'
      - /dev/null
    memoryLimit: 512M
    type: dockerimage
    image: sunix/google-cloud-sdk
    env:
      - value: /projects
        name: HOME
      - value: /bin/bash
        name: SHELL
  - mountSources: true
    memoryLimit: 512Mi
    type: dockerimage
    image: 'quay.io/sunix/chectl@sha256:99a2e13d5722b09acb0ad8fddb7c19fbf8bdd17a4345bde91f1e8779eef1cae4'
    alias: chectl
    env:
      - value: /bin/bash
        name: SHELL
      - value: /projects
        name: HOME

```
### Expected behaviour
Should not failed, or give an error message if it fails.

### Screenshots

![Selection_151](https://user-images.githubusercontent.com/650571/104186568-e3098e00-5416-11eb-8bc0-d64f1c951a64.png)
