### ISSUE TITLE
At least one CRD must include versions in its status

### ISSUE THREAD

**Issue by kristinochka** [eclipse-che/che#18786]
### Is your task related to a problem? Please describe.
At one 1 CRD must include versions in its status with one of the four options below.

The type fields must match.
The properties fields must contain these values but also may contain other values.
The required list must have at minimum the parameters listed in the option, but may have more including the ones specified here.

### Describe the solution you'd like
Full specification example:
deploy/crds/sample_v1_nginx_crd.yaml:

```
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
spec:
  group: sample.ibm.com
  names:
    kind: Nginx
  versions:
  - name: v1beta1
    schema:
      openAPIV3Schema:
        properties:
          status:
            properties:
              versions:
                properties:
                  available:
                    properties:
                      channels:
                        items:
                          properties:
                            name:
                              type: string
                          required:
                          - name
                          type: object
                        type: array
                      versions:
                        items:
                          properties:
                            name:
                              type: string
                          required:
                          - name
                          type: object
                        type: array
                    required:
                    - versions
                    type: object
                  reconciled:
                    type: string
                required:
                - reconciled
                - available
                type: object

```
Example: Minimum Specification

deploy/crds/sample_v1_nginx_crd.yaml:

```
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
spec:
  group: sample.ibm.com
  names:
    kind: Nginx
  versions:
  - name: v1beta1
    schema:
      openAPIV3Schema:
        properties:
          status:
            properties:
              versions:
                properties:
                  reconciled:
                    type: string
                required:
                - reconciled
                type: object
```
