### ISSUE TITLE
A custom resource status block should include a list of resources that it manages using the schema

### ISSUE THREAD

**Issue by kristinochka** [eclipse-che/che#18787]
### Is your task related to a problem? Please describe.
A custom resource status block should include a list of resources that it manages using the schema :/.

This gives a customer a better idea of what resources are being managed by this custom resource. Additionally, in the scenario that an Operator's controller gets deleted out from under a custom resource, this gives the customer a list of resources that can be cleaned up.

File: deploy/crds/org_v1_che_crd.yaml

### Describe the solution you'd like
Example: Passing Example

deploy/crds/good_cr.yaml:

```
apiVersion: sample.ibm.com/v1beta1
kind: Good
metadata:
  name: example-good
spec:
  appVersion: 0.2.0
  status:
    managedResources:
    - deployment:good-namespace/good-deployment
    - configmap:good-namespace/good-configmap

```

deploy/crds/good_crd.yaml:

```
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
spec:
  group: sample.ibm.com
  names:
    kind: Good
  validation:
    openAPIV3Schema:
      properties:
        apiVersion:
          type: string
        kind:
          type: string
        metadata:
          type: object
        spec:
          properties:
            appVersion:
              pattern: ^\d.\d.\d$
              type: string
          type: object
        status:
          properties:
            managedResources:
              items:
                type: string
              type: array
  versions:
  - name: v1beta1
```
