### ISSUE TITLE
Che-theia fails to import projects if one is located in a sub path of another

### ISSUE THREAD

**Issue by sunix** [eclipse-che/che#18790]
### Describe the bug
In a devfile, where one project is supposed to be cloned in a subpath of another project, in some (random?) case, the parent one is not cloned (considered as existing?)

```yaml
apiVersion: 1.0.0
metadata:
  generateName: che-test-clone-subfolders-
projects:
  - name: che-theia
    source:
      location: 'https://github.com/eclipse/che-theia.git'
      type: git
    clonePath: theia/che-theia
  - name: theia
    source:
      location: 'https://github.com/eclipse-theia/theia.git'
      type: git
```

### Che version

 - [x] latest
 - [x] nightly
 - [ ] other: please specify

### Steps to reproduce
1. create a workspace out of the devfile above.

`che-theia` is cloned in `/projects/theia/che-theia`. Missing content of `theia`.

### Expected behavior
`theia` should be cloned as well.

### Additional context
This could be required by https://github.com/eclipse/che/issues/18763
