### ISSUE TITLE
Dashboard does not appear after launch.

### ISSUE THREAD

**Issue by PatNikB** [eclipse-che/che#18813]
Trying to deploy Eclipse Che using Google Cloud Platform.
Followed the instructions from documentation: [https://www.eclipse.org/che/docs/che-7/installation-guide/installing-che-on-google-cloud-platform/](url)

The environment:
Google Cloud Shell (Debian)
Kubernetes version: 1.20
eclipse-che version: 7.24.1

Install cmd: chectl server:deploy --installer=helm --platform=k8s --domain=nikeshbpatel.xyz --multiuser

![image](https://user-images.githubusercontent.com/44244448/104746095-bcb15e80-5746-11eb-8883-44b87da5bdb0.png)

Eclipse che successfully deploys:
When I click the url: [https://che-che.nikeshbpatel.xyz](url) to access the dashboard I get a white web page with ''{{branding.footer.content}}".
![image](https://user-images.githubusercontent.com/44244448/104746838-b53e8500-5747-11eb-9043-2c2b1a5a49d2.png)

![image](https://user-images.githubusercontent.com/44244448/104746931-d30bea00-5747-11eb-891c-143bbcfca2f1.png)

Keycloak works fine and I can log in.
![image](https://user-images.githubusercontent.com/44244448/104747375-59c0c700-5748-11eb-81e7-0404a4d31aa2.png)

Could anyone point me where the issue might be?
Thank you.

**Comment by tolusha** [comment]
Did you try to refresh the page? 
Try to open in a private window as well.

**Comment by PatNikB** [comment]
> Did you try to refresh the page?
> Try to open in a private window as well.

Yes I have tried to refresh the page and also open it in a private window but I still get the same output.

**Comment by PatNikB** [comment]
![image](https://user-images.githubusercontent.com/44244448/104897747-a686e680-5970-11eb-959f-85848558e185.png)

**Comment by degiple** [comment]
It may be improved by fixing `che-dashboard-ingress`.
I added ". *" to the end of the path, and the site is accessible.

`kubectl -n che edit ingress che-dashboard-ingress`

```
~
spec:
  rules:
  - host: YOUR_DOMAIN
    http:
      paths:
      - backend:
          serviceName: che-dashboard
          servicePort: 8080
        path: /dashboard/.*       # add ".*"
        pathType: ImplementationSpecific
~
```
