### ISSUE TITLE
Eclipse Che(mikrok8s) 404 

### ISSUE THREAD

**Issue by k0st1kLOL** [eclipse-che/che#18843]
Install ubuntu server 18.04(20.04) 
install microk8s
 microk8s.kubectl proxy --accept-hosts=. --address=127.0.0.1 --port=8080 &
install chectl
 sudo chectl server:deploy --platform=microk8s --installer=helm

 ✔ Show important messages
    ✔ Eclipse Che **UNKNOWN** has been successfully deployed.
    ✔ Documentation             : https://www.eclipse.org/che/docs/
    ✔ -------------------------------------------------------------------------------
    ✔ Users Dashboard           : https://che-eclipse-che.193.125.11.12.nip.io
    ✔ Admin user login          : "admin:admin". NOTE: must change after first login.
    ✔ -------------------------------------------------------------------------------
    ✔ Plug-in Registry          : https://plugin-registry-eclipse-che.193.125.11.12.nip.io/v3
    ✔ Devfile Registry          : https://devfile-registry-eclipse-che.193.125.11.12.nip.io
    ✔ -------------------------------------------------------------------------------
    ✔ -------------------------------------------------------------------------------

user@mk8s:~$ chectl server:status
› Current Kubernetes context: 'loaded-context'
Eclipse Che Version    : UNKNOWN
Eclipse Che Url        : https://che-eclipse-che.193.125.11.12.nip.io
OpenShift OAuth enabled: No

![изображение](https://user-images.githubusercontent.com/34207621/105173421-0bd60580-5b32-11eb-8462-7d89e0c89502.png)

**Comment by tolusha** [comment]
Do you have any ingresses created?
`microk8s.kubectl get ingress -n eclipse-che`

**Comment by tolusha** [comment]
/cc @mmorhun 
As far I as remember you faced the similar issue.

**Comment by k0st1kLOL** [comment]
> 
> 
> Do you have any ingresses created?
> `microk8s.kubectl get ingress -n eclipse-che`

user@eclipseche:~$ microk8s.kubectl get ingress -n eclipse-che
NAME                    CLASS    HOSTS                                                 ADDRESS   PORTS     AGE
che-dashboard-ingress   <none>   che-eclipse-che.195.239.205.171.nip.io                          80, 443   19h
devfile-registry        <none>   devfile-registry-eclipse-che.195.239.205.171.nip.io             80, 443   19h
plugin-registry         <none>   plugin-registry-eclipse-che.195.239.205.171.nip.io              80, 443   19h
che-ingress             <none>   che-eclipse-che.195.239.205.171.nip.io                          80, 443   19h

**Comment by mmorhun** [comment]
Looks like host cannot access microk8s ingresses.
@k0st1kLOL to check that please deploy a simple application and expose it via ingress (**not** node port).

**Comment by k0st1kLOL** [comment]
> 
> 
> Looks like host cannot access microk8s ingresses.
> @k0st1kLOL to check that please deploy a simple application and expose it via ingress (**not** node port).

for example?

**Comment by mmorhun** [comment]
> for example?

For example enginx. Or it could be any server you want.

**Comment by k0st1kLOL** [comment]
> 
> 
> > for example?
> 
> For example nginx. Or it could be any server you want.

![изображение](https://user-images.githubusercontent.com/34207621/105666625-bd868500-5eea-11eb-838c-c049c11a3256.png)

**Comment by k0st1kLOL** [comment]
kubectl get service
NAME           TYPE        CLUSTER-IP       EXTERNAL-IP   PORT(S)        AGE
kubernetes     ClusterIP   10.152.183.1     <none>        443/TCP        4d18h
http-service   NodePort    10.152.183.207   <none>        80:31950/TCP   3d17h

**Comment by mmorhun** [comment]
> ![изображение](https://user-images.githubusercontent.com/34207621/105666625-bd868500-5eea-11eb-838c-c049c11a3256.png)
> http-service NodePort 10.152.183.207 80:31950/TCP 3d17h

But you exposed it via node port. Eclipse Che requires regular ingress. Please recheck by exposing the service via an ingress.

**Comment by gnoejuan** [comment]
Fresh install. 

```
charlesrod@mainhub:~$ microk8s status
microk8s is running
high-availability: no
  datastore master nodes: 127.0.0.1:19001
  datastore standby nodes: none
addons:
  enabled:
    dns                  # CoreDNS
    ha-cluster           # Configure high availability on the current node
    ingress              # Ingress controller for external access
    storage              # Storage class; allocates storage from host directory
```

I did not do the proxy as OP.

```
  ✔ Show important messages
    ✔ Eclipse Che 7.24.2 has been successfully deployed.
    ✔ Documentation             : https://www.eclipse.org/che/docs/
    ✔ -------------------------------------------------------------------------------
    ✔ Users Dashboard           : https://che-eclipse-che.mainhub.lan
    ✔ Admin user login          : "admin:admin". NOTE: must change after first login.
    ✔ -------------------------------------------------------------------------------
    ✔ Plug-in Registry          : https://plugin-registry-eclipse-che.mainhub.lan/v3
    ✔ Devfile Registry          : https://devfile-registry-eclipse-che.mainhub.lan
    ✔ -------------------------------------------------------------------------------
    ✔ Identity Provider URL     : https://keycloak-eclipse-che.mainhub.lan/auth
    ✔ Identity Provider login   : "admin:xxxxxxx".
    ✔ -------------------------------------------------------------------------------
    ✔ [ACTION REQUIRED] Please add Che self-signed CA certificate into your browser: /tmp/cheCA.crt.
```

```charlesrod@mainhub:~$ kubectl get ingress -n eclipse-che
NAME               CLASS    HOSTS                                      ADDRESS   PORTS     AGE
che                <none>   che-eclipse-che.mainhub.lan                          80, 443   8m47s
keycloak           <none>   keycloak-eclipse-che.mainhub.lan                     80, 443   8m47s
devfile-registry   <none>   devfile-registry-eclipse-che.mainhub.lan             80, 443   5m34s
plugin-registry    <none>   plugin-registry-eclipse-che.mainhub.lan              80, 443   4m52s
```

Same with a fresh [k3sup ](https://github.com/alexellis/k3sup) install 

`chectl server:deploy -a operator -b mainhub.lan -p k8s`

```
charlesrod@Power:~$ kubectl get ingress -n che

NAME               CLASS    HOSTS                              ADDRESS   PORTS     AGE
che                <none>   che-che.mainhub.lan                          80, 443   21m
keycloak           <none>   keycloak-che.mainhub.lan                     80, 443   21m
devfile-registry   <none>   devfile-registry-che.mainhub.lan             80, 443   18m
plugin-registry    <none>   plugin-registry-che.mainhub.lan              80, 443   17m
```

**Comment by mmorhun** [comment]
Hello @gnoejuan. Could you deploy, for example, nginx and try to access it:
Please apply each of the yamls using `kubectl apply -f <filename>.yaml`. In the `ingress` yaml please replace `spec.rules.host` with yours (but keep a `nginx-test` subdomain).
Deployment:
```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
spec:
  selector:
    matchLabels:
      app: nginx-demo
  replicas: 1
  template:
    metadata:
      labels:
        app: nginx-demo
    spec:
      containers:
      - name: nginx
        image: nginx:1.14.2
        ports:
        - containerPort: 80
```
Service:
```yaml
apiVersion: v1
kind: Service
metadata:
  name: nginx-service
spec:
  selector:
    app: nginx-demo
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
```
Ingress:
```yaml
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: nginx-ingress
spec:
 rules:
  - host: nginx-test.172.17.0.3.nip.io
    http:
      paths:
      - path: /
        pathType: ImplementationSpecific
        backend:
          service:
            name: nginx-service
            port:
              number: 80
```
You should get something like:
![Screenshot from 2021-01-26 09-59-29](https://user-images.githubusercontent.com/15607393/105816641-38b86b80-5fbd-11eb-9535-497a4dd4e216.png)

**Comment by gnoejuan** [comment]
The test passed.

```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
spec:
  selector:
    matchLabels:
      app: nginx-demo
  replicas: 1
  template:
    metadata:
      labels:
        app: nginx-demo
    spec:
      containers:
      - name: nginx
        image: nginx:1.14.2
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-service
spec:
  selector:
    app: nginx-demo
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    cert-manager.io/issuer: prod-issuer
    cert-manager.io/issuer-kind: OriginIssuer
    cert-manager.io/issuer-group: cert-manager.k8s.cloudflare.com
  name: nginx-ingress
  namespace: default
spec:
 rules:
  - host: website.me
    http:
      paths:
      - path: /
        pathType: ImplementationSpecific
        backend:
          service:
            name: nginx-service
            port:
              number: 80
 tls:
   - hosts:
     - "*.website.me"
     secretName: website-me-tls
---
```
