### ISSUE TITLE
Updates to the Devfile 2 model to support Che workspaces

### ISSUE THREAD

**Issue by l0rd** [eclipse-che/che#18878]
### Is your enhancement related to a problem? Please describe.

There are some features of workspaces that could be specified using a Devfile v1 that it's not possible to specify using Devfile v2 yet. 

### Describe the solution you'd like

- [x] [Support ephemeral](https://github.com/devfile/api/issues/310) **controller team**
```
spec:
  components:
    - name: my-ephemeral-volume 
      volume:
        ephemeral: false # Volume my-ephemeral-volume will be mounted as emptyDir
```
- [x] asynchronous storage **controller team**
- [x] Support secret and configmap injection (to review if we want to support [current injection mechanism](https://www.eclipse.org/che/docs/che-7/end-user-guide/mounting-a-secret-as-a-file-or-an-environment-variable-into-a-workspace-container/)) **controller team**
  ^ 
  we don't need to have it on devfile model, we're going to implement it in the same way as currently Che does, match secrets and configmaps with their labels/annotations.
