### ISSUE TITLE
Universal plugin definition in Devfile

### ISSUE THREAD

**Issue by sunix** [eclipse-che/che#18892]
### Is your enhancement related to a problem? Please describe.
- Automating the setup of a development environment
- From one single file
- To ease on-boarding
- That works for any editors

are the main purpose of the devfile.

At the moment everything may not working as expected:
- devfiles plugins are too tight to che-theia.
- there is no plugin for other IDEs
- The proposal https://github.com/eclipse/che/issues/18669 would make a nightmare to maintain plugins  for each IDEs for teams with diverse IDEs. When starting a new project, developers would have to write the extensions.json for each IDEs. In a team, if only one developer is using netbeans ... he would have to write the right configuration file for each projects.

At the end of the day, the only thing users are interested into is to have a simple and unique way to express what would be the development environnement and the plugins it would like to generate for a project and for any IDE's used.

#### Plugins declaration in devfile
It should be more generic and IDE/editor agnostic, users' wishes should be as simple as `I want Java11 support` or `I want github tools` or `i want openshift connector` or `I want mysql tools`

Taking as an example this project: https://github.com/sunix/scratch-kubernetes/blob/master/devfile.yaml

Current way:
```yaml
  - id: che-incubator/typescript/latest
    memoryLimit: 0.4Gi
    type: chePlugin

  - id: redhat/quarkus-java11/latest
    memoryLimit: 1.5Gi
    type: chePlugin

  - id: redhat/vscode-openshift-connector/latest
    memoryLimit: 0.7Gi
    type: chePlugin

  - id: redhat/vscode-didact/latest
    preferences:
      didact.openDefaultTutorialAtStartup: true
      che.welcome.enable: false
      didact.defaultUrl: /projects/quarkus-kubernetes-client-service/scratch-k8s-che.didact.md
    type: chePlugin
    registryUrl: 'https://che-plugin-registry-main.surge.sh/v3'
    alias: didact
```
The proposal is to declare plugins like `category/feature` something that could look like:

```yaml
  - id: language/typescript
    type: plugin

  - id: language/quarkus-java11
    type: plugin

  - id: connector/openshift
    type: plugin

  - id: guide/didact
    preferences:
      didact.openDefaultTutorialAtStartup: true
      default.welcome.enable: false
      didact.defaultUrl: ${projects-root}/quarkus-kubernetes-client-service/scratch-k8s-che.didact.md
    type: plugin
```

So these are some example on the plugins id we could have:
- `language/java11`
- `language/quarkus`
- `guide/didact`
- `connector/openshift`
- `scm/git`
- `scm/github`
- `database/mysql`
- `database/postgresql`
- `database/mongo`
- `issues/bugzilla`
- `issues/github`
- `issues/jira`
- etc.

As you can see there is nothing specific to a editor or IDE.

#### Implementation
On the IDE side, we would just have to maintain one plugin or generator per IDEs. These ones would have the right mapping and provide extensions/plugins/configuration that match each plugin id.
For instance, the `devfile plugin or generator in the Eclipse Desktop IDE could rely on Eclipse Oomph and enable/install the right plugins matching the plugin id.

An advance feature for could be to allow a user to override the set of extensions/configuration to be used for `language/java11` that would be done in the IDE level.

Another advance feature could be to let the user define the extension that he always wants to enable, whatever the project.

### Describe alternatives you've considered
N/A
