### ISSUE TITLE
shellcheck binary not found in the shellcheck extension

### ISSUE THREAD

**Issue by themr0c** [eclipse-che/che#18924]
shellcheck binary not found in the shellcheck extension

Here a screenshot when testing https://github.com/eclipse/che-docs/pull/1820 on Hosted Che:

![Screenshot from 2021-01-29 16-07-14](https://user-images.githubusercontent.com/243761/106291675-39b2fc80-624c-11eb-9c54-9fe498135f23.png)

**Comment by benoitf** [comment]
workaround is to add preference in the devfile itself:
```
  - id: timonwong/shellcheck/latest
    memoryLimit: 64Mi
    preferences:
      shellcheck.executablePath: /bin/shellcheck
    type: chePlugin
```
