### ISSUE TITLE
Displaying list of typescript tasks takes a lot of time 

### ISSUE THREAD

**Issue by RomanNikitenko** [eclipse-che/che#18928]
### Describe the bug

Displaying list of tasks takes at least 30 seconds for me when:
- I have typescript plugin is turned on
- big enough project, `che-theia` for example  

I understand that there are a lot of `tsc` tasks for such big project, but if the `typescript` plugin is  turned off - there are still a lot of `npm` tasks and displaying tasks takes only 1 second.

So, it would be really useful to investigate why we have such huge delay for displaying `tsc` tasks. 

### Che version

 - [ ] latest
 - [x] nightly
 - [ ] other: please specify

### Steps to reproduce

1. Start a workspace from the provided `devfile`:
<details>
<summary>Devfile</summary>

```
apiVersion: 1.0.0
metadata:
  name: typescript-tasks-bug
projects:
  - name: che-theia
    source:
      location: 'https://github.com/eclipse/che-theia.git'
      type: git
      branch: master
components:
  - id: eclipse/che-theia/next
    memoryLimit: 768Mi
    type: cheEditor
    alias: che-theia
  - id: vscode/typescript-language-features/latest
    type: chePlugin

``` 
</details>

2. Go to `Terminal => Run task` menu
3. It takes lot of time to display available tasks fro running (for me it's about 30 seconds)
4. Turn off the `typescript` plugin from dashborad
5. Go to `Terminal => Run task` menu again
6. Now displaying available tasks takes about 1 second 

### Expected behavior

It would be really useful to investigate why we have such huge delay for displaying `tsc` tasks. 

### Runtime
   I am able to reproduce the issue on che.openshift.io and dogfooding instances  
   
### Screenshots

![tsc_tasks_bug](https://user-images.githubusercontent.com/5676062/106390525-79671900-63f1-11eb-9a65-fe8a5a5584c6.gif)

### Installation method
   che.openshift.io and dogfooding instances
