### ISSUE TITLE
[che-operator] Configure OAuth1 and OAuth2 integrations with K8s Secrets 

### ISSUE THREAD

**Issue by skabashnyuk** [eclipse-che/che#18932]
### Is your task related to a problem? Please describe.
We would like to standardize/unify the way how OAuth1 and OAuth2 integration configured.

### Describe the solution you'd like

Proposed format.

```yaml
kind: Secret
apiVersion: v1
metadata:
  name: <scm-provider-id>-oaut-config
  namespace: <...> 
  labels:
    app.kubernetes.io/part-of: che.eclipse.org
    app.kubernetes.io/component: oauth-scm-configuration
  annotations:
    che.eclipse.org/oauth-scm-server: bitbucket (variants: github, bitbucket, gitlab)
    che.eclipse.org/scm-server-endpoint: http://bitbucket-bitbucket.apps.cluster-2d6e.2d6e.example.opentlc.com/ (if url is set that means that this is and on-prem otherwise this is saas)
type: Opaque
data:
  file1: <...> 
  file2: <...> 
```
For Github it will look like this.

```yaml
kind: Secret
apiVersion: v1
metadata:
  name: github-oaut-config
  namespace: <...> 
  labels:
    app.kubernetes.io/part-of: che.eclipse.org
    app.kubernetes.io/component: oauth-scm-configuration
  annotations:
    che.eclipse.org/oauth-scm-server: github
type: Opaque
data:
  id: <...> 
  secret: <...> 
```
That means that che operator has to :

- Mount GITHUB_CLIENT_ID  and GITHUB_SECRET to keycloak container
- Run the correct script to create github integrations on keycloak

For Bitbucket server it will looks like this:

```yaml
kind: Secret
apiVersion: v1
metadata:
  name: github-oaut-config
  namespace: <...> 
  labels:
    app.kubernetes.io/part-of: che.eclipse.org
    app.kubernetes.io/component: oauth-scm-configuration
  annotations:
    che.eclipse.org/oauth-scm-server: bitbucket
    che.eclipse.org/scm-server-endpoint: http://bitbucket-bitbucket.apps.cluster-2d6e.2d6e.example.opentlc.com/
type: Opaque
data:
  private.key: <...> 
  consumer.key: <...> 
```
That means that che operator has to :

- Mount private.key  and consumer.key to che-server container
- Set environment variables to che-server
 CHE_OAUTH1_BITBUCKET_CONSUMERKEYPATH=/home/user/eclipse-che/conf/oauth1/bitbucket/consumer.key
 CHE_OAUTH1_BITBUCKET_PRIVATEKEYPATH=/home/user/eclipse-che/conf/oauth1/bitbucket/private.key
 CHE_OAUTH1_BITBUCKET_ENDPOINT=http://bitbucket-bitbucket.apps.cluster-2d6e.2d6e.example.opentlc.com/
 CHE_INTEGRATION_BITBUCKET_SERVER__ENDPOINTS=http://bitbucket-bitbucket.apps.cluster-2d6e.2d6e.example.opentlc.com/

### Additional context
 - Obtain and persist Bitbucket personal access token as k8s secret https://github.com/eclipse/che/issues/18388
 - Bitbucket server support in Che's factory flow https://github.com/eclipse/che/issues/18385
