### ISSUE TITLE
E2E Happy path tests failed to start test workspace because of che-theia-runtime-binary image pull error

### ISSUE THREAD

**Issue by dmytro-ndp** [eclipse-che/che#18935]
### Describe the bug
E2E Happy path tests failed to start test workspace from because of _che-theia-runtime-binary_ image pull error:
https://main-jenkins-csb-crwqe.apps.ocp4.prod.psi.redhat.com/job/Che/job/e2e/job/minikube/job/basic/job/eclipse-che/447/
> Failed to pull image "quay.io/eclipse/che-theia-endpoint-runtime-binary@sha256:f07e63102eff29069524734d10dab480e34fdace006c284e6e91c5bbb3104ba2": rpc error: code = Unknown desc = Error response from daemon: manifest for quay.io/eclipse/che-theia-endpoint-runtime-binary@sha256:f07e63102eff29069524734d10dab480e34fdace006c284e6e91c5bbb3104ba2 not found: manifest unknown: manifest unknown

![screenshot-Wait_for_workspace_readiness (5)](https://user-images.githubusercontent.com/1197777/106453877-9e5f9880-6492-11eb-9645-6766a9715010.png)

Correct image address: quay.io/eclipse/che-theia-endpoint-runtime-binary@sha256:77bed604b46d12a4d7c0819272ec6dbce88ff18209e21d75d824af833f131ed8

Test workspace devfile: https://main-jenkins-csb-crwqe.apps.ocp4.prod.psi.redhat.com/job/Che/job/e2e/job/minikube/job/basic/job/eclipse-che/447/artifact/logs-and-configs/test-workspace-devfile.yaml/*view*/
```
---
apiVersion: 1.0.0
metadata:
  name: petclinic-dev-environment
projects:
  - name: petclinic
    source:
      type: git
      location: "https://github.com/spring-projects/spring-petclinic.git"
components:
  - type: cheEditor
    id: eclipse/che-theia/next
    memoryLimit: 512Mi
  - type: kubernetes
    alias: petclinic-web
    reference: https://raw.githubusercontent.com/eclipse/che/master/tests/e2e/files/happy-path/containers-happy-path.yaml
    selector:
      app.kubernetes.io/component: webapp
    entrypoints:
      - containerName: spring-boot
        command: ["tail"]
        args: ["-f", "/dev/null"]
  - type: kubernetes
    alias: petclinic-db
    reference: https://raw.githubusercontent.com/eclipse/che/master/tests/e2e/files/happy-path/containers-happy-path.yaml
    selector:
      app.kubernetes.io/component: database
  - type: dockerimage
    alias: maven-container
    image: quay.io/eclipse/happy-path:nightly
    env:
      - name: MAVEN_CONFIG
        value: /home/user/.m2
    memoryLimit: 1500Mi
    mountSources: true
  - type: chePlugin
    id: redhat/java/latest
    memoryLimit: "1000Mi"
    preferences:
      java.server.launchMode: Standard
  - type: chePlugin
    id: redhat/vscode-yaml/latest
commands:
  - name: build
    actions:
      - type: exec
        component: maven-container
        command: mvn clean package | tee build.txt && tail -n 40 /projects/petclinic/build.txt | grep 'BUILD SUCCESS' > /projects/petclinic/result-build.txt
        workdir: /projects/petclinic
  - name: build-file-output
    actions:
      - type: exec
        component: maven-container
        command: cd /projects/petclinic && mvn package | tee build-output.txt && tail -n 40 /projects/petclinic/build-output.txt | grep 'BUILD SUCCESS' > /projects/petclinic/result-build-output.txt
  - name: run
    actions:
      - type: exec
        component: maven-container
        command: java -jar spring-petclinic-2.4.2.jar --spring.profiles.active=mysql
        workdir: /projects/petclinic/target
  - name: run-with-changes
    actions:
      - type: exec
        component: maven-container
        command: java -jar spring-petclinic-2.4.2.jar --spring.profiles.active=mysql
        workdir: /projects/petclinic/target
  - name: run-debug
    actions:
      - type: exec
        component: maven-container
        command: java -jar -Xdebug -Xrunjdwp:transport=dt_socket,server=y,suspend=n,address=5005 spring-petclinic-2.4.2.jar --spring.profiles.active=mysql
        workdir: /projects/petclinic/target
  - name: Debug remote java application
    actions:
      - type: vscode-launch
        referenceContent: |
          {
          "version": "0.2.0",
          "configurations": [
            {
              "type": "java",
              "name": "Debug (Attach) - Remote",
              "request": "attach",
              "hostName": "localhost",
              "port": 5005
            }]
          }
```

Git ssh flow tests workspace had run successfully with correct image address quay.io/eclipse/che-theia-endpoint-runtime-binary@sha256:77bed604b46d12a4d7c0819272ec6dbce88ff18209e21d75d824af833f131ed8
https://main-jenkins-csb-crwqe.apps.ocp4.prod.psi.redhat.com/job/Che/job/e2e/job/minikube/job/basic/job/eclipse-che/451/

It blocks check of Eclipse Che PRs.

### Che version

 - [ ] latest
 - [x] nightly
 - [ ] other: please specify

### Runtime
   - [ ] kubernetes (include output of `kubectl version`)
   - [ ] Openshift (include output of `oc version`)
   - [x] minikube 1.1.1
   - [ ] minishift (include output of `minishift version` and `oc version`)
   - [ ] docker-desktop + K8S (include output of `docker version` and `kubectl version`)
   - [ ] other: (please specify)

### Installation method
   - [x] chectl next
     * provide a full command that was used to deploy Eclipse Che (including the output)
     * provide an output of `chectl version` command
   - [ ] OperatorHub
   - [ ] I don't know

### Environment
   - [ ] my computer
       - [ ] Windows
       - [ ] Linux
       - [ ] macOS
   - [ ] Cloud
       - [ ] Amazon
       - [ ] Azure
       - [ ] GCE
       - [ ] other (please specify)
   - [x] other: CRW CCI

### Additional context
Follow up of issue: https://github.com/eclipse/che/issues/18931
