### ISSUE TITLE
Dashboard does not configure credentials to registry which name is not URL like

### ISSUE THREAD

**Issue by sleshchenko** [eclipse-che/che#18959]
### Describe the bug
Dashboard restricts registry names be in URL (with protocol), but it's not requirement for registry names, e.g. `quay.io` should be used for containers form https://quay.io/

Note if registry does not have protocal specified - the dashboard should not display it as relative link:
![Screenshot_20210203_144030](https://user-images.githubusercontent.com/5887312/106748397-dbac5d80-662d-11eb-993c-9fdc907e048a.png)

### Che version

 - [ ] latest
 - [ ] nightly
 - [ ] other: please specify

### Steps to reproduce
docker pull quay.io/eclipse/che-nodejs8-centos:nightly
docker tag quay.io/eclipse/che-nodejs8-centos:nightly quay.io/MY_QUAY_USERNAME/che-nodejs8-centos:nightly
docker push quay.io/sleshche/che-nodejs8-centos:nightly

1. Configure credentials on the Dashboard to quay.io
2. Make sure the following workspace is started
```
apiVersion: 1.0.0
metadata:
  name: react-kw6z7
components:
  - mountSources: true
    endpoints:
      - name: nodejs
        port: 4100
    memoryLimit: 512Mi
    type: dockerimage
    image: 'quay.io/MY_QUAY_USERNAME/che-nodejs8-centos:nightly'
    alias: nodejs
```
