### ISSUE TITLE
Java Maven sample on minikube is not starting

### ISSUE THREAD

**Issue by l0rd** [eclipse-che/che#18955]
### Describe the bug

After a standard minikube installation, when trying to start a Java maven sample workspace, it fails with the following error:

```log
0/1 nodes are available: 1 Insufficient cpu.
```

<img width="1015" alt="image" src="https://user-images.githubusercontent.com/606959/106722858-c07a2780-6606-11eb-8067-9332e4f7024d.png">

Investigating the problem it looks like, after installing Che, the amount of CPU available is 550m:

```bash
$ kubectl describe nodes minikube
(...)
Allocated resources:
  (Total limits may be over 100 percent, i.e., overcommitted.)
  Resource           Requests      Limits
  --------           --------      ------
  cpu                1450m (72%)   5 (250%)
  memory             2436Mi (30%)  4522Mi (56%)
  ephemeral-storage  100Mi (0%)    0 (0%)
  hugepages-2Mi      0 (0%)        0 (0%)
Events:              <none>
```

And the CPU requested when starting a Java workpspace is 560:

```
kubectl get po -l 'che.original_name=maven' -o json |
   jq -r '.spec.containers[] | "---", .name, .resources.requests.cpu
---
che-jwtproxyxpyif8bp
30m
---
maven
null
---
vscode-javausm
30m
---
che-machine-exectuy
null
---
theia-ideunj
500m
---
```

That would explain why Kubernetes refuses to schedule the workspace pod.

### Che version

nightly

### Steps to reproduce

Install and start minikube with the command line provided in the documentation:

```bash
$ minikube start --addons=ingress --vm=true --memory=8192
```

Install Che using chectl (next channel):

```bash
$ chectl update next && \
  chectl server:deploy -p minikube
```

### Expected behavior

Every sample should work out of the box on a default minikube installation.

### Additional context

This is related to [this PR](https://github.com/eclipse/che-plugin-registry/pull/796). 

Now I think we have 2 options:

**OPTION 1: Set a lower CPU request for Theia**

We are setting 500m as CPU request considering that's the minimum CPU for Theia to work properly. Truth is that if I set 30m as CPU request request I can start a workspace and use Theia with no issue. If I set 500m I cannot even start a workspace.

**OPTION 2: Require at least 4 CPUs to run a workspace**

The documentation suggest the [following command to start minikube](https://www.eclipse.org/che/docs/che-7/installation-guide/installing-che-on-minikube/):

```bash
minikube start --addons=ingress --vm=true --memory=8192
```

And chectl is probably using the same command to start minikube. We should add `--cpus=4`.

**Comment by azatsarynnyy** [comment]
@vzhukovs take a look at it. We should set such `cpuRequest` value that wouldn't prevent different stacks from running.
Maybe, the proposed by @l0rd value (30m) is not enough to prevent the Offline mode from displaying too often.
But something in between should work well, I believe.
I'm raising it to blocker.

**Comment by l0rd** [comment]
> 30m is not enough to prevent the Offline mode from displaying too often.

I am not able to reproduce this problem. I have the offline mode problem if I set cpu limit too low, but not cpu request.

**Comment by azatsarynnyy** [comment]
@vzhukovs I think it also worth checking if the recently merged PR https://github.com/eclipse/che-plugin-registry/pull/774 affects the issue. It was merged yesterday.

**Comment by azatsarynnyy** [comment]
I know that @vzhukovs has checked https://github.com/eclipse/che-plugin-registry/pull/796 on minikube with Java Maven sample, and it was working well before https://github.com/eclipse/che-plugin-registry/pull/774 has been merged.

**Comment by l0rd** [comment]
@azatsarynnyy it's expect to work if CPU setting in minikube is set to 4. And I have just noticed that, if minikube is not already started, chectl sets [--cpu=4](https://github.com/che-incubator/chectl/blob/master/src/tasks/platforms/minikube.ts#L138). That may explain why @vzhukovs and PR checks haven't reproduced it.

**Comment by azatsarynnyy** [comment]
hm.. can't even start a workspace check it on my side

![image](https://user-images.githubusercontent.com/1636395/106747722-f6320700-662c-11eb-9cb4-9bdd05807c7e.png)

It looks very similar to https://github.com/eclipse/che/issues/18931

**Comment by vzhukovs** [comment]
> hm.. can't even start a workspace check it on my side
> 
> ![image](https://user-images.githubusercontent.com/1636395/106747722-f6320700-662c-11eb-9cb4-9bdd05807c7e.png)
> 
> It looks very similar to #18931

The same on my side:
![image (2)](https://user-images.githubusercontent.com/1968177/106748542-0f878300-662e-11eb-9549-0e6a477b506c.png)

Trying to run the following devfile:
```yaml
apiVersion: 1.0.0
metadata:
  name: java-mysql-vv762
projects:
  - name: web-java-spring-petclinic
    source:
      location: 'https://github.com/spring-projects/spring-petclinic.git'
      type: git
      commitId: 93873665453584deb891569c02e3acc7283cf394
components:
  - type: cheEditor
    reference: 'https://gist.github.com/vzhukovs/732676571880f51bc0b87cc2f7ee1304/raw/56d7e68a17b67a3ea6306bd51a2419ac334d25f2/meta.yaml'
  - id: redhat/java8/latest
    memoryLimit: 1280Mi
    type: chePlugin
  - mountSources: true
    endpoints:
      - name: 8080-tcp
        port: 8080
      - attributes:
          public: 'false'
        name: debug
        port: 5005
    memoryLimit: 1000Mi
    type: dockerimage
    volumes:
      - name: m2
        containerPath: /home/user/.m2
    alias: tools
    image: 'quay.io/eclipse/che-java8-maven:nightly'
    env:
      - value: ''
        name: MAVEN_CONFIG
      - value: '-XX:MaxRAMPercentage=50.0 -XX:+UseParallelGC -XX:MinHeapFreeRatio=10 -XX:MaxHeapFreeRatio=20 -XX:GCTimeRatio=4 -XX:AdaptiveSizePolicyWeight=90 -Dsun.zip.disableMemoryMapping=true -Xms20m -Djava.security.egd=file:/dev/./urandom -Duser.home=/home/user'
        name: JAVA_OPTS
      - value: $(JAVA_OPTS)
        name: MAVEN_OPTS
  - mountSources: true
    endpoints:
      - attributes:
          discoverable: 'true'
          public: 'false'
        name: db
        port: 3306
    memoryLimit: 300Mi
    type: dockerimage
    alias: mysql
    image: 'quay.io/eclipse/che--centos--mysql-57-centos7:latest-e08ee4d43b7356607685b69bde6335e27cf20c020f345b6c6c59400183882764'
    env:
      - value: petclinic
        name: MYSQL_USER
      - value: petclinic
        name: MYSQL_PASSWORD
      - value: petclinic
        name: MYSQL_DATABASE
      - value: '$(echo ${0})\\$'
        name: PS1
commands:
  - name: maven build
    actions:
      - workdir: '${CHE_PROJECTS_ROOT}/web-java-spring-petclinic'
        type: exec
        command: mvn clean install
        component: tools
  - name: run webapp
    actions:
      - workdir: '${CHE_PROJECTS_ROOT}/web-java-spring-petclinic'
        type: exec
        command: |
          SPRING_DATASOURCE_URL=jdbc:mysql://db/petclinic \
          SPRING_DATASOURCE_USERNAME=petclinic \
          SPRING_DATASOURCE_PASSWORD=petclinic \
          java -jar -Dspring.profiles.active=mysql \
          -Xdebug -Xrunjdwp:transport=dt_socket,server=y,suspend=n,address=5005 \
          target/*.jar
        component: tools
  - name: prepare database
    actions:
      - type: exec
        command: |
          /opt/rh/rh-mysql57/root/usr/bin/mysql -u root < ${CHE_PROJECTS_ROOT}/web-java-spring-petclinic/src/main/resources/db/mysql/user.sql &&
          /opt/rh/rh-mysql57/root/usr/bin/mysql -u root petclinic < ${CHE_PROJECTS_ROOT}/web-java-spring-petclinic/src/main/resources/db/mysql/schema.sql &&
          echo -e "\e[32mDone.\e[0m Database petclinic was configured!"
        component: mysql
  - name: Debug remote java application
    actions:
      - referenceContent: |
          {
          "version": "0.2.0",
          "configurations": [
            {
              "type": "java",
              "name": "Debug (Attach) - Remote",
              "request": "attach",
              "hostName": "localhost",
              "port": 5005
            }]
          }
        type: vscode-launch
```
