### ISSUE TITLE
Terminal's output is broken

### ISSUE THREAD

**Issue by RomanNikitenko** [eclipse-che/che#19056]
### Describe the bug

Please see the screenshot below

### Che version

 - [x] latest
 - [ ] nightly
 - [ ] other: please specify

### Steps to reproduce

1. Start a workspace from a stack
2. Go to `Terminal` => `Open terminal in a specific container`
3. Type some commands to the terminal

See the output.

### Expected behavior
An output for a a terminal is displayed correctly

### Runtime
I'm able to reproduce the problem on dogfooding instance and che.openshift.io

### Screenshots
![terminal_output](https://user-images.githubusercontent.com/5676062/107772705-4142cd00-6d45-11eb-8f6f-eadda82cb043.png)

**Comment by azatsarynnyy** [comment]
I've just checked it on che.openshift.io with the following Devfile:
```yaml
apiVersion: 1.0.0
metadata:
  name: wksp-custom-zhmgh
attributes:
  persistVolumes: 'false'
components:
  - id: eclipse/che-theia/next
    type: cheEditor
```

Everything looks good:

![image](https://user-images.githubusercontent.com/1636395/107773881-f75ae680-6d46-11eb-8d41-e2872285b50c.png)

I remember I had a similar issue when I've got some problems with the graphic drivers on my laptop.
