### ISSUE TITLE
Propagate Che user informations and preferences to DevWorkspaces

### ISSUE THREAD

**Issue by benoitf** [eclipse-che/che#19061]
### Is your task related to a problem? Please describe.
For example:

1. che-theia will require dashboard URL to display redirect.
But for example this information is not propagated to a workspace (no che api server to reach or no config map having this information)

2. I would want to grab user information (like che user id/user name/ user email, etc)

### Describe the solution you'd like
Have dashboard/che creating configMap with this kind of information

### Describe alternatives you've considered
N/A

### Additional context
che-theia can't grab information if it's not provided by 3rd party

**Comment by tsmaeder** [comment]
@benoitf "workspace/user settings" is a technical term in Theia IDE. What you mean is information about the che user and che workspace, right? How about we call it "workspace configuration" for clarity?

**Comment by benoitf** [comment]
I called it 'che information' like workspace/user settings as it's a che information coming from the Che Rest API.
It's not tied to Theia

**Comment by skabashnyuk** [comment]
What about an idea to put user profile/preference to some CR in user's namespace. Would it be possible from the Theia side to read it directly from CR without having a REST API for it? CC @sleshchenko

**Comment by sleshchenko** [comment]
> What about an idea to put user profile/preference to some CR in user's namespace. Would it be possible from the Theia side to read it directly from CR without having a REST API for it? CC @sleshchenko

yes, but it's the question who will put that info near DevWorkspace CR.

**Comment by skabashnyuk** [comment]
@l0rd can we move this to Step4?

**Comment by skabashnyuk** [comment]
We could create such two secrets (separate for user profile and prefereces) that can be reused Che7 based workspaces and Devworkspaces after k8s namespace provisioning.

```yaml
apiVersion: v1
kind: Secret
metadata:
  name: che-user-profile
  namespace: user1-che
  annotations:
    che.eclipse.org/automount-workspace-secret: 'true'
    che.eclipse.org/mount-path: /che-conf/user/profile
    che.eclipse.org/mount-as: file
  labels:
    controller.devfile.io/mount-to-devworkspace: "true"
    controller.devfile.io/mount-path: /che-conf/user/profile
    app.kubernetes.io/part-of: che.eclipse.org
    app.kubernetes.io/component: workspace-secret
type: Opaque
data:
  id: id
  name: user1
  email: user1@site.com
```


```yaml
apiVersion: v1
kind: Secret
metadata:
  name: che-user-preference
  namespace: user1-che
  annotations:
    che.eclipse.org/automount-workspace-secret: 'true'
    che.eclipse.org/mount-path: /che-conf/user/preferences
    che.eclipse.org/mount-as: file
  labels:
    controller.devfile.io/mount-to-devworkspace: "true"
    controller.devfile.io/mount-path: /che-conf/user/preferences
    app.kubernetes.io/part-of: che.eclipse.org
    app.kubernetes.io/component: workspace-secret
type: Opaque
data:
  k: v
  k2: v2
```
