### ISSUE TITLE
Only few functions work in the "redhat/vscode-yaml" plugin.

### ISSUE THREAD

**Issue by Ohrimenko1988** [eclipse-che/che#19091]
### Describe the bug
Only few functions work in the "redhat/vscode-yaml" plugin.
The list of expected functions got from here [yaml plugin](https://marketplace.visualstudio.com/items?itemName=redhat.vscode-yaml)
For example **work:**
 - Yaml validation
 - Format document
 
**don't work:**
 - Auto completion (Ctrl + Space)
 - Document Outlining (Ctrl + Shift + O)
 - Hover support:

### Che version

 - [ ] latest
 - [ x ] nightly
 - [ ] other: please specify

### Steps to reproduce
 - Create custom workspace using next devfile:
```
apiVersion: 1.0.0
metadata:
  name: apache-camel-k-dotsq
projects:
  - name: camel-k-examples
    source:
      location: 'https://github.com/apache/camel-k'
      type: git
      sparseCheckoutDir: examples
components:
  - id: redhat/vscode-xml/latest
    type: chePlugin
  - id: redhat/vscode-apache-camel/latest
    type: chePlugin
  - id: redhat/vscode-camelk/latest
    type: chePlugin
    alias: vscode-camelk
  - type: chePlugin
    id: redhat/vscode-yaml/latest
```
 - Go inside created workspace and open the "camel-k-examples/examples/languages/routes.yaml" file in the editor
 - Try to use auto completion (Ctrl + Space)
 - Pay attention that no appropriate suggestions shown
 - Try to use also "Document outlining" and "Hover support"
 - Pay attention that these features also don't work
 - Also pay attention that "Yaml validation" and "Format" features work

### Expected behavior
All plugin features work

### Observed behavior
Only a part of features work

### Runtime
   - [ ] kubernetes (include output of `kubectl version`)
   - [ ] Openshift (include output of `oc version`)
   - [ x ] minikube (include output of `minikube version` and `kubectl version`)
   - [ ] minishift (include output of `minishift version` and `oc version`)
   - [ ] docker-desktop + K8S (include output of `docker version` and `kubectl version`)
   - [ ] other: (please specify)

### Installation method
   - [ x ] chectl
```
./chectl server:deploy \
  --k8spodreadytimeout=600000 \
  --k8spodwaittimeout=600000 \
  --k8spoddownloadimagetimeout=600000 \
  --listr-renderer=verbose \
  --platform=minikube \
  --chenamespace=eclipse-che \
  --telemetry=off
```
```
chectl/7.26.0 linux-x64 node-v12.20.1
```
   - [ ] OperatorHub
   - [ ] I don't know

### Environment
   - [ ] my computer
       - [ ] Windows
       - [x ] Linux
       - [ ] macOS
   - [ ] Cloud
       - [ ] Amazon
       - [ ] Azure
       - [ ] GCE
       - [ ] other (please specify)
   - [ ] other: please specify
