### ISSUE TITLE
Che tasks looks unresponsive at some case

### ISSUE THREAD

**Issue by RomanNikitenko** [eclipse-che/che#19107]
### Describe the bug

I have a devfile for `che-in-che` development.
Running any `che` task from `Workspace` panel takes about 1 minute for me on `dogfooding` instance.
So for a user it looks like `che` tasks are not working at all.

<details>
<summary>Devfile</summary>

```
apiVersion: 1.0.0
metadata:
  name: che-in-che-next
projects:
  - name: theia
    source:
      location: 'https://github.com/eclipse-theia/theia.git'
      type: git
      branch: master
  - name: che-theia
    source:
      location: 'https://github.com/eclipse/che-theia.git'
      type: git
      branch: master
components:
  - id: redhat/vscode-yaml/latest
    type: chePlugin
  - mountSources: true
    endpoints:
      - attributes:
          protocol: http
          public: 'true'
        name: theia-dev-flow
        port: 3010
    memoryLimit: 6Gi
    type: dockerimage
    image: 'quay.io/eclipse/che-theia-dev:next'
    alias: che-dev
  - id: che-incubator/typescript/latest
    memoryLimit: 2048M
    type: chePlugin
  - id: eclipse/che-theia/next
    type: cheEditor
commands:
  - name: start hosted instance
    actions:
      - workdir: /projects/theia/examples/assembly
        type: exec
        command: |
          yarn theia start --hostname=0.0.0.0 --port=3130 --plugins=local-dir:../../../che-theia/plugins
        component: che-dev
  - name: 'che-theia:build'
    actions:
      - workdir: /projects/che-theia
        type: exec
        command: |
          yarn
        component: che-dev
  - name: 'che:theia:init'
    actions:
      - workdir: /projects/theia
        type: exec
        command: |
          che-theia init
        component: che-dev
  - name: 'theia:build'
    actions:
      - workdir: /projects/theia
        type: exec
        command: |
          yarn
        component: che-dev
  
``` 
</details>

### Che version

 - [ ] latest
 - [x] nightly
 - [ ] other: please specify

### Steps to reproduce
1. Start a workspace from the `devfile` above
2. Try to run any `che` task from the `Workspace` panel.
3. You can see the corresponding terminal for the task output in ~ 1 minute.
4. Go to dashboard and remove `typescript` plugin from the `devfile`
5. Repeat 1-2 steps.
6. You can see that `che` tasks works well now. 

### Expected behavior

Starting a `che` task from the `Workspace` panel takes about 1 second.

### Runtime
Dogfooding instance

### Additional context

I found that the bug somehow related to `typescript` plugin.
It's required to have the following to reproduce the issue:
-  `typescript` plugin in your `devfile`
-  a project which has a lot of `typescript` tasks, `che-theia` - is good example
