### ISSUE TITLE
Che plugin that extends a existing plugin

### ISSUE THREAD

**Issue by sunix** [eclipse-che/che#19125]
### Is your enhancement related to a problem? Please describe.
In many situation, a devfile should have the ability to use an existing plugin but with additional vscode extensions.
For instance:
- The quarkus plugin could extend the Java11 plugin (adding vscode ext) or the Java15 plugin (if one day it exists)
- The lombok plugin could extend any of the Java based, could be quarkus or Java11 or java8
- the tekton plugin could extend the openshift plugin or the kubernetes plugin

### Describe the solution you'd like
So let's say we have `cool2k/vscode-lombok/latest` that is defined with in the plugin registry with an attribute `basePlugin`

```yaml
apiVersion: v2
publisher: cool2k
name: vscode-lombok
version: 1.0.2
type: VS Code extension
repository: 'https://github.com/GabrielBB/vscode-lombok.git'
spec:
  basePlugin: redhat/java/latest
  extensions:
    - 'https://open-vsx.org/api/cool2k/vscode-lombok/1.0.2/file/cool2k.vscode-lombok-1.0.2.vsix'
```
in The devfile we would have:

```yaml
  - type: chePlugin
    id: cool2k/vscode-lombok/latest
    extends: 
      - redhat/java11/latest
      - redhat/quarkus/latest
```

or 

```yaml
  - type: chePlugin
    id: redhat/quarkus/latest
    extends: 
      - redhat/java11/latest
```

### Describe alternatives you've considered
There are merge plugin capabilities but these are very limited as it would merge the plugins with the same base image. For the lombok example, it would be hard to use as we would need to define lombok plugin per version of Java

### Additional context
N/A
