### ISSUE TITLE
Can not clone zip project on Minikube

### ISSUE THREAD

**Issue by RomanNikitenko** [eclipse-che/che#19120]
### Describe the bug

I get an error at importing a zip project on `minikube`.
The error is: 

```
Couldn't import https://github.com/eclipse-theia/theia/archive/master.zip: curl: (60) SSL certificate problem: 
unable to get local issuer certificate 
More details here: https://curl.haxx.se/docs/sslcerts.html curl 
failed to verify the legitimacy of the server and therefore could not establish a secure connection to it. 
To learn more about this situation and how to fix it, please visit the web page mentioned above.

```

Please see the screenshot below.

I'm not able to reproduce the bug using the same `devfile` on the `dogfooding` instance.

### Che version

 - [ ] latest
 - [x] nightly
 - [ ] other: please specify

### Steps to reproduce

Start a workspace from the following `devfile` on `minikube`.
<details>
<summary>Devfile</summary>

```
apiVersion: 1.0.0
metadata:
  name: test-import-zip
projects:
  - name: theia
    source:
      location: 'https://github.com/eclipse-theia/theia/archive/master.zip'
      type: zip
      branch: master
components:
  - id: eclipse/che-theia/next
    type: cheEditor

```
</details>

### Runtime
   - [ ] kubernetes (include output of `kubectl version`)
   - [ ] Openshift (include output of `oc version`)
   - [x] minikube 
   ```
   minikube version: v1.16.0
   commit: 9f1e482427589ff8451c4723b6ba53bb9742fbb1
   
   kubectl version: v1.20.1
```
   - [ ] minishift (include output of `minishift version` and `oc version`)
   - [ ] docker-desktop + K8S (include output of `docker version` and `kubectl version`)
   - [ ] other: (please specify)

### Screenshots

![zip_clone](https://user-images.githubusercontent.com/5676062/108698212-8cf73280-750c-11eb-9d84-bc2f8ec4a2af.png)

### Installation method
   - [x] chectl
     chectl/0.0.20210220-next.92bf415 linux-x64 node-v12.20.2
   - [ ] OperatorHub
   - [ ] I don't know

### Environment
   - [ ] my computer
       - [ ] Windows
       - [x] Linux
       - [ ] macOS
   - [ ] Cloud
       - [ ] Amazon
       - [ ] Azure
       - [ ] GCE
       - [ ] other (please specify)
   - [ ] other: please specify
