### ISSUE TITLE
Cannot open a working terminal 

### ISSUE THREAD

**Issue by tsmaeder** [eclipse-che/che#19124]
### Describe the bug
When I try to open a terminal windows for the `che-dev` container in a self-hosting workspace, the terminal windows opens, but the prompt text is never written to the console and typing has no effect.

### Che version

 - 7.26.0 with this devfile:

<details>

<summary>Devfile</summary>

```yaml
apiVersion: 1.0.0
metadata:
  name: self-hosting
components:
  - memoryLimit: 4Gi
    type: cheEditor
    reference: 'https://gist.githubusercontent.com/tsmaeder/426f8366f9579989a81b8e5816b23f15/raw/57246b2ed0021411967fca7f07c7ef8e55d1490c/che-theia.yaml'
    alias: theia-editor
    env:
      - value: '0'
        name: NODE_TLS_REJECT_UNAUTHORIZED
  - id: ms-vscode/node-debug2/latest
    type: chePlugin
  - id: redhat/vscode-yaml/latest
    type: chePlugin
  - id: che-incubator/typescript/latest
    type: chePlugin
  - mountSources: true
    endpoints:
      - attributes:
          protocol: http
          public: 'true'
        name: theia-dev-flow
        port: 3010
    memoryLimit: 6Gi
    type: dockerimage
    image: 'quay.io/eclipse/che-theia-dev:next'
    alias: che-dev
    memoryRequest: 2Gi
    env:
      - value: 2504;
        name: THEIA_PLUGIN_ENDPOINT_DISCOVERY_PORT
  - mountSources: true
    memoryLimit: 1Gi
    type: dockerimage
    image: 'quay.io/eclipse/che-theia-dev:next'
    alias: plugin-host
    env:
      - value: 2504;
        name: THEIA_PLUGIN_ENDPOINT_DISCOVERY_PORT
      - value: 'local-dir:///projects/plugins1/'
        name: THEIA_PLUGINS
      - value: /projects/java-11-openjdk
        name: JAVA_HOME
commands:
  - name: Run plugin host
    actions:
      - workdir: /projects/theia/che/che-theia/extensions/eclipse-che-theia-plugin-remote/lib/node
        type: exec
        command: node plugin-remote.js
        component: plugin-host
  - name: Debug plugin host
    actions:
      - workdir: /projects/theia/che/che-theia/extensions/eclipse-che-theia-plugin-remote/lib/node
        type: exec
        command: node --inspect-brk=8888 plugin-remote.js
        component: plugin-host
  - name: Run back end
    actions:
      - workdir: /projects/theia/examples/assembly
        type: exec
        command: 'yarn run start --hostname=0.0.0.0 --port=3010 --plugins=local-dir:/projects/theia/plugins'
        component: che-dev
  - name: Debug back end
    actions:
      - workdir: /projects/theia/examples/assembly
        type: exec
        command: 'yarn run start --inspect-brk=9999 --hosted-plugin-inspect=9339 --hostname=0.0.0.0 --port=3010 --plugins=local-dir:/projects/theia/plugins'
        component: che-dev
  - name: Debug Configs
    actions:
      - referenceContent: |
          {
            "name": "Attach to Plugin Host",
            "type": "node",
            "request": "attach",
            "port": 8888,
            "outFiles": [
                "/projects/theia/**/*.js"
            ]
          }, {
            "name": "Attach to Back End",
            "type": "node",
            "request": "attach",
            "port": 9999,
            "outFiles": [
                "/projects/theia/**/*.js"
            ]
          }
        type: vscode-launch
```

</details>

<details>

<summary>Machine exec sidecar logs </summary>

```
time="2021-02-22T13:09:47Z" level=info msg="Default 'info' log level is applied"
time="2021-02-22T13:09:47Z" level=info msg="Exec containers configuration:"
time="2021-02-22T13:09:47Z" level=info msg="==> Debug level info"
time="2021-02-22T13:09:47Z" level=info msg="==> Application url 127.0.0.1:4444"
time="2021-02-22T13:09:47Z" level=info msg="==> Absolute path to folder with static resources "
time="2021-02-22T13:09:47Z" level=info msg="==> Use bearer token: false"
time="2021-02-22T13:09:47Z" level=info msg="==> Pod selector: che.workspace_id=workspace66g6p6jduow9gdjs"
[GIN-debug] [WARNING] Creating an Engine instance with the Logger and Recovery middleware already attached.
[GIN-debug] [WARNING] Running in "debug" mode. Switch to "release" mode in production.
- using env: export GIN_MODE=release
- using code: gin.SetMode(gin.ReleaseMode)
[GIN-debug] GET /connect --> main.main.func2 (3 handlers)
[GIN-debug] GET /attach/:id --> main.main.func3 (3 handlers)
[GIN-debug] POST /exec/config --> main.main.func4 (3 handlers)
[GIN-debug] POST /exec/init --> main.main.func5 (3 handlers)
[GIN-debug] POST /activity/tick --> main.main.func6 (3 handlers)
[GIN-debug] GET /healthz --> main.main.func7 (3 handlers)
⇩ Registered RPCRoutes:
Json-rpc MachineExec Routes:
✓ create
✓ check
✓ resize
[GIN-debug] Listening and serving HTTP on 127.0.0.1:4444
[GIN] 2021/02/22 - 13:10:06 | 200 | 1.0851ms | 192.168.65.3 | GET /connect?token=eyJhbGciOiJSUzI1NiIsImtpbmQiOiJtYWNoaW5lX3Rva2VuIiwia2lkIjoid29ya3NwYWNlNjZnNnA2amR1b3c5Z2RqcyJ9.eyJ3c2lkIjoid29ya3NwYWNlNjZnNnA2amR1b3c5Z2RqcyIsInVpZCI6IjJmYjAxNmNlLTZlNjMtNGQ5Yi04MTE0LWExMTQ5MjY5OThjNiIsImF1ZCI6IndvcmtzcGFjZTY2ZzZwNmpkdW93OWdkanMiLCJuYmYiOi0xLCJ1bmFtZSI6ImFkbWluIiwiaXNzIjoid3NtYXN0ZXIiLCJleHAiOjE2NDU1MzUzMzAsImlhdCI6MTYxMzk5OTMzMCwianRpIjoiODc1NzU1ODUtODdiNS00MzIzLWIxNTMtMDJjYzBiMDhlMmI5In0.wo79uXrq8eXZ1r1IC60P0MAQgN_sAG0U3li-nQThiseGAoiVOTQtV7APKTnHqLIMiLjoDdMSEbX4kxfcUufdA3LeE9rjSbhRMX9CJBgECkMbZAgPzjLcFfxJUWoeyudNWISyKX8z7RluppIOaSU014IygXHu0pO9nCXlTfN_UWY57oULk_H6MRIKF6GW8zNTkHfQjjlQqcNVfyxbkiqa4RRpyk-3LASIJr97JDfgA1245sXiIcVHusJJk8DeQ8AcbstcaYF8ziZrasYIxx9ux_61jcd45shVDs4PTi9KHYkZn6XuCgDuJQqR6i0nmEoiy03tXquOfOqU5-JOShgJog
time="2021-02-22T13:10:08Z" level=info msg="[/bin/bash -c cd /projects; /bin/bash] is successfully initialized in user specified container workspace66g6p6jduow9gdjs.workspace-9585848c8-7zpxc/che-dev"
time="2021-02-22T13:10:08Z" level=info msg="[/bin/bash -c cd /projects; /bin/bash] is successfully initialized in user specified container workspace66g6p6jduow9gdjs.workspace-9585848c8-7zpxc/che-dev"
time="2021-02-22T13:10:08Z" level=info msg="[/bin/bash -c cd /projects; /bin/bash] is successfully initialized in user specified container workspace66g6p6jduow9gdjs.workspace-9585848c8-7zpxc/che-dev"
time="2021-02-22T13:10:09Z" level=info msg="[/bin/bash -c cd /projects; /bin/bash] is successfully initialized in user specified container workspace66g6p6jduow9gdjs.workspace-9585848c8-7zpxc/che-dev"
time="2021-02-22T13:10:09Z" level=info msg="[/bin/bash -c cd /projects; /bin/bash] is successfully initialized in user specified container workspace66g6p6jduow9gdjs.workspace-9585848c8-7zpxc/che-dev"
[GIN] 2021/02/22 - 13:10:32 | 200 | 197.2µs | 192.168.65.3 | GET /connect?token=eyJhbGciOiJSUzI1NiIsImtpbmQiOiJtYWNoaW5lX3Rva2VuIiwia2lkIjoid29ya3NwYWNlNjZnNnA2amR1b3c5Z2RqcyJ9.eyJ3c2lkIjoid29ya3NwYWNlNjZnNnA2amR1b3c5Z2RqcyIsInVpZCI6IjJmYjAxNmNlLTZlNjMtNGQ5Yi04MTE0LWExMTQ5MjY5OThjNiIsImF1ZCI6IndvcmtzcGFjZTY2ZzZwNmpkdW93OWdkanMiLCJuYmYiOi0xLCJ1bmFtZSI6ImFkbWluIiwiaXNzIjoid3NtYXN0ZXIiLCJleHAiOjE2NDU1MzUzMzAsImlhdCI6MTYxMzk5OTMzMCwianRpIjoiODc1NzU1ODUtODdiNS00MzIzLWIxNTMtMDJjYzBiMDhlMmI5In0.wo79uXrq8eXZ1r1IC60P0MAQgN_sAG0U3li-nQThiseGAoiVOTQtV7APKTnHqLIMiLjoDdMSEbX4kxfcUufdA3LeE9rjSbhRMX9CJBgECkMbZAgPzjLcFfxJUWoeyudNWISyKX8z7RluppIOaSU014IygXHu0pO9nCXlTfN_UWY57oULk_H6MRIKF6GW8zNTkHfQjjlQqcNVfyxbkiqa4RRpyk-3LASIJr97JDfgA1245sXiIcVHusJJk8DeQ8AcbstcaYF8ziZrasYIxx9ux_61jcd45shVDs4PTi9KHYkZn6XuCgDuJQqR6i0nmEoiy03tXquOfOqU5-JOShgJog
[GIN] 2021/02/22 - 13:18:00 | 400 | 103.3µs | 192.168.65.3 | GET /connect?token=eyJhbGciOiJSUzI1NiIsImtpbmQiOiJtYWNoaW5lX3Rva2VuIiwia2lkIjoid29ya3NwYWNlNjZnNnA2amR1b3c5Z2RqcyJ9.eyJ3c2lkIjoid29ya3NwYWNlNjZnNnA2amR1b3c5Z2RqcyIsInVpZCI6IjJmYjAxNmNlLTZlNjMtNGQ5Yi04MTE0LWExMTQ5MjY5OThjNiIsImF1ZCI6IndvcmtzcGFjZTY2ZzZwNmpkdW93OWdkanMiLCJuYmYiOi0xLCJ1bmFtZSI6ImFkbWluIiwiaXNzIjoid3NtYXN0ZXIiLCJleHAiOjE2NDU1MzUzMzAsImlhdCI6MTYxMzk5OTMzMCwianRpIjoiODc1NzU1ODUtODdiNS00MzIzLWIxNTMtMDJjYzBiMDhlMmI5In0.wo79uXrq8eXZ1r1IC60P0MAQgN_sAG0U3li-nQThiseGAoiVOTQtV7APKTnHqLIMiLjoDdMSEbX4kxfcUufdA3LeE9rjSbhRMX9CJBgECkMbZAgPzjLcFfxJUWoeyudNWISyKX8z7RluppIOaSU014IygXHu0pO9nCXlTfN_UWY57oULk_H6MRIKF6GW8zNTkHfQjjlQqcNVfyxbkiqa4RRpyk-3LASIJr97JDfgA1245sXiIcVHusJJk8DeQ8AcbstcaYF8ziZrasYIxx9ux_61jcd45shVDs4PTi9KHYkZn6XuCgDuJQqR6i0nmEoiy03tXquOfOqU5-JOShgJog
[GIN] 2021/02/22 - 13:18:10 | 400 | 35.7µs | 192.168.65.3 | GET /connect?token=eyJhbGciOiJSUzI1NiIsImtpbmQiOiJtYWNoaW5lX3Rva2VuIiwia2lkIjoid29ya3NwYWNlNjZnNnA2amR1b3c5Z2RqcyJ9.eyJ3c2lkIjoid29ya3NwYWNlNjZnNnA2amR1b3c5Z2RqcyIsInVpZCI6IjJmYjAxNmNlLTZlNjMtNGQ5Yi04MTE0LWExMTQ5MjY5OThjNiIsImF1ZCI6IndvcmtzcGFjZTY2ZzZwNmpkdW93OWdkanMiLCJuYmYiOi0xLCJ1bmFtZSI6ImFkbWluIiwiaXNzIjoid3NtYXN0ZXIiLCJleHAiOjE2NDU1MzUzMzAsImlhdCI6MTYxMzk5OTMzMCwianRpIjoiODc1NzU1ODUtODdiNS00MzIzLWIxNTMtMDJjYzBiMDhlMmI5In0.wo79uXrq8eXZ1r1IC60P0MAQgN_sAG0U3li-nQThiseGAoiVOTQtV7APKTnHqLIMiLjoDdMSEbX4kxfcUufdA3LeE9rjSbhRMX9CJBgECkMbZAgPzjLcFfxJUWoeyudNWISyKX8z7RluppIOaSU014IygXHu0pO9nCXlTfN_UWY57oULk_H6MRIKF6GW8zNTkHfQjjlQqcNVfyxbkiqa4RRpyk-3LASIJr97JDfgA1245sXiIcVHusJJk8DeQ8AcbstcaYF8ziZrasYIxx9ux_61jcd45shVDs4PTi9KHYkZn6XuCgDuJQqR6i0nmEoiy03tXquOfOqU5-JOShgJog
[GIN] 2021/02/22 - 13:19:32 | 200 | 196.6µs | 192.168.65.3 | GET /connect?token=eyJhbGciOiJSUzI1NiIsImtpbmQiOiJtYWNoaW5lX3Rva2VuIiwia2lkIjoid29ya3NwYWNlNjZnNnA2amR1b3c5Z2RqcyJ9.eyJ3c2lkIjoid29ya3NwYWNlNjZnNnA2amR1b3c5Z2RqcyIsInVpZCI6IjJmYjAxNmNlLTZlNjMtNGQ5Yi04MTE0LWExMTQ5MjY5OThjNiIsImF1ZCI6IndvcmtzcGFjZTY2ZzZwNmpkdW93OWdkanMiLCJuYmYiOi0xLCJ1bmFtZSI6ImFkbWluIiwiaXNzIjoid3NtYXN0ZXIiLCJleHAiOjE2NDU1MzUzMzAsImlhdCI6MTYxMzk5OTMzMCwianRpIjoiODc1NzU1ODUtODdiNS00MzIzLWIxNTMtMDJjYzBiMDhlMmI5In0.wo79uXrq8eXZ1r1IC60P0MAQgN_sAG0U3li-nQThiseGAoiVOTQtV7APKTnHqLIMiLjoDdMSEbX4kxfcUufdA3LeE9rjSbhRMX9CJBgECkMbZAgPzjLcFfxJUWoeyudNWISyKX8z7RluppIOaSU014IygXHu0pO9nCXlTfN_UWY57oULk_H6MRIKF6GW8zNTkHfQjjlQqcNVfyxbkiqa4RRpyk-3LASIJr97JDfgA1245sXiIcVHusJJk8DeQ8AcbstcaYF8ziZrasYIxx9ux_61jcd45shVDs4PTi9KHYkZn6XuCgDuJQqR6i0nmEoiy03tXquOfOqU5-JOShgJog
time="2021-02-22T13:19:33Z" level=info msg="[/bin/bash -c cd /projects; /bin/bash] is successfully initialized in user specified container workspace66g6p6jduow9gdjs.workspace-9585848c8-7zpxc/che-dev"
time="2021-02-22T13:19:35Z" level=info msg="[/bin/bash -c cd /projects; /bin/bash] is successfully initialized in user specified container workspace66g6p6jduow9gdjs.workspace-9585848c8-7zpxc/che-dev"
[GIN] 2021/02/22 - 13:19:40 | 200 | 209.2µs | 192.168.65.3 | GET /connect?token=eyJhbGciOiJSUzI1NiIsImtpbmQiOiJtYWNoaW5lX3Rva2VuIiwia2lkIjoid29ya3NwYWNlNjZnNnA2amR1b3c5Z2RqcyJ9.eyJ3c2lkIjoid29ya3NwYWNlNjZnNnA2amR1b3c5Z2RqcyIsInVpZCI6IjJmYjAxNmNlLTZlNjMtNGQ5Yi04MTE0LWExMTQ5MjY5OThjNiIsImF1ZCI6IndvcmtzcGFjZTY2ZzZwNmpkdW93OWdkanMiLCJuYmYiOi0xLCJ1bmFtZSI6ImFkbWluIiwiaXNzIjoid3NtYXN0ZXIiLCJleHAiOjE2NDU1MzUzMzAsImlhdCI6MTYxMzk5OTMzMCwianRpIjoiODc1NzU1ODUtODdiNS00MzIzLWIxNTMtMDJjYzBiMDhlMmI5In0.wo79uXrq8eXZ1r1IC60P0MAQgN_sAG0U3li-nQThiseGAoiVOTQtV7APKTnHqLIMiLjoDdMSEbX4kxfcUufdA3LeE9rjSbhRMX9CJBgECkMbZAgPzjLcFfxJUWoeyudNWISyKX8z7RluppIOaSU014IygXHu0pO9nCXlTfN_UWY57oULk_H6MRIKF6GW8zNTkHfQjjlQqcNVfyxbkiqa4RRpyk-3LASIJr97JDfgA1245sXiIcVHusJJk8DeQ8AcbstcaYF8ziZrasYIxx9ux_61jcd45shVDs4PTi9KHYkZn6XuCgDuJQqR6i0nmEoiy03tXquOfOqU5-JOShgJog
time="2021-02-22T
```

</details>

### Steps to reproduce
1. Open the workspace
2. Click on the "open terminal" link in the "workspace" sidebar

### Expected behavior
The terminal should work.

### Runtime

   - [ ] docker-desktop + K8S (include output of `docker version` and `kubectl version`) v20.10.2
   - [ ] other: (please specify)

### Installation method
   - [ ] chectl update
  

### Environment
   - [ ] my computer
       - [x] Windows
       - [ ] Linux
       - [ ] macOS
   - [ ] Cloud
       - [ ] Amazon
       - [ ] Azure
       - [ ] GCE
       - [ ] other (please specify)
   - [ ] other: please specify
