### ISSUE TITLE
[devfile-registry] Links (index.json, devfile.yaml) are not correct in Single Host mode

### ISSUE THREAD

**Issue by olexii4** [eclipse-che/che#19140]
### Describe the bug
index.json and devfile.yaml of devfile registry has absolute links which are wrong in Che Single-Host mode.
To make it working, Dashboard needs to workaround this issue in resolving link against Devfile Registry URL https://github.com/eclipse/che-dashboard/pull/176

Since Che has single host mode, each component should be adapted to share the host with others and in such case we cannot use  'From the Root' links, we should use 'Fully Qualified' or 'Relative' paths for all resources. 

### Che version

 - [x] latest
 - [ ] nightly
 - [ ] other: please specify

### Steps to reproduce

1. Deploy Single Host Che with the following CheCluster patch
```yaml
# save the content to /tmp/che-custom-che-server.yaml and execute the following:
# chectl server:deploy --installer=operator --platform=minikube --che-operator-cr-patch-yaml=/tmp/che-custom-che-server.yaml
spec:
  k8s: 
    singleHostExposureType: 'gateway'
  server:
    serverExposureStrategy: single-host
```
2. Open Devfile registry URL and make sure it's a absolute path which won't work when you use it, in the way it's supposed to be used (append path to the current host).

### Expected behavior
index.json and devfile.yaml have correct links.

### Runtime
   - [x] kubernetes (include output of `kubectl version`)
   - [ ] Openshift (include output of `oc version`)
   - [ ] minikube (include output of `minikube version` and `kubectl version`)
   - [ ] minishift (include output of `minishift version` and `oc version`)
   - [ ] docker-desktop + K8S (include output of `docker version` and `kubectl version`)
   - [ ] other: (please specify)

### Installation method
   - [x] chectl
     * provide a full command that was used to deploy Eclipse Che (including the output)
     * provide an output of `chectl version` command
   - [ ] OperatorHub
   - [ ] I don't know

### Environment
   - [ ] my computer
       - [ ] Windows
       - [x] Linux
       - [ ] macOS
   - [ ] Cloud
       - [ ] Amazon
       - [ ] Azure
       - [ ] GCE
       - [ ] other (please specify)
   - [ ] other: please specify

**Comment by benoitf** [comment]
hello, could you please give an example of links that are incorrect ?

**Comment by sleshchenko** [comment]
@benoitf it's not related to OpenShift templates and platform does not matter, it depends on Single Host. You can try to deploy with the following CheCluster Patch:
```
# save the content to /tmp/che-custom-che-server.yaml and execute the following:
# chectl server:deploy --installer=operator --platform=minikube --che-operator-cr-patch-yaml=/tmp/che-custom-che-server.yaml
spec:
  k8s: 
    singleHostExposureType: 'gateway'
  server:
    serverExposureStrategy: single-host
```

Che Devfile Registry will be available at `$host/devfile-registry/devfiles`
Links in index.json and meta.yaml are root-relative URL like `icon: /images/dotnetcore.svg` or `self:  /devfiles/dotnet/devfile.yaml`
Which since they are root-relative URL should be resolved by browser as `$host/images/dotnetcore.svg` which is not correct, while the right is `$host/devfile-registry/images/dotnetcore.svg`.

Does it make sense?
