### ISSUE TITLE
Improvements to devfile v2 factory flow support

### ISSUE THREAD

**Issue by sleshchenko** [eclipse-che/che#19147]
### Is your enhancement related to a problem? Please describe.
https://github.com/eclipse/che-dashboard/pull/175 partially implements factory flow, but some places should be improved, reworked:
1. Namespace should be created if it does not exist.
2. Specify the routing class `che`.
3. Default editors and plugins should be propagated to the DevWorkspace CR namespace, we should not rely on the DevWorkspaceTemplate registry, like we have after PR
```yaml
    - name: theia-next
      plugin:
        kubernetes:
          name: theia-next
          namespace: devworkspace-plugins
    - name: machine-exec
      plugin:
        kubernetes:
          name: machine-exec
          namespace: devworkspace-plugins
```
