### ISSUE TITLE
[plugins] Cannot read property 'getExtension' of vscode.extensions

### ISSUE THREAD

**Issue by svor** [eclipse-che/che#19172]
### Describe
This task is to investigate the problem why it is not possible to get extensions when trying to run tests of a vscode extension on top of che-theia, in other words`vscode.extensions.getExtension(id)` returns `Cannot read property 'getExtension' of undefined`.

It is needed for https://github.com/eclipse/che/issues/18219.

### Che version

 - [x] latest
 - [ ] nightly
 - [ ] other: please specify

### Steps to reproduce
1. Create a workspace from
```yaml
apiVersion: 1.0.0
metadata:
  name: che-helloworld-test-sample
components:
  - mountSources: true
    memoryLimit: 3Gi
    type: dockerimage
    image: 'quay.io/eclipse/che-theia-dev:next'
    alias: che-dev
  - type: chePlugin
    reference: 'https://raw.githubusercontent.com/svor/che-vscode-extension-tests/main/meta.yaml'
  - id: timonwong/shellcheck/latest
    type: chePlugin
  - id: eclipse/che-theia/next
    memoryLimit: 1024Mi
    type: cheEditor
```
2. Open theia-ide terminal and clone https://github.com/timonwong/vscode-shellcheck.git into /tmp
3. Go to /tmp/vscode/shellcheck and compile the extension (yarn install, yarn compile)
4. Copy /tmp/vscode/shellcheck into /projects (cp -r /tmp/vscode/shellcheck /projects)
5. Try to run tests from the extension by executing `Run VS Code extension tests` command (F1 -> Run VS Code extension tests)

**Another way with vscode extension:**
1. Create a workspace from
```yaml
apiVersion: 1.0.0
metadata:
  name: extension-test-sample
projects:
  - name: extension-tests-runner
    source:
      location: 'https://github.com/svor/extension-tests-runner.git'
      type: git
components:
  - mountSources: true
    memoryLimit: 3Gi
    type: dockerimage
    image: 'quay.io/eclipse/che-theia-dev:next'
    alias: che-dev
  - type: chePlugin
    reference: 'https://raw.githubusercontent.com/svor/extension-tests-runner/main/meta.yaml'
  - id: ms-vscode/node-debug2/latest
    type: chePlugin
```
2. Open theia-ide terminal and go to `/projects/extension-tests-runner` 
3. Run `yarn` and `yarn compile`
4. Run tests from /projects/extension-tests-runner by executing a command: F1 -> Run VSCode Extension's Tests From /projects  

### Runtime
   - [ ] kubernetes (include output of `kubectl version`)
   - [ ] Openshift (include output of `oc version`)
   - [x] minikube (include output of `minikube version` and `kubectl version`)
   - [ ] minishift (include output of `minishift version` and `oc version`)
   - [ ] docker-desktop + K8S (include output of `docker version` and `kubectl version`)
   - [ ] other: (please specify)

### Screenshots

![screenshot-che-dogfooding apps che-dev x6e0 p1 openshiftapps com-2021 03 01-14_20_08](https://user-images.githubusercontent.com/1271546/109496394-43bd5a80-7a99-11eb-80d9-86fa21cdcaa4.png)

### Installation method
   - [x] chectl
     * provide a full command that was used to deploy Eclipse Che (including the output)
     * provide an output of `chectl version` command
   - [ ] OperatorHub
   - [ ] I don't know

### Environment
   - [x] my computer
       - [ ] Windows
       - [x] Linux
       - [ ] macOS
   - [ ] Cloud
       - [ ] Amazon
       - [ ] Azure
       - [ ] GCE
       - [ ] other (please specify)
   - [ ] other: please specify
