### ISSUE TITLE
Support for async storage with DevWorkspace

### ISSUE THREAD

**Issue by l0rd** [eclipse-che/che#19194]
### Is your enhancement related to a problem? Please describe.

Workspaces started with the DevWorkspace operator do not support storage of type async. 

### Describe the solution you'd like

Devfile v2 spec doesn't support async storage. We can use the `DevWorkspace` CRD metadata annotations:

```yaml
metadata:
  annotations:
    storageType: [common|async|ephemeral]
```
