### ISSUE TITLE
Che is trying to create the mkdir container for Ephemeral storage, workspace loading in more than 1 minute

### ISSUE THREAD

**Issue by vladiacob** [eclipse-che/che#19227]
### Describe the bug
When you open a workspace with ephemeral storage the loading time is more than 1 minute and the following errors/events are displayed in the logs: 
```
6m55s       Warning   FailedScheduling         pod/mkdir-workspacey05nr3yuxczlzxmq                                   error while running "VolumeBinding" prebind plugin for pod "mkdir-workspacey05nr3yuxczlzxmq": Failed to bind volumes: pod "che-workspaces/mkdir-workspacey05nr3yuxczlzxmq" does not exist any more
6m51s       Normal    Scheduled                pod/mkdir-workspacey05nr3yuxczlzxmq                                   Successfully assigned che-workspaces/mkdir-workspacey05nr3yuxczlzxmq to ip-172-20-59-11.eu-west-2.compute.internal
6m48s       Normal    SuccessfulAttachVolume   pod/mkdir-workspacey05nr3yuxczlzxmq                                   AttachVolume.Attach succeeded for volume "pvc-e343bfac-3ab9-4165-baf7-5573bfe022f1"
6m41s       Normal    Pulling                  pod/mkdir-workspacey05nr3yuxczlzxmq                                   Pulling image "registry.access.redhat.com/ubi8-minimal:8.3-230"
6m39s       Normal    Pulled                   pod/mkdir-workspacey05nr3yuxczlzxmq                                   Successfully pulled image "registry.access.redhat.com/ubi8-minimal:8.3-230" in 1.691683603s
6m39s       Normal    Created                  pod/mkdir-workspacey05nr3yuxczlzxmq                                   Created container mkdir-workspacey05nr3yuxczlzxmq
6m39s       Normal    Started                  pod/mkdir-workspacey05nr3yuxczlzxmq                                   Started container mkdir-workspacey05nr3yuxczlzxmq
```
From what I understood an workspace with Ephemeral storage is loading in less than 30 seconds and mkdir container is not used.

### Che version
 - [ ] latest
 - [ ] nightly
 - [x] other: 7.26.1

### Steps to reproduce
Create a new workspace with Ephemeral storage, which is happening with any DevFile.

### Expected behavior
To have the workspace loaded in second without any events related to mkdir container.

### Runtime
   - [x] kubernetes (include output of `kubectl version`)
   - [ ] Openshift (include output of `oc version`)
   - [ ] minikube (include output of `minikube version` and `kubectl version`)
   - [ ] minishift (include output of `minishift version` and `oc version`)
   - [ ] docker-desktop + K8S (include output of `docker version` and `kubectl version`)
   - [ ] other: (please specify)

### Installation method
   - [x] chectl
     * provide a full command that was used to deploy Eclipse Che (including the output)
     * provide an output of `chectl version` command
   - [ ] OperatorHub
   - [ ] I don't know

### Environment
   - [ ] my computer
       - [ ] Windows
       - [ ] Linux
       - [ ] macOS
   - [x] Cloud
       - [x] Amazon
       - [ ] Azure
       - [ ] GCE
       - [ ] other (please specify)
   - [ ] other: please specify

### Eclipse Che Logs
[events.txt](https://github.com/eclipse/che/files/6099684/events.txt)

**Comment by vladiacob** [comment]
Any idea how can I solve this?

**Comment by amisevsk** [comment]
Are you sure the workspace is ephemeral? [This](https://github.com/eclipse/che/blob/7.26.1/infrastructures/kubernetes/src/main/java/org/eclipse/che/workspace/infrastructure/kubernetes/namespace/pvc/CommonPVCStrategy.java#L221-L222) is the line that triggers the mkdir pod, but it should never be reached due to [this check](https://github.com/eclipse/che/blob/7.26.1/infrastructures/kubernetes/src/main/java/org/eclipse/che/workspace/infrastructure/kubernetes/namespace/pvc/CommonPVCStrategy.java#L185-L187) earlier in the function. 

@vladiacob could you share the devfile you are using?

**Comment by vladiacob** [comment]
Sure, I will share it. But I'm 100% it's Ephemeral because I see it on the interface and also on AWS I don't have any new volume created.

**Comment by vladiacob** [comment]
```
---
apiVersion: 1.0.0
metadata:
  generateName: app-
attributes:
  persistVolumes: 'false'
projects:
  - name: app
    source:
      type: git
      location: '{{gitRepo}}'
components:
  - alias: theia-editor
    type: cheEditor
    id: eclipse/che-theia/latest
    memoryLimit: 2048Mi
    memoryRequest: 512Mi
    cpuLimit: 3
    cpuRequest: 10m
  - type: chePlugin
    id: vscode/typescript-language-features/latest
    memoryLimit: 1024Mi
    memoryRequest: 256Mi
    cpuLimit: 2
    cpuRequest: 10m
  - type: chePlugin
    id: angular/ng-template/latest
    memoryLimit: 2048Mi
    memoryRequest: 256Mi
    cpuLimit: 2
    cpuRequest: 10m
  - type: dockerimage
    alias: application
    image: 'x/che-nodejs-project:7.26.1'
    memoryLimit: 2048Mi
    memoryRequest: 512Mi
    cpuLimit: 3
    cpuRequest: 10m
    endpoints:
      - name: YourApplication
        port: 3000
    mountSources: true
  - type: dockerimage
    alias: auto-commiter
    image: 'x/auto-commit-agent:latest'
    memoryLimit: 512Mi
    memoryRequest: 128Mi
    cpuLimit: 1
    cpuRequest: 10m
    endpoints:
      - name: CodeAutoCommit
        port: 50050
    mountSources: true
  - type: dockerimage
    alias: tests-runner
    image: 'x/x-project-tests-runner:latest'
    memoryLimit: 2048Mi
    memoryRequest: 256Mi
    cpuLimit: 2
    cpuRequest: 10m
    endpoints:
      - name: TestsRunner
        port: 50040
    mountSources: false
commands:
  - name: Install dependencies
    actions:
      - type: exec
        component: application
        command: npm install
        workdir: '${CHE_PROJECTS_ROOT}/app'
  - name: Restart the application
    actions:
      - type: exec
        component: application
        command: supervisorctl restart start-app
        workdir: '${CHE_PROJECTS_ROOT}/app'
  - name: Show logs
    actions:
      - type: exec
        component: application
        command: tail -f /tmp/app.log
        workdir: '${CHE_PROJECTS_ROOT}/app'
```

@amisevsk The Devfile used.

**Comment by amisevsk** [comment]
Hmm, well I'm kind of out of ideas -- I don't know why this would be happening and I don't have a convenient setup to debug it. Testing your devfile on workspaces.openshift.com does not reproduce the issue.

**Comment by vladiacob** [comment]
@amisevsk How much time it takes to load? In my environment with 7.26.1, it's around 1 minute. Also what version is on openshift?

**Comment by amisevsk** [comment]
@vladiacob I can't fully start your workspace, since the `angular/ng-template/latest` plugin is unavailable and the `x/<image>`s are I assume censored, but no `mkdir` container is created.

Does this issue reproduce for you with the devfile below? 
```yaml
apiVersion: 1.0.0
metadata:
  generateName: test-
attributes:
  persistVolumes: 'false'
components:
  - id: eclipse/che-theia/latest
    type: cheEditor
  - id: eclipse/che-machine-exec-plugin/latest
    type: chePlugin
```

If you're open to some CLI wrangling, what happens if you run `kubectl get po -w` in the namespace where the workspace is created while your workspace is staring up? e.g. my output for the devfile above is
```
NAME                                          READY   STATUS    RESTARTS   AGE
workspacelwct35wj571442cz.che-plugin-broker   0/1     Pending   0          0s
workspacelwct35wj571442cz.che-plugin-broker   0/1     Pending   0          0s
workspacelwct35wj571442cz.che-plugin-broker   0/1     ContainerCreating   0          0s
workspacelwct35wj571442cz.che-plugin-broker   0/1     ContainerCreating   0          3s
workspacelwct35wj571442cz.che-plugin-broker   0/1     Terminating         0          5s
workspacelwct35wj571442cz.che-plugin-broker   0/1     Terminating         0          5s
workspacelwct35wj571442cz.che-workspace-pod-f77576b8f-ldbv8   0/4     Pending             0          0s
workspacelwct35wj571442cz.che-workspace-pod-f77576b8f-ldbv8   0/4     Pending             0          0s
workspacelwct35wj571442cz.che-workspace-pod-f77576b8f-ldbv8   0/4     Init:0/2            0          0s
workspacelwct35wj571442cz.che-workspace-pod-f77576b8f-ldbv8   0/4     Init:0/2            0          2s
workspacelwct35wj571442cz.che-workspace-pod-f77576b8f-ldbv8   0/4     Init:0/2            0          3s
workspacelwct35wj571442cz.che-workspace-pod-f77576b8f-ldbv8   0/4     Init:1/2            0          4s
workspacelwct35wj571442cz.che-workspace-pod-f77576b8f-ldbv8   0/4     PodInitializing     0          6s
workspacelwct35wj571442cz.che-workspace-pod-f77576b8f-ldbv8   4/4     Running             0          12s
```
no mkdir pod is created here.

This is on https://workspaces.openshift.com/, which is running CRW `2.7.0.GA`, which is based off of `che @ 7a68a (7.26.3-SNAPSHOT)` (this is the tip of the 7.26.x branch)
