### ISSUE TITLE
Handle sidecar args in che-theia-plugins.yaml

### ISSUE THREAD

**Issue by ericwill** [eclipse-che/che#19231]
### Is your task related to a problem? Please describe.
Currently we have no way of generating `meta.yaml` files with sidecar args, for example:

```yaml
apiVersion: v2
publisher: ms-vscode
name: node-debug2
version: 1.42.3
type: VS Code extension
displayName: Node Debug
title: Node.js debugging support
description: Node Debug is the debugger for Node.js versions >= 8.0. Together with
  Node Debug (legacy) forms the Node.js debugging experience. https://marketplace.visualstudio.com/items?itemName=ms-vscode.node-debug2
icon: /v3/images/ms-vscode-node-debug2-icon.png
repository: https://github.com/Microsoft/vscode-node-debug2
category: Debugger
firstPublicationDate: '2020-06-23'
spec:
  containers:
  - image: "registry.redhat.io/codeready-workspaces/plugin-java8-rhel8:2.8"
    name: vscode-node-debug
    memoryLimit: '512Mi'
    args:
      - sh
      - -c
      - ${PLUGIN_REMOTE_ENDPOINT_EXECUTABLE}
  extensions:
  - https://download.jboss.org/jbosstools/vscode/3rdparty/vscode-node-debug/node-debug-1.41.1.vsix
  - https://download.jboss.org/jbosstools/vscode/3rdparty/vscode-node-debug2/node-debug2-1.42.3.vsix
```

### Describe the solution you'd like
Parse an `args` section of the `sidecar` definition located in `che-theia-plugins.yaml`. For example:
```yaml
- repository:
    url: 'https://github.com/Microsoft/vscode-node-debug2'
    revision: v1.42.3
  sidecar:
    image: "registry.redhat.io/codeready-workspaces/plugin-java8-rhel8:2.8"
    name: vscode-node-debug
    memoryLimit: 512Mi
    cpuLimit: 500m
    cpuRequest: 30m
    args:
      - sh
      - -c
      - ${PLUGIN_REMOTE_ENDPOINT_EXECUTABLE}
  extensions:
    - >-
      https://download.jboss.org/jbosstools/vscode/3rdparty/vscode-node-debug2/node-debug2-1.42.3.vsix
    - >-
      https://download.jboss.org/jbosstools/vscode/3rdparty/vscode-node-debug/node-debug-1.41.1.vsix
```

### Describe alternatives you've considered
N/A

### Additional context
Needed for plugin registry downstreaming work.
