### ISSUE TITLE
Che Theia devfile v2 does not contain theia container

### ISSUE THREAD

**Issue by sleshchenko** [eclipse-che/che#19301]
### Describe the bug
Che Theia devfile v2 does not contain theia container. Today when I used `quay.io/eclipse/che-plugin-registry:nightly`(quay.io/eclipse/che-plugin-registry@sha256:f0cd1864603d090dc01cfb60f508add74f439547929e2771309e87e2ed223d11) I got the following content with `$PLUGIN_REGISTRY/v3/plugins/eclipse/che-theia/next/devfile.yaml`:
```yaml
schemaVersion: 2.1.0
metadata:
  name: theia-ide
commands:
  - id: init-container-command
    apply:
      component: remote-runtime-injector
events:
  preStart:
    - init-container-command
components:
  - name: remote-endpoint
    volume:
      ephemeral: true
  - name: remote-runtime-injector
    container:
      image: 'quay.io/eclipse/che-theia-endpoint-runtime-binary:next'
      env:
        - name: PLUGIN_REMOTE_ENDPOINT_EXECUTABLE
          value: /remote-endpoint/plugin-remote-endpoint
        - name: REMOTE_ENDPOINT_VOLUME_NAME
          value: remote-endpoint
      volumeMounts:
        - name: remote-endpoint
          path: /remote-endpoint
```
