### ISSUE TITLE
Fail to start workspaces using a factory link (DevWorkspace engine enabled)

### ISSUE THREAD

**Issue by l0rd** [eclipse-che/che#19322]
### Describe the bug

<img width="1462" alt="image" src="https://user-images.githubusercontent.com/606959/111617460-695d9a00-87e3-11eb-84b0-8575305cc7fc.png">

When I try to start a workspace using a factory link it fails with "Getting workspace detail data failed. Error: Failed to update. Could not retrieve devworkspace status information from spring-petclinic in namespace l0rd-che."

### Che version

Nightly

### Steps to reproduce

Deploy Che, on OpenShift, with devworkspace support enabled

```bash
$ cat patch.yaml
spec:
  devWorkspace:
    enable: true
$ chectl server:deploy --che-operator-cr-patch-yaml=patch.yaml \
                     -p openshift --no-olm-suggested-namespace \
                     -n workspaces-server
```

Open a factory link

```bash
open ${CHE_URL}/#https://github.com/l0rd/spring-petclinic/tree/devfile2  # <== devfile v2.0.0 
```

### Runtime

OpenShift 4.7.1

### Installation method

```bash
$ chectl version
chectl/0.0.20210317-next.8a10103 darwin-x64 node-v12.21.0
```

### Environment

OpenShift dev cluster

### Other information

```yaml
$ k get dw
NAME               WORKSPACE ID                PHASE      INFO
spring-petclinic   workspace541792f585994771   Starting   Waiting for workspace routing objects

$ k get devworkspaceroutings
NAME                                AGE
routing-workspace541792f585994771   3m13s

$ k describe devworkspaceroutings
Name:         routing-workspace541792f585994771
Namespace:    l0rd-che
Labels:       controller.devfile.io/workspace_id=workspace541792f585994771
Annotations:  <none>
API Version:  controller.devfile.io/v1alpha1
Kind:         DevWorkspaceRouting
Metadata:
  Creation Timestamp:  2021-03-18T11:05:31Z
  Generation:          1
  Managed Fields:
    API Version:  controller.devfile.io/v1alpha1
    Fields Type:  FieldsV1
    fieldsV1:
      f:metadata:
        f:labels:
          .:
          f:controller.devfile.io/workspace_id:
        f:ownerReferences:
      f:spec:
        .:
        f:endpoints:
          .:
          f:che-machine-exec:
          f:theia-ide:
        f:podSelector:
          .:
          f:controller.devfile.io/workspace_id:
        f:routingClass:
        f:routingSuffix:
        f:workspaceId:
      f:status:
    Manager:    devworkspace-controller
    Operation:  Update
    Time:       2021-03-18T11:05:31Z
  Owner References:
    API Version:           workspace.devfile.io/v1alpha2
    Block Owner Deletion:  true
    Controller:            true
    Kind:                  DevWorkspace
    Name:                  spring-petclinic
    UID:                   541792f5-8599-4771-b93b-152b21331bb3
  Resource Version:        104542
  Self Link:               /apis/controller.devfile.io/v1alpha1/namespaces/l0rd-che/devworkspaceroutings/routing-workspace541792f585994771
  UID:                     ff315721-6b04-4f4c-9649-01c98ebdf9ab
Spec:
  Endpoints:
    Che - Machine - Exec:
      Attributes:
        Cookies Auth Enabled:  true
        Discoverable:          false
        Type:                  terminal
      Exposure:                public
      Name:                    che-machine-exec
      Protocol:                ws
      Target Port:             4444
    Theia - Ide:
      Attributes:
        Cookies Auth Enabled:  true
        Discoverable:          false
        Type:                  ide
      Exposure:                public
      Name:                    theia
      Protocol:                http
      Target Port:             3100
      Attributes:
        Cookies Auth Enabled:  true
        Discoverable:          false
        Type:                  webview
        Unique:                true
      Exposure:                public
      Name:                    webviews
      Protocol:                http
      Target Port:             3100
      Attributes:
        Cookies Auth Enabled:  true
        Discoverable:          false
        Type:                  mini-browser
        Unique:                true
      Exposure:                public
      Name:                    mini-browser
      Protocol:                http
      Target Port:             3100
      Attributes:
        Discoverable:  false
        Type:          ide-dev
      Exposure:        public
      Name:            theia-dev
      Protocol:        http
      Target Port:     3130
      Attributes:
        Discoverable:  false
      Exposure:        public
      Name:            theia-redirect-1
      Protocol:        http
      Target Port:     13131
      Attributes:
        Discoverable:  false
      Exposure:        public
      Name:            theia-redirect-2
      Protocol:        http
      Target Port:     13132
      Attributes:
        Discoverable:  false
      Exposure:        public
      Name:            theia-redirect-3
      Protocol:        http
      Target Port:     13133
      Attributes:
        Cookies Auth Enabled:  true
        Discoverable:          false
        Type:                  collocated-terminal
      Exposure:                public
      Name:                    terminal
      Protocol:                ws
      Target Port:             3333
  Pod Selector:
    controller.devfile.io/workspace_id:  workspace541792f585994771
  Routing Class:                         che
  Routing Suffix:                        apps.mloriedo-che-devex.devcluster.openshift.com
  Workspace Id:                          workspace541792f585994771
Events:                                  <none>
```
