### ISSUE TITLE
Migrate docker.io/vgulyy/che-theia-codeready-workspaces:next to quay.io and update che-theia-branding-example

### ISSUE THREAD

**Issue by themr0c** [eclipse-che/che#19344]
Following error happen when loading 
https://workspaces.openshift.com/f?url=https://raw.githubusercontent.com/che-samples/che-theia-branding-example/master/devfile.yaml :

>   Error when starting workspace
>    Unable to start workspace. Error when trying to start the workspace: Unrecoverable event occurred: 'Failed', 'Failed to pull image "docker.io/vgulyy/che-theia-codeready-workspaces:next": rpc error: code = Unknown desc = Error reading manifest next in docker.io/vgulyy/che-theia-codeready-workspaces: toomanyrequests: You have reached your pull rate limit. You may increase the limit by authenticating and upgrading: https://www.docker.com/increase-rate-limit', 'workspacem8i1w1vcorki3lk1.che-workspace-pod-6b7ff47447-65p6b'

See original discussion: https://github.com/eclipse/che-docs/pull/1866#discussion_r581216322_

**Comment by nickboldt** [comment]
Code to update after moving the image:
* https://github.com/che-samples/che-theia-branding-example/blob/master/che-editor.meta.yaml#L51

Image source: 
* https://github.com/che-samples/che-theia-branding-example/blob/master/Dockerfile ?

**Comment by nickboldt** [comment]
New images in quay: https://quay.io/repository/eclipse/che-theia-branding-example?tab=tags

PR to update branding example: https://github.com/che-samples/che-theia-branding-example/pull/1

**Comment by nickboldt** [comment]
* click link https://workspaces.openshift.com/f?url=https://raw.githubusercontent.com/che-samples/che-theia-branding-example/master/devfile.yaml 
* reload browser when SSO bug appears on login
* aaand crap, I had the wrong path to quay image. PR: https://github.com/che-samples/che-theia-branding-example/pull/2/files

**Comment by nickboldt** [comment]
@azatsarynnyy need you help here --- maybe the old theia branding example from 2019 doesn't work in latest theia? or we're missing something in the product.json file? 

Or do we need the patch file in the branding example image?

![image](https://user-images.githubusercontent.com/227597/111856613-57bee400-8902-11eb-8600-a64ae8d563fe.png)

https://github.com/redhat-developer/codeready-workspaces-theia/blob/crw-2-rhel-8/conf/theia/branding/loader/loader.patch

**Comment by vitaliy-guliy** [comment]
@nickboldt I played with branding example around a month ago. Everything was working as expected.

**Comment by vitaliy-guliy** [comment]
Have just checked it again.

Works fine with che-theia next and latest

Devfiles
che-theia:next

```
---
apiVersion: 1.0.0
metadata:
  generateName: test-branding-
projects:
  -
    name: che-theia
    source:
      type: git
      location: "https://github.com/eclipse/che-theia.git"
components:
  - type: cheEditor
    alias: che-theia
    reference: https://gist.githubusercontent.com/vitaliy-guliy/39c925936feec1e777f96a9c17b3a737/raw/e46d2fb5c3f4d3cd468bca61a9d11569dd69b474/meta.yaml
```

che-theia:latest
```
---
apiVersion: 1.0.0
metadata:
  generateName: test-branding-
projects:
  -
    name: che-theia
    source:
      type: git
      location: "https://github.com/eclipse/che-theia.git"
components:
  - type: cheEditor
    alias: che-theia
    reference: https://gist.githubusercontent.com/vitaliy-guliy/7da6c6a9f56931615c1373890fac0bcd/raw/cfde85f504e81efcb0068f73cc7dc652ff6f4303/meta.yaml
```
