### ISSUE TITLE
multiroot + sparseCheckoutDir should have sparseCheckoutDir as a workspace root

### ISSUE THREAD

**Issue by sunix** [eclipse-che/che#19370]
Part of https://github.com/eclipse/che/issues/15529

### Describe the bug
Enabling multiroot to the Quarkus devfile the Che devfile registry, the final project (sparseCheckoutDir is still not a workspace root. multiroot is taking.

https://github.com/eclipse/che-devfile-registry/blob/master/devfiles/quarkus/devfile.yaml#L11 
```yaml
projects:
  -
    name: quarkus-quickstarts
    source:
      type: git
      location: "https://github.com/quarkusio/quarkus-quickstarts.git"
      sparseCheckoutDir: getting-started
      branch: main
```
The default workspace root folder should be located in `/projects/quarkus-quickstarts/getting-started`.

I think we should consider sparseCheckoutDirs as workspace roots.

Another option is to be able to override root folders:
https://github.com/devfile/api/issues/385
```yaml
projects:
  - name: quarkus-quickstarts
    git:
      location: "https://github.com/quarkusio/quarkus-quickstarts.git"
      sparseCheckoutDirs: ['getting-started']
      branch: main
    roots: ['getting-started']
```
### Che version

 - [x] latest
 - [ ] nightly
 - [ ] other: please specify

### Steps to reproduce

1. Create a new workspace from the template `Quarkus Rest API`
2. Turn on multiroot
3. See the workspace root is `/projects/quarkus-quickstarts/` which is not right.

### Expected behavior
Workspace root folder should be `/projects/quarkus-quickstarts/getting-started`

### Runtime
   - [x] kubernetes (include output of `kubectl version`)
   - [ ] Openshift (include output of `oc version`)
   - [ ] minikube (include output of `minikube version` and `kubectl version`)
   - [ ] minishift (include output of `minishift version` and `oc version`)
   - [ ] docker-desktop + K8S (include output of `docker version` and `kubectl version`)
   - [ ] other: (please specify)

### Screenshots
![Selection_283](https://user-images.githubusercontent.com/650571/112125639-f037bb80-8bc3-11eb-89af-4c4ad67bba24.png)

### Installation method
   - [ ] chectl
     * provide a full command that was used to deploy Eclipse Che (including the output)
     * provide an output of `chectl version` command
   - [ ] OperatorHub
   - [ ] I don't know

### Environment
   - [ ] my computer
       - [ ] Windows
       - [ ] Linux
       - [ ] macOS
   - [x] Cloud
       - [ ] Amazon
       - [ ] Azure
       - [x] GCE
       - [ ] other (please specify)
   - [ ] Dev Sandbox (workspaces.openshift.com)
   - [ ] other: please specify

### Eclipse Che Logs
N/A

### Additional context
N/A
