### ISSUE TITLE
Project is not imported when using devfile v2 factory flow

### ISSUE THREAD

**Issue by l0rd** [eclipse-che/che#19371]
### Describe the bug

When I try to start a workspace (using a factory link that points to a devfile v2.0.0) the project source code is not cloned.

Note that the [v2 devfile I have used](https://github.com/l0rd/spring-petclinic/tree/devfile) doesn't have an explicit project.

In fact the `DevWorkspace` resource doesn't have `projects`:

```yaml
k get devworkspace spring-petclinic -o json | jq .spec.template
{
  "components": [
    {
      "container": {
        "env": [
          {
            "name": "ENV_VAR",
            "value": "value"
          }
        ],
        "image": "quay.io/eclipse/che-java8-maven:nightly",
        "memoryLimit": "1536M",
        "sourceMapping": "/projects",
        "volumeMounts": [
          {
            "name": "mavenrepo",
            "path": "/root/.m2"
          }
        ]
      },
      "name": "maven"
    },
    {
      "name": "mavenrepo",
      "volume": {
        "size": "1G"
      }
    },
    {
      "name": "theia-ide-workspace1b393472f4684f0b",
      "plugin": {
        "kubernetes": {
          "name": "theia-ide-workspace1b393472f4684f0b",
          "namespace": "l0rd-che"
        }
      }
    }
  ]
}
```

### Che version

Nightly

### Steps to reproduce

Deploy Che, on OpenShift, with devworkspace support enabled

```bash
$ cat patch.yaml
spec:
  devWorkspace:
    enable: true
$ chectl server:deploy --che-operator-cr-patch-yaml=patch.yaml \
                     -p openshift --no-olm-suggested-namespace \
                     -n workspaces-server
```

Open a factory link

```bash
open ${CHE_URL}/#https://github.com/l0rd/spring-petclinic/tree/devfile2  # <== devfile v2.0.0 
```

### Expected behavior

I would expect the source code from `https://github.com/l0rd/spring-petclinic/tree/devfile2` to be cloned in my workspace.

### Runtime

OpenShift 4.7.1

### Installation method

```
chectl/0.0.20210322-next.99b0d8c darwin-x64 node-v12.21.0
```

### Environment

OpenShift dev cluster
