### ISSUE TITLE
che-plugin-registry cannot replace image tag according to `CHE_SIDECAR_CONTAINERS_REGISTRY_URL`

### ISSUE THREAD

**Issue by wcho** [eclipse-che/che#19405]
### Describe the bug

che-plugin-registry does not replace image tag according to `CHE_SIDECAR_CONTAINERS_REGISTRY_URL`.
It seems that the replace process in che-plugin-registry `entrypoint.sh` does not work properly. Maybe due to invalid regex.

### Che version
 - [x] latest
 - [ ] nightly
 - [ ] other: please specify

### Steps to reproduce
I deployed CheCluster using `airGapContainerRegistryHostname` and `airGapContainerRegistryOrganization` with custom value.
It sets `CHE_SIDECAR_CONTAINERS_REGISTRY_URL` and `CHE_SIDECAR_CONTAINERS_REGISTRY_ORGANIZATION` for plugin-registry pod. But che-plugin-registry does not replace image tags in `meta.yaml` files.

### Expected behavior
Image tags in `meta.yaml` files should be replaced with provided registry and organization.

### Runtime
   - [x] kubernetes (include output of `kubectl version`)
   - [ ] Openshift (include output of `oc version`)
   - [ ] minikube (include output of `minikube version` and `kubectl version`)
   - [ ] minishift (include output of `minishift version` and `oc version`)
   - [ ] docker-desktop + K8S (include output of `docker version` and `kubectl version`)
   - [ ] other: (please specify)

### Installation method
   - [x] chectl
     * provide a full command that was used to deploy Eclipse Che (including the output)
     * provide an output of `chectl version` command
   - [ ] OperatorHub
   - [ ] I don't know

**Comment by cccs-eric** [comment]
Yes, I am running into the same issue as well.  I did some digging and this was introduced in version 7.26.0.   A single quote surrounding the image name got added by the build process.  See below:
**In image version 7.25.2**
```
/usr/local/apache2 # cat /var/www/html/v3/plugins/rust-lang/rust/latest/meta.yaml
apiVersion: v2
publisher: rust-lang
name: rust
version: latest
type: VS Code extension
displayName: Rust
title: Rust
description: Rust for Visual Studio Code (powered by Rust Language Server/Rust Analyzer).
  Provides lints, code completion and navigation, formatting and more.
icon: /v3/images/rust-lang-rust-icon.png
category: Programming Languages
repository: https://github.com/rust-lang/rls-vscode
firstPublicationDate: '2020-05-13'
spec:
  containers:
    - image: quay.io/eclipse/che-plugin-sidecar:rust-52f9e9a
      name: vscode-rust
      memoryLimit: 1024Mi
```
See no quote around `    - image: quay.io/eclipse/che-plugin-sidecar:rust-52f9e9a`

**In image version 7.26.0 up to now**
```
/usr/local/apache2 # cat /var/www/html/v3/plugins/rust-lang/rust/latest/meta.yaml
apiVersion: v2
publisher: rust-lang
name: rust
version: latest
type: VS Code extension
displayName: Rust
title: Rust
description: >-
  Rust for Visual Studio Code (powered by Rust Language Server/Rust Analyzer). Provides lints, code completion and
  navigation, formatting and more.
icon: /v3/images/rust-lang-rust-icon.png
category: Programming Languages
repository: 'https://github.com/rust-lang/rls-vscode'
firstPublicationDate: '2020-05-13'
latestUpdateDate: '2021-02-10'
spec:
  containers:
    - image: 'quay.io/eclipse/che-plugin-sidecar@sha256:e374ec367447afea9b12f5a8f6690a6f993526408a3731f522a53e5d0bfc287f'
      name: vscode-rust
      memoryLimit: 1Gi
```
We now have quotes surrounding `- image: 'quay.io/eclipse/che-plugin-sidecar@sha256:e374ec367447afea9b12f5a8f6690a6f993526408a3731f522a53e5d0bfc287f'`

The problem is with the [IMAGE_REGEX](https://github.com/eclipse-che/che-plugin-registry/blob/master/build/dockerfiles/entrypoint.sh#L38).  It is expecting double-quotes instead of single-quotes.  I am not sure if the build process should be writing out double-quotes or if the IMAGE_REGEX should be updated to support single-quotes?

**Comment by cccs-eric** [comment]
There is also another problem with this `IMAGE_REGEX`.  Once the `entrypoint.sh` script has run to replace the tags with sha256, some images are written as a multi-line entry.  So the resulting YAML looks like this (from `/usr/local/apache2/htdocs/v3/plugins/eclipse/che-theia/latest/meta.yaml`):

```
  initContainers:
    - name: remote-runtime-injector
      image: >-
        quay.io/eclipse/che-theia-endpoint-runtime-binary@sha256:b98f3cd34dbc8785df4ea7dc155339a66dcc72a3989d804e1990d6ad9f6d0168
      env:
        - name: PLUGIN_REMOTE_ENDPOINT_EXECUTABLE
          value: /remote-endpoint/plugin-remote-endpoint
        - name: REMOTE_ENDPOINT_VOLUME_NAME
          value: remote-endpoint
```
Notice `image: >-` which will not match the [code ](https://github.com/eclipse-che/che-plugin-registry/blob/master/build/dockerfiles/entrypoint.sh#L116) in `entrypoint.sh`.

Because of this, we end up with an init-container referencing a public image, which crashes the workspace creation process in an air-gapped setup.
