### ISSUE TITLE
Add to the Che doc clarification about impossibility to change project name using override parameters in the factory link

### ISSUE THREAD

**Issue by Ohrimenko1988** [eclipse-che/che#19415]
### Is your task related to a problem? Please describe.
It is impossible to override the project name using the factory link.
For example:
**Root devfile:**
```
apiVersion: 1.0.0
metadata:
  name: nodejs-xml
projects:
  - name: nodejs-web-app
    source:
      location: 'https://github.com/Ohrimenko1988/web-nodejs-sample.git'
      type: git
components:
  - id: redhat/vscode-xml/latest
    type: chePlugin
```
**Factory link with overriding:**
```
/f?url=https://gist.githubusercontent.com/Ohrimenko1988/3479628d5bcd3a4ec7135e228a12457e/raw/8883e4d038a0ebc2718ed1b1919ed802cabdd142/xmlPluginTest.yaml&override.metadata.generateName=changedWorkspaceName&override.projects.name=changedProjectName
```

As a result workspace name changed to the ```changedWorkspaceName```
But project name the same ```nodejs-web-app```

Looks like it is related to the thing that project name uses for the selection particular project
and overriding project parameters, for example branch:
```
&override.projects.web-java-spring-petclinic.source.branch=1.0.x
```
### Describe the solution you'd like

Add clarification about that to the documentation
