### ISSUE TITLE
Dashboard should reuse Che Server functionality for devfile v1 overrides

### ISSUE THREAD

**Issue by themr0c** [eclipse-che/che#19424]
Following docs at: https://www.eclipse.org/che/docs/che-7/end-user-guide/creating-a-workspace-from-remote-devfile/#overriding-devfile-values-using-factory-parameters_che

I adapted the example to have a clickable example:

https://<che-host>/f?url=https://github.com/maxandersen/quarkus-quickstarts/tree/che&override.projects.quarkus-quickstarts.source.branch=1.0.x

But the branch was not adapted:

```
apiVersion: 1.0.0
metadata:
  name: quarkus-quickstarts-spuc5
projects:
  - name: quarkus-quickstarts
    source:
      location: 'https://github.com/maxandersen/quarkus-quickstarts.git'
      type: github
      branch: che
```

**Update:**
It's caused by fact that a new Dashboard merge devfile on client side, which does not handle several cases:
- dots in attribute name;
- matching objects in arrays with name/id, like projects.<projectName>.source.branch
