### ISSUE TITLE
Dashboard (or other clients like chectl) should provide metadata about the origin of the devfile with DevWorkspace

### ISSUE THREAD

**Issue by benoitf** [eclipse-che/che#19430]
### Is your task related to a problem? Please describe.
When using DevWorkspace engine, we can use a factory workflow and then a workspace is created.
But devfile can be extracted from the cloned project or from an external locations.

IDE like CheTheia need to interact with the devfile.yaml stored in the project (if any).
But CheTheia is missing the information about the origin of the devfile used to create the workspace.

For example, we may prompt the user differently if we know the devfile used to create the DevWorkspace was not the one of the project, etc. 

### Describe the solution you'd like
Add the information inside the DevWorkspace object with information allowing to know if it comes from the project or from an external location.

**Comment by sleshchenko** [comment]
Agreed to start with annotation to indicate if devfile used for creation is resolved from a repository or raw content, raw content link. That would help Theia to understand when it's appropriate to suggest users update devfile in the repository.

**Comment by sleshchenko** [comment]
I propose the following values

1. Workspace is created with git repository:
```yaml
annotations:
  che.eclipse.org/devfile-source: svc
  che.eclipse.org/devfile-location: https://github.com/eclipse-che/che-dashboard
```
2. Workspace is created with devfile raw content link: 
```yaml
annotations:
  che.eclipse.org/devfile-source: url
  che.eclipse.org/devfile-location: https://raw.githubusercontent.com/eclipse-che/che-dashboard/main/devfile.yaml
```
3. Workspace is created with a sample:
```yaml
annotations:
  che.eclipse.org/devfile-source: sample
  che.eclipse.org/devfile-location: https://che-devfile-registry/devfiles/apache-camel-k
```
3. Workspace is created with with Devfile Editor, possible template:
```yaml
annotations:
  che.eclipse.org/devfile-source: custom # I'm fine with any better proposal here
```

@benoitf do you think it's sufficient as first step for Theia?

**Comment by benoitf** [comment]
@sleshchenko if I use for example `https://raw.githubusercontent.com/eclipse-che/che-dashboard/main/devfile.yaml` I might expect to see at the end the same information that the first link `https://github.com/eclipse-che/che-dashboard` ?

for the first link, what does `svc` mean ?

I think that in case of repository, we'll need branch name or sha1//etc

**Comment by benoitf** [comment]
also is it possible to have different types like

```yaml
annotations:
  che.eclipse.org/devfile-source:
      - git: 'https://github.com/eclipse-che/che-dashboard'
        revision: '1.2.3'
```


```yaml
annotations:
  che.eclipse.org/devfile-source:
      - url: https://gist/mydevfile.com
```

**Comment by sleshchenko** [comment]
> for the first link, what does svc mean ?

my fault. I meant [scm](https://github.com/eclipse-che/che-server/pull/5)

>  if I use for example https://raw.githubusercontent.com/eclipse-che/che-dashboard/main/devfile.yaml I might expect to see at the end the same information that the first link https://github.com/eclipse-che/che-dashboard ?

That really depends on how Che Server behaves here. Let me change example to pastebin link and we'll handle resolving rawcontent to repo separately.

> I think that in case of repository, we'll need branch name or sha1//etc

We can easily provide it but how you're going to use it? Won't you let users flush devfile changes against cluster if the change branch?

> also is it possible to have different types like

That's a good idea I haven't thought about, just clarification, it may be something like that
```
annotations:
  che.eclipse.org/devfile-source: >
      url:
        location: https://gist/mydevfile.com
```
```
annotations:
  che.eclipse.org/devfile-source: >
      scm:
        repo:
        revision: '1.2.3'
```
^ different objects fields (url, scm) would have different structures.
