### ISSUE TITLE
Define CheCluster v2alpha1

### ISSUE THREAD

**Issue by metlos** [eclipse-che/che#19449]
This is a subtask of #19448.

We need to define the `CheCluster` version `v2alpha1` that is going to be the configuration basis for the che aspects of DevWorkspace.

This version should contain all Devworkspace-related configuration options under `spec` and should keep all the che7-related configuration (basically the `CheCluster` v1) under `spec.che7`.

I image it could take the following form:

``` yaml
apiVersion: v2alpha1
kind: CheCluster
metadata:
  ...
spec:
  che7:
    ... all the options from CheCluster v1
  enabled: false
  che7Enabled: true
  gatewayHost: workspaces.acme.com
  gatewayEnabled: true
  ... related image names and other trivia
```

The first 3 options (`che7`, `enabled` and `che7enabled`) are there to temporarily to handle the coexistence of che7 server and devworkspace and should probably be removed in the future. The rest of the options is copied from the `CheManager` which is a temporary CRD used currently by DWCO (https://github.com/che-incubator/devworkspace-che-operator/blob/main/apis/che-controller/v1alpha1/component_types.go#L21).

We need to have the code for this CRD in a place that is consumable by both `che-operator` and `devworkspace-che-operator`.
