### ISSUE TITLE
Check single-to-multi root mode migration in Che-Theia

### ISSUE THREAD

**Issue by azatsarynnyy** [eclipse-che/che#19445]
### Is your task related to a problem? Please describe.
ATM it's not fully clear what will be the Che-Theia behavior when the multi-root mode will be enabled for an existing workspace, after upgrading to Che 7.29.0.

### Describe the solution you'd like
We need to validate the Che-Theia behavior for the following use case:
- create a new persisted workspace with several projects where the multi-root mode is off
- turn the multi-root mode on and restart the workspace
- make sure the explorer shows a correct projects structure

**Comment by azatsarynnyy** [comment]
I started a workspace from the following Devfile:
```yaml
apiVersion: 1.0.0
metadata:
  name: che-theia-all
projects:
  - name: che-theia
    source:
      location: 'https://github.com/eclipse-che/che-theia.git'
      type: git
  - name: theia
    source:
      location: 'https://github.com/eclipse-theia/theia.git'
      type: git
components:
  - id: eclipse/che-theia/latest
    type: cheEditor
```
Note, `eclipse/che-theia/latest` has the multi-root mode off, by default.

The project explorer displayed the projects' structure correctly:
![image](https://user-images.githubusercontent.com/1636395/114090852-a2f46300-98c0-11eb-8845-e8f11911ad1a.png)


Then, I switched to `eclipse/che-theia/next` (where the multi-root mode is on by default) and restarted the workspace.
Now, the project explorer is empty:
![image](https://user-images.githubusercontent.com/1636395/114091288-29a94000-98c1-11eb-8341-fea3b13dddd3.png)

We need to make the multi-root mode off by default while investigating this problem.
