### ISSUE TITLE
devfile-registry: python-django app cannot preview

### ISSUE THREAD

**Issue by sunix** [eclipse-che/che#19459]
### Describe the bug
Python Django devfile cannot preview the application.

### Che version

 - [x] latest
 - [ ] nightly
 - [ ] other: please specify

### Steps to reproduce
1. Start the Django Python devfile from the Get Started Page
2. Run these commands:
   - `set up venv`
   - `install dependencies`
   - `migrate`
   - `run server`
3. Che propose to open the preview
4. the preview fails to connect
5. Opening in a new tab works fine

### Expected behavior
It should show the right page in the preview panel

Could be fixed by setting X_FRAME_OPTIONS to allowall.
```yaml
  - name: run server
    actions:
      - workdir: '${CHE_PROJECTS_ROOT}/django-realworld-example-app'
        type: exec
        command: |
          . ${CHE_PROJECTS_ROOT}/.venv/bin/activate && export DEBUG_MODE=False && cp conduit/settings.py local_settings.py && echo "X_FRAME_OPTIONS = 'ALLOWALL'" >> local_settings.py && python manage.py runserver --settings local_settings 0.0.0.0:7000
        component: python
  - name: run server in debug mode
    actions:
      - workdir: '${CHE_PROJECTS_ROOT}/django-realworld-example-app'
        type: exec
        command: |
          . ${CHE_PROJECTS_ROOT}/.venv/bin/activate &&  export DEBUG_MODE=True && && cp conduit/settings.py local_settings.py && echo "X_FRAME_OPTIONS = 'ALLOWALL'" >> local_settings.py && python manage.py runserver --settings local_settings 0.0.0.0:7000 --noreload --nothreading
        component: python
```

### Runtime
   - [ ] kubernetes (include output of `kubectl version`)
   - [ ] Openshift (include output of `oc version`)
   - [ ] minikube (include output of `minikube version` and `kubectl version`)
   - [ ] minishift (include output of `minishift version` and `oc version`)
   - [ ] docker-desktop + K8S (include output of `docker version` and `kubectl version`)
   - [ ] other: (please specify)

### Screenshots
![Eclipse Che_302](https://user-images.githubusercontent.com/650571/112964552-ba0cb580-9148-11eb-86e1-adf7b25001f8.png)

### Installation method
   - [ ] chectl
     * provide a full command that was used to deploy Eclipse Che (including the output)
     * provide an output of `chectl version` command
   - [ ] OperatorHub
   - [ ] I don't know

### Environment
   - [ ] my computer
       - [ ] Windows
       - [ ] Linux
       - [ ] macOS
   - [ ] Cloud
       - [ ] Amazon
       - [ ] Azure
       - [ ] GCE
       - [ ] other (please specify)
   - [ ] Dev Sandbox (workspaces.openshift.com)
   - [ ] other: please specify
