### ISSUE TITLE
Che Theia (multi-root) fails to detect projects when they are cloned by another tool

### ISSUE THREAD

**Issue by amisevsk** [eclipse-che/che#19489]
### Describe the bug
When projects are cloned by an external tool, Che Theia (with multi-root enabled) will show 
> No projects are in the workspace yet

even though the proejcts are present in their expected folders. 

The `che.theia-workspace` file in `/projects` is also unpopulated:
```
$ cat che.theia-workspace
{"folders":[]}
```

Manually filling in the file with
```json
{
   "folders": [
      {
         "path": "web-nodejs-sample"
      },
   ]
}
```
causes workspace folders to appear as expected.

### Che version
 - [x] latest

### Steps to reproduce
If DevWorkspaces support is enabled, can be reproduced via the following DevWorkspace:
```yaml
cat <<EOF | kubectl apply -f -
kind: DevWorkspace
apiVersion: workspace.devfile.io/v1alpha2
metadata:
  name: theia
spec:
  started: true
  template:
    projects:
      - name: web-nodejs-sample
        git:
          remotes:
            origin: "https://github.com/che-samples/web-nodejs-sample.git"
    components:
      - name: theia
        plugin:
          uri: https://che-plugin-registry-main.surge.sh/v3/plugins/eclipse/che-theia/next/devfile.yaml
      - name: project-clone          
        container:
          cpuLimit: 50m
          cpuRequest: 5m
          image: quay.io/amisevsk/project-clone:dev
          memoryLimit: 200Mi
          memoryRequest: 64Mi
          mountSources: true
    commands:
      - id: clone-projects
        apply:
          component: project-clone
    events:
      prestart:
        - clone-projects
EOF
```

### Expected behavior
Che-Theia should detect that projects are already there and set up the multi-root workspace appropriately
