### ISSUE TITLE
[UD] Devworkspaces renaming

### ISSUE THREAD

**Issue by akurinnoy** [eclipse-che/che#19543]
### Is your enhancement related to a problem? Please describe.
The name of resources in K8s is immutable, which means we won't be able to rename workspaces if we use devworkspace engine.

### Describe the solution you'd like
So, we could work around it if we introduce a dedicated annotation for the display name, also we may want to have a description (it's kind of official way since OpenShift Console uses it for the projects stuff):
![Screenshot_20210414_180402](https://user-images.githubusercontent.com/5887312/114733232-d82f0400-9d4b-11eb-9227-0b0e6aec420c.png)
```yaml
kind: Project
apiVersion: project.openshift.io/v1
metadata:
  name: test
  annotations:
    openshift.io/description: Just test description
    openshift.io/display-name: It's my test namespace
```

### Describe alternatives you've considered
Don't allow users to rename devworkspaces.

### Additional context

https://github.com/eclipse/che-dashboard/pull/209 makes the Overview tab read-only for devworkspaces.
