### ISSUE TITLE
Impossible to use nodeSelector for Theia 

### ISSUE THREAD

**Issue by KOSSOKO** [eclipse-che/che#19570]
Hello we are trying to to use node selector.

We use che7.18.0 deployed with chectl on kubernetes 1.15

Following the documentation to add a nodeSelector https://www.eclipse.org/che/docs/che-7/installation-guide/configuring-workspaces-nodeselector/.

```
We have noticed that for the theia editor, the nodeSelector are not working. 
metadata:
  name: theia-nodeSelector
components:
  - referenceContent: |
      kind: List
      items:
        - apiVersion: v1
          kind: Pod
          metadata:
            name: ws
            labels:
              name: ws
          spec:
           containers:
            - name: maap-theia
              image: 'kosted/bmap-stack:0.2'
              imagePullPolicy: Always
              mountSources: true
              resources:
                limits:
                  memory: 2048Mi
              securityContext:
                privileged: true
    type: kubernetes
    volumes:
      - name: projects
        containerPath: /projects
    alias: maap-theia
    env:
      - value: 97262
        name: CLIENT_ID
      - value: VAL
        name: env
  - id: eclipse/che-theia/7.18.0
    type: cheEditor
    alias: theia-editor
  - id: eclipse/che-machine-exec-plugin/7.18.0
    type: chePlugin
    alias: exec-plugin
apiVersion: 1.0.0

```

For the follwing devFile, we use for jupyterlab we created it is working:

```
metadata:
  name: jupyterlab-2j907
attributes:
  editorFree: 'true'
components:
  - endpoints:
      - name: jupyter
        port: 3100
        attributes:
          type: ide
          discoverable: 'false'
          path: /
          protocol: http
          public: 'true'
    referenceContent: |
      kind: List
      items:
        - apiVersion: v1
          kind: Pod
          metadata:
            name: ws
            labels:
              name: ws
          spec:
           containers:
            - name: jupyter
              image: 'kosted/maap-esa-jupyterlab:0.0.6'
              imagePullPolicy: IfNotPresent
              mountSources: true
              resources:
                limits:
                  memory: 2048Mi
              securityContext:
                privileged: true
    type: kubernetes
    volumes:
      - name: projects
        containerPath: /projects
    alias: maap-jupyterlab
    env:
      - value: WS_JUPYTER
        name: MACHINE_NAME
      - value: /projects
        name: JUPYTER_NOTEBOOK_DIR
      - value: id
        name: CLIENT_ID
      - value: cid
        name: env
apiVersion: 1.0.0
```

Do you have a solution to enable the nodeSelector when using the theia editor please ?
