### ISSUE TITLE
WebSocket unexpected closing problem on DevSandbox during initializing Projector Client

### ISSUE THREAD

**Issue by vzhukovs** [eclipse-che/che#19577]
### Is your task related to a problem? Please describe.
For some reason, workspace [1] with configured JetBrains IDE using Projector breaks the websocket connection during Projector initialize on DevSandbox [2], which is not reproducible on Dogfooding instance [3]. Need to understand, what the reason causes this problem.

### Additional context
[1] Workspace configuration:
```yaml
apiVersion: 1.0.0
metadata:
  name: projector-idea-c
components:
  - type: cheEditor
    reference: 'https://gist.github.com/vzhukovs/5130e6a4d441b2eefc76a57ac5b994f5/raw/148eda63cc17b56921488f15823b4bfc5facca03/quay-io-che-projector-idea-c.yaml'
    alias: projector-idea-c
```
[2] https://workspaces.openshift.com/
[3] https://che-dogfooding.apps.che-dev.x6e0.p1.openshiftapps.com/dashboard/

Linked PRJ issue: https://youtrack.jetbrains.com/issue/PRJ-386
Linked PRJ issue: https://youtrack.jetbrains.com/issue/PRJ-241
