### ISSUE TITLE
Che - 7.28.2 | External Keycloak -  Error: Unable to get available storage types

### ISSUE THREAD

**Issue by andr-azeez** [eclipse-che/che#19611]
### Che version

 - [x] latest
 - [ ] nightly
 - [ ] other: please specify

### Steps to reproduce

`sudo chectl server:deploy --installer=helm --platform=k8s --domain=l3.domain.com --multiuser --installer=operator --che-operator-cr-patch-yaml=resource.yaml
`
### resource.yaml
````
apiVersion: org.eclipse.che/v1
kind: CheCluster
metadata:
  name: eclipse-che
spec:
  auth:
    externalIdentityProvider: true
    identityProviderURL: 'https://auth.domain.com'
    identityProviderRealm: 'Che'
    identityProviderClientId: 'che-public'

````

Installations are completed without any error. Once I login eclipse-che, I get this error as in screenshot

![Screenshot from 2021-04-16 07-23-38](https://user-images.githubusercontent.com/81161330/114960474-bf763980-9e84-11eb-8912-7caa4111cb27.png)
![Screenshot from 2021-04-16 07-23-59](https://user-images.githubusercontent.com/81161330/114960485-c43aed80-9e84-11eb-83a2-0bc024088053.png)

### Expected behavior

Launch the workspace with out any issue

### Runtime
   - [x] kubernetes (include output of `kubectl version`)
   - [ ] Openshift (include output of `oc version`)
   - [ ] minikube (include output of `minikube version` and `kubectl version`)
   - [ ] minishift (include output of `minishift version` and `oc version`)
   - [ ] docker-desktop + K8S (include output of `docker version` and `kubectl version`)
   - [ ] other: (please specify)

### Installation method
   - [x] chectl
     * provide a full command that was used to deploy Eclipse Che (including the output)
     * provide an output of `chectl version` command
   - [ ] OperatorHub
   - [ ] I don't know

### Environment
   - [ ] my computer
       - [ ] Windows
       - [x] Linux
       - [ ] macOS
   - [ ] Cloud
       - [x] Amazon
       - [ ] Azure
       - [ ] GCE
       - [ ] other (please specify)
   - [ ] Dev Sandbox (workspaces.openshift.com)
   - [ ] other: please specify
