### ISSUE TITLE
CheCluster `devfileRegistryURL` no longer applied

### ISSUE THREAD

**Issue by sunix** [eclipse-che/che#19627]
### Describe the bug
I tested recently `devfileRegistryURL` to add my custom external devfile registry. It was working fine but after few modification of the CheCluster CR, it is no longer applied.

### Che version

 - [x] latest 7.29.0
 - [ ] nightly
 - [ ] other: please specify

### Steps to reproduce
Not sure it is reproducible in other instance, I can help providing logs, etc.

In my case:
1. edit the CheCluster CR ```kubectl edit CheCluster/eclipse-che -n che```
2. in the server section:
    ```yaml
      server:
        devfileRegistryURL: https://sunix-sunix-che-devfile-registry.surge.sh
        externalDevfileRegistry: true
    ```
3. save and quit
4. look at the new resource `status` section.
    ```yaml
    status:
      cheClusterRunning: Available
      cheURL: https://che-che.chegcp.mychecluster.org
      cheVersion: 7.29.0
      dbProvisioned: true
      devfileRegistryURL: ""
    ```
`devfileRegistryURL` is empty

### Expected behavior
Should be 

```yaml
    status:
      cheClusterRunning: Available
      cheURL: https://che-che.chegcp.mychecluster.org
      cheVersion: 7.29.0
      dbProvisioned: true
      devfileRegistryURL: "https://sunix-sunix-che-devfile-registry.surge.sh"
```
### Runtime
   - [x] kubernetes (include output of `kubectl version`) GKE
   - [ ] Openshift (include output of `oc version`)
   - [ ] minikube (include output of `minikube version` and `kubectl version`)
   - [ ] minishift (include output of `minishift version` and `oc version`)
   - [ ] docker-desktop + K8S (include output of `docker version` and `kubectl version`)
   - [ ] other: (please specify)

### Screenshots
![Selection_335](https://user-images.githubusercontent.com/650571/115386719-0a23e880-a1da-11eb-9362-196b92ec5fb9.png)

### Installation method
   - [x] chectl 7.29.0
     * provide a full command that was used to deploy Eclipse Che (including the output)
     * provide an output of `chectl version` command
   - [ ] OperatorHub
   - [ ] I don't know

### Environment
   - [ ] my computer
       - [ ] Windows
       - [ ] Linux
       - [ ] macOS
   - [x] Cloud
       - [ ] Amazon
       - [ ] Azure
       - [x] GCE
       - [ ] other (please specify)
   - [ ] Dev Sandbox (workspaces.openshift.com)
   - [ ] other: please specify
