### ISSUE TITLE
With per-workspace PVC strategy the PVC should be deleted when the workspace is deleted

### ISSUE THREAD

**Issue by fcomte** [eclipse-che/che#19636]
### Is your enhancement related to a problem? Please describe.
I am using eclipse che with the pvc strategy per-workspace.
I am surprised that deleting a workspace does not delete the pvc.

Am I missing something?

### Describe the solution you'd like
I would like that deleting workspace , delete the pvc for this workspace ( with unique or per-workspace strategy)

**Comment by l0rd** [comment]
@fcomte the workspace data (the source code) is deleted but the PVC is not. Is that correct?

And please provide some information on the platform you are using (the kubernetes distribution, version, underlying OS) and the instructions to reproduce your problem (how you installed and configured Che, how you have started the workspace and how you have deleted it)?

**Comment by l0rd** [comment]
@skabashnyuk is this expected?

**Comment by fcomte** [comment]
@l0rd Thx for your reply and yes pvc is not deleted.

I am using the che operator on kubernetes 1.19.7 on bare metal debian.
I create the workspace with the eclipse che UI and delete it with the UI eclipse che

**Comment by skabashnyuk** [comment]
@l0rd no `PerWorkspacePVCStrategy` should delete them. We need more information about Che's setup and workspace configuration. Especially I'm interested in ephemeral mode configuration.

**Comment by fcomte** [comment]
```
Version
7.28.2
Browser Name
chrome
Browser Version
90.0.4430
Browser OS
Windows 10
```

By default our workspae are type persistent.

We installed che with the operator.

```
apiVersion: org.eclipse.che/v1
kind: CheCluster
metadata:
  name: eclipse-che
spec:
  auth:
    externalIdentityProvider: true
    identityProviderClientId: che
    identityProviderRealm: sspcloud
    identityProviderURL: XXX
    identityProviderAdminUserName: XXXX
  k8s:
    ingressDomain: XXX
  database:
    externalDb: false
  server:
    selfSignedCert: true
    gitSelfSignedCert: false
    tlsSupport: true
    workspaceNamespaceDefault: user-<username>
    cheHost: XXXXX
    devfileRegistryImage: XXXX
    customCheProperties:
      CHE_LIMITS_USER_WORKSPACES_RUN_COUNT: "-1"
      CHE_WORKSPACE_PROJECTS_STORAGE_DEFAULT_SIZE: "10Gi"
      CHE_WORKSPACE_DEFAULT__MEMORY__LIMIT__MB: "0"
      CHE_WORKSPACE_DEFAULT__MEMORY__REQUEST__MB: "1024"
  storage:
    pvcStrategy: "per-workspace"
    pvcClaimSize: "10Gi"
  metrics:
    enable: true
```

**Comment by skabashnyuk** [comment]
workspace devfile? Did you enable ephemeral mode ?

**Comment by fcomte** [comment]
this is a persistent workspace

```
apiVersion: 1.0.0
metadata:
  name: python-7pu7r
projects:
  - name: python-hello-world
    source:
      location: 'https://github.com/che-samples/python-hello-world.git'
      type: git
components:
  - id: ms-python/python/latest
    type: chePlugin
  - mountSources: true
    memoryLimit: 512Mi
    type: dockerimage
    image: 'quay.io/eclipse/che-python-3.8:nightly'
    alias: python
  - mountSources: true
    command:
      - tail
    args:
      - '-f'
      - /dev/null
    memoryLimit: 512Mi
    type: dockerimage
    image: 'inseefrlab/shelly:cloudshell'
    alias: cloudshell
commands:
  - name: run
    actions:
      - workdir: '${CHE_PROJECTS_ROOT}/python-hello-world'
        type: exec
        command: '. ${CHE_PROJECTS_ROOT}/.venv/bin/activate &&  python hello-world.py'
        component: python
  - name: set up venv
    actions:
      - workdir: '${CHE_PROJECTS_ROOT}/'
        type: exec
        command: python -m venv /projects/.venv
        component: python

```
