### ISSUE TITLE
Unable to persist projects and plugins when the devfile contains kubernetes components

### ISSUE THREAD

**Issue by vitaliy-guliy** [eclipse-che/che#19634]
### Describe the bug

Che-Theia needs to be able to change the devfile to
- add / remove projects
- add / remove plugins

Since Che-Theia was reworked to be using devfile V2, there is a service on the backend, that converts devfile V1 to devfile V2 and vice versa.

When the devfile V1 contains cheEidtor and kubernetes components, they are translated to devfilev2 components incorrectly.
Translating of cheEditor componens was partially fixed by https://github.com/eclipse-che/che-theia/pull/1084
Components with kubernetes type still translated as empty objects. 

Link with https://github.com/eclipse/che/issues/19623

### Che version

 - [x] nightly

### Steps to reproduce

1. Create a workspace from following devfile
2. Open Plugins view and install any plugin
```
---
apiVersion: 1.0.0
metadata:
  name: petclinic-dev-environment
projects:
  - name: petclinic
    source:
      type: git
      location: "https://github.com/spring-projects/spring-petclinic.git"
components:
  - type: cheEditor
    alias: che-theia
    reference: https://raw.githubusercontent.com/chepullreq4/pr-check-files/master/che-theia/pr-1084/che_theia_meta.yaml
    memoryLimit: 512Mi
  - type: kubernetes
    alias: petclinic-web
    reference: https://raw.githubusercontent.com/eclipse/che/master/tests/e2e/files/happy-path/containers-happy-path.yaml
    selector:
      app.kubernetes.io/component: webapp
    entrypoints:
      - containerName: spring-boot
        command: ["tail"]
        args: ["-f", "/dev/null"]
  - type: kubernetes
    alias: petclinic-db
    reference: https://raw.githubusercontent.com/eclipse/che/master/tests/e2e/files/happy-path/containers-happy-path.yaml
    selector:
      app.kubernetes.io/component: database
  - type: dockerimage
    alias: maven-container
    image: quay.io/eclipse/happy-path:nightly
    env:
      - name: MAVEN_CONFIG
        value: /home/user/.m2
    memoryLimit: 1500Mi
    mountSources: true
  - type: chePlugin
    id: redhat/java/latest
    memoryLimit: "1000Mi"
    preferences:
      java.server.launchMode: Standard
  - type: chePlugin
    id: redhat/vscode-yaml/latest
```

It should work fine when the devfile contains only cheEditor, chePlugin and dockerimage components.

### Runtime
   - [x] minikube (include output of `minikube version` and `kubectl version`)

### Environment
   - [x] my computer
       - [x] Linux
