### ISSUE TITLE
Enable MM notifications for failing CI builds

### ISSUE THREAD

**Issue by nickboldt** [eclipse-che/che#19658]
### Is your task related to a problem? Please describe.

Recently we discovered that some images are nopt being published in a timely manner, eg., https://quay.io/repository/eclipse/che-e2e?tag=nightly&tab=tags

So for GH actions that require daily updates to avoid blocking QE processes, we should ensure that failures are announced so they're more easily seen/fixed.

### Describe the solution you'd like

Mattermost notifications in the new `eclipse-che-ci` channel can be enabled like this:

```
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Create message
      run: |
        echo "{\"text\":\":che-logo: MESSAGE GOES HERE!\"}" > mattermost.json
    - name: Send message
      uses: mattermost/action-mattermost-notify@master
      env:
        MATTERMOST_WEBHOOK_URL: ${{ secrets.MATTERMOST_WEBHOOK_URL }}
        MATTERMOST_CHANNEL: eclipse-che-ci
        MATTERMOST_USERNAME: che-bot
```

Of course for **failures**, we should use :no_entry_sign: instead of :che-logo: or :white_check_mark:
