### ISSUE TITLE
DevWorkspace - Dashboard fails - There is no any resources matched to request path /unsupported/k8s/apis

### ISSUE THREAD

**Issue by nils-mosbach** [eclipse-che/che#19666]
### Describe the bug

Che dashboard fails to start and displays: `There is no any resources matched to request path /unsupported/k8s/apis` in the Browser console if running devWorkspace-mode.

![image](https://user-images.githubusercontent.com/15126675/115860777-481b4980-a432-11eb-95c8-34f3d4ea9310.png)

Che-Server logs:

```
2021-04-23 10:33:46,284[io-8080-exec-10]  [WARN ] [k.n.KubernetesNamespaceFactory 674]  - Trying to fetch namespaces with labels '{app.kubernetes.io/part-of=che.eclipse.org, app.kubernetes.io/component=workspaces-namespace}', but failed for lack of permissions. Cause: 'Failure executing: GET at: https://10.43.0.1/api/v1/namespaces?labelSelector=app.kubernetes.io%2Fpart-of%3Dche.eclipse.org%2Capp.kubernetes.io%2Fcomponent%3Dworkspaces-namespace. Message: Forbidden!Configured service account doesn't have access. Service account may have been revoked. namespaces is forbidden: User "system:serviceaccount:eclipse-che:che" cannot list resource "namespaces" in API group "" at the cluster scope.'
2021-04-23 10:33:46,288[io-8080-exec-10]  [WARN ] [k.n.KubernetesNamespaceFactory 674]  - Trying to fetch namespaces with labels '{app.kubernetes.io/part-of=che.eclipse.org, app.kubernetes.io/component=workspaces-namespace}', but failed for lack of permissions. Cause: 'Failure executing: GET at: https://10.43.0.1/api/v1/namespaces?labelSelector=app.kubernetes.io%2Fpart-of%3Dche.eclipse.org%2Capp.kubernetes.io%2Fcomponent%3Dworkspaces-namespace. Message: Forbidden!Configured service account doesn't have access. Service account may have been revoked. namespaces is forbidden: User "system:serviceaccount:eclipse-che:che" cannot list resource "namespaces" in API group "" at the cluster scope.'
```

### Che version
 - [X] 7.29.0

### Runtime
   - [X] kubernetes (include output of `kubectl version`)

```
Client Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.0", GitCommit:"e19964183377d0ec2052d1f1fa930c4d7575bd50", GitTreeState:"clean", BuildDate:"2020-08-26T14:30:33Z", GoVersion:"go1.15", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.4", GitCommit:"e87da0bd6e03ec3fea7933c4b5263d151aafd07c", GitTreeState:"clean", BuildDate:"2021-02-18T16:03:00Z", GoVersion:"go1.15.8", Compiler:"gc", Platform:"linux/amd64"}
```

### Installation method
   - [X] chectl

``` sh
chectl server:deploy \
  --installer=operator \
  --domain=***.dev \
  --multiuser \
  --platform=k8s \
  --skip-kubernetes-health-check \
  --che-operator-cr-patch-yaml=./operator-config.yaml
```

``` yaml
apiVersion: org.eclipse.che/v1
kind: CheCluster
metadata:
  name: che
spec:
  devWorkspace:
    enable: true

  server:
    tlsSupport: true
    customCheProperties:
      CHE_LIMITS_USER_WORKSPACES_RUN_COUNT: "-1"
      CHE_LIMITS_WORKSPACE_IDLE_TIMEOUT: "9000000" 
    devfileRegistryPullPolicy: Always
    pluginRegistryPullPolicy: Always
    workspaceNamespaceDefault: che-workspace-<username>

  database:
    externalDb: false
    postgresImagePullPolicy: Always

  storage:
    pvcStrategy: per-workspace
    pvcClaimSize: '5Gi'

  auth:
      externalIdentityProvider: true
      identityProviderURL: 'https://auth.***.dev/auth'
      identityProviderRealm: 'che-dev'
      identityProviderClientId: 'che'
      openShiftoAuth: false
      identityProviderAdminUserName: admin

  k8s:
      ingressDomain: 'che.***.dev'
      ingressStrategy: 'multi-host'
      tlsSecretName: 'tls-dev'
```

### Environment

   - [X] Rancher provisioned Kubernetes Cluster
