### ISSUE TITLE
Dashboard should better handle devworkspace startup failure

### ISSUE THREAD

**Issue by sleshchenko** [eclipse-che/che#19684]
### Describe the bug
Dashboard should better handle devworkspace startup failure.

1. When DevWorkspace becomes failed it's still displayed as Starting:
![Screenshot_20210427_123253](https://user-images.githubusercontent.com/5887312/116221038-e884ad00-a755-11eb-9087-2dbd66d84c7e.png)
2. After tab is changed, the state is rerendered but the INFO is not propagated:
![Screenshot_20210427_123322](https://user-images.githubusercontent.com/5887312/116221109-fd614080-a755-11eb-9f94-6e09d2384c83.png)
3. When DevWorkspace has failed state, it's not possible to update DevWorkspace:
![Screenshot_20210427_123621](https://user-images.githubusercontent.com/5887312/116221186-0e11b680-a756-11eb-80f9-0a26222d577d.png)

DevWorkspace to test:
```yaml
schemaVersion: 2.0.0
metadata:
  name: spring-petclinic
  namespace: opentlc-mgr-che
components:
  - container:
      env:
        - name: ENV_VAR
          value: value
      image: 'quay.io/eclipse/che-java8-maven:nly'
      memoryLimit: 1536M
      sourceMapping: /projects
      volumeMounts:
        - name: mavenrepo
          path: /root/.m2
    name: maven
  - name: mavenrepo
    volume:
      size: 1G

```

### Che version

 - [ ] latest
 - [ ] nightly
 - [ ] other: please specify

### Runtime
   - [ ] kubernetes (include output of `kubectl version`)
   - [ ] Openshift (include output of `oc version`)
   - [ ] minikube (include output of `minikube version` and `kubectl version`)
   - [ ] minishift (include output of `minishift version` and `oc version`)
   - [ ] docker-desktop + K8S (include output of `docker version` and `kubectl version`)
   - [ ] other: (please specify)

### Installation method
   - [ ] chectl
     * provide a full command that was used to deploy Eclipse Che (including the output)
     * provide an output of `chectl version` command
   - [ ] OperatorHub
   - [ ] I don't know

### Environment
   - [ ] my computer
       - [ ] Windows
       - [ ] Linux
       - [ ] macOS
   - [ ] Cloud
       - [ ] Amazon
       - [ ] Azure
       - [ ] GCE
       - [ ] other (please specify)
   - [ ] Dev Sandbox (workspaces.openshift.com)
   - [ ] other: please specify
