### ISSUE TITLE
Plugins can't communicate properly if they are located in different sidecars 

### ISSUE THREAD

**Issue by vinokurig** [eclipse-che/che#19686]
### Describe the bug

If two plugins are located in different sidecars and one plugin has exposed API with function, the other plugin freezes when it calls the function. If the plugins are located in one sidecar, everything is OK.

### Che version

 - [ ] latest
 - [ ] nightly
 - [ ] other: please specify

### Steps to reproduce

Start a workspace from this devfile:
```
apiVersion: 1.0.0
metadata:
  name: wksp-5mj7l
components:
  - type: chePlugin
    reference: 'https://gist.github.com/vinokurig/739a13b8f4829ed8f9074c1300e34f8e/raw/db739826c2ce7b8435abfc227bcf862e85739906/master.yaml'
    alias: master-extension
  - type: chePlugin
    reference: 'https://gist.github.com/vinokurig/5494e7505c8d6cc55cb7c245f7b100f1/raw/f9f303786c38570dd9593417def59d187bddf57e/slave.yaml'
```
2. Execute `Test Command` from the command palette.

This devfile represents two sidecars with two plugins. One plugin has exposed function `onFunction: () => void`, and another plugin calls this function.
### Expected behavior

A notification must appear after execution of the plugin API.
This works if the plugins are located in a common sidecar:
```
apiVersion: v2
publisher: ivinokur
name: master-extension
version: latest
type: Theia plugin
displayName: Master
title: Master extension
description: 'Master extension'
icon: /v3/images/redhat-java-icon.png
category: Programming Languages
repository: 'https://github.com/redhat-developer/vscode-java'
firstPublicationDate: '2021-02-11'
latestUpdateDate: '2021-04-22'
spec:
  containers:
    - image: 'quay.io/eclipse/che-plugin-sidecar@sha256:974dd0a5ab7e075d7d344af2e8e2a2f80a069e8a5a4c9ffc2a57e421b62aa17a'
      name: theia-master
  extensions:
    - 'https://github.com/vinokurig/master-extension/releases/download/0.0.1/master_extension.theia'
    - 'https://github.com/vinokurig/slave-extension/releases/download/0.0.1/slave_extension.theia'
```
### Runtime
   - [ ] kubernetes (include output of `kubectl version`)
   - [ ] Openshift (include output of `oc version`)
   - [ ] minikube (include output of `minikube version` and `kubectl version`)
   - [ ] minishift (include output of `minishift version` and `oc version`)
   - [ ] docker-desktop + K8S (include output of `docker version` and `kubectl version`)
   - [ ] other: (please specify)

### Installation method
   - [ ] chectl
     * provide a full command that was used to deploy Eclipse Che (including the output)
     * provide an output of `chectl version` command
   - [ ] OperatorHub
   - [ ] I don't know

### Environment
   - [ ] my computer
       - [ ] Windows
       - [ ] Linux
       - [ ] macOS
   - [ ] Cloud
       - [ ] Amazon
       - [ ] Azure
       - [ ] GCE
       - [ ] other (please specify)
   - [ ] Dev Sandbox (workspaces.openshift.com)
   - [ ] other: please specify
