### ISSUE TITLE
[UD] Support factory create policies for devWorkspaces

### ISSUE THREAD

**Issue by sleshchenko** [eclipse-che/che#19711]
### Is your task related to a problem? Please describe.
Che Workspaces supports two create policies: perClick, perUser.

But DevWorkspaces does not support them which cause to:
- by default factory accepting fails if devworkspace with the devfile's name already exists (name should be generated since perClick is the default policy);
- OpenShift DevConsole will work incorrectly if repository contains devfile v2, since it uses perUser policy;

To store used policy DevWorkspace CR labels/annotations should be used.

**Comment by sleshchenko** [comment]
label value format is pretty limited, so annotation is our way.

Currently, we have

```yaml
apiVersion: workspace.devfile.io/v1alpha2
kind: DevWorkspace
metadata:
  annotations:
    che.eclipse.org/devfile-source: |
      scm:
        repo: 'https://github.com/che-samples/java-spring-petclinic.git'
        revision: devfilev2
        fileName: devfile.yaml
```
```yaml
apiVersion: workspace.devfile.io/v1alpha2
kind: DevWorkspace
metadata:
  annotations:
    che.eclipse.org/devfile-source: |
      url:
        location: >-
          https://raw.githubusercontent.com/che-samples/java-spring-petclinic/devfilev2/devfile.yaml
```
But it does not seem to be appropriate to store policyCreate, so instead of repurposing existing annotation I propose to use
```yaml
apiVersion: workspace.devfile.io/v1alpha2
kind: DevWorkspace
metadata:
  annotations:
    che.eclipse.org/factory-parameters: url=https://raw.githubusercontent.com/che-samples/java-spring-petclinic/devfilev2/devfile.yaml&policies.create=peruser
```
^ So, dashboard is able to find a proper workspace for peruser, even without requesting Che Server to analyze devfile source.

**Comment by benoitf** [comment]
I would prefer if we have structured content and smaller names
also why you would need the URL again?

something like

```yaml
metadata:
  annotations:
    che.eclipse.org/factory: |
      createPolicy: peruser
```

**Comment by sleshchenko** [comment]
I'm OK with factory as well.

> also why you would need the URL again?

well, devfile source does not have an original URL but like in scm case has analyzed and probably modified content, like `'https://github.com/che-samples/java-spring-petclinic` become `https://github.com/che-samples/java-spring-petclinic.git`
We also are able to include factory field into devfile-origin if it makes sense, like:
```yaml
apiVersion: workspace.devfile.io/v1alpha2
kind: DevWorkspace
metadata:
  annotations:
    che.eclipse.org/devfile-source: |
      factory:
        params: url=https://raw.githubusercontent.com/che-samples/java-spring-petclinic/devfilev2/devfile.yaml&policies.create=peruser&devfile.override=metadata.name=your-first-dw
      scm:
        repo: 'https://github.com/che-samples/java-spring-petclinic.git'
        revision: devfilev2
        fileName: devfile.yaml
```
^ devfile.override is just here for an example, we haven't agreed yet if we need it for devworkspace.
