### ISSUE TITLE
Tabs flickering in Eclipse Che when workspace contains opened Jupyter notebooks.

### ISSUE THREAD

**Issue by nupurnegi** [eclipse-che/che#19735]
## Summary
Flickering: Tabs are switching automatically and continuously while navigating between opened Jupyter notebooks. If we bring the focus out of the workspace's tab the toggling stops. 

https://user-images.githubusercontent.com/35726589/116691329-4a544980-a9d8-11eb-97e2-2c660b0d563c.mov

Focus: Notebooks are taking the focus if we try to toggle back to any other file type. 

https://user-images.githubusercontent.com/35726589/116691341-4d4f3a00-a9d8-11eb-908d-f7790c8869ed.mov

## Relevant information
Che Versions tried: 7.28.2 and 7.29.1
We are using a remote Jupyter server on cloud.
Python extension (.vsix) Version: 2020.7.94776

python meta.yaml file
```
apiVersion: v2
publisher: ms-python
name: python
version: latest
type: VS Code extension
displayName: Python
title: Python
description: >-
 Linting, Debugging (multi-threaded, remote), Intellisense, Jupyter Notebooks, code formatting, refactoring, unit
 tests, snippets, and more.
icon: /v3/images/ms-python-python-icon.png
category: Programming Languages
repository: 'https://github.com/Microsoft/vscode-python'
firstPublicationDate: '2020-07-16'
latestUpdateDate: '2021-04-07'
spec:
 containers:
  - image: 'quay.io/eclipse/che-plugin-sidecar@sha256:64311210e710ca1614839f897285fc1d39b2ca17215d56c165d091aafd19a14b'
   name: vscode-python
   memoryLimit: 512Mi
   cpuRequest: 30m
   cpuLimit: 500m
 extensions:
  - 'https://github.com/microsoft/vscode-python/releases/download/2020.7.94776/ms-python-release.vsix'
```
To reproduce the issue:

- Create Jupyter notebooks inside different folders.
   - Switch between the opened Jupyter notebooks using the tabs to see the flickering issue.
   - Switch between a .ipynb file and any other file type(different extension) to see focus issue.

**Comment by nupurnegi** [comment]
@JPinkney 
Figured out somehow the python sidecar is causing the issue. On removing the sidecar image from the python plugin meta.yaml focus and flickering issue with the jupyter notebooks went away.

<details>
<summary>Use this Devfile to open the workspace</summary>

```
apiVersion: 1.0.0
metadata:
  name: jupyterws
attributes:
  persistVolumes: 'false'
components:
  - type: chePlugin
     reference: 'https://raw.githubusercontent.com/nupurnegi/jupyter_plugin/main/ms-python/python/latest/meta.yaml'
    preferences:
      python.dataScience.jupyterServerURI: <jupyter-ip-if-remote>
      python.disableInstallationCheck: true
```

</details>

We need the sidecar but on adding it the issues will come back. 

**Need help in figuring out why Che python sidecar is causing this issue.**
