### ISSUE TITLE
Offline che-plugin-registry build fails to embed all vsix files for plugins with depedencies

### ISSUE THREAD

**Issue by ericwill** [eclipse-che/che#19746]
### Che version

 - [ ] latest
 - [x] nightly
 - [ ] other: please specify

### Steps to reproduce
1. Build the che-plugin-registry with the offline parameter: `build.sh --offline`.
2. When the build finishes, enter the container to inspect the generated `meta.yaml` files.
3. Find the `meta.yaml` for a plugin that has dependencies, i.e. the ``metaYaml -> extraDependencies` field
4. Look at the `extensions` field and observe that the 2nd and onward extensions are not `relative:` links but are regular HTTP URLs.

For example, the `node-debug2` plugin `meta.yaml`:
```yaml
apiVersion: v2
publisher: ms-vscode
name: node-debug2
version: latest
type: VS Code extension
displayName: Node Debug
title: Node Debug
description: Node.js debugging support
icon: /v3/images/ms-vscode-node-debug2-icon.png
category: Debuggers
repository: 'https://github.com/Microsoft/vscode-node-debug2.git'
firstPublicationDate: '2020-10-07'
latestUpdateDate: '2021-05-04'
spec:
  containers:
    - image: 'quay.io/eclipse/che-plugin-sidecar@sha256:4bce2e39fee6b9e4a8b4e8681380ce2462674597a48b81c131cbbf055dd5d0c3'
      name: vscode-node-debug
      memoryLimit: 512Mi
      cpuRequest: 30m
      cpuLimit: 500m
      env:
        - name: CHE_THEIA_SIDECAR_PREFERENCES
          value: '{"debug.node.useV3":false}'
  extensions:
    - 'relative:extension/resources/open-vsx_org/api/ms-vscode/node-debug2/1_42_5/file/ms-vscode.node-debug2-1.42.5.vsix'
    - 'https://open-vsx.org/api/ms-vscode/node-debug/1.44.8/file/ms-vscode.node-debug-1.44.8.vsix'
```
### Expected behavior
All links in the `extensions` field should be `relative:` when building with the offline parameter.

### Runtime
   - [ ] kubernetes (include output of `kubectl version`)
   - [ ] Openshift (include output of `oc version`)
   - [ ] minikube (include output of `minikube version` and `kubectl version`)
   - [ ] minishift (include output of `minishift version` and `oc version`)
   - [ ] docker-desktop + K8S (include output of `docker version` and `kubectl version`)
   - [x] other: N/A

### Installation method
   - [ ] chectl
     * provide a full command that was used to deploy Eclipse Che (including the output)
     * provide an output of `chectl version` command
   - [ ] OperatorHub
   - [x] N/A

### Environment
   - [x] my computer
       - [ ] Windows
       - [x] Linux
       - [ ] macOS
   - [ ] Cloud
       - [ ] Amazon
       - [ ] Azure
       - [ ] GCE
       - [ ] other (please specify)
   - [ ] Dev Sandbox (workspaces.openshift.com)
   - [ ] other: please specify
