### ISSUE TITLE
Che devfile should support dockerimage components built from source (with tekton)

### ISSUE THREAD

**Issue by sunix** [eclipse-che/che#19774]
### Is your enhancement related to a problem? Please describe.
With docker compose, you can build with 
```yaml
version: '3'
services:
  app:
    build: .
    ports:
      - "8081:8080"
```
with a Dockerfile located in the root folder of the repo.

Developer may want something similar and be able to build/rebuild a container that is part of his devfile.yaml.

### Describe the solution you'd like
Delegate that to a tekton if it is installed

### Describe alternatives you've considered
N/A
