### ISSUE TITLE
Add the ability for an administrator to specify multiple external devfile registries

### ISSUE THREAD

**Issue by sleshchenko** [eclipse-che/che#19781]
### Is your enhancement related to a problem? Please describe.
Prehistory: we want to have the ability to enable Community Devfile Registry on CodeReadyWorkspaces https://github.com/eclipse/che/issues/19271
Che Dashboard has the ability to use multiple devfile registries, and Dashboard does not care if it's managed by the current Che Operator or external one https://github.com/eclipse-che/che-dashboard/pull/5.

The way we configure Che instance is CheCluster CR.
Currently, CheCluster CR allows to use internal devfile registry (managed by Che Operator):
```yaml
spec:
  server:
    devfileRegistryURL: https://internal-devfile-registry.com # value is provisioned by Che Operator
    externalDevfileRegistry: false
```
or use external one: any URL,URLs administrator configures in the corresponding fields:
```yaml
spec:
  server:
    devfileRegistryURL: https://my-registry1.com https://my-registry2.com
    externalDevfileRegistry: true
```

### Describe the solution you'd like
To cover the usecase described above, we need to mix both - we need to have the ability to use internal registry + configure some external ones.
The CheCluster format I see to cover it is the following:
```yaml
spec:
  server:
    devfileRegistryImage: "" # image used for internal devfile registry managed by Che Operator
    devfileRegistryImagePullPolicy: "Always"
    externalDevfileRegistries:
      - url: https://explicit-link-to-external-devfile-registry-1
      - url: https://explicit-link-to-external-devfile-registry-2" # additional devfile registries. Note that internal devfile registry is not supposed to be here.
status:
  devfileRegistryUrl: "https://che-devfile-registry.ingress-domain/" # note that previously, Che Operator stored internal registry URL in spec.server.devfileRegistryURL but I believe the status is better for such stuff, which should not be configured by user.
```

### Additional context
Not sure that it's important but DevSandbox(The first place where we're going to use this feature) is going to use single-host.

As a possible workaround for DevSandbox until it's not resolved:
1. CRW is already deployed and available.
2. Provision community registry in CheCluster CR:
```yaml
server:
    devfileRegistryURL: https://explicit-link-to-the-internal-devfile-registry https://explicit-link-to-external-devfile-registry
    externalDevfileRegistry: true
```
note: https://explicit-link-to-the-internal-devfile-registry is provisioned by CRW on phase 1, it needs to be just kept
3. Dashboard should use both of registries.
4. The internal registry becomes `unmanaged`, after upgrade to newer version the configuration must be redone manually, so revert to `spec.server.externalDevfileRegistry: false`. And after CRW operator did work and updated devfile registry deployment, go to step 2.

### Release Notes Text

Administrators are able to specify multiple external devfile registries in the `CheCluster` Kubernetes Custom Resource.

**Comment by sleshchenko** [comment]
As we discussed on the Deploy Team cabal:
1. instead of configuring external registries as space-separated list of URLs, we introduce list of object that has URL:
```
spec:
  server:
    devfileRegistryImage: "" # image used for internal devfile registry managed by Che Operator
    devfileRegistryImagePullPolicy: "Always"
    externalDevfileRegistries:
      - url: https://explicit-link-to-external-devfile-registry-1
      - url: https://explicit-link-to-external-devfile-registry-2
```
that allows us to extend it with titles and warnings, if we decide it should be configured separately for each devfile registry, but not on the common level on devfile tags.
2. We're not sure users have any need to disable internal plugin registry, if they want to have custom registry - they just need to build and configure devfileRegistryImage. So, we think it makes sense consider not introducing `devfileRegistryEnabled`, since it's a new field, which may be overhead. If we see the case for it - we can easily enable it any time. P.S. But we should be careful with it since it's a functional gap, since before we had an ability like to replace default devfile registry with external ones (one from surge from github)
