### ISSUE TITLE
Tasks are not working for DevWorkspaces

### ISSUE THREAD

**Issue by sleshchenko** [eclipse-che/che#19810]
### Describe the bug
If you try to run task on DevWorkspace you'll get the following error 
![Screenshot_20210514_143215](https://user-images.githubusercontent.com/5887312/118484965-800b6900-b720-

It's caused by fact that devfile 2.0 endpoint is:
```
        - attributes:
            controller.devfile.io/endpoint-url: wss://workspace8dcdfddb9c904843-8.apps.cluster-56cf.56cf.sandbox1489.opentlc.com/
            cookiesAuthEnabled: true
            discoverable: false
            type: collocated-terminal
          exposure: public
          name: terminal
          protocol: wss
          targetPort: 3333
```
while Theia tries to find port in attributes https://github.com/eclipse-che/che-theia/blob/master/plugins/task-plugin/src/che-workspace-client.ts#L48

### Runtime
   - [ ] kubernetes (include output of `kubectl version`)
   - [ ] Openshift (include output of `oc version`)
   - [ ] minikube (include output of `minikube version` and `kubectl version`)
   - [ ] minishift (include output of `minishift version` and `oc version`)
   - [ ] docker-desktop + K8S (include output of `docker version` and `kubectl version`)
   - [ ] other: (please specify)

### Installation method
   - [ ] chectl
     * provide a full command that was used to deploy Eclipse Che (including the output)
     * provide an output of `chectl version` command
   - [ ] OperatorHub
   - [ ] I don't know

### Environment
   - [ ] my computer
       - [ ] Windows
       - [ ] Linux
       - [ ] macOS
   - [ ] Cloud
       - [ ] Amazon
       - [ ] Azure
       - [ ] GCE
       - [ ] other (please specify)
   - [ ] Dev Sandbox (workspaces.openshift.com)
   - [ ] other: please specify
