### ISSUE TITLE
TestNG suport for Theia

### ISSUE THREAD

**Issue by akhilajayakumar** [eclipse-che/che#19828]
We have been working with Eclipse che theia 7.31 version and have done "deploy plugin by id" to add the Java test runner plugin to enable TestNg support for the projects. We could see the Run| Debug option for java but not for @Test annotations from Junit/TestNG libraries. Could you please guide us where we are going wrong?

![image](https://user-images.githubusercontent.com/65273884/118928501-eed70500-b960-11eb-89e7-0a0480e1eece.png)
![image](https://user-images.githubusercontent.com/65273884/118928619-19c15900-b961-11eb-9bf1-6083dad10360.png)

We also tried adding vscode extension in theia following the instructions from the below document,

https://www.eclipse.org/che/docs/che-7/end-user-guide/adding-a-vs-code-extension-to-a-workspace/

We have used below meta.yamal as reference to add vscode plugin, but no luck
https://github.com/eclipse-che/che-plugin-registry/blob/7.24.x/v3/plugins/cdr/code-server/3.6.2/meta.yaml

Setup details:
Che version: latest (7.31.0)
Deployed on Azure Kubernetes (AKS) Using helm chart
Kubernetes version: 1.18.17, 16Gb 4CPU
Storage for a workspace -10GB

**Comment by ericwill** [comment]
https://github.com/eclipse-che/che-plugin-registry/blob/7.24.x/v3/plugins/cdr/code-server/3.6.2/meta.yaml is an editor `meta.yaml` to use VS Code as an editor in Che.

To use the Java plugin (with test runner support), you can use the existing `redhat/java11` plugin from the plugin registry -- it should have everything you need. Do you have a devfile you can share?

**Comment by akhilajayakumar** [comment]
Hi Eric,

Please find the devfile.

apiVersion: 1.0.0
metadata:
  name: java-maven-sd9rm
projects:
  - name: TAF-Scripting
    source:
      location: 'https://github.com/USTQE/NoSkriptTrial.git'
      type: git
      branch: dev
components:
  - id: redhat/java11/latest
    preferences:
      java.server.launchMode: Standard
    type: chePlugin
  - mountSources: true
    endpoints:
      - attributes:
          public: 'false'
        name: debug
        port: 5005
    memoryLimit: 512Mi
    type: dockerimage
    volumes:
      - name: m2
        containerPath: /home/user/.m2
    image: 'quay.io/eclipse/che-java11-maven:nightly'
    alias: maven
    env:
      - value: ''
        name: MAVEN_CONFIG
      - value: '-XX:MaxRAMPercentage=50 -XX:+UseParallelGC -XX:MinHeapFreeRatio=10 -XX:MaxHeapFreeRatio=20 -XX:GCTimeRatio=4 -XX:AdaptiveSizePolicyWeight=90 -Dsun.zip.disableMemoryMapping=true -Xms20m -Djava.security.egd=file:/dev/./urandom -Duser.home=/home/user'
        name: MAVEN_OPTS
      - value: '-XX:MaxRAMPercentage=50 -XX:+UseParallelGC -XX:MinHeapFreeRatio=10 -XX:MaxHeapFreeRatio=20 -XX:GCTimeRatio=4 -XX:AdaptiveSizePolicyWeight=90 -Dsun.zip.disableMemoryMapping=true -Xms20m -Djava.security.egd=file:/dev/./urandom'
        name: JAVA_OPTS
      - value: '-XX:MaxRAMPercentage=50 -XX:+UseParallelGC -XX:MinHeapFreeRatio=10 -XX:MaxHeapFreeRatio=20 -XX:GCTimeRatio=4 -XX:AdaptiveSizePolicyWeight=90 -Dsun.zip.disableMemoryMapping=true -Xms20m -Djava.security.egd=file:/dev/./urandom'
        name: JAVA_TOOL_OPTIONS
commands:
  - name: maven build
    actions:
      - workdir: '${CHE_PROJECTS_ROOT}/TAF-Scripting'
        type: exec
        command: mvn clean install
        component: maven
  - name: maven build and run
    actions:
      - workdir: '${CHE_PROJECTS_ROOT}/TAF-Scripting'
        type: exec
        command: mvn clean install && java -jar ./target/*.jar
        component: maven


We have used java11, still its not showing the Run debugg option. Thanks for the support

**Comment by spvece** [comment]
Hi Eric,

On Behalf of Akhil, any update on the above issue?

**Comment by ericwill** [comment]
> Hi Eric,
> 
> On Behalf of Akhil, any update on the above issue?

Not yet, this is something we'll look at next sprint (June 15th and onward).

**Comment by sunix** [comment]
Hi @akhilajayakumar @spvece , do you have a public git project where this issue could be reproduced? I cannot access to https://github.com/USTQE/NoSkriptTrial.git

**Comment by vitaliy-guliy** [comment]
I have tried to write a small test with TestNG and can say, that it works. But there is an issue, that needs to be fixed (see below).

Try create a workspace with this devfile
```
apiVersion: 1.0.0
metadata:
  name: testng-example
projects:
  - name: testng-example
    source:
      location: 'https://github.com/vitaliy-guliy/testng-example.git'
      type: git
components:

  - id: redhat/java/latest
    preferences:
      java.server.launchMode: Standard
    type: chePlugin

  - mountSources: true
    endpoints:
      - attributes:
          public: 'false'
        name: debug
        port: 5005
    memoryLimit: 512Mi
    type: dockerimage
    volumes:
      - name: m2
        containerPath: /home/user/.m2
    alias: maven
    image: 'quay.io/eclipse/che-java11-maven:next'
    env:
      - value: ''
        name: MAVEN_CONFIG
      - value: '-XX:MaxRAMPercentage=50 -XX:+UseParallelGC -XX:MinHeapFreeRatio=10 -XX:MaxHeapFreeRatio=20 -XX:GCTimeRatio=4 -XX:AdaptiveSizePolicyWeight=90 -Dsun.zip.disableMemoryMapping=true -Xms20m -Djava.security.egd=file:/dev/./urandom -Duser.home=/home/user'
        name: MAVEN_OPTS
      - value: '-XX:MaxRAMPercentage=50 -XX:+UseParallelGC -XX:MinHeapFreeRatio=10 -XX:MaxHeapFreeRatio=20 -XX:GCTimeRatio=4 -XX:AdaptiveSizePolicyWeight=90 -Dsun.zip.disableMemoryMapping=true -Xms20m -Djava.security.egd=file:/dev/./urandom'
        name: JAVA_OPTS
      - value: '-XX:MaxRAMPercentage=50 -XX:+UseParallelGC -XX:MinHeapFreeRatio=10 -XX:MaxHeapFreeRatio=20 -XX:GCTimeRatio=4 -XX:AdaptiveSizePolicyWeight=90 -Dsun.zip.disableMemoryMapping=true -Xms20m -Djava.security.egd=file:/dev/./urandom'
        name: JAVA_TOOL_OPTIONS

commands:
  - name: maven build
    actions:
      - workdir: '${CHE_PROJECTS_ROOT}/testng-example'
        type: exec
        command: mvn clean install
        component: maven
```

After workspace startup go to `My Workspace` view and run `maven build`. Then open a test java file and wait for java language server being initialized. `Run Test` and `Debug Test` controls should appear under `@Test` annotation.
Click `Run Test` to open a `Debug Console` and launch the test.

![Screenshot from 2021-09-03 14-38-30](https://user-images.githubusercontent.com/1655894/132004553-e77c4cf7-4262-4f43-9d06-b4c4b5ce4ff7.png)

It should be as on the screenshot, but..
There is a bug, which needs to be fixed https://github.com/eclipse/che/issues/20410

Clicking on `Run  Test` opens an empty `Debug Console` and nothing happens.
The browser console says, that there is something wrong running `LinkProviderAdapter.provideLinks(...)`
To have the test running it needs to refresh the browser and to run the test again.
