### ISSUE TITLE
Tasks are not ended properly

### ISSUE THREAD

**Issue by svor** [eclipse-che/che#19821]
### Describe the bug
When start a task from the My workspace view by quickly clicking many times on it, it is not ended properly (IDE doesn't show "✓", but still shows spinning wheel) and the next task execution can't be started. 

### Che version

 - [x] latest
 - [ ] nightly
 - [ ] other: please specify

### Steps to reproduce

1. Use this devfile to create a workspace:
```yaml
apiVersion: 1.0.0
metadata:
  name: test-workspace
components:
  - mountSources: true
    memoryLimit: 512Mi
    type: dockerimage
    image: 'quay.io/eclipse/che-java11-maven:nightly'
    alias: maven
commands:
  - name: Click me many times
    actions:
      - type: exec
        command: echo 'Command was finished'
        component: maven
```
2. Try to click quickly many times on **Click me many times** from Workspace view
3. See that the task never finish and it is not possible to re-run it

### Expected behavior
Task should be finished properly 

### Runtime
   - [x] kubernetes (include output of `kubectl version`)
   - [x] Openshift (include output of `oc version`)
   - [ ] minikube (include output of `minikube version` and `kubectl version`)
   - [ ] minishift (include output of `minishift version` and `oc version`)
   - [ ] docker-desktop + K8S (include output of `docker version` and `kubectl version`)
   - [ ] other: (please specify)

### Screenshots

https://user-images.githubusercontent.com/1271546/127866606-84582247-6687-4f3e-a5e7-cea5d4810a8a.mp4

### Installation method
   - [x] chectl
     * provide a full command that was used to deploy Eclipse Che (including the output)
     * provide an output of `chectl version` command
   - [ ] OperatorHub
   - [ ] I don't know
