### ISSUE TITLE
[Devsandbox] Failures during the project import after Get Started workspace startup - Couldn't import http://172.30.145.30:8080/resources/quarkus-quarkus-quickstarts-main.zip: curl: (7) Failed to connect to 172.30.145.30 port 8080: Connection timed out

### ISSUE THREAD

**Issue by ibuziuk** [eclipse-che/che#19853]
### Che version
CRW 2.8

### Steps to reproduce

1. Go to Get Started Tab workspaces.openshift.com#get-started
2. Start one of the samples e.g. quarkus
3. ERROR: workspace is started but the project can not be imported:

![image](https://user-images.githubusercontent.com/1461122/119313323-b5a9d800-bc73-11eb-9f10-61b8fd534627.png)

### Expected behavior
Workspace started without problems

### Runtime
   - OSD 4.7

### Additional context
devfile of the created workspace looks bizarre and reference to the cluster-specific zip source:
```
projects:
  - name: quarkus-quickstarts
    source:
      location: 'http://172.30.59.26:8080/resources/quarkus-quarkus-quickstarts-main.zip'
      type: zip
```

**Comment by ibuziuk** [comment]
Dogfooding instance and https://www.eclipse.org/che/getting-started/cloud/ are also affected

**Comment by ibuziuk** [comment]
The culprit is the incorrect cluster-specific location to the zip files e.g.:
```
- name: quarkus-quickstarts
    source:
      location: 'http://172.30.189.177:8080/resources/quarkus-quarkus-quickstarts-main.zip'
      type: zip
```
