### ISSUE TITLE
Strange behavior with json arrays set as preference values

### ISSUE THREAD

**Issue by bfitzpat** [eclipse-che/che#19885]
### Describe the bug

This is related to https://github.com/eclipse/che/pull/16680 and https://github.com/eclipse/che/issues/16594

I am attempting to do a couple of things. First, I'm simply attempting to do something like this example from the docs - https://www.eclipse.org/che/docs/che-7/end-user-guide/configuring-a-workspace-using-a-devfile/#adding-components-to-a-devfile_che in the "Preferences may also be specified as an array:" section.

This simple devfile should work I think:

```
apiVersion: 1.0.0
metadata:
  name: test-environment
components:
  - id: redhat/java/latest
    preferences:
      go.lintFlags: ["--enable-all", "--new"]
    type: chePlugin
```

But it gets reformatted as:
```
      go.lintFlags: go.lintFlags: ["--enable-all", "--new"]
        - '--enable-all'
        - '--new'
```

And does not open when I am trying it in a CodeReady Workspaces in the Developer Sandbox. It seems to hang.

Other odd things I have noticed are when I attempt to pass a json array as preferences to my Che plugin:

```
apiVersion: 1.0.0
metadata:
  name: didact-yaml-3
components:
  - preferences:
      didact.defaultUrl: 'https://raw.githubusercontent.com/redhat-developer/vscode-didact/f1e87d6df758ff0d5f31850dc034252403a7336f/examples/test.didact.yaml'
      didact.append.registry: '["name":"AppendMe","category":"AppendedCat","sourceUri":"https%3A%2F%2Fraw.githubusercontent.com%2Fredhat-developer%2Fvscode-didact%2Fmaster%2Fexamples%2Fregistry.example.didact.md"}]'
      che.welcome.enable: false
      didact.openDefaultTutorialAtStartup: true
    type: chePlugin
    reference: 'https://gist.githubusercontent.com/bfitzpat/0b8dc17395918c9dcb7750a9b745cb2a/raw/2ec67203adb1e0aaf73d552127dbdfb7c524bdef/meta.yaml'
    alias: didact-plugin
  - type: cheEditor
    reference: 'https://che-plugin-registry-main.surge.sh/v3/plugins/eclipse/che-theia/latest/meta.yaml'
```

Though this is not a published version of the plugin, I have seen this strange behavior:
* spaces after commas (single or more), between delimited items seems to prevent loading
* breaking the line into multiple lines inserts spaces, which then causes the devfile to not load properly
* I have attempted to escape all double quotes, but that doesn't seem to help either

My question is this: What are the limits of providing arrays in JSON via preference values? 

### Che version

 - [ ] latest
 - [ ] nightly
 - [ ] other: please specify

### Runtime
   - [ ] kubernetes (include output of `kubectl version`)
   - [ ] Openshift (include output of `oc version`)
   - [ ] minikube (include output of `minikube version` and `kubectl version`)
   - [ ] minishift (include output of `minishift version` and `oc version`)
   - [ ] docker-desktop + K8S (include output of `docker version` and `kubectl version`)
   - [ ] other: (please specify)

### Installation method
   - [ ] chectl
     * provide a full command that was used to deploy Eclipse Che (including the output)
     * provide an output of `chectl version` command
   - [ ] OperatorHub
   - [ ] I don't know

### Environment
   - [ ] my computer
       - [ ] Windows
       - [ ] Linux
       - [ ] macOS
   - [ ] Cloud
       - [ ] Amazon
       - [ ] Azure
       - [ ] GCE
       - [ ] other (please specify)
   - [ ] Dev Sandbox (workspaces.openshift.com)
   - [ ] other: please specify
