### ISSUE TITLE
Yeoman plugin generator generates a plugin with outdated dependencies

### ISSUE THREAD

**Issue by vitaliy-guliy** [eclipse-che/che#19889]
### Describe the bug

Yeoman plugin generator generates non-working plugin.
The generator prints a lot of error messages when installing dependencies for generated plugin.
The same, but in colors and with wider explanation we have when trying to build the generated plugin by hands.

### Che version

 - [ ] nightly

### Steps to reproduce

<details>
<summary>Devfile</summary>
<p>

```
apiVersion: 1.0.0

metadata:
  name: theia-dogfooding

attributes:
  multiRoot: 'off'

projects:

  - name: che-theia
    source:
      location: 'https://github.com/eclipse-che/che-theia.git'
      type: git
      branch: master

components:
  - id: eclipse/che-theia/latest
    type: cheEditor
    alias: theia-editor

  - type: chePlugin
    id: che-incubator/typescript/latest

  - type: chePlugin
    id: redhat/vscode-yaml/latest

  - type: dockerimage
    image: 'quay.io/eclipse/che-theia-dev:next'
    alias: che-dev
    mountSources: true
    endpoints:
      - name: theia-dev-flow
        port: 3010
        attributes:
          protocol: http
          public: 'true'
    memoryLimit: 3Gi
```

</p>
</details>

1. Open command palette, run `Yeoman wizard` and generate theia backend plugin.
2. Open a terminal in `dev` container, goto plugin directory and run `yarn`.

### Screenshots

![Screenshot from 2021-05-31 15-21-22](https://user-images.githubusercontent.com/1655894/120193853-925bcb80-c225-11eb-9be6-1f2dd69a5d47.png)

![Screenshot from 2021-05-31 15-21-28](https://user-images.githubusercontent.com/1655894/120193870-95ef5280-c225-11eb-923c-b15f0cb5c40a.png)
