### ISSUE TITLE
Plugins view must display proper icons if plugins were installed from third-party registry (registryUrl: ...)

### ISSUE THREAD

**Issue by vitaliy-guliy** [eclipse-che/che#19898]
### Describe the bug

Plugins view displays wrong icon if the plugin was added to the devfile with custom `registryUrl`
```
  - type: chePlugin
    id: che-incubator/typescript/latest
    registryUrl: https://eclipse-che.github.io/che-plugin-registry/7.31.0/v3/
```

Event if the plugins view displays some icon, it needs to ensure, that the icon refers on specific registry.

### Che version

 - [x] nightly

### Steps to reproduce

1. Create workspace from the devfile
```
apiVersion: 1.0.0
metadata:
  generateName: nodejs-web-app-
projects:
  - name: react-web-app
    source:
      type: git
      location: https://github.com/che-samples/react-web-app
components:
  - type: chePlugin
    id: editorconfig/editorconfig/0.14.4
    registryUrl: http://custom-plugin-registry.surge.sh/path/to/registry/v3/
  - type: dockerimage
    alias: nodejs
    image: quay.io/eclipse/che-nodejs12-community:7.31.0
    memoryLimit: 1500Mi
    endpoints:
      - name: nodejs
        port: 3000
    mountSources: true
commands:
  - name: 1. Install Yarn 2
    actions:
      - type: exec
        component: nodejs
        command: yarn set version berry
        workdir: ${CHE_PROJECTS_ROOT}/react-web-app
  - name: 2. Install all required dependencies
    actions:
      - type: exec
        component: nodejs
        command: yarn install
        workdir: ${CHE_PROJECTS_ROOT}/react-web-app
  - name: 3. Build the app
    actions:
      - type: exec
        component: nodejs
        command: yarn build
        workdir: ${CHE_PROJECTS_ROOT}/react-web-app
  - name: 4. Run the app
    actions:
      - type: exec
        component: nodejs
        command: yarn start
        workdir: ${CHE_PROJECTS_ROOT}/react-web-app
  - name: 5. Launch tests
    actions:
      - type: exec
        component: nodejs
        command: yarn test
        workdir: ${CHE_PROJECTS_ROOT}/react-web-app
```

2. Open plugin view and check the icon of `editorconfig/editorconfig/0.14.4` plugin.
