### ISSUE TITLE
Add new link entries in devfile registry for devfile v2

### ISSUE THREAD

**Issue by benoitf** [eclipse-che/che#19906]
### Is your task related to a problem? Please describe.
For now, we have meta.yaml with self links pointing to devfile.yaml
For devfile v2, we'll need to have links to v2 devfiles. But also as the idea is to be "repository first" instead of "devfile first", the links should be pointers to repositories.

### Describe the solution you'd like
Add `v2` links in addition to the self-links.

for example
```yaml
"v2": "http://github.com/my/repository/tree/1.x"
```
to use the `1.x` branch of this git repository

### Additional context
as part of https://github.com/eclipse/che/issues/19718, some other entries would be defined like

```yaml
prebuilt: 
   - "che-theia/next": "/path/to/all-in-one-che-theia-next.yaml"
   - "che-theia/latest": "/path/to/all-in-one-che-theia-latest.yaml"
   - "intellij/latest": "/path/to/all-in-one-intellij-latest.yaml"
```

For offline builds, we may still need to copy the repository devfile.yaml instead of using repository link
