### ISSUE TITLE
Installation on nginx ingress leads to infinite redirect on dashboard

### ISSUE THREAD

**Issue by tarioch** [eclipse-che/che#19914]
### Describe the bug
After installing on my cluster, the ingress that was generated for the dashboard looked like this

```yaml
spec:
  rules:
  - host: che-eclipse-che.che.mydomain.com
    http:
      paths:
      - backend:
          service:
            name: che-dashboard
            port:
              number: 8080
        path: /dashboard/*
        pathType: ImplementationSpecific
  tls:
  - hosts:
    - che-eclipse-che.che.mydomain.com
    secretName: che-tls
```

When trying to access the dashboard, there was an infinite redirect to the dashboard.

After dropping the * at the end of /dashboard/, everything works fine.

### Che version
7.32.0-SNAPSHOT
installed with chectl 7.31.0

### Runtime
   - [x] k3s Server Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.1+k3s1", GitCommit:"75dba57f9b1de3ec0403b148c52c348e1dee2a5e", GitTreeState:"clean", BuildDate:"2021-05-21T16:12:29Z", GoVersion:"go1.16.4", Compiler:"gc", Platform:"linux/amd64"}

### Installation method
   - [x] chectl
```
chectl server:deploy --installer=helm --platform=k8s --domain=che.mydomain.com --telemetry=off --multiuser
chectl/7.31.0 linux-x64 node-v12.22.1
```

### Environment
   - [x] my computer
       - [x] Linux
