### ISSUE TITLE
Ensure that che-server's SA have enough permission to manipulate with devworkspaces resource on kubernetes

### ISSUE THREAD

**Issue by skabashnyuk** [eclipse-che/che#19920]
### Is your task related to a problem? Please describe.
When we tried to add an ability to use Kubernetes API proxy on Kubernetes | #19813 and enabled devworkspaces 
we got 
```
devworkspaces.workspace.devfile.io is forbidden: User \"system:serviceaccount:eclipse-che:che\" cannot list resource \"devworkspaces\" in API group \"workspace.devfile.io\" in the namespace \"admin-che\""
metadata: {}
```
https://github.com/eclipse-che/che-server/pull/6#issuecomment-853882365

### Describe the solution you'd like
On k8s if devworkspaces is enabled add permission for t che-server's SA to work with devworkspaces resources in all namespaces.

### Additional context
#19813 
Need for https://github.com/eclipse-che/che-server/pull/6

**Comment by skabashnyuk** [comment]
I'm testing now such permissions
```

  - apiGroups:
      - workspace.devfile.io
    resources:
      - devworkspaces
      - devworkspacetemplate
    verbs:
      - get
      - create
      - delete
      - list
      - update
      - patch
```
