### ISSUE TITLE
Invalid plugin registry URL

### ISSUE THREAD

**Issue by RomanNikitenko** [eclipse-che/che#19955]
### Describe the bug

I get `Invalid plugin registry URL` warning when a workspace is started.
The warning proposes to check settings, but I have no idea what's wrong with settings.
The `Plugins` panel is empty.

### Che version

 - [ ] latest
 - [x] nightly
 - [ ] other: please specify

### Steps to reproduce

1. Start a workspace from the devfile:
```
apiVersion: 1.0.0
metadata:
  name: wksp-uhias
components:
  - id: eclipse/che-theia/next
    type: cheEditor
    alias: che-theia

```
2. Please pay attention on the warning.
3. Check the `Plugins` panel.

### Runtime
   dogfooding instance
### Screenshots

![invsalid_plugin_reg](https://user-images.githubusercontent.com/5676062/121500623-275d8200-c9e7-11eb-9431-072edca5b96c.png)

![master_plugin_registry](https://user-images.githubusercontent.com/5676062/121497038-b4064100-c9e3-11eb-8a9e-564ecbc068cb.png)

![settings](https://user-images.githubusercontent.com/5676062/121497784-76ee7e80-c9e4-11eb-92f8-5ba55c24d0de.png)
