### ISSUE TITLE
Labelling devfiles in the Dashboard

### ISSUE THREAD

**Issue by sunix** [eclipse-che/che#19953]
### Is your enhancement related to a problem? Please describe.
In the dashboard get-started page, admin can configure Che to have devfiles coming from different devfile registries. The problem is that it is hard to differentiate where the devfile is coming from.
This is what is done in the Red Hat Developer Sandbox SaaS which is mixing CodeReady Workspaces devfiles and Che community devfiles. It is not possible to distinguish from which registry is coming a devfile. A user may use unwillingly the community one rather than the one from CodeReady Workspaces.
A label showing that a devfile is a "community" devfile would help. Labels could be used in other use cases: showing the supported architectures for instance.

### Describe the solution you'd like
The idea is to reuse the field from the meta.yaml file that we have already in the devfile registries: The tags field.
In meta.yaml attributes
```yaml
displayName: Quarkus Postgresql
description: Build and run hotspot or native Quarkus app with postgresql
tags: ["Community", "arm64", "Airgap", "Java", "Quarkus", "OpenJDK", "Maven", "Native", "GraalVM"]
icon: /images/quarkus.svg
globalMemoryLimit: 8Gi
Links:
  self: /devfiles/quarkus-postgresql/devfile.yaml
```

In index.json (generated) of the registry

```json
[
...
,
  {
    "displayName": "Quarkus Postgresql",
    "description": "Build and run hotspot or native Quarkus app with postgresql",
    "tags": [
      "Community",
      "arm64",
      "Airgap",
      "Java",
      "Quarkus",
      "OpenJDK",
      "Maven",
      "Native",
      "GraalVM"
    ],
    "icon": "/images/quarkus.svg",
    "globalMemoryLimit": "8Gi",
    "links": {
      "self": "/devfiles/quarkus-postgresql/devfile.yaml"
    }
  },
```
Based on an operator cluster configuration, the admin would set the list of tags that would be displayed as a label in the user dashboard.

This is how would look like the dashboard
-  with only "Community" labels selected in the operator cluster config
   ```yaml
   showDevfileTagsInLabels: : ["Community"]
   ```
- having all the devfiles from the community marked with the tag "Community"

![image](https://user-images.githubusercontent.com/650571/121374154-f5451500-c93f-11eb-8ef1-5c67fdc1b15b.png)

Here are few subtasks to achieve that:

- [ ] Have an operator configuration option “showDevfileTagsInLabels”  to define a list of tags to display as a label. and make it available to the dashboard.
- [ ] Visually display tags labels in the dashboard get-started page for devfile with tags listed in “showDevfileTags”
- [ ] Mark with the tag "community" to all the devfiles coming from the default devfile registry
