### ISSUE TITLE
Eclipse che - 7.29.2 | Mysql based workspace not working

### ISSUE THREAD

**Issue by andr-azeez** [eclipse-che/che#19989]
### Describe the bug

Mysql based sample projects are not running. Refer to the screenshot

### Steps to reproduce
Create any mysql based workspace

### Screenshots

![Screenshot from 2021-06-16 23-17-04](https://user-images.githubusercontent.com/81161330/122267845-fe625300-cef8-11eb-8111-c4768538bf0f.png)

**Comment by ericwill** [comment]
Can you please share your devfile that you are using?

**Comment by andr-azeez** [comment]
````
apiVersion: 1.0.0
metadata:
  name: java-mysql-custom-1k6cb
projects:
  - name: project-java-mysql-sample
    source:
      location: 'https://github.com/spadmins/project-java-mavan-sample.git'
      type: git
      branch: main
components:
  - id: redhat/java/latest
    preferences:
      java.server.launchMode: Standard
    type: chePlugin
  - mountSources: true
    endpoints:
      - name: 8080-tcp
        port: 8080
      - attributes:
          public: 'false'
        name: debug
        port: 5005
    memoryLimit: 1000Mi
    type: dockerimage
    volumes:
      - name: m2
        containerPath: /home/user/.m2
    image: 'quay.io/eclipse/che-java11-maven:7.29.2'
    alias: tools
    env:
      - value: ''
        name: MAVEN_CONFIG
      - value: '-XX:MaxRAMPercentage=50.0 -XX:+UseParallelGC -XX:MinHeapFreeRatio=10 -XX:MaxHeapFreeRatio=20 -XX:GCTimeRatio=4 -XX:AdaptiveSizePolicyWeight=90 -Dsun.zip.disableMemoryMapping=true -Xms20m -Djava.security.egd=file:/dev/./urandom -Duser.home=/home/user'
        name: JAVA_OPTS
      - value: $(JAVA_OPTS)
        name: MAVEN_OPTS
  - mountSources: true
    endpoints:
      - attributes:
          discoverable: 'true'
          public: 'false'
        name: db
        port: 3306
    command:
      - tail
    args:
      - '-f'
      - /dev/null
    memoryLimit: 300Mi
    type: dockerimage
    image: 'docker.io/library/mysql:5.7'
    alias: mysql
    env:
      - value: root
        name: MYSQL_USER
      - value: password
        name: MYSQL_PASSWORD
      - value: sample
        name: MYSQL_DATABASE
      - value: petclinic
        name: MYSQL_ROOT_PASSWORD
      - value: '$(echo ${0})\\$'
        name: PS1
commands:
  - name: maven build
    actions:
      - workdir: '${CHE_PROJECTS_ROOT}/project-java-mysql-sample'
        type: exec
        command: mvn clean install
        component: tools
  - name: Debug remote java application
    actions:
      - referenceContent: |
          {
          "version": "0.2.0",
          "configurations": [
            {
              "type": "java",
              "name": "Debug (Attach) - Remote",
              "request": "attach",
              "hostName": "localhost",
              "port": 5005
            }]
          }
        type: vscode-launch

````
