### ISSUE TITLE
[che-auth] chectl should not wait for keycloak in nativeUserMode

### ISSUE THREAD

**Issue by sparkoo** [eclipse-che/che#20009]
### Is your task related to a problem? Please describe.

When in nativeUserMode enabled, keycloak is not deployed. However, chectl is waiting for it and fails.

```
apiVersion: org.eclipse.che/v1
kind: CheCluster
metadata:
  name: eclipse-che
spec:
  auth:
    nativeUserMode: true
```

❗ Note to assignee: In time I'm creating this issue, the che-operator PR to deploy in nativeUserMode is open. If it is still the case, you have to use custom che-operator image.

### Describe the solution you'd like

Chectl should not wait for keycloak deployment when nativeUserMode is enabled.

### Additional context

[che-auth] - make it possible to deploy Che with new auth #19705 
che-operator PR - native user authentication #861 (https://github.com/eclipse-che/che-operator/pull/861)
