### ISSUE TITLE
Implement an ability to debug devworkspace startup

### ISSUE THREAD

**Issue by sleshchenko** [eclipse-che/che#20023]
### Is your enhancement related to a problem? Please describe.
https://github.com/devfile/devworkspace-operator/pull/425 implement an ability to debug devworkspace startup. This issue is about exposing this ability on the dashboard.

```
cat <<EOF | kubectl apply -f -
kind: DevWorkspace
apiVersion: workspace.devfile.io/v1alpha2
metadata:
  name: failing-devworkspace
  annotations:
    controller.devfile.io/debug-start: "true"
spec:
  started: true
  routingClass: 'che'
  template:
    components:
      - name: web-terminal
        container:
          image: quay.io/wto/web-terminal-tooling:latest
          memoryLimit: 512Mi
          mountSources: true
          command:
           - "exit"
           - "1"
EOF
```
