### ISSUE TITLE
Environment variable for che-plugins 

### ISSUE THREAD

**Issue by gautam-borkar** [eclipse-che/che#20036]
I am trying to create a plugin that will load a didact file. However didact file keeps changing based on project being loaded. So I am thinking of passing filename to plugin via the devfile as an environment variable.

My devfile looks like this :- 
```
- id: gborkar/didact-plugin/latest
    type: chePlugin
    env:
      - value: 'https://raw.githubusercontent.com/gautam-borkar/nodejs-express/master/README.md'
        name: DIDACT_FILE_URL
```

However in plugin, environment variable is `undefined`.

**Comment by RomanNikitenko** [comment]
@gautam-borkar 

Hello!
I tried something similar and can see the variable using a terminal for the corresponding container.
So - I provided a variable for `typescript` plugin and then checked that the variable existed for the `typescript` container.
Please see a short video.
Could you clarify the way how you checked the variable.
thanks!


https://user-images.githubusercontent.com/5676062/123825063-3f9a3000-d907-11eb-8ab4-807843fb8018.mp4

**Comment by gautam-borkar** [comment]
@RomanNikitenko Thanks for the response!

Yes. I can see the environment variable in typescript container. But when plugin is initialised, it does not get the variable. 
In this file :- https://github.com/gautam-borkar/didact-plugin/blob/616233ed24f8cd536391d503b6e0d706be7b6c98/src/extension.ts#L8

**Comment by RomanNikitenko** [comment]
@gautam-borkar 
I see that your code reads the variable before the `activate(context: vscode.ExtensionContext)` function is called.
I'm not sure if it matters - as I don't have details about the mechanism how variables are provided for the corresponding container. 

@svor @vitaliy-guliy 
could you take a look
any idea here?

**Comment by vitaliy-guliy** [comment]
@gautam-borkar 
The variable must be set to the container before the plugin startup. Could you please share your plugin meta.yaml?

There is a known issue, that you can apply the variable only if your plugin is running in separate container ( as @RomanNikitenko demonstrated on his video ).
If your plugin is running within che-theia, such injections of the variables does not work.
But you can try to workaround that by applying the variable to editor component.
```
  - type: cheEditor
    alias: che-theia
    id: eclipse/che-theia/latest
    env:
      - value: 'https://raw.githubusercontent.com/gautam-borkar/nodejs-express/master/README.md'
        name: DIDACT_FILE_URL

  - id: gborkar/didact-plugin/latest
    type: chePlugin
```

@skabashnyuk I asked you about that kind of variables injection (as @gautam-borkar reported ) about half a year ago. Is there any plans to implement it?
