### ISSUE TITLE
Cannot open Jupyter notebook with the python extension

### ISSUE THREAD

**Issue by sunix** [eclipse-che/che#20057]
### Describe the bug
With the latest che-theia, opening a Jupyter notebook is failing:

We can see errors logs in the python extension output like :
```
Error 2021-07-01 07:35:22: stat() failed for "/home/theia/.venv/bin/activate" Unavailable (FileSystemError): No file system provider found for scheme file-sidecar-vscode-python17o
    at ConsumerFileSystem._handleError (/remote-endpoint/node_modules/@theia/plugin-ext/lib/plugin/file-system-ext-impl.js:237:48)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async _.pathExists (/tmp/vscode-unpacked/ms-python.python.latest.fqbiwemdiz.ms-python-release.vsix/extension/out/client/extension.js:1:572896)
    at async /tmp/vscode-unpacked/ms-python.python.latest.fqbiwemdiz.ms-python-release.vsix/extension/out/client/extension.js:24:130723
    at async /tmp/vscode-unpacked/ms-python.python.latest.fqbiwemdiz.ms-python-release.vsix/extension/out/client/extension.js:24:130809
    at async Object.t.getType (/tmp/vscode-unpacked/ms-python.python.latest.fqbiwemdiz.ms-python-release.vsix/extension/out/client/extension.js:24:131106)
    at async v.getEnvironmentType (/tmp/vscode-unpacked/ms-python.python.latest.fqbiwemdiz.ms-python-release.vsix/extension/out/client/extension.js:48:837050)
    at async Promise.all (index 1)
    at async C.collectInterpreterDetails (/tmp/vscode-unpacked/ms-python.python.latest.fqbiwemdiz.ms-python-release.vsix/extension/out/client/extension.js:48:830883) {
  code: ''
}
```
in the editor window:
```
/tmp/vscode-unpacked/ms-python.python.latest.fqbiwemdiz.ms-python-release.vsix/extension/out/datascience-ui/notebook/require.js, /tmp/vscode-unpacked/ms-python.python.latest.fqbiwemdiz.ms-python-release.vsix/extension/out/datascience-ui/notebook/ipywidgets.js, /tmp/vscode-unpacked/ms-python.python.latest.fqbiwemdiz.ms-python-release.vsix/extension/out/datascience-ui/notebook/monaco.bundle.js, /tmp/vscode-unpacked/ms-python.python.latest.fqbiwemdiz.ms-python-release.vsix/extension/out/datascience-ui/notebook/commons.initial.bundle.js, /tmp/vscode-unpacked/ms-python.python.latest.fqbiwemdiz.ms-python-release.vsix/extension/out/datascience-ui/notebook/nativeEditor.js is not a valid file name
```
![image](https://user-images.githubusercontent.com/650571/124085542-72037480-da50-11eb-8537-4269043d314a.png)

### Che version

 - [x] latest
 - [ ] nightly
 - [ ] other: please specify

### Steps to reproduce

with the devfile:
```
apiVersion: 1.0.0
metadata:
  generateName: python-jupyter-
projects:
  - name: jupyter-hello-world1
    source:
      startPoint: master
      location: 'https://github.com/chasbecker/TextAnalysis.git'
      type: git
components:
  - id: ms-python/python/latest
    type: chePlugin
  - mountSources: true
    memoryLimit: 512Mi
    type: dockerimage
    volumes:
      - name: venv
        containerPath: /home/user/.venv
    image: 'quay.io/eclipse/che-python-3.8:7.29.0'
    alias: python
commands:
  - name: set up venv with requirements
    actions:
      - workdir: /home/user
        type: exec
        command: python -m venv .venv && . .venv/bin/activate && python -m pip install -r /projects/jupyter-hello-world1/requirements.txt
        component: python
```

1. start a workspace from the devfile
2. open the file AzureTextAnalysisRestAPI.ipynb 
3. observe the error

### Expected behavior
Should start the jupyter server and open the editor notebook. This was working a month ago:
See video provided in https://github.com/eclipse-che/che-plugin-registry/pull/958

### Runtime
   - [ ] kubernetes (include output of `kubectl version`)
   - [ ] Openshift (include output of `oc version`)
   - [ ] minikube (include output of `minikube version` and `kubectl version`)
   - [ ] minishift (include output of `minishift version` and `oc version`)
   - [ ] docker-desktop + K8S (include output of `docker version` and `kubectl version`)
   - [ ] other: (please specify)

### Installation method
   - [ ] chectl
     * provide a full command that was used to deploy Eclipse Che (including the output)
     * provide an output of `chectl version` command
   - [ ] OperatorHub
   - [ ] I don't know

### Environment
   - [ ] my computer
       - [ ] Windows
       - [ ] Linux
       - [ ] macOS
   - [ ] Cloud
       - [ ] Amazon
       - [ ] Azure
       - [ ] GCE
       - [ ] other (please specify)
   - [ ] Dev Sandbox (workspaces.openshift.com)
   - [ ] other: please specify
