### ISSUE TITLE
Dogfooding instance fails to start workspace

### ISSUE THREAD

**Issue by tsmaeder** [eclipse-che/che#20052]
### Describe the bug
The dogfooding instance fails to start the following devfile with a timeout:

<details>

```yaml
apiVersion: 1.0.0
metadata:
  name: linklessbuild2
projects:
  - name: theia
    source:
      startPoint: master
      location: 'https://github.com/eclipse-theia/theia'
      type: git
  - name: vscode-test-extension
    source:
      startPoint: master
      location: 'https://github.com/RomanNikitenko/vscode-test-extension.git'
      type: git
    clonePath: test/vscode-test-extension
  - name: che-theia
    source:
      startPoint: master
      location: 'https://github.com/eclipse-che/che-theia'
      type: git
components:
  - id: ms-vscode/node-debug2/latest
    type: chePlugin
    alias: node-debug
  - mountSources: true
    endpoints:
      - attributes:
          protocol: http
          public: 'true'
        name: theia-dev-flow
        port: 3010
    memoryLimit: 5Gi
    type: dockerimage
    alias: che-dev
    image: 'quay.io/eclipse/che-theia-dev:next'
    env:
      - value: 2504;
        name: THEIA_PLUGIN_ENDPOINT_DISCOVERY_PORT
  - mountSources: true
    memoryLimit: 1Gi
    type: dockerimage
    alias: plugin-host
    image: 'quay.io/eclipse/che-theia-dev:next'
    env:
      - value: 2504;
        name: THEIA_PLUGIN_ENDPOINT_DISCOVERY_PORT
      - value: 'local-dir:///projects/plugins1/'
        name: THEIA_PLUGINS
      - value: /projects/java-11-openjdk
        name: JAVA_HOME
  - id: eclipse/che-theia/next
    memoryLimit: 2048Mi
    registryUrl: 'https://eclipse-che.github.io/che-plugin-registry/main/v3/'
    type: cheEditor
  - id: redhat/java11/latest
    type: chePlugin
  - id: che-incubator/typescript/latest
    memoryLimit: 2Gi
    type: chePlugin
  - id: timonwong/shellcheck/latest
    type: chePlugin
```

</details>

### Che version

 - [ ] dogfooding instance at https://che-dogfooding.apps.che-dev.x6e0.p1.openshiftapps.com/

### Steps to reproduce

Make the new workspace with the devfile above.

### Expected behavior
The workspace should run.

### Runtime
   - [ ] kubernetes (include output of `kubectl version`)
   - [ ] Openshift (include output of `oc version`)
   - [ ] minikube (include output of `minikube version` and `kubectl version`)
   - [ ] minishift (include output of `minishift version` and `oc version`)
   - [ ] docker-desktop + K8S (include output of `docker version` and `kubectl version`)
   - [ ] other: (please specify)

### Installation method
   - [ ] chectl
     * provide a full command that was used to deploy Eclipse Che (including the output)
     * provide an output of `chectl version` command
   - [ ] OperatorHub
   - [x] I don't know

### Environment
   - [ ] my computer
       - [ ] Windows
       - [ ] Linux
       - [ ] macOS
   - [ ] Cloud
       - [ ] Amazon
       - [ ] Azure
       - [ ] GCE
       - [x] other (please specify)
   - [ ] Dev Sandbox (workspaces.openshift.com)
   - [ ] other: please specify

**Comment by benoitf** [comment]
![Screenshot 2021-06-30 at 17 28 43](https://user-images.githubusercontent.com/436777/123988907-b1867e00-d9c8-11eb-910f-e6100b5aa216.png)

anyway I tried your devfile and it's starting. But you're referring to master branch that has been renamed to main (leading an error when opening the IDE)

**Comment by tsmaeder** [comment]
> But you're referring to master branch that has been renamed to main

@benoitf main vs. master is a red herring: my problem happens a long time before the IDE ever opens.

**Comment by tsmaeder** [comment]
Also, looks like Che to me 🤷 

![Capture](https://user-images.githubusercontent.com/13163770/124084481-4f249080-da4f-11eb-888a-330fa74cc211.PNG)

**Comment by l0rd** [comment]
@tsmaeder since the same devfile on the same cluster  works for others, your problem should be related to a particular configuration of your account or to some objects that are in the namespace and are using resources. I think it would be useful if you could provide your namespace OpenShift events when you start the workspace.

@ibuziuk do you know if we are showing a specific error when there are not enough resources to start the workspace (CPU/RAM/PVs) or if a PV fails to get attached. Or are we just failing for timeout?

@sleshchenko I think that the new dashboard is providing less details about errors, is there something that comes to your mind here? Something @tsmaeder can do to get more information on the nature of the error.

**Comment by sleshchenko** [comment]
I have created an issue to improve the situation with devworkspaces: Dashboard should expose workspace related events in output https://github.com/eclipse/che/issues/20066

But then I checked and see it's devfile v1. So, a new dashboard provides as many details as the previous one used to provide.
@tsmaeder any info in output?

**Comment by sleshchenko** [comment]
I see two issues:

1. Workspace pod can't be created due

> docker pull quay.io/eclipse/che-machine-exec@sha256:916929bb252f1bff813327e3bffa3641c4f79fcde802f00349aa4cb644826fe9
Error response from daemon: manifest for quay.io/eclipse/che-machine-exec@sha256:916929bb252f1bff813327e3bffa3641c4f79fcde802f00349aa4cb644826fe9 not found: manifest unknown: manifest unknown

2. Mkdir pod hangs due:

> the mkdir-pod says "Unable to attach or mount volumes: unmounted volumes=[claim-che-workspace], unattached volumes=[default-token-tvnln claim-che-workspace]: timed out waiting for the condition"

**Comment by benoitf** [comment]
@sleshchenko I don't see how you could reference the issue 'workspace pod could not pull che-machine-exec'

as the devfile specified in the issue is:
```yaml
  - id: eclipse/che-theia/next
    memoryLimit: 2048Mi
    registryUrl: 'https://eclipse-che.github.io/che-plugin-registry/main/v3/'
```

then it doesn't fetch definition from the current registry but from an external location which has no sha256
