### ISSUE TITLE
Changing CheCluster storage.pvcClaimSize is not updating PersistentVolumeClaim spec.resources.requests.storage

### ISSUE THREAD

**Issue by sunix** [eclipse-che/che#20061]
### Describe the bug
Updating PVC storage size from the operator is not working.

### Che version

 - [x] latest
 - [ ] nightly
 - [ ] other: please specify

### Steps to reproduce

As an administrator, My users are running out of disk space, I would like to increase the size of their PVC.
Updated CheCluster CR:
```
specs:
  storage:
    preCreateSubPaths: true
    pvcClaimSize: 1Gi
    pvcStrategy: common
```
to
```
specs:
  storage:
    preCreateSubPaths: true
    pvcClaimSize: 7Gi
    pvcStrategy: common
```
I expected all my PVC claim-che-workspace to be updated but still 1Gi:
```
kind: PersistentVolumeClaim
spec:
  resources:
    requests:
      storage: 1Gi
  storageClassName: standard
  volumeMode: Filesystem
  volumeName: pvc-cdaa906c-979c-41ad-92c9-81c5a2988fb8
```

### Expected behavior
I had to update each PersistentVolumeClaim manually to have the storage requested size updated. I think it should be done at the operator level.

### Runtime
   - [x] kubernetes (include output of `kubectl version`)
   - [ ] Openshift (include output of `oc version`)
   - [ ] minikube (include output of `minikube version` and `kubectl version`)
   - [ ] minishift (include output of `minishift version` and `oc version`)
   - [ ] docker-desktop + K8S (include output of `docker version` and `kubectl version`)
   - [ ] other: (please specify)

### Installation method
   - [x] chectl
     * provide a full command that was used to deploy Eclipse Che (including the output)
     * provide an output of `chectl version` command
   - [ ] OperatorHub
   - [ ] I don't know

### Environment
   - [ ] my computer
       - [ ] Windows
       - [ ] Linux
       - [ ] macOS
   - [x] Cloud
       - [ ] Amazon
       - [ ] Azure
       - [x] GCE
       - [ ] other (please specify)
   - [ ] Dev Sandbox (workspaces.openshift.com)
   - [ ] other: please specify
