### ISSUE TITLE
"checlt server:deploy" command failed to deploy operator pod: error "'RELATED_IMAGE_gateway_authentication_sidecar'. Environment variable with default value was not found."

### ISSUE THREAD

**Issue by RomanNikitenko** [eclipse-che/che#20073]
### Describe the bug

`Happy path` tests fails on the Eclipse Che `Deploy` step.
The error is:
```
stderr: '    Error: Command server:deploy failed. Error log: \n' +
    '    /home/runner/.cache/chectl/error.log. Eclipse Che logs: \n' +
    '    /tmp/chectl-logs/1625429415235.',
```

Operator pod logs:
https://main-jenkins-csb-crwqe.apps.ocp4.prod.psi.redhat.com/job/Che/job/e2e/job/minikube/job/basic/job/che-server/287/artifact/logs-and-configs/che-logs/che-operator-5dcbfd85bf-wwrws.pod.log
```
time="2021-07-04T04:29:18Z" level=fatal msg="Failed to initialize default value: 'RELATED_IMAGE_gateway_authentication_sidecar'. Environment variable with default value was not found."
```

### Che version

 - [ ] latest
 - [x] nightly
 - [ ] other: please specify

### Che installation
chectl/0.0.20210702-next.ba26304 linux-x64 node-v12.22.1
```
chectl server:deploy --k8spodreadytimeout=600000 --k8spodwaittimeout=600000 --k8spoddownloadimagetimeout=600000 --listr-renderer=verbose --platform=minikube --che-operator-cr-patch-yaml=custom-resource-patch.yaml --telemetry=off --chenamespace=eclipse-che
```
where custom-resource-patch.yaml content:
```
spec:
  server:
    cheImage: 'quay.io/eclipse/che-server'
    cheImageTag: 'nightly'
    customCheProperties:
      CHE_LIMITS_USER_WORKSPACES_RUN_COUNT: '-1'
      CHE_WORKSPACE_SIDECAR_IMAGE__PULL__POLICY: IfNotPresent
      CHE_WORKSPACE_PLUGIN__BROKER_PULL__POLICY: IfNotPresent
      CHE_INFRA_KUBERNETES_WORKSPACE_START_TIMEOUT_MIN: '12'
  auth:
    updateAdminPassword: false
```

### Steps to reproduce
I detected a problem on `che-theia` PR's check.
Please see https://github.com/eclipse-che/che-theia/pull/1157 or https://github.com/eclipse-che/che-theia/pull/1049
### Screenshots

![happy_path_failure](https://user-images.githubusercontent.com/5676062/124425147-d126f900-dd70-11eb-80b0-7543948f4025.png)

![deploy_failure](https://user-images.githubusercontent.com/5676062/124424964-92913e80-dd70-11eb-991c-7100e1d32899.png)
