### ISSUE TITLE
Cannot build che-theia with linkless build

### ISSUE THREAD

**Issue by sunix** [eclipse-che/che#20083]
### Is your task related to a problem? Please describe.
We recently introduced linkless build for che-theia that should replace the current build strategy. However, it looks like it is not possible to build che-theia with it at the moment:

![Selection_424](https://user-images.githubusercontent.com/650571/124639223-33285100-de8c-11eb-8174-4dbb940b0f7c.png)

```
 $ yarn
yarn install v1.22.5
[1/5] Validating package.json...
[2/5] Resolving packages...
success Already up-to-date.
$ yarn run clean && yarn build && yarn download:plugins
yarn run v1.22.5
$ theia clean && rimraf errorShots
Done in 0.70s.
yarn run v1.22.5
$ theia build --mode production --config cdn/webpack.config.js --env cdn=./cdn.json --env monacopkg=@theia/monaco-editor-core@0.20.0 && yarn run override-vs-loader
Failed to resolve module: filenamify
[webpack-cli] Failed to load '/projects/che-theia/assembly/cdn/webpack.config.js' config

[webpack-cli] Error: Cannot find module 'circular-dependency-plugin'
Require stack:
- /projects/che-theia/assembly/gen-webpack.config.js
- /projects/che-theia/assembly/webpack.config.js
- /projects/che-theia/assembly/cdn/webpack.config.js
- /projects/theia/node_modules/webpack-cli/lib/webpack-cli.js
- /projects/theia/node_modules/webpack-cli/lib/bootstrap.js
- /projects/theia/node_modules/webpack-cli/bin/cli.js
- /projects/theia/node_modules/webpack/bin/webpack.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:815:15)
    at Function.Module._load (internal/modules/cjs/loader.js:667:27)
    at Module.require (internal/modules/cjs/loader.js:887:19)
    at require (/projects/theia/node_modules/v8-compile-cache/v8-compile-cache.js:159:20)
    at Object.<anonymous> (/projects/che-theia/assembly/gen-webpack.config.js:10:34)
    at Module._compile (/projects/theia/node_modules/v8-compile-cache/v8-compile-cache.js:192:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
    at Module.load (internal/modules/cjs/loader.js:863:32)
    at Function.Module._load (internal/modules/cjs/loader.js:708:14)
    at Module.require (internal/modules/cjs/loader.js:887:19)
    at require (/projects/theia/node_modules/v8-compile-cache/v8-compile-cache.js:159:20)
    at Object.<anonymous> (/projects/che-theia/assembly/webpack.config.js:6:16)
    at Module._compile (/projects/theia/node_modules/v8-compile-cache/v8-compile-cache.js:192:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
    at Module.load (internal/modules/cjs/loader.js:863:32)
    at Function.Module._load (internal/modules/cjs/loader.js:708:14) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/projects/che-theia/assembly/gen-webpack.config.js',
    '/projects/che-theia/assembly/webpack.config.js',
    '/projects/che-theia/assembly/cdn/webpack.config.js',
    '/projects/theia/node_modules/webpack-cli/lib/webpack-cli.js',
    '/projects/theia/node_modules/webpack-cli/lib/bootstrap.js',
    '/projects/theia/node_modules/webpack-cli/bin/cli.js',
    '/projects/theia/node_modules/webpack/bin/webpack.js'
  ]
}

Error: webpack exited with an unexpected code: 2.
```

To reproduce, use this devfile:
```
apiVersion: 1.0.0
metadata:
  generateName: che-theia-linklessbuild-
projects:
  - name: theia
    source:
      startPoint: master
      location: 'https://github.com/eclipse-theia/theia'
      type: git
  - name: vscode-test-extension
    source:
      startPoint: master
      location: 'https://github.com/RomanNikitenko/vscode-test-extension.git'
      type: git
    clonePath: test/vscode-test-extension
  - name: che-theia
    source:
      location: 'https://github.com/eclipse-che/che-theia'
      type: git
components:
  - alias: didact-plugin
    type: chePlugin
    id: redhat/vscode-didact/latest
    preferences:
      didact.openDefaultTutorialAtStartup: true
      che.welcome.enable: false
      didact.defaultUrl: /projects/che-theia/linkless-build.md
    registryUrl: 'https://che-plugin-registry-main.surge.sh/v3'
  - id: github/vscode-pull-request-github/latest
    type: chePlugin
  - id: redhat/vscode-yaml/latest
    type: chePlugin
  - id: ms-vscode/node-debug2/latest
    type: chePlugin
    alias: node-debug
  - mountSources: true
    endpoints:
      - attributes:
          protocol: http
          public: 'true'
        name: theia-dev-flow
        port: 3010
    memoryLimit: 5Gi
    type: dockerimage
    alias: che-dev
    image: 'quay.io/eclipse/che-theia-dev:next'
    env:
      - value: 2504;
        name: THEIA_PLUGIN_ENDPOINT_DISCOVERY_PORT
  - mountSources: true
    memoryLimit: 1Gi
    type: dockerimage
    alias: plugin-host
    image: 'quay.io/eclipse/che-theia-dev:next'
    env:
      - value: 2504;
        name: THEIA_PLUGIN_ENDPOINT_DISCOVERY_PORT
      - value: 'local-dir:///projects/plugins1/'
        name: THEIA_PLUGINS
      - value: /projects/java-11-openjdk
        name: JAVA_HOME
  - id: eclipse/che-theia/next
    memoryLimit: 1Gi
    type: cheEditor
    alias: theia-editor
    env:
      - value: '0'
        name: NODE_TLS_REJECT_UNAUTHORIZED
  - id: che-incubator/typescript/latest
    memoryLimit: 2Gi
    type: chePlugin
  - id: redhat/java11/latest
    type: chePlugin
  - id: timonwong/shellcheck/latest
    type: chePlugin
commands:
  - name: Run plugin host
    actions:
      - workdir: /projects/theia/che/che-theia/extensions/eclipse-che-theia-plugin-remote/lib/node
        type: exec
        command: node plugin-remote.js
        component: plugin-host
  - name: Debug plugin host
    actions:
      - workdir: /projects/theia/che/che-theia/extensions/eclipse-che-theia-plugin-remote/lib/node
        type: exec
        command: node --inspect-brk=8888 plugin-remote.js
        component: plugin-host
  - name: Run back end
    actions:
      - workdir: /projects/che-theia/assembly
        type: exec
        command: 'yarn run start --hostname=0.0.0.0 --port=3010 --plugins=local-dir:/projects/theia/plugins'
        component: che-dev
  - name: Debug back end
    actions:
      - workdir: /projects/che-theia/assembly
        type: exec
        command: 'yarn run start --inspect-brk=9999 --hostname=0.0.0.0 --port=3010 --plugins=local-dir:/projects/theia/plugins'
        component: che-dev
  - name: Debug Configs
    actions:
      - referenceContent: |
          {
            "name": "Attach to Plugin Host",
            "type": "node",
            "request": "attach",
            "port": 8888,
            "outFiles": [
                "/projects/theia/packages/**/*.js",
                "/projects/theia/che/che-theia/exensions/**/*.js"
            ]
          }, {
            "name": "Attach to Back End",
            "type": "node",
            "request": "attach",
            "port": 9999,
            "outFiles": [
                "/projects/theia/packages/**/*.js"
                "/projects/theia/examples/**/*.js"
            ]
          }
        type: vscode-launch
```
and follow https://github.com/eclipse-che/che-theia/blob/main/linkless-build.md

you may need to `git reset --hard a378cfb5d9530e883612b4920890c083cae8a705` in /projects/theia
and do an `che-theia generate` after `che-theia link`

### Describe the solution you'd like
Should be able to build

**Comment by sunix** [comment]
I maybe related to the webpack upgrade
I can see
```
warning "workspace-aggregator-bdffdee8-5505-4230-b837-216730d0f6bd > @eclipse-che/theia-assembly > @theia/compression-webpack-plugin@3.0.0" has unmet peer dependency "webpack@^4.3.0".
```
also 
```
yarn why @theia/compression-webpack-plugin
yarn why v1.22.5
[1/4] Why do we have the module "@theia/compression-webpack-plugin"...?
[2/4] Initialising dependency graph...
[3/4] Finding dependency...
[4/4] Calculating file sizes...
=> Found "@theia/compression-webpack-plugin@3.0.0"
info Reasons this module exists
   - "_project_#@eclipse-che#theia-assembly#@theia#cli#@theia#application-manager" depends on it
   - Hoisted from "_project_#@eclipse-che#theia-assembly#@theia#cli#@theia#application-manager#@theia#compression-webpack-plugin"
Done in 2.25s
```

**Comment by sunix** [comment]
My tries:
1. align https://github.com/eclipse-che/che-theia/blob/main/extensions/eclipse-che-theia-plugin-ext/package.json#L34 ... but it is not related ... the problem is @theia/compression-webpack-plugin@3.0.0 which is bringing the wrong version of webpack
2. tried to use compression-webpack-plugin" "version": "8.0.1" but theia is not building anymore after this

TODO
try to clone build and use https://github.com/theia-ide/compression-webpack-plugin with the aligned version of webpack

**Comment by sunix** [comment]
I have tried with a modified compression-webpack-plugin and the build is ok now. But now starting and trying to access to the new Che-theia, it fails with an empty black screen.
My devfile :
```yaml
apiVersion: 1.0.0
metadata:
  generateName: che-theia-linklessbuild-
projects:
  - name: theia
    source:
      location: 'https://github.com/sunix/theia'
      type: git
      startPoint: che-linklessbuild-fix-investigation
  - name: vscode-test-extension
    source:
      location: 'https://github.com/RomanNikitenko/vscode-test-extension.git'
      type: git
    clonePath: test/vscode-test-extension
  - name: che-theia
    source:
      location: 'https://github.com/eclipse-che/che-theia'
      type: git
  - name: compression-webpack-plugin
    source:
      startPoint: master
      location: 'https://github.com/sunix/compression-webpack-plugin'
      type: git
components:
  - id: redhat/vscode-didact/latest
    preferences:
      didact.defaultUrl: /projects/che-theia/linkless-build.md
      che.welcome.enable: false
      didact.openDefaultTutorialAtStartup: true
    registryUrl: 'https://che-plugin-registry-main.surge.sh/v3'
    type: chePlugin
    alias: didact-plugin
  - id: github/vscode-pull-request-github/latest
    type: chePlugin
  - id: redhat/vscode-yaml/latest
    type: chePlugin
  - id: ms-vscode/node-debug2/latest
    type: chePlugin
    alias: node-debug
  - mountSources: true
    endpoints:
      - attributes:
          protocol: http
          public: 'true'
        name: theia-dev-flow
        port: 3010
    memoryLimit: 5Gi
    type: dockerimage
    alias: che-dev
    image: 'quay.io/sunix/che-theia-dev:next'
    env:
      - value: 2504;
        name: THEIA_PLUGIN_ENDPOINT_DISCOVERY_PORT
  - mountSources: true
    memoryLimit: 1Gi
    type: dockerimage
    alias: plugin-host
    image: 'quay.io/sunix/che-theia-dev:next'
    env:
      - value: 2504;
        name: THEIA_PLUGIN_ENDPOINT_DISCOVERY_PORT
      - value: 'local-dir:///projects/plugins1/'
        name: THEIA_PLUGINS
      - value: /projects/java-11-openjdk
        name: JAVA_HOME
  - id: eclipse/che-theia/next
    memoryLimit: 1Gi
    type: cheEditor
    alias: theia-editor
    env:
      - value: '0'
        name: NODE_TLS_REJECT_UNAUTHORIZED
  - id: che-incubator/typescript/latest
    memoryLimit: 2Gi
    type: chePlugin
  - id: redhat/java11/latest
    type: chePlugin
  - id: timonwong/shellcheck/latest
    type: chePlugin
commands:
  - name: Run plugin host
    actions:
      - workdir: /projects/che-theia/extensions/eclipse-che-theia-plugin-remote/lib/node
        type: exec
        command: node plugin-remote.js
        component: plugin-host
  - name: Debug plugin host
    actions:
      - workdir: /projects/che-theia/extensions/eclipse-che-theia-plugin-remote/lib/node
        type: exec
        command: node --inspect-brk=8888 plugin-remote.js
        component: plugin-host
  - name: Run back end
    actions:
      - workdir: /projects/che-theia/assembly
        type: exec
        command: yarn run start --hostname=0.0.0.0 --port=3010
        component: che-dev
  - name: Build Theia
    actions:
      - workdir: /projects/theia
        type: exec
        command: yarn
        component: che-dev
  - name: Generate and link che-theia
    actions:
      - workdir: /projects/che-theia
        type: exec
        command: che-theia link && che-theia generate && rm yarn.lock
        component: che-dev
  - name: Build che-theia
    actions:
      - workdir: /projects/che-theia
        type: exec
        command: yarn
        component: che-dev
  - name: Debug back end
    actions:
      - workdir: /projects/che-theia/assembly
        type: exec
        command: yarn run start --inspect-brk=9999 --hostname=0.0.0.0 --port=3010
        component: che-dev
  - name: Debug Configs
    actions:
      - referenceContent: |
          {
            "name": "Attach to Plugin Host",
            "type": "node",
            "request": "attach",
            "port": 8888,
            "outFiles": [
                "/projects/theia/packages/**/*.js",
                "/projects/che-theia/exensions/**/*.js"
            ]
          }, {
            "name": "Attach to Back End",
            "type": "node",
            "request": "attach",
            "port": 9999,
            "outFiles": [
                "/projects/theia/packages/**/*.js"
                "/projects/theia/examples/**/*.js"
            ]
          }
        type: vscode-launch
```
