### ISSUE TITLE
[regression]Failed to run the "vscode-xml" plugin because of absence of the "redhat.vscode-commons" dependency

### ISSUE THREAD

**Issue by Ohrimenko1988** [eclipse-che/che#20094]
### Describe the bug
Failed to run the "vscode-xml" plugin because of absence of the "redhat.vscode-commons" dependency

### Che version

 - [ x ] latest
 - [ ] nightly
 - [ ] other: please specify

### Steps to reproduce

 - Create workspace using next devfile:
```
apiVersion: 1.0.0
metadata:
  name: xml-plugin-test
projects:
  - name: nodejs-web-app
    source:
      location: 'https://github.com/che-samples/web-nodejs-sample.git'
      branch: che-qe-tests
      type: git
components:
  - id: redhat/vscode-xml/latest
    type: chePlugin

```
 - Go inside created workspace
 - Open the "hello.xml" file
 - Pay attention to the displayed notifications with errors (see attachments)

### Expected behavior
The "vscode-xml" plugin activated and ready to work

### Observed behavior
Activation of the "vscode-xml" plugin has been failed.

### Runtime
   - [ ] kubernetes (include output of `kubectl version`)
   - [ ] Openshift (include output of `oc version`)
   - [ x ] minikube (include output of `minikube version` and `kubectl version`)
   - [ ] minishift (include output of `minishift version` and `oc version`)
   - [ ] docker-desktop + K8S (include output of `docker version` and `kubectl version`)
   - [ ] other: (please specify)

### Screenshots
![Screenshot from 2021-07-07 15-02-39](https://user-images.githubusercontent.com/22724619/124757633-77702b80-df36-11eb-9f33-4e4fc1e5152e.png)

![Screenshot from 2021-07-07 15-03-14](https://user-images.githubusercontent.com/22724619/124757642-7939ef00-df36-11eb-812b-a5cee9bae05c.png)

### Installation method
   - [ x ] chectl
```
chectl server:deploy \
  --k8spodreadytimeout=600000 \
  --k8spodwaittimeout=600000 \
  --k8spoddownloadimagetimeout=600000 \
  --listr-renderer=verbose \
  --platform=minikube \
  --chenamespace=iokhrime-che \
  --telemetry=off
```
   - [ ] OperatorHub
   - [ ] I don't know

### Environment
   - [ x ] my computer
       - [ ] Windows
       - [ x ] Linux
       - [ ] macOS
   - [ ] Cloud
       - [ ] Amazon
       - [ ] Azure
       - [ ] GCE
       - [ ] other (please specify)
   - [ ] Dev Sandbox (workspaces.openshift.com)
   - [ ] other: please specify
