### ISSUE TITLE
'Try it' buttons on Che Theia PR are not working 

### ISSUE THREAD

**Issue by RomanNikitenko** [eclipse-che/che#20099]
### Describe the bug

I'm not able to start a workspace using `Try it` buttons.
The error is: 
````
Cause: Devfile schema validation failed. Error: (/metadata):The value must be of object type, but actual type is null.(/generateName):The object must not have a property whose name is "generateName".(/projects/0):The object must have a property whose name is "source".(/source):The object must not have a property whose name is "source".(/type):The object must not have a property whose name is "type".(/location):The object must not have a property whose name is "location".(/branch):The object must not have a property whose name is "branch".(/components/0):The object must have a property whose name is "type".
`````
### Che version

  - [x] nightly
 

### Steps to reproduce
Try to use `Try it` buttons on a PR to `che-theia`

The URL is like the following:
`https://workspaces.openshift.com/f?url=https://raw.githubusercontent.com/chepullreq4/pr-check-files/master/che-theia/pr-1161/simple/che-theia-simple-devfile.yaml`

### Screenshots

![try_it](https://user-images.githubusercontent.com/5676062/124876156-607f1700-dfd2-11eb-9fbb-e67fcbbdd21f.png)

<img width="1548" alt="try_it_error" src="https://user-images.githubusercontent.com/5676062/124876434-a936d000-dfd2-11eb-9ac1-217c945acaf2.png">

**Comment by sleshchenko** [comment]
As far as I see it happens due broken yaml:
```bash
> curl https://raw.githubusercontent.com/chepullreq4/pr-check-files/master/che-theia/pr-1161/simple/che-theia-simple-devfile.yaml

apiVersion: 1.0.0
metadata:
generateName: pr-che_theia-1161-
projects:
- name: pr-1161
source:
type: git
location: 'https://github.com/eclipse-che/che-theia.git'
branch: 'dontSetPublicUrlValueToInternalUrlSettings'
components:
- reference: https://raw.githubusercontent.com/chepullreq4/pr-check-files/master/che-theia/pr-1161/simple/che-theia-editor.yaml
type: cheEditor
```
^ spaces are missing, it should be like:
```
apiVersion: 1.0.0
metadata:
  generateName: pr-che_theia-1161-
projects:
- name: pr-1161
source:
  type: git
  location: 'https://github.com/eclipse-che/che-theia.git'
  branch: 'dontSetPublicUrlValueToInternalUrlSettings'
components:
- reference: https://raw.githubusercontent.com/chepullreq4/pr-check-files/master/che-theia/pr-1161/simple/che-theia-editor.yaml
  type: cheEditor
```
I'm not sure who owns chepullreq4/pr-check-files, adding che theia area.

**Comment by RomanNikitenko** [comment]
> I'm not sure who owns chepullreq4/pr-check-files

I'm not sure as well, maybe @dmytro-ndp knows...

**Comment by dmytro-ndp** [comment]
@RomanNikitenko: Che QE team is responsible for Che Theia PR check on CRW Jenkins including `Try it` buttons.

**Comment by dmytro-ndp** [comment]
@sleshchenko: thanks for the root cause analysis!

Small remark: `source` is `projects` property and so should be placed at the `projects` level:
```
apiVersion: 1.0.0
metadata:
  generateName: pr-che_theia-1161-
projects:
- name: pr-1161
  source:
    type: git
    location: 'https://github.com/eclipse-che/che-theia.git'
    branch: 'dontSetPublicUrlValueToInternalUrlSettings'
components:
- reference: https://raw.githubusercontent.com/chepullreq4/pr-check-files/master/che-theia/pr-1161/simple/che-theia-editor.yaml
  type: cheEditor
```
