### ISSUE TITLE
Cannot create a project with a name that starts with "."

### ISSUE THREAD

**Issue by gorshkov-leonid** [eclipse-che/che#20107]
Failed to create a new workspace from the devfile, reason: Invalid project name found:'.common'. Name must contain only Latin letters,digits or these following special characters ._-

According to message I can use symbol .

### Che version
7.32.1

### Steps to reproduce
Add section to devfile and try to create worspace
```
projects: 
  - name: .common
    source:
      type: zip
      location: <somewhere>/some.zip
```
### Screenshots
![image](https://user-images.githubusercontent.com/2270831/124927818-b4f0b980-e007-11eb-87d2-b8027bde9803.png)
