### ISSUE TITLE
Correct CSVs and metadata in order to get scorecard to fully pass its tests

### ISSUE THREAD

**Issue by tolusha** [eclipse-che/che#20118]
### Is your task related to a problem? Please describe.

SDK Scorecard Validation
Che-Operator project was checked against the default Scorecard image configuration which is
added by default in the projects which are generated using SDK. These tests are being
run by CVP now, but are not gating releases at this time. Here is the scorecard test
output against your latest bundle version

```yaml
Image: quay.io/operator-framework/scorecard-test:v1.5.0
Entrypoint: [scorecard-test olm-spec-descriptors]
Labels:
"suite":"olm"
"test":"olm-spec-descriptors-test"
Results:
Name: olm-spec-descriptors
State: fail
Suggestions:
Add a spec descriptor for auth
Add a spec descriptor for database
Add a spec descriptor for metrics
Add a spec descriptor for server
Add a spec descriptor for storage
Errors:
auth does not have a spec descriptor
database does not have a spec descriptor
metrics does not have a spec descriptor
server does not have a spec descriptor
storage does not have a spec descriptor
```

```yaml
Image: quay.io/operator-framework/scorecard-test:v1.5.0
Entrypoint: [scorecard-test olm-crds-have-resources]
Labels:
"suite":"olm"
"test":"olm-crds-have-resources-test"
Results:
Name: olm-crds-have-resources
State: fail
Errors:
Owned CRDs do not have resources specified
```

### Describe the solution you'd like

Correct CSVs and metadata in order to get scorecard to fully pass its tests

### Describe alternatives you've considered

N/A

### Additional context

https://sdk.operatorframework.io/docs/advanced-topics/scorecard/scorecard/
