### ISSUE TITLE
As a developer, I want to have a link automatically generated for verifying a PR on workspaces.openshift.com

### ISSUE THREAD

**Issue by ibuziuk** [eclipse-che/che#20155]
### Is your task related to a problem? Please describe.
As a developer, I want to have a link automatically generated for verifying a PR on workspaces.openshift.com:

### Describe the solution you'd like
- a developer opens a PR to one of the Eclipse Che related repositories
- a link to workspaces.openshift.com is automatically generated in the following format:

`https://workspaces.openshift.com#https://github.com/fork/repo/tree/branch` e.g.

[![Contribute](https://raw.githubusercontent.com/redhat-developer-demos/quarkus-reactjs-postit-app/master/factory-contribute.svg)](https://workspaces.openshift.com#https://github.com/ibuziuk/che-docs/tree/che-19271)

### Describe alternatives you've considered
N/A

### Additional context
ideally, the `Try it on Eclipse Che hosted by Red Hat` link should be generated for every Eclipse Che related repo and every PR

**Comment by nickboldt** [comment]
> Try it on Eclipse Che hosted by Red Hat

Should the link be labelled "Open this PR in Developer Workspace" ? or is "Eclipse Che hosted by Red Hat" the official name?

**Comment by ibuziuk** [comment]
Eclipse Che hosted by Red Hat is the official name - https://www.eclipse.org/che/docs/che-7/hosted-che/hosted-che/
However, I think just generate the following badge:

[![Contribute](https://raw.githubusercontent.com/redhat-developer-demos/quarkus-reactjs-postit-app/master/factory-contribute.svg)](https://workspaces.openshift.com#https://github.com/ibuziuk/che-docs/tree/che-19271)

**Comment by l0rd** [comment]
cc @benoitf

**Comment by benoitf** [comment]
would be nice to have badge available on shields.io

**Comment by l0rd** [comment]
> would be nice to have badge available on shields.io

There is a [simple icon](https://simpleicons.org/?q=eclipse%20che) for Che. So we can use something like `https://img.shields.io/static/v1?logo=eclipse-che&label=label&message=message`. For example: 
![](https://img.shields.io/badge/Eclipse_Che-Hosted%20by%20Red%20Hat-525C86?logo=eclipse-che&labelColor=FDB940)

**Comment by ibuziuk** [comment]
The action has been created

```
on: pull_request

jobs:
  example_comment_pr:
    runs-on: ubuntu-latest
    name: Try the PR on Eclipse Che hosted by Red Hat
    steps:
      - name: Checkouthttps://github.com/eclipse/che-docs/pull/2092
        uses: actions/checkout@v1

      - name: Comment PR
        uses: thollander/actions-comment-pull-request@master
        with:
          message: 'Try the PR on Eclipse Che hosted by Red Hat [![Contribute](https://img.shields.io/badge/Eclipse_Che-Hosted%20by%20Red%20Hat-525C86?logo=eclipse-che&labelColor=FDB940)](https://workspaces.openshift.com#https://github.com/${{ github.event.pull_request.head.repo.full_name }}/tree/${{ github.head_ref }})'
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
```

Each Eclipse Che repo should have it in place. Example https://github.com/eclipse/che-docs/pull/2092
