### ISSUE TITLE
devfile using `sparseCheckoutDir` in conjunction with a `branch` doesn't work right

### ISSUE THREAD

**Issue by edeandrea** [eclipse-che/che#20157]
### Describe the bug
I'm using the CodeReady Workspaces thats part of the Red Hat developer sandbox (https://workspaces.openshift.com). I have a devfile in my project with a `projects` section that looks like this:

```yaml
projects:
  - name: rhoar-getting-started
    source:
      type: git
      location: https://github.com/openshift-katacoda/rhoar-getting-started.git
      branch: solution
      sparseCheckoutDir: spring/spring-db-access
```

When the project gets checked out, the UI and the tooling (running `git branch`) shows `master`, yet the source code thats checked out reflects the correct branch (the `solution` branch in my specific case).

![Screen Shot 2021-07-20 at 11 53 25 AM](https://user-images.githubusercontent.com/363447/126364775-b546006a-53d4-4b25-b732-25cba6dfbf49.png)
