### ISSUE TITLE
[STEP3] user's namespace provisioning 

### ISSUE THREAD

**Issue by skabashnyuk** [eclipse-che/che#20168]
### Is your task related to a problem? Please describe.

Che server is able to use its configuration to set various settings on the workspace pod and/or user's namespace. We should think about supporting them on the DevWorkspaces, too:

- [x] custom certificates eclipse-che/che-operator#1027
- [x] proxy settings eclipse-che/che-operator#1027
- [x] https://github.com/eclipse/che/issues/20534
- [x] https://github.com/devfile/devworkspace-operator/issues/615
- [x] https://github.com/eclipse/che/issues/20528 (che-platform)
- [x] https://github.com/devfile/devworkspace-operator/issues/613 (controller)
- [x] https://github.com/eclipse/che/issues/20832
- [x] https://github.com/eclipse/che/issues/20884 (che-platform)
- [x]  https://github.com/devfile/devworkspace-operator/issues/614

### Describe the solution you'd like
1. Create new custom resource CheUser like 

 ```
apiVersion: org.eclipse.che/v1beta1
kind: CheUser
metadata:
  name: username
spec:
   id: 238409230-2349023049-24509i
   firstName: John
   lastName: Doe
   profile:
     attributes:
        a1:v1

```
2. On CheUser creation/update run k8s namespace reconcile loop that will create k8s secret with custom certificates
```
apiVersion: v1
kind: Secret
metadata:
  name: ca-crt-secret
  labels:
    controller.devfile.io/mount-to-devworkspace: "true"
  annotations:
    controller.devfile.io/mount-path: '/tmp/che/secret/'
data:
  ca.crt: <base64 encoded data content here>
```
3. Create secret with proxy settings
```
apiVersion: v1
  kind: Secret
metadata:
  name: env-var-secret
  labels:
    controller.devfile.io/mount-to-devworkspace: "true"
  annotations:
    controller.devfile.io/mount-as: env
data:
  https_proxy: value
  http_proxy: value
  no_proxy: value
```

### Describe alternatives you've considered
All the settings that would be in the `CheUser` instance can also be placed in variously labeled config maps and secrets and the user information can be drawn from OpenShift's User object or, hopefully, from the user info of the OIDC provider of Kubernetes.

### Additional context
-  https://github.com/devfile/devworkspace-operator/pull/417
 - https://github.com/eclipse-che/che-server/blob/main/infrastructures/kubernetes/src/main/java/org/eclipse/che/workspace/infrastructure/kubernetes/provision/ProxySettingsProvisioner.java
 - https://github.com/eclipse-che/che-server/blob/main/infrastructures/kubernetes/src/main/java/org/eclipse/che/workspace/infrastructure/kubernetes/provision/CertificateProvisioner.java
 - https://www.eclipse.org/che/docs/che-7/end-user-guide/mounting-a-secret-as-a-file-or-an-environment-variable-into-a-workspace-container/#mounting-a-secret-as-a-file-into-a-workspace-container_che
