### ISSUE TITLE
Create CheUser CR when pre-creating k8s namespace

### ISSUE THREAD

**Issue by skabashnyuk** [eclipse-che/che#20169]
### Is your task related to a problem? Please describe.
Trigger k8s namespace provisioning from rest method https://github.com/eclipse/che/issues/20165.

### Describe the solution you'd like

Create CheUser CR https://github.com/eclipse/che/issues/20168 when pre-creating k8s namespace https://github.com/eclipse/che/issues/20165.

 ```yaml
apiVersion: org.eclipse.che/v1beta1
kind: CheUser
metadata:
  name: username
spec:
   id: 238409230-2349023049-24509i
   firstName: John
   lastName: Doe
   profile:
     attributes:
        a1:v1

```
