### ISSUE TITLE
Projects should not be added to workspace if it specified a workspace config file `my-custom.theia-workspace`

### ISSUE THREAD

**Issue by zWingz** [eclipse-che/che#20196]
### Describe the bug
If I create a workspace config file named `my-custom.theia-workspace`
```json
{
   "folders": [
      {
         "path": "a"
      },
      {
         "path": "b"
      },
   ]
}
```

and workspace's devfile is
```yaml
# ...
projects:
  - name: project-from-devfile
    source:
      startPoint: master
      location: 'git@git.xxxx.xxxx/test-xxx.git'
      type: git
```

So, when I open my custom workspace by `Open Workspace Root` command
And the new workspace should only have folder with `a` and `b`, but actually It will add the folder `project-from-devfile` to my custom workspace

**Expect**
```
|- a
|- b
```

**Actually**
```
|-a
|-b
|-project-from-devfile
```

I think it is because the [workspace-plugin](https://github.com/eclipse-che/che-theia/blob/main/plugins/workspace-plugin/src/workspace-projects-manager.ts#L51-L73) add the project to current workspace even if it have a custom workspace config

### Che version

 - [x] 7.31.2

### Steps to reproduce

- create a folder named `a` and `b` in `/projects`
- create a custom workspace config
  ```
  {
     "folders": [
        {
           "path": "a"
        },
        {
           "path": "b"
        },
     ]
  }
  ```
- press `F1` and select `Open Workspace Root`
- open the custom workspace
