### ISSUE TITLE
Bitbucket factory repo fails for public repo without bitbucket OAuth

### ISSUE THREAD

**Issue by skabashnyuk** [eclipse-che/che#20195]
### Describe the bug
Bitbucket factory repo fails for public repo without bitbucket OAuth
https://issues.redhat.com/browse/CRW-2094

### Che version

 - [x] latest
 - [ ] nightly
 - [ ] other: please specify

### Steps to reproduce
1. Setup CheCluster with public Bitbucket only
```
    customCheProperties:
      CHE_INFRA_KUBERNETES_WORKSPACE_START_TIMEOUT_MIN: '10'
      CHE_INFRA_KUBERNETES_WORKSPACE__UNRECOVERABLE__EVENTS: 'Failed Scheduling,Failed to pull image'
      CHE_INTEGRATION_BITBUCKET_SERVER__ENDPOINTS: 'https://bitbucket-bitbucket.apps.ocp47-aws.crw-qe.com/'
      CHE_LIMITS_USER_WORKSPACES_RUN_COUNT: '-1'
      CHE_LIMITS_WORKSPACE_IDLE_TIMEOUT: '900001'
      CHE_LOGGER_CONFIG: org.eclipse.che.api.factory.server=DEBUG
    externalDevfileRegistry: false
```
2. Test factory with git repo from this SCM server.

### Expected behavior
Factory should work

### Runtime
   - [ ] kubernetes (include output of `kubectl version`)
   - [X] Openshift (include output of `oc version`)
   - [ ] minikube (include output of `minikube version` and `kubectl version`)
   - [ ] minishift (include output of `minishift version` and `oc version`)
   - [ ] docker-desktop + K8S (include output of `docker version` and `kubectl version`)
   - [ ] other: (please specify)

### Installation method
   - [ ] chectl
     * provide a full command that was used to deploy Eclipse Che (including the output)
     * provide an output of `chectl version` command
   - [ ] OperatorHub
   - [ ] I don't know

### Environment
   - [ ] my computer
       - [ ] Windows
       - [ ] Linux
       - [ ] macOS
   - [ ] Cloud
       - [ ] Amazon
       - [ ] Azure
       - [ ] GCE
       - [ ] other (please specify)
   - [ ] Dev Sandbox (workspaces.openshift.com)
   - [ ] other: please specify
