### ISSUE TITLE
[devworkspace-che-operator] Prototype and plan of controller that is reconciling resources in user's namespace

### ISSUE THREAD

**Issue by skabashnyuk** [eclipse-che/che#20219]
### Is your task related to a problem? Please describe.
The goal of this task is to have **Prototype and plan** version of https://github.com/eclipse/che/issues/20168

### Describe the solution you'd like
We need to understand what will be a trigger to start. It could be 
1. New CR, for Example, CheUser
2. Namespace create/update/delete with proper labels.

If we decide to go in the direction of 1. we need to define a model of this CustomeResource.
Here https://github.com/eclipse/che/issues/20168 we want to reconcile certs and secretes, however
for the prototype I  think we can choose one. What is easier.

```yaml
apiVersion: org.eclipse.che/v1beta1
kind: CheUser
metadata:
 name: username
spec:
  id: 238409230-2349023049-24509i
  firstName: John
  lastName: Doe
  profile:
    attributes:
       a1:v1
````

 - Q1. What if the user changes the username/id?

### Describe alternatives you've considered
Trigger on Namespace create/update/delete with proper labels.
### Additional context
https://github.com/eclipse/che/issues/20164
