### ISSUE TITLE
 How to modify the default cheEditor id

### ISSUE THREAD

**Issue by zWingz** [eclipse-che/che#20245]
## Summary

![image](https://user-images.githubusercontent.com/13031838/128111766-64b04b19-3c16-4416-b970-c16aaa252978.png)

But I can't find any code about `theia` in [che-machine-exec](https://github.com/eclipse-che/che-machine-exec)

**Comment by mmorhun** [comment]
Hello @zWingz.
You can take a look at docs [here](https://www.eclipse.org/che/docs/che-7/end-user-guide/customizing-developer-environments/) or look at devfile spec [here](https://www.eclipse.org/che/docs/che-7/end-user-guide/authoring-devfiles-version-1/#_component_type_cheeditor).
Also [this example](https://github.com/che-incubator/custom-native-editor-base-image) might be useful as well. It uses VNC, but actually you don't have to. It could be any server (as Che Theia, web terminal, projector, etc.).

**Comment by zWingz** [comment]
When devfile miss `cheEditor`, che-server will use `eclipse/che-theia/next` as the default editor.
I want to modify all default editor to `my/che-theia/id`, not by devfile

**Comment by mmorhun** [comment]
To do that you have to modify two properties:
- `che.workspace.devfile.default_editor`
- `che.factory.default_editor`

To do so on existing installation, you have to edit `checluster` custom resource (the diff):
```yaml
spec:
  server:
    customCheProperties:
      CHE_WORKSPACE_DEVFILE_DEFAULT__EDITOR: "eclipse/che-theia/next"
      CHE_FACTORY_DEFAULT__EDITOR: "eclipse/che-theia/next"
```
