### ISSUE TITLE
[Query]Error issuing ACME challenge on Eclipse che Azure AKS deployment

### ISSUE THREAD

**Issue by brootware** [eclipse-che/che#20264]
### Summary

Hi folks, as mentioned in the title I am running into an error while trying to create a certificate request following the example from the [che installation on AKS](https://www.eclipse.org/che/docs/che-7/installation-guide/installing-che-on-microsoft-azure/#installing-cert-manager-on-azure_che).

### Relevant information

Below is the status of certificate issuance.
```
kubectl describe certificate/che-tls -n eclipse-che
Status:
  Conditions:
    Last Transition Time:  2021-08-05T07:20:07Z
    Message:               Waiting for CertificateRequest "che-tls-1653251112" to complete
    Reason:                InProgress
    Status:                False
    Type:                  Ready
Events:
  Type    Reason        Age   From          Message
  ----    ------        ----  ----          -------
  Normal  GeneratedKey  31m   cert-manager  Generated a new private key
  Normal  Requested     31m   cert-manager  Created new CertificateRequest resource "che-tls-1653251112"
```

I double-checked the logs and found out that the **clientSecretSecretRef key** from ClusterIssuer definition file is not found in the Certificate as per the log below.

```
E0805 07:41:15.995935       1 controller.go:143] cert-manager/controller/challenges 
"msg"="re-queuing item  due to error processing" 
"error"="error getting azure dns client secret: key 'KEY-SANITIZED' not found in secret" 
"key"="eclipse-che/che-tls-1653251112-776589142-45289757" 
```

This is the ClusterIssuer definition file.
```
cat <<EOF | kubectl apply -f -
apiVersion: cert-manager.io/v1alpha2
kind: ClusterIssuer
metadata:
  name: che-certificate-issuer
spec:
  acme:
    solvers:
    - dns01:
        azuredns:
          # Service principal clientId (It's the value printed in the previous lines: echo ID=$AZURE_CERT_MANAGER_SP_APP_ID )
          clientID: ID-SANITIZED
          # A secretKeyRef to a service principal ClientSecret (password)
          # ref: https://docs.microsoft.com/en-us/azure/container-service/kubernetes/container-service-kubernetes-service-principal
          clientSecretSecretRef:
            name: azuredns-config
            # CLIENT_SECRET is the value of AZURE_CERT_MANAGER_SP_PASSWORD
            key: KEY-SANITIZED
          # Azure subscription Id that can be obtained with command:
          # $ az account show  | jq -r '.id'
          subscriptionID: SUBID
          # Azure AD tenant Id that can be obtained with command:
          # $ az account show  | jq -r '.tenantId'
          tenantID: TENANTID
          resourceGroupName: eclipseCheResourceGroup
          # The DNS Zone to use
          hostedZoneName: dns.cloud
    email: EMAIL-SANITIZED
    privateKeySecretRef:
      name: letsencrypt
    server: https://acme-v02.api.letsencrypt.org/directory
EOF
```
Below is the Certificate definition file.
```
cat <<EOF | kubectl apply -f -
apiVersion: cert-manager.io/v1alpha2
kind: Certificate
metadata:
 name: che-tls
 namespace: eclipse-che
spec:
 secretName: che-tls
 issuerRef:
   name: che-certificate-issuer
   kind: ClusterIssuer
 dnsNames:
   - '*.dns.cloud'
EOF
```
As you can see the Certificate definition file is properly referencing to the ClusterIssuer definition file through this piece of code:
```
spec:
 secretName: che-tls
 issuerRef:
   name: che-certificate-issuer
   kind: ClusterIssuer
```

So I'm stuck here and how can I go about fixing this?
