### ISSUE TITLE
Provide alternative way for user to setup image pull secrets

### ISSUE THREAD

**Issue by skabashnyuk** [eclipse-che/che#20310]
### Is your task related to a problem? Please describe

At this moment there is a way to set up mage pull secrets from user's preferences.
This data is stored in DB in the opened way. We should provide a new mechanism based on K8s secrets to provide such data.

### Describe the solution you'd like

```yaml
apiVersion: v1
kind: Secret
type: kubernetes.io/dockerconfigjson
metadata:
  name: workspace-image-pull-secret
  labels:
    app.kubernetes.io/part-of: che.eclipse.org
    app.kubernetes.io/component: image-pull-secret
data:
  .dockerconfigjson
```

Content something like that 
```json
{
    "auths": {
        "https://index.docker.io/v1/": {
            "auth": "c3R...zE2"
        }
    }
}
```

### Additional context

 - https://github.com/moby/moby/blob/v1.6.0/registry/auth.go#L37
 - https://github.com/eclipse-che/che-server/blob/main/infrastructures/kubernetes/src/main/java/org/eclipse/che/workspace/infrastructure/kubernetes/provision/ImagePullSecretProvisioner.java
- https://kubernetes.io/docs/tasks/configure-pod-container/pull-image-private-registry/
- https://github.com/eclipse/che/issues/19809
