### ISSUE TITLE
Align che-theia with upstream changes

### ISSUE THREAD

**Issue by vitaliy-guliy** [eclipse-che/che#20366]
### Describe the bug

It seems the [commit to the upstream](https://github.com/eclipse-theia/theia/commit/5e5b0157fdd26ae317d8f2490a08372ea8be553a) broke che-theia.

che-theia image can be built successfully (no any issues, as tests are turned off), but the container fails with the following output
```
TypeError: Class constructor MessagingContribution cannot be invoked without 'new'
    at new CheMessagingContribution (/home/theia/node_modules/@eclipse-che/theia-messaging/lib/node/messaging/che-messaging-contribution.js:78:47)
    at _createInstance (/home/theia/node_modules/inversify/lib/resolution/instantiation.js:27:12)
    at Object.resolveInstance (/home/theia/node_modules/inversify/lib/resolution/instantiation.js:47:18)
    at /home/theia/node_modules/inversify/lib/resolution/resolver.js:75:42
    at Object.resolve (/home/theia/node_modules/inversify/lib/resolution/resolver.js:99:12)
    at /home/theia/node_modules/inversify/lib/container/container.js:335:37
    at Container._get (/home/theia/node_modules/inversify/lib/container/container.js:326:44)
    at Container.get (/home/theia/node_modules/inversify/lib/container/container.js:243:21)
    at Binding.dynamicValue (/home/theia/node_modules/inversify/lib/syntax/binding_to_syntax.js:76:75)
    at /home/theia/node_modules/inversify/lib/resolution/resolver.js:66:118
Theia app listening on http://127.0.0.1:3100.
```

### Che version

next (development version)

### Steps to reproduce

a) Since build of [`eclipse/che-theia:next`](https://quay.io/repository/eclipse/che-theia?tag=latest&tab=tags) is broken (the image must be published on each change), it needs to build the image by hands.

1. clone che-theia, build the image
```
./build.sh --build-args:GITHUB_TOKEN=${GITHUB_TOKEN} --skip-tests --dockerfile:Dockerfile.alpine
```

2. then use this image when creating a workspace

b) Create a workspace using the devfile
```
apiVersion: 1.0.0
metadata:
  name: che-theia-next
projects:
  - name: web-java-spring-petclinic
    source:
      location: 'https://github.com/che-samples/java-spring-petclinic'
      type: git
components:
  - type: cheEditor
    alias: che-theia
    reference: https://gist.githubusercontent.com/vitaliy-guliy/2bb6318a84a2911e334cba6d7dfbf423/raw/b52df74920ace02d0c11d35c01bc621eadb5d3bd/editor.meta.yaml
```

### Expected behavior

Working editor.

### Runtime

OpenShift, minikube

### Screenshots

![Screenshot from 2021-08-26 17-51-49](https://user-images.githubusercontent.com/1655894/130988287-55cd2b67-01bc-4702-b435-25d61a28a491.png)

![Screenshot from 2021-08-26 17-51-55](https://user-images.githubusercontent.com/1655894/130988301-d89f75c5-6e57-4d80-a9bd-35cbd0a7bef8.png)

### Installation method

chectl/next

### Environment

Linux, Dev Sandbox (workspaces.openshift.com)

### Additional context

To build che-theia use `eclipse-che/che-theia/main` and `eclipse-theia/theia/master`
