### ISSUE TITLE
che-theia fails with `redhat/java8/latest` plugin

### ISSUE THREAD

**Issue by vitaliy-guliy** [eclipse-che/che#20360]
### Describe the bug

It's impossible to properly start a workspace if there is `redhat/java8/latest` plugin in the devfile.
The bug is reproducible only if build che-theia, based on `eclipse-theia/theia/master`.

The problem does not depend on the infrastructure and the installation method.

### Che version

latest

### Steps to reproduce

- Build che-theia image

1. build che-theia:next image, using `eclipse-che/che-theia/main` and `eclipse-theia/theia/master`
2. create a minimal devfile, use built che-theia and latest `redhat/java8` plugin.
3. start a workspace, open browser console, check errors

You will not be able to see `My Workspace` and other views, that contributed by plugins. The most of plugins at this point are not properly started.

- Do not build anything, just run prepared devfile

```
apiVersion: 1.0.0
metadata:
  name: minimal-workspace
projects:
  - name: web-java-spring-petclinic
    source:
      location: 'https://github.com/che-samples/java-spring-petclinic'
      type: git
components:
  - type: cheEditor
    alias: che-theia
    reference: https://gist.githubusercontent.com/vitaliy-guliy/261c8e37493c20d6504701c537a146e0/raw/24606999f923183f992f34d6617f570dd7e0858c/editor.meta.yaml
  - id: redhat/java8/latest
    type: chePlugin
```

### Expected behavior

Plugin system must be working.

### Runtime

other (please specify in additional context)

### Screenshots

![Screenshot from 2021-08-25 19-38-53](https://user-images.githubusercontent.com/1655894/130836623-4a1be18b-37b7-4217-bb95-2ab9e03ba67e.png)

There are few unexpected errors, which could be reason of failure
![Screenshot from 2021-08-25 20-32-29](https://user-images.githubusercontent.com/1655894/130838173-aa14325c-5dc4-4dce-a49f-5593a31b8f5b.png)

![Screenshot from 2021-08-25 20-32-35](https://user-images.githubusercontent.com/1655894/130838192-0e1577e6-04ba-46c1-bc7b-130021ec55d1.png)

There is a similar error on che-theia backend
![Screenshot from 2021-08-25 20-45-00](https://user-images.githubusercontent.com/1655894/130839950-d64cc4cd-544a-4eb3-b365-2e0574a49383.png)

### Installation method

other (please specify in additional context)

### Environment

Dev Sandbox (workspaces.openshift.com), other (please specify in additional context)
