### ISSUE TITLE
Latest Che-theia editor image fails to start

### ISSUE THREAD

**Issue by vinokurig** [eclipse-che/che#20376]
### Describe the bug

Cannot start a workspce with che-theia image built from latest main branch

### Che version

next (development version)

### Steps to reproduce

1. Build a che-theia image from the latest main branch, see https://github.com/eclipse-che/che-theia/blob/b9575b3d7e2f618f9e6f0a992ede7070ed6ac0bc/dockerfiles/theia/README.md
and push it to docker registry
2. Post a devfile with the built image:
```
apiVersion: v2
publisher: eclipse
name: che-theia
version: next
type: Che Editor
displayName: theia-ide
title: Eclipse Theia development version.
description: 'Eclipse Theia, get the latest release each day.'
icon: /images/default.png
category: Editor
repository: 'https://github.com/eclipse-che/che-theia'
firstPublicationDate: '2019-03-07'
latestUpdateDate: '2021-08-18'
spec:
  endpoints:
    - name: theia
      targetPort: 3100
      attributes:
        type: ide
        cookiesAuthEnabled: true
        discoverable: false
        urlRewriteSupported: true
        protocol: http
        secure: true
      public: true
    - name: webviews
      targetPort: 3100
      attributes:
        type: webview
        cookiesAuthEnabled: true
        discoverable: false
        unique: true
        urlRewriteSupported: true
        protocol: http
        secure: true
      public: true
    - name: mini-browser
      targetPort: 3100
      attributes:
        type: mini-browser
        cookiesAuthEnabled: true
        discoverable: false
        unique: true
        urlRewriteSupported: true
        protocol: http
        secure: true
      public: true
    - name: theia-dev
      targetPort: 3130
      attributes:
        type: ide-dev
        discoverable: false
        urlRewriteSupported: true
        protocol: http
      public: true
    - name: theia-redirect-1
      targetPort: 13131
      attributes:
        discoverable: false
        urlRewriteSupported: true
        protocol: http
      public: true
    - name: theia-redirect-2
      targetPort: 13132
      attributes:
        discoverable: false
        urlRewriteSupported: true
        protocol: http
      public: true
    - name: theia-redirect-3
      targetPort: 13133
      attributes:
        discoverable: false
        urlRewriteSupported: true
        protocol: http
      public: true
    - name: terminal
      targetPort: 3333
      attributes:
        type: collocated-terminal
        discoverable: false
        cookiesAuthEnabled: true
        urlRewriteSupported: true
        protocol: ws
        secure: true
      public: true
  containers:
    - image: '<reference to the docker image>'
      env:
        - name: THEIA_PLUGINS
          value: 'local-dir:///plugins'
        - name: HOSTED_PLUGIN_HOSTNAME
          value: 0.0.0.0
        - name: HOSTED_PLUGIN_PORT
          value: '3130'
        - name: THEIA_HOST
          value: 127.0.0.1
      mountSources: true
      memoryLimit: 512M
      cpuLimit: 1500m
      cpuRequest: 100m
      volumes:
        - name: plugins
          mountPath: /plugins
        - name: theia-local
          mountPath: /home/theia/.theia
      name: theia-ide
      ports:
        - exposedPort: 3100
        - exposedPort: 3130
        - exposedPort: 13131
        - exposedPort: 13132
        - exposedPort: 13133
    - image: 'quay.io/eclipse/che-machine-exec:next'
      memoryLimit: 128Mi
      memoryRequest: 32Mi
      cpuLimit: 500m
      cpuRequest: 30m
      command:
        - /go/bin/che-machine-exec
        - '--url'
        - '127.0.0.1:3333'
      name: che-machine-exec
      ports:
        - exposedPort: 3333
  initContainers:
    - image: 'quay.io/eclipse/che-theia-endpoint-runtime-binary:next'
      memoryLimit: 128Mi
      memoryRequest: 32Mi
      cpuLimit: 500m
      cpuRequest: 30m
      env:
        - name: PLUGIN_REMOTE_ENDPOINT_EXECUTABLE
          value: /remote-endpoint/plugin-remote-endpoint
        - name: REMOTE_ENDPOINT_VOLUME_NAME
          value: remote-endpoint
      volumes:
        - name: remote-endpoint
          mountPath: /remote-endpoint
          ephemeral: true
      name: remote-runtime-injector
``` 
3. Start a workspace from devfile:
```
apiVersion: 1.0.0
metadata:
  name: wksp-po0rm
components:
  - type: cheEditor
    reference: '<reference to the devfile>'
```

See: an error appears:
`Failed to run the workspace: "Server 'theia' in container 'theia-idewu0' not available."`
Container logs:
```
TypeError: Class constructor MessagingContribution cannot be invoked without 'new'
    at new CheMessagingContribution (/home/theia/node_modules/@eclipse-che/theia-messaging/lib/node/messaging/che-messaging-contribution.js:78:47)
    at _createInstance (/home/theia/node_modules/inversify/lib/resolution/instantiation.js:27:12)
    at Object.resolveInstance (/home/theia/node_modules/inversify/lib/resolution/instantiation.js:47:18)
    at /home/theia/node_modules/inversify/lib/resolution/resolver.js:75:42
    at Object.resolve (/home/theia/node_modules/inversify/lib/resolution/resolver.js:99:12)
    at /home/theia/node_modules/inversify/lib/container/container.js:335:37
    at Container._get (/home/theia/node_modules/inversify/lib/container/container.js:326:44)
    at Container.get (/home/theia/node_modules/inversify/lib/container/container.js:243:21)
    at Binding.dynamicValue (/home/theia/node_modules/inversify/lib/syntax/binding_to_syntax.js:76:75)
    at /home/theia/node_modules/inversify/lib/resolution/resolver.js:66:118
Theia app listening on http://127.0.0.1:3100.
```

### Expected behavior

Workspace starts

### Runtime

minikube

### Installation method

chectl/next

### Environment

macOS
