### ISSUE TITLE
DevWorkspaces on minikube does not work due some routing issues

### ISSUE THREAD

**Issue by sleshchenko** [eclipse-che/che#20375]
### Describe the bug

DevWorkspaces on minikube does not work due some routing issues.
Workspace URL is redirected to dashboard.

### Che version

next (development version)

### Steps to reproduce

1. Deploy Che on minikube with next chectl:
```bash
chectl server:deploy --installer=operator --platform=minikube --che-operator-cr-patch-yaml=/home/sleshche/che-custom-che-server.yaml --workspace-engine=dev-workspace
```
where patch file has the following content
```yaml
spec:
  devWorkspace:
    enable: true
  server:
    customCheProperties:
      CHE_INFRA_KUBERNETES_ENABLE__UNSUPPORTED__K8S: "true"
```
2. When Dashboard is opened, create a workspace with Sample and wait it started.
3. Check that Dashboard is opened instead of Theia IDE.

4. Switch single host impl to gateway by adding `spec.k8s.singleHostExposureType: gateway` into Che Cluster, wait Che is reconfigured.
5. Try a new workspace or restart the existing one.
6. Check that Theia is not opened.

### Expected behavior

Theia is opened after workspace is started.

### Runtime

minikube

### Screenshots

![Screenshot_20210830_110738](https://user-images.githubusercontent.com/5887312/131307528-62dac37e-d72b-495f-bca8-ff31c365ae89.png)

### Installation method

chectl/next

### Environment

Linux
