### ISSUE TITLE
vscode-xml/0.16.1 plugin does not work due to infinity initializing

### ISSUE THREAD

**Issue by vitaliy-guliy** [eclipse-che/che#20382]
### Describe the bug

`vscode-xml/0.16.1` become not working anymore. It is running in the dedicated sidecar, and depends on `vscode-commons`, which is running in the same container with `che-theia`.

The problem appeared after switching to node v12. 

There is a known issue, that plugins cannot communicate properly if they are running in different containers https://github.com/eclipse/che/issues/19686.

In fact, all the plugins, that are running in the separate container and depend on another plugin/extension have the same problem.

### Che version

next (development version)

### Steps to reproduce

1. Create a workspace from the devfile
```
apiVersion: 1.0.0
metadata:
  name: vscode-xml-test
projects:
  - name: nodejs-web-app
    source:
      location: 'https://github.com/che-samples/web-nodejs-sample.git'
      type: git
      branch: xml-scheme-test
components:
  - id: redhat/vscode-xml/latest
    type: chePlugin
  - id: redhat/vscode-commons/latest
    type: chePlugin
```

2. Open `hello.xml` file
3. Check for `Activating XML` item in the status bar. With `vscode-xml/0.16.1` it will never dissappear.

### Expected behavior

Status bar item must disappear, `ctrl+space` must display items from XML language server.

### Runtime

minikube

### Screenshots

![infinity-activating-xml-transparent](https://user-images.githubusercontent.com/1655894/131483499-bd5d0468-899c-480e-bdfb-6c677a9d9380.png)

### Installation method

chectl/next

### Environment

Linux
