### ISSUE TITLE
Set resources requests and limits for workspace initialization containers

### ISSUE THREAD

**Issue by disaster37** [eclipse-che/che#20381]
### Describe the bug

Our namespace user have quota, so we need specify resources (cpu, memory) when we start pods.
In section `server`, we have added:
```
  customCheProperties:
     CHE_WORKSPACE_DEFAULT__CPU__LIMIT__CORES: '1'
      CHE_WORKSPACE_DEFAULT__CPU__REQUEST__CORES: '300m'
      CHE_WORKSPACE_SIDECAR_DEFAULT__CPU__LIMIT__CORES: '300m'
      CHE_WORKSPACE_SIDECAR_DEFAULT__CPU__REQUEST__CORES: '50m'
```

After lauch workspace, it failed because of to pods have no resources specified:
  - **remote-runtime-injector**: no memory and no cpu resources (request and limit)
  - **che-plugin-artifacts-broker**: no cpu resource (request and limit)

### Che version

other (please specify in additional context)

### Steps to reproduce

1. Deploy Eclpise che 7.35.1 with chectl and add the following options:

```
spec:
  k8s:
    server:
      customCheProperties:
        CHE_WORKSPACE_DEFAULT__CPU__LIMIT__CORES: '1'
        CHE_WORKSPACE_DEFAULT__CPU__REQUEST__CORES: '300m'
        CHE_WORKSPACE_SIDECAR_DEFAULT__CPU__LIMIT__CORES: '300m'
        CHE_WORKSPACE_SIDECAR_DEFAULT__CPU__REQUEST__CORES: '50m'
```
2. Create user namespace with quota and without default container quota.
3. Start workspace.

### Expected behavior

We expect that is run workspace, ans we expect that the internal pod as juste the required ressource setted like is already the case for ``che-machine-exec`, theia-ide`, etc.

### Runtime

Kubernetes (vanilla)

### Installation method

chectl/latest

### Environment

Linux

### Release Notes Text

Plugin artifact broker and remote runtime injector are containers created during workspace initialization. Those containers failed to run in clusters where CPU and memory request had to be specified for every container. Che sever has been updated to specifies CPU and memory request and limits for every container it starts. Values are configurable.

**Comment by skabashnyuk** [comment]
@disaster37 can you provide more details in steps to reproduce? Especially in desired behavior and what you got.

**Comment by disaster37** [comment]
We deploy Eclipse on this way:

```
chectl server:deploy --installer=operator --domain=che.domain.local --multiuser --chenamespace=che --cheboottimeout=600000 --platform=k8s --che-operator-cr-patch-yaml=che-operator-cr-patch.yaml --skip-kubernetes-health-check
```

With `che-operator-cr-patch.yaml`:
```yaml
spec:
  k8s:
    singleHostExposureType: 'gateway'
    tlsSecretName: 'che-tls-certificates'
  metrics:
    enable: true
  server:
    serverExposureStrategy: 'single-host'
    useInternalClusterSVCNames: true
    workspaceNamespaceDefault: 'che-<username>'
    customCheProperties:
      CHE_LIMITS_USER_WORKSPACES_COUNT: "-1"
      CHE_LIMITS_USER_WORKSPACES_RUN_COUNT: "3"
      CHE_LIMITS_WORKSPACE_IDLE_TIMEOUT: "43200000"
      CHE_INFRA_KUBERNETES_NAMESPACE_ANNOTATIONS: 'che.eclipse.org/username=<username>,field.cattle.io/projectId=c-57d7n:p-8j45h'
      CHE_INFRA_KUBERNETES_NAMESPACE_LABELS: 'app.kubernetes.io/part-of=che.eclipse.org,app.kubernetes.io/component=workspaces-namespace,field.cattle.io/projectId=p-8j45h'
      CHE_WORKSPACE_DEFAULT__CPU__LIMIT__CORES: '1'
      CHE_WORKSPACE_DEFAULT__CPU__REQUEST__CORES: '500m'
      CHE_WORKSPACE_SIDECAR_DEFAULT__CPU__LIMIT__CORES: '300m'
      CHE_WORKSPACE_SIDECAR_DEFAULT__CPU__REQUEST__CORES: '50m'
  storage:
    pvcClaimSize: 4Gi
    pvcStrategy: per-workspace
```

Create namespace `che-admin` and add resource quota on it:
```yaml
apiVersion: v1
kind: ResourceQuota
metadata:
  name: quota
  namespace: che-admin
spec:
  hard:
    limits.cpu: "10"
    limits.memory: 8Gi
    requests.storage: 30Gi
```

Loggon on che with admin account and lauch workspace.

On rancher2, we set project/namespace with resource quota. So all container that run  must have resources specified, aka
```yaml
resource:
  request:
    cpu: 100m
    memory: 256Mi
  limit:
    cpu: 300m
    memory: 512Mi
```

The problem appear when we run workspace because of some che internal pod doesn't have resources specified. So it failed:

```
Unrecoverable event occurred: 'FailedCreate', 'Error creating: pods "workspace4lwyzglr3jftam0r.cli-8598877dcc-7vwnx" is forbidden: failed quota: default-44qk2: must specify limits.cpu,limits.memory', 'workspace4lwyzglr3jftam0r.cli-8598877dcc'
```

After some check, to fix that, you need to add the following ressources on the following pods that is launched with workspace:
  - pod `remote-runtime-injector-xxx`:
```yaml
resource:
  request:
    cpu: 100m
    memory: 256Mi
  limit:
    cpu: 300m
    memory: 512Mi
```
  - pod `che-plugin-artifacts-broker-xxx`:
```yaml
resource:
  request:
    cpu: 100m
  limit:
    cpu: 300m
```
> Memory limit is already setted


The previous resources values is just for sample purpose. I doesn't know the right resources needed by this pods ... Bu you need to specify them.
