### ISSUE TITLE
[testNG/junit] vscode-java-test extension opens an empty and not responding terminal

### ISSUE THREAD

**Issue by vitaliy-guliy** [eclipse-che/che#20410]
### Describe the bug

With `redhat/java/latest` plugin it is possible to run a separate `junit/testNG` test from the UI.
When java test file opened, the plugin adds `Run Test` and `Debug Test` controls under `@Test` annotation.

Clicking on `Run Test` must run a specific test and print the output to `Debug Console` view.

But something broken, clicking on `Run Test` opens an empty `Debug Console` and nothing happens.
With the following clicks Theia says: `A test session is currently running. Please wait until it finishes.`

-------

In fact, `redhat/java/latest` plugin runs three vscode extension in the dedicated sidecar.
```
  extensions:
    - 'https://download.jboss.org/jbosstools/static/jdt.ls/stable/java-0.75.0-60.vsix'
    - 'https://download.jboss.org/jbosstools/vscode/3rdparty/vscode-java-debug/vscode-java-debug-0.26.0.vsix'
    - 'https://open-vsx.org/api/vscjava/vscode-java-test/0.28.1/file/vscjava.vscode-java-test-0.28.1.vsix'
```

Extensions depends on each other, so the problem could be related to bug in cross-plugin communication https://github.com/eclipse/che/issues/19686

### Che version

next (development version)

### Steps to reproduce

1. Create a workspace from the devfile
```
apiVersion: 1.0.0
metadata:
  name: testng-example
projects:
  - name: testng-example
    source:
      location: 'https://github.com/vitaliy-guliy/testng-example.git'
      type: git
components:

  - id: redhat/java/latest
    preferences:
      java.server.launchMode: Standard
    type: chePlugin

  - mountSources: true
    endpoints:
      - attributes:
          public: 'false'
        name: debug
        port: 5005
    memoryLimit: 512Mi
    type: dockerimage
    volumes:
      - name: m2
        containerPath: /home/user/.m2
    alias: maven
    image: 'quay.io/eclipse/che-java11-maven:next'
    env:
      - value: ''
        name: MAVEN_CONFIG
      - value: '-XX:MaxRAMPercentage=50 -XX:+UseParallelGC -XX:MinHeapFreeRatio=10 -XX:MaxHeapFreeRatio=20 -XX:GCTimeRatio=4 -XX:AdaptiveSizePolicyWeight=90 -Dsun.zip.disableMemoryMapping=true -Xms20m -Djava.security.egd=file:/dev/./urandom -Duser.home=/home/user'
        name: MAVEN_OPTS
      - value: '-XX:MaxRAMPercentage=50 -XX:+UseParallelGC -XX:MinHeapFreeRatio=10 -XX:MaxHeapFreeRatio=20 -XX:GCTimeRatio=4 -XX:AdaptiveSizePolicyWeight=90 -Dsun.zip.disableMemoryMapping=true -Xms20m -Djava.security.egd=file:/dev/./urandom'
        name: JAVA_OPTS
      - value: '-XX:MaxRAMPercentage=50 -XX:+UseParallelGC -XX:MinHeapFreeRatio=10 -XX:MaxHeapFreeRatio=20 -XX:GCTimeRatio=4 -XX:AdaptiveSizePolicyWeight=90 -Dsun.zip.disableMemoryMapping=true -Xms20m -Djava.security.egd=file:/dev/./urandom'
        name: JAVA_TOOL_OPTIONS

commands:
  - name: maven build
    actions:
      - workdir: '${CHE_PROJECTS_ROOT}/testng-example'
        type: exec
        command: mvn clean install
        component: maven
```

2. Go to `My Workspace` view and run `maven build`
3. Open a test file and wait for jaba language server being initialized. `Run Test` and `Debug` test controls shoud appear under `@Test` annotation.
4. Click `Run Test`, wait for `Debug Console` view will be opened.
5. Open browser console and check for the error (first screenshot).
6. Refresh the browser, `Debug Console` view must be already opened.
7. Wait for language server being relaunched, click `Run Test` again.

Test must be launched properly, output should be printed to `Debug Console` view.
(second screenshot)

### Expected behavior

Running test with output to `Debug Console` on the first click at `Run Test` (as on second screenshot)

### Runtime

minikube

### Screenshots

![Screenshot from 2021-09-03 14-31-59](https://user-images.githubusercontent.com/1655894/132007387-17886c83-45ba-4cda-9e66-c50ecc9b8545.png)

![Screenshot from 2021-09-03 14-38-30](https://user-images.githubusercontent.com/1655894/132007434-646e67fa-b083-4cff-8098-e596c0d95f0a.png)

### Installation method

chectl/next

### Environment

Linux
