### ISSUE TITLE
Validate factory flow with devfile v2 from private repos

### ISSUE THREAD

**Issue by sleshchenko** [eclipse-che/che#20432]
### Is your enhancement related to a problem? Please describe
DevWorkspace Operator add an ability to to configure secret with personal access token which is used then for project clone component and can be mounted into containers
```
kind: Secret
apiVersion: v1
metadata:
  name: git-credentials-secret
  namespace: devworkspace-controller
  annotations:
    controller.devfile.io/mount-path: /home/theia/.git-credentials/
  labels:
    controller.devfile.io/git-credential: 'true'
data:
  credentials: >- ${your base64 credentials here}
type: Opaque
```
More see https://github.com/devfile/devworkspace-operator/pull/564.

P.S. The demo from DWO point of view https://www.youtube.com/watch?v=BamW5SxSGtE

### Describe the solution you'd like

It's needed to complete the story from Che integration point of view.
Che Server would need to apply needed labels/annotations to secrets it creates after OAuth flow to make it working on DWO side.

**Comment by skabashnyuk** [comment]
depends on https://github.com/eclipse/che/issues/20496 and https://github.com/eclipse/che/issues/20497

**Comment by skabashnyuk** [comment]
Now we are creating 

```
apiVersion: v1
kind: Secret
metadata:
  name: git-credentials-secret
  labels:
    app.kubernetes.io/part-of: che.eclipse.org
    app.kubernetes.io/component: workspace-secret
  annotations:
    che.eclipse.org/automount-workspace-secret: 'true'
    che.eclipse.org/mount-path: /home/theia/.git-credentials
    che.eclipse.org/mount-as: file
    che.eclipse.org/git-credential: 'true'
data:
  credentials: aHR0cHM6Ly91c2VyOnBhc3NAZXhhbXBsZS5jb20K
```
according to https://github.com/devfile/devworkspace-operator/pull/564
we nee to have it in format 
```
apiVersion: v1
metadata:
  name: git-credentials-secret
  namespace: devworkspace-controller
  annotations:
    controller.devfile.io/mount-path: /home/theia/.git-credentials/
  labels:
    controller.devfile.io/git-credential: 'true'
data:
  credentials: >- ${your base64 credentials here}
type: Opaque  
```
The data is identical so we need to add extra label `controller.devfile.io/git-credential: 'true' `and annotation ` controller.devfile.io/mount-path: /home/theia/.git-credentials/`  here https://github.com/eclipse-che/che-server/blob/ce6bcf2d198371db95d6722aabbba1f4c8cfff65/infrastructures/infrastructure-factory/src/main/java/org/eclipse/che/api/factory/server/scm/kubernetes/KubernetesGitCredentialManager.java#L120-L134
