### ISSUE TITLE
Change Title of Terminal created a developer container

### ISSUE THREAD

**Issue by pgirishibm** [eclipse-che/che#20447]
### Summary

I am creating  workspace using the below devfile.

```
apiVersion: 1.0.0
metadata:
  name: wksp-custom-6v3gs
attributes:
  persistVolumes: 'false'
components:
  - mountSources: true
    endpoints:
      - name: access-react-web-app
        port: 3001
    memoryLimit: 2Gi
    type: dockerimage
    image: 'quay.io/devplayground/che-nodejs-python:latest'
    alias: nodejs
  - id: redhat/vscode-didact/latest
    type: chePlugin
```

This creates the developer container names nodejs. I also get a command ID to create a terminal in this container. terminal-for-nodejs-container:new

When I use the menu option to create the terminal in the nodejs container , 

<img width="658" alt="image" src="https://user-images.githubusercontent.com/17478559/132690147-49caf520-f7ca-400e-9ad9-2132a9bdccf0.png">

<img width="604" alt="image" src="https://user-images.githubusercontent.com/17478559/132690109-1c59fcbe-928e-48b6-9a85-8565a966f914.png">

The terminal title shows as 'nodejs terminal 1'.    
<img width="307" alt="image" src="https://user-images.githubusercontent.com/17478559/132690371-b65783c6-3e53-4ebe-af0e-0bb958adb223.png">

Is there a way i can specify the title of the terminal that gets created in the nodejs container? 

In case of the theia terminal, I have a didact command didact.sendNamedTerminalAString&text="MyTerminal"  which will create a terminal in the theia container with the title 'MyTerminal', 

Any help specific to the terminal creation in the developer container ? 

If there is a way to achieve this by changing the che-theia code and creating a customized che-theia image please do suggest
