### ISSUE TITLE
Theia endpoint type attribute value: 'ide' or 'main'?

### ISSUE THREAD

**Issue by virtuakazib** [eclipse-che/che#20457]
### Summary

This question is in regards to Eclipse Che v7.36.0

There are some parts of che that check the value of an `type` attribute on the theia server within the workspace config.  Some code in che expects that value to be `main` and others expect it to be `ide`. Which is correct?

### Relevant information

The following information is based on Eclipse Che v7.36.0

I'm getting an error when trying to open a new terminal window with the theia terminal extension:
`Error: Failed to create terminal. Cause: Error: Only one endpoint should be of ide type.`

Looking at the the terminal extension code, the error is thrown while executing this [line](https://github.com/eclipse-che/che-theia/blob/7.36.0/extensions/eclipse-che-theia-terminal/src/browser/contribution/exec-terminal-contribution.ts#L213):
`const ideComponents = await this.endpointService.getEndpointsByType('main');`

But a log of my server attributes data looks like this (with a `type` value of `ide`):
```
"attributes":{
   "internal":"false",
   "port":"3100",
   "discoverable":"false",
   "cookiesAuthEnabled":"true",
   "secure":"true",
   "type":"ide",
   "endpointOrigin":"/"
}`
```

I double checked the [`che-editors.yaml`](https://github.com/eclipse-che/che-plugin-registry/blob/7.36.0/che-editors.yaml#L215) file in the plugin registry which includes a value of `main` for the relevant theia endpoint:
```
endpoints:
   - name: theia
      exposure: public
      secure: true
      targetPort: 3100
      attributes:
         type: main
         cookiesAuthEnabled: true
         discoverable: false
         urlRewriteSupported: true
      protocol: http
```

But the [`endpoints-helper.ts`](https://github.com/eclipse-che/che-plugin-registry/blob/7.36.0/tools/build/src/common/endpoints-helper.ts#L30) code in the plugin regsitry build process converts the value of 'main' into 'ide':
```
   if (attributes.type === 'main') {
      attributes.type = 'ide';
   }
```

Which is the correct value?  `main` or `ide`?  Or how do I get that type value to be `main` so that the terminal extension can open a new terminal?
