### ISSUE TITLE
Users should be able to configure their workspace pods securityContext capabilities

### ISSUE THREAD

**Issue by l0rd** [eclipse-che/che#20459]
### Is your enhancement related to a problem? Please describe

I would like to be able to build a Dockerfile using `buildah` from within a workspace as described [here](https://github.com/containers/buildah/blob/main/docs/tutorials/05-openshift-rootless-build.md). On OpenShift and using the DevWorkspace operator.

### Describe the solution you'd like

To be able to run buildah successfully the pod should use a ServiceAccount that has `anyuid` scc (`oc adm policy add-scc-to-user anyuid -z <my-service-account>`) and it should be possible to set containers SecurityContext capabilities.

```yaml
    spec:
      serviceAccount: buildah-sa
      containers:
        - name: buildah
          image: image-registry.openshift-image-registry.svc:5000/image-build/buildah
          securityContext:
            capabilities:
              drop:
                - KILL
```

### Additional context

That may be a user configuration specified in a `ConfigMap`: every workspace of the user would have the  `serviceAccount` and `securityContext` specified in the `ConfigMap`.
