### ISSUE TITLE
DevWorkspaces does not work on minikube with default native single host

### ISSUE THREAD

**Issue by sleshchenko** [eclipse-che/che#20454]
### Describe the bug

DevWorkspaces does not work on minikube with default native single host.

It works fine with 
```yaml
spec:
  k8s:
    singleHostExposureType: gateway
```
So, probably we must deprecate native single host with devworkspace workspace engine.

### Che version

next (development version)

### Steps to reproduce

1. chectl server:deploy --installer=operator --platform=minikube --che-operator-cr-patch-yaml=/home/sleshche/che-custom-che-server.yaml --workspace-engine=dev-workspace
where /home/sleshche/che-custom-che-server.yaml is
```yaml
spec:
  server:
    customCheProperties:
      CHE_INFRA_KUBERNETES_ENABLE__UNSUPPORTED__K8S: "true"

```
2. Try to start workspace.

### Expected behavior

Workspace is started and Theia is opened.

### Runtime

Kubernetes (vanilla), minikube

### Screenshots

![Screenshot_20210910_144224](https://user-images.githubusercontent.com/5887312/132848968-a3b33a27-93d8-4bc2-bf01-3aae7905f297.png)

### Installation method

chectl/next

### Environment

Linux
