### ISSUE TITLE
It should be easier to configure remotes in Devfile v2 flow

### ISSUE THREAD

**Issue by amisevsk** [eclipse-che/che#21315]
### Is your enhancement related to a problem? Please describe

By default, I set up repos I work in with remotes
```yaml
  upstream: <the main repo -- e.g. github.com/eclipse/che>
  origin: <my fork of the repo -- e.g. github.com/amisevsk/che>
```
However, with the devfile v2 flow, only one repo can be specified and the devfile from that repo is used for the workspace. This can lead to issues if a fork is out of date, and requires adding remotes manually after the fact.

### Describe the solution you'd like

Ideally it would be possible to specify a full list of remotes that the workspace should use. If not that, specifying (or automatically detecting) a fork + upstream set of remotes would be very useful

When cloning a new repo for the first time, I would like it to be configured so that
1. The upstream remote is cloned, in order to pull the latest changes from `main` into the workspace and track upstream/main in the local main branch
2. The origin remote is configured, allowing me to push branches to origin in order to open a PR

### Additional context

On a DevWorkspace level, the configuration looks like
```yaml
projects:
  - name: che-docs
    git:
      remotes:
        upstream: 'https://github.com/eclipse-che/che-docs.git'
        origin: https://github.com/amisevsk/che-docs.git
      checkoutFrom:
        remote: upstream
        revision: master
```
(`revision` can be omitted if the default branch is to be used)

Related issue: Sometimes Che-Theia overwrites the DevWorkspace CR when adding remotes via UI: https://github.com/eclipse/che/issues/21244
