### ISSUE TITLE
Cannot install any plugin if sample repo doesn't have `extensions.json` file

### ISSUE THREAD

**Issue by svor** [eclipse-che/che#21422]
### Describe the bug

After creating a workspace via factory with the project sample which doesn't contain `.vscode/extensions.json`, I tried to use the Plugins view to install some plugins. As a result plugins were marked as installed, but not into **tools** container, because `/plugins` folder doesn't exist in tools container. See screenshots. 

Repo url: https://github.com/crw-samples/web-nodejs-sample/tree/che-qe-no-extensions

<details>
  <summary>Devfile.yaml</summary>

```
schemaVersion: 2.1.0
metadata:
  name: nodejs-web-app
components:
  - name: tools
    container:
      image: quay.io/devspaces/udi-rhel8:3.1
      endpoints:
        - exposure: public
          name: nodejs
          protocol: http
          targetPort: 3000
      memoryLimit: 1G
      mountSources: true
      volumeMounts:
        - name: npm
          path: /home/user/.npm
  - name: npm
    volume:
      size: 1G
commands:
  - id: 1-dependencies
    exec:
      label: "Download dependencies"
      component: tools
      workingDir: ${PROJECTS_ROOT}/web-nodejs-sample/app
      commandLine: "npm install"
      group:
        kind: build
  - id: 2-run
    exec:
      label: "Run the web app"
      component: tools
      workingDir: ${PROJECTS_ROOT}/web-nodejs-sample/app
      commandLine: "nodemon app.js"
      group:
        kind: run
  - id: 3-install-and-run
    exec:
      label: "Run the web app (and download dependencies)"
      component: tools
      workingDir: ${PROJECTS_ROOT}/web-nodejs-sample/app
      commandLine: "npm install; nodemon app.js"
      group:
        kind: run
  - id: 4-debug
    exec:
      label: "Run the web app (debugging enabled)"
      component: tools
      workingDir: ${PROJECTS_ROOT}/web-nodejs-sample/app
      commandLine: "nodemon --inspect app.js"
      group:
        kind: debug
        isDefault: true
  - id: 5-stopapp
    exec:
      label: "Stop the web app"
      component: tools
      commandLine: >-
          node_server_pids=$(pgrep -fx '.*nodemon (--inspect )?app.js' | tr "\\n" " ") &&
          echo "Stopping node server with PIDs: ${node_server_pids}" && 
          kill -15 ${node_server_pids} &>/dev/null && echo 'Done.'
      group:
        kind: run
```

</details>

### Che version

next (development version)

### Steps to reproduce

1. start the workspace by factory: https://che-host/#/https://github.com/crw-samples/web-nodejs-sample/tree/che-qe-no-extensions
2. Open plugins view and install Go plugin
3. Check **/plugins** folder in tools container

### Expected behavior

Plugins should be installed into the tools container

### Runtime

OpenShift

### Screenshots

![screenshot-che-dogfooding apps che-dev x6e0 p1 openshiftapps com-2022 05 24-20_27_33](https://user-images.githubusercontent.com/1271546/170101941-8bf8619a-2391-42b2-8dcd-8af92fc946ba.png)

![screenshot-che-dogfooding apps che-dev x6e0 p1 openshiftapps com-2022 05 24-20_24_53](https://user-images.githubusercontent.com/1271546/170101944-268e6aa7-ff9f-40c7-ac54-70994548f3f8.png)

### Installation method

chectl/next

### Environment

Linux
