### ISSUE TITLE
Support the Devfile Composite Commands in VS Code

### ISSUE THREAD

**Issue by azatsarynnyy** [eclipse-che/che#21859]
### Is your enhancement related to a problem? Please describe

Devfile has a notion of [Composite Commands](https://devfile.io/docs/2.2.0/adding-a-composite-command). It allows connecting multiple Commands together by defining a single Composite Command. E.g.:
```yaml
commands:
  - id: package
    exec:
      component: tools
      commandLine: 'mvn package'
      group:
        kind: build
  - id: install
    exec:
      component: tools
      commandLine: 'mvn install'
      group:
        kind: build
        isDefault: true
  - id: installAndPackage
    composite:
      commands:
        - install
        - package
      parallel: false
```

Currently, VS Code editor in Che doesn't support the Devfile Composite Commands. So, the user isn't able to use them in any way.

### Describe the solution you'd like

VS Code has a notion of the [Compound Tasks](https://code.visualstudio.com/docs/editor/tasks#_compound-tasks) which we can rely on when translating the Devfile's Composite Commands.
The example above can be translated to something like:
```json
{
  "version": "2.0.0",
  "tasks": [
    {
      "label": "package",
      "command": "mvn",
      "args": ["package"]
    },
    {
      "label": "Install",
      "command": "mvn",
      "args": ["install"]
    },
    {
      "label": "installAndPackage",
      "dependsOn": ["package", "Install"]
    }
  ]
}
```
