### ISSUE TITLE
Add utils to parse environment recipe format

### ISSUE THREAD

**Issue by ashumilova** [eclipse-che/che#2213]
Add ability to parse environment recipe format, which is yaml file as following:

```
"services:
  dev-machine:
    build:
      context: url
    depends_on:
      - second-machine
    mem_limit: 2147483648
  second-machine:
    image: codenvy/ubuntu_jdk8 
    mem_limit: 1073741824"
```

This will allow to read machine's recipe/image, RAM limit. 
Also need to be able to set those values in environment recipe from dashboard
