### ISSUE TITLE
"che-operator" ignores "imagePullPolicy: Always" value in CheCluster

### ISSUE THREAD

**Issue by dmytro-ndp** [eclipse-che/che#22272]
### Describe the bug

There was `imagePullPolicy: IfNotPresent` in "che-dashboard" deployment even though Eclipse Che has been installed with CheCluster containing:
```
spec:
  components:
    dashboard:
      deployment:
        containers:
          - image: 'quay.io/eclipse/che-dashboard:pr-829'
          - imagePullPolicy: Always
```

It makes it's impossible to check PR using the several builds of the same image built from PR with tag with PR number, like `pr-829` on the same OpenShift instance, due to `imagePullPolicy: IfNotPresent` in che-dashboard deployment by default.

### Che version

next (development version)

### Steps to reproduce

1. Deploy Eclipse Che Next with next CheCluster patch [1]:
```
spec:
  components:
    cheServer:
      debug: false
      logLevel: INFO
    dashboard:
      deployment:
        containers:
          - image: 'quay.io/eclipse/che-dashboard:pr-829'
          - imagePullPolicy: Always
```

2. Go to `che-dashboard` deployment.

### Expected behavior

There is `imagePullPolicy: Always` in "che-dashboard" deployment.

### Runtime

OpenShift

### Installation method

chectl/next

### Environment

Linux

### Eclipse Che Logs
Che-operator logs: 
[che-operator-56bd6b848d-96pbq-che-operator.log.txt](https://github.com/eclipse/che/files/11657897/che-operator-56bd6b848d-96pbq-che-operator.log.txt)

### Additional context

- CheCluster: 
[checluster-eclipse-che.yaml.txt](https://github.com/eclipse/che/files/11657855/checluster-eclipse-che.yaml.txt)

- che-dahsboard deployment: 
[deployment-che-dashboard.yaml.txt](https://github.com/eclipse/che/files/11657856/deployment-che-dashboard.yaml.txt)

**Comment by tolusha** [comment]
Probably it is misconfiguration, try this:
```
spec:
  components:
    dashboard:
      deployment:
        containers:
          - image: 'quay.io/eclipse/che-dashboard:pr-829'
            imagePullPolicy: Always
```
