### ISSUE TITLE
Make default setting CHE_DEFAULT_SPEC_DEVENVIRONMENTS_DEFAULTCOMPONENTS use same UDI image as everything else

### ISSUE THREAD

**Issue by amisevsk** [eclipse-che/che#22427]
### Is your enhancement related to a problem? Please describe

The default value for `checluster.spec.devEnvironments.defaultComponents` is stored in the environment variable CHE_DEFAULT_SPEC_DEVENVIRONMENTS_DEFAULTCOMPONENTS.

This variable references the UDI image associated with the current release:
```yaml
  - name: CHE_DEFAULT_SPEC_DEVENVIRONMENTS_DEFAULTCOMPONENTS
    value: '[{"name": "universal-developer-image", "container":
      {"image": "quay.io/devfile/universal-developer-image@sha256:c351dba8c203494512aae20d91144a0843f68e897fbc4ce0296939b48f49853e"}}]'
```

This can cause an issue with automation for updating the UDI image in response to CVEs, etc., as this automation will replace e.g. the UDI used in the devfile and plugin registries:
```yaml
  - name: RELATED_IMAGE_universal_developer_image_plugin_registry_image_<base64>
    value: quay.io/devfile/universal-developer-image@sha256:c351dba8c203494512aae20d91144a0843f68e897fbc4ce0296939b48f49853e
```
since they are RELATED_IMAGEs, but not the UDI image used for default components.

This means that empty workspace samples do not necessarily get the same CVE fixes as other workspaces (that have devfiles associated with them).

### Describe the solution you'd like

Ideally, we should resolve additional environment variables inside the default setting field. Something like
```yaml
  - name: RELATED_IMAGE_universal-developer-image
    value: quay.io/devfile/universal-developer-image@sha256:c351dba8c203494512aae20d91144a0843f68e897fbc4ce0296939b48f49853e
  - name: CHE_DEFAULT_SPEC_DEVENVIRONMENTS_DEFAULTCOMPONENTS
    value: '[{"name": "universal-developer-image", "container":
      {"image": "${RELATED_IMAGE_universal-developer-image}"}}]'
```
which the Che Operator resolves to the same default setting as above.
