### ISSUE TITLE
Add support for devfiles with popular images e.g. ubuntu, debian

### ISSUE THREAD

**Issue by olexii4** [eclipse-che/che#22862]
### Describe the bug

We cannot start a workspace with the **che-code** editor and a **ubuntu** or **debian** container.

### Che version

7.82@latest

### Steps to reproduce

1. Create a gist with one  of the standard images as a  dev-container:
``` yaml
schemaVersion: 2.2.0
metadata:
  generateName: empty-ubuntu-
components:
  - name: runtime
    container:
      image: docker.io/ubuntu:20.04
      args:
        - tail
        - '-f'
        - /dev/null
```
or use the [created one](https://gist.githubusercontent.com/olexii4/aafcb34e0a396a03f3e1bc644f10f624/raw/9386bac1621e7320c14c8b09163fd40cc68e1d16/devfile.yaml).
2. Create a new workspace from the gist:
```
{che-server}#https://gist.githubusercontent.com/olexii4/aafcb34e0a396a03f3e1bc644f10f624/raw/9386bac1621e7320c14c8b09163fd40cc68e1d16/devfile.yaml
```
4. You will see an infinity loop after the workspace starts:

[Empty ubuntu with Eclipse CHE](https://youtu.be/m_h-IMirZLA)

[Nodejs starter with Eclipse CHE](https://youtu.be/vE9u5NdD6lo)

### Expected behavior

A new workspace should be started without any issues.

### Runtime

OpenShift

### Screenshots

![Знімок екрана 2024-03-04 о 16 09 27](https://github.com/eclipse/che/assets/6310786/a20a3d0a-02e6-4d91-860b-d65c28be6051)
![Знімок екрана 2024-03-04 о 16 11 05](https://github.com/eclipse/che/assets/6310786/8402ffd6-aecf-473d-9c70-e1cf7c43d520)

### Installation method

chectl/latest, chectl/next

### Environment

Linux, macOS

### Additional context

[Empty ubuntu with Eclipse CHE](https://youtu.be/m_h-IMirZLA)

[Nodejs starter with Eclipse CHE](https://youtu.be/vE9u5NdD6lo)
