### ISSUE TITLE
Restart Workspace from Local Devfile command should be more informative when devfile is not valid

### ISSUE THREAD

**Issue by svor** [eclipse-che/che#22913]
### Is your task related to a problem? Please describe

After changing the devfile by making it invalid, the Restart Workspace from Local Devfile command fails and it is expected, but the reason of the failure is not clear.

I've started the workspace via https://github.com/che-samples/web-nodejs-sample and made next changes in the devfile:
```yaml
components:
  - name: tools
    container:
      image: quay.io/devfile/universal-developer-image:latest
      endpoints:
        - exposure: public
          name: nodejs
          protocol: http
          targetPort: 3000
      memoryLimit: 1G
      mountSources: true
      env:
        - name: KUBEDOCK_ENABLE
          value: true
```

_NOTE:_  **value: true** is not valid, it should be **value: "true"**

![screenshot-nimbusweb me-2024 04 09-12_03_02](https://github.com/eclipse-che/che/assets/1271546/c5d1b556-8ef8-49e6-bba1-5726e5b9951d)

### Describe the solution you'd like

It would be nice to see the reason of failure instead of **Something went wrong for the 'Restart From Local Devfile' action: HttpError: HTTP request failed**

### Describe alternatives you've considered

maybe we should use devfile schema validator during the restart and show the real problem. 
We've added the validator into devworkspace generator tool: https://github.com/eclipse-che/che-devfile-registry/pull/796  

### Additional context

If vscode-yaml extension is installed in the workspace, it shows this problem in the editor:
![screenshot-nimbusweb me-2024 04 09-12_28_07](https://github.com/eclipse-che/che/assets/1271546/785c7c51-3961-4a0e-a54c-8ff941195da7)
