### ISSUE TITLE
The quay.io/devfile/universal-developer-image does not persist SDKMAN newly installed versions when a PVC is mounted to /home/user

### ISSUE THREAD

**Issue by achdmbp** [eclipse-che/che#23332]
### Describe the bug

 quay.io/devfile/universal-developer-image doesn't persist newly installed SDKMAN versions when  a PVC is mounted to /home/user

### Che version

7.95

### Steps to reproduce

1. use the following devfile.yaml to create a workspace

```yaml
schemaVersion: 2.2.0
metadata:
  name: home-persistence-test
components:
  - container:
      image:  quay.io/devfile/universal-developer-image:latest
      sourceMapping: /projects
      volumeMounts:
        - name: home-vol
          path: /home/user
    name: tools
  - volume:
      size: 10Gi
    name: home-vol
```

2. once workspace starts, run the following in a bash terminal to install java 23 and set it to default globally

```bash
sdk install java 23.0.2-amzn
sdk default java 23.0.2-amzn
```

3. afterward if you run `java --version` you will get `openjdk 23.0.2*` as expected.
4. run `sdk list java`, `23.0.2-amzn` shows with status installed
5. restart workspace and run `java --version` you will see it is back to default `openjdk 17.0.13*`
6. run `sdk list java`, `23.0.2-amzn` doesn't showa as it is installed

### Expected behavior

after installing a new version of java and setting it to default using sdkman, restarting workspace should persist the new version

### Runtime

OpenShift

### Installation method

OperatorHub

### Environment

macOS

### Eclipse Che Logs

```shell

```

**Comment by dkwon17** [comment]
Hello, for quay.io/devfile/universal-developer-image, the sdkman candidates are stored here:
```
$ echo $SDKMAN_CANDIDATES_DIR
/home/tooling/.sdkman/candidates
```

To persist the new version of Java, could you try:
```
schemaVersion: 2.2.0
metadata:
  name: home-persistence-test
components:
  - container:
      image:  quay.io/devfile/universal-developer-image:latest
      sourceMapping: /projects
      volumeMounts:
        - name: candidates
          path: /home/tooling/.sdkman/candidates
    name: tools
  - volume:
      size: 10Gi
    name: candidates
```

Also, for persistent /home/user, have you considered [enabling persistent user home](https://eclipse.dev/che/docs/stable/administration-guide/about-persistent-user-home/) from the CheCluster CR?
