### ISSUE TITLE
command instruction not supported in compose file

### ISSUE THREAD

**Issue by ghost** [eclipse-che/che#2365]
**Reproduction Steps:**

Use:

`command: tail -f /dev/null`

in the compose file.

**Expected behavior:**

Command is executed

**Observed behavior:**

Error parsing compose file

Currently command is accepted as:

`command: [tail, -f, /dev/null]`

**Comment by garagatyi** [comment]
Please provide an example of compose file you used to reproduce behavior

**Comment by ghost** [comment]
```
services:
 db:
  image: codenvy/mysql
  environment:
   MYSQL_USER: petclinic
   MYSQL_PASSWORD: password
  mem_limit: 2147483648
  command: service mysql start
 dev-machine:
  image: codenvy/ubuntu_jdk8
  mem_limit: 2147483648
  depends_on:
    - db
```
