### ISSUE TITLE
volumes_from does not work

### ISSUE THREAD

**Issue by ghost** [eclipse-che/che#2366]
When using volumes_from in compose file, an error occurred saying that container with a `service` name does not exist.

**Reproduction Steps:**

Create a custom stack with the following recipe:

```
services:
 db:
  image: codenvy/mysql
  environment:
   MYSQL_ROOT_PASSWORD: root
   MYSQL_USER: petclinic
   MYSQL_PASSWORD: password
  mem_limit: 2147483648
 dev-machine:
  image: codenvy/ubuntu_jdk8
  mem_limit: 2147483648
  depends_on:
    - db
  links:
    - db
  volumes_from:
   - db

```

**Expected behavior:**

Workspace starts and dev-machine inherits volumes from db service

**Observed behavior:**

Unable to start workspace agent. Error when trying to start the workspace agent: Start of environment wksp-7vlgfw failed. Error: Error response from docker API, status: 404, message: No such container: db
