### ISSUE TITLE
Dev agent is not deployed to all machines

### ISSUE THREAD

**Issue by ghost** [eclipse-che/che#2467]
When starting a workspace with multiple machines, terminal is unavailable for non dev machine

**Reproduction Steps:**
1. Start a workspace from the following recipe in UD (custom stack):

```
services:
 machine:
  image: codenvy/ubuntu_jdk8
  mem_limit: 2147483648
 dev-machine:
  image: codenvy/ubuntu_jdk8
  mem_limit: 2147483648
  depends_on:
   - machine
```

Terminal in machine `machine` is unavailable.
