### ISSUE TITLE
Array format unsupported for environment in compose file

### ISSUE THREAD

**Issue by ghost** [eclipse-che/che#2624]
Docker compose environment is accepted as array and dictionary - https://docs.docker.com/compose/compose-file/#/environment. However, array format is unsupported in Che.

**Reproduction Steps:**
1. Create a workspace with the following compose file

```
services: 
 dev-machine: 
  image: codenvy/ubuntu_jdk8
  environment: 
   - MYSQL_ROOT_PASSWORD=root 
   - MYSQL_DATABASE=utqg 
```

**Expected behavior:**
Support dictionary and array.

```
environment:
  RACK_ENV: development
  SHOW: 'true'
  SESSION_SECRET:

environment:
  - RACK_ENV=development
  - SHOW=true
  - SESSION_SECRET
```

**Observed behavior:**

```

Parsing of recipe of environment 'wksp-rkq9' failed. Error: Parsing of environment configuration failed. Can not deserialize instance of java.util.LinkedHashMap out of START_ARRAY token
at [Source: java.io.StringReader@29a1353; line: 5, column: 4] (through reference chain: org.eclipse.che.api.environment.server.compose.model.ComposeEnvironmentImpl["services"]->java.util.LinkedHashMap["dev-machine"]->org.eclipse.che.api.environment.server.compose.model.ComposeServiceImpl["environment"])
```
