### ISSUE TITLE
Remote build context in compose file fails when using a git repo rather than a direct link to a Dockerfile

### ISSUE THREAD

**Issue by ghost** [eclipse-che/che#2684]
1. Create a workspace with the following recipe:

```
services:
 dev-machine:
  build:
   context: https://github.com/eclipse/che.git
```

This recipe works locally while Che says:

`Unable to start workspace agent. Error when trying to start the workspace agent: Start of environment wksp-aekgddsdffews failed. Error: Error response from docker API, status: 500, message: Error response from daemon: Error trying to use git: exec: "git": executable file not found in $PATH ()`
