### ISSUE TITLE
Named Volume Support for Compose Recipes

### ISSUE THREAD

**Issue by JamesDrummond** [eclipse-che/che#2783]
Enhancement request for [named volumes](https://docs.docker.com/compose/compose-file/#/volume-configuration-reference) support in compose recipe. This enhancement will allow runtime machines in a multi-machine workspaces the ability to share folders/files through shared volumes created specifically for the multi-machine workspace while not making the host file system vulnerable.

This enhancement is related to [https://github.com/codenvy/codenvy/issues/897](https://github.com/codenvy/codenvy/issues/897).

**Expected Usage Example:**

```
services:
  db:
    image: codenvy/mysql
    volumes:
      - db_volume:/mnt/db_volume
    environment:
      MYSQL_DATABASE: petclinic
      MYSQL_USER: petclinic
      MYSQL_PASSWORD: password
    mem_limit: 1073741824
  dev-machine:
    image: codenvy/ubuntu_jdk8
    mem_limit: 2147483648
    volumes:
      - db_volume:/mnt/db_volume
    depends_on:
      - db
  volumes:
    db_volume:

```
