### ISSUE TITLE
cannot open git-upload-pack error

### ISSUE THREAD

**Issue by aleksei-burlakov** [eclipse-che/che#4110]
I have added custom project types into the `samples.json` file. I have also configure git on the host machine to avoid ssl verification by the command `git config --global http.sslVerify false`. When I try to create a custom project (one from the samples.json list) it returns an error
`https://github.com/BlahBlah/Demo.git: cannot open git-upload-pack` 

**OS and version:**    Ubuntu 16.04

**Comment by TylerJewell** [comment]
@skabashnyuk @vkuznyetsov @vparfonov - any ideas on this?

@aleksei-burakov - can you give some more specifics on how you setup your Che assembly?

**Comment by vinokurig** [comment]
@aleksei-burakov Workspace runs in a separate environment, so configuring Git on your host machine does not make sense. Try to execute your configuration command in the terminal in Che.

**Comment by aleksei-burlakov** [comment]
@vinokurig thank you. I should have configured dns in the docker file.

**Comment by riuvshin** [comment]
it seems this issue still can be reproduced sometimes.

**Comment by riuvshin** [comment]
we can't reliably reproduce this issue it happens randomly
on client:
![image](https://cloud.githubusercontent.com/assets/1636732/26113106/4b6d0fe4-3a62-11e7-9eb1-7a85b16191e3.png)
![image 1](https://cloud.githubusercontent.com/assets/1636732/26113122/585cdffe-3a62-11e7-90f4-66f03f54f26d.png)
in ws agent logs :
(we've figured out that this trace is result of import failure this is not the cause)
```
2017-05-16 14:47:56,549[ted-scheduler-4]  [ERROR] [o.e.c.a.v.w.FileWatcherService 199]  - Can’t register dir /projects/release22/.git in file watch service
java.nio.file.NoSuchFileException: /projects/release22/.git
        at sun.nio.fs.UnixException.translateToIOException(UnixException.java:86)
        at sun.nio.fs.UnixException.asIOException(UnixException.java:111)
        at sun.nio.fs.LinuxWatchService$Poller.implRegister(LinuxWatchService.java:246)
        at sun.nio.fs.AbstractPoller.processRequests(AbstractPoller.java:260)
        at sun.nio.fs.LinuxWatchService$Poller.run(LinuxWatchService.java:329)
        at java.lang.Thread.run(Thread.java:745)
```

**Comment by ghost** [comment]
This error shows up when there's no connectivity and JGit can't import sources (can be reproduced behind the proxy when proxy isn't configured for ws agent for example)

**Comment by ghost** [comment]
Can it be some networking issues on AWS? users report smth similar https://github.com/codenvy/codenvy/issues/2205

![image](https://cloud.githubusercontent.com/assets/5337267/26140691/d9247c18-3ae0-11e7-968b-68d9ce951491.png)

**Comment by ghost** [comment]
Looks liek aws issues. Closing.

**Comment by kostiamol** [comment]
I'm deploying che as a helm chart at private infrastructure with proxy. I use my custom stack with http_proxy and https_proxy var defined. But when I'm starting workspace che can't clone the projects:

![screenshot from 2018-06-15 11-24-11](https://user-images.githubusercontent.com/5477699/41462915-cac4d59c-7094-11e8-9241-b98d5304aa91.png)

At the same time I'm able to clone the project in the terminal:

![image](https://user-images.githubusercontent.com/5477699/41462987-1b2303ce-7095-11e8-82e4-e3457ea41914.png)

**Comment by eivantsov** [comment]
You will need to add proxy settings as JAVA_OPTS.

**Comment by kostiamol** [comment]
@eivantsov You mean in `configmap.yaml` like that?
` JAVA_OPTS: "-XX:MaxRAMFraction=2 -XX:+UseParallelGC -XX:MinHeapFreeRatio=10 -XX:MaxHeapFreeRatio=20 ... http_proxy=$IP https_proxy=$IP "`

**Comment by eivantsov** [comment]
@kostiamol no, those will be applied for Che pod not workspace pods.

It should be 

`CHE_WORKSPACE_WSAGENT_JAVA__OPTIONS`

Once you add this one and redeploy, pay attention to ws-agent start logs to make sure it uses your proxy settings as JVM args

**Comment by kostiamol** [comment]
@eivantsov I tried a lot of format variants according to the  [post](https://stackoverflow.com/questions/120797/how-do-i-set-the-proxy-to-be-used-by-the-jvm) but the workspace doesn't see my variables. I even used another [variable name](https://github.com/eclipse/che/blob/master/assembly/assembly-wsmaster-war/src/main/webapp/WEB-INF/classes/che/che.properties#L69).
```
CHE_WORKSPACE_HTTP_PROXY_JAVA_OPTIONS: "-Dhttp.proxyHost=135.245.192.7 -Dhttp.proxyPort=8000 "
CHE_WORKSPACE_HTTPS_PROXY_JAVA_OPTIONS: "-Dhttp.proxyHost=135.245.192.7 -Dhttp.proxyPort=8000 "
CHE_WORKSPACE_WSAGENT_JAVA__OPTIONS: "-Dhttp.proxyHost=135.245.192.7 -Dhttp.proxyPort=8000 "
```

![image](https://user-images.githubusercontent.com/5477699/41533666-ddba632e-72fb-11e8-8968-1627b194f436.png)

**Comment by eivantsov** [comment]
@kostiamol it should be 

`CHE_WORKSPACE_WSAGENT__JAVA__OPTIONS`

Double underscore.

**Comment by kostiamol** [comment]
It still doesn't work.

```
# Copyright (c) 2012-2017 Red Hat, Inc
# All rights reserved. This program and the accompanying materials
# are made available under the terms of the Eclipse Public License v1.0
# which accompanies this distribution, and is available at
# http://www.eclipse.org/legal/epl-v10.html
#

apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    app: che
  name: che
data:
  CHE_HOST: {{ template "cheHost" . }}
  CHE_PORT: "8080"
{{- if and .Values.global.tls .Values.global.tls.enabled }}
  CHE_API: https://{{ template "cheHost" . }}/api
  CHE_WEBSOCKET_ENDPOINT:  wss://{{ template "cheHost" . }}/api/websocket
  CHE_INFRA_KUBERNETES_BOOTSTRAPPER_BINARY__URL: https://{{ template "cheHost" . }}/agent-binaries/linux_amd64/bootstrapper/bootstrapper
{{ else }}
  CHE_API: http://{{ template "cheHost" . }}/api
  CHE_WEBSOCKET_ENDPOINT:  ws://{{ template "cheHost" . }}/api/websocket
  CHE_INFRA_KUBERNETES_BOOTSTRAPPER_BINARY__URL: http://{{ template "cheHost" . }}/agent-binaries/linux_amd64/bootstrapper/bootstrapper
{{- end }}
  CHE_DEBUG_SERVER: "true"
  CHE_INFRASTRUCTURE_ACTIVE: "kubernetes"
  CHE_INFRA_KUBERNETES_INGRESS_DOMAIN: {{ .Values.global.ingressDomain }}
  CHE_INFRA_KUBERNETES_MACHINE__START__TIMEOUT__MIN: "5"
  CHE_INFRA_KUBERNETES_MASTER__URL: ""
  CHE_INFRA_KUBERNETES_OAUTH__TOKEN: ""
  CHE_INFRA_KUBERNETES_PASSWORD: ""
  CHE_INFRA_KUBERNETES_USERNAME: ""
  CHE_INFRA_KUBERNETES_NAMESPACE: {{ .Values.global.cheNamespace }}
{{- if and .Values.global.tls .Values.global.tls.enabled }}
  CHE_INFRA_KUBERNETES_TLS__ENABLED: {{ .Values.global.tls.enabled | quote}}
  CHE_INFRA_KUBERNETES_TLS__SECRET: {{ .Values.global.tls.secretName }}
{{- else }}
  CHE_INFRA_KUBERNETES_TLS__ENABLED: "false"
  CHE_INFRA_KUBERNETES_TLS__SECRET: ""
{{- end }}
{{- if .Values.global.multiuser }}
  CHE_KEYCLOAK_CLIENT__ID: {{ .Values.cheKeycloakClientId }}
  CHE_KEYCLOAK_AUTH__SERVER__URL: {{ template "keycloakAuthUrl" . }}
  CHE_KEYCLOAK_REALM: {{ .Values.cheKeycloakRealm }}
{{- end }}
{{- if (and .Values.global.multiuser .Values.customOidcProvider) }}
  CHE_KEYCLOAK_OIDC__PROVIDER: {{ .Values.customOidcProvider }}
{{- end }}
{{- if and .Values.global.multiuser .Values.customOidcUsernameClaim }}
  CHE_KEYCLOAK_USERNAME__CLAIM: {{ .Values.customOidcUsernameClaim }}
{{- end }}
  CHE_INFRA_KUBERNETES_NAMESPACE: ""
  CHE_INFRA_KUBERNETES_TRUST__CERTS: "false"
  CHE_INFRA_KUBERNETES_PVC_STRATEGY: "common"
  CHE_INFRA_KUBERNETES_PVC_PRECREATE__SUBPATHS: "false"
  CHE_INFRA_KUBERNETES_POD_SECURITY__CONTEXT_RUN__AS__USER: "0"
  CHE_INFRA_KUBERNETES_POD_SECURITY__CONTEXT_FS__GROUP: "0"
  CHE_LOCAL_CONF_DIR: /etc/conf
  CHE_LOGS_DIR: /data/logs
  CHE_LOG_LEVEL: "INFO"
  CHE_MULTIUSER: {{ .Values.global.multiuser | quote }}
  CHE_OAUTH_GITHUB_CLIENTID: {{ .Values.global.gitHubClientID }}
  CHE_OAUTH_GITHUB_CLIENTSECRET: {{ .Values.global.gitHubClientSecret }}
  CHE_PREDEFINED_STACKS_RELOAD__ON__START: "false"
  CHE_WORKSPACE_HTTP__PROXY__JAVA__OPTIONS: "-Dhttp.proxyHost=135.245.192.7 -Dhttp.proxyPort=8000 "
  CHE_WORKSPACE_HTTPS__PROXY__JAVA__OPTIONS: "-Dhttp.proxyHost=135.245.192.7 -Dhttp.proxyPort=8000 "
  CHE_WORKSPACE_WSAGENT__JAVA__OPTIONS: "-Dhttp.proxyHost=135.245.192.7 -Dhttp.proxyPort=8000 "
  JAVA_OPTS: "-XX:MaxRAMFraction=2 -XX:+UseParallelGC -XX:MinHeapFreeRatio=10 -XX:MaxHeapFreeRatio=20 -XX:GCTimeRatio=4 -XX:AdaptiveSizePolicyWeight=90 -XX:+UnlockExperimentalVMOptions -XX:+UseCGroupMemoryLimitForHeap -Dsun.zip.disableMemoryMapping=true -Xms20m "
  CHE_WORKSPACE_AUTO_START: "false"
{{- if .Values.global.tls.enabled }}
  CHE_INFRA_KUBERNETES_INGRESS_ANNOTATIONS__JSON: '{"kubernetes.io/ingress.class": "nginx", "kubernetes.io/tls-acme": "true", "{{ .Values.global.ingressAnnotationsPrefix }}ingress.kubernetes.io/rewrite-target": "/","{{ .Values.global.ingressAnnotationsPrefix }}ingress.kubernetes.io/ssl-redirect": "true","{{ .Values.global.ingressAnnotationsPrefix }}ingress.kubernetes.io/proxy-connect-timeout": "3600","{{ .Values.global.ingressAnnotationsPrefix }}ingress.kubernetes.io/proxy-read-timeout": "3600"}'
{{- else }}
  CHE_INFRA_KUBERNETES_INGRESS_ANNOTATIONS__JSON: '{"kubernetes.io/ingress.class": "nginx", "{{ .Values.global.ingressAnnotationsPrefix }}ingress.kubernetes.io/rewrite-target": "/","{{ .Values.global.ingressAnnotationsPrefix }}ingress.kubernetes.io/ssl-redirect": "false","{{ .Values.global.ingressAnnotationsPrefix }}ingress.kubernetes.io/proxy-connect-timeout": "3600","{{ .Values.global.ingressAnnotationsPrefix }}ingress.kubernetes.io/proxy-read-timeout": "3600"}'
{{- end }}
  CHE_INFRA_KUBERNETES_SERVER__STRATEGY: {{ .Values.global.serverStrategy }}
  CHE_LOGS_APPENDERS_IMPL: "plaintext"

```
