### ISSUE TITLE
How to correctly setup Eclipse Che on Docker Cloud

### ISSUE THREAD

**Issue by davidwindell** [eclipse-che/che#4878]
I've just got Che running nicely (all diagnostic tests pass) on Docker Cloud / AWS. I just wanted to check whether we should still be setting `CHE_HOST` or not with the below config?

Everything seems to work fine without, I just don't want to slow anything down by external DNS or something happening where I can't see it.

We have set `CHE_DOCKER_IP_EXTERNAL` to the FQDN of the container running Che.

```yml
che:
  environment:
    - CHE_DOCKER_IP_EXTERNAL=$DOCKERCLOUD_SERVICE_FQDN
    - CHE_DOCKER_SERVER__EVALUATION__STRATEGY=docker-local
#  - CHE_HOST=$DOCKERCLOUD_SERVICE_FQDN
  image: 'eclipse/che-server:5.7.2'
  ports:
    - '8080:8080'
  restart: always
  ...
```

Oh, and how do `CHE_IP` and `CHE_API` come into this? They don't seem to be necessary even through we are connecting from a remote browser?

**Comment by TylerJewell** [comment]
So, you should only need to set `CHE_DOCKER_IP_EXTERNAL` if you want that value to be different from `CHE_HOST`. So, we would expect that you set `CHE_HOST` to your FQDN and then things will work properly. You also shouldn't need to set the server evaluation strategy. Anything in the `che.env` that is commented out is reflecting the default values, for which yours is one.

I believe that `CHE_IP` and `CHE_API` are no longer applicable variables, reflecting legacy of our 4.x generation and not the 5.x.

**Comment by davidwindell** [comment]
@TylerJewell when I change `CHE_DOCKER_IP_EXTERNAL` to `CHE_HOST`, diagnostics reports;

```
REST Call on Workspace Agent
Unable to perform call on http://172.17.0.1:33355/api:
```

It seems to be ignoring the CHE_HOST and using an internal IP?

**Comment by davidwindell** [comment]
Also, I set the evaluation strategy because our security group (firewall) on AWS only allows connections from remote IP's. if I leave it as the default, I get;

```
The workspace started, but Eclipse Che <--> Workspace connection not established
Hint: The workspace agent has started in the workspace, but the Eclipse Che server cannot verify this. There is a failure for Eclipse Che server to connect to your workspace's agent. Either your firewall is blocking essential ports or you can change CHE_DOCKER_IP and DOCKER_HOST to values specific to your environment. See the `Eclipse Cheenv file` file for specifics.
```

It seems to work fine if I force `docker-local`?

**Comment by TylerJewell** [comment]
Hi @davidwindell - sorry it took me some time to get back to you. 

Ok I see where the issue was in my guess. Your configuration is the proper one.

I had to go back into the networking specs to be clear on what you were doing.
1. Agree on the importance of `CHE_DOCKER_SERVER__EVALUATION__STRATEGY`. You need that for your specific configuration to enable the right server - workspace connections.

2. If `CHE_DOCKER_IP_EXTERNAL` is not set, then it will default to the value of `CHE_DOCKER_IP`. I thought this was automatically set to the value of `CHE_HOST` and that is not correct. It is set to an internal default Docker IP address as a default. So, your original configuration is the proper one. `CHE_HOST` is getting set to the default value of our IP detection algorithm.

**Comment by davidwindell** [comment]
Awesome, thanks for validating the setup!

I won't set `CHE_DOCKER_IP` or presumably Che will then try to use the external FQDN to connect to docker which *isn't* what I want to happen.

For stability, shall I just go ahead and set `CHE_HOST` to the external FQDN?

**Comment by TylerJewell** [comment]
There shouldn't be a need to.  It is not necessary here.

**Comment by davidwindell** [comment]
For those interested, our full stack looks roughly like this:

```yml
che-user1:
  environment:
    - CHE_DOCKER_IP_EXTERNAL=$DOCKERCLOUD_SERVICE_FQDN
    - CHE_DOCKER_SERVER__EVALUATION__STRATEGY=docker-local
    - CHE_PORT=80
    - CHE_WORKSPACE_VOLUME=/var/run/docker.sock:/var/run/docker.sock
    - VIRTUAL_HOST=$DOCKERCLOUD_SERVICE_FQDN
  expose:
    - '80'
  image: 'eclipse/che-server:5.7.2'
  restart: always
  volumes:
    - '/var/run/docker.sock:/var/run/docker.sock'
    - '/your/host/data/path:/data'
che-user2:
  ...same as "che-user1" but with a different volume mount
nginx-proxy:
  image: 'jwilder/nginx-proxy:alpine'
  ports:
    - '80:80'
  restart: always
  volumes:
    - '/var/run/docker.sock:/tmp/docker.sock:ro'
```

This instantly gives us multi-user single-server Che with auth handled via AWS VPC Security Groups (i.e. IP grants).
