### ISSUE TITLE
Cannot create a workspace from a custom composefile

### ISSUE THREAD

**Issue by ghost** [eclipse-che/che#5047]
Steps to reproduce:

1. Create a workspace from a custom composefile:

```
services:
  db:
    image: eclipse/mysql
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: petclinic
      MYSQL_USER: petclinic
      MYSQL_PASSWORD: password
    mem_limit: 1073741824
  dev-machine:
    image: eclipse/ubuntu_jdk8
    mem_limit: 2147483648
    depends_on:
      - db
```
2. Create button is disabled and the following errors are displayed:

```
Cannot parse recipe from line: services

The environment should contain exactly one dev machine. Switch on Dev property to have terminal, SSH and IDE tooling injected to the machine

```
