### ISSUE TITLE
BC break in Docker Che entrypoint.sh

### ISSUE THREAD

**Issue by davidwindell** [eclipse-che/che#5142]
A recent change to `entrypoint.sh` https://github.com/eclipse/che/commit/4813a1a712abb1e0bb949b1c2dcdc7a7b206fd63#diff-1da4013f60e1b92b5613cf9680423a88 seems to have caused our environments to start up without the users database or custom stacks.

Are there upgrade docs for this or do we need to set `CHE_HOME` in an env var?

**Comment by benoitf** [comment]
@riuvshin ?

**Comment by davidwindell** [comment]
For context, here is the current service definition

```
che-user:
  environment:
    - CHE_DOCKER_IP_EXTERNAL=user.cheserverdomain.com
    - CHE_DOCKER_SERVER__EVALUATION__STRATEGY=docker-local
    - CHE_PORT=80
    - CHE_WORKSPACE_VOLUME=/var/run/docker.sock:/var/run/docker.sock;/root/data/eclipse/users/user/ssh:/root/.ssh
    - VIRTUAL_HOST=user.cheserverdomain.com
  expose:
    - '80'
  image: 'eclipse/che-server:nightly'
  restart: always
  volumes:
    - '/var/run/docker.sock:/var/run/docker.sock'
    - '/root/data/eclipse/users/user:/data'
    - '/root/data/eclipse/templates:/data/templates'
    - '/root/data/eclipse/stacks/stacks.json:/tmp/stacks.json'
```
