### ISSUE TITLE
How to specify a dockerfile in recipe when create a new stack

### ISSUE THREAD

**Issue by qi-min** [eclipse-che/che#5310]
I am trying to create a stack with my runtime environment. From the Che Doc https://www.eclipse.org/che/docs/devops/runtime-stacks-data-model/index.html, recipe can also reference to dockerfile like below:
example:
```
"source": {
  "type": "dockerfile",
  "location": "http://beta.codenvy.com/api/recipe/recipec0v4ta2uz6jok0bn/script"
}
"source": {
  "type": "dockerfile",
  "content": "FROM eclipse/ubuntu_jdk8
              RUN echo hello world
              ENV MYCUSTOM=VALUE"
}
```
During creating stack, the default recipe format is as below. There will be syntax error  if I change 'image' to 'dockerfile'
```
new-machine:
 image: codenvy/ubuntu_jdk8
 mem_limit: 2147483648
```
![447673b3ac4ae9b8](https://user-images.githubusercontent.com/10006307/26964738-8521ba52-4d25-11e7-85bc-2c285582ec80.jpg)

The link 'Recipe Structure' links to 'http://localhost:8080/docs/workspace/recipes/index.html' return 404, so I do not find the correct format of Recipe file. What is the correct way to specify dockerfile in Recipe?

**Comment by ghost** [comment]
@m7luffy you have correctly specified a docker recipe. However, when it comes to adding a machine, your recipe is a composefile and the syntax you used is wrong.

In this case you need to use build context - https://docs.docker.com/compose/compose-file/compose-file-v2/#context However, in Che there can be only a remote build context.

Here's an example of how a compose recipe may look like:

```
services:
  dev-machine:
    image: eclipse/ubuntu_jdk8
    mem_limit: 2147483648
  new-machine:
    build:
      context: https://gist.githubusercontent.com/eivantsov/b22dcf0ca33f02005e694b86ca27c5fb/raw/c8d3ee5f7a2a78bbb118a2af8d05b70a664a3e3a/gistfile1.txt
    mem_limit: 2147483648
```
