### ISSUE TITLE
[SPI] Prefix names of objects in OpenShift recipe on provisioning step

### ISSUE THREAD

**Issue by sleshchenko** [eclipse-che/che#5963]
It is needed to rename objects in OpenShift recipe to make it possible to create two OpenShift workspace in one project aka namespace.
To make it possible it is needed to prefixes all objects in original user's OpenShift Recipe with some unique for workspace value like `id`. 

> It would be more readable to prefix them with workspace name (it is also unique) but OpenShift objects name is not сompatible with workspace name pattern:
Workspace name pattern is `[a-zA-Z0-9][-_.a-zA-Z0-9]{1,18}[a-zA-Z0-9]` [see](https://github.com/eclipse/che/blob/spi/wsmaster/che-core-api-workspace/src/main/java/org/eclipse/che/api/workspace/server/WorkspaceValidator.java#L43)
While OpenShift object name must match the regex `[a-z0-9]([-a-z0-9]*[a-z0-9])?(\.[a-z0-9]([-a-z0-9]*[a-z0-9])?)*` (e.g. 'example.com')

Now it is known the following list of fields which must be updated:
```yaml
Pod
    metadata:
        name: PREFIX
```
```yaml
Service
    metadata:
        name: DO_NOT_PREFIX,  # see UPDATE
```
```yaml
Route
    metadata:
        name: PREFIX
```

**Update:** Services names should not be prefixed because a user may use it for communication between pods. Note that in this case, a workspace will fail to start if there is another running workspace which contains at least one service with the same name.
Removed prefixing of labels and selectors keys. Issues with ensuring that services use only pods in the same workspace will be solved by adding label and selector fields entry with workspace id within this [issue](https://github.com/eclipse/che/issues/6284).
