### ISSUE TITLE
In `deploy_che.sh`, the keycloack route should be `https` when the che server is `https`

### ISSUE THREAD

**Issue by davidfestal** [eclipse-che/che#6666]
### Description

Currently, when deploying to Openshift, the route of the dedicated Keycloak server is always unsecured, even if the che server is deployed with a secured route.

This brings errors when the che-server tries to authenticate to the Keycloak server URL.

**Comment by ghost** [comment]
@davidfestal thanks for filing this issue. Just make sure that you have 

```
  tls:
    termination: edge
    insecureEdgeTerminationPolicy: Allow
  wildcardPolicy: None
```
in your https yaml for KC route.
