### ISSUE TITLE
[Multiuser] Instructions to run without CLI

### ISSUE THREAD

**Issue by davidwindell** [eclipse-che/che#6750]
In the docs, instructions are provided to run Multi-user Che with the CLI. 

We use a orchestrator (Rancher) to deploy our servers so we need to replicate how `CHE_MULTIUSER=true` works manually (i.e. by launching `che-server-multiuser`, etc).

Could someone update the docs or provide a link here to follow?

**Comment by ghost** [comment]
@davidwindell currently there are no docs as it's automated in CLI. Even though the process is not too complicated, there are things to take care of:

* configuration for Keycloak and Postgres
* volumes
* containers boot order (postgres-keycloak-che)

Here's composefile https://github.com/eclipse/che/blob/master/dockerfiles/init/modules/compose/templates/docker-compose.yml.erb

And this is how keycloak and postgres are configured https://github.com/eclipse/che/tree/master/dockerfiles/init/modules

I'll try to document it later

**Comment by davidwindell** [comment]
Fantastic, thanks!

**Comment by davidwindell** [comment]
After a bit of a push and shove, I've been able to get this to work in Rancher/Compose :+1: This is roughly what our compose definition now looks like:

```yml
version: '2'
services:
  keycloak:
    image: jboss/keycloak:3.3.0.CR2-3
    volumes:
    - /host/path/to/che/theme:/opt/jboss/keycloak/themes/che
    links:
    - postgres:postgres
    ports:
    - 5050:8080/tcp=
  che-server:
    image: eclipse/che-server-multiuser:5.19.0
    environment:
      CHE_PORT: '80'
      CHE_DOCKER_IP_EXTERNAL: our.che.host
      CHE_DOCKER_SERVER__EVALUATION__STRATEGY: docker-local
      CHE_HOST: our.che.host
      CHE_WORKSPACE_VOLUME: /var/run/docker.sock:/var/run/docker.sock
      CHE_MULTIUSER: 'true'
    volumes:
    - /var/run/docker.sock:/var/run/docker.sock
    links:
    - postgres:postgres
  postgres:
    image: postgres:9.6-alpine
    environment:
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: password
    volumes:
    - /host/path/to/postgres/data:/var/lib/postgresql/data
```

Anyone who takes this route will have to create their own che and keycloak databases and keycloak realm (I just imported the erb template into keycloak). We also mount the Che keycloak theme as a manual process.
