### ISSUE TITLE
YAML language server hover feature doesn't work

### ISSUE THREAD

**Issue by acdhound** [eclipse-che/che#9637]
### Description
Hover doesn't work for YAML files, when default YAML language server is enabled.

### Reproduction Steps
1. Run Che from Docker via command:
`docker run -i --rm -v //var/run/docker.sock://var/run/docker.sock -v //home/user/che_1:/data eclipse/che:6.4.1 start`

2. Create workspace from default blank stack

2. Enable YAML language server and run workspace

3. Go to Profile -> Preferences -> Language Server Settings -> YAML, click "Add Schema Url" and enter https://raw.githubusercontent.com/garethr/kubernetes-json-schema/master/v1.6.6/deployment.json. Save and close.
![che_set_yaml_schema](https://user-images.githubusercontent.com/10697631/39713812-c651869a-5230-11e8-8641-7a65613a4dd5.png)

4. Create blank project then create file "file.yaml" file with the following content:
```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  labels:
    app: nginx
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx:1.7.9
        ports:
        - containerPort: 80
```
Click Ctrl+Space after line 13 and see suggestions to ensure that schema is recognized and LS works.
![che_yaml_autocomplete](https://user-images.githubusercontent.com/10697631/39712572-351e8348-522c-11e8-94f6-dd16918d16af.png)

5. Hover on apiVersion in first line - nothing is shown.
![che_yaml_hover_doesnt_work](https://user-images.githubusercontent.com/10697631/39712630-671ccbac-522c-11e8-8823-3d3a57edbfc1.png)

What is expected to be shown (the same file and same schema in VS Code, Red Hat YAML plugin is enabled):
![vs_code_hover_works](https://user-images.githubusercontent.com/10697631/39712752-db05ad18-522c-11e8-845c-f38162842021.png)

**OS and version:**    
Che version: 6.4.1
OS: Windows 10 Pro

**Diagnostics:** 
![che_dev_machine_logs](https://user-images.githubusercontent.com/10697631/39713398-53bec724-522f-11e8-92f1-d15f3e957682.png)
