### ISSUE TITLE
timeout expired waiting for volumes to attach/mount for pod "eclipse-che"/"postgres-1-56ffs". list of unattached/unmounted volumes=[postgres-data]

### ISSUE THREAD

**Issue by mrmStack** [eclipse-che/che#9880]
I try to deploy elipse che multiuser in openshift origin 3.9.0, and I follow the steps of the documents of eclipse che in openshift, but doesnt't work.

https://www.eclipse.org/che/docs/openshift-multi-user.html

after time out 10 min the pod fail and "oc get events" shows this:

Warning   FailedMount  kubelet, che-nodo.app.es    Unable to mount volumes for pod "postgres-1-56ffs_eclipse-che(8e8c10b6-6419-11e8-b655-001a4aab0006)": timeout expired waiting for volumes to attach/mount for pod "eclipse-che"/"postgres-1-56ffs". list of unattached/unmounted volumes=[postgres-data]

PersistentVolumeClaim  Normal    FailedBinding           persistentvolume-controller   no persistent volumes available for this claim and no storage class is set

I don't know what's the problem,  somebody helps's me...

thanks regards.

**Comment by mrmStack** [comment]
LAST SEEN   FIRST SEEN   COUNT     NAME                                 KIND                    SUBOBJECT                     TYPE      REASON                        SOURCE                        MESSAGE
11m         11m          1         postgres-1-56ffs.153373ec11199ee3    Pod                                                   Normal    Scheduled                     default-scheduler             Successfully assigned postgres-1-56ffs to che-nodo.app.es
11m         11m          1         postgres-1-56ffs.153373ec229829ce    Pod                                                   Normal    SuccessfulMountVolume         kubelet, che-nodo.app.es    MountVolume.SetUp succeeded for volume "default-token-t7flx" 
2m          9m           4         postgres-1-56ffs.15337408b5502dab    Pod                                                   Warning   FailedMount                   kubelet, che-nodo.app.es    Unable to mount volumes for pod "postgres-1-56ffs_eclipse-che(8e8c10b6-6419-11e8-b655-001a4aab0006)": timeout expired waiting for volumes to attach/mount for pod "eclipse-che"/"postgres-1-56ffs". list of unattached/unmounted volumes=[postgres-data]
27s         27s          1         postgres-1-56ffs.15337487c22f4a56    Pod                                                   Warning   FailedMount                   kubelet, che-node01.pic.es    Unable to mount volumes for pod "postgres-1-56ffs_eclipse-che(8e8c10b6-6419-11e8-b655-001a4aab0006)": timeout expired waiting for volumes to attach/mount for pod "eclipse-che"/"postgres-1-56ffs". list of unattached/unmounted volumes=[postgres-data default-token-t7flx]
11m         11m          1         postgres-1-deploy.153373eb61b04081   Pod                                                   Normal    Scheduled                     default-scheduler             Successfully assigned postgres-1-deploy to che-nodo.app.es
11m         11m          1         postgres-1-deploy.153373eb6911472d   Pod                                                   Normal    SuccessfulMountVolume         kubelet, che-nodo.app.es    MountVolume.SetUp succeeded for volume "deployer-token-pdtcd" 
11m         11m          1         postgres-1-deploy.153373ebeaf37164   Pod                     spec.containers{deployment}   Normal    Pulled                        kubelet, che-nodo.app.es    Container image "openshift/origin-deployer:v3.9.0" already present on machine
11m         11m          1         postgres-1-deploy.153373ebedf2b4da   Pod                     spec.containers{deployment}   Normal    Created                       kubelet, che-nodo.app.es    Created container
11m         11m          1         postgres-1-deploy.153373ebf6a0540d   Pod                     spec.containers{deployment}   Normal    Started                       kubelet, che-nodo.app.es    Started container
11m         11m          1         postgres-1.153373ec10b7d5ec          ReplicationController                                 Normal    SuccessfulCreate              replication-controller        Created pod: postgres-1-56ffs
1m          1m           1         postgres-1.153374780b1c00e3          ReplicationController                                 Normal    SuccessfulDelete              replication-controller        Deleted pod: postgres-1-56ffs
1m          11m          43        postgres-data.153373eb61203c9d       PersistentVolumeClaim                                 Normal    FailedBinding                 persistentvolume-controller   no persistent volumes available for this claim and no storage class is set
11m         11m          1         postgres.153373eb5f576699            DeploymentConfig                                      Normal    DeploymentCreated             deploymentconfig-controller   Created new replication controller "postgres-1" for version 1
1m          1m           1         postgres.1533747809343101            DeploymentConfig                                      Normal    ReplicationControllerScaled   deploymentconfig-controller   Scaled replication controller "postgres-1" from 1 to 0

**Comment by eivantsov** [comment]
@mrmStack it looks like you do not have available PVs that can satisfy PVC that Postgres requires:

```
no persistent volumes available for this claim and no storage class is set
```

Can you log in as admin and run:

```
oc get pv
```

**Comment by mrmStack** [comment]
hi @eivantsov 

[root@che-astro multi]# oc get pv
NAME      CAPACITY   ACCESS MODES   RECLAIM POLICY   STATUS    CLAIM                                   STORAGECLASS   REASON    AGE
pv0001    5Gi        RWO            Recycle          Bound     openshift-ansible-service-broker/etcd                            26m

**Comment by mrmStack** [comment]
I created the pv whith a yaml template like this:

apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv0001 
spec:
  capacity:
    storage: 5Gi 
  accessModes:
  - ReadWriteOnce 
  nfs: 
    path: /tmp 
    server: 172.17.0.2 
  persistentVolumeReclaimPolicy: Recycle

**Comment by mrmStack** [comment]
thanks so much!

**Comment by eivantsov** [comment]
@mrmStack you will need more pvs - https://www.eclipse.org/che/docs/openshift-admin-guide.html#storage-overview

**Comment by mrmStack** [comment]
Ok, but how I bind the pv whith the pvc in the template? because I will create in eclipse-che project the pvc, but I dont know how I can binding both. 

thanks regards

**Comment by mrmStack** [comment]
would you mind some example for a deploy like this?

**Comment by eivantsov** [comment]
@mrmStack you just need more PVs and that's it. Once a PVC is created, OpenShift will automatically bind it to a free PV that can satisfy the claim.

**Comment by mrmStack** [comment]
ok!, then...I have to create one pvc for each pv?, or I can create one pv in ReadWriteMany and bind all pvc's in one pv?...because the pvc should create inside the project....I'm wrong??

Che server claims 1GB to store logs and initial workspace stacks. PVC mode is RWO.
Keycloak needs 2 PVCs, 1Gb each to store logs and Keycloak data.
Postgres needs one 1GB PVC to store db.

thanks so much @eivantsov !! I try now your steps!!

**Comment by eivantsov** [comment]
@mrmStack you don't need to create any PVCs. IJust make sure you have at least 5 PVs.

Once Che is deployed, a unique PVC strategy is used by default, which means start of a new workspace will require a new PV.

However, you can reconfigure it - https://www.eclipse.org/che/docs/openshift-admin-guide.html#common-pvc-strategy

**Comment by mrmStack** [comment]
hi @eivantsov , 

first stuff, thanks for alll
I get to run postgres & and keycloak, but che server, doesn't work.  It's the same method that I used to deploy postgres and keyckIoak??, beacuse in the documents of eclipse che I read this... I try but none. 

oc apply -f pvc/che-server-pvc.yaml
oc new-app -f che-server-template.yaml -p ROUTING_SUFFIX=${ROUTING_SUFFIX} -p CHE_MULTIUSER=true
oc set volume dc/che --add -m /data --name=che-data-volume --claim-name=che-data-volume 

thanks  regards

**Comment by eivantsov** [comment]
@mrmStack yes, this is how you deploy Che server. You may check pod logs

**Comment by mrmStack** [comment]
che server is the only doesn't works, is necesary that I must put the flag https if my master have address https:che-astrto.app.es:8443 ??

![image](https://user-images.githubusercontent.com/36670698/40790547-8a5fbe0e-64f5-11e8-9b78-03dbd27135f3.png)

thanks for all!!

**Comment by eivantsov** [comment]
```
oc get pods
oc logs $chepod
```
Or you can go to eclipse che project in https://che-astrto.app.es:8443/, click on Che pod icon, logs tab

**Comment by mrmStack** [comment]
i write a bash script for a request to server and the server response 200 ok to me...but I dont know if I should use the https flag for install eclipse che if my address master server openshift is this:

https://che-astrto.app.es:8443/

bash script:

```
url3="http://keycloak-eclipse-che.apps.openshift.che-astro.pic.es";
url4="http://10.129.0.250:8080/api/system/state";
response=$(curl -s -I -L $url4 | grep HTTP);

status=${response#* };
status=${status:0:3};

if [ "$status" != "200" ]
then
    printf "success!!!,  page seems that's working now!!!\n"
fi
url3="http://keycloak-eclipse-che.apps.openshift.che-astro.pic.es";
url4="http://10.129.0.250:8080/api/system/state";
response=$(curl -s -I -L $url4 | grep HTTP);

status=${response#* };
status=${status:0:3};

if [ "$status" != "200" ]
then
    printf "success!!!,  page seems that's working now!!!\n"
fi
```

**Comment by eivantsov** [comment]
@mrmStack just get Che pod logs:

![image](https://user-images.githubusercontent.com/5337267/40792079-b20da158-6501-11e8-9713-cd75c9f7a185.png)

**Comment by mrmStack** [comment]
I follow this steps:

create che pv:
```

apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-che
spec:
  capacity:
    storage: 1Gi
  accessModes:
  - ReadWriteOnce
  nfs:
    path: /var/lib/openshift_containers/che
    server: che-astro.pic.es
  persistentVolumeReclaimPolicy: Recycle
```
oc apply -f pvc/che-server-pvc.yaml

che-server-pvc.yaml:
```
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: eclipse-che
  name: che-data-volume
spec:
 accessModes:
 - ReadWriteOnce
 resources:
   requests:
     storage: 1Gi
 volumeName: "pv-che"
```


oc new-app -f che-server-template.yaml  -p CHE_MULTIUSER=true

oc set volume dc/che --add -m /data --name=che-data-volume --claim-name=che-data-volume

**Comment by mrmStack** [comment]
I don't acces with graphical ui, because I am working outside the local network cluster...but the logs of the pod are this:
```
--> Scaled older deployment che-1 down
--> Scaling che-2 to 1
error: update acceptor rejected che-2: pods for rc 'eclipse-che/che-2' took longer than 600 seconds to become available
```
the steps that I followed are right?

**Comment by mrmStack** [comment]
Should I modify some fields of che-server template?
---
```
kind: Template
apiVersion: v1
metadata:
  name: che
  annotations:
    description: Che
objects:
- apiVersion: v1
  kind: ServiceAccount
  metadata:
    name: che
- apiVersion: v1
  kind: RoleBinding
  metadata:
    name: che
  roleRef:
    name: admin
  subjects:
  - kind: ServiceAccount
    name: che
- apiVersion: v1
  kind: Service
  metadata:
    name: che-host
  spec:
    ports:
    - name: http
      port: 8080
      protocol: TCP
      targetPort: 8080
    selector:
      app: che
- apiVersion: v1
  kind: Route
  metadata:
    name: che
  spec:
    to:
      kind: Service
      name: che-host
- apiVersion: v1
  kind: DeploymentConfig
  metadata:
    name: che
  spec:
    replicas: 1
    revisionHistoryLimit: 2
    selector:
      app: che
    strategy:
      type: ${STRATEGY}
    template:
      metadata:
        labels:
          app: che
      spec:
        containers:
        - env:
          - name: OPENSHIFT_KUBE_PING_NAMESPACE
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
          - name: NAMESPACE
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
          - name: CHE_MULTIUSER
            value: "${CHE_MULTIUSER}"
          - name: CHE_HOST
            value: "che-${NAMESPACE}.${ROUTING_SUFFIX}"
          - name: CHE_PORT
            value: "8080"
          - name: CHE_API
            value: "${PROTOCOL}://che-${NAMESPACE}.${ROUTING_SUFFIX}/api"
          - name: CHE_WEBSOCKET_ENDPOINT
            value: "${WS_PROTOCOL}://che-${NAMESPACE}.${ROUTING_SUFFIX}/api/websocket"
          - name: CHE_DEBUG_SERVER
            value: "false"
          - name: CHE_INFRASTRUCTURE_ACTIVE
            value: "openshift"
          - name: CHE_INFRA_KUBERNETES_BOOTSTRAPPER_BINARY__URL
            value: "${PROTOCOL}://che-${NAMESPACE}.${ROUTING_SUFFIX}/agent-binaries/linux_amd64/bootstrapper/bootstrapper"
          - name: CHE_INFRA_KUBERNETES_MACHINE__START__TIMEOUT__MIN
            value: "5"
          - name: CHE_INFRA_KUBERNETES_MASTER__URL
            value: "${CHE_INFRA_KUBERNETES_MASTER__URL}"
          - name: CHE_INFRA_KUBERNETES_OAUTH__TOKEN
            value: "${OPENSHIFT_TOKEN}"
          - name: CHE_INFRA_KUBERNETES_USERNAME
            value: "${OPENSHIFT_USERNAME}"
          - name: CHE_INFRA_KUBERNETES_PASSWORD
            value: "${OPENSHIFT_PASSWORD}"
          - name: CHE_INFRA_OPENSHIFT_PROJECT
            value: "${CHE_INFRA_OPENSHIFT_PROJECT}"
          - name: CHE_INFRA_KUBERNETES_PVC_STRATEGY
            value: "${CHE_INFRA_KUBERNETES_PVC_STRATEGY}"
          - name: CHE_INFRA_KUBERNETES_PVC_PRECREATE__SUBPATHS
            value: "${CHE_INFRA_KUBERNETES_PVC_PRECREATE__SUBPATHS}"
          - name: CHE_INFRA_OPENSHIFT_TLS__ENABLED
            value: "${TLS}"
          - name: CHE_INFRA_KUBERNETES_TRUST__CERTS
            value: "${TLS}"
          - name: CHE_LOCAL_CONF_DIR
            value: "/etc/conf"
          - name: CHE_LOGS_DIR
            value: "/var/lib/openshift_containers/logs"
          - name: CHE_LOG_LEVEL
            value: "INFO"
          - name: CHE_KEYCLOAK_AUTH__SERVER__URL
            value: "${CHE_KEYCLOAK_AUTH__SERVER__URL}"
          - name: CHE_INFRA_OPENSHIFT_OAUTH__IDENTITY__PROVIDER
            value: "${CHE_INFRA_OPENSHIFT_OAUTH__IDENTITY__PROVIDER}"
          - name: CHE_OAUTH_GITHUB_CLIENTID
            value: "${CHE_OAUTH_GITHUB_CLIENTID}"
          - name: CHE_OAUTH_GITHUB_CLIENTSECRET
            value: "${CHE_OAUTH_GITHUB_CLIENTSECRET}"
          - name: CHE_PREDEFINED_STACKS_RELOAD__ON__START
            value: 'true'
          - name: JAVA_OPTS
            value: "-XX:MaxRAMFraction=2 -XX:+UseParallelGC -XX:MinHeapFreeRatio=10
              -XX:MaxHeapFreeRatio=20 -XX:GCTimeRatio=4 -XX:AdaptiveSizePolicyWeight=90
              -XX:+UnlockExperimentalVMOptions -XX:+UseCGroupMemoryLimitForHeap -Dsun.zip.disableMemoryMapping=true
              -Xms20m "
          - name: CHE_WORKSPACE_AUTO_START
            value: "false"
          - name: CHE_INFRA_KUBERNETES_PVC_QUANTITY
            value: "${CHE_INFRA_KUBERNETES_PVC_QUANTITY}"
          - name: PROTOCOL
            value: "${PROTOCOL}"
          - name: ROUTING_SUFFIX
            value: "${ROUTING_SUFFIX}"
          image: ${IMAGE_CHE}:${CHE_VERSION}
          imagePullPolicy: "${PULL_POLICY}"
          livenessProbe:
            httpGet:
              path: /api/system/state
              port: 8080
              scheme: HTTP
            initialDelaySeconds: 50
            failureThreshold: 3
            timeoutSeconds: 2
          name: che
          readinessProbe:
            httpGet:
              path: /api/system/state
              port: 8080
              scheme: HTTP
            initialDelaySeconds: 25
            timeoutSeconds: 5
            failureThreshold: 5
          name: che
          ports:
          - containerPort: 8080
            name: http
            protocol: TCP
          - containerPort: 8000
            name: http-debug
          - containerPort: 8888
            name: jgroups-ping
            protocol: TCP
          resources:
            limits:
              memory: 1Gi
            requests:
              memory: 256Mi
          terminationMessagePath: "/dev/termination-log"
          terminationMessagePolicy: File
        restartPolicy: Always
        serviceAccountName: che
        terminationGracePeriodSeconds: 360
    triggers:
    - type: ConfigChange

parameters:
- name: ROUTING_SUFFIX
  displayName: Routing suffix of your OpenShift cluster
  description: This is the suffix appended to routes in your OpenShift cluster <route>-<project>.<routing_suffix>
- name: CHE_VERSION
  displayName: Eclipse Che version
  description: Eclipse Che version which defaults to nightly
  value: nightly
- name: IMAGE_CHE
  displayName: Eclipse Che server image
  description: Che server Docker image. Defaults to docker.io/eclipse/che-server
  value: docker.io/eclipse/che-server
- name: CHE_MULTIUSER
  displayName: Che Multi-user flavor
  description: False i.e. single user by default
  value: 'false'
- name: OPENSHIFT_USERNAME
  displayName: OpenShift Username
  description: OpenShift username that will be used to create workspace objects
- name: OPENSHIFT_PASSWORD
  displayName: OpenShift Password
  description: OpenShift Password that will be used to create workspace objects
- name: OPENSHIFT_TOKEN
  displayName: OpenShift token
  description: OpenShift token to be used to create workspace objects. Must be set if username/password are impossible to use. Do not set if username/pass are provided!
- name: PROTOCOL
  displayName: HTTP protocol
  description: Protocol to be used in Che communications
  value: http
- name: WS_PROTOCOL
  displayName: Websocket protocol
  description: Websocket protocol to be used in Che communications. Defaults to ws. Set to wss only if TLS is true and https protocol is defined
  value: ws
- name: TLS
  displayName: HTTPS support
  description: HTTPS support in Che
  value: 'false'
- name: CHE_INFRA_OPENSHIFT_PROJECT
  displayName: OpenShift namespace to create workspace objects
  description: Che server namespace by default. When empty, each workspace gets own namespace. In this case a privileged sa or credentials/token need to be used.
  value: '${NAMESPACE}'
- name: CHE_INFRA_KUBERNETES_PVC_QUANTITY
  displayName: Default PVC claim
  description: Default PVC claim for storage. Defaults to 1Gi
  value: '1Gi'
- name: CHE_INFRA_KUBERNETES_PVC_STRATEGY
  displayName: PVC strategy
  description: PVC strategy. Unique implies creating PVC per workspace. Common uses one PVC with subpaths in PV. Defaults to unique
  value: 'unique'
- name: CHE_KEYCLOAK_ADMIN_REQUIRE_UPDATE_PASSWORD
  displayName: Admin password update
  description: Force an admin to update password after 1st login. True by default
  value: 'true'
- name: CHE_KEYCLOAK_AUTH__SERVER__URL
  displayName: Identity provider URL
  description: URL of a remote identity provider. Defaults to Keycloak bundled with Che multi user
  value: '${PROTOCOL}://keycloak-${NAMESPACE}.${ROUTING_SUFFIX}/auth'
- name: CHE_INFRA_OPENSHIFT_OAUTH__IDENTITY__PROVIDER
  displayName: Alias of the Openshift identity provider in Keycloak
  description: Alias of the Openshift identity provider registered in Keycloak, that should be used to create workspace OpenShift resources in Openshift namespaces owned by the current Che user.
  value: 'NULL'
- name: STRATEGY
  displayName: Update Strategy
  description: Che server update strategy. Defaults to Recreate. Use Rolling only if Che deployment does not use PVC
  value: 'Recreate'
- name: PULL_POLICY
  displayName: Che server image pull policy
  description: Always pull by default. Can be IfNotPresent
  value: 'Always'
- name: CHE_INFRA_KUBERNETES_MASTER__URL
  displayName: OpenShift master URL
  description: Required only in case of multi-cluster setup. Empty string by default.
  value: ''
- name: CHE_INFRA_KUBERNETES_PVC_PRECREATE__SUBPATHS
  displayName: Pre-create subpaths in PV
  description: Applied only if a common strategy is used. Required for Kubernetes versions before 1.6
  value: 'false'
- name: CHE_OAUTH_GITHUB_CLIENTID
  displayName: GitHub Client ID
  description: GitHub oAuth app client ID. Applicable to Che single user only!
  value: ''
- name: CHE_OAUTH_GITHUB_CLIENTSECRET
  displayName: GitHub Client Secret
  description: GitHub oAuth app client servet. Applicable to Che single user only!
  value: ''
labels:
  app: che
  template: che
 
```
