### ISSUE TITLE
Failed to connect to AWS ECR due to missing auth credentials (Workspace Build)

### ISSUE THREAD

**Issue by abargnesi** [eclipse-che/che#9919]
### Description

I am running Eclipse Che in Single User mode on Docker:

```
docker run -it --rm -v /var/run/docker.sock:/var/run/docker.sock -v /home/vagrant/che-root:/data eclipse/che start
```

I have edited `/home/vagrant/che-root/che.env` to include AWS ECR config:

```
CHE_DOCKER_REGISTRY_AWS_REGISTRY1_ID=xxxxxxxxxxx
CHE_DOCKER_REGISTRY_AWS_REGISTRY1_REGION=us-east-1
CHE_DOCKER_REGISTRY_AWS_REGISTRY1_ACCESS__KEY__ID=xxxxxxxxxx
CHE_DOCKER_REGISTRY_AWS_REGISTRY1_SECRET__ACCESS__KEY=xxxxxxxxxx
```

Then I configure a simple docker-compose recipe with:

```
version: '3.2'
services:
 db:
  image: xxxxxxxxxxxxxx.dkr.ecr.us-east-1.amazonaws.com/db
  command: '-c max_connections=200'
```

When I create workspace using this stack I receive:

```
Could not start workspace postgres-workspace. Reason: Can't create machine from image. Cause: Error response from docker API, status: 500, message: Get https://xxxxxxxxxxx.dkr.ecr.us-east-1.amazonaws.com/v2/db/manifests/latest: no basic auth credentials
````

**OS and version:**    

Ubuntu 18.04 LTS

Eclipse Che 6.5.2: Single User mode on Docker
