### ISSUE TITLE
Terminal disconnect when another workspace is starting or stopping on kubernetes

### ISSUE THREAD

**Issue by liyanliang1994** [eclipse-che/che#9943]
### Description
I try to start several workspaces and the terminal doesn't work sometimes.
### Reproduction Steps
After a workspace started, I try to start another one, and when it's starting, the terminal in the previous workspace doesn't work and can't reconnect again unless I start a new terminal. This also happens when another workspace is stopping.
**OS and version:**    
che 6.6.0
kubernetes 1.9.2
nginx-ingress-controller 0.15.0
**Diagnostics:** 
![default](https://user-images.githubusercontent.com/39881038/40988059-b9c37430-691c-11e8-858e-0e2ef965a807.png)

**Comment by liyanliang1994** [comment]
I guess the problem is caused by the nginx-ingress. When a workspace starting, new ingresses is generated and the nginx will reload, which breaks the websoket.

**Comment by eivantsov** [comment]
@liyanliang1994 you are most probably right. However, the IDE should reconnect

@sleshchenko can this be caused by nginx reload?

**Comment by sleshchenko** [comment]
@eivantsov I think that the reason is nginx reload. I've described it here https://github.com/eclipse/che/issues/8675#issue-295470083

**Comment by liyanliang1994** [comment]
@sleshchenko #8675 solved the bug of websocket in dashboard. But the terminal is a websocket in ide.
![20180608105157](https://user-images.githubusercontent.com/39881038/41136896-fa1713bc-6b0a-11e8-99ad-3ac5367211b7.png)

**Comment by sleshchenko** [comment]
@liyanliang1994 Well, when I shared this issue I just wanted to point to a description of WebSocket and nginx issue. 
So, as far as I see IDE reconnects to terminal WebSocket endpoint when a connection is lost. It tries to reconnect 2 times each 2 seconds.
@vparfonov Am I right? Could you take a look at this issue maybe terminal in IDE can be improved and reconnection can be fixed in such cases?

@liyanliang1994 But still it can be a quite annoying issue that all clients lose WebSocket connections when each workspace start/stop. You can try to fix it for you by using another Ingress Backend, like traefik.

**Comment by liubin10** [comment]
@sleshchenko I found that if socket is closed or some error occurred, terminal send method can still be triggered. I think some check should be added before sending data through Websocket.

**Comment by AndrienkoAleksandr** [comment]
About reconnection: we need improve this stuff. Because on reconnection terminal-agent server side create new one  terminal process instead of connection to the previous one. So seems it's issue about improve terminal agent server side api and adaptation client side to the impoved api.

**Comment by liyanliang1994** [comment]
Thanks for your reply.
@sleshchenko I try to replace nginx with traefik. Che create ingresses and service for workspace successsfully, but pod is not created. Is there anything I forget to configure?

traefik deployment
```
apiVersion: v1
kind: Deployment
apiVersion: extensions/v1beta1
metadata:
  name: traefik-ingress-controller
  namespace: kube-system
  labels:
    k8s-app: traefik-ingress-lb
spec:
  replicas: 1
  selector:
    matchLabels:
      k8s-app: traefik-ingress-lb
  template:
    metadata:
      labels:
        k8s-app: traefik-ingress-lb
        name: traefik-ingress-lb
    spec:
      terminationGracePeriodSeconds: 60
      containers:
      - image: traefik
        name: traefik-ingress-lb
        ports:
        - name: http
          containerPort: 80
          hostport: 80
          protocol: TCP
        args:
        - --api
        - --kubernetes
        - --logLevel=INFO
```

configmap
`CHE_INFRA_KUBERNETES_INGRESS_ANNOTATIONS__JSON: '{"kubernetes.io/ingress.class": "traefik", "traefik.ingress.kubernetes.io/rewrite-target": "/","traefik.ingress.kubernetes.io/ssl-redirect": "false","traefik.ingress.kubernetes.io/proxy-connect-timeout": "3600","traefik.ingress.kubernetes.io/proxy-read-timeout": "3600"}'`

che-ingress
```
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: che-ingress
  annotations:
    kubernetes.io/ingress.class: "traefik"
    traefik.ingress.kubernetes.io/proxy-read-timeout: "3600"
    traefik.ingress.kubernetes.io/proxy-connect-timeout: "3600"
    traefik.ingress.kubernetes.io/ssl-redirect: "false"
spec:
  rules:
  - host: <domain>
    http:
      paths:
      - path: /
        backend:
          serviceName: che-host
          servicePort: 8080
```
